### ISSUE TITLE
Detected non-PlatformIO `monitor_baud` option

### ISSUE THREAD

**Issue by universam1** [platformio/platformio-core#1001]
What kind of issue is this?

- [x ] PlatformIO Core. If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: W10 x64

**PlatformIO Version** (`platformio --version`):
3.4.0

### Description of problem
`monitor_baud` is not working, I also get a warning.

#### Steps to Reproduce

ESP8266 Arduino, also with staging version

try this platformio.ini

```
[platformio]
env_default = main
lib_dir = asd\lib
src_dir = asd\src

[env:main]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_baud = 115200
upload_speed = 921600
lib_deps = ArduinoJson, ESPAsyncTCP, ESPAsyncWebServer
```

### Actual Results

Detected non-PlatformIO `monitor_baud` option in `[env:main]` section

**Comment by ivankravets** [comment]
It should be fixed before. Could you re-test with http://docs.platformio.org/en/latest/installation.html#development-version ?
