### ISSUE TITLE
Provide an option to run without project?

### ISSUE THREAD

**Issue by ChillarAnand** [platformio/platformio-core#1008]
What kind of issue is this?

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.
------------------------------------------------------------------

### Description of problem

For small experiments, creating a single file and uploading it will be sufficient. To use platformio in such cases, it becomes too much work as we have to create seperate project for every experiment. 

### Additional info

One solution is to allow `run` command to optionally take a file name and board and upload it.

**Comment by ivankravets** [comment]
You can use `pio ci` command for this case http://docs.platformio.org/en/latest/userguide/cmd_ci.html
