### ISSUE TITLE
printf("%f", float) crashes teensy 3.2

### ISSUE THREAD

**Issue by pljakobs** [platformio/platformio-core#1015]
```
float a=3.1415;
int   b=7;
void setup() {
  Serial.begin(9600);
  delay(5000);
  Serial.println("start");
  for(int i=0;i<50;i++){
    Serial.print(".");
    delay(100);
  }
  Serial.println();

  Serial.printf("float a: %f\n",a);
  Serial.printf("int   b: %i\n",b);
  Serial.printf("float b: %f\n",(float)b);
}

void loop() {
  // put your main code here, to run repeatedly:

}
```
works fine in Arduino with Teensyduino
on Atom/PlatformIO:

> 
> start
> ..................................................float a:
> ␀at b:
> ␀�==1=�*X���y!e>�␖3�eU�K�[eE^��/$t��"��v�M�␏␔#�s�/␆␆|�4>����]M�mH�}&+آ�
> ��ɪoQ�/␂ev␒4␐j*␄@,"I^�g␑�␁9␜H`�&�K��O��k��V� pd8er ��*␌�Ј|�T�␐��S���c␔r�׆�t�里aS��!X,�Լ����
> ���` �$ύ�␆��딧� }C␕�a␅JjY�"P75�\�␀�␌��␄�␒␕hF8�␐��{���Z�Nr/��]�m����4CΜO�qR*␔    %ެ�␋
> ��A��S��0�i%S␗␀␀␀␀���␟␀␀␀␀���␟␀␀␀␀␁␕␀␀␀␀␀␀␄␀␀␀� ␇@�␋␀␀␀␀␀␀���␟�,␀␀␁␀␀␀s�␀␀␀␀␀␀␀␀␀␀␀␀␀␀␀␀␀
> ␀␀␀␀␀␀␀␀����

**Comment by valeros** [comment]
Hi @pljakobs !
Please move this issue to the appropriate [repository](https://github.com/platformio/platform-teensy) and specify your OS.
Thanks!
