### ISSUE TITLE
Add board Elektor Uno R4 with ATMega328PB 

### ISSUE THREAD

**Issue by elektor-labs** [platformio/platformio-core#1016]
https://www.elektormagazine.com/labs/elektorino-uno-r4-150790
https://www.elektor.com/elektor-uno-r4

Name: Elektor Uno R4
Platform: Atmel AVR
Frameworks: Arduino
MCU: ATmega328PB
Debug: 
Frequency: 16 MHz
RAM: 2 kB
Flash: 31.5 kB

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-atmelavr/issues
