### ISSUE TITLE
error building project:  multiple definition

### ISSUE THREAD

**Issue by itamar244** [platformio/platformio-core#1018]
What kind of issue is this?

- [x] PlatformIO Core. If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: elementary OS 0.4.1 Loki (Linux based on Ubuntu 16.04.2 LTS)

**PlatformIO Version**: 3.5.0a4

### Description of problem
When i build the project a compilation error is raised about multiple definitions.
Probably it copies accidentally the source of the file twice. include guardsd don't 

#### Steps to Reproduce

1. install platformio-ide on atom
2. create project for arduino uno
3. copy the files i listed
4. build

### Actual Results
Looking for dependencies...
No dependencies
Linking .pioenvs/uno/firmware.elf
.pioenvs/uno/src/sum.o (symbol from plugin): In function `sum(int, int)':
(.text+0x0): multiple definition of `sum(int, int)'
.pioenvs/uno/src/main.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
*** [.pioenvs/uno/firmware.elf] Error 1
=========================================================== [ERROR] Took 0.72 seconds ===========================================================
arduino@itamars:~/Documents/coding/arduino-test1$

### Expected Results
Should build fine.

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
```

**Source file to reproduce issue:**
main.cpp
```cpp
#include "Arduino.h"
#include "sum.cpp"

void setup() {
  Serial.println(sum(4, 5));
}
void loop() {}
```

sum.cpp
```cpp
int sum(int a, int b) {
  return a + b;
}
```

**Comment by ivankravets** [comment]
main.cpp
```c
#include "Arduino.h"
#include "sum.h"

void setup() {
  Serial.println(sum(4, 5));
}
void loop() {}
```

sum.h
```
int sum(int a, int b);
```

sum.cpp
```
int sum(int a, int b) {
  return a + b;
}
```

**Comment by itamar244** [comment]
thanks
