### ISSUE TITLE
pio lib -g uininstall removes source code

### ISSUE THREAD

**Issue by g3rb3n** [platformio/platformio-core#1023]
To reproduce this behavior:

mkdir TheLib
mkdir TheLib/src
touch TheLib/src/TheLib.h
touch TheLib/src/TheLib.cpp
touch TheLib/platformio.ini
cd TheLib
pio run
cd ..
pio lib -g install ./TheLib
pio lib -g uninstall TheLib

I would expect my source code to still be under ~/git/TheLib and ~/.platformio/lib/TheLib removed.
But at this stage the source folder ~/git/TheLib is deleted by pio and ~/.platformio/lib/TheLib still exists.

Doing a second
pio lib -g uninstall TheLib
Removes ~/.platformio/lib/TheLib

See: [Discussion](https://community.platformio.org/t/pio-lib-g-uninstall-removes-source-code/2411)

**Comment by ivankravets** [comment]
Thanks, fixed!
