### ISSUE TITLE
[Board]RTOS Thread not work on LPC1768

### ISSUE THREAD

**Issue by 32duino** [platformio/platformio-core#1024]
rtos thread not work on LPC1768 board.  but same code work fine on stm32f103rb and FRDM K64F 

### Configuration
**Win 7 64bit operate system**:

**PlatformIO Version**:
Atom + PlatformIO IDE 2.0.0-beta.8  Core 3.5.0.a4

**The content of `platformio.ini`:**
[env:lpc1768]
platform = nxplpc
board = lpc1768
framework = mbed
build_flags = -Wall -lc -DPIO_FRAMEWORK_MBED_RTOS_PRESENT

**Source file to reproduce issue:**
#include "mbed.h"
#include "rtos.h"
 
DigitalOut led1(LED1);
DigitalOut led2(LED2);
Thread thread;
 
void led2_thread() {
    while (true) {
        led2 = !led2;
        Thread::wait(1000);
    }
}
 
int main() {
    thread.start(led2_thread);
    
    while (true) {
        led1 = !led1;
        Thread::wait(500);
    }
}

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-nxplpc/issues
