### ISSUE TITLE
Ongoing Crashes after update

### ISSUE THREAD

**Issue by fah** [platformio/platformio-core#1026]
Atom & Platformio is not usable anymore.
After an upgrade a few minutes ago it crashes every 2-5 minutes.

------------------------------

Process:               Atom Helper [16341]
Path:                  /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/Atom Helper
Identifier:            com.github.atom.helper
Version:               1.19.3 (1.19.3)
Code Type:             X86-64 (Native)
Parent Process:        Atom [15582]
Responsible:           Atom [15582]
User ID:               501

Date/Time:             2017-08-25 18:29:00
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12

Time Awake Since Boot: 100000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

...

Thread 11:
0   libsystem_kernel.dylib        	0x00007fffacb19d96 kevent + 10
1   pathwatcher.node              	0x0000000116887acf PlatformThread() + 76
2   libsystem_pthread.dylib       	0x00007fffacc0393b _pthread_body + 180
3   libsystem_pthread.dylib       	0x00007fffacc03887 _pthread_start + 286
4   libsystem_pthread.dylib       	0x00007fffacc0308d thread_start + 13

...

  0x7fffacbf7000 -     0x7fffacbfffe7  libsystem_platform.dylib (126.50.8) <897462FD-B318-321B-A554-E61982630F7E> /usr/lib/system/libsystem_platform.dylib

**Comment by ivankravets** [comment]
Please report to https://github.com/atom/atom/issues
