### ISSUE TITLE
add --save flag to pio lib install

### ISSUE THREAD

**Issue by jhoogeboom** [platformio/platformio-core#1028]
feature request:

When installing a new library with `pio lib install` it would be useful to have the option to add it to the dependency-list in the `platformio.ini` file. Similar to npm if you are familiar with that, using a --save flag.

**Comment by paulhayes** [comment]
+1 for this feature.

**Comment by ofiratt** [comment]
Must have feature

**Comment by ivankravets** [comment]
Please re-test with the latest development version of PlatformIO Core => https://docs.platformio.org/en/latest/installation.html#development-version

Or, open via CLI => `pio upgrade --dev`.
