### ISSUE TITLE
Ability to "star" any folder and see it in file explorer "Places" section

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#1033]
# Project Wizard

- [x] PIO Home -> Clone function for projects would be nice. ( @sstaub )
- [x] Ability to "star" any folder and see it in file explorer "Places" section.  ( @sstaub )

**Comment by neilmendoza** [comment]
The new file browser for "non-default location" project creation is super clunky. Any reason for not using the system file browser?

**Comment by ivankravets** [comment]
@neilmendoza you can share PIO Home with other developers within a local network. Also, remote access to PIO Home is coming soon. PIO Home could be started on a server and used from other machines.

Nevertheless, we will improve current FileExplorer with new features, such as an ability to mark a folder as a favourite, create a new or rename existing.

**Comment by ivankravets** [comment]
File Explorer has been refactored in 3.5.0rc5. Please `pio upgrade`.

**Comment by ivankravets** [comment]
Implemented in PIO Home 0.5.0. Please update
