### ISSUE TITLE
Support NRF52840

### ISSUE THREAD

**Issue by samuelint** [platformio/platformio-core#1036]
What kind of issue is this?

- [X] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-
------------------------------------------------------------------

Support for the new NRF-52840 board would be really great!

**Comment by ivankravets** [comment]
Please move feature request to https://github.com/platformio/platform-nordicnrf52/issues
