### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by OdinsHat** [platformio/platformio-core#1037]
PIO Core Call Error: got stderr: 'sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\n'

**Comment by ivankravets** [comment]
What is your OS? If Linux, could you try these?
```
sudo locale-gen en_US.UTF-8
sudo update-locale 
```

Maybe, restart machine.

**Comment by ivankravets** [comment]
Fixed in the latest release of our IDEs. Please update
