### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by mdanetzky** [platformio/platformio-core#1038]
PIO Core Call Error: got stderr: 'From https://github.com/esp8266/Arduino\n   ba0e049..fe6f3cc  master     -> origin/master\n'

**Comment by tedder** [comment]
Here too.
```PIO Core Call Error: got stderr: 'From https://github.com/espressif/arduino-esp32\n   29a253a..79ee46e  master     -> origin/master\n'```

**Comment by ivankravets** [comment]
Fixed in PIO Core+ 0.10.10. Please run in PIO IDE Terminal `pio update` and restart IDE.
