### ISSUE TITLE
Home: Could not list directory/home/techtaiwa

### ISSUE THREAD

**Issue by TechTaiwa** [platformio/platformio-core#1042]
Could not list directory by `/home/techtaiwa`

**Comment by ivankravets** [comment]
Please open system terminal and provide an output of 
```
ls -al /home/techtaiwa
```

**Comment by ivankravets** [comment]
Thanks a lot! Fixed in https://github.com/platformio/platformio-node-helpers/releases/tag/v0.2.4

For Atom: just uninstall `platformio-ide` package and install again. It will use the new updated helpers.
For VSCode: update our `platformio-ide` extension to 0.7.3.
