### ISSUE TITLE
Missing BSP: Adafruit WICED feather STM32F205 120MHz

### ISSUE THREAD

**Issue by nekropolit** [platformio/platformio-core#1046]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [x] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Windows 10**:

**PlatformIO Version** (`platformio --version`):
Home 0.2.5·Core 3.5.0a9-0.7.2. Extension
### Description of problem
Missing Board: Adafruit WICED feather STM32F205 120MHz

**Comment by ivankravets** [comment]
Please open new issue at https://github.com/platformio/platform-ststm32/issues
