### ISSUE TITLE
Home: Could not list directory/home/efischer

### ISSUE THREAD

**Issue by feugen** [platformio/platformio-core#1048]
Could not list directory by `/home/efischer`

Hello guys, fresh install of atom and platformio. Home 0.2.5·Core 3.5.0a9

Problem 1: I cant select a custom directory and get an error when I try to open home directory : "Could not list directory by `/home/xyz`". Its not a permission problem, I checked it and the permission is set correctly.

Problem 2: If I try to start a new project, the default project directory is not localized, so it creates a "documents" directory instead of using german "Dokumente" directory, but it is at least able to create the folder. 

Edit: ls -al /home/efischer gives me:

drwxr-xr-x  8 efischer efischer   4096 Sep  8 04:24 .atom
drwxr-xr-x  7 efischer efischer   4096 Sep  8 04:39 .platformio

**Comment by ivankravets** [comment]
Is it a real error with `/home/xyz`?

**Comment by feugen** [comment]
No, it says `/home/efischer` and its my home folder

**Comment by ivankravets** [comment]
What is your locale?

**Comment by feugen** [comment]
```
LANG=de_DE.utf8
LANGUAGE=
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
```

**Comment by ivankravets** [comment]
Which IDE do you use?

**Comment by ivankravets** [comment]
Please try to open system terminal (not terminal from IDE) and type:
```
~/.platformio/penv/bin/platformio home
```

It should open PIO Home in browser. Does it work?

**Comment by feugen** [comment]
I am using Atom 1.19.7
I have tried `~/.platformio/penv/bin/platformio home` and it opens in browser tab (address http://127.0.0.1:8008/). I am now able to browse my home directory and I have successfully created a new project. It looks like Atom is able to open this project.

**Comment by ivankravets** [comment]
Thanks a lot! Fixed in https://github.com/platformio/platformio-node-helpers/releases/tag/v0.2.4

For Atom: just uninstall `platformio-ide` package and install again. It will use the new updated helpers.
For VSCode: update our `platformio-ide` extension to 0.7.3.

**Comment by feugen** [comment]
Thanks, it works now. :-)

**Comment by ivankravets** [comment]
Would be thankful for a  star ⭐️ https://github.com/platformio/platformio-core/stargazers 😊 

Happy coding with PlatformIO!

**Comment by feugen** [comment]
No problem, I am following now :-)
