### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by domingosliraneto** [platformio/platformio-core#1060]
PIO Core Call Error: got stderr: "sh: module: line 1: syntax error: unexpected end of file\nsh: error importing function definition for `module'\nsh: scl: line 1: syntax error: unexpected end of file\nsh: error importing function definition for `scl'\n"

**Comment by ivankravets** [comment]
What is your OS?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1054
