### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by jeremybuisson** [platformio/platformio-core#1063]
Server error

Same as in issue #1062, but leave "Use default location" ticked. Click finish. and... tada!
No other information appears in Code's window.

**Comment by ivankravets** [comment]
Could you open PIO IDE Terminal and type
```
pio upgrade
pio update
```
Restart IDE.

Does it work now?

**Comment by candidoneto89** [comment]
Having the same issue. I have folders with non-ascii characters too. Tried what was suggested and still facing this problem.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1062
