### ISSUE TITLE
Prevent repeat installation of identical libraries via git vs library registry

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#1064]
Feature Request  (bug?)
------------------------------------------------------------------

### Configuration

**Operating system**:  Windows 7, Atom 1.19.7x64

**PlatformIO Version** (`platformio --version`): 3.5.0a9

### Description of problem
The same library will be installed twice if it is called in different ways by the pio lib install command or within a library dependency list.  (ie, one lists the github url and another lists the library id number)

#### Steps to Reproduce

1.  pio lib install https://github.com/PaulStoffregen/AltSoftSerial.git
2.  pio lib install AltSoftSerial

### Actual Results
Two nearly identical copies of AltSoftSerial are now installed in .piolibdeps, one in the folder "AltSoftSerial" and one in the folder "AltSoftSerial_ID73."  The version installed from the git repository is tied to the latest git commit, the version installed from the library registry is tied to the version number within the library.json (and the git release number).  Both versions seem to be compiled and then the linker decides which version it wants to use.  If the versions are not identical, there may be compiling issues or just weird results in the final progam.

### Expected Results
The library manager detects that there are two libraries with the same name and asks which version you truly want and removes the other.

### Additional info
It's fairly easy to avoid double-installing libraries when installing them manually, but the same thing happens when the library manager automatically installs dependencies.  So if the library.json of one library lists a git repository as a dependency and another lists the same library by its registry name/number, the library manager will continually reinstall both libraries.  Even if you attempt to uninstall one version manually, it will automatically be re-installed the next build or clean.

**Comment by ivankravets** [comment]
PlatformIO allows libraries with the same names. There are a lot of libraries with the same name but different compatibility options.

**Comment by SRGDamia1** [comment]
In the case of two libraries with the same name, how do I know/control which is being used?

**Comment by ivankravets** [comment]
Do you want to install both libraries for the same project and use them for different environemnts?

**Comment by SRGDamia1** [comment]
No, I only want one of them, I would like to uninstall the other.  They just keep reinstalling because of the different ways they're listed as dependencies.

**Comment by ivankravets** [comment]
Please remove library from `.piolibdeps` and add 1 record to 
```
[env:...]
lib_deps = https://github.com/PaulStoffregen/AltSoftSerial.git
```
