### ISSUE TITLE
Project home has strange display list

### ISSUE THREAD

**Issue by mrnarong** [platformio/platformio-core#1066]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ #] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
![image](https://user-images.githubusercontent.com/31098401/30356471-7147af58-9863-11e7-9af6-95907219b71b.png)

**PlatformIO Version** (`platformio --version`):

### Description of problem

Strange sumarize home display:

![image](https://user-images.githubusercontent.com/31098401/30356516-a1f0da58-9863-11e7-9463-22f6c3d51b13.png)

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
Fixed. Please open PIO IDE Terminal and type 
```
pio upgrade
pio update
```

Now, please restart IDE.

**Comment by mrnarong** [comment]
Exellence!
