### ISSUE TITLE
Home: Could not load installed platforms

### ISSUE THREAD

**Issue by thosoo** [platformio/platformio-core#1070]
PIO Core Call Error: got stderr: "sh: module: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.\nsh: Fehler beim Importieren der Funktionsdefinition f\xc3\xbcr `module'.\nsh: scl: Zeile 1: Syntax Fehler: Unerwartetes Dateiende.\nsh: Fehler beim Importieren der Funktionsdefinition f\xc3\xbcr `scl'.\n"

**Comment by thosoo** [comment]
Running fedora26 everything freshly installed

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1054
