### ISSUE TITLE
PlatformIO does not support Pumbaa on ESP32 Devkit, although Pumbaa says they do support it.

### ISSUE THREAD

**Issue by MrDadaGuy** [platformio/platformio-core#1077]
`
[Tue Sep 19 10:24:49 2017] Processing esp32dev (platform: espressif32; board: esp32dev; framework: pumbaa)
--------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Error: This board doesn't support pumbaa framework!
======================================================== [ERROR] Took 0.48 seconds ========================================================
The terminal process terminated with exit code: 1`

Here is the information on Pumbaa site:

http://pumbaa.readthedocs.io/en/latest/boards/esp32_devkitc.html

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif32/issues
