### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by ronguest** [platformio/platformio-core#1085]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "/Users/ronaldg/Documents/PlatformIO/Projects/170907-144124-huzzah/~/Documents/Arduino/libraries" does not exist.

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system

**Comment by ivankravets** [comment]
Thanks! Fixed. Please run `pio update` in PIO IDE Terminal and restart IDE
