### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by exothink** [platformio/platformio-core#1086]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "C:\Users\je\Documents\PlatformIO\Projects\_4sqBase111216\~\Documents\Arduino\libraries" does not exist.

**Comment by exothink** [comment]
Using PIO Home to update the libraries.  It appears that it is appending the library path to the current project path instead of just using the library path.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1085
