### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by marbalon** [platformio/platformio-core#1095]
Can't load any project. No matter if it is existing one or new.

**Comment by ivankravets** [comment]
Could you open PIO IDE Terminal and type
```
pio home
```

Do you see any errors?

**Comment by pratikguru** [comment]
hey, the when you use pio on the terminal it say pio command not found?
is it supposed to be installed?

**Comment by ivankravets** [comment]
What is your OS?

**Comment by marbalon** [comment]
My OS is Windows 7 64bit.
`
pio home
PlatformIO Plus (https://pioplus.com) v0.10.11
`
No errors, just open default webbrowser with pio home screen.


But today it is working fine. Maybe PC restart helps like always...

**Comment by ivankravets** [comment]
Do any items work? Libraries? Boards? Platforms?

**Comment by marbalon** [comment]
Now everythig seems to work.

03.10.2017 1:29 PM "Ivan Kravets" <notifications@github.com> napisał(a):

**Comment by ivankravets** [comment]
Thanks!
