### ISSUE TITLE
Remote Serial Connection

### ISSUE THREAD

**Issue by phhoef** [platformio/platformio-core#1101]
It would be nice to have a remote serial connection to send some serial commands to the remote device.
So, I do not want to flash the firmware, but send some serial commands to a remote device.
I am using a small Python script using pySerial to configure the device. It would be great if I could run such scripts from remote.

**Comment by phhoef** [comment]
Any news on that :-)?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2228
