### ISSUE TITLE
Home: Could not list directoryC:\Users\Victor\My Documents

### ISSUE THREAD

**Issue by rkit1** [platformio/platformio-core#1105]
Could not list directory by `C:\Users\Victor\My Documents`

**Comment by rkit1** [comment]
Directory selection dialog is pretty much unusable.

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio home
```

Now, it should be opened in your browser. Do you see any errors in a console?

**Comment by rkit1** [comment]
Nothing in console. Directory selection dialog fails on directory names that contain spaces.
![default](https://user-images.githubusercontent.com/4385053/31695620-72b425b2-b3b4-11e7-9e92-faa5c6ab69c4.png)

**Comment by ivankravets** [comment]
Thanks for the report!

Please open PIO IDE Terminal and type `pio upgrade`. It should be fixed in 3.5.0b1. Don't forget to restart IDE.
