### ISSUE TITLE
Home: Could not list directoryC:\Users\giuse\SendTo

### ISSUE THREAD

**Issue by Lettly** [platformio/platformio-core#1106]
Could not list directory by `C:\Users\giuse\SendTo`

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio home
```

Now, it should be opened in your browser. Do you see any errors in a console?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1105
