### ISSUE TITLE
Please support Wio Node board

### ISSUE THREAD

**Issue by yozzozo** [platformio/platformio-core#1109]
https://www.seeedstudio.com/Wio-Node-p-2637.html

**Comment by ivankravets** [comment]
Could you test this board with `esp_wroom_02` board profile? 

See http://wiki.seeed.cc/Wio_Node/

> CE/FCC/TELEC Certified for core module ESP-WROOM-02

If it works, we will add separate profile for Wio Node

**Comment by yozzozo** [comment]
Hi,

I’ve tested this board using that esp_wroom_02 profile and it seems to work great!  Thank you!
It would be nice to have a separate profile for the Wio Node (and Wio Link, separate product) as you mentioned.

**Comment by ivankravets** [comment]
Added in https://github.com/platformio/platform-espressif8266/commit/fa3cbbee36565f5ea873586682f12f53a1ac1f18
