### ISSUE TITLE
Please support Seeeduino board

### ISSUE THREAD

**Issue by yozzozo** [platformio/platformio-core#1110]
https://www.seeedstudio.com/Seeeduino-V4.2-p-2517.html

**Comment by ivankravets** [comment]
Please connect this board, open PlatformIO IDE Terminal and type
```
pio device list
```

Please provide an output here.

**Comment by yozzozo** [comment]
Hardware ID: USB VID:PID=2886:0004 SER=85438333036351103282 LOCATION=20-5
Description: Seeeduino v4

**Comment by ivankravets** [comment]
Added in https://github.com/platformio/platform-atmelavr/commit/950cac12a83a38403dd0c18287cf65da06368a28
