### ISSUE TITLE
Support for Ameba Arduino: [RTL8195] [RTL8710]

### ISSUE THREAD

**Issue by ebergmundur** [platformio/platformio-core#1119]
What kind of issue is this?

- [X] PlatformIO Core. If you’ve found a bug, please provide an information below.

Support for Ameba Arduino: [RTL8195] [RTL8710] would be much appreciated 

https://www.amebaiot.com/en/ameba-sdk-boards/

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/769
