### ISSUE TITLE
esp32 esp-idf framework libs missing

### ISSUE THREAD

**Issue by Strelok2** [platformio/platformio-core#1121]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ x ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 7

**PlatformIO Version** (`platformio --version`): 3.5.0a16

### Description of problem
When trying to build the following example with atom + paltformio + esp-idf framework:
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/adc
it says the esp_adc_calc lib is missing. When i compare the components folder with the manualy downloaded framework there are few folders missing. 
![image](https://user-images.githubusercontent.com/32818557/31586800-c0cc9bba-b1d6-11e7-8577-07ae586c3889.png)
If i mannualy copy the files of the downloaded framwork it produces a different error:
Two environments with different actions were specified for the same target: C:\Users\Strelok\Documents\PlatformIO\Projects\171013-124206-esp32dev\.pioenvs\esp32dev\app_trace\app_trace.o
(action 1: xtensa-esp32-elf-gcc -o app_trace.o -c -Wno-old-style-declaration -std=gnu99 -Wall -Werror=all -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-error=un
used-function -Og -g3 -nostdlib -Wpointer-arith -Wno-error=unused-but-set-variable -Wno-error=unused-variable -mlongcalls -ffunction-sections -fdata-sections -fstrict-volatile-bitfields $(subst --covera
ge,,$(CFLAGS)) -DWITH_POSIX -DIDF_VER=\"2.210.0\" -DESP32 -DESP_PLATFORM -DF_CPU=240000000L -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DPLATFORMIO=30500 -DESP32_DEV -DARDUINO_ESP32_
DEV @"C:\Users\Strelok\Documents\PlatformIO\Projects\171013-124206-esp32dev\.pioenvs\esp32dev\longcmd-34749ca1e74b0c2915631cab35b9815d" app_trace.c)
(action 2: xtensa-esp32-elf-gcc -o app_trace.o -c -Wno-old-style-declaration -std=gnu99 -Wall -Werror=all -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-error=un
used-function -Og -g3 -nostdlib -Wpointer-arith -Wno-error=unused-but-set-variable -Wno-error=unused-variable -mlongcalls -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -DWITH_POSIX -DI
DF_VER=\"2.210.0\" -DESP32 -DESP_PLATFORM -DF_CPU=240000000L -DHAVE_CONFIG_H -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DPLATFORMIO=30500 -DESP32_DEV -DARDUINO_ESP32_DEV @"C:\Users\Strelok\Document
s\PlatformIO\Projects\171013-124206-esp32dev\.pioenvs\esp32dev\longcmd-34749ca1e74b0c2915631cab35b9815d" app_trace.c)
File "C:\Users\Strelok\.platformio\penv\lib\site-packages\platformio\builder\tools\platformio.py", line 272, in BuildLibrary

I am looking forward for your answer :)

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-espressif32/issues
