### ISSUE TITLE
Undefined reference to `__wrap_main' / undefined reference to `rtos::Thread::wait(unsigned long)'

### ISSUE THREAD

**Issue by FusedShadowX** [platformio/platformio-core#1127]
### Configuration

**Operating system**: mbed-os

**PlatformIO Version** (`platformio --version`): latest

### Description of problem
> Linking .pioenvs\frdm_k64f\firmware.elf
c:/users/fusedshadowx/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/lib/thumb/v7e-m/fp
v4-sp/softfp/crt0.o: In function `_start':
(.text+0x4a): undefined reference to `__wrap_main'
.pioenvs/frdm_k64f/FrameworkMbedCore/platform/mbed_wait_api_rtos.o: In function `wait_us':
mbed_wait_api_rtos.cpp:(.text.wait_us+0x2a): undefined reference to `rtos::Thread::wait(unsigned long)'
collect2.exe: error: ld returned 1 exit status
*** [.pioenvs\frdm_k64f\firmware.elf] Error 1

The above error shows on build. I didn't change anything important since the last succesful build, but after inserting a header file, this error shows.

#### Steps to Reproduce

1. Build project.

### Actual Results
Build fails.

### Expected Results
Based on flags, project should be build succesfully.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:frdm_k64f]
platform = freescalekinetis
board = frdm_k64f
framework = mbed
build_flags = -Wl,--wrap,main -D PIO_FRAMEWORK_MBED_RTOS_PRESENT -D PIO_FRAMEWORK_MBED_EVENTS_PRESENT
```

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-freescalekinetis/issues
