### ISSUE TITLE
Home: Platforms: Frameworks

### ISSUE THREAD

**Issue by cain52** [platformio/platformio-core#1129]
PIO Core Call Error: Extra data: line 3 column 1 - line 5 column 66 (char 6336 - 6535)

**Comment by ivankravets** [comment]
How to reproduce that?

**Comment by ivankravets** [comment]
Thanks for the report!

Please open PIO IDE Terminal and type `pio upgrade`. It should be fixed in 3.5.0b1. Don't forget to restart IDE.
