### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by miguelpom** [platformio/platformio-core#1137]
PIO Core Call Error: Library Storage: C:\Users\casfid\.platformio\lib
Updating ESP8266wifi                     @ 90e280d096     [cc03db7dad]

Uninstalling ESP8266wifi @ 90e280d096: 	[OK]
Looking for ESP8266wifi library in registry

Error: Library `ESP8266wifi` has not been found in PlatformIO Registry.
You can ignore this message, if `ESP8266wifi` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
How did you install ESP8266wifi library?

**Comment by ivankravets** [comment]
Please reopen if you still need help
