### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by ddjikic** [platformio/platformio-core#1139]
PIO Core Call Error: Library Storage: /home/damir/.platformio/lib
LibraryManager: Installing id=1766
Downloading...
Unpacking...
EspSpiffsService @ a9f97052d3 has been successfully installed!
Installing dependencies
Looking for EspCoreArchitecture library in registry
Found: http://platformio.org/lib/show/1761/EspCoreArchitecture
LibraryManager: Installing id=1761 @ *

Error: Could not find a version that satisfies the requirement '*' for your system 'linux_x86_64'

**Comment by ivankravets** [comment]
* Do you have problems with Internet/Permissions?
* Could you install other libraries?

**Comment by ddjikic** [comment]
I can install others without any issue, the internet is working, permissions where good.

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio update`. Then, restart IDE. Does it work now?

**Comment by ddjikic** [comment]
still same error msg

**Comment by ivankravets** [comment]
Could you try to run in PIO IDE Terminal
```
pio lib -g install EspCoreArchitecture
```

**Comment by ddjikic** [comment]
damir@damir-N76VB:~/Documents/PlatformIO/Projects/171025-001001-nodemcuv2$ pio lib -g install EspCoreArchitecture
Library Storage: /home/damir/.platformio/lib
LibraryManager: Installing id=1761
EspCoreArchitecture @ 3fe2c50406 is already installed

**Comment by ivankravets** [comment]
Sorry, I can't reproduce this issue :(

Could you reproduce it again?

**Comment by ivankravets** [comment]
Please reopen if you still need help
