### ISSUE TITLE
port 8010 is bound on 0.0.0.0

### ISSUE THREAD

**Issue by chaostheory88** [platformio/platformio-core#1140]
I found that port 8010 by default is bound on 0.0.0.0, could you please fix that? Anyone can gain information about projects and users credentials exposed into the page simply connecting from his browser to the machine on which the PlatformIO is running.

Here ss -ltn4p output from my machine:
LISTEN     0      50                                              *:8010                                                        *:*                   users:(("pioplus",pid=6217,fd=3))

**Comment by ivankravets** [comment]
Thanks for the report!

Please open PIO IDE Terminal and type `pio upgrade`. It should be fixed in 3.5.0b1. Don't forget to restart IDE.
