### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by patilsan90** [platformio/platformio-core#1144]
PIO Core Call Error: PlatformManager: Installing espressif32
Downloading
Downloading
Unpacking
Unpacking
espressif32 @ 0.10.0 has been successfully installed!
PackageManager: Installing toolchain-xtensa32 @ ~1.50200.0

Downloading
Downloading
Warning! Package Mirror: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\patilsp\\.platformio\\packages\\_tmp_installing-3zrday-package\\toolchain-xtensa32-windows-1.50200.0.tar.gz'
Looking for other mirror...

Please manually remove file `C:\Users\patilsp\.platformio\packages\_tmp_installing-3zrday-package\toolchain-xtensa32-windows-1.50200.0.tar.gz`
Error: Could not install 'toolchain-xtensa32' with version requirements '~1.50200.0' for your system 'windows_amd64'.
If you use Antivirus, it can block PlatformIO Package Manager. Try to disable it for a while.

**Comment by ivankravets** [comment]
Please close IDE. Remove `C:\Users\patilsp\.platformio` and open IDE.
