### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by mogplus88** [platformio/platformio-core#1149]
PIO Core Call Error: Extra data: line 3 column 1 - line 4 column 52 (char 142001 - 142101)

OS was PClinuxOS, clean install of latest version. Installed VS code, then Platformio. Hit new project and got this error. All the other functions give a similar error.

**Comment by ivankravets** [comment]
Thanks for the report!

Please open PIO IDE Terminal and type `pio upgrade`. It should be fixed in 3.5.0b1. Don't forget to restart IDE.
