### ISSUE TITLE
Pio doesn't use git library when requested

### ISSUE THREAD

**Issue by andig** [platformio/platformio-core#1155]
Consider this config file for pio 3.5.0a16:

    [platformio]
    #env_default = esp8266
    #env_default = esp32

    [common_env_data]
    lib_compat_mode=2
    #lib_ldf_mode=deep+

    [env:esp8266]
    platform=espressif8266
    framework=arduino
    board=esp12e
    build_flags = -Tesp8266.flash.4m1m.ld
    upload_port = vzero-edd834.local
    #targets = upload
    lib_deps =
      ArduinoOTA
      Hash
      ESPAsyncWebServer
    #  https://github.com/me-no-dev/ESPAsyncWebServer.git
      OneWire
      DHT Sensor Library
      Adafruit Unified Sensor
      DallasTemperature
      ArduinoJson

      ESP8266mDNS
      DNSServer
      ESPAsyncTCP
    #  https://github.com/me-no-dev/ESPAsyncTCP.git
    lib_ignore =
      AsyncTCP

    [env:esp8266_stage]
    platform=https://github.com/platformio/platform-espressif8266.git#feature/stage
    framework=arduino
    board=esp12e
    build_flags = -Tesp8266.flash.4m1m.ld
    upload_port = vzero-edd834.local
    #targets = upload
    lib_deps =
      ArduinoOTA
      Hash
      ESPAsyncWebServer
    #  https://github.com/me-no-dev/ESPAsyncWebServer.git
      OneWire
      DHT Sensor Library
      Adafruit Unified Sensor
      DallasTemperature
      ArduinoJson

      ESP8266mDNS
      DNSServer
    #  ESPAsyncTCP
      https://github.com/me-no-dev/ESPAsyncTCP.git
    lib_ignore =
      AsyncTCP

    [env:esp32]
    platform=espressif32_stage
    framework=arduino
    board=featheresp32
    lib_deps =
      ArduinoOTA
      Hash
    #  ESPAsyncWebServer
      https://github.com/me-no-dev/ESPAsyncWebServer.git
      OneWire
      DHT Sensor Library
      Adafruit Unified Sensor
      DallasTemperature
      ArduinoJson

    #  HTTPClient
      WiFiClientSecure
    #  AsyncTCP
      https://github.com/me-no-dev/AsyncTCP.git
      https://github.com/bbx10/DNSServer_tng
      ESPmDNS
    lib_ignore =
      ESPAsyncTCP

When compiling `esp8266_stage` pio shows this dependency tree:

	Library Dependency Graph
	|-- <ArduinoOTA> v1.0
	|   |-- <ESP8266WiFi> v1.0
	|   |-- <ESP8266mDNS>
	|   |   |-- <ESP8266WiFi> v1.0
	|-- <Hash> v1.0
	|-- <ESPAsyncWebServer> v1.1.0
	|   |-- <ESPAsyncTCP> v1.1.0
	|   |   |-- <ESP8266WiFi> v1.0
	|   |-- <ESP8266WiFi> v1.0
	|   |-- <ArduinoJson> v5.11.1
	|   |-- <Hash> v1.0
	|-- <OneWire> v2.3.2
	|-- <Adafruit Unified Sensor> v1.0.2
	|-- <DallasTemperature> v3.7.7
	|   |-- <OneWire> v2.3.2
	|-- <ArduinoJson> v5.11.1
	|-- <ESP8266mDNS>
	|   |-- <ESP8266WiFi> v1.0
	|-- <DNSServer> v1.1.0
	|   |-- <ESP8266WiFi> v1.0
	|-- <ESP8266HTTPClient> v1.1
	|   |-- <ESP8266WiFi> v1.0
	|-- <DHT sensor library> v1.3.0
	|   |-- <Adafruit Unified Sensor> v1.0.2
	|-- <ESP8266WiFi> v1.0

It shows that `ESPAsyncTCP` is used at 1.1.0, not git. 

Even if the git version of `ESPAsyncWebServer` is used it still doesn't use `ESPAsyncTCP` git. In this case also the `ESPAsyncWebServer` is still locked at 1.1.0 which is not what is requested.

**Comment by ivankravets** [comment]
Please `pio upgrade` to 3.5.0b5 and retest. Thanks!
