### ISSUE TITLE
Change default Project Location

### ISSUE THREAD

**Issue by roberto314** [platformio/platformio-core#1161]
I am working on PlatformIO with Atom on Windows 10.
It would be nice to make the default Project location configurable.
That means when i click on "New Project" the folder should be in "my" location or, as an alternative, in the last folder i made a new project.

best regards,
Robert

**Comment by Kaibz** [comment]
Same here, PlatformIO is a great platform but the ability to change the default location should be mandatory.

**Comment by ivankravets** [comment]
Docs: http://docs.platformio.org/en/latest/userguide/cmd_settings.html#projects-dir
