### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by mogplus88** [platformio/platformio-core#1164]
PIO Core Call Error: Extra data: line 3 column 1 - line 4 column 52 (char 142001 - 142101)
reinstalled Platformio core (as pio command not found). did pio upgrade, but same error. It is also complaining about the "nospoof on" command and "spoofalert on" command. But it got past those and told me my system was up to date.

Found the problem. There is a file called /etc/host-conf, which has two lines in it, "nospoof on" and "spoofalert on". I commented these two lines out and now it all works fine. I don't know what the file does. There are only two other lines in it, "order hosts,bind" and "multi on". So I guess I'll have to wait and see if anything else odd happens...
;-) Ian

**Comment by ivankravets** [comment]
What is your OS? Locale?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by mogplus8** [comment]
Hi Ivan,
Thanks for the quick response. Unfortunately I'm nowhere near my computer for this week, I won't be back home until Monday so I can't try it until then. I'll try it again then and let you know how I go. 
I thought I'd answered your question earlier but maybe not, as it doesn't look like it's here! OS is PCLinuxOS (KDE desktop), local is Australia (Melbourne).
Thanks,
Ian

**Comment by ivankravets** [comment]
@romankot  do you have the same lines https://github.com/platformio/platformio-core/issues/1164#issue-271169305 ?

**Comment by ivankravets** [comment]
Please reopen if you still need help
