### ISSUE TITLE
Home: Could not load lastest application state

### ISSUE THREAD

**Issue by samuelbles07** [platformio/platformio-core#1167]
When i opening platfom io, i get an error pop up like this

`Could not load recent projects
Server error`

and

`Could not load lastest application state
Server error`

And when make new project i got like this

`Could not load boards list`
`PIO Core Call Error: 'module' object has no attribute 'path_to_unicode'`

**Comment by ivankravets** [comment]
Please close IDE and remove `%HOME_DIR%/.platformio/penv` folder. Start IDE
