### ISSUE TITLE
Board support request: Heltec Wifi kit 8

### ISSUE THREAD

**Issue by hans-olav** [platformio/platformio-core#1169]
Would be great if you could add support for Heltec Wifi Kit 8:

https://www.amazon.com/ESP8266-development-Arduino-NodeMcu-0-91inch/dp/B074373KTY/ref=sr_1_1?ie=UTF8&qid=1509914109&sr=8-1&keywords=heltec+wifi+kit+8

**Comment by davidbitton** [comment]
hear hear

**Comment by ivankravets** [comment]
Added in https://github.com/platformio/platform-espressif8266/commit/fa3cbbee36565f5ea873586682f12f53a1ac1f18
