### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by Shlepzig** [platformio/platformio-core#1171]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "/home/sam/Documents/Arduino/libraries/" does not exist.

**Comment by ivankravets** [comment]
Does this folder exist?

**Comment by ivankravets** [comment]
Please restart IDE. It should fix.
