### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by Npizza** [platformio/platformio-core#1178]
PIO Core Call Error: Library Storage: /home/pizza/Desktop/backup_usb1/GrowProject/.piolibdeps
Updating MenuSystem                      @ 2.1.1          [3.0.0]
Uninstalling MenuSystem @ 2.1.1: 	[OK]
Looking for MenuSystem library in registry

Error: Library `MenuSystem` has not been found in PlatformIO Registry.
You can ignore this message, if `MenuSystem` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
Please `arduino-menusystem` as a library name.
