### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by axion9801** [platformio/platformio-core#1186]
PIO Core Call Error: PlatformManager: Installing linux_i686
Downloading...
Unpacking...
linux_i686 @ 1.1.2 has been successfully installed!
PackageManager: Installing toolchain-gcclinux32 @ ~1.40801.0

Error: Could not find a version that satisfies the requirement '~1.40801.0' for your system 'linux_x86_64'

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-linux_i686/issues
