### ISSUE TITLE
Can't select Location in PlatformIO

### ISSUE THREAD

**Issue by Tim3game** [platformio/platformio-core#1187]
### Configuration

**Operating system**: Windows 10 64bit Home Edtion

**PlatformIO Version** (`platformio --version`): 3.5.0b3

### Description of problem
I tried to install PlatformIO on Atom and on VSCode, but there is the same problem. When creating a new project, loading Arduino project, or loading any files in PlatformIO, It can't load my files. The only thing is doing is saying **Loading...**. Yes, I'l tried it with Admin privileges

#### Steps to Reproduce

1. Open Atom or VSCode
2. Go to PlatformIO Home
3. Select **+New Project**
4. **De**select *Use default location*

### Actual Results
![image](https://user-images.githubusercontent.com/10467214/32920619-3e118b50-cb2a-11e7-9adb-b2f5e9bc11d8.png)

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
