### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by dunk8888** [platformio/platformio-core#1194]
PIO Core Call Error: Error: Could not load broken JSON: C:\Users\Dunk\.platformio\lib\I2C_Sensor\library.json

**Comment by ivankravets** [comment]
Could you share a content of  `C:\Users\Dunk.platformio\lib\I2C_Sensor\library.json` here?

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
