### ISSUE TITLE
Home: Error: Invalid value for "-d" / "--storage-dir": Directory "global" does not exist

### ISSUE THREAD

**Issue by thbui** [platformio/platformio-core#1196]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "global" does not exist.

**Comment by ivankravets** [comment]
Could you explain how to reproduce it?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
Fixed in PIO Home 0.5.3. Thanks for the report!
