### ISSUE TITLE
digispark-tiny platform: SPI.h not found

### ISSUE THREAD

**Issue by dontsovcmc** [platformio/platformio-core#1197]
### Configuration

**Operating system**:
MacOS, Visual Studio Code (Windows 10x64 also)
**PlatformIO Version**:
PlatformIO, version 3.5.0b3

### Description of problem
I got error when build project that depends SPI.h
`src/main.cpp:2:17: fatal error: SPI.h: No such file or directory`

#### Steps to Reproduce
1. Project for Digistump Digispark 16Mhz
2. Add "SPI.h" header or add library that included "SPI.h"

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```
[env:digispark-tiny]
platform = atmelavr
board = digispark-tiny
framework = arduino
```

**Source file to reproduce issue:**
```
#include <Arduino.h>
#include "SPI.h"
void setup() {
    // put your setup code here, to run once:
}

void loop() {
    // put your main code here, to run repeatedly:
}
```

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-atmelavr/issues
