### ISSUE TITLE
Board support for Macchina M2

### ISSUE THREAD

**Issue by John-Titor** [platformio/platformio-core#1198]
It'd be nice to have support for this board:

    https://www.macchina.cc

which is currently supported by the Arduino IDE, and seems to be very similar to the Arduino Due

    http://docs.macchina.cc/m2/technical-references/processor.html

**Comment by ivankravets** [comment]
Implemented in https://github.com/platformio/platform-atmelsam/releases/tag/v2.7.1

**Comment by ivankravets** [comment]
Would be thankful for a star ⭐️ for PlatformIO Core project https://github.com/platformio/platformio/stargazers

Thanks a lot!

**Comment by NMSTEC** [comment]
> Would be thankful for a star ⭐️ for PlatformIO Core project https://github.com/platformio/platformio/stargazers
> 
> Thanks a lot!

Unfortunately you guys removed it again in 3.5, is there any chance of returning it into the IDE?
Thanks!
