### ISSUE TITLE
TI MSP-EXP430FR2433

### ISSUE THREAD

**Issue by shaunhey** [platformio/platformio-core#1199]
Please add support for the newest TI MSP430 Launchpad, the TI MSP-EXP430FR2433.  Support for this board was recently added to TI's Arduino fork, Energia.

http://www.ti.com/tool/msp-exp430fr2433

Output of pio device list:
```
/dev/ttyACM1
------------
Hardware ID: USB VID:PID=2047:0013 SER=58349B6F0F000C00 LOCATION=1-1.1.3:1.2
Description: MSP Tools Driver - MSP Application UART

/dev/ttyACM0
------------
Hardware ID: USB VID:PID=2047:0013 SER=58349B6F0F000C00 LOCATION=1-1.1.3:1.0
Description: MSP Tools Driver - MSP Debug Interface
```

**Comment by ivankravets** [comment]
Please move an issue to https://github.com/platformio/platform-timsp430/issues

**Comment by shaunhey** [comment]
Sorry about that, will do!
