### ISSUE TITLE
Never ending loop ... PlatformIO IDE: Installing... -> Restart ... What to do?

### ISSUE THREAD

**Issue by profra** [platformio/platformio-core#1201]
![image](https://user-images.githubusercontent.com/11443489/33230691-7f2b3a36-d1e8-11e7-8426-2b244371c258.png)

![image](https://user-images.githubusercontent.com/11443489/33230693-8bb1e1e2-d1e8-11e7-8c9b-dfa34381dd80.png)

What kind of issue is this?

- [X ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [X ] PlatformIO Core. If you’ve found a bug, please provide an information below.
------------------------------------------------------------------
### Configuration
**Operating system**:
1st machine ... Linux Mint
2nd machine ... W10 Pro
**PlatformIO Version** (`platformio --version`):
trying to update from ...b3 to ....b4 ... both machine's-IDEs got stuck

**Comment by ivankravets** [comment]
Could you try this solution?

https://github.com/crsmithdev/arrow/issues/495#issuecomment-346939862

**Comment by profra** [comment]
Thanks... it helped

**Comment by ivankravets** [comment]
Thanks!
