### ISSUE TITLE
Home: Could not list directory/home/jopjeknopje/Stuff/Programming

### ISSUE THREAD

**Issue by JopjeKnopje** [platformio/platformio-core#1203]
Could not list directory by `/home/jopjeknopje/Stuff/Programming`
help plis

**Comment by ivankravets** [comment]
Do you have non-ascii chars in /home/jopjeknopje/Stuff/Programming ?

**Comment by JopjeKnopje** [comment]
Yep renamed the file and that fixed it.
thanks.

**Comment by ivankravets** [comment]
What is your locale? Could you post a file name here?

**Comment by ivankravets** [comment]
Please reopen if you still need help
