### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by vadim315** [platformio/platformio-core#1207]
PIO Core Call Error: PlatformManager: Installing file:f:\ESP8266\ESP8266_IOT_PLATFORM-master

Error: Detected unknown package 'file:f:\ESP8266\ESP8266_IOT_PLATFORM-master'

**Comment by ivankravets** [comment]
See URI syntax here http://docs.platformio.org/en/latest/userguide/platforms/cmd_install.html

It should be `file://f:/ESP8266/ESP8266_IOT_PLATFORM-master`
