### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by ykqureshi** [platformio/platformio-core#1210]
PIO Core Call Error: Error: Unknown development platform 'espressif32@0.10.0'

**Comment by ivankravets** [comment]
Could you reproduce it when close/open PIO Home?

**Comment by ykqureshi** [comment]
> Could you reproduce it when close/open PIO Home?

No, I couldn't reproduce the error after closing and reopening the PIO home.

**Comment by ivankravets** [comment]
I'll think on that...
