### ISSUE TITLE
PIO Core Call Error: Extra data

### ISSUE THREAD

**Issue by alletaon** [platformio/platformio-core#1216]
PIO Core Call Error: Extra data: line 3 column 1 - line 36 column 124 (char 4 - 2365)

**Comment by ivankravets** [comment]
Could you reproduce this issue when restart IDE?

**Comment by ivankravets** [comment]
@MurzzZ could you reproduce this issue after restart?

**Comment by alletaon** [comment]
After restart IDE all ok.
