### ISSUE TITLE
Home: Could not load platform updates

### ISSUE THREAD

**Issue by vadim315** [platformio/platformio-core#1224]
PIO Core Call Error: Error: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'returncode': 128, 'err': "fatal: unable to access 'https://github.com/platformio/platform-espressif8266.git/': Failed to connect to github.com port 443: Socket is not connected\n", 'out': ''})

**Comment by ivankravets** [comment]
Please check your internet connection
