### ISSUE TITLE
pic32prog missing from microchippic32 on Raspberr PI

### ISSUE THREAD

**Issue by rianders** [platformio/platformio-core#1226]
What kind of issue is this?
Cannot upload from Raspberry PI Zero W. pic32prog missing from microchippic32 on Raspberr PI.

- [ ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration
```
[env:fubarino_mini]
platform = microchippic32
framework = arduino
board = fubarino_mini

[platformio]
src_dir=.
```
**Operating system**:
Raspian

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 3.4.1

### Description of problem
Cannot upload from Raspberry PI Zero W. pic32prog missing from microchippic32 on Raspberr PI.

#### Steps to Reproduce

`pio run -t upload`

`pio run -v  -t upload --upload-port /dev/ttyAMA0`

### Actual Results

```
Checking program size
text	 rodata	   data	    bss	    dec	    hex	filename
46944	   1044	   2336	   8636	  58960	   e650	.pioenvs/fubarino_mini/firmware.elf
pic32-bin2hex -a .pioenvs/fubarino_mini/firmware.elf
MethodWrapper(["upload"], [".pioenvs/fubarino_mini/firmware.hex"])
Use manually specified: /dev/ttyAMA0
pic32prog -d "/dev/ttyAMA0" -b 115200 .pioenvs/fubarino_mini/firmware.hex
Segmentation fault
*** [upload] Error 139
=========================================================== [ERROR] Took 41.88 seconds ===========================================================

```

### Expected Results
The hex file should upload

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-microchippic32/issues
