### ISSUE TITLE
Support for Linkit Smart Duo (Arduino Mcu Programing)

### ISSUE THREAD

**Issue by ssribeiro** [platformio/platformio-core#1227]
- [x] Feature Request. 

Can you please add support for Linkit Smart Duo platform from MediaTek for programing in arduino language?
It would be nice of you.
Thanks.

**Comment by ivankravets** [comment]
Added https://github.com/platformio/platform-atmelavr/commit/0f48c2b69bf57a36be9d26346861da6e26192cf8

**Comment by ivankravets** [comment]
Please test it with this `platformio.ini`
```ini
[env:smart7688]
platform = https://github.com/platformio/platform-atmelavr.git
framework = arduino
board = smart7688
```

Does it work?
