### ISSUE TITLE
Home: Could not uninstall platform

### ISSUE THREAD

**Issue by cesar-rojas** [platformio/platformio-core#1228]
PIO Core Call Error: Uninstalling espressif32 @ 0.11.0: 	[OK]
Uninstalling toolchain-xtensa32 @ 2.50200.0: 	[OK]
Uninstalling framework-arduinoespressif32 @ 1.3.2: 	[OK]
Uninstalling framework-espidf @ 2.211.0: 	[OK]
Uninstalling tool-espotapy @ 1.1.0: 	[OK]
Uninstalling tool-esptoolpy @ 1.20100.0: 	[OK]
Uninstalling toolchain-xtensa32 @ 2.50200.0: 	[OK]

Error: Detected unknown package 'c:\Projects\.platformio\packages\toolchain-xtensa32@1.50200.2 @ 1.50200.2'

**Comment by ivankravets** [comment]
Could you reproduce this issue again?

**Comment by ivankravets** [comment]
Please reopen if you still need help
