### ISSUE TITLE
Could not login into PIO Account [VSCode]

### ISSUE THREAD

**Issue by mkohns** [platformio/platformio-core#1231]
### Configuration

Win7 64Bit
Home 0.5.3·Core 3.5.0rc7

VSCode:
Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T12:06:43.492Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

### Description of problem
Unable to Login into PIO Account

1) Press on "Account"
2) Fill in credentials press ok
3) Progress indicator on Login Button
4) results in a page reload (login page shows up again)

- When entering wrong password -> a bad credentials popup occurs
- login with cli works fine
- I made a new account -> no login possible either
- I uninstalled PIO + VSCode + delete ~.platformio, ~.vscode

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal, type `pio update` and restart IDE.
