### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by peranchu** [platformio/platformio-core#1233]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "/home/norino/Documents/Arduino/libraries" does not exist.

**Comment by ivankravets** [comment]
> Directory "/home/norino/Documents/Arduino/libraries" does not exist.

Is it true?

**Comment by ivankravets** [comment]
Please restart IDE. The issue should be gone.
