### ISSUE TITLE
No stuch commande on : everything 

### ISSUE THREAD

**Issue by Essenceia** [platformio/platformio-core#1234]
### Configuration

Python 2.7.14

**Operating system**:

4.9.66-1-MANJARO (arch)

**PlatformIO Version** (`platformio --version`):

PlatformIO, version 3.4.1
+ have  99-platformio-udev.rules 

### Description of problem

No more commands seem to be recognized, even `platformio init` and `platformio init` isn't recognised ....
`Error: No such command "init"` 

Only `platformio --version` still seems to work. I have already uninstalled + reinstalled with pip as `pip uninstall platformio` `pip install -U platformio` with no results.

#### Steps to Reproduce

1.Install serial module `pip install serial`
2.Uninstall serial module `pip uninstall serial`

### Additional info

If field is left empty `platformio` I get `Error: No such command "ci"`.
Thanks for the help, I have no idea where to start with this problem.

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
You need to use virtual environment in this case if main `python` binary is 3.0. We don't support Python 3.0 yet.

```
sudo pip install virtualenv
virtualenv ~/.platformio/penv -p pyton2.7
source ~/.platformio/penv/activate
(penv) pip install platformio
```

Now, please add `~/.platformio/penv/bin` to your system `PATH`.

**Comment by Essenceia** [comment]
Hello, unfortunately it would seem that the project still persists with the same symptoms. There were no problems with any of the installs.
` echo $PATH `
`/home/pookie/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/pookie/.platformio/penv/bin `

**Comment by ivankravets** [comment]
> source ~/.platformio/penv/bin/activate

Ahhh... That was my mistake. Sorry :(

I recommend to switch to the latest PIO Core 3.5.0RC:

```
~/.platformio/penv/bin/pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
```
