### ISSUE TITLE
ESP32 - change of partition size not working

### ISSUE THREAD

**Issue by beegee-tokyo** [platformio/platformio-core#1248]
### Configuration

**Operating system**: Windows 7 Ultimate 64bit Service Pack 1

**PlatformIO Version** (`platformio --version`): 3.5.0rc10

**Visual Studio Code Version**: 1.18.0

**Atom Version**: 1.23.1 x64
### Description of problem
Partition sizes doesn't change even if default.csv is changed.
#### Steps to Reproduce

Following this [issue](https://github.com/espressif/arduino-esp32/issues/703) I tried to change the partition sizes on my ESP32 Dev Module.
The changed default.csv:
> # Name,   Type, SubType, Offset,  Size, Flags
> nvs,      data, nvs,     0x9000,  0x5000,
> otadata,  data, ota,     0xe000,  0x2000,
> app0,     app,  ota_0,   0x10000, 0x150000,
> app1,     app,  ota_1,   0x160000,0x150000,
> eeprom,   data, 0x99,    0x310000,0x1000,
> spiffs,   data, spiffs,  0x311000,640K,

But after uploading the partition sizes are still the default ones:

> App partition table:
> SubType 10 Address 0x010000 Size 0x140000 Encryption 0 Label app0
> SubType 11 Address 0x150000 Size 0x140000 Encryption 0 Label app1
> Data partition table:
> SubType 02 Address 0x009000 Size 0x005000 Encryption 0 Label nvs
> SubType 00 Address 0x00e000 Size 0x002000 Encryption 0 Label otadata
> SubType 99 Address 0x290000 Size 0x001000 Encryption 0 Label eeprom
> SubType 82 Address 0x291000 Size 0x16f000 Encryption 0 Label spiffs

Then I tried the exact same procedure on Arduino IDE and the partition size changed to:
> App partition table:
> Type: 00 SubType 10 Address 0x010000 Size 0x150000 Encryption 0 Label app0
> Type: 00 SubType 11 Address 0x160000 Size 0x150000 Encryption 0 Label app1
> Data partition table:
> Type: 01 SubType 02 Address 0x009000 Size 0x005000 Encryption 0 Label nvs
> ype: 01 SubType 00 Address 0x00E000 Size 0x002000 Encryption 0 Label otadata
> Type: 01 SubType 99 Address 0x310000 Size 0x001000 Encryption 0 Label eeprom
> Type: 01 SubType 82 Address 0x311000 Size 0x0A0000 Encryption 0 Label spiffs

Going back to PlatformIO, I uploaded my code again from there and the changed partition sizes are still valid.

It seems that PlatformIO doesn't change the partition size at all. Or is my method to change the partition sizes wrong?

**Comment by ivankravets** [comment]
Please move issue to appropriate repository https://github.com/platformio/platform-espressif32/issues
