### ISSUE TITLE
T89C51CC01

### ISSUE THREAD

**Issue by heikohettler** [platformio/platformio-core#1250]
Subj

**Comment by heikohettler** [comment]
I need this board to start to program

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/907

**Comment by chrizbee** [comment]
> Duplicate of #907

This is marked as `done` here https://registry.platformio.org/platforms/platformio/intel_mcs51 but I can't seem to find the Atmel T89C51CC01 MCU there...

**Comment by ivankravets** [comment]
Please file a feature request at https://github.com/platformio/platform-intel_mcs51/issues
