### ISSUE TITLE
IndentationError in exception.py

### ISSUE THREAD

**Issue by Nzbuu** [platformio/platformio-core#1251]
There's a missing line continuation marker in exception.py causing an IndentationError

https://github.com/platformio/platformio-core/blob/d70a90f1d54f551523322797b37efe61d7c76680/platformio/exception.py#L229

Although, as discussed the the [Google Python style guide](https://google.github.io/styleguide/pyguide.html?showone=Line_length#Line_length) it's better to use parentheses and the implicit line joining.

This is the (first) cause of the failing Travis builds: https://travis-ci.org/platformio/platformio-core/jobs/318628355

**Comment by ivankravets** [comment]
Should be fixed in https://github.com/platformio/platformio-core/commit/1171cb204c8c5ef3eb379f94e66754eda43c310f
