### ISSUE TITLE
PlatformIO fail to upload to ESP32 after update

### ISSUE THREAD

**Issue by NRJ-Javor** [platformio/platformio-core#1255]
After updating PlatformIO to Core 3.5.0rc14, it fails to upload firmware to ESP32 Dev Module. Tried uninstalling PlatformIO, Atom, VSCode (yes, I use both IDEs), Python (both ver. 2 and ver. 3) and reinstall VSCode, Atom and PlatformIO. Result is always the same. Tried to upload with Arduino - worked.

Here are my specs:
OS: Windows 10 Pro
PlatformIO: Home 0.5.3 Core 3.5.0rc14
Console output:

>...
Looking for upload port...
Auto-detected: COM7
Uploading .pioenvs\esp32dev\firmware.bin
usage: esptool write_flash [-h] [--flash_freq {keep,40m,26m,20m,80m}]
[--flash_mode {keep,qio,qout,dio,dout}]
[--flash_size FLASH_SIZE]
[--spi-connection SPI_CONNECTION] [--no-progress]
[--verify] [--compress | --no-compress]
><address> <filename> [<address> <filename> ...]
>esptool write_flash: error: argument <address> <filename>: Address "Controller" must be a number
>*** [upload] Error 2
>============================================================================================== [ERROR] Took 3.04 seconds ==============================================================================================
>The terminal process terminated with exit code: 1
This error happens to both Atom and VSCode, that's why I think it's PlatformIO related. 
Even g00gle doesn't know anything regarding "esptool write_flash: error: argument <address> <filename>: Address "Controller" must be a number"

**Comment by ivankravets** [comment]
Please move to https://github.com/platformio/platform-espressif32/issues
