### ISSUE TITLE
Cannot create freertos project under esp32 / arduino

### ISSUE THREAD

**Issue by kristsm** [platformio/platformio-core#1264]
Trying to create the simplest rtos example under Arduino sdk without any luck:
1. I was using this as a base code: https://techtutorialsx.com/2017/05/06/esp32-arduino-creating-a-task/
Platformio doesn't allow to include <task.h> therefore the compiler gives out:

Verbose mode can be enabled via `-v, --verbose` option
Collected 21 compatible libraries
Looking for dependencies...
No dependencies
Compiling .pioenvs\esp32doit-devkit-v1\src\main.o
Compiling .pioenvs\esp32doit-devkit-v1\FrameworkArduino\esp32-hal-adc.o
Compiling .pioenvs\esp32doit-devkit-v1\FrameworkArduino\esp32-hal-bt.o
Compiling .pioenvs\esp32doit-devkit-v1\FrameworkArduino\esp32-hal-dac.o
src\main.cpp:2:18: fatal error: task.h: No such file or directory

after rebuilding index with platformio, the file is not included. It does not matter if I put correct path in the c_cpp_properties.json , it doesn't work anyway!

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif32/issues
