### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by HollisTech** [platformio/platformio-core#1272]
Server error

There doesn't appear to be any other information.

**Comment by ivankravets** [comment]
Please share here `~/.platformio/homestate.json` file. Thanks!

**Comment by HollisTech** [comment]
``{"storage": {"homeDir": "C:\\Users\\Mark", "coreCaller": "vscode", "cid": "8dade227-34c2-4810-eb1d-ae85f85bac54", "projectsDir": "C:\\Users\\Mark\\Documents\\PlatformIO\\Projects", "lastCheckPlatformUpdates": 1514933837960, "lastUpdateCorePackages": 1514933837959, "coreVersion": "3.5.0", "routeBadges": {}, "lastCheckLibraryUpdates": 1514933837960, "recentProjects": ["C:\\Users\\Mark\\Documents\\PlatformIO\\Projects\\171209-143700-featheresp32-pwm-test", "C:\\Users\\Mark\\Documents\\PlatformIO\\Projects\\171218-144021-featheresp32-oled", "C:\\Users\\Mark\\Documents\\PlatformIO\\Projects\\esp32-threaded-test"], "coreSystype": "windows_x86", "showOnStartup": {"vscode": false}}, "inputValues": {"libBuiltinFilter": "timer", "boardsFilter": "Adafruit ESP32 Feather"}}

**Comment by ivankravets** [comment]
Could you reproduce this issue after IDE restart?

**Comment by HollisTech** [comment]
yes.

Mark Roddy

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio home`. Do you see any errors?

**Comment by HollisTech** [comment]
Yes it is the same issue "could not load recent projects" "server error"
![image](https://user-images.githubusercontent.com/5400087/34544329-b2654fe2-f0b3-11e7-826f-1ff9eb1ba9ad.png)

**Comment by ivankravets** [comment]
Please share the contents of these files:
1. C:\Users\Mark\Documents\PlatformIO\Projects\171209-143700-featheresp32-pwm-test\platformio.ini
2. C:\Users\Mark\Documents\PlatformIO\Projects\171218-144021-featheresp32-oled\platformio.ini
3. C:\Users\Mark\Documents\PlatformIO\Projects\esp32-threaded-test\platformio.ini

Thanks!

**Comment by HollisTech** [comment]
```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_baud=115200`
```

They all look pretty much the same as the above, with the same result when opening pio home.

Here's the one I'm currently working on (esp32-threaded) it is slightly different:

```
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:featheresp32]
platform = espressif32
board = featheresp32
framework = arduino
monitor_baud=115200
build_flags=-Wl,-Map,output.map
upload_port=esp32-1.local


;[env:native]
; platform = native
```

**Comment by ivankravets** [comment]
How did you fix it?

**Comment by HollisTech** [comment]
I accidentally downloaded a repo into .platformio/platforms that should not have been there. Once I moved it out of there all was good. Sorry. My blunder.
