### ISSUE TITLE
Could not uninstall platform

### ISSUE THREAD

**Issue by thbui** [platformio/platformio-core#1282]
# Temporary solution

Please reopen PIO Home

--------
PIO Core Call Error: Uninstalling espressif32 @ 0.11.0: 	[OK]
Uninstalling framework-arduinoespressif32 @ 1.3.2: 	[OK]
Uninstalling tool-esptoolpy @ 1.20100.0: 	[OK]
Uninstalling toolchain-xtensa32 @ 2.50200.0: 	[OK]

Error: Detected unknown package 'C:\Users\Tuan\.platformio\packages\toolchain-xtensa32@1.50200.2 @ 1.50200.2'

**Comment by ivankravets** [comment]
Could you reproduce this issue when close/open PIO Home?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
Fixed in the upcoming update to PIO Home
