### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by scalemidia** [platformio/platformio-core#1284]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "/home/welklin/Documents/Arduino/libraries" does not exist.

**Comment by ivankravets** [comment]
Do you see this folder `/home/welklin/Documents/Arduino/libraries`?

**Comment by scalemidia** [comment]
this is correct path "/home/welklin/Arduino/libraries"
