### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by chenhonglin** [platformio/platformio-core#1289]
PIO Core Call Error: Library Storage: C:\Users\bing\.platformio\lib

Error: Detected unknown package 'C:\Users\bing\.platformio\lib\ESPAsyncWebServer_ID306 @ *'

**Comment by ivankravets** [comment]
Could you reproduce this issue when reopen PIO Home?

**Comment by ivankravets** [comment]
Please reopen if you still need help
