### ISSUE TITLE
Home: Error: Invalid value for "-d" / "--storage-dir" when directory

### ISSUE THREAD

**Issue by boguslawb** [platformio/platformio-core#1293]
PIO Core Call Error: Usage: platformio lib [OPTIONS] COMMAND [ARGS]...

Error: Invalid value for "-d" / "--storage-dir": Directory "/home/boguslaw/Documents/PlatformIO/Projects/180115-104626-d1_mini" does not exist.

Of course I renamed this automated name of folder in system (ubuntu)

**Comment by ivankravets** [comment]
So, this is a known issue. Please reopen PIO Home. It should help.

**Comment by ivankravets** [comment]
Fixed in the upcoming update to the PIO Home
