### ISSUE TITLE
[FAILURE] The installation process has been FAILED!

### ISSUE THREAD

**Issue by kaline** [platformio/platformio-core#1298]
I'm trying install the platformio core in windows 10 however  at the moment I try run that command the prompt shows a fail. Any ideas mabout the problem?

![erro](https://user-images.githubusercontent.com/31135896/35059639-072c0ada-fba3-11e7-95c3-83213a6b2ed2.PNG)

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by kalineBr** [comment]
![capturar](https://user-images.githubusercontent.com/31135896/35301482-c7e6b990-0072-11e8-9e14-1e57dd8bbb81.PNG)

**Comment by ivankravets** [comment]
I see that you sucessfully installed PIO Core. Do you still have any problems?

**Comment by ivankravets** [comment]
Please reopen if you still need help
