### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by ramiws** [platformio/platformio-core#1302]
Server error

also could not load boards list when click new project

**Comment by ivankravets** [comment]
@ramiws @2DRobotics

Please open PIO IDE Terminal and type `pio home`. Do you see any errors?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
@ramiws @2DRobotics @EnnajimiYassine @murataka 

Please open PIO IDE Terminal and type `pio home`. Do you see any errors?

**Comment by ivankravets** [comment]
@ramiws @2DRobotics @EnnajimiYassine @murataka  @SackDago

Please open PIO IDE Terminal and type `pio home --port 8888`. Do you see any errors?

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart IDE.
