### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by ovsel43** [platformio/platformio-core#1304]
PIO Core Call Error: PlatformManager: Installing ststm32
Downloading...
Unpacking...
ststm32 @ 3.8.0 has been successfully installed!
PackageManager: Installing toolchain-gccarmnoneeabi @ >=1.40803.0,<1.40805.0

Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] 
Looking for another mirror...
Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] 
Looking for another mirror...

Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.40803.0,<1.40805.0' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Have you tried all solutions form http://bit.ly/faq-package-manager?

**Comment by ovsel43** [comment]
I tried, to no avail.

The problem was solved after changing CLANG version 64-bit to 86-bit.

**Comment by ivankravets** [comment]
Hm... This issue should not be linked with Clang. Nevertheless, that is good that you found a solution.

**Comment by edogaldo** [comment]
Hi, I just installed PlatformIO over VSCode over Win10/64bit and I'm having the same error.
I'm not familiar with CLANG so I don't know how to change it.
Could you help me to solve the problem?

Thanks in advance, E.

**Comment by ivankravets** [comment]
@edogaldo Have you tried all solutions form http://bit.ly/faq-package-manager?

**Comment by ovsel43** [comment]
Hi

http://docs.platformio.org/en/latest/ide/atom.html#ii-clang-for-intelligent-code-completion

1. Deinstall CLANG x64 version (LLVM)

2. Install  CLANG x86 version

At me after that the error has disappeared.

**Comment by edogaldo** [comment]
@ivankravets: I tried solution 3 as suggested but no luck, still same error..

@ovsel43: looks like Platformio@VSCode is not using Clang, does it?

**Comment by ovsel43** [comment]
Yes Clang not using, can not install it.
But in my case, with the Clang x64 installed, stably produces an error (see the picture): could not install toolchain-gccarmnoneeabi. I tried to install the package STM32 several times.
![platformio](https://user-images.githubusercontent.com/30753123/35423199-b27c6a86-025d-11e8-82ce-1d7320950b01.png)
I do not know what causes it (Maybe just a coincidence). I do not have time to understand.
Without CLANG or with the installed CLANG x86 the installation is successful (disable the antivirus). I checked several times (once there was a problem with downloading the package).
![platformio2](https://user-images.githubusercontent.com/30753123/35423605-9610dfd8-025f-11e8-8815-94b9294e8f2c.png)
Most likely, the problem is not in "CLANG".
Perhaps the problem is in the antivirus (I'm using Kaspersky Endpoint Security) or another.
But during the installation of stm32 the antivirus is turned off.

**Comment by edogaldo** [comment]
I give up: I can't disable the antivirus because it is locked at corporate level and there and I can't get STM32 platform working..

@ivankravets: here the error screenshot, hope this helps
![immagine](https://user-images.githubusercontent.com/20240750/35434517-c6589032-0287-11e8-9a5a-bfcd8022ecd7.png)

Best regards, E.

**Comment by edogaldo** [comment]
Maybe it depends on the fact that there is a strict requirement for a win_64bit version of the "toolchain-gccarmnoneeabi" package and it [does not esists](https://answers.launchpad.net/gcc-arm-embedded/+question/663539)?!

> Tejas Belagod (belagod-tejas) said on 2018-01-25:   #2  
> 
> Hi,
> 
> We don't build a 64-bit Windows version of the toolchain yet. I suspect you would need to start with replacing i686-w64-mingw32-gcc with x86_64-w64-mingw32-gcc and then take it from there.
> 
> Thanks,
>  Tejas.
>

**Comment by ivankravets** [comment]
@edogaldo 
> @ivankravets: I tried solution 3 as suggested but no luck, still same error..

Did you use SYSTEM TERMINAL? Not VSCode!

**Comment by edogaldo** [comment]
> Did you use SYSTEM TERMINAL? Not VSCode!
yes, I did.

**Comment by edogaldo** [comment]
@ivankravets 
Maybe it depends on the fact that there is a strict requirement for a win_64bit version of the "toolchain-gccarmnoneeabi" package and it [does not esists](https://answers.launchpad.net/gcc-arm-embedded/+question/663539)?!

> Tejas Belagod (belagod-tejas) said on 2018-01-25:   #2  
> 
> Hi,
> 
> We don't build a 64-bit Windows version of the toolchain yet. I suspect you would need to start with replacing i686-w64-mingw32-gcc with x86_64-w64-mingw32-gcc and then take it from there.
> 
> Thanks,
>  Tejas.
>

**Comment by edogaldo** [comment]
Ok, solution 4 worked!
Could successfully manually install the toolchain using package "toolchain-gccarmnoneeabi-windows-1.40804.0.tar.gz" in https://bintray.com/platformio/dl-packages/toolchain-gccarmnoneeabi/1.40804.0#files
Anyway automatic download is not working in any way..

Best, E.

**Comment by ivankravets** [comment]
> Ok, solution 4 worked!

Thanks!
