### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by martinesaldo** [platformio/platformio-core#1307]
PIO Core Call Error: Library Storage: C:\Users\sergio\.platformio\lib
Looking for platformIO library in registry

Error: Library `{'requirements': None, 'name': 'platformIO'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'platformIO'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
There is no "'platformIO" library in registry. See http://platformio.org/lib
