### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by abhra0897** [platformio/platformio-core#1316]
PIO Core Call Error: Error: Unknown development platform 'espressif8266@1.5.0'

**Comment by ivankravets** [comment]
Could you reproduce this issue when restart IDE?

**Comment by abhra0897** [comment]
The issue is solved. I have no clue why it showed up. Right after
restarting (the pc itself) the problem is gone.
The issue may be closed now.

On Jan 28, 2018 21:09, "Ivan Kravets" <notifications@github.com> wrote:

Could you reproduce this issue when restart IDE?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/platformio/platformio-core/issues/1316#issuecomment-361071943>,
or mute the thread
