### ISSUE TITLE
Home: Platforms: Frameworks

### ISSUE THREAD

**Issue by Commandoser** [platformio/platformio-core#1317]
PIO Core Call Error: Error: [API] Could not connect to PlatformIO API Service. Please try later.

**Comment by ivankravets** [comment]
Do you still experience this issue?

**Comment by Commandoser** [comment]
Nope. Right now just - CorePackageManager: Installing tool-scons

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#error-5-access-is-denied
