### ISSUE TITLE
Add Pycom LoPy Board

### ISSUE THREAD

**Issue by cyberman54** [platformio/platformio-core#1319]
Add [Pycom LoPy Board](https://pycom.io/product/lopy/) based on ESP32.

**Comment by ivankravets** [comment]
Depends on https://github.com/platformio/platformio-core/issues/728

**Comment by cyberman54** [comment]
does not necessary depend on implementation of micropython. The LoPy boards can be erased and used as native ESP32 board, for programming in C++ on platforms ESP-IDF or ardunio-espressif

**Comment by d-Pixie** [comment]
Exactly, I was looking for this board here since I want to be able to use platformio to push C code to my LoPy4 😄 Python support not needed, there are already good integration with Atom/VSCode for that toolchain from the developers of the board.

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/boards/espressif32/lopy.html
