### ISSUE TITLE
pio init makes QtCreator not understand Arduino C++ properly

### ISSUE THREAD

**Issue by hongquan** [platformio/platformio-core#1323]
What kind of issue is this?

- [x] PlatformIO Core. If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**: Ubuntu 17.10

**PlatformIO Version** (`platformio --version`): 3.5.2a5

#### Steps to Reproduce

1. Have an Arduino project
2. Run `pio init --ide qtcreator --board esp07`
3. Open the .ino file in QtCreator

### Actual Results
.pro file contains `DEFINES` lines like this:

```pro
DEFINES += ARDUINO=10600
DEFINES += LWIP_OPEN_SRC
```
and QtCreator shows some errors in .ino: "expected a declaration".

### Expected Results

There should be no "expected a declaration" error.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp07]
platform = espressif8266
board = esp07
framework = arduino
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info
This is the result of attempt to fix #1299.

Before the fix (with the trailing "#" being stripped):

![pio-old](https://user-images.githubusercontent.com/314607/35605151-627cd046-0679-11e8-9422-bdf578a189fc.png)

After the fix:

![pio_v3 5 2a5](https://user-images.githubusercontent.com/314607/35605164-7d1b752e-0679-11e8-9c29-189c2f005414.png)

I used to proposed a fix (#1290), in which I keep the quote (`"`) and removed `#` from `DEFINES`, but unfortunately, it was rejected.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev` and `pio init`

**Comment by hongquan** [comment]
In 53afdc5, I see that you are doing:

```tpl
% tokens = define.split("##", 1)
DEFINES += "{{tokens[0].strip()}}"
```

but what happen if some lines use single `#`?

**Comment by ivankravets** [comment]
The problem was caused by internal macros of GCC compiler. We've started to add them recently. There is no `#` in macro, see https://stackoverflow.com/questions/21891784/what-does-mean-in-c

**Comment by hongquan** [comment]
Thank you.
