### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by golfri** [platformio/platformio-core#1327]
PIO Core Call Error: PlatformManager: Installing espressif32
Downloading...
Unpacking...
espressif32 @ 0.11.0 has been successfully installed!
PackageManager: Installing toolchain-xtensa32 @ ~1.50200.2

Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] Zugriff verweigert
Looking for another mirror...
Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] Zugriff verweigert
Looking for another mirror...

Error: Could not install 'toolchain-xtensa32' with version requirements '~1.50200.2' for your system 'windows_amd64'.
More details: http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please use one of these solutions http://bit.ly/faq-package-manager
