### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by wsnell** [platformio/platformio-core#1336]
PIO Core Call Error: PlatformManager: Installing nxplpc
Downloading
Downloading
Unpacking
Unpacking
nxplpc @ 2.8.0 has been successfully installed!
PackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0

Downloading
Downloading
Unpacking
Unpacking
Warning! Package Mirror: [Error 5] Access is denied
Looking for another mirror...
Downloading
Downloading
Unpacking
Unpacking
Warning! Package Mirror: [Error 5] Access is denied
Looking for another mirror...

Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
