### ISSUE TITLE
Home: Could not list directory /home/username

### ISSUE THREAD

**Issue by artbody** [platformio/platformio-core#1339]
Could not list directory by  /home/username
Import a Arduino Projekt
Choose a directory with existing Arduino IDE project:
doesn't work
BUT
home/username/Documents/PlatformIO/Projects
works
So why doesn't home/username not list directory ???

WORKAROUND was to copy my files to home/username/Documents/PlatformIO/Projects
but that's not professional - > and arduino saves the projects by default in /home/username/Arduino
but normally you could save  files, projects or what ever, everywhere you want to

**Comment by ivankravets** [comment]
It SHOULD work. Which errors do you see?

**Comment by artbody** [comment]
`Could not list directory by /home/username`

**Comment by ivankravets** [comment]
Maybe, permission issue?

Could you try in Terminal?
```
python -c "import os; print os.listdir(os.path.expanduser('~'))"
python -c "import os; print os.listdir('/home/username')"
```

**Comment by artbody** [comment]
```
 python -c "import os; print os.listdir(os.path.expanduser('~'))"
  File "<string>", line 1
    import os; print os.listdir(os.path.expanduser('~'))
                      ^
SyntaxError: invalid syntax

```
 ```
python -c "import os; print os.listdir('/home/username')"
  File "<string>", line 1
    import os; print os.listdir('/home/username')
                      ^
SyntaxError: invalid syntax
```
ok
python console
```
 python
Python 3.5.4 (default, Feb  6 2018, 02:10:34) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print os.listdir('/home/username')
  File "<string>", line 1
    import os; print os.listdir('/home/username')
                      ^
SyntaxError: invalid syntax
>>>  os.listdir('/home/username')
['some.sh', '.mplayer', ..... '.hydrogen']
```
username was replaced by my username 

so i think python and the import os module works

**Comment by ivankravets** [comment]
Oh... Python 3. See updated commands https://github.com/platformio/platformio-core/issues/1339#issuecomment-365440763

**Comment by ivankravets** [comment]
@apenaz artbody please provide an output of
```
ls -al /home
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
