### ISSUE TITLE
Add Board: Hologram Dash

### ISSUE THREAD

**Issue by kmacvittie** [platformio/platformio-core#1341]
Would love to see support for the Dash by Hologram, info available here: https://hologram.io

**Comment by ivankravets** [comment]
@benstr do you have any ideas?

**Comment by ugorur** [comment]
Will this happen?

**Comment by ivankravets** [comment]
Please contact @benstr or https://community.hologram.io/ and place the link to this issue.

**Comment by ivankravets** [comment]
Dash Discontinued

https://community.hologram.io/t/dash-discontinued-q-a/1767
