### ISSUE TITLE
Incorrect ecoding when select custom location for project

### ISSUE THREAD

**Issue by egofoxlab** [platformio/platformio-core#1342]
OS: Microsoft Windows [Version 10.0.14393]

http://prntscr.com/ib1b0x

It is very, very cool that you finally fixed error with select custom project location on the Windows OS. But.. You can see that explorer encoding it is incorrect.

**Comment by ivankravets** [comment]
Could you provide a screenshot of the valid device names? What is your locale?

**Comment by egofoxlab** [comment]
@ivankravets http://prntscr.com/iezwki

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart VSCode. Does it work now?
