### ISSUE TITLE
#includes do not work in CLion with cpp files but work fine with h files within same lib/ directory

### ISSUE THREAD

**Issue by BryceBeagle** [platformio/platformio-core#1345]
### Configuration

**Operating system**:
Arch Linux

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 3.5.1

### Description of problem
.cpp files within the lib/ dir are not correctly recognized for builtin PlatformIO libraries (eg. the Arduino ones). Linting works fine within the same .h files within the same directory. Program builds correctly even though CLion doesn't think it should.

#### Steps to Reproduce

1. Create library within lib directory
2. Attempt `#include <Arduino.h>` within a .cpp file and within a .h file

### Actual Results
![image](https://user-images.githubusercontent.com/5437880/35961261-42972eb0-0c6a-11e8-85c6-61bd855de7de.png)
.h/.hpp files can find Arduino.h

![image](https://user-images.githubusercontent.com/5437880/35961241-3174202a-0c6a-11e8-88b7-7701dc6b0e3d.png)
.cpp files can find Arduino.h

Note that these two files are next to each other in the same directory

### Expected Results
Both should be able to #include the Arduino.h file

**Comment by ivankravets** [comment]
Please re-test with the latest PIO Core and re-init project:
```
pio upgrade --dev
pio init
```
