### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by rdonca** [platformio/platformio-core#1346]
# Temporary solution

Please reopen PIO Home

-------

PIO Core Call Error: Error: Unknown development platform 'espressif8266@1.4.0'

**Comment by ivankravets** [comment]
Could you reproduce this issue when close/open PIO Home?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
Fixed in the upcoming update to PIo Home.
