### ISSUE TITLE
Home: OS_RENAME_FILE

### ISSUE THREAD

**Issue by kjtl78** [platformio/platformio-core#1347]
Server error

**Comment by ivankravets** [comment]
Could you provide more details?

**Comment by kjtl78** [comment]
Received error when hitting ENTER while trying to rename a project in the
wizard. The renaming went fine after pressing finish. On Windows 10 64-bit.

Love the editor, though the renaming projects feature seems a bit
convoluted.

**Comment by ivankravets** [comment]
This an OS issue :( You can't rename an opened project, Windows does not allow that. Please close project from IDE before renaming.
