### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by mogplus8** [platformio/platformio-core#1351]
Occurred when I selected the update. Linux Mint 18.1. VSCode 1.19.2

PIO Core Call Error: Platform /home/ian/.platformio/platforms/ststm32
--------
Updating ststm32                         @ 04961a3        [143ed71]
git version 2.7.4

From https://github.com/platformio/platform-ststm32
   04961a3..143ed71  develop    -> origin/develop
fatal: Not a git repository: /home/ian/.platformio/platforms/_tmp_installing-3Tpu10-package/.git/modules/builder/frameworks/libopencm3
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment]
this is a known issue with old GIT. Please install/uninstall dev/platform or upgrade GIT.
