### ISSUE TITLE
Mark project directories in CLion

### ISSUE THREAD

**Issue by JackDn** [platformio/platformio-core#1359]
Currently PlatformIO projects look like this when they are opened with CLion:
![Project Files](https://i.imgur.com/VNkSHqN.png)

* `lib` is marked as a source directory
* `src` is not marked at all

This is what they should look like:
![Project Files](https://i.imgur.com/8h6fWQQ.png)

* `.pioenvs` and `.piolibdeps` are excluded (CLion won't index them)
* `lib` is marked as a library root
* `src` is marked as a source directory

To accomplish this, the CLion project builder should also create the following file:
`.idea/misc.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="CMakeWorkspace" PROJECT_DIR="$PROJECT_DIR$" />
  <component name="CidrRootsConfiguration">
    <sourceRoots>
      <file path="$PROJECT_DIR$/src" />
    </sourceRoots>
    <libraryRoots>
      <file path="$PROJECT_DIR$/lib" />
    </libraryRoots>
    <excludeRoots>
      <file path="$PROJECT_DIR$/.pioenvs" />
      <file path="$PROJECT_DIR$/.piolibdeps" />
    </excludeRoots>
  </component>
</project>
```

**Comment by ivankravets** [comment]
Please re-test with the latest PIO Core and re-init project:
```
pio upgrade --dev
pio init
```
