### ISSUE TITLE
Add Board: SiFive HiFive1

### ISSUE THREAD

**Issue by martin-robert-fink** [platformio/platformio-core#1361]
https://www.sifive.com/products/hifive1/

**Comment by ivankravets** [comment]
Could you provide us this board?

**Comment by martin-robert-fink** [comment]
Sure.  Where (and to who) should I send it?

**Comment by ivankravets** [comment]
Please mail ikravets at platformio org

**Comment by ivankravets** [comment]
Added in https://platformio.org/platforms/riscv
