### ISSUE TITLE
attachInterrupt function arduino

### ISSUE THREAD

**Issue by dvera2004** [platformio/platformio-core#1364]
For this:
  attachInterrupt (digitalPinToInterrupt(2), myFuction, FALLING);

The compiler return:
src/main.cpp:25:45: error: 'myFunction' was not declared in this scope
attachInterrupt(digitalPinToInterrupt(2), myFunction, FALLING);

I have defined myFunction correctly.

Then same code in arduino IDE compile without any problem.

Thanks

**Comment by ivankravets** [comment]
attachInterrupt(digitalPinToInterrupt(2), &myFunction, FALLING);

**Comment by dvera2004** [comment]
Ivan,

thanks for your fast support.

I added the "&" but the issue still in there:

src/main.cpp:25:46: error: 'myFunction' was not declared in this scope
attachInterrupt(digitalPinToInterrupt(2), &myFunction, FALLING);
^
*** [.pioenvs/nanoatmega328/src/main.o] Error 1

Regards

**Comment by ivankravets** [comment]
Could you share a simple INO files to reproduce this issue?

**Comment by dvera2004** [comment]
Yes, 
[main.cpp.zip](https://github.com/platformio/platformio-core/files/1727559/main.cpp.zip)

**Comment by dvera2004** [comment]
Ivan

I found the problem.
I'm using the default name for the source file, main.cpp (suggested by software), and the compiler maybe check the extension of file for compile. I renamed to main.ino and compiled without any problem.
When a new project is started and selecting an arduino board, atom must suggest a main.INO by default.

Thanks

**Comment by ivankravets** [comment]
Ah... INO format is not a valid C/C++ file. It should die. People think that code in C but "INO Preprocessor" converts their NONAME format to valid C/C++ on-the-fly. As result, you can have a lot of issues.
See http://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually

**Comment by dvera2004** [comment]
Ivan thanks for your kindly support.
I'm not understanding well about source code.

In arduino IDE every time I put all necessary "#include <Arduino.h>", compile and works, and the final version of .ino looks like a converted by hand ino file to c++.

The same code in Atom, not work like a c++ extension, but look like converted to c++ file, but when I only renamed the extension of the file and compile without any problem and the board works too.

**Comment by ivankravets** [comment]
Indeed, you can use that file without modifications with PIO too. Just rename it from CPP to INO.

But... Advanced features, such as code linting and code completion will not work because INO is not CPP file.

**Comment by dvera2004** [comment]
OK.

OK.

I will write all code using a .cpp file for have "code completion" service and in the last moment I will change to INO if is needed.

Thanks again.

**Comment by zalexzperez** [comment]
Is there really no fix for this? I just go the same error, changing the extension from .cpp to .ino allowed me to compile the code successfully.

**Comment by ivankravets** [comment]
@zalexzperez just add `&` before callback

**Comment by zalexzperez** [comment]
@ivankravets Well, I already tried that and also writing the myFunction() on top of void setup but I get the same error...

**Comment by ivankravets** [comment]
please provide a simple code to reproduce this issue. Also, be careful with spaces before function line. New line should start with a RETURN type of a function

**Comment by ivankravets** [comment]
@zalexzperez I see. You can't use INO source code as C++ without modification. INO is not valid C++ code, you need to convert your project from INO to CPP manually. See Please read http://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually

**Comment by zalexzperez** [comment]
@ivankravets Hmm... that sounds like a hassle. I'm sorry, but I'm new to the IDE world.

Anyway, what do I lose by changing the file extension from .cpp to .ino ? I see everything is working perfectly after doing so. Code completion still works (for instance, I write analogWr and the full command suggestion appears)

**Comment by ivankravets** [comment]
> I'm sorry, but I'm new to the IDE world

You can stay with INO in this case (Arduino IDE compatible mode).

**Comment by mattmunee** [comment]
> @ivankravets Okay. But right now I'm struggling to add external libraries after changing the extension to .ino.
> I pasted the library source code in a subfolder under /lib folder, then use the command #include "FastLED.h" and I'm getting the following error:
> 
> #include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\Users\Alejandro\Documents\PlatformIO\Projects\Prueba004\src\main.ino) will be provided by the Tag Parser.
> cannot open source file "FastLED.h"
> ![screenshot](https://user-images.githubusercontent.com/38706594/40690690-5b02d46e-63a8-11e8-9df6-28eefc3421f1.png)

Have you fixed this issue?  I'm struggling to get files in my "lib" folder included.  Platformio doesn't seem to recognize them.  The README makes me think I can just put source into the "lib" folder and include it in my project main.cpp with no issue.  That doesn't seem to be the case. (PlatformIO version 4.3.2a1)

**Comment by ivankravets** [comment]
1. I'm not sure that VSCode's C/C++ extension support INO format. INO is not a CPP file and you should avoid using INO files. See https://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually
