### ISSUE TITLE
Home: Could not load recent projects, Libraries, Boards

### ISSUE THREAD

**Issue by Akshit09** [platformio/platformio-core#1368]
Server error
Unable to load the boards installed or the prebuild libraries.
Tried reinstalling the platformIO but no luck.

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type
```
pio home --port 8888
```

Do you see any errors when trying to open Boards or LIbraries?

**Comment by ivankravets** [comment]
Please reopen if you still need help
