### ISSUE TITLE
Please update esptool to v0.4.12

### ISSUE THREAD

**Issue by omersiar** [platformio/platformio-core#1370]
- [x] PlatformIO Core.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 7 32-Bit

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.5.2b2

### Description of problem

Can not upload SPIFFS binary to ESP8266 module with built-in **esptool v0.4.9** but **can** upload with **esptool v0.4.12** 

At least with my setup below:

ESP-12 Module with 4MByte Flash Chip but `Flash_mode` is `dout`

```ini
[env:dout]
platform = https://github.com/platformio/platform-espressif8266.git
framework = arduino
board = esp12e
board_flash_mode = dout
upload_resetmethod = ck
build_flags = -Wl,-Teagle.flash.4m.ld
upload_speed = 921600
```

#### Steps to Reproduce

1. Build a SPIFFS binary with -Wl,-Teagle.flash.4m.ld build_flag. This will produce 3MB SPIFFS binary
2. `pio run -e dout -t uploadfs`

### Actual Results

```
warning: espcomm_send_command: didn't receive command response
warning: espcomm_send_command(FLASH_DOWNLOAD_BEGIN) failed
```

### Expected Results

**Flash without an error**

### Additional info

My 3 hours trial and error, did not blame the version so i kept trying with different environment, when Arduion IDE did not complain, and flashed successfully i immediately checked versions.

Please update esptool to v0.4.12

**Comment by ivankravets** [comment]
Updated, please run `pio update`
