### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by maxiclo** [platformio/platformio-core#1372]
PIO Core Call Error: Platform /home/maxiclo/.platformio/platforms/nordicnrf51
--------
Updating nordicnrf51                     @ 2.8.0          [3.0.1]
Uninstalling nordicnrf51 @ 2.8.0: 	[OK]
PlatformManager: Installing nordicnrf51 @ 3.0.1
Downloading
Downloading
Unpacking
Unpacking
Warning! Package Mirror: Package version 3.0.0 doesn't satisfy requirements 3.0.1
Looking for another mirror...
Downloading
Downloading
Unpacking
Unpacking
Warning! Package Mirror: Package version 3.0.0 doesn't satisfy requirements 3.0.1
Looking for another mirror...

Error: Could not install 'nordicnrf51' with version requirements '3.0.1' for your system 'linux_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Thanks! Fixed. Please try reinstalling this dev/platform.
