### ISSUE TITLE
PIOHome changes (add project name)

### ISSUE THREAD

**Issue by DarioDaF** [platformio/platformio-core#1377]
All the code regarding the home screen (server) seems to point to [contrib-piohome](http://dl.platformio.org/packages/contrib-piohome-0.6.1.tar.gz) and that package is minified (obfuscated).
I would like to contribute to the project adding a project name feature (since actually on vscode and probably to all other editor because the page is in this external package the name is a timestamp) but, I cannot find the source of the home page.
If it is closed source is there an alternative package which can be used in substitution and altered to implement this feature?

**Comment by ivankravets** [comment]
We will add it soon. See https://github.com/platformio/platformio-core/issues/1312
