### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by EvgenySytko** [platformio/platformio-core#1379]
PIO Core Call Error: PlatformManager: Installing espressif32
Downloading...
Unpacking...
espressif32 @ 0.12.0 has been successfully installed!
PackageManager: Installing toolchain-xtensa32 @ ~1.50200.2

Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] 
Looking for another mirror...
Downloading...
Unpacking...
Warning! Package Mirror: [Error 5] 
Looking for another mirror...

Error: Could not install 'toolchain-xtensa32' with version requirements '~1.50200.2' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
