### ISSUE TITLE
OpenOCD does not want to download no matter how many times i try

### ISSUE THREAD

**Issue by KarelKruger** [platformio/platformio-core#1387]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 1-

**PlatformIO Version** (`platformio --version`): 3.5.2b5

### Description of problem
When trying to upload any application the following occures every time
![image](https://user-images.githubusercontent.com/36231192/36598204-1786f24a-18b4-11e8-9f02-3083dd71f948.png)

#### Steps to Reproduce

1. upload : PackageManager: Installing tool-openocd @ ~1.1000.0
Downloading  [#-----------------------------------]    3%
Error: Please read http://bit.ly/package-manager-ioerror
Warning! Package Mirror: [Errno 0] Error
Looking for another mirror...
Downloading  [------------------------------------]    0%
Error: Please read http://bit.ly/package-manager-ioerror
Warning! Package Mirror: [Errno 0] Error
Looking for another mirror...
Error: Could not install 'tool-openocd' with version requirements '~1.1000.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
2.
3.

### Actual Results
code did not flash

### Expected Results
flashed code to board

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:waveshare_ble400]
platform = nordicnrf51
board = waveshare_ble400
framework = arduino

```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

void setup() {
    // put your setup code here, to run once:
    pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
    // put your main code here, to run repeatedly:
    digitalWrite(LED_BUILTIN, HIGH);
    delay(1000);
    digitalWrite(LED_BUILTIN, LOW);
    delay(1000);
}

```
![image](https://user-images.githubusercontent.com/36231192/36598276-500bcfc8-18b4-11e8-862a-69f6732306a6.png)

**Comment by ivankravets** [comment]
Please read http://bit.ly/package-manager-ioerror
