### ISSUE TITLE
Uploading to ESP32 fails when ESP32-specific upload flags are added

### ISSUE THREAD

**Issue by egueli** [platformio/platformio-core#1389]
What kind of issue is this?

### Configuration

**Operating system**: Mac OS X 10.13.3

**PlatformIO Version** (`platformio --version`): 3.5.2b4

### Description of problem

Uploading to ESP32 fails when the `auth` option for OTA uploading is used.

#### Steps to Reproduce

1. Add a line like `upload_flags = --auth 'xyz'` to specify the authentication password for OTA uploads, as per http://docs.platformio.org/en/latest/platforms/espressif32.html#authentication-and-upload-options .
2. `pio run -t upload`

### Actual Results

The upload fails with the message `esptool write_flash: error: argument <address> <filename>: Must be pairs of an address and the binary filename to write there`

### Expected Results

The upload starts and succeeds.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32]
platform = espressif32
framework = arduino
board = lolin32
upload_flags = --auth='xyz'
```

**Source file to reproduce issue:**
No-op Arduino code:
```cpp
void setup() {}
void loop() {}
```

### Additional info

The same upload flags work fine with the `espressif8266` environment.

PlatformIO is probably placing the non-standard upload flags in the wrong position in the esptool.py command line: running `pio -v run -t upload` shows that the command line is `"/Users/enrico/.platformio/penv/bin/python" "/Users/enrico/.platformio/packages/framework-arduinoespressif32/tools/esptool.py" --before default_reset --after hard_reset --chip esp32 --port "/dev/cu.SLAB_USBtoUART" --baud 115200 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 40m --flash_size detect 0x1000 /Users/enrico/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_40m.bin 0x8000 /private/tmp/piotest/.pioenvs/esp32/partitions.bin 0xe000 /Users/enrico/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 --auth 'xyz' .pioenvs/esp32/firmware.bin`

Note that other upload options like `upload_speed` don't make the upload fail.

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif32/issues
