### ISSUE TITLE
digitalWrite

### ISSUE THREAD

**Issue by anwarbashir** [platformio/platformio-core#1391]
When I use Platform IO with Visual Studio Code and I try the use the analogWrite command it is not available (see example code below).  I am using a WEMOS 32 board, why is analogWrite not available?

#include <Arduino.h>

int ledPin = 9;      // LED connected to digital pin 9
int analogPin = 3;   // potentiometer connected to analog pin 3
int val = 0;         // variable to store the read value

void setup()
{
  pinMode(ledPin, OUTPUT);   // sets the pin as output
}

void loop()
{
  val = analogRead(analogPin);   // read the input pin
  analogWrite(ledPin, val / 4);  // analogRead values go from 0 to 1023, analogWrite values from 0 to 255
}

**Comment by per1234** [comment]
Why did you title the issue "digitalWrite" when the problem is with `analogWrite`?

From https://github.com/espressif/arduino-esp32/blob/master/README.md:
>## Development Status
>Most of the framework is implemented. Most noticable is the missing analogWrite. While analogWrite is on it's way, there are a few other options that you can use:
>- 16 channels [LEDC](cores/esp32/esp32-hal-ledc.h) which is PWM
>- 8 channels [SigmaDelta](cores/esp32/esp32-hal-sigmadelta.h) which uses SigmaDelta modulation
>- 2 channels [DAC](cores/esp32/esp32-hal-dac.h) which gives real analog output
