### ISSUE TITLE
Logs from platformio are marked as spam in community forum.

### ISSUE THREAD

**Issue by mihai331** [platformio/platformio-core#1392]
After creating my first question on Platformio community forum, it was marked as spam.
The offending lines appear to be two lines recognized as links:

File "C:\Users\name\.platformio\packages\framework-arduinoespressif32\tools\esptool.py", line 227, in write
self._port.write(buf)
File "c:\users\name.platformio\penv\lib\site-packages\serial\serialwin32.py", line 323, in write
raise writeTimeoutError
serial.serialutil.SerialTimeoutException: Write timeout

Apparently the two lines starting with "File" are marked as links and trigger the spam protection which blocked the thread.

Would it be possible to improve the spam filter to better recognize links?

Thank you!

**Comment by ivankravets** [comment]
https://community.platformio.org/t/esp32-write-timeout/3517
