### ISSUE TITLE
Failure to save files because "too many files open"

### ISSUE THREAD

**Issue by ssilverman** [platformio/platformio-core#1395]
### Configuration

**Operating system**:
OSX 10.13.3

**PlatformIO Version** (`platformio --version`):
Home 0.6.1, Core 3.5.2b5

### Description of problem
Twice now, the IDE would not save files because there were "too many files open".

#### Steps to Reproduce
Use the IDE for some period of time, unknown.

### Actual Results
Failures to save files.

### Expected Results
The files save.

**Comment by ivankravets** [comment]
If you use Atom, please file an issue here https://github.com/atom/atom

For VSCode, here https://github.com/Microsoft/vscode/issues
