### ISSUE TITLE
STM32F103ZET

### ISSUE THREAD

**Issue by jourjine** [platformio/platformio-core#1397]
Hi

How can i edit / add the correct description of the MCU STM32F103ZET because I  have compile errors.

```
src / main.cpp: In function 'void setup ()':
src / main.cpp: 5: 13: error: 'PF0' was not declared in this scope
pinMode (PF0, OUTPUT);
^ ~~
src/main.cpp:5:13: note: suggested alternative: 'PE0'

```
Z has more ports than V series

Regards.

**Comment by ivankravets** [comment]
Please file a future request here https://github.com/platformio/platform-ststm32/issues
