### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by GZandstra** [platformio/platformio-core#1399]
PIO Core Call Error: Platform C:\Users\gz9660\.platformio\platforms\ststm32@src-15e0e87f41a00aa2f9602f71367ac29c
--------
Updating ststm32                         @ d5cbaf0        [f66dd09]
git version 2.7.2.windows.1

From https://github.com/platformio/platform-ststm32
   143ed71..f66dd09  develop    -> origin/develop
 * [new tag]         v4.0.1     -> v4.0.1
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v1.0.0     -> v1.0.0
 * [new tag]         v1.0.1     -> v1.0.1
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.2.0     -> v1.2.0
 * [new tag]         v1.3.0     -> v1.3.0
 * [new tag]         v1.3.1     -> v1.3.1
 * [new tag]         v1.4.0     -> v1.4.0
 * [new tag]         v1.5.0     -> v1.5.0
 * [new tag]         v1.6.0     -> v1.6.0
 * [new tag]         v1.7.0     -> v1.7.0
 * [new tag]         v1.8.0     -> v1.8.0
 * [new tag]         v1.8.1     -> v1.8.1
 * [new tag]         v2.0.0     -> v2.0.0
 * [new tag]         v2.1.0     -> v2.1.0
 * [new tag]         v3.0.0     -> v3.0.0
 * [new tag]

**Comment by ivankravets** [comment]
Please upgrade Git client, remove `C:\Users\gz9660.platformio\platforms\ststm32@src-15e0e87f41a00aa2f9602f71367ac29c` folder and start building project again.
