### ISSUE TITLE
Only the libraries used by the current configuration should be compiled

### ISSUE THREAD

**Issue by VioletGiraffe** [platformio/platformio-core#1407]
I have an Arduino project with multiple configurations. Different configurations use different libraries, and the problem is that PIO compiles everything it can find in .piolibdeps.  It means that if I have a library that's only compatible with some of the configurations, the other configurations will fail to build until I manually clean the .piolibdeps folder.

Suggested solution: wipe .piolibdeps on first build after environment variables have changed. Or, more correctly, wipe the libraries specified as `git` repos and/or as references to the PIO library registry.

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce this issue?

**Comment by VioletGiraffe** [comment]
Sure. Check it out: https://github.com/VioletGiraffe/platformio-1407-demo
See travis.yml for the scenario that triggers the error. And here's what it looks like (scroll to the bottom):
https://travis-ci.org/VioletGiraffe/platformio-1407-demo

**Comment by ivankravets** [comment]
Please read http://docs.platformio.org/en/latest/librarymanager/ldf.html#storage. 

You need http://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-ignore

**Comment by VioletGiraffe** [comment]
Hm. Regarding `lib_ignore`: if "The correct value for this option is library name (not folder name)", what is the library name for a GitHub repo library?

And don't you think that _for the user-specified dependencies_, only those specified by the current environment should be visible?

**Comment by ivankravets** [comment]
> what is the library name for a GitHub repo library?

You should see library name in build log. See https://travis-ci.org/VioletGiraffe/platformio-1407-demo/jobs/349887944#L689

Also, you can control library name with `<name>=repository`. See examples http://docs.platformio.org/en/latest/userguide/lib/cmd_install.html

> only those specified by the current environment should be visible?

By default, PlatformIO scans dependency automatically. If you would like to manage them manually, please turn off LDF http://docs.platformio.org/en/latest/librarymanager/ldf.html#ldf-mode

**Comment by VioletGiraffe** [comment]
>You should see library name in build log. 
Thanks.

> If you would like to manage them manually, please turn off LDF
I got that idea from your previous link, but it brought with it a host of issues I don't feel like dealing with. For instance, I couldn't get it to find "SPI.h" (any hints?).
What I'm proposing is a fully automatic solution that does not require any manual labor from the programmer, and does not induce any issues.

**Comment by ivankravets** [comment]
> For instance, I couldn't get it to find "SPI.h" (any hints?).

lib_deps = SPI
