### ISSUE TITLE
Error: You are not connected to the Internet

### ISSUE THREAD

**Issue by zayden** [platformio/platformio-core#1408]
PIO Core Call Error: Error: You are not connected to the Internet.
If you build a project first time, we need Internet connection to install all dependencies and toolchain.

**Comment by kemaldede** [comment]
I have internet connection but I can not load board lists and libraries

**Comment by ivankravets** [comment]
What is your OS?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by abdulnafea-auf** [comment]
I have also the same problem but while trying to install a library, I am working on Windows 10 education 64-bit.

**Comment by jeffminton** [comment]
I am having this same issue on linux using the vs code ide

**Comment by ivankravets** [comment]
@jeffminton could you reproduce this issue again?

**Comment by gerhardh** [comment]
I Have the same problem using VS Code on macOS Mojave. I ave a very good 100 Mb/s Internet connection. However this problem shows up every few weeks for a few days.

**Comment by ivankravets** [comment]
When do you see this message? After which command?

**Comment by gerhardh** [comment]
I got this message whenever I tried to list either boards or frameworks or libraries in PIO Home. 
Problem is solved. 
Reason was interference from Little Snitch.
Had to delete some Little Snitch rules and PIO work properly again.
Thanks
