### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by furas38** [platformio/platformio-core#1410]
PIO Core Call Error: Library Storage: C:\Users\furas\.platformio\lib
Updating MqttConnector                   @ 0.99.1         [1.0.4]

Uninstalling MqttConnector @ 0.99.1: 	[OK]
Looking for MqttConnector library in registry

Error: Library `{'requirements': u'1.0.4', 'name': 'MqttConnector'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': u'1.0.4', 'name': 'MqttConnector'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
The correct name of dependency is `CMMC MQTT Connector`. See https://github.com/cmmakerclub/MQTT-Connector/blob/master/library.json#L2
