### ISSUE TITLE
Feature request: Specify maximum size of binary

### ISSUE THREAD

**Issue by someburner** [platformio/platformio-core#1412]
Right now it appears pio only checks size before uploading. For CI and OTA purposes, it would be really nice if one could specify size as a build parameter and to fail the build if it is too large. May as well add minimum feature too as a sanity check for similar purposes.

**Comment by ivankravets** [comment]
See

* http://docs.platformio.org/en/latest/faq.html#firmware-memory-size-explanation-text-data-and-bss
* http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html

You can create own POST action, call gcc-size, read data and analyze them.

**Comment by someburner** [comment]
Seen it.. I cannot get it to execute within a virtual environment, but even if I could, it seems like a lot of code duplication and mess to have it in a project when it could be added as its own flag.

**Comment by me21** [comment]
It can be done by providing custom linker script.

**Comment by ivankravets** [comment]
Please use `pio run -t checkprogsize` for CI/CD
