### ISSUE TITLE
Home: Error occurred while requesting content from https://github.com/Timvrakas/SRADio-GFSK/raw/master/lib/Hermes/library.json

### ISSUE THREAD

**Issue by redscientific** [platformio/platformio-core#1415]
Could not fetch content `https://github.com/Timvrakas/SRADio-GFSK/raw/master/lib/Hermes/library.json`

**Comment by ivankravets** [comment]
If you use macOS Sierra, please update SSL library

See https://github.com/platformio/platformio-core/issues/1390
