### ISSUE TITLE
After a build on HIGH SIERRA : 10.13.3 and Visual Studio 

### ISSUE THREAD

**Issue by SSkedge** [platformio/platformio-core#1418]
After a build on HIGH SIERRA : 10.13.3 and Visual Studio Code: Version 1.20.1 (1.20.1)

The code helper has many processes running and doesnt seem to exit them. This means the build button or key bindings don't always work. Only solution ive found is to kill the process and restart visual studio code.

Platformio: Home 0.7.0, Core 3.5.2rc3

**Comment by ivankravets** [comment]
Please provide a screenshot and move issue to https://github.com/platformio/platformio-vscode-ide
