### ISSUE TITLE
"UnicodeDecodeError: 'ascii' codec can't decode byte"

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#143]
Problem occurs under Windows OS and for environment where configurable encoding is used (non UTF-8 paths). 

https://docs.python.org/2/howto/unicode.html#unicode-filenames

``` python
import sys
sys.getdefaultencoding()
```

Try this hook for `platformio.util.get_home_dir`:

``` python
def get_home_dir():
    home_dir = _get_projconf_option_dir(
        "home_dir",
        join(expanduser("~"), ".platformio")
    )

    import sys
    home_dir = home_dir.decode(sys.getfilesystemencoding())

    if not isdir(home_dir):
        os.makedirs(home_dir)

    assert isdir(home_dir)
    return home_dir
```

How to reproduce? Just create account with "non-UTF-8" chars (Cyrillic is good candidate).

**Comment by ivankravets** [comment]
We can fix this issue within PlatformIO source code, but problem still exists within SCons source code.

To avoid this issue please re-define PlatformIO [home_dir](http://docs.platformio.org/en/latest/projectconf.html#home-dir) in your project configuration file [platformio.ini](http://docs.platformio.org/en/latest/projectconf.html). PlatformIO uses user's home directory by default, which can contain "non-latin" characters. The easy way is to set ``home_dir`` with path, which doesn't contain "non-latin" chars:

**platformio.ini**
```ini
[platformio]
home_dir = C:\.platformio

[env:your_env_here]
....
```

**Comment by ivankravets** [comment]
Add this issue to http://docs.platformio.org/en/latest/faq.html#windows-unicodedecodeerror-ascii-codec-can-t-decode-byte

**Comment by me21** [comment]
@ivankravets This error is also triggered by storing project in path containing non-latin characters. The workaround is (obviously) to store projects elsewhere or creating symlink (directory junction) so that PlatformIO does not have to deal with non-latin paths.

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart VSCode. Does it work now?
