### ISSUE TITLE
`include_dir` option in platformio.ini not recognized

### ISSUE THREAD

**Issue by Piroro-hs** [platformio/platformio-core#1433]
### Configuration

**Operating system**: Xubuntu 17.10 64bit

**PlatformIO Version** (`platformio --version`): `PlatformIO, version 3.5.2rc4`

### Description of problem

The `include_dir` option in the `platformio.ini` is not recognized by PlatformIO core.

#### Steps to Reproduce

1. Create `platformio.ini` with following contents.
   ```ini
   [platformio]
   include_dir = Inc
   ```

2. Run `pio run`.

### Actual Results

``Warning! Ignore unknown `include_dir` option in `[platformio]` section``

### Expected Results

According to the [docs](http://docs.platformio.org/en/latest/projectconf/section_platformio.html#include-dir), it configures a path to project’s header files.

**Comment by ivankravets** [comment]
Thanks! Please open PIO IDE Terminal and type `pio upgrade --dev`. Does it work now?

**Comment by Piroro-hs** [comment]
It works! Thank you.
