### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by motley197** [platformio/platformio-core#1437]
PIO Core Call Error: The next files/directories have been created in C:\Users\motley\Documents\PlatformIO\Projects\Blinky
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'toolchain-xtensa32' with version requirements '~1.50200.2' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
