### ISSUE TITLE
Error: Could not install 'framework-esp8266-rtos-sdk' with version requirements '>=1.5.0-beta' for your system 'darwin_x86_64'

### ISSUE THREAD

**Issue by AdrianBaqueiro** [platformio/platformio-core#1441]
PIO Core Call Error: The next files/directories have been created in /Users/adrian/Proyect Tank/Tank
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'framework-esp8266-rtos-sdk' with version requirements '>=1.5.0-beta' for your system 'darwin_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Could you check Internet connection? or restart IDE?

**Comment by ivankravets** [comment]
Please reopen if you still need help
