### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ronyef** [platformio/platformio-core#1451]
PIO Core Call Error: The next files/directories have been created in /Users/ronyefendy/Documents/PlatformIO/Projects/Fuel
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing atmelavr

Error: Detected unknown package 'atmelavr'

**Comment by ivankravets** [comment]
Please check your internet connection and install Atmel AVR dev/platform manually using PIO Home > Platforms
