### ISSUE TITLE
PIO Home board selection in project wizard and sort of project folders

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio-core#1454]
Home v0.8.1
Core v3.5.3a3

The search function for boards in the project wizard should ignore lower/upper cases and spaces, e.g.:
"mbed lpc1768" gives no result, also "mbed LPC 1768", only "mbedLPC1768" gives the right result.

The sort function of the folders and data in the location depends on lower/upper cases, it confusing because the os (macOS) sorts without depends of cases.
<img width="601" alt="sort" src="https://user-images.githubusercontent.com/6450325/37522634-c7126070-2924-11e8-86bf-9795b26ff2e0.png">

**Comment by ivankravets** [comment]
> only "mbedLPC1768" gives the right result.

Are you sure? It does not work for me. The search is case-insensitive.

![screen shot 2018-03-16 at 23 30 52](https://user-images.githubusercontent.com/1760209/37545614-182ccf7a-2972-11e8-84f4-28da05a54ecc.png)

**Comment by sstaub** [comment]
Interesting, now it works. Maybe there is an complete restart necessary for VSCode after an update.

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart IDE.
