### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by leobel96** [platformio/platformio-core#1456]
I'm trying to compile the "NMEAsimple.ino" example from https://github.com/SlashDevin/NeoGPS with platformio in VSCode for NodeMCU board but I'm getting a lot of:
`error: 'constexpr' needed for in-class initialization of static data member 'const float`
Compiling it with Arduino IDE returns no error so, I think, it's a PlatformIO compiler error.

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif8266

**Comment by leobel96** [comment]
Ok, I've done it
