### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by wisegeeksrules** [platformio/platformio-core#1457]
PIO Core Call Error: The next files/directories have been created in /home/object-undefined/Documents/PlatformIO/Projects/180318-112014-wiringpi-blink
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: PlatformIO temporary does not support cross-compilation for WiringPi framework. Please use PIO Core directly on Raspberry Pi

**Comment by ivankravets** [comment]
Also, please take a look at PIO Remote http://docs.platformio.org/en/latest/plus/pio-remote.html

You can start PIO Remote agent on RPi side and program it from anywhere in the world.
