### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by 1330154737** [platformio/platformio-core#1460]
PIO Core Call Error: The next files/directories have been created in C:\Users\junhao\Documents\PlatformIO\Projects\test01
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing espressif8266
Downloading
Downloading
Unpacking
Unpacking
espressif8266 @ 1.6.0 has been successfully installed!
PackageManager: Installing toolchain-xtensa @ ~1.40802.0

Downloading
Downloading
Warning! Package Mirror: 
Looking for another mirror...
Downloading
Downloading
Warning! Package Mirror: 
Looking for another mirror...

Error: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
