### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by gittiago12** [platformio/platformio-core#1463]
PIO Core Call Error: The next files/directories have been created in C:\Users\Tiago\Documents\PlatformIO\Projects\180319-204001-uno
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'framework-arduinoavr' with version requirements '~1.10620.2' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please check Please try this solution -> http://bit.ly/faq-package-manager
