### ISSUE TITLE
Home: Could not load latest Tweets

### ISSUE THREAD

**Issue by Jevby** [platformio/platformio-core#1466]
HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/profiles/show/PlatformIO_Org/timeline/tweets?include_available_features=1&include_entities=1&include_new_items_bar=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000054D7DA0>: Failed to establish a new connection: [Errno 10060] ',))

**Comment by ivankravets** [comment]
Do you have a problem with https://twitter.com ?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1465
