### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by stalek71** [platformio/platformio-core#1468]
Server error when I try to log in using temporary password.
The account I was using has email stankiewiczAL at yahoo com

**Comment by ivankravets** [comment]
What is your PIO Core version? IDE?

**Comment by stalek71** [comment]
I use VS Code 1.21.1 and PlatformIO IDE for VSCode in version 0.14.0

**Comment by stalek71** [comment]
Win 10 64

**Comment by ivankravets** [comment]
1) VSCode > Tasks > PlatformIO: Upgrade PIO Core
2) VSCode > Tasks > PlatformIO: Upgrade packages, libraries...

Restart VSCOde. Does it work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help
