### ISSUE TITLE
lib folder is automatically created everytime platformio.ini is modified

### ISSUE THREAD

**Issue by theagoliveira** [platformio/platformio-core#1473]
What kind of issue is this?

[x] PlatformIO Core. If you’ve found a bug, please provide an information below.

-----------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu 17.10

**PlatformIO Version** (`platformio --version`): 3.5.3a3

### Description of problem

I'm using a folder called **libraries** (instead of **lib**) for my private libraries, with the option **platformio.ini > [platformio] > lib_dir = libraries**. Everything is working fine; however, everytime I modify and save the platformio.ini file a **lib** folder appears inside the project's folder. I'm also using custom source folders with the **src_dir** option, but no **src** folder gets created (which is the expected behavior). Is there a way to stop this **lib** folder from being created?

#### Steps to Reproduce

1. Create a new project;
2. Add lib_dir = libraries to platformio.ini file;
3. Delete lib folder;
4. Save platformio.ini file.

### Actual Results

A **lib** folder appears.

### Expected Results

No **lib** folder appears, since I'm not using a folder called **lib** inside my project anymore.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[platformio]
lib_dir = libraries
; src_dir = src1
src_dir = src2

[env:uno]
platform = atmelavr
board = uno
framework = arduino
```

**Comment by ivankravets** [comment]
Please retest with the latest dev version via `pio upgrade --dev`.
