### ISSUE TITLE
Home: Could not load latest Tweets

### ISSUE THREAD

**Issue by epsimatic** [platformio/platformio-core#1474]
I've blocked your app access to twitter.com and this pops up every time I open «Home» page. I doupt it's so important message to show it blocking a big part of the main view

HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/profiles/show/PlatformIO_Org/timeline/tweets?include_available_features=1&include_entities=1&include_new_items_bar=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10c54d6d0>: Failed to establish a new connection: [Errno 64] Host is down',))

**Comment by ivankravets** [comment]
Sorry, we will fix it ASAP.

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio update`. Restart IDE.
