### ISSUE TITLE
Board: EPS8622 with SDK v2.0 and DeautherPatch

### ISSUE THREAD

**Issue by schinfo** [platformio/platformio-core#1475]
Can you include this Boards into PlatformIO.

Here is the link for the additional boards from the Arduino IDE:.

http://phpsecu.re/esp8266/package_deauther_index.json

https://github.com/tobozo/Arduino

**Comment by tobozo** [comment]
Actually it's a bundle of custom boards hooked on the SDK 2.0.0 where some files have been patched to expose the necessary functions for the Deauther to work, so it's not limited to the boards.

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif8266/issues
