### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mpablo135** [platformio/platformio-core#1476]
PIO Core Call Error: The next files/directories have been created in C:\SPB_Data\Documents\PlatformIO\Projects\Test_BP1
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Detected unknown package 'toolchain-xtensa32'

**Comment by ivankravets** [comment]
Please try one of these solutions http://docs.platformio.org/en/latest/faq.html#package-manager

If it didn't help, please reopen issue.
