### ISSUE TITLE
pio lib install stop after download 100% (VSC+PIOIDE+PIOCORE)

### ISSUE THREAD

**Issue by reinaldoaf** [platformio/platformio-core#1477]
Hi, 

I have installed VSC+PIO on win10 and don´t have problens, but when i install on WIN7 + Py 2.xx + PIO IDE, when I try download librari (for NODEMCU 1.0 ESP-12x with ARDUINO platform) we get this

G:\Projetos\NODEMCU_TEST>pio lib install 1480
Library Storage: G:\Projetos\NODEMCU_TEST\.piolibdeps
LibraryManager: Installing id=1480
Downloading  [####################################]  100%

and stop, I try change directory of project, change disk (C: D: G:) and try open VSC with administrator rights, but ever time same problem...

any else have any idea about? I only get this msg on terminal...

thks for help

**Comment by ivankravets** [comment]
Try one of http://docs.platformio.org/en/latest/faq.html#package-manager

If it didn't help, please reopen this issue.
