### ISSUE TITLE
Home: Could not load latest Tweets

### ISSUE THREAD

**Issue by vknector** [platformio/platformio-core#1480]
HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/profiles/show/PlatformIO_Org/timeline/tweets?include_available_features=1&include_entities=1&include_new_items_bar=true (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000551A320>: Failed to establish a new connection: [Errno 10060] ',))

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio update`. Restart IDE.
