### ISSUE TITLE
Automatic detection of port on upload

### ISSUE THREAD

**Issue by pelikhan** [platformio/platformio-core#15]
First, let's just say that this project is awesome. This is some awesome work.

One feature that I missed moving from ion was the automatic detection of upload port. It's a very nifty feature that makes things a tad simpler.

**Comment by DesktopMan** [comment]
I realise this issue is old, but is this working correctly? What criteria does it use to find the correct upload port?

`Looking for upload port...
Auto-detected: /dev/ttyACM0`

ttyACM0 is not my device, the correct port is ttyACM3.

**Comment by ivankravets** [comment]
@DesktopMan could you provide an output of `pio device list` command?

**Comment by DesktopMan** [comment]
Here's the device list:

/dev/ttyACM3
Hardware ID: USB VID:PID=2341:0243 SER=95432313438351608221 LOCATION=3-1.2.1
Description: Genuino Uno

/dev/ttyACM2
Hardware ID: USB VID:PID=03F0:3D1D SER=285E91F4229B54M0 LOCATION=1-1.5
Description: HP hs2350 HSPA+ MobileBroadband - HP hs2350 HSPA+ Mobile Broadband NMEA

/dev/ttyACM1
Hardware ID: USB VID:PID=03F0:3D1D SER=285E91F4229B54M0 LOCATION=1-1.5
Description: HP hs2350 HSPA+ MobileBroadband - HP hs2350 HSPA+ Mobile Broadband Data Modem

/dev/ttyACM0
Hardware ID: USB VID:PID=03F0:3D1D SER=285E91F4229B54M0 LOCATION=1-1.5
Description: HP hs2350 HSPA+ MobileBroadband - HP hs2350 HSPA+ Mobile Broadband Modem

**Comment by ivankravets** [comment]
> What criteria does it use to find the correct upload port?

See https://github.com/platformio/platformio-core/blob/develop/platformio/builder/tools/pioupload.py#L114

> Here's the device list:

Thank you, I've just added Genuino Uno's PID/VID to board manifest. See

* https://github.com/platformio/platform-atmelavr/commit/ccf12494820a8bf886b63144471afe63b63163b5

**Comment by ivankravets** [comment]
Temporary solution is to manually specify `upload_port` in `platformio.ini` while new version of Atmel AVR development platform is not released.

* http://docs.platformio.org/en/latest/projectconf.html#upload-port

**Comment by DesktopMan** [comment]
Any idea how long it takes for these changes to show up in production? I'm getting 150 students next week and this would save me hours of support.

**Comment by ivankravets** [comment]
@DesktopMan, done! Please run `pio update` and re-test. Thanks!

**Comment by DesktopMan** [comment]
Thanks, working. This also seems to be the case for Genuino 101. (intel_arc32):

```
Hardware ID: USB VID:PID=8087:0AB6 SER=AE6771SQ55201EZ LOCATION=3-1.2.1
Description: GENUINO 101
```

**Comment by ivankravets** [comment]
@DesktopMan It should work for Genuino 101, see

* https://github.com/platformio/platform-intel_arc32/blob/develop/boards/genuino101.json#L7

**Comment by mgawron86** [comment]
Hi. I ordered new arduino uno board and it seems that auto detection does not work for my board version. @ivankravets Could you update boards/uno.json ?
Terminal output:
```
/dev/ttyUSB1
------------
Hardware ID: USB VID:PID=1A86:7523 LOCATION=1-1.2
Description: USB2.0-Serial
```
Thank you in advance !

**Comment by ivankravets** [comment]
@mgawron86 please file an issue here https://github.com/platformio/platform-atmelavr/issues

**Comment by mgawron86** [comment]
@ivankravets Issue opened: https://github.com/platformio/platform-atmelavr/issues/133
Thanks !
