### ISSUE TITLE
Home: Could not log in PIO Account

### ISSUE THREAD

**Issue by antoniobreton** [platformio/platformio-core#1514]
Server error

I cannot log in in my PIO account. 

Antonio Breton

**Comment by silps** [comment]
Server is down looks like

**Comment by ivankravets** [comment]
Could you try this solution https://github.com/platformio/platformio-core/issues/1482#issuecomment-375574185 ? Does it work?

**Comment by ivankravets** [comment]
Please reopen if you still need help
