### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mmx-Dimitrov** [platformio/platformio-core#1515]
PIO Core Call Error: The next files/directories have been created in C:\Users\Maksym\Documents\PlatformIO\Projects\BedroomLight
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'toolchain-atmelavr' with version requirements '~1.40902.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
