### ISSUE TITLE
vscode (1.21.1)+platformio  (3.5.3a7) + openocd (0.10) -> no jlink device found

### ISSUE THREAD

**Issue by ozanoner** [platformio/platformio-core#1516]
What kind of issue is this?

- PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: windows 10

**PlatformIO Version** (`platformio --version`): 3.5.3a7

### Description of problem
unable to upload firmware.hex

#### Steps to Reproduce

1. create a new project for nrf52-dk with vscode+platformio
2. try example code: .platformio\platforms\nordicnrf52\examples\mbed-events\src
3. pio run target --upload

### Actual Results
   
[03/23/18 22:51:47] Processing nrf52_dk (platform: https://github.com/platformio/platform-nordicnrf52.git; board: nrf52_dk; framework: mbed)

Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Nordic nRF52 > Nordic nRF52-DK
SYSTEM: NRF52832 64MHz 64KB RAM (512KB Flash)
DEBUG: CURRENT(jlink) ON-BOARD(cmsis-dap, jlink) EXTERNAL(blackmagic, stlink)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(light)
Collected 15 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <mbed-events>
Configuring upload protocol...
AVAILABLE: blackmagic, cmsis-dap, jlink, mbed, nrfjprog, stlink
CURRENT: upload_protocol = jlink
Uploading .pioenvs\nrf52_dk\firmware.hex
GNU MCU Eclipse 32-bits Open On-Chip Debugger 0.10.0+dev-00392-gbe9ef0b0 (2018-01-12-10:20)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
0
adapter speed: 1000 kHz
cortex_m reset_config sysresetreq
Warn : Failed to open device: LIBUSB_ERROR_NOT_SUPPORTED.
Warn : Failed to open device: LIBUSB_ERROR_NOT_FOUND.
Error: No J-Link device found.
Error: No Valid JTAG Interface Configured.
*** [upload] Error -1
================================================================= [ERROR] Took 5.63 seconds =================================================================
The terminal process terminated with exit code: 1

### Expected Results
uploaded firmware

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:nrf52_dk]
platform = https://github.com/platformio/platform-nordicnrf52.git
framework = mbed
board = nrf52_dk
debug_tool = jlink
upload_protocol = jlink
```

**Source file to reproduce issue:**
```cpp
#include "mbed_events.h"
#include <stdio.h>

int main() {
    // creates a queue with the default size
    EventQueue queue;

    // events are simple callbacks
    queue.call(printf, "called immediately\n");
    queue.call_in(2000, printf, "called in 2 seconds\n");
    queue.call_every(1000, printf, "called every 1 seconds\n");

    // events are executed by the dispatch method
    queue.dispatch();
}

```

### Additional info
![image](https://user-images.githubusercontent.com/6412075/37850524-7d3b3ab2-2eec-11e8-91b9-6f3f88df3dc3.png)

**Comment by ivankravets** [comment]
Do you see J-LInk in system device manager?

**Comment by ozanoner** [comment]
yes
![image](https://user-images.githubusercontent.com/6412075/37851356-9abcd192-2eef-11e8-911f-41bdc4e41a90.png)

**Comment by ozanoner** [comment]
I installed drivers here: C:\Program Files (x86)\SEGGER\JLink_V630h\USBDriver

**Comment by ivankravets** [comment]
https://sourceforge.net/p/openocd/mailman/message/32252376/

**Comment by ivankravets** [comment]
http://zadig.akeo.ie/

**Comment by ozanoner** [comment]
yeah. actually I tried it, and worked but with a side-effect (and a terrible one). it causes a disabled com port somehow, which means there is no terminal access to the nrf52-dk. rollback took my 3 hours, therefore, I won't try it once more :)
there is a serious warning here: 
![image](https://user-images.githubusercontent.com/6412075/37851654-bd12ea5a-2ef0-11e8-81d8-719dd2169bb1.png)
https://gnu-mcu-eclipse.github.io/openocd/install/

which I didn't take serious first (causing 3 wasted hours)

**Comment by ivankravets** [comment]
Indeed, you can use J-LInk GDB server directly, without openOCD. Could you try it?

* http://docs.platformio.org/en/latest/plus/debugging.html#j-link-and-st-nucleo

**Comment by ozanoner** [comment]
ok let me try. do I need "extra_script.py"? if so, does it need any edit?

**Comment by ivankravets** [comment]
No no, just use `debug_server`. You even can keep `debu_tool = stlink`.

**Comment by ozanoner** [comment]
seems that I'm doing something wrong. can you please check the following ini?

![image](https://user-images.githubusercontent.com/6412075/37852312-2fec2116-2ef3-11e8-8bba-2232ad4e421f.png)

**Comment by ivankravets** [comment]
1. `debug_tools = jlink`
2. Please remove quotes from debug server arguments

**Comment by ozanoner** [comment]
I cannot get rid of openocd :(

latest ini:

[env:nrf52_dk]
platform = https://github.com/platformio/platform-nordicnrf52.git
framework = mbed
board = nrf52_dk
; debug_tool = jlink
upload_protocol = jlink

debug_tool = jlink
debug_server =
  C:/Program Files (x86)/SEGGER/JLink_V630h/JLinkGDBServerCL.exe
  -singlerun
  -if
  SWD
  -select
  USB
  -port
  2331
  -device
  nRF52832_xxAA

and terminal output:

Uploading .pioenvs\nrf52_dk\firmware.hex
GNU MCU Eclipse 32-bits Open On-Chip Debugger 0.10.0+dev-00392-gbe9ef0b0 (2018-01-12-10:20)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
0
adapter speed: 1000 kHz
cortex_m reset_config sysresetreq
Warn : Failed to open device: LIBUSB_ERROR_NOT_SUPPORTED.
Warn : Failed to open device: LIBUSB_ERROR_NOT_FOUND.
Error: No J-Link device found.
Error: No Valid JTAG Interface Configured.
*** [upload] Error -1


actually segger debugger works from command line:
![image](https://user-images.githubusercontent.com/6412075/37853004-dd2aeb58-2ef5-11e8-80b0-30b281f5e734.png)


if I am not wrong, "debug_server" option doesn't change the upload utility (which is openocd now)

**Comment by ivankravets** [comment]
This works for me:
```ini
[env:nrf52_dk]
platform = nordicnrf52
framework = mbed
board = nrf52_dk
debug_server =
    C:/Program Files (x86)/SEGGER/JLink_V630h/JLinkGDBServerCL.exe
    -singlerun
    -if
    SWD
    -select
    USB
    -port
    2331
    -device
    nRF52832_xxAA
```

**Comment by ozanoner** [comment]
can you post terminal output too?

**Comment by ivankravets** [comment]
![screen shot 2018-03-23 at 23 14 58](https://user-images.githubusercontent.com/1760209/37853590-07de7d70-2ef0-11e8-9050-4648dbaa2f7d.png)

**Comment by ozanoner** [comment]
seems that it doesn't work for you either. can you show me 'TERMINAL' tab pls?

![image](https://user-images.githubusercontent.com/6412075/37853741-162cf150-2ef9-11e8-85bc-ca1e40b12940.png)

**Comment by ozanoner** [comment]
I really appreciate if you can upload the firmware under windows-10 with a proper ini file. 
I've tested something new. jlink.exe works, but I couldn't configure platformio to use jlink.exe. 
![image](https://user-images.githubusercontent.com/6412075/37854155-c0198cae-2efa-11e8-8d31-292e04e687f2.png)

do you know how to configure platformio to use jlink as 'uploader'. I tried this ini:
```
[env:nrf52_dk]
platform = https://github.com/platformio/platform-nordicnrf52.git
framework = mbed
board = nrf52_dk

upload_protocol = custom
extra_scripts = extra_script.py

debug_tool = jlink

debug_server =
  C:/Program Files (x86)/SEGGER/JLink_V630h/JLinkGDBServerCL.exe
```
and this script:
```
Import("env")

env.Replace(
    UPLOADHEXCMD=
    'JLink.Exe -device nRF52832_xxAA -speed 4000 -if swd -autoconnect 1 -CommanderScript $BUILD_DIR/1.jlink'
)
```
but no luck :( still it uses openocd and fails:
Uploading .pioenvs\nrf52_dk\firmware.hex
GNU MCU Eclipse 32-bits Open On-Chip Debugger 0.10.0+dev-00392-gbe9ef0b0 (2018-01-12-10:20)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
0
adapter speed: 1000 kHz
cortex_m reset_config sysresetreq
Warn : Failed to open device: LIBUSB_ERROR_NOT_SUPPORTED.
Warn : Failed to open device: LIBUSB_ERROR_NOT_FOUND.
Error: No J-Link device found.
Error: No Valid JTAG Interface Configured.
*** [upload] Error -1


is there any way to select & configure uploader tool?
I see this in the platform.json: 
https://github.com/platformio/platform-nordicnrf52/blob/c45f941e1b076272ceecbdd2d6fd4b575ac5517c/platform.json#L48

and this:
https://github.com/platformio/platform-nordicnrf52/blob/c45f941e1b076272ceecbdd2d6fd4b575ac5517c/platform.json#L53

how can I config to use 'tool-nrfjprog' as uploader? I think this may solve my problem.

**Comment by ozanoner** [comment]
just to clarify: my problem is not with debugger, but uploader. openocd as uploader fails in my trials and I am trying to replace openocd with segger tools to be able to upload in platformio (with ctrl+alt+U)

**Comment by ivankravets** [comment]
Oh... Upload!!! I thought you mean debugging! Does debug work for you?
Of course uploading will not work. You need to declare custom uploader. For example,

```
[env:]
..
upload_protocol = custom
extra_scripts = extra.py
```

`extra.py`
```py
from os import makedirs
from os.path import isdir, join
Import(env)

def _jlink_cmd_script(env, source):
    build_dir = env.subst("$BUILD_DIR")
    if not isdir(build_dir):
        makedirs(build_dir)
    script_path = join(build_dir, "upload.jlink")
    commands = ["h", "loadbin %s,0x0" % source, "r", "q"]
    with open(script_path, "w") as fp:
        fp.write("\n".join(commands))
    return script_path

env.Replace(
    __jlink_cmd_script=_jlink_cmd_script,
    UPLOADER="C:/Program Files (x86)/SEGGER/JLink_V630h/JLinkGDBServerCL.exe",
    UPLOADERFLAGS=[
        "-device", "nRF52832_xxAA",
        "-speed", "4000",
        "-if", "swd",
        "-autoconnect", "1"
    ],
    UPLOADCMD='"$UPLOADER" $UPLOADERFLAGS -CommanderScript ${__jlink_cmd_script(__env__, SOURCE)}'
)
```

**Comment by ivankravets** [comment]
P.S: I didn't test it :) Just wrote.

**Comment by ozanoner** [comment]
thumbs up!! many thanks @ivankravets . your solution works with small modifications. I am attaching working platform.ini and extra_script.py for others.

[tmp.zip](https://github.com/platformio/platformio-core/files/1843677/tmp.zip)

**Comment by ivankravets** [comment]
Stop! Maybe, we should use official JLink GDB default without these extra scripts and hooks? PIO should work smoothly.

**Comment by ozanoner** [comment]
ok, right. I've used jlink.exe as uploader, not jlink gdb. moreover, I didn't test jlink-gdb as debugger. how can I help you?

**Comment by profra** [comment]
Hi all, please do it according to Ivan ... "Stop! Maybe, we should use official JLink GDB default without these extra scripts and hooks? PIO should work smoothly." ... I have been solving a similar problem right now... the clear solution would be beneficial to all!

**Comment by ozanoner** [comment]
sure, he is the boss :)

**Comment by profra** [comment]
MVP for PIO! 🥇 👍

**Comment by ivankravets** [comment]
Please remove all extra scripts and extra lines from `platformio.ini` and re-test with upstream version. Don't forget to add JLink installation to your system PATH. `JLinkExe` command should from your `cmd` terminal without the full path.

* http://docs.platformio.org/en/latest/platforms/nordicnrf52.html#stable-and-upstream-versions

**Comment by ivankravets** [comment]
If you already use upstream version, please PIO Home > Platforms > Updates.

All should work out the box now.

**Comment by profra** [comment]
I am in weekend-house now... My equipment here is only NB with Win10 Pro and Nucleo-64 STM32F103 with ST/link on board... and VS Code with PIO... I would like to rid off OpenOCD (now is working OK) on this board, I would prefer to have direct GDB as uploader and debugger. Do you see any possibilities how to reach it? ... and how?

**Comment by ivankravets** [comment]
>  I would prefer to have direct GDB as uploader and debugger.

```
pio run -t upload
pio debug --interface gdb -x .pioinit
```

**Comment by ivankravets** [comment]
Please reopen if you still need a help

**Comment by ozanoner** [comment]
@ivankravets  sorry man, my bad about jlink.
the right tool should be nrfjprog, not jlink.
The following command worked correctly.
nrfjprog --program firmware.hex --chiperase --reset

Of course, you can update the repo for that tool, but if you wait, I will fully test it within script and confirm if it works as so.  
![image](https://user-images.githubusercontent.com/6412075/37864489-c53e2a92-2f80-11e8-8075-07633ac80aff.png)

**Comment by ivankravets** [comment]
`upload_protocol = nrfjprog`

**Comment by profra** [comment]
I would prefer to have direct GDB as uploader and debugger.

pio run -t upload
pio debug --interface gdb -x .pioinit
---------------------------------------------------
OK, but I don't know how to connect (gdb) console... any help?

**Comment by ivankravets** [comment]
You have! We use GDB for debugging.
