### ISSUE TITLE
embedding binary files into esp32 Firmware 

### ISSUE THREAD

**Issue by MarkusBec** [platformio/platformio-core#1517]
Hello

I am trying to compile the esp32 ssl example with Platformio for:
platform = espressif32
board = esp32dev
framework = espidf

https://community.platformio.org/clicks/track?url=https%3A%2F%2Fgithub.com%2Fespressif%2Fesp-idf%2Ftree%2Fmaster%2Fexamples%2Fprotocols%2Fhttps_request&post_id=10639&topic_id=3791

The problem seems to be that platformIO is not recognising the needed component.mk with its option:
COMPONENT_EMBED_TXTFILES := server_root_cert.pem
Documented here: https://esp-idf.readthedocs.io/en/latest/api-guides/build-system.html#embedding-binary-data

there is no obvious way to me to configure or bypass these configuration to the underlaying sdk.

Can anybody help me with this problem?

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif32/issues
