### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by abduIkadir** [platformio/platformio-core#1522]
PIO Core Call Error: Library Storage: C:\Users\Developer\.platformio\lib
Updating GT511C3                         @ 90c64cb9db     [37c1d616a8]

Uninstalling GT511C3 @ 90c64cb9db: 	[OK]
Looking for GT511C3 library in registry

Error: Library `{'requirements': u'37c1d616a8', 'name': 'GT511C3'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': u'37c1d616a8', 'name': 'GT511C3'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
I don't see this library in our registry https://platformio.org/lib/search?query=GT511C3&page=1
