### ISSUE TITLE
Home: Libraries: Installed -> PIO Core Call Error: Error: Could not load broken JSON

### ISSUE THREAD

**Issue by starscream4002** [platformio/platformio-core#1531]
PIO Core Call Error: Error: Could not load broken JSON: C:\Users\{username}\AppData\Roaming\SPB_Data\.platformio\lib\HTU21D\library.json

**Comment by ivankravets** [comment]
Please remove this file C:\Users{username}\AppData\Roaming\SPB_Data.platformio\lib\HTU21D\library.json
