### ISSUE TITLE
Does lib_extra_dirs  support relative path?

### ISSUE THREAD

**Issue by palivoda** [platformio/platformio-core#1532]
I have project structure where 

src/main.c
lib/foo/src/a.h
lib/foo/lib/woo/src/b.h

main.c includes a.h
a.h includes b.h

plaformio.ini:

[platformio]
lib_extra_dirs = lib/woo/lib

And I get error b.h is not found. 

Does lib_extra_dirs should work in such case?
How I can include b.h?

**Comment by ivankravets** [comment]
`lib` folder MUST contain ONE library per folder. You can use nested folders here

**Comment by palivoda** [comment]
> You can use nested folders here

Hi Ivan,  can you clarify a bit?

From response I assume I even dont need lib_extra_dirs  option and I can just put

/lib/FooLib
and inside FooLib there could be also lib folder
/lib/FooLib/lib/ZooLib/src/aaa.h

this aaa.h will be included?

**Comment by ivankravets** [comment]
You should have 1 level libraries structure. 

- lib/ZooLib/src/aaa.h
- lib/BooLib/src/bbb.h

**Comment by palivoda** [comment]
Then it's impossible to include other project as git submodule.

**Comment by ivankravets** [comment]
You can use http://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-extra-dirs as you described above. To eliminate whole library(with sublibraries) building, just ignore it via http://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-ignore

**Comment by nelfata** [comment]
On a similar issue, if I have a precompiled library and I am using the following:

-L../../Libraries -llibSomeLib.a

the relative path does not work, I have to specify the absolute path in the -L directive.

Is this a bug, or is there another method to link with a precompiled library?

**Comment by ivankravets** [comment]
@nelfata I've just tried and can't reproduce this issue. Please provide a test example and open a new issue.
