### ISSUE TITLE
Home: Could not list directory/private/var/folders/g1/xjqcdvhx2_b16q704r03tt6h0000gn/T/AppTranslocation/751BAE81-C51D-4C9C-87D8-6D530EDCF474

### ISSUE THREAD

**Issue by HermannLihl** [platformio/platformio-core#1534]
Could not list directory by `/private/var/folders/g1/xjqcdvhx2_b16q704r03tt6h0000gn/T/AppTranslocation/751BAE81-C51D-4C9C-87D8-6D530EDCF474`

**Comment by ivankravets** [comment]
Do you have access to this folder? Please restart PIO Home and IDE.
