### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by hulkco** [platformio/platformio-core#1538]
PIO Core Call Error: Platform /home/greynaga/.platformio/platforms/espressif8266_stage
--------
Updating espressif8266                   @ 07636e5        [Up-to-date]
Updating tool-mkspiffs                   @ 1.200.0        [Up-to-date]
Updating tool-esptool                    @ 1.413.0        [Up-to-date]
Updating tool-espotapy                   @ 1.1.0          [Up-to-date]
Updating framework-arduinoespressif8266  @ 303a71d        [241531a]
git version 2.7.4

fatal: Not a git repository: /home/greynaga/.platformio/packages/_tmp_installing-6U6GhZ-package/.git/modules/lwip2
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1223
