### ISSUE TITLE
[Question] How can I flash firmware.bin manually by using `esptool.py` after build by `platformio run --target build`?

### ISSUE THREAD

**Issue by dphans** [platformio/platformio-core#1542]
### Configuration

**Operating system**: MacOS 10.13.3

**PlatformIO Version**: 3.5.2

### Description of problem
After build project by running `platformio run --target build`. I found the `firmware.bin` file created at `.../PlatformIO/Projects/<my-project>/.pioenvs/<board-name>/firmware.bin`.
How can I upload `firmware.bin` manually by running `esptool.py` command from external Terminal program?
Because I'm going to write a tool can flash `firmware.bin` for many users simply.
I know that not only just upload `firmware.bin` file, it must includes `partitions.bin` and `bootloader.bin`. But I don't know correct `addresses` and `offsets` for each binary files to write firmware by `esptool.py ... write_flash <address> <path> ...`

After searching inside library, I found there required files. So I can execute command below to flash, is it correct? I have flash done with script below:

```python
flash_files = {
  './boot_app0.bin': '0xe000',
   './bootloader_dio_40m.bin': '0x1000',
  './firmware.bin': '0x10000',
  './partitions.bin': '0x8000'
}
esptool_flash_command = "%s --chip esp32 --port %s --baud %d --before default_reset --after hard_reset write_flash -z --flash_size detect" % (esptool_env_path, flash_config['port'], flash_config['baud'])
if not file_is_exist(flash_file):
  raise Exception("Missing required binary file (%s)!" % flash_file)
esptool_flash_command += " %s %s" % (flash_addr, flash_file)
subprocess_exec(esptool_flash_command)
```

This is not issues, just my problem. I'm sorry if this post is wrong.

**Comment by ivankravets** [comment]
Please move to https://community.platformio.org/

**Comment by probonopd** [comment]
Running into the same issue.

Is it possible to combine all parts into  __one__ firmware image that contains __everything__ and can be easily be flashed to the ESP32 using `esptool.py` starting at offset `0x00`? Not a bunch of files in different directories.

**Comment by ivankravets** [comment]
See [upload_command](https://docs.platformio.org/en/latest/projectconf/section_env_upload.html#upload-command)

**Comment by 45gfg9** [comment]
Same problem here. I want to create a .bin file, that doesn't just contain the app code section, but also the filesystem image, nvs, bootloader etc that just make up the whole 4MB (or larger) flash chip size, that I can just flash it into the address 0x0 of the ESP32. Is that possible or am I having some misconception here?

**Comment by gsicilia82** [comment]
This would be a great feature. I encounter same issue. I want to provide firmware which can be flashed as simple as possible.

**Comment by ivankravets** [comment]
You can use recently added [pio pkg exec](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_exec.html) command

```
pio pkg exec --package "platformio/tool-esptoolpy" -- esptool.py --help
```
