### ISSUE TITLE
Atmega32u4 - Adafruit ItsyBitsy 32u4 - 5V 16MHz PRODUCT ID: 3677

### ISSUE THREAD

**Issue by morridm** [platformio/platformio-core#1547]
I do not see the "[Adafruit ItsyBitsy 32u4 - 5V 16MHz PRODUCT ID: 3677](https://www.adafruit.com/product/3677)" listed as a supported board.  Will you please add this as one of the available boards?

Thanks,

David

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr/issues
