### ISSUE TITLE
Add support for devduino board

### ISSUE THREAD

**Issue by cemclellan** [platformio/platformio-core#1549]
- [ ] Development Platform or Board. 

I would like to request support for the devduino board - http://devduino.cc/

It is based on the Arduino Leonardo, but has a custom library:

http://devduino.cc/wp-content/uploads/devduino-master.zip

Thanks!
Chuck

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr/issues
