### ISSUE TITLE
add custom library into arduino-platformio project

### ISSUE THREAD

**Issue by ios198** [platformio/platformio-core#1553]
I downloaded Lora library for Arduino  to customize some features. I put that library in folder lib/. It has tructure as below in lib/:

I downloaded Lora library for Arduino  to customize some features. I put that library in folder lib/. It has tructure as below in lib/:

![untitled](https://user-images.githubusercontent.com/7995051/38401159-1dcf18ac-398f-11e8-913b-a53ae72cb530.png)

I added #include <board.h>, but it get errors:
#include <board.h>
^
compilation terminated.
*** [.pioenvs\nanoatmega328\src\main.cpp.o] Error 1

Inc c_cpp_properties.json
   "includePath": [
                ....
                "<my project directory>/lib/boards",
                "<my project directory>/lib/mac",
                "<my project directory>/lib/radio",
                "<my project directory>/lib/system",
                 ...
            ],

I am quite new to PlatformIO, How to fix this problem and configure this lib correctly?

**Comment by ivankravets** [comment]
Invalid structure. See https://github.com/platformio/platformio-examples/blob/develop/wiring-blink/lib/readme.txt#L10
