### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by huongvn** [platformio/platformio-core#1555]
PIO Core Call Error: Library Storage: C:\Users\HUONGVN\.platformio\lib
Looking for painl library in registry

Error: Library `{'requirements': None, 'name': 'painl'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'painl'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
`painl` is this correct name of a library?
