### ISSUE TITLE
SRC_FILTER not working for arduino project

### ISSUE THREAD

**Issue by zafrirron** [platformio/platformio-core#1564]
reproduction

1. Create arduino project.
2. Define src_dir = source
3. put some file.ino  in source/subfolder
4. Define (env level) SRC_FILTER = +<subfolder/> (or +<subfolder/*> or +<subfolder/*.*> or +<subfolder/*.ino> or +<subfolder/*.ino.cpp> or +<subfolder/file.ino>

The source files are not collected...
changing file.ino names to file.cpp does include them but not in arduino model (i.e the folder is found by SRC_FILTER processor but not by the Ino files converter)

 looks like can be fixed here:
```
def ConvertInoToCpp(env):
    src_dir = util.glob_escape(env.subst("$PROJECTSRC_DIR"))
    ino_nodes = (
        env.Glob(join(src_dir, "*.ino")) + env.Glob(join(src_dir, "*.pde")))
    if not ino_nodes:
        return
    c = InoToCPPConverter(env)
    out_file = c.convert(ino_nodes)

    atexit.register(_delete_file, out_file)
```
by adding proper processing of ...SRC_FILTER content

**Comment by ivankravets** [comment]
INO is a fake format intended for Arduino IDE. This is not a valid CPP file. PlatformIO converts this file to CPP. As result, you need to operate with CPP files instead of INO... `<subfolder/.ino.cpp>`

Also, I highly recommend converting all files to CPP where you will receive true code completion and code linting services http://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually

**Comment by zafrirron** [comment]
Thanks,
Agree with all your points, having said that two points to consider:
1. All arduino IDE developers should move from that stupid environment to (preferably platformio ),
in order to do this the migration path should be as simple as possible:
  a. import project to platformio (ino files converted (by InoToCPPConverter in piomisc.py).
  b. for large arduino project, move to more reasonable folder structure.
  c. start to migrate to cpp
2. once someone moves out from that S ide, there shouldn't be any way back, step b is not back, this to prevent back and forth between the PIO IDE and arduino IDE....
