### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by WicoP** [platformio/platformio-core#1580]
PIO Core Call Error: The next files/directories have been created in C:\Users\wico.pretorius\Documents\PlatformIO\Projects\IR Remote
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'toolchain-atmelavr' with version requirements '~1.40902.0' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
