### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by autodomain** [platformio/platformio-core#1581]
PIO Core Call Error: The next files/directories have been created in C:\Users\Carmelo\Documents\PlatformIO\Projects\180419-113723-pumbaa-blink
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'framework-pumbaa' with version requirements '>=2.3.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
