### ISSUE TITLE
Home: Could not load mDNS services

### ISSUE THREAD

**Issue by brezuicabogdan** [platformio/platformio-core#1582]
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 142 (char 13461 - 13602)

**Comment by ivankravets** [comment]
What is your OS?

**Comment by brezuicabogdan** [comment]
Windows 10 Pro updated to latest version. The problem went away after reading installing the vs code plugin and restarting the computer

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1311
