### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by SuLLLivaN** [platformio/platformio-core#1585]
PIO Core Call Error: PlatformManager: Installing SuLLLy
git version 2.16.2.windows.1

Cloning into 'C:\Users\deriy_aa\.platformio\platforms\_tmp_installing-bh7kws-package'...
warning: You appear to have cloned an empty repository.
Error: VCS: Could not receive an output from `['git', 'rev-parse', '--short', 'HEAD']` command ({'returncode': 128, 'err': 'fatal: Needed a single revision\n', 'out': ''})

**Comment by ivankravets** [comment]
You have to specify full URL to git repo
