### ISSUE TITLE
Home: Could not list directory/private/var/folders/5f/1h7mmtss1dlgnp4s7kg28j_c0000gn/T/AppTranslocation/4B8A4857-33CB-4D24-A9C0-C63725823267

### ISSUE THREAD

**Issue by maonTEC** [platformio/platformio-core#1586]
Could not list directory by `/private/var/folders/5f/1h7mmtss1dlgnp4s7kg28j_c0000gn/T/AppTranslocation/4B8A4857-33CB-4D24-A9C0-C63725823267`

**Comment by ivankravets** [comment]
Please check permissions and restart VSCode.
