### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by rodinholland** [platformio/platformio-core#1588]
PIO Core Call Error: PlatformManager: Installing linux_arm
linux_arm @ 1.4.6 is already installed
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0

Error: Could not find a version that satisfies the requirement '~1.40802.0' for your system 'linux_x86_64'

Not 100% sure this is an error... would appreciate a hint, though!

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-linux_arm/issues/2
