### ISSUE TITLE
Include external configuration files

### ISSUE THREAD

**Issue by lobradov** [platformio/platformio-core#1590]
# Summary

It would be good if there would be a way to include other .ini files to form grand platformio.ini. 

Something like: 

`platformio.ini`:
```
[platformio]
env_default = my-device
extra_configs = 
       my-other-device.ini
       yet-another-device.ini
       extra_envs/*.ini

[env:my-device]
...
```

`my-other-device.ini`: 
```
[env:my-other-device]
...
```

# Rationale

Looking at Espurna (https://github.com/xoseperez/espurna), you can notice that platformio.ini is quite big and has a lot of different environments. Managing that is a bit hard, given the volume. Ability to include parts of config would allow split into multiple files and better organize it.

Another problem are per-user definitions. Repo defines platformio.ini with quite a few boards, but any local customization needs to be committed (which would further grow variances) or overwritten on any sync with latest development progress. Enabling includes would allow custom environments to be placed in separate directory covered by .gitignore.

**Comment by lobradov** [comment]
As discussed in xoseperez/espurna#810, we changed the request to: 
- implement C-style `#include "custom.ini"` in platformio.ini to be able to include external files 
- add options to include wildcard files in directories, as in `#include "directory/*.ini"` 

Thanks @ivankravets.

**Comment by zafrirron** [comment]
I will Second that.
See also:
https://github.com/xoseperez/espurna/issues/764 for improved folders structure that should be supported.
This feature will enable platformio users to add their own boards specific configs (and code) in folders structure and adding new boards just by dropping board_x folder that includes its specific platformio.ini env part without changing the main platformio.ini

**Comment by xoseperez** [comment]
Also note I submitted a PR some time ago to allow multi-inheritance in the platformio.ini file at environment level...  Not exactly the same idea as exposed here but still another way (compatible with the 2 above by @lobradov) to easy handling long definition files.

https://github.com/platformio/platformio-core/pull/790

**Comment by Misiu** [comment]
@lobradov ini file is just an ini, I think syntax from first post is better (it is similar to lib_debs - https://github.com/xoseperez/espurna/blob/dev/code/platformio.ini#L55)

regardless the format this would be an awesome feature to have and project like [ESPurna](https://github.com/xoseperez/espurna) would benefit from it.

wildcard support would be even more awesome, this way we could have single folder called boards, and only thing to do would be to drop `board_X.ini` into that folder.

Really looking forward to seeing this 👍

**Comment by proddy** [comment]
me too.

**Comment by ivankravets** [comment]
Documentation http://docs.platformio.org/en/latest/projectconf/section_platformio.html#extra-configs

Please re-test with the latest `pio upgrade --dev`.

Thanks!
