### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by watchdogservice** [platformio/platformio-core#1591]
PIO Core Call Error: The next files/directories have been created in C:\Users\Watchdog\Documents\PlatformIO\Projects\ESP8266
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing espressif8266
Downloading...
Unpacking...
espressif8266 @ 1.7.0 has been successfully installed!
PackageManager: Installing toolchain-xtensa @ ~1.40802.0

Downloading...
Warning! Package Mirror: ("Connection broken: error(10054, 'Se ha forzado la interrupci\\xf3n de una conexi\\xf3n existente por el host remoto')", error(10054, 'Se ha forzado la interrupci\xf3n de una conexi\xf3n existente por el host remoto'))
Looking for another mirror...

Error: Please read http://bit.ly/package-manager-ioerror
Error: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
