### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by t0k4rt** [platformio/platformio-core#1593]
PIO Core Call Error: The next files/directories have been created in /Users/alexandre/Documents/PlatformIO/Projects/180425-193832-esp8266-rtos-sdk-blink
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Could not install 'framework-esp8266-rtos-sdk' with version requirements '>=1.5.0-beta' for your system 'darwin_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

----------------
Any idea ?
Thanks !

**Comment by ivankravets** [comment]
I've just re-tested and it works well. Could you try again or check Internet?
