### ISSUE TITLE
PlatfomIO IDE extension installed via VS Code

### ISSUE THREAD

**Issue by CBDeepak** [platformio/platformio-core#1595]
Hello

I will not say this as an issue... But when I install platformIO for VS Code, there a way I can have it installed in my python directort say "c:\python" instead of "c:\users\[user]" location?

Thanks
Deepak

**Comment by ivankravets** [comment]
You can install Python manually before and PlatformIO will use it. See http://docs.platformio.org/en/latest/faq.html#install-python-interpreter
