### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by jaekar99** [platformio/platformio-core#1603]
PIO Core Call Error: Library Storage: /home/jasoniv/.platformio/lib

Error: Detected unknown package '/home/jasoniv/.platformio/lib/ssd1306_ID1904 @ *'

Not sure what I have configured ...  A bit of a novice at Atom and Platformio..

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1346
