### ISSUE TITLE
I cannot upload code to my arduino mega due to platformio using an outdated version of libtinfo.so

### ISSUE THREAD

**Issue by Darwin-II** [platformio/platformio-core#1618]
I am using Arch Linux Arm (armv7) on my raspberry pi 3 model b+. I need to use platformio and the raspberry pi for a project of mine, on Arch Linux.

My problem is as follows:

When uploading to the arduino, the source code is correctly compiled as a hex file. It however cannot upload, with the included version of avrdude stating that it cannot load shared libraries as libtinfo.so.5 is missing. The exact report it gives is:

/root/.platformio/packages/tool-avrdude/avrdude:` error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
*** [upload] Error 127

Is there a solution that does not include changing operating system or using avrdude on it's own to upload the hex file, which it cannot do due to a lack of a uploadable bootloader? Also, would it be possible to fix by creating a symlink between the separate version of avrdude and platformio?

**Comment by ivankravets** [comment]
Please move your issue to https://github.com/platformio/platform-atmelavr/issues
