### ISSUE TITLE
update / upgrade progress

### ISSUE THREAD

**Issue by mrred128** [platformio/platformio-core#1619]
- [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.
------------------------------------------------------------------

### Configuration

VSCode IDE

**Operating system**:

Win64

**PlatformIO Version** (`platformio --version`):

3.5.3b2

### Description of problem

When the IDE starts up on a valid project it first checks PIO upgrades then PIO updates silently with just a spinning wheel on the status line. The problem is it doesn’t show any activity similar to what happens when something get’s loaded during a run session ie: shows what is being updated / upgraded at that time.

I would like to see the results as they occur.
#### Steps to Reproduce

1. Open up a valid platformio project.

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platformio-node-helpers/issues/2
