### ISSUE TITLE
Home: Could not initialize project [pico32]

### ISSUE THREAD

**Issue by hebl** [platformio/platformio-core#1626]
PIO Core Call Error: The next files/directories have been created in /Users/xxx/Documents/PlatformIO/Projects/esp32
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: [Tue May 15 07:53:52 2018] Processing pico32 (platform: espressif32; board: pico32; framework: arduino)
--------------------------------------------------------------------------------
PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0
Downloading...
Unpacking...
Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'pico32'
========================== [ERROR] Took 45.13 seconds ==========================

**Comment by ivankravets** [comment]
This board has been added recently. You need to switch project to upstream/dev version http://docs.platformio.org/en/latest/platforms/espressif32.html#stable-and-upstream-versions
