### ISSUE TITLE
Fallo al instalar platformio en linuxMint de 32bits

### ISSUE THREAD

**Issue by donguty** [platformio/platformio-core#1630]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-KOaUgr/semantic-version/

[FAILURE]
The installation process has been FAILED!

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
