### ISSUE TITLE
Add Board : beaglebone black and Freescale Kinetis FRDM-KL26Z

### ISSUE THREAD

**Issue by Dileepkv** [platformio/platformio-core#1635]

**Comment by ivankravets** [comment]
* BeagleBone Black - https://github.com/platformio/platform-linux_arm/issues/10
* Freescale Kinetis FRDM-KL26Z - see https://github.com/platformio/platform-freescalekinetis/commit/be2087c1619a4dc4ead4ab60b6edd7fe453de904

If you would like to use Kinetis FRDM-KL26Z with PlatformIO, try previous releases https://github.com/platformio/platform-freescalekinetis/releases

```
[env:...]
platform = freescalekinetis@3.0.0
```

I don't remember in which version mbed  has dropped a support for this board.
