### ISSUE TITLE
Add mechanism to inform user about platform packages update

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio-core#165]
In order to allow the user of platformio to have more control over the update process, information about the available update shall be provided. These include, but are not limited to:
- versions currently installed and available through the update
- release notes and/or changelog for all versions between the currently installed version and the update version

**Comment by ivankravets** [comment]
Implemented in PIO Core 3.0 via [pio platform update --only-check](http://docs.platformio.org/en/latest/userguide/platforms/cmd_update.html#cmdoption-platformio-platform-update-c) option.
