### ISSUE TITLE
PPP components missing from lwip in esp-idf

### ISSUE THREAD

**Issue by dmitrygaa** [platformio/platformio-core#1655]
My project, using PPP portion of lwip stack, failed to build with PlatformIO, but it can be successfully built via ESP32 toolchain and esp-idf SDK 3.0.
Build fails with error:
```
.pioenvs\esp32dev\liblwip.a(init.o):(.literal.lwip_init+0x0): undefined reference to `ppp_init'
.pioenvs\esp32dev\liblwip.a(init.o): In function `lwip_init':
init.c:(.text.lwip_init+0x15): undefined reference to `ppp_init'
```
Some examination shows that folder componets/lwip/netif/ppp is not included in the build.

Environment:
VS Code
PlatformIO 3.6.0a1
ESP32 platform 1.0.2

**Comment by ivankravets** [comment]
Please move to https://github.com/platformio/platform-espressif32/issues
