### ISSUE TITLE
Invalid paths to cJSON library component of esp-idf

### ISSUE THREAD

**Issue by dmitrygaa** [platformio/platformio-core#1656]
While building rather simple project, using cJSON, I've got error message:
```
components/utils/JSON.h:4:19: fatal error: cJSON.h: No such file or directory
```
This projects successfully builds with ESP32 toolchain and esp-idf SDK 3.0.
When I look in .pioenvs/esp32dev/longcmd-* files I see these folders in include search dirs:
```
.platformio/packages/framework-espidf/components/json/include
.platformio/packages/framework-espidf/components/json/port/include
```
But there are no /include or /port/include dirs inside json component. The only dir is cJSON. You can check directory structure [here](https://github.com/espressif/esp-idf/tree/release/v3.0/components/json).
To temporarily solve this issue, I've had to change include to:
```
#include "../../json/cJSON/cJSON.h"
```
Environment:
VSCode
PlatformIO 3.6.0a1
esp-idf platform 1.0.2

**Comment by ivankravets** [comment]
Please move to https://github.com/platformio/platform-espressif32/issues
