### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by thebreadboard** [platformio/platformio-core#1657]
Not an Arduino project: Z:\GITHUB\Arduino-Tutorials\Arduino Tutorial Lesson 5

**Comment by ivankravets** [comment]
Do you have `Not an Arduino project: Z:\GITHUB\Arduino-Tutorials\Arduino Tutorial Lesson 5\Arduino Tutorial Lesson 5.ino` file?

**Comment by ivankravets** [comment]
Please reopen if you still need help
