### ISSUE TITLE
Add mechanism to inform user about library update 

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio-core#166]
Before updating a library, it may be useful for the user to review the changes (e.g. git log) between the currently installed library version and the version available through the update. Platformio should provide a mechanism to
- inform which libraries have new updates
- display a list of changes for individual updates

**Comment by ivankravets** [comment]
Implemented in PIO Core 3.0 via [pio lib update --only-check](http://docs.platformio.org/en/latest/userguide/cmd_update.html#cmdoption-platformio-update-c) option.
