### ISSUE TITLE
How to make changes in pre-installed library/c file of arduino platform ?

### ISSUE THREAD

**Issue by yatharthaggarwal** [platformio/platformio-core#1673]
I don't know if this has been asked earlier. But I'm programming for Arduino platform using Platform - IO on atom and want to make some changes in 'analogReference()' function, which happens to be predefined in 'wiring_analog.c' file.
The changes cannot be made otherwise.
Thanks

**Comment by ivankravets** [comment]
Do you mean http://docs.platformio.org/en/latest/projectconf/section_platformio.html#home-dir and packages/framework-arduinoavr?

**Comment by ivankravets** [comment]
https://community.platformio.org/
