### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by StephanJoubert** [platformio/platformio-core#1675]
PIO Core Call Error: The next files/directories have been created in D:\Work\Research\Raspberry PI\PIO_Raspberry
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: PlatformIO temporary does not support cross-compilation for WiringPi framework. Please use PIO Core directly on Raspberry Pi

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/plus/pio-remote.html
