### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by tarzan115** [platformio/platformio-core#1682]
`Server error`

I can not import Arduino project in vscode. please help!

**Comment by ivankravets** [comment]
Could you reproduce it again?

**Comment by tarzan115** [comment]
I got that error all the time I try to import. it also errors when I create a new project
![image](https://user-images.githubusercontent.com/13164182/41494841-66341b50-7144-11e8-8124-481651b77777.png)

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio home -p 8055` and try to repeat your workflow. Do you see any errors in a console?

**Comment by tarzan115** [comment]
No, I don't!
after the command, it auto open `127.0.0.1:8055`
![image](https://user-images.githubusercontent.com/13164182/41518911-2760ca34-72ef-11e8-8ea3-fbf84fd10622.png)

**Comment by ivankravets** [comment]
Did you try to import Arduino project?

**Comment by tarzan115** [comment]
yes, I tried to import but I got that error. after that, I try to create a new project but it got the same error.

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio update`. Now, it should show more explained exception report.

**Comment by tarzan115** [comment]
here what I got
`[Error 2] The system cannot find the file specified: u'C:\\Users\\tarzan115\\Documents'`

**Comment by ivankravets** [comment]
Which folder do you select when trying to import? `C:\\Users\\tarzan115\\Documents`?

**Comment by ivankravets** [comment]
Please share a screenshot from PIO Home > Import Arduino Project wizard before pressing “Import” button.

**Comment by tarzan115** [comment]
I tried to create `Documents` folder in user folder because I don't have that folder before.
and then `PIO` still show error cannot find folder `PlatformIO`, and I create folder `PlatformIO` and error continue show cannot find folder `Projects` and so on...
here is the errors
![image](https://user-images.githubusercontent.com/13164182/42751555-57e9a05e-8915-11e8-848a-ee80b7afadbd.png)

**Comment by ivankravets** [comment]
You can import THE ONLY Arduino projects, where folder contains the INO file with the same name as folder name. In other cases, please use Open Project or Create New porject.

**Comment by tarzan115** [comment]
I did. I had import INO file with the same name as the folder. but PIO shows that error.

**Comment by ivankravets** [comment]
Please read my previous post carefully. I asked you to show me a real Arduino project which you are going to import. Of course, and error after "Import" action.

**Comment by tarzan115** [comment]
I figure out that when I move my folder "Documents" in another place and my windows user folder will not have "Documents" anymore. so now I left the "Documents" to default, that mean windows user folder will have "Documents" folder and this error gone.
error:
```
|--C:
|   |--Users
|   |   |--tarzan115 (user folder and not include "Documents")
|   |   |   |--.platformio
```

work:
```
|--C:
|   |--Users
|   |   |--tarzan115
|   |   |   |--.platformio
            |--Documents   <-- this makes everything work.
```

hopefully, this information will help somehow
