### ISSUE TITLE
Add Support for the TinyCircuits TinyScreen+ Board

### ISSUE THREAD

**Issue by solinvictus21** [platformio/platformio-core#1684]
What kind of issue is this?

- [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------

### Configuration

**Operating system**: All

**PlatformIO Version** (`platformio --version`): 3.6.0a2

### Description of problem

I would like to request that a new board type be added to support the [TinyScreen+](https://tinycircuits.com/collections/processors/products/tinyscreenplus) board for development. The is an [Arduino IDE board configuration](http://files.tinycircuits.com/ArduinoBoards/tinycircuits-samd-1.0.7.zip) available. I'm guessing it's just a matter of refactoring that into the PlatformIO board configuration style.

### Additional info

While the board is similar to a MKRZero Arduino board, several functions do not work on TinyScreen+ when building with that board type because the pinouts are different. I've already discovered that SDA/SDL are connected to PA08/PA09 on the MKRZero and PA22/PA23 on the TinyScreen+, so i2c does not work correctly when compiling with the "mkrzero" board type.

**Comment by ivankravets** [comment]
> Atmel ATSAMD21G18A 32 bit ARM processor at 48MHz, Arduino Zero compatible

Arduino ZERO, not MKZero

https://tinycircuits.com/collections/processors/products/tinyscreenplus

Please try `zero` or `zeroUSB` it this board has bootloader.

If it does not work, please move this issue to https://github.com/platformio/platform-atmelsam/issues
