### ISSUE TITLE
macOS will soon drop 32-bit support

### ISSUE THREAD

**Issue by tiferrei** [platformio/platformio-core#1689]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: macOS 10.14 Beta (18A293u)

**PlatformIO Version** (`platformio --version`): 3.5.3

### Description of problem
macOS Mojave drops support for 32 bit binaries, the atmelavr toolchain seems to be almost all 32 bit, which means that every time I compile something I get:
<img width="637" alt="screenshot 2018-06-18 at 16 45 09" src="https://user-images.githubusercontent.com/8849915/41547028-0a1ea4fa-7317-11e8-9c86-69928abb6509.png">

Here's a list of all the platformio binaries the system has complained about so far:
<img width="841" alt="screenshot 2018-06-18 at 16 45 37" src="https://user-images.githubusercontent.com/8849915/41547055-140352f4-7317-11e8-9c51-e13fa6aa64a5.png">

More info here: https://support.apple.com/en-gb/HT208436

#### Steps to Reproduce

1. Install Mojave
2. `platformio run`

### Additional info
Everything still works for now, this is more of a deprecation warning.
Is there any way I can fix this?

Thanks,
Tiago

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr/issues
