### ISSUE TITLE
Home: Libraries: Could not uninstall library

### ISSUE THREAD

**Issue by twobaker** [platformio/platformio-core#1700]
PIO Core Call Error: Library Storage: C:\xyz\Documents\PlatformIO\Projects\ESP32 OTA\.piolibdeps

Error: Detected unknown package 'C:\xyz\Documents\PlatformIO\Projects\ESP32 OTA\.piolibdeps\EasyOTA_ID1975 @ *'

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1700
