### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by szmolnar** [platformio/platformio-core#1701]
PIO Core Call Error: Library Storage: /Users/szmolnar/Documents/Projects/MenuSystem/MenuSystem_v3/.piolibdeps
Updating Arduino                         @ 1a9403d        [641c5cd]
git version 2.8.3
Updating 1a9403d..641c5cd

From https://github.com/esp8266/Arduino
   ebda795..641c5cd  master     -> origin/master
Fetching submodule tools/sdk/lwip2/builder
From https://github.com/d-a-v/esp82xx-nonos-linklayer
   0c0d8c2..c4150ca  master     -> origin/master
Fetching submodule tools/sdk/lwip2/builder/lwip2-src
From https://git.savannah.nongnu.org/git/lwip
   f8e7ccc..58f928a  master     -> origin/master
Fetching submodule tools/sdk/ssl/bearssl
error: Your local changes to the following files would be overwritten by merge:
	cores/esp8266/base64.cpp
	cores/esp8266/base64.h
	cores/esp8266/libb64/cencode.c
	cores/esp8266/libb64/cencode.h
	libraries/ESP8266WiFi/examples/BearSSL_CertStore/certs-from-mozilla.py
	tests/common.sh
	tools/boards.txt.py
Please, commit your changes or stash them before you can merge.
Aborting
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment]
> error: Your local changes to the following files would be overwritten by merge:

Please manually merge or remove `~/.platformio/packages/framework-arduinoesp8266...`
