### ISSUE TITLE
Not possible to remove -fno-rtti from build flags

### ISSUE THREAD

**Issue by Henry0191** [platformio/platformio-core#1712]
**Operating system**: 
Windows 10, using Atom with PlatformIO Package.

**PlatformIO Version** (`platformio --version`): 
3.5.3

### Description of problem
I tried every information found in the platformio docs to remove the build flag '-fno-rtti' from the build process, because I want to use the typeid() operator of C++.
However, it seems to compile with the flag every time, regardless of what I do. 

Compiler output:
```
error: cannot use typeid with -fno-rtti
Serial.printf(typeid(test).name());
```

**The content of `platformio.ini`:**
```ini
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM11
upload_speed = 921600
build_unflags = -fno-rtti
```

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.
