### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by sve95** [platformio/platformio-core#1714]
PIO Core Call Error: Library Storage: D:\user\work\platformio\ttgo\.piolibdeps

Error: Detected unknown package 'D:\user\work\platformio\ttgo\.piolibdeps\Adafruit ST7735 Library_ID12 @ *'

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1346
