### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by VMirik** [platformio/platformio-core#1718]
PIO Core Call Error: The next files/directories have been created in C:\Users\vmiroshnichenko\Documents\PlatformIO\Projects\Romer
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Processing nucleo_f446ze (platform: ststm32; board: nucleo_f446ze; framework: mbed)

 [SUCCESS] Took 0.20 seconds

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1616
