### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by vietez** [platformio/platformio-core#1720]
PIO Core Call Error: The next files/directories have been created in C:\Users\DieterAdm\Documents\PlatformIO\Projects\180704-133042-pico32
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Processing pico32 (platform: espressif32; board: pico32; framework: arduino)

PackageManager: Installing toolchain-xtensa32 @ ~2.50200.0
Downloading
Downloading
Unpacking
Unpacking
Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'pico32'
 [ERROR] Took 23.24 seconds

**Comment by ivankravets** [comment]
Error: Unknown board ID 'pico32'

See https://platformio.org/boards
