### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by larsjueljensen** [platformio/platformio-core#1721]
PIO Core Call Error: The next files/directories have been created in /Users/larsjueljensen/Documents/PlatformIO/Projects/ThePiChamber
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing linux_arm
Downloading...
Unpacking...
linux_arm @ 1.4.6 has been successfully installed!
PackageManager: Installing toolchain-gccarmlinuxgnueabi @ ~1.40802.0
Downloading...
Unpacking...
toolchain-gccarmlinuxgnueabi @ 1.40802.0 has been successfully installed!
The platform 'linux_arm' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.

Error: PlatformIO temporary does not support cross-compilation for WiringPi framework. Please use PIO Core directly on Raspberry Pi

**Comment by ivankravets** [comment]
Fixed in the recent PIO Home 0.9.7 which will be deployed soon.
