### ISSUE TITLE
vs

### ISSUE THREAD

**Issue by jhoughjr** [platformio/platformio-core#1723]
PIO Core Call Error: Library Storage: /Users/jimmyhoughjr/Documents/PlatformIO/Projects/routeKeeper/.piolibdeps

Error: Detected unknown package '/Users/jimmyhoughjr/Documents/PlatformIO/Projects/routeKeeper/.piolibdeps/U8g2_ID942 @ *'

**Comment by ivankravets** [comment]
Please reopen PIO Home
