### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ronyef** [platformio/platformio-core#1731]
PIO Core Call Error: The next files/directories have been created in C:\Users\Hp\Documents\PlatformIO\Projects\MMU
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Detected unknown package 'tool-scons'

**Comment by ivankravets** [comment]
You need to have access to install dependent packages. Please re-init project again.
