### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by jjongyeonglee** [platformio/platformio-core#1733]
PIO Core Call Error: PlatformManager: Installing espressif8266
Downloading
Downloading
Unpacking
Unpacking
espressif8266 @ 1.7.3 has been successfully installed!
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
Downloading
Downloading
Unpacking
Unpacking
Warning! Package Mirror: Could not extract `xtensa-lx106-elf/lib` to `/Users/leejongyoung/.platformio/packages/_tmp_installing-Yne8oI-package`. Try to disable antivirus tool or check this solution -> http://bit.ly/faq-package-manager
Looking for another mirror...
Downloading...
Unpacking
Unpacking
Warning! Package Mirror: Could not extract `xtensa-lx106-elf/lib` to `/Users/leejongyoung/.platformio/packages/_tmp_installing-Kf3PHT-package`. Try to disable antivirus tool or check this solution -> http://bit.ly/faq-package-manager
Looking for another mirror...

Error: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'darwin_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio-core/commit/f2c4ba1895a900c6a29f2584fcf546c7183ba6b7

Please open PIO IDE Terminal and run `pio upgrade --dev`. It should work now.
