### ISSUE TITLE
Home: Could not list directory/private/var/folders/04/4lmq617s0fx7yzf64ckf4jx00000gn/T/AppTranslocation/A83777AA-5DF3-442B-8EA3-F8E0549D3DB6

### ISSUE THREAD

**Issue by tongcuctruynatoipham** [platformio/platformio-core#1741]
Could not list directory by `/private/var/folders/04/4lmq617s0fx7yzf64ckf4jx00000gn/T/AppTranslocation/A83777AA-5DF3-442B-8EA3-F8E0549D3DB6`

**Comment by ivankravets** [comment]
Please check that you have access to this folder
