### ISSUE TITLE
Cannot uninstall 'lockfile'

### ISSUE THREAD

**Issue by wasi54** [platformio/platformio-core#1744]
I just want to report as adviced below!

Problem with [Installer Script](http://docs.platformio.org/en/latest/installation.html#installation-installer-script) (Super-Quick) on Linux Mint MATE (ubuntu based package repository)

# python get-platformio.py

==> Installing Python Package Manager ...
pip 10.0.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

[SUCCESS]

==> Installing PlatformIO and dependencies ...
Collecting platformio
  Downloading https://files.pythonhosted.org/packages/8c/f9/1da2df1b4b66e5ec777df79613ea3e8db3228f6121c7ae15803d79bc5157/platformio-3.5.4-py27-none-any.whl (138kB)
Requirement not upgraded as not directly required: colorama in /usr/local/lib/python2.7/dist-packages (from platformio) (0.3.9)
Requirement not upgraded as not directly required: requests<3,>=2.4.0 in /usr/lib/python2.7/dist-packages (from platformio) (2.4.3)
Collecting lockfile<0.13,>=0.9.1 (from platformio)
  Downloading https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting pyserial!=3.3,<4,>=3 (from platformio)
  Downloading https://files.pythonhosted.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193kB)
Collecting click<6,>=5 (from platformio)
  Downloading https://files.pythonhosted.org/packages/8f/98/14966b6d772fd5fba1eb3bb34a62a7f736d609572493397cdc5715c14514/click-5.1-py2.py3-none-any.whl (65kB)
Collecting semantic-version<3,>=2.5.0 (from platformio)
  Downloading https://files.pythonhosted.org/packages/72/83/f76958017f3094b072d8e3a72d25c3ed65f754cc607fdb6a7b33d84ab1d5/semantic_version-2.6.0.tar.gz
Collecting bottle<0.13 (from platformio)
  Downloading https://files.pythonhosted.org/packages/bd/99/04dc59ced52a8261ee0f965a8968717a255ea84a36013e527944dbf3468c/bottle-0.12.13.tar.gz (70kB)
Installing collected packages: lockfile, pyserial, click, semantic-version, bottle, platformio
  Found existing installation: lockfile 0.8

Cannot uninstall 'lockfile'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

[FAILURE]
The installation process has been FAILED!
Please report about this problem here
< https://github.com/platformio/platformio-core/issues >

**Comment by ivankravets** [comment]
We removed `lockfile` dependency in https://github.com/platformio/platformio-core/commit/e1578dabac936a1595ff127c07b113804e3d7212

Please use the latest dev/version http://docs.platformio.org/en/latest/installation.html#development-version
