### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by josephmcclane** [platformio/platformio-core#1749]
PIO Core Call Error: The next files/directories have been created in C:\\jos
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Detected unknown package 'tool-scons'

**Comment by ivankravets** [comment]
Please check Internet connection and restart IDE.

**Comment by jankap** [comment]
It's usually a proxy problem. Could not solve it yet.

**Comment by ivankravets** [comment]
Please set environment variables. See http://docs.python-requests.org/en/master/user/advanced/#proxies
