### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mjhejazi** [platformio/platformio-core#1752]
PIO Core Call Error: The next files/directories have been created 
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Processing black_F407ZG (platform: ststm32; board: black_F407ZG; framework: mbed)

PackageManager: Installing framework-mbed @ ~4.50806.0
Downloading
Downloading
Unpacking
Unpacking
Verbose mode can be enabled via `-v, --verbose` option
Error: Unknown board ID 'black_F407ZG'
 [ERROR] Took 377.21 seconds

**Comment by ivankravets** [comment]
Error: Unknown board ID 'black_F407ZG'
