### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by asitemap** [platformio/platformio-core#1753]
PIO Core Call Error: Library Storage: /Users/ntodorov/.platformio/lib
Updating SG_Helper                       @ 0.0.7          [1.0]
Uninstalling SG_Helper @ 0.0.7: 	[OK]
Looking for SG_Helper library in registry

Error: Library `{'requirements': u'1.0', 'name': 'SG_Helper'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': u'1.0', 'name': 'SG_Helper'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
This library was removed by its author.
