### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by PyePhyo** [platformio/platformio-core#1755]
PIO Core Call Error: Library Storage: C:\Users\HP\.platformio\lib
Looking for arduino mega library in registry

Error: Library `{'requirements': None, 'name': 'arduino mega'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'arduino mega'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
Error: Library {'requirements': None, 'name': 'arduino mega'}

See https://platformio.org/lib
