### ISSUE TITLE
Feature Request Support  RealTek Arduino Ameba boards

### ISSUE THREAD

**Issue by openAccess** [platformio/platformio-core#1757]
What kind of issue is this?

- [ ] **Feature Request**.
How can I create a custom Platform for the RealTek Arduino Ameba boards. It would be great is PlatformIO supported this board since it uses very little power and great for embedded systems.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/769

**Comment by chris-hatton** [comment]
There is an ongoing effort by [8Devices](https://www.8devices.com/) to bring the [RTL8710](https://en.wikipedia.org/wiki/RTL8710) (['Standard' GCC SDK](https://www.amebaiot.com/en/ameba-sdk-intro/)) to PlatformIO.

See: https://github.com/8devices/platformio-realtek-rtl8710b
