### ISSUE TITLE
PlatformManager: print size of packages

### ISSUE THREAD

**Issue by dontsovcmc** [platformio/platformio-core#1767]
It's rarely needed feature, but very usefull with low speed internet: "Downloading" freezing... You don't know what's wrong.

```
$ platformio run -t upload
Processing attiny85 (framework: arduino; platform: atmelavr; board: attiny85)

PlatformManager: Installing atmelavr
Downloading
Downloading
```

**Comment by ivankravets** [comment]
PlatformIO Core provides this information. Currently, PlatformIO IDE suppresses detailed output to avoid issues with a built-in terminal.

Please move this issue to https://github.com/platformio/platformio-vscode-ide/issues and I'll add an option to settings where you can enable verbose downloading/installation.
