### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by aemmenet** [platformio/platformio-core#1774]
PIO Core Call Error: Platform C:\Users\AemmeNet\.platformio\platforms\espressif32@src-5f117260f75b328038ec9d3fd0e14a68
--------

Error: Detected unknown package 'C:\Users\AemmeNet\.platformio\platforms\espressif32@src-5f117260f75b328038ec9d3fd0e14a68 @ *'

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio update`. Restart IDE. Should work now.
