### ISSUE TITLE
Add mbed support to RedbearLabs BLE Nano 2

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio-core#1777]
Currently, PIO only provides the android framework for the RedbearLabs BLE Nano 2 board. The mBed framework already supports this board as RBLAB_BLENANO2, so I propose adding the following line to `variants_remap.json`:
```
    "redbear_blenano2": "RBLAB_BLENANO2",
```

**Comment by ivankravets** [comment]
Thanks! Resolved in https://github.com/platformio/platform-nordicnrf52/commit/c14931b90f98d7b01c6a08b419617abbb1b3f767
