### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by EdwinKestler** [platformio/platformio-core#1779]
PIO Core Call Error: Library Storage: C:\Users\Edwin Kestler\.platformio\lib
Updating NtpClientLib                    @ 2.5.0          [2.5.1]

Uninstalling NtpClientLib @ 2.5.0: 	[OK]
Looking for NtpClientLib library in registry
Found: https://platformio.org/lib/show/727/NtpClientLib
LibraryManager: Installing id=727 @ 2.5.1

Downloading...
Unpacking...
NtpClientLib @ 2.5.1 has been successfully installed!
Installing dependencies
LibraryManager: Installing Time
git version 1.9.5.msysgit.1

Cloning into 'C:\Users\Edwin Kestler\.platformio\lib\_tmp_installing-qblfkv-package'...
fatal: unable to access 'https://github.com/PaulStoffregen/Time/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/PaulStoffregen/Time', 'C:\\Users\\Edwin Kestler\\.platformio\\lib\\_tmp_installing-qblfkv-package']

**Comment by ivankravets** [comment]
> routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Please upgrade your GIT client
