### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by EdwinKestler** [platformio/platformio-core#1780]
PIO Core Call Error: Library Storage: C:\Users\Edwin Kestler\.platformio\lib
Updating WiFiManager                     @ 0.13           [1.0]

Uninstalling WiFiManager @ 0.13: 	[OK]
Looking for WiFiManager library in registry
Found: https://platformio.org/lib/show/567/WifiManager
LibraryManager: Installing id=567 @ 1.0

Error: Could not find a version that satisfies the requirement '1.0' for your system 'windows_x86'

**Comment by ivankravets** [comment]
See available versions https://platformio.org/lib/show/567/WifiManager
