### ISSUE TITLE
Home: Error occurred while requesting content from https://raw.githubusercontent.com/MajenkoLibraries/DisplayCore/master/Drivers/SSD1306/library.json

### ISSUE THREAD

**Issue by xinuxnt** [platformio/platformio-core#1781]
Could not fetch content `https://raw.githubusercontent.com/MajenkoLibraries/DisplayCore/master/Drivers/SSD1306/library.json`

**Comment by rkrasin** [comment]
The library moved to https://github.com/DisplayCore/DisplayCore/blob/master/library.json

**Comment by ivankravets** [comment]
Thanks, all libraries by @MajenkoLibraries are fixed https://platformio.org/lib/search?query=author%253A%2522Majenko%20Technologies%2522
