### ISSUE TITLE
PlatformManager: Show valid error when internet is off-line

### ISSUE THREAD

**Issue by kondex** [platformio/platformio-core#1784]
PIO Core Call Error: The next files/directories have been created in E:\ARDUINO\PROJECTS\oled
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing espressif8266

Error: Detected unknown package 'espressif8266'

**Comment by rkrasin** [comment]
May I suggest that improving an error message here might be beneficial for the users?
