### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by GerogeFu** [platformio/platformio-core#1788]
PIO Core Call Error: The next files/directories have been created in C:\Users\George\Documents\PlatformIO\Projects\180809-173320-megaatmega1280
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing atmelavr
Downloading...
Unpacking...
atmelavr @ 1.9.0 has been successfully installed!
PackageManager: Installing toolchain-atmelavr @ ~1.40902.0

Downloading...
Warning! Package Mirror: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Looking for another mirror...

Error: Please read http://bit.ly/package-manager-ioerror
Error: Could not install 'toolchain-atmelavr' with version requirements '~1.40902.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Connection broken. Please check internet connection or use  http://bit.ly/faq-package-manager
