### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by AlexandreAgostini** [platformio/platformio-core#1791]
PIO Core Call Error: The next files/directories have been created in C:\Users\alexandre.agostini\Documents\PlatformIO\Projects\WeatherStation
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Unknown board ID 'uno'

Got this error when trying to create first project.

PlatformIO V; Core 3.6.0
                      Home 1.0.2
VSC: Version: 1.26.0
      Commit: 4e9361845dc28659923a300945f84731393e210d  
      Date: 2018-08-13T16:29:31.933Z
      Electron: 2.0.5
      Chrome: 61.0.3163.100
      Node.js: 8.9.3
      V8: 6.1.534.41
      Architecture: x64

**Comment by ivankravets** [comment]
Please check internet connection and try again
