### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by cawena** [platformio/platformio-core#1794]
PIO Core Call Error: Library Storage: /Users/pascalclement/.platformio/lib
Updating Adafruit ST7735 Library         @ 1.0.8          [1.2.1]
Uninstalling Adafruit ST7735 Library @ 1.0.8: 	[OK]
Looking for Adafruit ST7735 Library library in registry

Error: Library `{'requirements': u'1.2.1', 'name': 'Adafruit ST7735 Library'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': u'1.2.1', 'name': 'Adafruit ST7735 Library'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
There is no this library. Please fix manifest https://platformio.org/lib/search?query=name:%22Adafruit%20ST7735%20Library%22
