### ISSUE TITLE
Core/Build: Variables appended to CPPDEFINES in extra_scripts py files are not accessible from project.cpp files.

### ISSUE THREAD

**Issue by teolitto** [platformio/platformio-core#1797]
### Summary
Variables appended to CPPDEFINES by extra_scripts .py files are not accessible from project .cpp files.

If I attempt to programmatically define a set of variables (e.g. passwords read from a passwords.txt) using the extra_scripts functionality from platformio.ini, the variables I define in the platformio.ini via build_flags are accessible to my CPP files, but the ones I define in the extra scripts are not accessible to my CPP files. 

I suspect that "pre" scripts are having their values overwritten by the values platformio.ini pushes in, and that "post" scripts, as per the documentation, are running after the CPP files have been compiled, and as a result of these two behaviors, the values are never available to the CPP files. 

Minimal reproduction case has been pushed here: https://github.com/teolitto/pio_extra_scripts_issue

### Configuration

**Operating system**:
win10

**PlatformIO Version** (`platformio --version`):
3.6.0

**Comment by ivankravets** [comment]
Do you use the latest release of ESP32 dev/platform? It should be fixed recently.
