### ISSUE TITLE
Dynamic flags does not seems to work

### ISSUE THREAD

**Issue by fmuntean** [platformio/platformio-core#1799]
I am trying to use the dynamic build flags as described here: docs.platformio.org/en/latest/projectconf/section_env_build.html#dynamic-build-flags

[my_environment]
build_flags = ${esp8266_4M.build_flags} -D PLUGIN_SET_MFD -D USE_CUSTOM_H -D FEATURE_ADC_VCC=true !python git_rev_macro.py

It does not seem to insert the output of the python 

running the python file directly shows the correct results.

this is the content of the python file
import subprocess

#revision = subprocess.check_output(["git", "rev-parse", "HEAD"]).strip()
revision = subprocess.check_output(["git", "describe"]).strip()
print "-D BUILD_GIT=%s" % revision

I am running the platformIO under VSCode in Windows

Please help getting the dynamic build flag working

**Comment by ivankravets** [comment]
Thanks for the report! 

1. Please upgrade to the latest development version `pio upgrade --dev`
2. Use dynamic build flags from the new line. For example,
```
build_flags =
  ${esp8266_4M.build_flags} -D PLUGIN_SET_MFD -D USE_CUSTOM_H -D FEATURE_ADC_VCC=true
  !python git_rev_macro.py
```

It should work now.
