### ISSUE TITLE
Not all the tests results are displayed in unit testing (unity, test)

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-core#1805]
### Configuration

**Operating system**: Windows 8.1

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.6.0

### Description of problem

[A] We can see this bug directly on the tutorial documentation here (so you can follow these steps to reproduce them) :

https://docs.platformio.org/en/latest/tutorials/nordicnrf52/arduino_debugging_unit_testing.html#writing-unit-tests

![image](https://user-images.githubusercontent.com/15887222/44527432-12ed5500-a6e7-11e8-85a6-bdfba7de38e2.png)

As you can see there is 11 tests that have run, and only 6 are displayed. There is also 1 failure which is not desplayed. 

So as we can see the bug is that the unit testing module doesn't display all the results, this is a bug. Besides, there is a failure, I don't know if it is a real one, but this failure is not displayed.

### Additional remarks

[B] Note also that "1 Failures" (instead of "1 Failure" or "1 Failure(s)") is a grammatical error. 

[C] It will be good and more coherent if the test abstract shows "11 Test(s) 1 Failure(s) 10 Passed 0 Ignored" and not only "11 Test(s) 1 Failure(s) 0 Ignored".

**Comment by Navis-Raven** [comment]
This issue is linked to this one : https://github.com/platformio/platformio-docs/issues/33

**Comment by Navis-Raven** [comment]
this one is solved by the documentation

**Comment by ivankravets** [comment]
Thanks! Docs also should be fixed.
