### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Minzp** [platformio/platformio-core#1811]
PIO Core Call Error: The next files/directories have been created in /home/min/Documents/PlatformIO/Projects/LED
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error:

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1616

**Comment by ivankravets** [comment]
Which board did you select?

**Comment by Minzp** [comment]
Sorry, this is my first time using VScode, also is my first time using Github, and my English is not good, so, I'm very sorry that I didn't reply you in time.

**Comment by Minzp** [comment]
STM32F407VET6

**Comment by Minzp** [comment]
I'm sorry, I'm using MDK now.
