### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by zekageri** [platformio/platformio-core#1815]
PIO Core Call Error: The next files/directories have been created in C:\Users\Hitec\Documents\PlatformIO\Projects\lan
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Processing nodemcuv2 (platform: espressif8266; board: nodemcuv2; framework: arduino)

Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Espressif 8266 > NodeMCU 1.0 (ESP-12E Module)
SYSTEM: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 26 compatible libraries
Scanning dependencies...
No dependencies

*** SyntaxError `unexpected EOF while parsing (<string>, line 1)' trying to evaluate `$EXa0.627'
File "C:\Users\Hitec\.platformio\penv\lib\site-packages\platformio\builder\tools\pioide.py", line 148, in DumpIDEData
 [ERROR] Took 0.72 seconds

**Comment by ivankravets** [comment]
Please reopen if you still need help
