### ISSUE TITLE
Package dependency by owner

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#1824]
Implement an option to declare library/platform/tool dependencies by a specific owner using the next format:
```
owner/PKGNAME @ SemVerSpec
```

For example, `platformio.ini`

```
[env:myenv]
platform = platformio/nordicnrf52 @ ^4.4.0
board = ...
lib_deps = 
  owner/libname
  owner2/libname2 @ >2.0,!=2.3.4
```

CLI
```
pio lib -g install "owner/lib"
```

**Comment by cr1st1p** [comment]
Just a note to think about it (also related to #1138): ArduinoJWT library is present *twice* in the repository. 
Same author, different version numbering though. 
I tried to load it by name and version. (ArduinoJWT@~02)
Program picked the wrong library and then tried to search for the version - which it failed to find.

**Comment by ivankravets** [comment]
Sorry for the delay. We will back to this issue soon. We need new data in registry ("owner" info)

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/893ca1b328523650a9832ba2dbfaf14994d61584
