### ISSUE TITLE
When starting debug session, the console does not switch from the terminal to the debug console

### ISSUE THREAD

**Issue by SDS-Emb** [platformio/platformio-core#1825]
- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 8.1

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.6.1a1

### Description of problem
When starting debug session, the console does not switch from the terminal to the debug console

#### Steps to Reproduce

1. Start any debug session with any dev card (for example STM32 Disovery IOT Node) with any code

### Actual Results
See that all look like nothing happens on the console (New Terminal(*)), however all is prompting in the debug console tab

### Expected Results
It should switch automaticaly from "terminal" console" to "debug" console

(*): I don't know why there is the same name for the terminal tab, and "New Terminal" command which doesn't open only a terminal but also 3 other tabs: it might be confusing

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/a477e8cb23ae115eb49eff1da04a4be4f23d5a84

Default debug configuration will work without Pre-Debug. Please run VSCode > Activity Bar (Left side) > PlatformIO > Updates > Upgrade PlatformIO Core.
