### ISSUE TITLE
Issue while installing 'face_recognition'

### ISSUE THREAD

**Issue by NVDEEPAK** [platformio/platformio-core#1828]
Command "c:\users\ds04\appdata\local\programs\python\python35\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\DS04\\AppData\\Local\\Temp\\pip-install-mvgxxagf\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\DS04\AppData\Local\Temp\pip-record-xacviw9f\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\DS04\AppData\Local\Temp\pip-install-mvgxxagf\dlib\

I got this issue while installing 'face_recognition', kindly help.

**Comment by ivankravets** [comment]
https://community.platformio.org/
