### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Jason0416** [platformio/platformio-core#1831]
Invalid `platformio.ini`, project configuration file: 'File contains no section headers.
file: /Users/JasonAir/Documents/PlatformIO/Projects/180903-170935-mbed-rtos/platformio.ini, line: 11
' [env:nucleo_f030r8]\n''

**Comment by ivankravets** [comment]
'File contains no section headers.
file: /Users/JasonAir/Documents/PlatformIO/Projects/180903-170935-mbed-rtos/platformio.ini, line: 11
' [env:nucleo_f030r8]\n''

Please check INI syntax
