### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by DickSwart** [platformio/platformio-core#1834]
Invalid `platformio.ini`, project configuration file: 'File contains no section headers.
file: /Users/dickswart/Documents/PlatformIO/Projects/Multisensor/platformio.ini, line: 11
'/dev/cu.SLAB_USBtoUART\n''

**Comment by ivankravets** [comment]
> File contains no section headers.

Please check a syntax of `platformio.ini`. See https://en.wikipedia.org/wiki/INI_file
