### ISSUE TITLE
UI blurs away from cursor area over time

### ISSUE THREAD

**Issue by ieatacid** [platformio/platformio-core#1836]
### Configuration

**Operating system**: Windows 10.0.17134 x64

**PlatformIO Version**:  3.6.1a4

### Description of problem
While working or idle the UI starts blur around the area that has cursor focus (see screenshot). Clicking into another area (up or down a few lines) clears the blurriness, but it returns 5 to 10 seconds later. It's not sudden, it starts to fuzz then, as seconds go on, it gets more blurry. The worst it gets is pictured in the screenshot I've attached.

I've first encountered the problem on Atom some months ago, then recenently installed PlatformIO in VS Code with thinking that maybe Atom was the problem. To my surprise the exact same thing happened with VS Code as did with Atom. VS Code did not do this prior to installing PIO.

![vscode_blur2](https://user-images.githubusercontent.com/1000007/45259206-265e1880-b395-11e8-8ef7-82258b81430c.png)

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/Microsoft/vscode/issues
