### ISSUE TITLE
DISCOF407VG RAM size

### ISSUE THREAD

**Issue by masoudr** [platformio/platformio-core#1837]
Hi,
Please fix the [disco_f407vg ](https://www.st.com/en/evaluation-tools/stm32f4discovery.html)board. It has 192KB of ram, but in PIO I get 128KB for `mbed` platform.
And It would be better to add a single chip type for `stm32f407vgt6` instead of DISCO boards.
Full specs are [here](https://www.st.com/content/st_com/en/products/microcontrollers/stm32-32-bit-arm-cortex-mcus/stm32-high-performance-mcus/stm32f4-series/stm32f407-417/stm32f407vg.html).
Thanks.

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-ststm32/issues
