### ISSUE TITLE
Enable monitoring via TCP/IP connection

### ISSUE THREAD

**Issue by blackketter** [platformio/platformio-core#1838]
For devices that are updated via the network (ESP8266/ESP32, for example) or for debugging ports that are network connected, it would be great to be able to specify a telnet: or ssh: URL to connect to for monitoring.

**Comment by ivankravets** [comment]
Could you try `pio device monitor -p ip:port`?

**Comment by blackketter** [comment]
It was worth a shot, but:
`could not open port u'192.168.2.12:23': [Errno 2] could not open port 192.168.2.12:23: [Errno 2] No such file or directory: '192.168.2.12:23'`

**Comment by ivankravets** [comment]
Sorry, just checked docs, try 
```
platformio device monitor -p socket://<host>:<port>
```

**Comment by ivankravets** [comment]
See https://pyserial.readthedocs.io/en/latest/url_handlers.html#urls

If it wroks, I'll update our docs and put links to PySerial.

**Comment by blackketter** [comment]
It locked up the first time, but seems to work now!  Nifty!

Thanks again, Ivan!
