### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by rosleno320** [platformio/platformio-core#1840]
PIO Core Call Error: Library Storage: C:\Users\blah\.platformio\lib
LibraryManager: Installing id=727
Downloading...
Unpacking
Unpacking
NtpClientLib @ 2.5.1 has been successfully installed!
Installing dependencies
LibraryManager: Installing Time
git version 2.12.2

Cloning into 'C:\Users\blah\.platformio\lib\_tmp_installing-60jzg6-package'...
fatal: Invalid path '/cygdrive/c/Users/blah/.platformio/lib/_tmp_installing-60jzg6-package/C:\Users\blah\.platformio\lib\_tmp_installing-60jzg6-package': No such file or directory
Error: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'https://github.com/PaulStoffregen/Time', 'C:\\Users\\blah\\.platformio\\lib\\_tmp_installing-60jzg6-package']

**Comment by ivankravets** [comment]
```
 pio lib -g install https://github.com/PaulStoffregen/Time
Library Storage: /Users/ikravets/.platformio/lib
LibraryManager: Installing Time
git version 2.17.0 (Apple Git-106)
Cloning into '/Users/ikravets/.platformio/lib/_tmp_installing-0cCPPE-package'...
remote: Counting objects: 39, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 39 (delta 2), reused 26 (delta 0), pack-reused 0
Unpacking objects: 100% (39/39), done.
Time @ a8f9be7 has been successfully installed!
```

Please check that antivirus system does not block PlatformIO.
