### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by VictorVihtori** [platformio/platformio-core#1843]
Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\Users\Documents\PlatformIO\Projects\Lora\platformio.ini
	[line 17]: 'Lora\n''

**Comment by ivankravets** [comment]
Invalid platformio.ini, project configuration file: 'File contains parsing errors: C:\Users\Documents\PlatformIO\Projects\Lora\platformio.ini
[line 17]: 'Lora\n''

https://en.wikipedia.org/wiki/INI_file
