### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by pelti** [platformio/platformio-core#1850]
PIO Core Call Error: The next files/directories have been created in C:\Users\Lenovo\Documents\PlatformIO\Projects\fokkari
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Unknown board ID 'nanoatmega328new'

**Comment by ivankravets** [comment]
Please update `atmelavr` dev/platform. PlatformIO IDE for VSCode > PlatformIO Activity (left side bar ) > Updates.
