### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Troupal** [platformio/platformio-core#1856]
'ascii' codec can't encode character u'\xc9' in position 44: ordinal not in range(128)

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/143

**Comment by Troupal** [comment]
I am not on Windows OS but on GNU/Linux Manjaro. Which doesn't seem to match the issue 143.

**Comment by ivankravets** [comment]
Do you have non-ascii chars in the path?
