### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by levin-kelevra** [platformio/platformio-core#1857]
PIO Core Call Error: Platform /home/slevinkelevra/.platformio/platforms/espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d
--------
Updating espressif32                     @ d4c38ab        [Up-to-date]
Updating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]
Updating tool-openocd-esp32              @ 1.1000.20180729[Up-to-date]
Updating tool-mkspiffs                   @ 2.230.0        [Up-to-date]
Updating framework-arduinoespressif32    @ a0f0bd9        [e5ea089]
git version 2.7.4

From https://github.com/espressif/arduino-esp32
   a0f0bd9..e5ea089  master     -> origin/master
fatal: Not a git repository: /home/slevinkelevra/.platformio/packages/_tmp_installing-F_lFMA-package/.git/modules/libraries/AzureIoT
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment]
Please remove this package `/home/slevinkelevra/.platformio/packages/framework-arduinoespressif32` and restart IDE.
