### ISSUE TITLE
Home: Could not list directory/home/demon

### ISSUE THREAD

**Issue by demonskull** [platformio/platformio-core#1860]
Hi there,

When trying to open a project, I get the following message:

"Could not list directory/home/demon"
"Could not list directory by /home/demon"
where demon is my user name. It looks like a problem with permissions, but no idea.

I'm using Platformio IDE 2.2.2 on Atom 1.26.1 ia32. OS is Ubuntu 16.04, CPU is Intel 32 bits (Hence the old version of Atom)

Thanks in advance.

**Comment by ivankravets** [comment]
Please provide 
```
ls -al /home/demon
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
