### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by BigBadBri** [platformio/platformio-core#1863]
Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\Users\Brian\Documents\PlatformIO\Projects\Blomk1\platformio.ini
	[line 17]: '// Set LED_BUILTIN if it is not defined by Arduino framework\n'
	[line 18]: '// #define LED_BUILTIN 13\n'
	[line 20]: 'void setup()\n'
	[line 21]: '{\n'
	[line 24]: '}\n'
	[line 26]: 'void loop()\n'
	[line 27]: '{\n'
	[line 39]: '}''

**Comment by ivankravets** [comment]
Please check syntax https://en.wikipedia.org/wiki/INI_file
