### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by xukao** [platformio/platformio-core#1864]
PIO Core Call Error: The next files/directories have been created in C:\Users\Administrator\Documents\PlatformIO\Projects\xk_esp32
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries
PlatformManager: Installing espressif32
Downloading
Downloading
Unpacking
Unpacking
espressif32 @ 1.3.0 has been successfully installed!

Error:

**Comment by ivankravets** [comment]
Could you provide more details?

**Comment by ivankravets** [comment]
Please reopen if you still need help
