### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by qvinh222** [platformio/platformio-core#1869]
PIO Core Call Error: Platform C:\Users\Vinh\.platformio\platforms\espressif32
--------
Updating espressif32                     @ 0aa4e7b        [0632d52]
git version 2.17.0.windows.1
Updating 0aa4e7b..0632d52

From https://github.com/platformio/platform-espressif32
   d4c38ab..0632d52  feature/stage -> origin/feature/stage
 * [new tag]         v1.4.0        -> v1.4.0
error: Your local changes to the following files would be overwritten by merge:
	boards/esp32doit-devkit-v1.json
Please commit your changes or stash them before you merge.
Aborting
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment]
Please decide what to do with "boards/esp32doit-devkit-v1.json".
