### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by RiPeter** [platformio/platformio-core#1872]
Invalid `platformio.ini`, project configuration file: 'While reading from u'C:\\Users\\peter\\Documents\\PlatformIO\\Projects\\ESP32_BLE_Server\\platformio.ini' [line 14]: option u'board' in section u'env:featheresp32' already exists'

**Comment by ivankravets** [comment]
Please check your C:\Users\peter\Documents\PlatformIO\Projects\ESP32_BLE_Server\platformio.ini

See explanation above.
