### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by mike-serinus** [platformio/platformio-core#1874]
PIO Core Call Error: Platform C:\Users\mike_\.platformio\platforms\espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d
--------
Updating espressif32                     @ 0632d52

Error: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'returncode': 128, 'err': "fatal: unable to access 'https://github.com/platformio/platform-espressif32.git/': Empty reply from server\n", 'out': ''})

**Comment by ivankravets** [comment]
Please try again, it seems that GitHub host was down.
