### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by pppxcom** [platformio/platformio-core#1882]
PIO Core Call Error: The next files/directories have been created in C:\Users\Administrator\Documents\PlatformIO\Projects\181018-235147-arduino-blink
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Error:

**Comment by ivankravets** [comment]
Could you provide more details?

**Comment by ivankravets** [comment]
Please reopen if you still need help
