### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by yantocobain** [platformio/platformio-core#1885]
PIO Core Call Error: The next files/directories have been created in /Users/kontri/Documents/PlatformIO/Projects/181021-112859-esp8266-nonos-sdk-blink
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Error: Detected unknown package 'framework-esp8266-nonos-sdk'

**Comment by ivankravets** [comment]
Please check your internet connection, proxy, etc.
