### ISSUE TITLE
Upload failure when trying to upload esp-idf to esp32

### ISSUE THREAD

**Issue by wegunterjr** [platformio/platformio-core#1888]
Linux OS - compiles fine, and I can connect serial, but when I try to upload, it gets the following error.
I have also deleted .pioenvs and started the build again to make sure and get the same error. I cannot upload any compiled code.

```
Uploading .pioenvs/esp-wrover16/firmware.bin
sh: 1: Syntax error: "(" unexpected
*** [upload] Error 2
```

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif32/issues
