### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by isjianjian** [platformio/platformio-core#1890]
PIO Core Call Error: The next files/directories have been created in /Users/wz/Documents/PlatformIO/Projects/test
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Error: Could not install 'framework-arduinoespressif8266' with version requirements '~2.20402.0' for your system 'darwin_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please provide an output from a system Terminal
```
echo $PATH
echo $PYTHONPATH
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
