### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by mimik130** [platformio/platformio-core#1891]
PIO Core Call Error: Error: Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\Users\Admin\Documents\PlatformIO\Projects\181024-213559-nodemcu\platformio.ini
	[line 18]: 'Blynk\n''

**Comment by ivankravets** [comment]
Please check your `platformio.ini` file. It contains errors. See https://en.wikipedia.org/wiki/INI_file
