### ISSUE TITLE
update/upgrade breaks things after download stalls, package uninstalled before successful download

### ISSUE THREAD

**Issue by zcattacz** [platformio/platformio-core#1897]
### Configuration

**Operating system**:
Windows 7

**PlatformIO Version** (`platformio --version`):

3.6.0

### Description of problem

I am using pio command line. Every time the connection stalled during a upgrade/update, ^C wouldn't stop pio, only pskill will do.
Afterwards, you will find some package is missing, and has to be installed again, before pio can be usable again.

#### Steps to Reproduce

1. pio upgrade/update
2. somehow make the connection stall
3. stop the python process since there is no other way around.

### Actual Results

random package got missing, has to be reinstalled ** most of the time, before pio become usable again **
sometimes, pio-home is removed, sometimes other big tool-chain package is gone. 

### Expected Results

pio should be in a usable state even if some package failed to download during update.

most package managers uninstall package  after new versions are downloaded completely. Not sure why pio choose to do it differently.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
Fixed in the latest dev-version. Please re-test with `pio upgrade --dev`
