### ISSUE TITLE
Home: Could not load mDNS services

### ISSUE THREAD

**Issue by SinglWolf** [platformio/platformio-core#1898]
PIO Core Call Error: Extra data: line 3 column 1 - line 3 column 115 (char 224 - 338)
OS Win 10 64, IDE vs code.
Strange, but after executing the command in the console from IDE vs code
`platformio device list --mdns`, the error disappeared...

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1582
