### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by max1140** [platformio/platformio-core#1899]
PIO Core Call Error: Library Storage: C:\Users\siyov\.platformio\lib
Looking for github.com/AlexGyver/GyverLibs library in registry

Error: Library `{'requirements': None, 'name': 'github.com/AlexGyver/GyverLibs'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'github.com/AlexGyver/GyverLibs'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by max1140** [comment]
з

**Comment by ivankravets** [comment]
Please fix dependency to `https://github.com/AlexGyver/GyverLibs.git`
