### ISSUE TITLE
Long pause after uploading via OTA and strange in console error

### ISSUE THREAD

**Issue by SinglWolf** [platformio/platformio-core#1900]
- [x] **PlatformIO Core**.
------------------------------------------------------------------

### Configuration

**Operating system**:
Win 10 64bit IDE VS Code
**PlatformIO Version** (`platformio --version`):
PlatformIO, version 3.6.1rc6
### Description of problem
Long pause after uploading via OTA and strange in console error
`Uploading .pioenvs\nodemcuv2\firmware.bin
20:16:19 [DEBUG]: Options: {'timeout': 10, 'esp_ip': '192.168.1.144', 'host_port': 14686, 'image': '.pioenvs\\nodemcuv2\\firmware.bin', 'host_ip': '0.0.0.0', 'auth': '', 'esp_port': 8266, 'spiffs': False, 'debug': True, 'progress': True}
20:16:19 [INFO]: Starting on 0.0.0.0:14686
20:16:19 [INFO]: Upload size: 304208
Sending invitation to 192.168.1.144
20:16:19 [INFO]: Waiting for device...
Uploading: [============================================================] 100% Done...

20:16:26 [INFO]: Waiting for result...
#################################### There is a long pause here
Traceback (most recent call last):
File "C:\Users\Alexander\.platformio\packages\tool-espotapy\espota.py", line 353, in <module>
sys.exit(main(sys.argv))
File "C:\Users\Alexander\.platformio\packages\tool-espotapy\espota.py", line 348, in main
return serve(options.esp_ip, options.host_ip, options.esp_port, options.host_port, options.auth, options.image, command)
File "C:\Users\Alexander\.platformio\packages\tool-espotapy\espota.py", line 220, in serve
except e:
NameError: global name 'e' is not defined
*** [upload] Error 1`
Uploaded firmware OK. Everything is working.
What could be the  problem?

**Comment by ivankravets** [comment]
This is not a PlatformIO Core issue. Please move it to https://community.platformio.org
