### ISSUE TITLE
Unknown "doglcd" library

### ISSUE THREAD

**Issue by moriusz** [platformio/platformio-core#1901]
PIO Core Call Error: Library Storage: C:\Users\Moriusz\.platformio\lib
Looking for doglcd library in registry

Error: Library `{'requirements': None, 'name': 'doglcd'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'doglcd'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
Please reopen if you still need help
