### ISSUE TITLE
Create JSON schema for library.json

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#1903]
It would be nice to have a JSON schema to validate library.json files against.

**Comment by drorgl** [comment]
Try this:
https://gist.github.com/drorgl/28ab5cf4843acc61c33ac31146ed1102

Usage:
```
{
    "$schema": "https://gist.githubusercontent.com/drorgl/28ab5cf4843acc61c33ac31146ed1102/raw/70d687dbaddf9a631fdf538338787b9526380041/library_json_schema.json",
    "name": "test library",
    "build": {
        "srcDir": "./"
    }
}
```

**Comment by ivankravets** [comment]
@drorgl, could you make PR to https://github.com/platformio/platformio-core/tree/develop/platformio/assets?

Please create a `schemas` folder and name the new schema as `library.json`. Thanks!

**Comment by drorgl** [comment]
https://github.com/platformio/platformio-core/pull/4476

**Comment by ivankravets** [comment]
Solved in https://docs.platformio.org/en/latest/manifests/library-json/fields/schema.html#manifest-library-json-schema

Thanks, @drorgl, for the PR #4476
