### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Tranhuuphuc123** [platformio/platformio-core#1907]
PIO Core Call Error: Usage: platformio init [OPTIONS]

Error: Invalid value for "--project-dir" / "-d": Directory "E:\BÁO CÁO Ð? ÁN CU?I KHOA\Tu_dong_hoa" does not exist.

**Comment by ivankravets** [comment]
This is a known issue. Please use a project where path does not contain non-ascii chars.
