### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by phuoclieu** [platformio/platformio-core#1909]
PIO Core Call Error: The next files/directories have been created in C:\Users\ADMIN\Documents\PlatformIO\Projects\RESET-PRINTER
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File
PlatformManager: Installing atmelavr
Downloading
Downloading
Unpacking
Unpacking
atmelavr @ 1.12.0 has been successfully installed!
PackageManager: Installing toolchain-atmelavr @ ~1.50400.0

Downloading
Downloading
Warning! Package Mirror: ("Connection broken: error(10053, 'An established connection was aborted by the software in your host machine')", error(10053, 'An established connection was aborted by the software in your host machine'))
Looking for another mirror...

Error: Please read http://bit.ly/package-manager-ioerror
Error: Could not install 'toolchain-atmelavr' with version requirements '~1.50400.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please check your internet connection, anti-virus and firewall tools. They can block PlatformIO. Please try again.
