### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Flo082002** [platformio/platformio-core#1910]
PIO Core Call Error: Library Storage: C:\Users\Flo\.platformio\lib
LibraryManager: Installing id=727
NtpClientLib @ 2.5.1 is already installed
Installing dependencies
LibraryManager: Installing Time

Error: Please install Git client from https://git-scm.com/downloads

**Comment by ivankravets** [comment]
Error: Please install Git client from https://git-scm.com/downloads
