### ISSUE TITLE
Allow overriding a default project "platformio.ini" configuration file

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#1913]
Allow overriding a default project "platformio.ini" configuration file using`pio run -c custom_platformio.ini` option.

If you need to merge different `platformio.ini`, see https://github.com/platformio/platformio-core/issues/1590

**Comment by TD-er** [comment]
Could such ini files also be used to setup a personal config extension?
For example have a list of env's used in the platformio.ini and add the used com port or OTA settings for each of those.
These files are very specific for a build environment/PC, so no need to have it in your version control list.

**Comment by ivankravets** [comment]
@TD-er it seems you mean this feature request https://github.com/platformio/platformio-core/issues/1590?

**Comment by TD-er** [comment]
@ivankravets Looks like it indeed :)

**Comment by ivankravets** [comment]
Docs:
- http://docs.platformio.org/en/latest/userguide/cmd_run.html#cmdoption-platformio-run-c
- http://docs.platformio.org/en/latest/userguide/cmd_test.html#cmdoption-platformio-test-c
- http://docs.platformio.org/en/latest/userguide/cmd_debug.html#cmdoption-platformio-debug-c
