### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by yusu24** [platformio/platformio-core#1921]
[Error 2] The system cannot find the file specified: u'C:\\Users\\M Yusuf Effendi\\Documents\\PlatformIO\\Projects'

**Comment by ivankravets** [comment]
Do you have this folder `C:\Users\M Yusuf Effendi\Documents\PlatformIO\Projects`? Please note that you can set a custom path for projects. http://docs.platformio.org/en/latest/userguide/cmd_settings.html#projects-dir

**Comment by hansmbakker** [comment]
@ivankravets I have the same issue and see a lot of others having it, can it have to do something with permissions?

**Comment by ivankravets** [comment]
@hansmbakker does your name also contain space project path?

**Comment by hansmbakker** [comment]
No, my issue is python not behaving well with Controlled Folder Access in Windows (see https://github.com/platformio/platformio-core/issues/1952). So different problems can lead to the same symptom (the error message in the opening post)
