### ISSUE TITLE
Home: Could not import Arduino project   (behind a proxy on Mac)

### ISSUE THREAD

**Issue by anthonygao** [platformio/platformio-core#1923]
PIO Core Call Error: The next files/directories have been created in /Users/anthonygao/Documents/PlatformIO/Projects/181113-192449-uno
platformio.ini - Project Configuration File
src - Put your source files here
lib - Put here project specific (private) libraries

Error: Detected unknown package 'tool-scons'

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-vscode-ide/issues/96#issuecomment-434256258
