### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by tommasopolonelli** [platformio/platformio-core#1924]
PIO Core Call Error: The next files/directories have been created in C:\Users\TP\AppData\Roaming\SPB_Data\Documents\PlatformIO\Projects\TestGAP
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Error: Could not install 'framework-gap_sdk' with version requirements '~1.2.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
