### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by KeenFeng** [platformio/platformio-core#1929]
PIO Core Call Error: The next files/directories have been created in /Users/keenfeng/Documents/PlatformIO/Projects/esp_nonos_test1
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File
PlatformManager: Installing espressif8266
Downloading...
Unpacking...
espressif8266 @ 1.8.0 has been successfully installed!
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
Downloading...
Unpacking...
toolchain-xtensa @ 1.40802.0 has been successfully installed!
PackageManager: Installing tool-esptool @ <2
Downloading...
Unpacking...
tool-esptool @ 1.413.0 has been successfully installed!
The platform 'espressif8266' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.

Error: Could not install 'framework-esp8266-nonos-sdk' with version requirements '>=2.1.0' for your system 'darwin_x86_64'.

Please try this solution -> http://bit.ly/faq-package-manager

**Comment by ivankravets** [comment]
Please try this solution -> http://bit.ly/faq-package-manager
