### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by gsam01** [platformio/platformio-core#1931]
Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\Users\owner\Documents\PlatformIO\Projects\g_nano\platformio.ini
	[line 26]: 'upload_flags\n''

**Comment by ivankravets** [comment]
Please check syntax of `platformio.ini` file. You have the errors.

**Comment by gsam01** [comment]
Thank you.
