### ISSUE TITLE
I can't start platformio home

### ISSUE THREAD

**Issue by davidleyabe** [platformio/platformio-core#1933]
Hi, 

I am trying to open platformio Home but I get this message:

> Start PIO Home Server
Error: Error: Traceback (most recent call last): File "c:.platformio\penv\lib\site-packages\platformio__main__.py", line 120, in main cli(None, None, None) File "c:.platformio\penv\lib\site-packages\click\core.py", line 700, in call return self.main(args, kwargs) File "c:.platformio\penv\lib\site-packages\click\core.py", line 680, in main rv = self.invoke(ctx) File "c:.platformio\penv\lib\site-packages\click\core.py", line 1027, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:.platformio\penv\lib\site-packages\click\core.py", line 873, in invoke return ctx.invoke(self.callback, ctx.params) File "c:.platformio\penv\lib\site-packages\click\core.py", line 508, in invoke return callback(args, kwargs) File "c:.platformio\penv\lib\site-packages\platformio\commands\home.py", line 31, in cli pioplus_call(sys.argv[1:]) File "c:.platformio\penv\lib\site-packages\platformio\managers\core.py", line 132, in pioplus_call code = subprocess.call([pioplus_path] + args, kwargs) File "c:.platformio\penv\lib\subprocess.py", line 172, in call return Popen(*popenargs, **kwargs).wait() File "c:.platformio\penv\lib\subprocess.py", line 394, in init errread, errwrite) File "c:.platformio\penv\lib\subprocess.py", line 644, in _execute_child startupinfo) WindowsError: [Error 2] The system cannot find the file specified

![platformio](https://user-images.githubusercontent.com/45171470/48709947-275dc280-ebee-11e8-916c-5c907ed38072.PNG)

I tried to run the command 

> pip install -U platformio

and everything seems to be ok
![platformio2](https://user-images.githubusercontent.com/45171470/48710087-73106c00-ebee-11e8-980b-eec83a880c2b.PNG)

Could you please help me?

Thanks

**Comment by ivankravets** [comment]
Please remove `C:/.platformio/penv` folder and restart IDE.

**Comment by davidleyabe** [comment]
Hi Ivan, 

Thanks for your answer. I did the procedure that you mentioned but unfortunately the problem is not solved. I got a similar message. Could you please help me?

> Error: Error: Traceback (most recent call last): File "c:\python27\lib\site-packages\platformio__main__.py", line 120, in main cli(None, None, None) File "c:\python27\lib\site-packages\click\core.py", line 700, in call return self.main(args, kwargs) File "c:\python27\lib\site-packages\click\core.py", line 680, in main rv = self.invoke(ctx) File "c:\python27\lib\site-packages\click\core.py", line 1027, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "c:\python27\lib\site-packages\click\core.py", line 873, in invoke return ctx.invoke(self.callback, ctx.params) File "c:\python27\lib\site-packages\click\core.py", line 508, in invoke return callback(args, kwargs) File "c:\python27\lib\site-packages\platformio\commands\home.py", line 31, in cli pioplus_call(sys.argv[1:]) File "c:\python27\lib\site-packages\platformio\managers\core.py", line 132, in pioplus_call code = subprocess.call([pioplus_path] + args, kwargs) File "c:\python27\lib\subprocess.py", line 172, in call return Popen(*popenargs, **kwargs).wait() File "c:\python27\lib\subprocess.py", line 394, in init errread, errwrite) File "c:\python27\lib\subprocess.py", line 644, in _execute_child startupinfo) WindowsError: [Error 2] The system cannot find the file specified

![platformio3](https://user-images.githubusercontent.com/45171470/48725630-e4164a80-ec13-11e8-9e72-29fedbb1cf8a.PNG)

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio home`. Do you see any errors?

**Comment by davidleyabe** [comment]
I have the following error:

> C:\Users\Zôdio>pio home
***********************************************************************************************************************
Obsolete PIO Core v3.6.1 is used (previous was 3.6.2b1)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
***********************************************************************************************************************
Error: Traceback (most recent call last):
  File "c:\python27\lib\site-packages\platformio\__main__.py", line 120, in main
    cli(None, None, None)
  File "c:\python27\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\platformio\commands\home.py", line 31, in cli
    pioplus_call(sys.argv[1:])
  File "c:\python27\lib\site-packages\platformio\managers\core.py", line 132, in pioplus_call
    code = subprocess.call([pioplus_path] + args, **kwargs)
  File "c:\python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

![platformio4](https://user-images.githubusercontent.com/45171470/48725880-afef5980-ec14-11e8-9157-2645d40f9424.PNG)

I am not able to solve it with the link that is specified. 

Do you have any other solutions?

Thanks

David

**Comment by ivankravets** [comment]
Do you see `tool-pioplus` folder in `C:/.platformio/packages`? Please remove this folder and try again. Do you have an antivirus in a system?

**Comment by davidleyabe** [comment]
Yes I have this folder and I removed it

![platformio5](https://user-images.githubusercontent.com/45171470/48726160-a74b5300-ec15-11e8-84d5-53b53d43ca5b.PNG)

But I have another issue:
![platformio6](https://user-images.githubusercontent.com/45171470/48726662-37d66300-ec17-11e8-9624-1f837f343308.PNG)

My antivirus is AVAST.

**Comment by ivankravets** [comment]
AVAST blocks PlatformIO. 
1. Please exclude `C:/.platformio` folder from AVAST
2. Please remove all files and folders in `C:/.platformio/`.
3. Restart IDE.

Everything should work now.

**Comment by davidleyabe** [comment]
Hi Ivan, 
It works! Thanks for your help!
David

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!
