### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by tconnolly80** [platformio/platformio-core#1934]
PIO Core Call Error: Library Storage: C:\Users\tconn\.platformio\lib
Looking for android root library in registry

Error: Library `{'requirements': None, 'name': 'android root'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'requirements': None, 'name': 'android root'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.

**Comment by ivankravets** [comment]
Please reopen if you still need help
