### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by xixxi** [platformio/platformio-core#1937]
PIO Core Call Error: Library Storage: /home/user003/.platformio/lib
Updating Adafruit SSD1306                @ ddfec78        [1973f00]
git version 2.17.1
Обновление ddfec78..1973f00

Из https://github.com/adafruit/Adafruit_SSD1306
   ddfec78..1973f00  master     -> origin/master
 * [новая метка]     1.2.9      -> 1.2.9
 * [новая метка]     1.2.0      -> 1.2.0
 * [новая метка]     1.2.1      -> 1.2.1
 * [новая метка]     1.2.2      -> 1.2.2
 * [новая метка]     1.2.3      -> 1.2.3
 * [новая метка]     1.2.4      -> 1.2.4
 * [новая метка]     1.2.5      -> 1.2.5
 * [новая метка]     1.2.6      -> 1.2.6
 * [новая метка]     1.2.7      -> 1.2.7
 * [новая метка]     1.2.8      -> 1.2.8
error: Ваши локальные изменения в указанных файлах будут перезаписаны при слиянии:
	Adafruit_SSD1306.h
Сделайте коммит или спрячьте ваши изменения перед слиянием веток.
Прерываю
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']

**Comment by ivankravets** [comment]
We don't update library/package which was installed via VCS and has modified files. Please resolve changes manually or remove this lib/package.
