### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by MikikoUmetsu** [platformio/platformio-core#1940]
PIO Core Call Error: Error: [API] Invalid response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="ja">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>èªè¨¼ã¨ã©ã¼</title>

<meta http-equiv="Pragma" content="no-cache">

<meta http-equiv="Cache-Control" content="no-cache">

<meta http-equiv="Expires" content="0">

<meta http-equiv="Content-Style-Type" content="text/css" />

<link rel="stylesheet" href="http://172.31.240.17:8080/resource/block.css" type="text/css" charset="UTF-8" />

</head>

<body id="control" class="align_center">

<div class="logo_img"><img alt="InterSafe" src="http://172.31.240.17:8080/resource/logo.png" border="0"></div>

<div class="color0 margin_bottom10 padding_top30 font_size15 font_bold">Authentication Failed.</div>

</body>

</html>

**Comment by ivankravets** [comment]
Please check your internet/proxy connection and try again.
