### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by alvarohub** [platformio/platformio-core#1944]
Server error: {"message":"[Errno 13] Permission denied: '/Users/alvaro/.platformio/.cache/3b'","args":[13,"Permission denied"],"type":"OSError"}

**Comment by alvarohub** [comment]
![image](https://user-images.githubusercontent.com/2045015/49197921-a205ab00-f36f-11e8-87e1-accf37f4ac43.png)

**Comment by ivankravets** [comment]
Please remove `/Users/alvaro/.platformio/.cache` folder and resart VSCode.

**Comment by alvarohub** [comment]
Thank you so much!! and sorry for bothering.

**Comment by ivankravets** [comment]
Does it work now?

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!
