### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by sufni** [platformio/platformio-core#1946]
Importing a very basic Arduino project with for a Teensy 3.6 board gives me the following error:

PIO Core: non-ASCII chars in arguments

**Comment by ivankravets** [comment]
Do you have non-ascii symbols in the path?

**Comment by ivankravets** [comment]
This is a bug. Please open PlatformIO IDE Terminal and type `pio update`. Restart IDE. Everything should work now.
