### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by profra** [platformio/platformio-core#1949]
PIO Core Call Error: "Platform C:\\Users\\fp.CHG\\.platformio\\platforms\\espressif8266_stage\r\n--------\r\nUpdating espressif8266                   @ ac1e0c8        [Up-to-date]\r\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\r\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\r\nUpdating tool-espotapy                   @ 1.1.2          [Up-to-date]\r\nUpdating framework-arduinoespressif8266  @ 440a3aa        [92373a9]\r\ngit version 2.11.1.windows.1\nUpdating 440a3aa..92373a9\n\nerror: Your local changes to the following files would be overwritten by merge:\n\tlibraries/esp8266/examples/interactive/interactive.ino\nPlease commit your changes or stash them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
> Please commit your changes or stash them before you merge

We don't do automatic merging if you did changes in cloned packages. Please review your changes or remove `C:\Users\fp.CHG\.platformio\platforms\espressif8266_stage` and start build again.
