### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by hansmbakker** [platformio/platformio-core#1952]
When creating a new project using a freshly installed PlatformIO, I get the error "The system cannot find the file specified":

```
Server error: {"message":"[Error 2] Het systeem kan het opgegeven bestand niet vinden: u'C:\\\\Users\\\\MyUsername\\\\Documents\\\\PlatformIO\\\\Projects\\\\BLETest'","args":[2,"Het systeem kan het opgegeven bestand niet vinden"],"type":"WindowsError"}
```
I would expect PlatformIO to create the required folder structure of `PlatformIO/Projects/BLETest` in my documents folder instead of giving this warning when you have the "use default location" box checked.

**Comment by hansmbakker** [comment]
It turns out that Windows' "Controlled folder access" will block the python file actions in the user folder unless you whitelist it.

**Comment by ivankravets** [comment]
Yes, you need to have permissions to write in a directory.
