### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by tea1975** [platformio/platformio-core#1953]
При попытке создать проект для Nucleo L476RG в Mbed, процесс инсталляции прерывается сообщением об ошибке: 
PIO Core Call Error: "<Exception instance at 0x7ed8408 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-63: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1955
