### ISSUE TITLE
Problems building even just created platformio

### ISSUE THREAD

**Issue by daecepi** [platformio/platformio-core#1954]
I had sometime since i worked on microcontroller projects, now that i came back i tried creating a new project and after builng with Esp32 and even Arduino it launched a problem.

I also tried reinstalling and upgrading platformIO with "platformIO upgrade"

I work on a windows 8.1 64 bits machine on Atom Editor

PS C:\Users\XXXXXX\Documents\PlatformIO\Projects\UnoDasas> platformio --PlatformIO, version 3.6.2
PS C:\Users\XXXXXX\Documents\PlatformIO\Projects\UnoDasas> platformio upgrade
You're up-to-date!
PlatformIO 3.6.2 is currently the newest version available.

### Steps to Reproduce

1. Open platformIO
2. Creating a blank project
3. building that project

#### main.cpp
#include <Arduino.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}

 
#### platformio.ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
 
#### COMMAND:  platformio run --target upload
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/uno.html
PLATFORM: Atmel AVR > Arduino Uno
HARDWARE: ATMEGA328P 16MHz 2KB RAM (31.50KB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(deep) COMPATIBILITY(soft)
Collected 24 compatible libraries
Scanning dependencies...
No dependencies
C:\.platformio\packages\tool-scons\script\..\engine\SCons\Environment.py:1714: UnicodeWarning: Unicode equal comparison fa
iled to convert both arguments to Unicode - interpreting them as being unequal
val = [x for x in val if x not in dk]
Compiling .pioenvs\uno\src\main.cpp.o
Archiving .pioenvs\uno\libFrameworkArduinoVariant.a
"avr-gcc-ar" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"avr-g++" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Compiling .pioenvs\uno\FrameworkArduino\CDC.cpp.o
*** [.pioenvs\uno\libFrameworkArduinoVariant.a] Error 1
Compiling .pioenvs\uno\FrameworkArduino\HardwareSerial.cpp.o
"avr-g++" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
*** [.pioenvs\uno\src\main.cpp.o] Error 1
*** [.pioenvs\uno\FrameworkArduino\CDC.cpp.o] Error 1
"avr-g++" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
*** [.pioenvs\uno\src\main.cpp.o] Error 1
*** [.pioenvs\uno\FrameworkArduino\CDC.cpp.o] Error 1
"avr-g++" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
*** [.pioenvs\uno\FrameworkArduino\HardwareSerial.cpp.o] Error 1
 [ERROR] Took 4.01 seconds

SAME SKETCH
#### platformio.ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

#### COMMAND:  platformio run --target upload
Compiling .pioenvs\esp32dev\FrameworkArduino\IPAddress.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\IPv6Address.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\MD5Builder.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\Print.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\Stream.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\StreamString.cpp.o

Compiling .pioenvs\esp32dev\FrameworkArduino\WMath.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\WString.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\base64.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\cbuf.cpp.o
Compiling .pioenvs\esp32dev\FrameworkArduino\esp32-hal-adc.c.o
xtensa-esp32-elf-gcc: error: CreateProcess: No such file or directory
Compiling .pioenvs\esp32dev\FrameworkArduino\esp32-hal-bt.c.o
*** [.pioenvs\esp32dev\FrameworkArduino\esp32-hal-adc.c.o] Error 1
xtensa-esp32-elf-gcc: error: CreateProcess: No such file or directory
*** [.pioenvs\esp32dev\FrameworkArduino\esp32-hal-bt.c.o] Error 1
 [ERROR] Took 17.70 seconds

GRACIAS DE ANTEMANO

**Comment by ivankravets** [comment]
Do you have antivirus tools in system? It seems they block builder.

**Comment by ivankravets** [comment]
Please reopen if you still need help
