### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters

### ISSUE THREAD

**Issue by zhanghaotree** [platformio/platformio-core#1955]
PIO Core Call Error: "<Exception instance at 0x65dfcc8 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 51-55: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Does your project contain non-ascii chars in path?

**Comment by ivankravets** [comment]
Please reopen if you still need help
