### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by pavellzubkov** [platformio/platformio-core#1956]
PIO Core Call Error: "<Exception instance at 0x7359ec8 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-61: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1955
