### ISSUE TITLE
'utf8' codec can't decode byte

### ISSUE THREAD

**Issue by zfeifei90** [platformio/platformio-core#1959]
'utf8' codec can't decode byte 0xce in position 9: invalid continuation byte

**Comment by ivankravets** [comment]
@AluisioRobotica @zfeifei90 what is your operating system? Do you have non-ascii char in user name?

**Comment by AluisioRobotica** [comment]
> @AluisioRobotica @zfeifei90 what is your operating system? Do you have non-ascii char in user name?

Windows 10 x64, Visual Studio Code 1.30.0, Node.js 8.9.3, PIO Home 2.0 / Core 3.6.4b1
What user name? The account PIO?

**Comment by ivankravets** [comment]
OS's user name.

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart VSCode. Does it work now?

**Comment by AndreasBahrt** [comment]
... Just to confirm that the error relates to this thread;

![CLI Error Output](https://github.com/platformio/platformio-core/assets/57658011/e6e31b55-a3e8-4bc1-9d05-4d817d8b418e)
