### ISSUE TITLE
Problem with header directory paths in .clang_complete

### ISSUE THREAD

**Issue by maxchaos** [platformio/platformio-core#1960]
When initializing a new project directory or updating an existing one with `pio init --ide emacs`, the directory paths searched for headers listed inside `.clang_complete` are enclosed in double quotes, which confuses clang-based tools (such as `irony`) and results in "file not found" errors in Emacs (`flycheck-irony`).

This is a typical line of `.clang_complete` that gets generated now:
`-I"/home/USER/.platformio/packages/framework-arduinoavr/cores/arduino"`
and this is what it should have been generated instead:
`-I/home/USER/.platformio/packages/framework-arduinoavr/cores/arduino`

**Comment by ivankravets** [comment]
Thanks for the report!
