### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by l3rros** [platformio/platformio-core#1962]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /Users/rene/Documents/PlatformIO/Projects/Pixel_Tester/platformio.ini\n\t[line 19]: '\\xe2\\x80\\xa0''","args":["File contains parsing errors: /Users/rene/Documents/PlatformIO/Projects/Pixel_Tester/platformio.ini\n\t[line 19]: '\\xe2\\x80\\xa0'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
> File contains parsing errors: /Users/rene/Documents/PlatformIO/Projects/Pixel_Tester/platformio.ini

Please fix INI file. See https://en.wikipedia.org/wiki/INI_file
