### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by fernagonzalez** [platformio/platformio-core#1963]
PIO Core Call Error: "The next files/directories have been created in /home/fernando/Documents/PlatformIO/Projects/Prueba_Arduino\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError:"

**Comment by ivankravets** [comment]
Could you provide more details? Which board did you select?

**Comment by fernagonzalez** [comment]
Is solucionated already
