### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by eddymgido** [platformio/platformio-core#1965]
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\Eddymgido\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Please restart VSCode. Do you have this folder `C:\\Users\\Eddymgido\\Documents\\PlatformIO`?
