### ISSUE TITLE
[platformio.ini] platform dependent path error when using $PROJECTSRC_DIR

### ISSUE THREAD

**Issue by cyberman54** [platformio/platformio-core#1966]
Paths which use $PROJECTDIR in `platformio.ini` seems to run on platform dependent file not found error, as reported [here](https://github.com/cyberman54/ESP32-Paxcounter/issues/219):

File not found error with Ubuntu, but runs on Windows10:

```
build_flags_basic =
    -include $PROJECTSRC_DIR/hal/${PIOENV}.h
```
    
File not found error on Windows10, but runs on Ubuntu:

```
build_flags_basic =
    -include /$PROJECTSRC_DIR/hal/${PIOENV}.h
```

**Comment by cyberman54** [comment]
Not a bug. Sorry, my fault. My path was invalid.

**Comment by cyberman54** [comment]
I need to reopen this, because i closed it to soon. This issue persists.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by cyberman54** [comment]
i found a workaround by wrapping the include parameters in "...", so can be closed, not sure if this is a clean solution, but seems to work.

**Comment by ivankravets** [comment]
Great!
