### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by sabiinsearch** [platformio/platformio-core#1971]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/boards.py\", line 29, in cli\n    return _print_boards_json(query, installed)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/boards.py\", line 81, in _print_boards_json\n    for board in _get_boards(installed):\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/boards.py\", line 76, in _get_boards\n    return pm.get_installed_boards() if installed else pm.get_all_boards()\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 184, in get_all_boards\n    for board in self.get_registered_boards():\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py\", line 138, in wrapper\n    self.cache[key] = (time.time(), func(*args, **kwargs))\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 178, in get_registered_boards\n    return util.get_api_result(\"/boards\", cache_valid=\"7d\")\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py\", line 665, in get_api_result\n    cc.set(cache_key, result, cache_valid)\n  File \"/home/sarbjeetsingh/.platformio/penv/local/lib/python2.7/site-packages/platformio/app.py\", line 201, in set\n    os.makedirs(dirname(cache_path))\n  File \"/home/sarbjeetsingh/.platformio/penv/lib/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: '/home/sarbjeetsingh/.platformio/.cache/c5'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please remove this folder `Permission denied: '/home/sarbjeetsingh/.platformio/.cache` and restart VSCode.
