### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by DavidP92** [platformio/platformio-core#1973]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\pcc\\Documents\\PlatformIO\\Projects\\temp_humidity\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'pro16MHzatmega328'"

**Comment by ivankravets** [comment]
The board ID is valid `pro16MHzatmega328`. Please remove `HOME_DIR/.platformio/platforms/atmelavr` folder and restart VSCode.
