### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by nambuco** [platformio/platformio-core#1976]
PIO Core Call Error: "Platform /Users/paulohenriquefortesalves/.platformio/platforms/espressif8266@1.7.0\n--------\nUpdating espressif8266                   @ 1.7.0          [Detached]\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\nUpdating tool-espotapy                   @ 1.1.2          [Up-to-date]\n\nError: Detected unknown package '/Users/paulohenriquefortesalves/.platformio/packages/framework-arduinoespressif8266@1.20401.2 @ ~1.20401.1'"

**Comment by ivankravets** [comment]
Could you try to remove this folder `/Users/paulohenriquefortesalves/.platformio/packages/framework-arduinoespressif8266@1.20401.2` and start build again?

Please run `pio update` before.
