### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by bertrandAKQA** [platformio/platformio-core#1978]
Server error: {"message":"[Errno 1] Operation not permitted: '/Users/bertrand.tronsson/Documents/PlatformIO'","args":[1,"Operation not permitted"],"type":"OSError"}

**Comment by ivankravets** [comment]
> /Users/bertrand.tronsson/Documents/PlatformIO

Please check if you have permissions to this folder. Also, restarting of VSCode could help. Please reopen if you still have this issue.
