### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by legenddcr** [platformio/platformio-core#1980]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1025, in invoke\n    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 594, in make_context\n    self.parse_args(ctx, args)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 858, in parse_args\n    value, args = param.handle_parse_result(ctx, opts, args)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1362, in handle_parse_result\n    self.callback, ctx, self, value)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 56, in invoke_param_callback\n    return callback(ctx, param, value)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py\", line 34, in validate_boards\n    pm.board_config(id_)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 193, in board_config\n    for manifest in self.get_installed_boards():\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/util.py\", line 138, in wrapper\n    self.cache[key] = (time.time(), func(*args, **kwargs))\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 168, in get_installed_boards\n    p = PlatformFactory.newPlatform(manifest['__pkg_dir'])\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 250, in newPlatform\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 460, in __init__\n    self._manifest = util.load_json(manifest_path)\n  File \"~/.platformio/penv/lib/python2.7/site-packages/platformio/util.py\", line 185, in load_json\n    with open(file_path, \"r\") as f:\nIOError: [Errno 2] No such file or directory: '~/.platformio/platforms/ESP8266_RTOS_SDK/platform.json'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> .platformio/platforms/ESP8266_RTOS_SDK

where did you download this dev/platform?
