### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by 610172110** [platformio/platformio-core#1981]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\Newton\\Documents\\PlatformIO\\Projects\\181217-171128-stm32cube-hal-blink\\platformio.ini, line: 9\n'debug_tool = blackmagic\\n''","args":["File contains no section headers.\nfile: C:\\Users\\Newton\\Documents\\PlatformIO\\Projects\\181217-171128-stm32cube-hal-blink\\platformio.ini, line: 9\n'debug_tool = blackmagic\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
> Invalid platformio.ini, project configuration file: 'File contains no section headers.\nfile

Please read https://en.wikipedia.org/wiki/INI_file
