### ISSUE TITLE
Honor include/exclude when downloading a remote library

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#1983]
What kind of issue is this?

- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------

The library.json file has include/exclude files for decreasing the library size in the archive.  It would be nice if it honored those when downloading a library directly from a git repo instead of the library archive.

I like to keep pdf's and other documentation in my git repo with my libraries.  When the library is zipped up and downloaded from the archive, they're correctly ignored.  But if someone wants to download the library from git, they have to wait while git processes and downloads all of those pdf's.

Note:  The presence/absence of these things makes no difference at all to the build.  This would just be to speed up downloads.

**Comment by ivankravets** [comment]
Is it technically possible to clone Git repository and explain Git client which files to exclude? As I understand, Git clones the whole tree.

**Comment by SRGDamia1** [comment]
You can use a sparse checkout:  https://git-scm.com/docs/git-read-tree

I admit, I don't know how to set it up right, though.

**Comment by ivankravets** [comment]
This is tree information. We need something for `git clone`.

**Comment by SRGDamia1** [comment]
I don't know of anything else in git.

**Comment by ivankravets** [comment]
Sorry, I don't have an idea of how to resolve this issue in a simple form :(
