### ISSUE TITLE
Home: Could not initialize project with adafruit_feather_m4

### ISSUE THREAD

**Issue by hoss** [platformio/platformio-core#1985]
**adafruit_feather_m4** shows up as available board to select but project creation fails.

PIO Core Call Error: "The next files/directories have been created in /Users/hg/Documents/PlatformIO/Projects/weighscales\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'adafruit_feather_m4'"

**Comment by ivankravets** [comment]
Please open PlatformIO IDE > PIO Home > Platforms > Updates and apply available updates. Start initializing of a project again.

Please reopen if you still need help.
