### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by abreuw25** [platformio/platformio-core#1987]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /Users/williamabreu/Documents/PlatformIO/Projects/WorkingWithVariable&MixingColors/platformio.ini, line: 1\n'include <Arduino.h>\\n''","args":["File contains no section headers.\nfile: /Users/williamabreu/Documents/PlatformIO/Projects/WorkingWithVariable&MixingColors/platformio.ini, line: 1\n'include <Arduino.h>\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Invalid platformio.ini, project configuration file: 'File contains no section headers.\nfile: /Users/williamabreu/Documents/PlatformIO/Projects/WorkingWithVariable&MixingColors/platformio.ini, line: 1\n'include <Arduino.h>\n''","args":["File contains no section headers.\nfile: /Users/williamabreu/Documents/PlatformIO/Projects/WorkingWithVariable&MixingColors/platformio.ini, line: 1\n'include <Arduino.h>\n'"],"type":"InvalidProjectConf"

See https://en.wikipedia.org/wiki/INI_file
