### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Affenarsch110** [platformio/platformio-core#1988]
PIO Core Call Error: "Error: Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /Users/info/Documents/PlatformIO/Projects/Uhrzeit/platformio.ini\n\t[line 16]: '421\\n''"

**Comment by ivankravets** [comment]
File contains parsing errors: /Users/info/Documents/PlatformIO/Projects/Uhrzeit/platformio.ini\n\t[line 16]: '421\n
