### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by zazzazzaz** [platformio/platformio-core#1989]
PIO Core Call Error: "<Exception instance at 0x5ed1c88 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u0131' in position 58: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1959
