### ISSUE TITLE
Check docs and add support for Python 3.5+ before release

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#1991]
Subj.

**Comment by JustACatRu** [comment]
Definetly need to add some points about (experimental?) Python 3.5+ support here:
https://docs.platformio.org/en/latest/installation.html#system-requirements
And here:
https://docs.platformio.org/en/latest/faq.html#install-python-interpreter

There is a statement in docs:

> Python 2.7 is required. PlatformIO does not support Python 3.

Which took (me :) a lot of time trying to make work a Python 3+ extra_script with a PIO building system in Python 2.7. But all I was needed: to install last dev PIO with pip (of Python 3 install).

For now, maybe, put there something like:

> Python 3.5+ support is experimental. You can try it with PlatformIO Core (CLI) [development installation](https://docs.platformio.org/en/latest/installation.html#development-version).
PlatformIO IDE still require (and will use) Python 2.7 for now! You have to uninstall it and use Core (CLI) version instead.

And, maybe:

> Windows Users, please Download the latest Python 2.7.x (or Python 3.5+ experimental, if you will use Core CLI only) and install it.
