### ISSUE TITLE
Runtime Error:  Dictionary size changed during iteration --- Visual Studio Code

### ISSUE THREAD

**Issue by wisegeeksrules** [platformio/platformio-core#2003]
<s>I'm trying to install a library u8glib2 by Oliver and getting a "Runtime Error: Dictionary changed during iteration."

There was no other way of reporting the issue as I was getting a "success" message though I'm failing to install the library. see screenshot below.</s>

**Update:**
It looks like the library has installed since it is appearing under installed libraries. The issue is I'm getting the same "Runtime Error: dictionary changed size during iteration" error when building projects which include the u8g2 library.
_________________________________________________________________________________
Retrieving maximum program size .pioenvs/esp32doit-devkit-v1/firmware.elf
Checking size .pioenvs/esp32doit-devkit-v1/firmware.elf
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [          ]   4.6% (used 14932 bytes from 327680 bytes)
PROGRAM: [=         ]  10.6% (used 222216 bytes from 2097152 bytes)
================================================= [SUCCESS] Took 82.48 seconds =================================================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/object-undefined/.platformio/penv/lib/python2.7/site-packages/platformio/telemetry.py", line 375, in _finalize
    backup_reports(MPDataPusher().get_items())
  File "/home/object-undefined/.platformio/penv/lib/python2.7/site-packages/platformio/telemetry.py", line 391, in backup_reports
    for key in params:
RuntimeError: dictionary changed size during iteration
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/object-undefined/.platformio/penv/lib/python2.7/site-packages/platformio/telemetry.py", line 375, in _finalize
    backup_reports(MPDataPusher().get_items())
  File "/home/object-undefined/.platformio/penv/lib/python2.7/site-packages/platformio/telemetry.py", line 391, in backup_reports
    for key in params:
RuntimeError: dictionary changed size during iteration

Terminal will be reused by tasks, press any key to close it.

How do I solve the issue?
I'm running Solus Mate.

**Comment by wisegeeksrules** [comment]
![screenshot at 2018-12-30 15-09-39](https://user-images.githubusercontent.com/10378575/50547709-c8a55300-0c47-11e9-9a47-ce8fb92c2c3e.png)

**Comment by reloxx13** [comment]
same here

> Error in atexit._run_exitfuncs:
> 
> Traceback (most recent call last):
> 
>   File "c:\users\nils\.platformio\python27\lib\atexit.py", line 24, in _run_exitfuncs
> 
>     func(*targs, **kargs)
> 
>   File "c:\users\nils\.platformio\python27\lib\site-packages\platformio\telemetry.py", line 375, in _finalize
> 
>     backup_reports(MPDataPusher().get_items())
> 
>   File "c:\users\nils\.platformio\python27\lib\site-packages\platformio\telemetry.py", line 391, in backup_reports
> 
>     for key in params:
> 
> RuntimeError: dictionary changed size during iteration
> 
> Error in sys.exitfunc:
> 
> Traceback (most recent call last):
> 
>   File "c:\users\nils\.platformio\python27\lib\atexit.py", line 24, in _run_exitfuncs
> 
>     func(*targs, **kargs)
> 
>   File "c:\users\nils\.platformio\python27\lib\site-packages\platformio\telemetry.py", line 375, in _finalize
> 
>     backup_reports(MPDataPusher().get_items())
> 
>   File "c:\users\nils\.platformio\python27\lib\site-packages\platformio\telemetry.py", line 391, in backup_reports
> 
>     for key in params:
> 
> RuntimeError: dictionary changed size during iteration
> 



Atom
1.33.1

**Comment by ivankravets** [comment]
1. Please enable development version of PIO Core in VSCode, see https://docs.platformio.org/en/latest/ide/vscode.html#platformio-ide-usedevelopmentpiocore
2. Open VSCode Terminal and type `pio upgrade --dev`.

Does it work now?

**Comment by wisegeeksrules** [comment]
I did the first step, when I try the second step I'm getting an error :

 bash: pio: command not found

**Comment by reloxx13** [comment]
yes it works, thank you!

**Comment by wisegeeksrules** [comment]
>     1. Please enable development version of PIO Core in VSCode, see https://docs.platformio.org/en/latest/ide/vscode.html#platformio-ide-usedevelopmentpiocore
> 
>     2. Open VSCode Terminal and type `pio upgrade --dev`.
> 
> 
> Does it work now?

Yes, it's now working. Thanks!
