### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by omar75** [platformio/platformio-core#2006]
PIO Core Call Error: "Error: Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /home/omar/Documents/PlatformIO/Projects/181231-160100-nodemcuv2/platformio.ini\n\t[line 20]: 'void setup() {\\n'\n\t[line 23]: '}\\n'\n\t[line 25]: 'void loop() {\\n'\n\t[line 38]: '}\\n''"

**Comment by ivankravets** [comment]
File contains parsing errors: /home/omar/Documents/PlatformIO/Projects/181231-160100-nodemcuv2/platformio.ini

See https://en.wikipedia.org/wiki/INI_file
