### ISSUE TITLE
Library Storage: Could not extract 

### ISSUE THREAD

**Issue by Nullfati** [platformio/platformio-core#2015]
PIO Core Call Error: "Library Storage: C:\\Users\\Nullfati\\.platformio\\lib\r\nLibraryManager: Installing id=5784\r\nDownloading...\r\nUnpacking\r\nUnpacking\n\nError: Could not extract `./tools/esp-idf/version_finder.mk` to `C:\\Users\\Nullfati\\.platformio\\lib\\_tmp_installing-zhm3ck-package`. Try to disable antivirus tool or check this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Do you use antivirus tool in system?

**Comment by ivankravets** [comment]
Yes, this is a bug. I can reproduce it.

**Comment by ivankravets** [comment]
The bug has been fixed. Please 

1. Switch PIO Core in PlatformIO IDE to development version https://docs.platformio.org/en/latest/ide/vscode.html#platformio-ide-usedevelopmentpiocore
2. Open PIO IDE Terminal and type `pio upgrade --dev`. It should be 4.0.0a1.

Does it work now?
