### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by djzul** [platformio/platformio-core#2018]
PIO Core Call Error: "Library Storage: C:\\Users\\Zver'\\.platformio\\lib\r\nLibraryManager: Installing id=1747\r\nDownloading...\r\nUnpacking\r\nUnpacking\r\nESP8266MQTTMesh @ 1.0.4 has been successfully installed!\r\nInstalling dependencies\r\nLibraryManager: Installing id=305 @ ^1.1.3\r\r\nESPAsyncTCP @ 1.2.0 is already installed\r\nLooking for AsyncMqttClient library in registry\r\r\nFound: https://platformio.org/lib/show/346/AsyncMqttClient\r\nLibraryManager: Installing id=346 @ ^0.8.1\r\r\nDownloading...\r\nUnpacking\r\nUnpacking\r\nAsyncMqttClient @ 0.8.2 has been successfully installed!\r\nInstalling dependencies\r\nLibraryManager: Installing id=305 @ ^1.1.0\r\r\nESPAsyncTCP @ 1.2.0 is already installed\r\nLibraryManager: Installing id=1826 @ ^1.0.0\r\r\nAsyncTCP @ 1.0.1 is already installed\r\nLibraryManager: Installing id=1826\r\nAsyncTCP @ 1.0.1 is already installed\r\nLooking for Ticker-esp32 library in registry\r\r\nFound: https://platformio.org/lib/show/1938/Ticker-esp32\r\nLibraryManager: Installing id=1938\r\nDownloading...\r\nUnpacking\r\nUnpacking\r\nTicker-esp32 @ 1.1.0 has been successfully installed!\r\nLibraryManager: Installing AsyncMqttClient\n\nError: Please install Git client from https://git-scm.com/downloads"

**Comment by ivankravets** [comment]
Please install Git client from https://git-scm.com/downloads
