### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by Sergiolapria** [platformio/platformio-core#2020]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/boards.py\", line 29, in cli\n    return _print_boards_json(query, installed)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/boards.py\", line 81, in _print_boards_json\n    for board in _get_boards(installed):\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/boards.py\", line 76, in _get_boards\n    return pm.get_installed_boards() if installed else pm.get_all_boards()\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 185, in get_all_boards\n    boards = self.get_installed_boards()\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py\", line 142, in wrapper\n    self.cache[key] = (time.time(), func(*args, **kwargs))\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 171, in get_installed_boards\n    for manifest in self.get_installed():\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 404, in get_installed\n    manifest = self.load_manifest(pkg_dir)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 364, in load_manifest\n    src_manifest_path = self.get_src_manifest_path(pkg_dir)\n  File \"/home/sergio/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 335, in get_src_manifest_path\n    for item in os.listdir(pkg_dir):\nOSError: [Errno 13] Permission denied: '/home/sergio/.platformio/platforms/espressif32'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
It seems that you have broken permissions. Please remove `/home/sergio/.platformio` folder and restart VSCode WITHOUT SUDO!
