### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by mkihr** [platformio/platformio-core#2024]
PIO Core Call Error: "Error: Could not load broken JSON: /Users/mkihr/Documents/Arduino/libraries/I2C-Sensor-Lib_iLib/library.json"

**Comment by ivankravets** [comment]
Please remove this file `/Users/mkihr/Documents/Arduino/libraries/I2C-Sensor-Lib_iLib/library.json` and use official library https://github.com/orgua/iLib
