### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by vpomax** [platformio/platformio-core#2030]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\vpoma\\Documents\\PlatformIO\\Projects\\MAID-EM\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 16, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\init.py\", line 91, in cli\r\n    init_base_project(project_dir)\r\n  File \"c:\\users\\vpoma\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\init.py\", line 153, in init_base_project\r\n    join(project_dir, \"platformio.ini\"))\r\n  File \"C:\\Users\\vpoma\\.platformio\\python27\\Lib\\shutil.py\", line 97, in copyfile\r\n    with open(dst, 'wb') as fdst:\r\nIOError: [Errno 13] Permission denied: 'C:\\\\Users\\\\vpoma\\\\Documents\\\\PlatformIO\\\\Projects\\\\MAID-EM\\\\platformio.ini'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
>  [Errno 13] Permission denied: 'C:\\Users\\vpoma\\Documents\\PlatformIO\\Projects\\MAID-EM\\platformio.ini

Please check permissions/antivirus.
