### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by anysomewhere** [platformio/platformio-core#2032]
PIO Core Call Error: "Platform C:\\Users\\hey\\.platformio\\platforms\\espressif32
--------
Updating espressif32                     @ 1.5.0          [1.6.0]
Uninstalling espressif32 @ 1.5.0: [OK]
PlatformManager: Installing espressif32 @ 1.6.0
Downloading
Downloading
Warning! Package Mirror: The size (76725 bytes) of downloaded file 'platform-espressif32-1.6.0.tar.gz' is not equal to remote size (75277 bytes)
Looking for another mirror...

Error: Could not install 'espressif32' with version requirements '1.6.0' for your system 'windows_amd64'.

Please try this solution -> http://bit.ly/faq-package-manager"

**Comment by chr2002qw** [comment]
Same Issue here

**Comment by ivankravets** [comment]
Should be fixed. Sorry for the issue.
