### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by aschoelzhorn** [platformio/platformio-core#2034]
Server error: {"message":"Could not load broken JSON: C:\\Users\\alexa\\.platformio\\platforms\\atmelavr\\boards\\attiny24.json","args":["C:\\Users\\alexa\\.platformio\\platforms\\atmelavr\\boards\\attiny24.json"],"type":"InvalidJSONFile"}

**Comment by ivankravets** [comment]
Please remove `C:\Users\alexa\.platformio\platforms\atmelavr` folder and restart IDE.
