### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by propolino** [platformio/platformio-core#2036]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\gp\\Documents\\PlatformIO\\Projects\\ESP32_POE_1\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing esp32-poe (platform: espressif32; board: esp32-poe; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'esp32-poe'\r\n [ERROR] Took 0.98 seconds"

**Comment by ivankravets** [comment]
Please update ESP32 dev platform via PIO Home > Platforms > Updates and restart VSCode.
