### ISSUE TITLE
TypeError: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by meltdown03** [platformio/platformio-core#2037]
**Description of Issue**
Clicking "Project Examples" leads to:

API Exception: {'type': 'TypeError', 'args': ("'<' not supported between instances of 'dict' and 'dict'",), 'message': "'<' not supported between instances of 'dict' and 'dict'"}
Traceback (most recent call last):
  File "/home/neal/.platformio/packages/contrib-pysite/jsonrpc/manager.py", line 112, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "<string>", line 205, in get_project_examples
TypeError: '<' not supported between instances of 'dict' and 'dict'

This is the the error from running `pio home` from the  linux commandline

**Configuration**
Happens with Python3, platformio-core version 4.0.0a1 (from git, not built-in core) in VSCode for ArchLinux installed. Same setup as in Issue #2031

**Comment by ivankravets** [comment]
Thanks for the report!
Fixed in the latest PIO Plus Core. Please re-run `pio update`.
