### ISSUE TITLE
Home: Could not load installed platforms: HELP WANTED

### ISSUE THREAD

**Issue by davrad3** [platformio/platformio-core#2054]
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 223, in platform_list\r\n    expose_packages=False))\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\platform.py\", line 81, in _get_installed_platform_data\r\n    name=p.name,\r\n  File \"c:\\users\\david\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 485, in name\r\n    return self._manifest['name']\r\nKeyError: 'name'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Please remove `c:\users\david\.platformio\platforms` folder and restart VSCode.
