### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by djgoldcleatscom** [platformio/platformio-core#2055]
When I try to install Keyboard library of Arduino from within platformio. I get this error. 

**Wondering why I am getting this error?**

PIO Core Call Error: "Library Storage: /home/xxx/.platformio/lib\nLibraryManager: Installing id=891\n\nError: Got an unrecognized status code '503' when downloaded http://dl.platformio.org/libraries/archives/8/14855.tar.gz"

**Comment by ivankravets** [comment]
Could you open this link https://dl.platformio.org/libraries/archives/8/14855.tar.gz?filename=Keyboard_1.0.2_891? Please check your firewall/internet.

**Comment by djgoldcleatscom** [comment]
yes, I could download it manually. Thanks for helping. DJ

**Comment by ivankravets** [comment]
Does it work now from PIO Home?
