### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by WangXianbin1989** [platformio/platformio-core#2060]
PIO Core Call Error: "The next files/directories have been created in E:\\STM32 Prj\\Platform\\test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError:"

**Comment by ivankravets** [comment]
Could you provide more details on how to reproduce this issue? Could you try to use another destination folder?

**Comment by ivankravets** [comment]
Please reopen if you still need help
