### ISSUE TITLE
Library update: more than one library has been found

### ISSUE THREAD

**Issue by lucasromeiro** [platformio/platformio-core#2065]
PIO Core Call Error: "Library Storage: /Users/lucas/.platformio/lib\nUpdating ssd1306                         @ 1.7.12         [1.7.13]\nUninstalling ssd1306 @ 1.7.12: \t[OK]\nLooking for ssd1306 library in registry\nSSD1306\n=======\n#ID: 1134\nSSD1306 for DisplayCore\n\nKeywords: display, displaycore, tft, lcd, glcd, oled, graphics, font\nCompatible frameworks: Arduino\nCompatible platforms: Microchip PIC32\nAuthors: Majenko Technologies\n\nssd1306\n=======\n#ID: 1904\nVGA, SSD1306, SSD1331, SSD1351, IL9163/ST7735, PCD8544 spi/i2c OLED/LED Display driver.\n\nKeywords: display\nCompatible frameworks: Arduino\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, Teensy, TI MSP430\nAuthors: Alexey Dynda\n\nSSD1306\n=======\n#ID: 2735\nA buffered display driver for the SSD1306 OLED controller. Please note that this is a work-in-progress; only very rudimentary drawing support is provided.\n\nKeywords: oled, ssd1306\nCompatible frameworks: mbed\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\nAuthors: Jonathan Gaul\n\nFound: https://platformio.org/lib/show/1134/SSD1306\nLibraryManager: Installing id=1134 @ 1.7.13\n\nConflict: More than one library has been found by request {\"requirements\": \"1.7.13\", \"name\": \"ssd1306\"}:\nAutomatically chose the first available library (use `--interactive` option to make a choice)\nError: Could not find a version that satisfies the requirement '1.7.13' for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Will be resolved in https://github.com/platformio/platformio-core/issues/2065
