### ISSUE TITLE
Home: The system cannot find the file specified

### ISSUE THREAD

**Issue by ptracton** [platformio/platformio-core#2067]
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\ptrac\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

Taking a look at platformio for some embedded work, but it appears to fail to create projects.  Using the Atom IDE.  Home 2.0.0 Core 3.6.3.  Windows 10.  Examples do not open either.  Seems like this tool did not completely install or installed incorrectly.

**Comment by ivankravets** [comment]
Could you reproduce this issue with PlatformIO IDE for VSCode?
- https://platformio.org/platformio-ide

**Comment by ptracton** [comment]
Same issue with VSCode as with Atom.

![vs_platformio_error](https://user-images.githubusercontent.com/1445070/51954772-5cf50800-23f6-11e9-9c1a-f4d820e23a25.png)

**Comment by ivankravets** [comment]
What is your %USERHOME%  directory? This wizard allows creating a project in another location. Please uncheck "Use default location". Do you see this error again?

**Comment by ptracton** [comment]
%USERHOME% is not set.  The environment variable %USERPROFILE% has my home directory.   Is  this a windows version difference?

When I create a project and do not use the default location it at least makes a project, but there are no files in it.  I am attempting to make an STM32 project with the SPL (low level) device drivers.

**Comment by ivankravets** [comment]
Did you resolve this issue?

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core/issues/2195

The issue is linked with antivirus tools
