### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mampez** [platformio/platformio-core#2069]
Hi guys,

I got this error. Could you please help me? 

PIO Core Call Error: "The next files/directories have been created in D:\\Tes\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not find a version that satisfies the requirement '>=4.8.3' for your system 'windows_x86'"

Solved: Reinstalled everything again.

**Comment by ivankravets** [comment]
Maybe the issue with antivirus tools.
