### ISSUE TITLE
Home: Could not load installed platforms

### ISSUE THREAD

**Issue by andymwaters** [platformio/platformio-core#2073]
PIO Core Call Error: "Upon execvpe /Users/Andy/.platformio/penv/bin/platformio ['/Users/Andy/.platformio/penv/bin/platformio', 'platform', 'list', '--json-output'] in environment id 4573207360\n:Traceback (most recent call last):\n  File \"/Users/Andy/.platformio/packages/contrib-pysite/twisted/internet/process.py\", line 445, in _fork\n    environment)\n  File \"/Users/Andy/.platformio/packages/contrib-pysite/twisted/internet/process.py\", line 523, in _execChild\n    os.execvpe(executable, args, environment)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py\", line 355, in execvpe\n    _execvpe(file, args, env)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py\", line 370, in _execvpe\n    func(file, *argrest)\nOSError: [Errno 62] Too many levels of symbolic links"

**Comment by ivankravets** [comment]
Please remove `/Users/Andy/.platformio/packages/contrib-pysite` folder and restart VSCode.
