### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by rauldotta** [platformio/platformio-core#2080]
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 29, in cli\r\n    return _print_boards_json(query, installed)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 81, in _print_boards_json\r\n    for board in _get_boards(installed):\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 76, in _get_boards\r\n    return pm.get_installed_boards() if installed else pm.get_all_boards()\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 181, in get_all_boards\r\n    boards = self.get_installed_boards()\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 138, in wrapper\r\n    self.cache[key] = (time.time(), func(*args, **kwargs))\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 168, in get_installed_boards\r\n    p = PlatformFactory.newPlatform(manifest['__pkg_dir'])\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 250, in newPlatform\r\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 460, in __init__\r\n    self._manifest = util.load_json(manifest_path)\r\n  File \"c:\\users\\raul.dotta\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 185, in load_json\r\n    with open(file_path, \"r\") as f:\r\nIOError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\raul.dotta\\\\.platformio\\\\platforms\\\\arduino-esp32\\\\platform.json'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Where did you find this platform? `arduino-esp32\\platform.json`
