### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by xuongrau** [platformio/platformio-core#2082]
PIO Core Call Error: "<Exception instance at 0x53e9cc8 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\KCOM\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xf5' in position 29: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
