### ISSUE TITLE
Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by deninzane** [platformio/platformio-core#2083]
Server error: {"message":"[Errno 2] No such file or directory: '/private/var/folders/zl/lxyty1ms0m9d1y7ygv96m1wm0000gn/T/AppTranslocation/9AD5F3FE-A9B1-4AE0-A04C-F0656BFC8770 copy'","args":[2,"No such file or directory"],"type":"OSError"}

**Comment by ivankravets** [comment]
Did you resolve this issue?

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core/issues/2195#issuecomment-470495189
