### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by wdavalil** [platformio/platformio-core#2087]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/click/decorators.py\", line 26, in new_func\n    return f(get_current_context().obj, *args, **kwargs)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py\", line 138, in lib_update\n    latest = lm.outdated(pkg_dir, requirements)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 661, in outdated\n    silent=True)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py\", line 196, in get_latest_repo_version\n    cache_valid=\"1h\")['versions'], requirements)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/platformio/util.py\", line 665, in get_api_result\n    cc.set(cache_key, result, cache_valid)\n  File \"/Users/will/.platformio/penv/lib/python2.7/site-packages/platformio/app.py\", line 201, in set\n    os.makedirs(dirname(cache_path))\n  File \"/Users/will/.platformio/penv/bin/../lib/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: '/Users/will/.platformio/.cache/3b'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please remove `/Users/will/.platformio/.cache` folder and restart IDE
