### ISSUE TITLE
Error: You are not connected to the Internet

### ISSUE THREAD

**Issue by miki105** [platformio/platformio-core#2088]
PIO Core Call Error: "Error: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

**Comment by ivankravets** [comment]
Could you reproduce this issue after IDE restart?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by j0hncc** [comment]
I have this problem when going through a cntlm proxy at work.  I use this proxy routinely for git, Intellij, brew, etc, mostly using environment variables http_proxy and https_proxy (I'm using a Mac).

I *was* able to install platformio and then **platformio init -b teensy**, for example, and it worked just fine.

But if I do **platformio lib search LED**  for example, I get the error "You are not connected to the Internet

I have reproduced this several times so I'm wondering if the library search function uses some tool that is not picking up my proxy setting.

**Comment by ivankravets** [comment]
@j0hncc please create new issue and make a reference to this. I would be glad to debug it and fix.

**Comment by nullpainter** [comment]
I have the same setup. It appears that the library search functionality uses the `HTTP_PROXY` and `HTTPS_PROXY` environment variables. If these are pointing to a bogus proxy server (i.e., cntlm referencing a corporate proxy, while connecting at home), the library search won't work.

Solution is to either remove/rename these environment variables, or tweak cntlm configuration at home by setting `NoProxy *`.
