### ISSUE TITLE
ARM gcc 8

### ISSUE THREAD

**Issue by Trass3r** [platformio/platformio-core#2089]
Hi it would be nice if [arm-gcc 8](https://github.com/gnu-mcu-eclipse/arm-none-eabi-gcc/releases) could be added to https://bintray.com/platformio/dl-packages/toolchain-gccarmnoneeabi for custom platforms.

**Comment by ivankravets** [comment]
Done! Please re-run `$ pio update`

**Comment by Trass3r** [comment]
Thanks it seems to work!
