### ISSUE TITLE
Home: Could not update platform

### ISSUE THREAD

**Issue by AsyaSyarif** [platformio/platformio-core#2095]
PIO Core Call Error: "Platform C:\\Users\\asyar\\.platformio\\platforms\\espressif8266\r\n--------\r\nUpdating espressif8266                   @ 1.8.0          [Up-to-date]\r\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\r\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\n\nError: Detected unknown package 'C:\\Users\\asyar\\.platformio\\packages\\tool-espotapy @ ~1.1.0'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2072
