### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by edisamuelbm** [platformio/platformio-core#2096]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\edisa\\Documents\\PlatformIO\\Projects\\Delta\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing fm-devkit (platform: espressif32; board: fm-devkit; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'fm-devkit'\r\n [ERROR] Took 1.54 seconds"

**Comment by ivankravets** [comment]
See valid board manfiests https://github.com/platformio/platform-espressif8266/tree/develop/boards
