### ISSUE TITLE
UnicodeDecodeError in platformio\util.py line 420

### ISSUE THREAD

**Issue by JustACatRu** [platformio/platformio-core#2100]
- [ ] **PlatformIO Core**.
**Error:** UnicodeDecodeError: Non-ASCII characters found in build environment
**Real error:** UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 0: invalid start byte

### Configuration
- Windows 10 x64 (ru)
- PlatformIO (Core CLI through "[pip install -U https...](https://docs.platformio.org/en/latest/installation.html#development-version)"), version 4.0.0a3
- Python 3.7.2
- Eclipse as IDE (not matter, it happens with all IDEs)

### Description of problem
When using "pio init" with "--ide" parameter (no matter what ide) with platform = espressif8266.
![2019-02-01_001338](https://user-images.githubusercontent.com/12075875/52295185-343bb800-298c-11e9-9e4d-0ff3383c7995.png)
And there is no Non-ASCII characters in my paths as I can see:
![2019-02-01_001404](https://user-images.githubusercontent.com/12075875/52295193-3867d580-298c-11e9-8361-1210f953547c.png)

#### Details
If I select some avr board like "pio init --board pro16MHzatmega328" then "pio init --ide eclipse" works without errors:
![2019-02-02_013425](https://user-images.githubusercontent.com/12075875/52295287-7c5ada80-298c-11e9-9533-038b012a1df6.png)
If I select esp board like "pio init --board esp07" then "pio init --ide eclipse" produce error:
![2019-02-02_013619](https://user-images.githubusercontent.com/12075875/52295290-8086f800-298c-11e9-9239-e8234e472d2d.png)
If there is 2 envs in a project and avr goes first in "platformio.ini" then all is workig fine too:
![2019-02-02_014015](https://user-images.githubusercontent.com/12075875/52295319-92689b00-298c-11e9-8010-37c21dfb9a72.png)
But if I put "env:esp07" first, "pio init --ide eclipse" stops working again.

**Comment by JustACatRu** [comment]
I've modified code a little bit and found traceback of error ([this catch](https://github.com/platformio/platformio-core/blob/e23ca2c10992f10b1906ad616248aa2ef999db23/platformio/builder/main.py#L213) hides traceback):
![2019-02-02_023330](https://user-images.githubusercontent.com/12075875/52295520-17ec4b00-298d-11e9-8593-e30cb9aeea25.png)
Here: https://github.com/platformio/platformio-core/blob/e23ca2c10992f10b1906ad616248aa2ef999db23/platformio/util.py#L420
For me it starts working, if I change that line to **any** of this variants:
```
result[k] = str(result[k])
result[k] = str(result[k], "windows-1251")
result[k] = result[k].decode("windows-1251")
```
![2019-02-02_024315](https://user-images.githubusercontent.com/12075875/52295524-1c186880-298d-11e9-96b4-383c550c2f7b.png)
I do not know if it's a right solution. And which variant is the best and correct. And why it is working with "windows-1251" encoding. My Python knowledge is way too low for this :)
But hope all this will help solve the problem quicker.

PS: I've transferred this issue and details from there: https://github.com/platformio/platformio-atom-ide/issues/768#issuecomment-459515920 - because it is not Atom IDE specific.

**Comment by JustACatRu** [comment]
I've found out, that this variant:
```
result[k] = str(result[k])
```
coused [this bug](https://github.com/platformio/platformio-core/issues/2101#issuecomment-460873992). Because [here](https://docs.python.org/3.7/library/stdtypes.html#str):
> Passing a bytes object to str() without the encoding or errors arguments falls under the first case of returning the informal string representation (see also the -b command-line option to Python).
For example:
```
str(b'Zoot!')
"b'Zoot!'"
```
So, the encoding must be specified explicitly:
```
result[k] = result[k].decode("windows-1251")
# Or:
result[k] = str(result[k], "windows-1251")
```
But it should be "windows-1251", not "utf-8". I still do not get why.

**Comment by JustACatRu** [comment]
When I saw this line: https://github.com/platformio/platformio-core/blob/35f96a534aee4ade4f5327945a6544e2f20d9391/platformio/util.py#L816
I tried this variant:
```
result[k] = result[k].decode("latin-1")
```
And it works too. So decode("latin-1") or decode("windows-1251") both working for me. 
But not decode("utf-8") or decode() which is equivalent.

**Comment by ivankravets** [comment]
Could you reproduce this issue with the latest `pio upgrade --dev`?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by JustACatRu** [comment]
> Could you reproduce this issue with the latest `pio upgrade --dev`?

Yep. Same issue:
![2019-04-27_133423](https://user-images.githubusercontent.com/12075875/56848409-5a208b00-68f1-11e9-9121-470ecd1fc42d.png)

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`. Thanks!

**Comment by JustACatRu** [comment]
> Please re-test

Just tested on version 4.0.0a18 and it is working without issues now! Great and thanks.

**Comment by ivankravets** [comment]
Thanks for the report! We are so close for the amazing release :) 

- https://github.com/platformio/platformio-core/blob/develop/HISTORY.rst
