### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by DarioX7** [platformio/platformio-core#2103]
Server error: {"message":"Missed J-Link Device ID for malyanM200v2","args":["Missed J-Link Device ID for malyanM200v2"],"type":"AssertionError"}

**Comment by ivankravets** [comment]
Is it a custom board? You need to declare J-Link device. See example https://github.com/platformio/platform-atmelsam/blob/develop/boards/adafruit_circuitplayground_m0.json#L24
