### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by gparvind** [platformio/platformio-core#2108]
Server error: {"message":"Could not load broken JSON: /home/gpa/.platformio/platforms/ststm32@src-15e0e87f41a00aa2f9602f71367ac29c/platform.json","args":["/<user-home>/.platformio/platforms/ststm32@src-15e0e87f41a00aa2f9602f71367ac29c/platform.json"],"type":"InvalidJSONFile"}

**Comment by ivankravets** [comment]
Please remove `/home/gpa/.platformio/platforms/` folder and build project again.
