### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by AndreyGrand** [platformio/platformio-core#2112]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\Gerankin-EIS\\Documents\\PlatformIO\\Projects\\STM32-habr\\platformio.ini\n\t[line 21]: 'include''","args":["File contains parsing errors: C:\\Users\\Gerankin-EIS\\Documents\\PlatformIO\\Projects\\STM32-habr\\platformio.ini\n\t[line 21]: 'include'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2074
