### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Psychedelic-Engineering** [platformio/platformio-core#2114]
PIO Core Call Error: "The next files/directories have been created in /Users/makra/Desktop/MBED/MBed-Test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing redbear_blenano2 (platform: nordicnrf52; board: redbear_blenano2; framework: mbed)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/nordicnrf52/redbear_blenano2.html\nPLATFORM: Nordic nRF52 > RedBearLab BLE Nano 2\nHARDWARE: NRF52832 64MHz 64KB RAM (512KB Flash)\nDEBUG: CURRENT(cmsis-dap) ON-BOARD(cmsis-dap) EXTERNAL(blackmagic, jlink, stlink)\nmbed build API internal error\nwrite() takes exactly 2 arguments (3 given)\n========================== [ERROR] Took 8.64 seconds =========================="

**Comment by ivankravets** [comment]
Should be fixed in the latest release. Please open PIO Home and Platforms > Updates.
