### ISSUE TITLE
Platformio website is down?

### ISSUE THREAD

**Issue by MaliMrav** [platformio/platformio-core#2118]
Is the PlatformIO site down?
I cannot connect to the site https://platformio.org

**Comment by honzakucera** [comment]
See #2117

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2117

**Comment by diversit** [comment]
Website is down again. Or at least not reachable from NL.
docs.platformio.org does seem to work.
Why are you having so much trouble keeping a simple website up?

**Comment by ivankravets** [comment]
Everything is online since 2014. 
Could you provide `traceroute PlatformIo.org`?

**Comment by diversit** [comment]
Sorry, already resolved.
Apparently it's hosted from Ukraine and I had everything from Ukraine blocked in my firewall.
