### ISSUE TITLE
Error: No such command "init"

### ISSUE THREAD

**Issue by davidwood3** [platformio/platformio-core#2133]
PIO Core Call Error: "Usage: platformio [OPTIONS] COMMAND [ARGS]...\r\r\n\r\r\nError: No such command \"init\""

I believe that maybe PIO is trying to use Python to run the scripting commands.  I use Python 3.7 with PyCharm and Visual Studio Code on this machine.  Is it failing to use the right version of Python (trying to use Python 3.7 when it should use Python 2.x)?

**Comment by ivankravets** [comment]
Do you use VSCode?

**Comment by davidwood3** [comment]
Yes I use VSCode.  Installed Python 2.7 with paths set.  This fixed it

Thanks - Awesome product!

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!
