### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by moracabanas** [platformio/platformio-core#2138]
PIO Core Call Error: "Library Storage: /Users/alberto/Documents/MarlinMKII/.piolibdeps\nUpdating TMCStepper                      @ cefefbe        [20465ae]\ngit version 2.19.2\nUpdating cefefbe..20465ae\n\nFrom https://github.com/teemuatlut/TMCStepper\n   cefefbe..20465ae  master     -> origin/master\n * [new tag]         v0.2.3     -> v0.2.3\n * [new tag]         v0.3.0     -> v0.3.0\n * [new tag]         v0.3.1     -> v0.3.1\nerror: Your local changes to the following files would be overwritten by merge:\n\tREADME.md\n\tlibrary.json\n\tlibrary.properties\n\tsrc/TMCStepper.h\n\tsrc/source/DRV_CONF.cpp\n\tsrc/source/SHORT_CONF.cpp\n\tsrc/source/TMC2130Stepper.cpp\n\tsrc/source/TMC2208_bitfields.h\n\tsrc/source/TMC2660Stepper.cpp\n\tsrc/source/TMC5130Stepper.cpp\n\tsrc/source/TMC5160Stepper.cpp\n\tsrc/source/TMCStepper.cpp\nPlease commit your changes or stash them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
> Your local changes to the following files would be overwritten by

Please decide what to do with modified files or remove `.piolibdeps` folder from a project.
