### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by KhaledElprince** [platformio/platformio-core#2139]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /Users/Khaled_El-Prince/Documents/PlatformIO/Projects/espressif-mqtt-publiah/platformio.ini\n\t[line 18]: 'ArduinoJson@5.13.1 \\n''","args":["File contains parsing errors: /Users/Khaled_El-Prince/Documents/PlatformIO/Projects/espressif-mqtt-publiah/platformio.ini\n\t[line 18]: 'ArduinoJson@5.13.1 \\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2074
