### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by tranquangvu0651** [platformio/platformio-core#2140]
Server error: {"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\Vu.Tran\\\\.platformio\\\\platforms\\\\Arduino_STM32\\\\platform.json'","args":[2,"No such file or directory"],"type":"IOError"}

**Comment by ivankravets** [comment]
Where did you find `platforms\\Arduino_STM32` this dev/platform?

please use https://github.com/platformio/platform-ststm32
