### ISSUE TITLE
build_dir = %TEMP%/pio-build/$PROJECT_HASH doesn't work as expected.

### ISSUE THREAD

**Issue by richard-scott** [platformio/platformio-core#2145]
Following instructions [here](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#build-dir), on a Windows 10 setup when editing a projects platformio.ini and adding this:

```
[platformio]
build_dir = %TEMP%/pio-build/$PROJECT_HASH
```

You get a new folder in the root of your project called %TEMP%

However, if you add this:
```
[platformio]
build_dir = C:\Windows\Temp\PlatformIO\$PROJECT_HASH
```

It works as expected and builds in that folder.
What's the correct solution to this?

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/projectconf/dynamic_variables.html

`${sysenv.TEMP}`
