### ISSUE TITLE
platformio lib install with no arguments does not install project dependencies

### ISSUE THREAD

**Issue by mje-nz** [platformio/platformio-core#2147]
### Configuration

**Operating system**:
macOS 10.12.6

**PlatformIO Version** (`platformio --version`):
3.6.4
### Description of problem
[The documentation](https://docs.platformio.org/en/latest/userguide/lib/cmd_install.html#usage) says that running `platformio lib install` from a project directory will install the libraries listed in the project's `lib_deps`. This behaviour is not implemented (see [here](https://github.com/platformio/platformio-core/blob/6575ddab2654e7f12cd02e18748afe34ca728f27/platformio/commands/lib.py#L105-L107)).

#### Steps to Reproduce
1. From the main directory of a project with external dependencies defined in its default target, run `platformio lib install`.

### Actual Results
The library storage directory is printed and nothing is installed.

### Expected Results
Libraries listed in `lib_deps` are installed.

**Comment by ivankravets** [comment]
Libraries will be installed automatically when you try to build project with `pio run`.

Nevertheless, I mark this issue as a feature request.

**Comment by rileyrg** [comment]
I've just spent ages finding this. Yes, it would be nice if it was honoured. The --init needs to add the -I for the project to the .clang_complete too.

**Comment by ivankravets** [comment]
Please re-test with the latest development version of PIO Core => http://docs.platformio.org/en/latest/installation.html#development-version

or , `pio upgrade --dev` from CLI.

**Comment by mje-nz** [comment]
Works for me, thanks!
