### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by gerliettore** [platformio/platformio-core#2150]
PIO Core Call Error: "Error: Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\work\\WbEcoFirebase\\WbEcoFirebase\\platformio.ini\r\n\t[line 16]: '551\\n''"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2074
