### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by lauritis232** [platformio/platformio-core#2151]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\laura\\Documents\\PlatformIO\\Projects\\2000\\platformio.ini\n\t[line 17]: 'lip_deps \\n''","args":["File contains parsing errors: C:\\Users\\laura\\Documents\\PlatformIO\\Projects\\2000\\platformio.ini\n\t[line 17]: 'lip_deps \\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2074
