### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by homonecloco** [platformio/platformio-core#2154]
PIO Core Call Error: "Library Storage: /Users/ramirezr/.platformio/lib\nUpdating Light sensor TSL2561 (fork of SparkFun) @ 1.0.0          [1.2.0]\nUninstalling Light sensor TSL2561 (fork of SparkFun) @ 1.0.0: \t[OK]\nLooking for Light sensor TSL2561 (fork of SparkFun) library in registry\n\nError: Library `{'requirements': u'1.2.0', 'name': 'Light sensor TSL2561 (fork of SparkFun)'}` has not been found in PlatformIO Registry.\nYou can ignore this message, if `{'requirements': u'1.2.0', 'name': 'Light sensor TSL2561 (fork of SparkFun)'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
We don't have this library in our registry https://platformio.org/lib
