### ISSUE TITLE
Printing package versions before a build

### ISSUE THREAD

**Issue by dontsovcmc** [platformio/platformio-core#2155]
Please, add printting  framework version when compile. The Dependency Graph has libraries versions, but user don't know what framework version used... It's really danger for production.

**Comment by ivankravets** [comment]
Thanks! I renamed this issue. I think it would be great to print all packages and their versions which will be used for building/uploading.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.
