### ISSUE TITLE
Home: Could not load boards list (critical bugs)

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-core#2159]
PIO Core Call Error: "Error: Unknown development platform 'C:\\.platformio\\platforms\\ststm32'"

I had many problems with framworks updating: The frameworks updating didn't stop after more than 30min. So I decided to reboot VSCode and unistall them and reinstall them, but when uninstalling one of them I get this error :

![image](https://user-images.githubusercontent.com/15887222/53279289-82341800-370f-11e9-91f1-9dc9d1b3510b.png)

**Comment by Navis-Raven** [comment]
Adding to that I have many critical problems... 
IntelliSense rebuild doesn't stop
The server crashes
And impossible to build (I think as a consequence of IntelliSense crash)

![image](https://user-images.githubusercontent.com/15887222/53279480-0dfa7400-3711-11e9-9453-333ea4ee64d6.png)

And all that makes my PC lagging

**Comment by Navis-Raven** [comment]
I've tried to open a ESP32/arduino project, -> same issues

![image](https://user-images.githubusercontent.com/15887222/53279644-78f87a80-3712-11e9-9db3-1a66be139d5b.png)

After waiting 30 min the intellisense rebuild finally stops but I wasn't able to install ST STM32 framwork

Look at the error message
![image](https://user-images.githubusercontent.com/15887222/53279874-7008a880-3714-11e9-8a56-8c7f5deece54.png)

**Comment by Navis-Raven** [comment]
I've tried through another way but this is what it gave

`
Processing disco_l475vg_iot01a (platform: ststm32; board: disco_l475vg_iot01a; framework: mbed)
---------------------------------------------------------------------------------------------------------------------------------------------------------------
PackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi\\7.2.1\\cc1.exe' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi\7.2.1\cc1.exe`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi\\7.2.1\\cc1plus.exe' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi\7.2.1\cc1plus.exe`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi\\7.2.1' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi\7.2.1`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi`
Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager
Le processus du terminal s'est achevé avec le code de sortie 1

Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.

`

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/help-me-please-connection-to-server-got-closed/6551/7?u=ivankravets

**Comment by Navis-Raven** [comment]
@ivankravets  sorry but the problem is still here

`
Processing disco_l475vg_iot01a (platform: ststm32; board: disco_l475vg_iot01a; framework: mbed)
---------------------------------------------------------------------------------------------------------------------------------------------------------------
PackageManager: Installing toolchain-gccarmnoneeabi @ >=1.60301.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi\\7.2.1\\cc1.exe' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi\7.2.1\cc1.exe`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi\\7.2.1\\cc1plus.exe' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi\7.2.1\cc1plus.exe`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi\\7.2.1' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi\7.2.1`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc\\arm-none-eabi' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc\arm-none-eabi`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib\\gcc' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib\gcc`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi\\lib' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi\lib`
[Error 5] AccÞs refus: 'C:\\.platformio\\packages\\toolchain-gccarmnoneeabi' 
Please manually remove the file `C:\.platformio\packages\toolchain-gccarmnoneeabi`
Error: Could not install 'toolchain-gccarmnoneeabi' with version requirements '>=1.60301.0' for your system 'windows_x86'.

Please try this solution -> http://bit.ly/faq-package-manager
Le processus du terminal s'est achevé avec le code de sortie 1

Le terminal sera réutilisé par les tâches, appuyez sur une touche pour le fermer.
`

**Comment by ivankravets** [comment]
Could you provide a TeamViewer session to debug this issue? Please ping me at me@ikravets.com

**Comment by Navis-Raven** [comment]
I've just installed TeamViewer, I'll contact you on your mail tomorrow. (please ignore my previous mail)
