### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by kmohammad1996** [platformio/platformio-core#2160]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\Mohammad\\Documents\\PlatformIO\\Projects\\190223-091053-megacore128\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'megacore128'"

**Comment by ivankravets** [comment]
Please update platforms and packages via PIO Home > Platforms > Updates. Try again.
