### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by andrewklmn** [platformio/platformio-core#2161]
PIO Core Call Error: "The next files/directories have been created in /home/user/Documents/PlatformIO/Projects/test-mbed\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'bluepill_f103c8_128k'"

**Comment by ivankravets** [comment]
This board has not been released with the latest version. You need to switch to upstream > https://docs.platformio.org/en/latest/platforms/ststm32.html#stable-and-upstream-versions

**Comment by andrewklmn** [comment]
thank you... дякую... )))

**Comment by ivankravets** [comment]
Ха ) Будь ласка! 😊
