### ISSUE TITLE
Add user-definable monitor options to platformio.ini

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platformio-core#2165]
Users may want to give extra options to the execution of the `miniterm.py` script, e.g. `--raw` to enable seeing color codes for the shell (see e.g. [here](https://community.platformio.org/t/some-bizare-characters-prints-on-serial-monitor-with-esp-idf-hello-world-example/5025/11)). This is currently not possible.

Therefore, I suggest to create a new option `monitor_options` in which users can write additional configuration options for `miniterm.py`.

**Comment by kazooiebombchu** [comment]
I'd also like this idea. I really want to be able to enable local echo by default when opening monitor if my projects needs it.

**Comment by kazooiebombchu** [comment]
Do you accept PRs for this?

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.

**Comment by ivankravets** [comment]
Docs http://docs.platformio.org/en/latest/projectconf/section_env_monitor.html

**Comment by del13r** [comment]
For newbies, add this to env: section of platformio.ini of your project
monitor_raw = yes
