### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by nkimlevn** [platformio/platformio-core#2166]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\nkiml\\Documents\\PlatformIO\\Projects\\N5110\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing bluepill_f103c8_128k (platform: ststm32; board: bluepill_f103c8_128k; framework: mbed)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'bluepill_f103c8_128k'\r\n [ERROR] Took 0.98 seconds"

**Comment by ivankravets** [comment]
You need upstream version https://docs.platformio.org/en/latest/platforms/ststm32.html#stable-and-upstream-versions
