### ISSUE TITLE
Home: Could not list directory/Users/USERNAME/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by engali94** [platformio/platformio-core#2169]
Invalid params: {"type":"TypeError","args":["'cmp' is an invalid keyword argument for this function"],"message":"'cmp' is an invalid keyword argument for this function"}

**Comment by ivankravets** [comment]
Could you reproduce this issue after IDE restart?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2327
