### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by verminsky** [platformio/platformio-core#2171]
PIO Core Call Error: "PlatformManager: Installing riscv\nDownloading\nDownloading\nUnpacking\nUnpacking\nriscv @ 0.3.0 has been successfully installed!\nPackageManager: Installing toolchain-riscv @ ~1.70200.0\n\nError: Detected unknown package 'toolchain-riscv'"

**Comment by verminsky** [comment]
Using Ubuntu 18.04.2 with VSCode   : Installing toolchain-riscv @ ~1.70200.0\n\nError: Detected unknown package 'toolchain-riscv'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-riscv/issues/3#issuecomment-469353138
