### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by petervandepol** [platformio/platformio-core#2188]
PIO Core Call Error: "The next files/directories have been created in /home/peter/Documents/PlatformIO/Projects/Lora sender\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'lora32u4II'"

**Comment by ivankravets** [comment]
Please update platforms via PlatformIO IDE > PIO Home > Platforms > Updates
