### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by 22demais** [platformio/platformio-core#2191]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\C4rl1n\\Documents\\PlatformIO\\Projects\\TESTE ESP32\\platformio.ini\n\t[line  7]: 'void setup(){\\n'\n\t[line  9]: '}\\n'\n\t[line 11]: 'void loop(){\\n'\n\t[line 17]: '}''","args":["File contains parsing errors: C:\\Users\\C4rl1n\\Documents\\PlatformIO\\Projects\\TESTE ESP32\\platformio.ini\n\t[line  7]: 'void setup(){\\n'\n\t[line  9]: '}\\n'\n\t[line 11]: 'void loop(){\\n'\n\t[line 17]: '}'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains parsing errors: C:\Users\C4rl1n\Documents\PlatformIO\Projects\TESTE ESP32\platformio.ini

See https://en.wikipedia.org/wiki/INI_file
