### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by MatCat** [platformio/platformio-core#2193]
PIO Core Call Error: "Platform C:\\Users\\MatCat\\.platformio\\platforms\\espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d\r\n--------\r\nUpdating espressif32                     @ 6a9dbef        [Up-to-date]\r\nUpdating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]\r\nUpdating tool-openocd-esp32              @ 1.1000.20190212[Up-to-date]\r\nUpdating tool-mkspiffs                   @ 2.230.0        [Up-to-date]\r\nUpdating framework-arduinoespressif32    @ 86fdb5b        [7df50a9]\r\ngit version 2.17.1.windows.2\nUpdating 86fdb5b..7df50a9\n\nFetching submodule libraries/AzureIoT\nFetching submodule libraries/BLE\nerror: Your local changes to the following files would be overwritten by merge:\n\ttools/sdk/include/config/sdkconfig.h\n\ttools/sdk/sdkconfig\nPlease commit your changes or stash them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
> Please commit your changes or stash them before you merge

It seems that you have changes in framework-arduinoespressif32 package. Please uninstall Espressif 32 dev/platform and install again using PIO IDE > PIO Home > Platforms.
