### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by brentforman** [platformio/platformio-core#2194]
PIO Core Call Error: "Usage: platformio lib [OPTIONS] COMMAND [ARGS]...\r\r\n\r\r\nError: Invalid value for \"-d\" / \"--storage-dir\": Directory \"C:\\Users\\bf\\Documents\\PlatformIO\\Projects\\SFFMTMeter3.0\" does not exist."

**Comment by ivankravets** [comment]
Please reload PIO Home in IDE. It should be fixed.
