### ISSUE TITLE
Home: Could not import project in Win10

### ISSUE THREAD

**Issue by dastarke** [platformio/platformio-core#2195]
Hello, 
i installed ther actual versions of vs-code and platformio on Win10. There was no error during installation but i am not able to import any example. The following error message is shown. 

_**Server error: {"message":"[Error 2] Das System kann die angegebene Datei nicht finden: u'C:\\\\Users\\\\Daniel\\\\Documents\\\\PlatformIO'","args":[2,"Das System kann die angegebene Datei nicht finden"],"type":"WindowsError"}**_

I tried a lot but nothing helped. There is no "PlatformIO" in Documents but in C:\users\Daniel.
Hope someone has an idea. 

Daniel

**Comment by ivankravets** [comment]
Do you have this folder `C:\\Users\\Daniel\\Documents`?

**Comment by dastarke** [comment]
Hello Ivan,

thanks for your reply. Yes it ist he standard documents folder „C:\Users\Daniel\Documents“
or are the double backslash relevant?

Daniel

Von: Ivan Kravets <notifications@github.com>
Gesendet: Donnerstag, 7. März 2019 12:03
An: platformio/platformio-core <platformio-core@noreply.github.com>
Cc: dastarke <d.starke@hotmail.de>; Author <author@noreply.github.com>
Betreff: Re: [platformio/platformio-core] Home: Could not import project in Win10 (#2195)


Do you have this folder C:\\Users\\Daniel\\Documents?

**Comment by dastarke** [comment]
![image](https://user-images.githubusercontent.com/34912232/53953201-02288d80-40d3-11e9-9317-d89a865fc997.png)
![image](https://user-images.githubusercontent.com/34912232/53953287-3c922a80-40d3-11e9-9ebe-db9c2e77ad54.png)

**Comment by dastarke** [comment]
sorry touched the wrong button.

**Comment by ivankravets** [comment]
Could you reproduce this issue after VSCode restart?

**Comment by dastarke** [comment]
Yea there is no difference after restarting VSCode.

**Comment by ivankravets** [comment]
It seems that you have a permission issue. Could you create `PlatformIO` folder in `C:\Users\Daniel\Documents`? Restart VSCode?

**Comment by dastarke** [comment]
I created the folder and restarted VSCode but trying to Import an example Ends in the same issue:

**_Server error: {"message":"[Error 2] Das System kann die angegebene Datei nicht finden: u'C:\\\\Users\\\\Daniel\\\\Documents\\\\PlatformIO\\\\Projects\\\\190307-124128-arduino-blink'","args":[2,"Das System kann die angegebene Datei nicht finden"],"type":"WindowsError"}_**

**Comment by ivankravets** [comment]
Do you have antivirus tools in a system?

**Comment by dastarke** [comment]
yes Defender.

**Comment by ivankravets** [comment]
Could you try to disable it for a while?

**Comment by dastarke** [comment]
thanks with disabling everything it works. I will try to find out what exactly is causing the Problem and let you know.

sorry i thought this test was one fo my first...

**Comment by ivankravets** [comment]
It seems that Defender does not like when PlatformIO creates folder in background and removes it.
