### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by dvirgol10** [platformio/platformio-core#2196]
PIO Core Call Error: "PlatformManager: Installing riscv @ 0.2.1\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nriscv @ 0.2.1 has been successfully installed!\r\nPackageManager: Installing toolchain-riscv @ ~1.70200.0\n\nError: Detected unknown package 'toolchain-riscv'"

**Comment by ivankravets** [comment]
Please update dev/platform via PlatformIO IDE > PIO Home > Platforms > Updates

**Comment by dvirgol10** [comment]
There is nothing there, what can I do?

**Comment by ivankravets** [comment]
Fixed. Please try again. Sorry.
