### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by zafrirron** [platformio/platformio-core#2198]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: D:\\Google-Drive\\Technology\\ESP32\\Dev\\Arduino\\espurna-hw655\\code\\platformio.ini\n\t[line  7]: '<<<<<<< HEAD\\n'\n\t[line 10]: '=======\\n'\n\t[line 15]: '>>>>>>> dev\\n''","args":["File contains parsing errors: D:\\Google-Drive\\Technology\\ESP32\\Dev\\Arduino\\espurna-hw655\\code\\platformio.ini\n\t[line  7]: '<<<<<<< HEAD\\n'\n\t[line 10]: '=======\\n'\n\t[line 15]: '>>>>>>> dev\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains parsing errors: D:\Google-Drive\Technology\ESP32\Dev\Arduino\espurna-hw655\code\platformio.ini\

https://en.wikipedia.org/wiki/INI_file
