### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by masruri3** [platformio/platformio-core#2199]
PIO Core Call Error: "The next files/directories have been created in /home/masruri3/Documents/PlatformIO/Projects/STM32F1_MBED_T1-Blinky\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing bluepill_f103c8_128k (platform: ststm32; board: bluepill_f103c8_128k; framework: mbed)\n--------------------------------------------------------------------------------\nPackageManager: Installing framework-mbed @ ~5.51104.190214\nDownloading\nDownloading\nUnpacking\nUnpacking\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/bluepill_f103c8_128k.html\nPLATFORM: ST STM32 > BluePill F103C8 (128k)\nHARDWARE: STM32F103C8T6 72MHz 20KB RAM (128KB Flash)\nDEBUG: CURRENT(stlink) EXTERNAL(blackmagic, jlink, stlink)\nmbed build API internal error\nwrite() takes exactly 2 arguments (3 given)\n========================= [ERROR] Took 1273.41 seconds ========================="

**Comment by ivankravets** [comment]
Please open PIO Home > Platforms > Updates
