### ISSUE TITLE
Bug with unit tests

### ISSUE THREAD

**Issue by Nullfati** [platformio/platformio-core#2200]
### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.6.5

### Description of problem
If you run `platformio test --without-uploading`, get an error: `Error: Please specify 'test_port' for environment or use global '--test-port' option.`.  If I understood correctly, flag `--without-uploading` must remove step with uploading and any interactions with a port.

### Actual Results
Get error: `Error: Please specify 'test_port' for environment or use global '--test-port' option.`

### Expected Results
Build tests and run it

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
debug_tool = stlink
board_build.mcu = stm32f103c8t6
build_unflags = -Os -std=gnu++11
build_flags = -O3 -std=gnu++14
lib_ignore =
    StandardCplusplus

[env:uno]
; platform = atmelavr@1.11.0 // For lib "StandartCplusCplus"
platform = atmelavr@1.11.0
board = uno
framework = arduino
monitor_speed = 57600
build_unflags = -Os -std=gnu++11
build_flags = -O3 -std=gnu++14
lib_deps =
    StandardCplusplus
test_ignore = test_native

[env:megaatmega2560]
; platform = atmelavr@1.11.0 // For lib "StandartCplusCplus"
platform = atmelavr@1.11.0
board = megaatmega2560
framework = arduino
monitor_speed = 57600
build_unflags = -Os -std=gnu++11
build_flags = -O3 -std=gnu++14
lib_deps =
    StandardCplusplus
test_ignore = test_native
```

**Comment by ivankravets** [comment]
Could you provide a test log? On the which stage do you see this error? "Testing... (3/3)"? If yes, we use `test_port` to read test results from a target device.

**Comment by ivankravets** [comment]
Please reopen if you still need help
