### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ANH2018** [platformio/platformio-core#2203]
I Creat new project stm32f103 bluepill Use Visual studio code
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\Administrator\\AppData\\Roaming\\SPB_Data\\Documents\\PlatformIO\\Projects\\Ahbb\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not install 'framework-mbed' with version requirements '~5.51104.190214' for your system 'windows_x86'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

who can help me? thank you!

**Comment by ivankravets** [comment]
Please check antivirus tools
