### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Schmithtrigger** [platformio/platformio-core#2206]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\schmith\\Documents\\PlatformIO\\Projects\\Caudal2polegadas\\platformio.ini, line: 11\n' ;[env:nucleo_f103rb]\\n''","args":["File contains no section headers.\nfile: C:\\Users\\schmith\\Documents\\PlatformIO\\Projects\\Caudal2polegadas\\platformio.ini, line: 11\n' ;[env:nucleo_f103rb]\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\nfile: C:\Users\schmith\Documents\PlatformIO\Projects\Caudal2polegadas\platformio.ini

**Comment by Schmithtrigger** [comment]
it work fine when i delete the paste .pioenvs and build, afeter delete de paste .vscode  restart the program vscode. After 5 minutes i have again the paste  .vscode and compile fine and no error.

Thanks.

**Comment by ivankravets** [comment]
You have broken `platformio.ini` file in project => https://en.wikipedia.org/wiki/INI_file
