### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Nakin72** [platformio/platformio-core#2207]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\repac\\Documents\\PlatformIO\\Projects\\VRIMU\\platformio.ini, line: 12\n'\"[env:sparkfun_promicro16]\\n''","args":["File contains no section headers.\nfile: C:\\Users\\repac\\Documents\\PlatformIO\\Projects\\VRIMU\\platformio.ini, line: 12\n'\"[env:sparkfun_promicro16]\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
'File contains no section headers.\nfile: C:\Users\repac\Documents\PlatformIO\Projects\VRIMU\platformio.ini, lin
