### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Nakin72** [platformio/platformio-core#2208]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\repac\\Documents\\PlatformIO\\Projects\\VRIMU\\platformio.ini\n\t[line 15]: '     platform = espressif32\\n'\n\t[line 16]: '     #\\xd0\\x9f\\xd0\\xbb\\xd0\\xb0\\xd1\\x82\\xd0\\xb0 \\n'\n\t[line 17]: '     board = esp32doit-devkit-v1\\n'\n\t[line 18]: '     #\\xd0\\xa1\\xd1\\x80\\xd0\\xb5\\xd0\\xb4\\xd0\\xb0\\n'\n\t[line 19]: '     framework = arduino\\n''","args":["File contains parsing errors: C:\\Users\\repac\\Documents\\PlatformIO\\Projects\\VRIMU\\platformio.ini\n\t[line 15]: '     platform = espressif32\\n'\n\t[line 16]: '     #\\xd0\\x9f\\xd0\\xbb\\xd0\\xb0\\xd1\\x82\\xd0\\xb0 \\n'\n\t[line 17]: '     board = esp32doit-devkit-v1\\n'\n\t[line 18]: '     #\\xd0\\xa1\\xd1\\x80\\xd0\\xb5\\xd0\\xb4\\xd0\\xb0\\n'\n\t[line 19]: '     framework = arduino\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate https://github.com/platformio/platformio-core/issues/2207
