### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by pistoletov1974** [platformio/platformio-core#2209]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\Artem\\Documents\\PlatformIO\\Projects\\ARDUINO_HID\\platformio.ini, line: 1\n'cmd\\n''","args":["File contains no section headers.\nfile: C:\\Users\\Artem\\Documents\\PlatformIO\\Projects\\ARDUINO_HID\\platformio.ini, line: 1\n'cmd\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\nfile: C:\Users\Artem\Documents\PlatformIO\Projects\ARDUINO_HID\platformio.ini, line: 1\n'cmd\n''","args":["File contains no section headers.
