### ISSUE TITLE
Home: Could not load platform data this when i upgrade 5.2.0 to 5.3.0

### ISSUE THREAD

**Issue by Schmithtrigger** [platformio/platformio-core#2216]
PIO Core Call Error: "Platform C:\\Users\\schmith\\.platformio\\platforms\\ststm32\r\n--------\r\nUpdating ststm32                         @ 5.2.0          [5.3.0]\r\r\nUninstalling ststm32 @ 5.2.0: \t[OK]\r\nPlatformManager: Installing ststm32 @ 5.3.0\r\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\n\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\platforms\\\\ststm32\\\\examples\\\\mbed-filesystem' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\platforms\\ststm32\\examples\\mbed-filesystem`\r\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\platforms\\\\ststm32\\\\examples\\\\mbed-rtos' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\platforms\\ststm32\\examples\\mbed-rtos`\r\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\platforms\\\\ststm32\\\\examples\\\\stm32cube-hal-blink' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\platforms\\ststm32\\examples\\stm32cube-hal-blink`\r\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\platforms\\\\ststm32\\\\examples' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\platforms\\ststm32\\examples`\r\n[Error 5] Acesso negado: 'C:\\\\

**Comment by ivankravets** [comment]
Please remove this folder `C:\\Users\\schmith\\.platformio` and start building again. It seems that antivirus tools blocks it.
