### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by racingpassion** [platformio/platformio-core#2218]
PIO Core Call Error: "The next files/directories have been created in /Users/andynunes/Documents/PlatformIO/Projects/190313-175145-esp8266-nonos-sdk-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Could not install 'framework-esp8266-nonos-sdk' with version requirements '>=2.1.0' for your system 'darwin_x86_64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Please check your internet connection and firewall. The package exists in registry => https://raw.githubusercontent.com/sanderv32/framework-esp8266-nonos-sdk/master/manifest.json
