### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Pawel-Was** [platformio/platformio-core#2219]
PIO Core Call Error: "<Exception instance at 0x4fd6e08 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u0142' in position 30: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
