### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by altf4arnold** [platformio/platformio-core#2220]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/click/decorators.py\", line 26, in new_func\n    return f(get_current_context().obj, *args, **kwargs)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py\", line 269, in lib_list\n    items = lm.get_installed()\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 404, in get_installed\n    manifest = self.load_manifest(pkg_dir)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py\", line 63, in load_manifest\n    manifest = BasePkgManager.load_manifest(self, pkg_dir)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 364, in load_manifest\n    src_manifest_path = self.get_src_manifest_path(pkg_dir)\n  File \"/home/arnold/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 335, in get_src_manifest_path\n    for item in os.listdir(pkg_dir):\nOSError: [Errno 13] Permission denied: '/home/arnold/Documents/PlatformIO/Projects/Test/.piolibdeps/PubSubClient_ID89'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by adri94** [comment]
Same here. Any clue ?
