### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by AntumArk** [platformio/platformio-core#2222]
PIO Core Call Error: "Platform C:\\Users\\Caustic_Zinc\\.platformio\\platforms\\ststm32\r\n--------\r\nUpdating ststm32                         @ 2c39824        [a1c78e0]\r\ngit version 2.18.0.windows.1\n\nfatal: not a git repository: '.git'\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

Error occured when trying to update st stm32 platform.
![image](https://user-images.githubusercontent.com/23199497/54423031-66250480-4718-11e9-887b-c980ffd272cf.png)

**Comment by ivankravets** [comment]
How did you install these dev/platforms?

**Comment by AntumArk** [comment]
Through platforms window.

**Comment by ivankravets** [comment]
Could you uninstall these dev/platforms and install directly from the registry using PIO Home > Platforms > Install.

**Comment by AntumArk** [comment]
Installed successfully

**Comment by ivankravets** [comment]
Thanks for the confirmation!
