### ISSUE TITLE
Python3 PIO Remote issue

### ISSUE THREAD

**Issue by glucee** [platformio/platformio-core#2223]
- [x] **PlatformIO Core**.
The pio remote device monitor doesnot work under Python3 Pio4 version. It crushed with a error message with 'str,bytes-like' error.

### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): 4.0.0a5

### Description of problem
The pio remote device monitor doesnot work under Python3 Pio4 version. It crushed with a error message with 'builtins.TypeError: a bytes-like object is required, not 'str'' error.

#### Steps to Reproduce

1. Install Pio using Python3
2. pio account login 
3. pio remote device list

### Actual Results
2019-03-15 12:33:47 [info] Remote command received: b'device.list'
Peer will receive following PB traceback:
Unhandled Error
Traceback (most recent call last):
.....
builtins.TypeError: a bytes-like object is required, not 'str'
### Expected Results
serial print

____
I tried on Python2.7 to install PIO4.0.05a, it works. So I guess it is some problem in supporting Pyhton3 ?

**Comment by ivankravets** [comment]
Should be fixed in the latest version. Please do `pio update` and re-test. Thanks!
