### ISSUE TITLE
I HAVE ILLEGAL END TO END BACKROUND PROGRAMMING RAN DIDNT LOOK THROUGH THIS BUT IF YOU HAVE TIME ENJOY

### ISSUE THREAD

**Issue by alphadesign427** [platformio/platformio-core#2226]
PIO Core Call Error: "[]\n\nFatal Python error: PyImport_GetModuleDict: no module dictionary!\r\n\r\nThis application has requested the Runtime to terminate it in an unusual way.\nPlease contact the application's support team for more information."

**Comment by ivankravets** [comment]
What is your OS? Did you run `$ pio update` in PlatformIO IDE Terminal?

**Comment by ivankravets** [comment]
Please reopen if you still need help
