### ISSUE TITLE
PLEASE HELP ME OUT !this is an illegal recycle bin that keeps f***ing my over by owning my computer with a gpo i cant getg rid of PLEASE HELP!Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by alphadesign427** [platformio/platformio-core#2230]
Server error: {"message":"[(u'E:\\\\$Recycle.Bin\\\\S-1-5-21-1902746814-3590437262-582043826-1001\\\\desktop.ini', u'E:\\\\$Recycle.Bin\\\\S-1-5-21-1902746814-3590437262-582043826-1001 copy\\\\desktop.ini', \"[Errno 13] Permission denied: u'E:\\\\\\\\$Recycle.Bin\\\\\\\\S-1-5-21-1902746814-3590437262-582043826-1001 copy\\\\\\\\desktop.ini'\")]","args":[[["E:\\$Recycle.Bin\\S-1-5-21-1902746814-3590437262-582043826-1001\\desktop.ini","E:\\$Recycle.Bin\\S-1-5-21-1902746814-3590437262-582043826-1001 copy\\desktop.ini","[Errno 13] Permission denied: u'E:\\\\$Recycle.Bin\\\\S-1-5-21-1902746814-3590437262-582043826-1001 copy\\\\desktop.ini'"]]],"type":"Error"}

**Comment by ivankravets** [comment]
Could you provide more details?

**Comment by ivankravets** [comment]
Please reopen if you still need help
