### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by bobcroft** [platformio/platformio-core#2231]
PIO Core Call Error: "Library Storage: C:\\PIO_libraries\r\nUpdating Adafruit Unified Sensor         @ 1.0.2          [1.0.3]\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 26, in new_func\r\n    return f(get_current_context().obj, *args, **kwargs)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 151, in lib_update\r\n    lm.update(library, only_check=only_check)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 835, in update\r\n    self.uninstall(pkg_dir, after_update=True)\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 752, in uninstall\r\n    with LockFile(self.package_dir):\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\lockfile.py\", line 102, in __enter__\r\n    self.acquire()\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\lockfile.py\", line 86, in acquire\r\n    return self._lock()\r\n  File \"c:\\users\\bob\\.platformio\\penv\\lib\\site-packages\\platformio\\lockfile.py\", line 61, in _lock\r\n    self._fp = open(self._lock_path, \"w\")\r\nIOError: [Errno 13] Permission denied: 'C:\\\\PIO_libraries.lock'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
PLease check permissions for C:\PIO_libraries
