### ISSUE TITLE
Error: [API] Could not connect to PlatformIO API Service. Please try later.

### ISSUE THREAD

**Issue by Thomas-QM** [platformio/platformio-core#2234]
PIO Core Call Error: "Error: [API] Could not connect to PlatformIO API Service. Please try later."

website down again? lol

**Comment by ivankravets** [comment]
It should work. We have strong uptime on the server side. Maybe, network issue? Does it work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by Thomas-QM** [comment]
sorry, found out that it was just me, probably an issue with my network

thanks for closing it for me
