### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by DoraLC** [platformio/platformio-core#2236]
PIO Core Call Error: "<Exception instance at 0x444a170 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\lcmo\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 4355-4359: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
