### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by matjakov** [platformio/platformio-core#2237]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /home/mk/Projects/PlatformIO/181213-174539-arduino-hid-usb-mouse/platformio.ini, line: 2\n'Home\\n''","args":["File contains no section headers.\nfile: /home/mk/Projects/PlatformIO/181213-174539-arduino-hid-usb-mouse/platformio.ini, line: 2\n'Home\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2198
