### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mathzol** [platformio/platformio-core#2246]
PIO Core Call Error: "The next files/directories have been created in /Users/mathezoltan/Projects/Arduino/32u4IITest00_2\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'lora32u4II'"

**Comment by ivankravets** [comment]
Please update dev/platforms via PIO Home > Platforms > Updates and try again.
