### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by testerxxx** [platformio/platformio-core#2247]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\Viper\\Documents\\PlatformIO\\Projects\\190323-144601-esp8266-nonos-sdk-blink\\platformio.ini, line: 1\n' ; PlatformIO Project Configuration File\\n''","args":["File contains no section headers.\nfile: C:\\Users\\Viper\\Documents\\PlatformIO\\Projects\\190323-144601-esp8266-nonos-sdk-blink\\platformio.ini, line: 1\n' ; PlatformIO Project Configuration File\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\nfile: C:\Users\Viper\Documents\PlatformIO\Projects\190323-144601-esp8266-nonos-sdk-blink\platformio.ini
