### ISSUE TITLE
"Missed J-Link Device ID for malyanM200v2

### ISSUE THREAD

**Issue by salfter** [platformio/platformio-core#2249]
This popup occurred when I opened the PlatformIO homepage in VSCode (on Gentoo Linux, if it matters):

Server error: {"message":"Missed J-Link Device ID for malyanM200v2","args":["Missed J-Link Device ID for malyanM200v2"],"type":"AssertionError"}

**Comment by ivankravets** [comment]
what is malyanM200v2? Where did you find it?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1990

**Comment by salfter** [comment]
Whatever was causing the problem seems to have been fixed, as it's no longer occurring.
