### ISSUE TITLE
Home: Libraries: Search

### ISSUE THREAD

**Issue by kdh961113** [platformio/platformio-core#2250]
PIO Core Call Error: "Error: [API] Invalid response: <html>\r\n<head>\r\n \r\n\t<script>\r\n\t location.href = \"http://first.wifi.olleh.com/webauth/redirection.php?ip=222.120.247.12&mac=685d437148dc&url=http://api.platformio.org&ssid=Public%20WiFi%20Free%20&ap_mac=00300dcf2e7f&apmodel=MW-6900AP\";\r\n\t</script>\r\n</head>\r\n</html>"

**Comment by ivankravets** [comment]
Do you use a proxy? Please check the internet connection.
