### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by irymor** [platformio/platformio-core#2252]
PIO Core Call Error: "<Exception instance at 0x5eaff48 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 63-66: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
