### ISSUE TITLE
Platformio install failure errno 1

### ISSUE THREAD

**Issue by Hektor6766** [platformio/platformio-core#2270]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration Standard full install, successfully installed atom runner, paths set in both local user and system.

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): 2.9.1

### Description of problem from the debug log:
2096 warn enoent ENOENT: no such file or directory, open 'C:\Users\richa\AppData\Local\Temp\apm-install-dir-119231-28128-1anrcg.j52ig\package.json'
2097 verbose enoent This is related to npm not being able to find a file.
2098 warn apm-install-dir-119231-28128-1anrcg.j52ig No description
2099 warn apm-install-dir-119231-28128-1anrcg.j52ig No repository field.
2100 warn apm-install-dir-119231-28128-1anrcg.j52ig No README data
2101 warn apm-install-dir-119231-28128-1anrcg.j52ig No license field.
2102 verbose stack Error: node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
2102 verbose stack Exit status 1
2102 verbose stack     at EventEmitter.<anonymous> (C:\Users\richa\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
2102 verbose stack     at emitTwo (events.js:126:13)
2102 verbose stack     at EventEmitter.emit (events.js:214:7)
2102 verbose stack     at ChildProcess.<anonymous> (C:\Users\richa\AppData\Local\atom\app-1.35.1\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2102 verbose stack     at emitTwo (events.js:126:13)
2102 verbose stack     at ChildProcess.emit (events.js:214:7)
2102 verbose stack     at maybeClose (internal/child_process.js:925:16)
2102 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2103 verbose pkgid node-pty-prebuilt@0.7.6
2104 verbose cwd C:\Users\richa\AppData\Local\Temp\apm-install-dir-119231-28128-1anrcg.j52ig
2105 verbose Windows_NT 10.0.17134
2106 verbose argv "C:\\Users\\richa\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\richa\\AppData\\Local\\atom\\app-1.35.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\richa\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\richa\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/platformio-ide-terminal/versions/2.9.1/tarball" "--runtime=electron" "--target=2.0.18" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style" "--msvs_version=2015"
2107 verbose node v8.9.3
2108 verbose npm  v6.2.0
2109 error code ELIFECYCLE
2110 error errno 1
2111 error node-pty-prebuilt@0.7.6 install: `prebuild-install || node scripts/install.js`
2111 error Exit status 1
2112 error Failed at the node-pty-prebuilt@0.7.6 install script.
2112 error This is probably not a problem with npm. There is likely additional logging output above.
2113 verbose exit [ 1, true ]

#### Steps to Reproduce

1. 
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
Please use [PlatformIO IDE for VSCode](https://platformio.org/platformio-ide).
