### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by JovanS** [platformio/platformio-core#2280]
PIO Core Call Error: "The next files/directories have been created in D:\\Programming\\MCU_ZEZANJE\\Stm_Blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing bluepill_f103c6 (platform: ststm32; board: bluepill_f103c6; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'bluepill_f103c6'\r\n [ERROR] Took 21.46 seconds"

**Comment by ivankravets** [comment]
Please update existing dev/platforms via PIO IDE > PIO Home > Platforms > Updates and try again.
