### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by inforaudio** [platformio/platformio-core#2282]
PIO Core Call Error: "The next files/directories have been created in F:\\Proyectos PLATFORM\\Primera Prueba\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing esp12e (platform: espressif8266; board: esp12e; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp12e.html\r\nPLATFORM: Espressif 8266 > Espressif ESP8266 ESP-12E\r\nHARDWARE: ESP8266 80MHz 80KB RAM (4MB Flash)\r\nValueError: 'call_user_start' is not in list:\r\nFile \"C:\\users\\pablo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 173:\r\nenv.SConscript(\"$BUILD_SCRIPT\")\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\r\nreturn _SConscript(self.fs, *files, **subst_kw)\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\r\nexec _file_ in call_stack[-1].globals\r\nFile \"C:\\users\\pablo\\.platformio\\platforms\\espressif8266\\builder\\main.py\", line 316:\r\ntarget_elf = env.BuildProgram()\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\nreturn self.method(*nargs, **kwargs)\r\nFile \"C:\\users\\pablo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 107:\r\nenv.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\nreturn self.method(*nargs, **kwargs)\r\nFile \"C:\\users\\pablo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 319:\r\nSConscript(env.GetFrameworkScript(f), exports=\"env\")\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 604:\r\nreturn method(*args, **kw)\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\r\nreturn _SConscript(self.fs, *files, **subst_kw)\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\r\nexec _file_ in call_stack[-1].globals\r\nFile \"C:\\users\\pablo\\.platformio\\platforms\\espressif8266\\builder\\frameworks\\arduino.py\", line 33:\r\n\"framework-arduinoespressif8266\"), \"tools\", \"platformio-build.py\"))\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 604:\r\nreturn method(*args, **kw)\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\r\nreturn _SConscript(self.fs, *files, **subst_kw)\r\nFile \"C:\\Users\\Pablo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\r\nexec _file_ in call_stack[-1].globals\r\nFile \"C:\\users\\pablo\\.platformio\\packages\\framework-arduinoespressif8266\\tools\\platformio-build.py\", line 135:\r\nindex = env['LINKFLAGS'].index(\"call_user_start\")\r\nFile \"C:\\Users\\Pablo\\.platformio\\python27\\Lib\\UserList.py\", line 81:\r\ndef index(self, item, *args): return self.data.index(item, *args)\r\n [ERROR] Took 1.44 seconds"

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal and type `pio update`. Restart VSCode.
