### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by girs1982** [platformio/platformio-core#2283]
PIO Core Call Error: "Library Storage: C:\\Users\\Girs\\Documents\\PlatformIO\\Projects\\Converter_HZ_Stm32\\.piolibdeps\r\nUpdating ssd1306                         @ 1.7.17         [1.7.18]\r\r\nUninstalling ssd1306 @ 1.7.17: \t[OK]\r\nLooking for ssd1306 library in registry\r\nSSD1306\r\r\n=======\r\n#ID: 1134\r\nSSD1306 for DisplayCore\r\r\n\r\r\nKeywords: display, displaycore, tft, lcd, glcd, oled, graphics, font\r\r\nCompatible frameworks: Arduino\r\r\nCompatible platforms: Microchip PIC32\r\r\nAuthors: Majenko Technologies\r\r\n\r\r\nssd1306\r\r\n=======\r\n#ID: 1904\r\nVGA, SSD1306, SSD1331, SSD1351, IL9163/ST7735, PCD8544 spi/i2c OLED/LED Display driver.\r\r\n\r\r\nKeywords: display\r\r\nCompatible frameworks: Arduino\r\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, ST STM8, Teensy, TI MSP430\r\r\nAuthors: Alexey Dynda\r\r\n\r\r\nSSD1306\r\r\n=======\r\n#ID: 2735\r\nA buffered display driver for the SSD1306 OLED controller. Please note that this is a work-in-progress; only very rudimentary drawing support is provided.\r\r\n\r\r\nKeywords: oled, ssd1306\r\r\nCompatible frameworks: mbed\r\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\r\nAuthors: Jonathan Gaul\r\r\n\r\r\nFound: https://platformio.org/lib/show/1134/SSD1306\r\nLibraryManager: Installing id=1134 @ 1.7.18\n\nConflict: More than one library has been found by request {\"requirements\": \"1.7.18\", \"name\": \"ssd1306\"}:\r\nAutomatically chose the first available library (use `--interactive` option to make a choice)\r\nError: Could not find a version that satisfies the requirement '1.7.18' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Please remove `C:\Users\Girs\Documents\PlatformIO\Projects\Converter_HZ_Stm32\.piolibdeps` folder and build project again.
