### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by orcim** [platformio/platformio-core#2284]
PIO Core Call Error: "Platform /home/orcim/.platformio/platforms/ststm32\n--------\nUpdating ststm32                         @ e765934        [8e5232d]\ngit version 2.7.4\n\nfatal: Not a git repository: /home/orcim/.platformio/platforms/_tmp_installing-md1Duk-package/.git/modules/builder/frameworks/libopencm3\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please remove `/home/orcim/.platformio/platforms/ststm32` folder and start build again.
