### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by fedyfausto** [platformio/platformio-core#2286]
PIO Core Call Error: "Library Storage: D:\\Progetti\\CaemraIoT\\Esp32 camera\\.piolibdeps\r\nLibraryManager: Installing esp32-camera\r\ngit version 2.16.1.windows.4\n\nCloning into 'D:\\Progetti\\CaemraIoT\\Esp32 camera\\.piolibdeps\\_tmp_installing-cav7et-package'...\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 26, in new_func\r\n    return f(get_current_context().obj, *args, **kwargs)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 103, in lib_install\r\n    library, silent=silent, interactive=interactive, force=force)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 352, in install\r\n    force=force)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 721, in install\r\n    name, url, requirements, track=True)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 527, in _install_from_url\r\n    return self._install_from_tmp_dir(_tmp_dir, requirements)\r\n  File \"c:\\users\\fedyf\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 606, in _install_from_tmp_dir\r\n    shutil.move(tmp_dir, pkg_dir)\r\n  File \"C:\\Python27\\Lib\\shutil.py\", line 314, in move\r\n    rmtree(src)\r\n  File \"C:\\Python27\\Lib\\shutil.py\", line 261, in rmtree\r\n    rmtree(fullname, ignore_errors, onerror)\r\n  File \"C:\\Python27\\Lib\\shutil.py\", line 261, in rmtree\r\n    rmtree(fullname, ignore_errors, onerror)\r\n  File \"C:\\Python27\\Lib\\shutil.py\", line 261, in rmtree\r\n    rmtree(fullname, ignore_errors, onerror)\r\n  File \"C:\\Python27\\Lib\\shutil.py\", line 266, in rmtree\r\n    onerror(os.remove, fullname, sys.exc_info())\r\n  File \"C:\\Python27\\Lib\\shutil.py\", line 264, in rmtree\r\n    os.remove(fullname)\r\nWindowsError: [Error 5] Accesso negato: 'D:\\\\Progetti\\\\CaemraIoT\\\\Esp32 camera\\\\.piolibdeps\\\\_tmp_installing-cav7et-package\\\\.git\\\\objects\\\\10\\\\a58d5b3a99886eab73f9542407ca82f81cb789'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
> [Error 5] Accesso negato

It seems that your antivirus tools block PLatformIO
