### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by seshancs** [platformio/platformio-core#2289]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\Seshan.C.S\\Documents\\PlatformIO\\Projects\\Micro Measure\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

**Comment by ivankravets** [comment]
Error: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains.

Please check your internet conenction and restart VSCode.
