### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by AidanMcCarthy** [platformio/platformio-core#2290]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\ajm112\\Documents\\PlatformIO\\Projects\\iButton CRC\\platformio.ini\n\t[line 19]: 'void setup() \\n'\n\t[line 20]: '{\\n'\n\t[line 23]: '}\\n'\n\t[line 25]: 'void loop() \\n'\n\t[line 26]: '{\\n'\n\t[line 81]: '}''","args":["File contains parsing errors: C:\\Users\\ajm112\\Documents\\PlatformIO\\Projects\\iButton CRC\\platformio.ini\n\t[line 19]: 'void setup() \\n'\n\t[line 20]: '{\\n'\n\t[line 23]: '}\\n'\n\t[line 25]: 'void loop() \\n'\n\t[line 26]: '{\\n'\n\t[line 81]: '}'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains parsing errors: C:\Users\ajm112\Documents\PlatformIO\Projects\iButton CRC\platformio.ini\n\
