### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by lfnoleto** [platformio/platformio-core#2294]
PIO Core Call Error: "<Exception instance at 0x7ffb710778c0 with str error:\n Traceback (most recent call last):\n  File \"/home/lfnoleto/.platformio/packages/contrib-pysite/twisted/python/reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe3' in position 480: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
