### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by RachitThukral** [platformio/platformio-core#2295]
PIO Core Call Error: "The next files/directories have been created in C:\\SPB_Data\\Documents\\PlatformIO\\Projects\\test_blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing atmelavr\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\natmelavr @ 1.12.5 has been successfully installed!\r\nPackageManager: Installing toolchain-atmelavr @ ~1.50400.0\r\r\nDownloading\r\nDownloading\r\nWarning! Package Mirror: (\"Connection broken: error(10053, 'An established connection was aborted by the software in your host machine')\", error(10053, 'An established connection was aborted by the software in your host machine'))\r\nLooking for another mirror...\n\nError: Please read http://bit.ly/package-manager-ioerror\r\nError: Could not install 'toolchain-atmelavr' with version requirements '~1.50400.0' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
> Connection broken: error(10053, 'An established connection was aborted by the software in your host machine')

please check your internet connection.
