### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by amin-amani** [platformio/platformio-core#2296]
PIO Core Call Error: "Error: [API] Invalid response: \n<html>\n<title>...</title>\n<body>\n<form name=\"redirect\" action=\"https://internet1.ut.ac.ir/login\" method=\"get\">\n<input type=\"hidden\" name=\"username\" value=\"\">\n<input type=\"hidden\" name=\"link-login\" value=\"https://internet.ut.ac.ir/login\">\n<input type=\"hidden\" name=\"link-orig\" value=\"http://api.platformio.org/lib/stats\">\n<input type=\"hidden\" name=\"error\" value=\"\">\n<input type=\"hidden\" name=\"link-logout\" value=\"http://internet.ut.ac.ir/logout\">\n</form>\n<script language=\"JavaScript\">\n\tdocument.redirect.submit();\n</script>\n</body>\n</html>"

**Comment by ivankravets** [comment]
Please check your internet connection
