### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by seasonic98** [platformio/platformio-core#2299]
PIO Core Call Error: "The next files/directories have been created in E:\\WangHaipeng\\VS_Code_Test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'black_f407ze'"

**Comment by ivankravets** [comment]
Please open PIO Home > Platforms > Updates and apply all updates. Restart VSCode
