### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by perferom123** [platformio/platformio-core#2300]
Server error: {"message":"[Error 2] : u'C:\\\\Users\\\\HP\\\\Documents\\\\PlatformIO'","args":[2,""],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Could you try again? Do you have this folder `C:\\Users\\HP\\Documents\\PlatformIO`?

**Comment by ivankravets** [comment]
Please reopen if you still need help
