### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by maxi53** [platformio/platformio-core#2303]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\Maxi\\Documents\\PlatformIO\\Projects\\piloto\\platformio.ini, line: 12\n'upload_port = 8000\\n''","args":["File contains no section headers.\nfile: C:\\Users\\Maxi\\Documents\\PlatformIO\\Projects\\piloto\\platformio.ini, line: 12\n'upload_port = 8000\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Dupicate of https://github.com/platformio/platformio-core/issues/2260
