### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by Gilbert84** [platformio/platformio-core#2304]
PIO Core Call Error: "Error: The directory `C:\\Users\\gilbert\\.platformio` or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually `C:\\Users\\gilbert\\.platformio` directory and PlatformIO will create new from the current user."

**Comment by ivankravets** [comment]
Error: The directory C:\\Users\\gilbert\\.platformio or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\r\nPlease check the permissions and owner of that directory.\r\nOtherwise, please remove manually C:\\Users\\gilbert\\.platformio directory and PlatformIO will create new from the current user.
