### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Mysticblur** [platformio/platformio-core#2306]
PIO Core Call Error: "Library Storage: C:\\Users\\James\\Documents\\PlatformIO\\Projects\\190412-233728-hello-world\\.piolibdeps\r\nLooking for autonetkit library in registry\n\nError: Library `{'requirements': None, 'name': 'autonetkit'}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'requirements': None, 'name': 'autonetkit'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
Unknown library https://platformio.org/lib/search?query=autonetkit
