### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by fabianpedd** [platformio/platformio-core#2310]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /home/fabian/Documents/PlatformIO/Projects/190414-165250-libopencm3-blink/platformio.ini, line: 11\n'platform = ststm32\\n''","args":["File contains no section headers.\nfile: /home/fabian/Documents/PlatformIO/Projects/190414-165250-libopencm3-blink/platformio.ini, line: 11\n'platform = ststm32\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Dupicate of https://github.com/platformio/platformio-core/issues/2260
