### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by IZ76** [platformio/platformio-core#2314]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /home/ivan/Documents/PlatformIO/Projects/i_clock_2019_v1/platformio.ini\n\t[line 20]: 'eagle.flash.512k64.ld 512K (64K SPIFFS)''","args":["File contains parsing errors: /home/ivan/Documents/PlatformIO/Projects/i_clock_2019_v1/platformio.ini\n\t[line 20]: 'eagle.flash.512k64.ld 512K (64K SPIFFS)'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
> ile contains parsing errors: /home/ivan/Documents/PlatformIO/Projects/i_clock_2019_v1/platformio.ini

Please check INI file.
