### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by SocketNet** [platformio/platformio-core#2317]
PIO Core Call Error: "Library Storage: /Users/tanxw/.platformio/lib\nLibraryManager: Installing id=5725\n\nError: Please read http://bit.ly/package-manager-ioerror\nError: Traceback (most recent call last):\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/click/decorators.py\", line 26, in new_func\n    return f(get_current_context().obj, *args, **kwargs)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py\", line 103, in lib_install\n    library, silent=silent, interactive=interactive, force=force)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py\", line 352, in install\n    force=force)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 723, in install\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/managers/lib.py\", line 213, in _install_from_piorepo\n    if app.get_setting(\"enable_ssl\") else dl_data['url'], requirements)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 508, in _install_from_url\n    dlpath = self.download(url, tmp_dir, sha1)\n  File \"/Users/tanxw/.platformio/penv/lib/python2.7/site-packages/platformio/managers/package.py\", line 199, in download\n    raise e\nConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> \n raise e\nConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer')

Please check your internet connection.
