### ISSUE TITLE
LDF doesn't find all dependencies

### ISSUE THREAD

**Issue by timoxd7** [platformio/platformio-core#2320]
### Configuration

**Operating system**: Windows 10 Pro 64 bit

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.6.6

### Description of problem

If i try to compile my project with some libraries, the LDF doesn't them.

#### Steps to Reproduce

[TestLib.zip](https://github.com/platformio/platformio-core/files/3081603/TestLib.zip) Compile with one of the pre-configured environments.

### Actual Results

Compiler Error: Include-file not found.

```
src\test/x.h:1:25: fatal error: TestLibrary.h: No such file or directory
```

### Expected Results

Correct compilation including Libraries and Libraries in Libraries.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:ArduinoTest]
platform = atmelavr
board = nanoatmega328new
framework = arduino
build_flags =
    -D USE_ARDUINO

[env:MbedTest]
platform = ststm32
board = nucleo_f446re
framework = mbed
debug_tool = stlink
debug_init_break =
build_flags =
    -std=gnu++11
    -D USE_MBED
build_unflags =
    -std=gnu++98
```

**Source file to reproduce issue:**
```cpp
[TestLib.zip](https://github.com/platformio/platformio-core/files/3081603/TestLib.zip)
```

### Additional info

I have made pseudocode of my actual code including just the part which fails. Thats why the code looks like nothing. Because i use mbed and Arduino, i also included both in the config. The strange thing is, in my actual project, mbed compiles completely fine but Arduino not (with the exact same config), however in the pseudo-code, both do not work...

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/projectconf/section_env_build.html#src-filter

PlatformIO excludes `test` folder by default. You can override this via `src_filter = +<*>`.
