### ISSUE TITLE
[Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by czecht** [platformio/platformio-core#2321]
# Solution

Please check your antivirus tools in the operating system. They block PlatformIO from creating a new project. Try to disable it for a while.

------------

Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\ARDUINO\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

This is the error when I tried to create a new project.

Windows 10, i7 Intel, 16GB RAM

**Comment by ivankravets** [comment]
It seems that antivirus tools block PlatformIO.

**Comment by czecht** [comment]
I'm running Microsoft's Antivirus, I never seen it block programs!
Are you sure that it is my antivirus?
Thanks.
Tony

**Comment by ivankravets** [comment]
Do you have this folder `C:\\Users\\ARDUINO\\Documents\\PlatformIO`?

**Comment by czecht** [comment]
No, it did not create that directory!
Here is where my PlatformIO is - using search command:
search-ms:displayname=Search%20Results%20in%20Documents&crumb=location:C%3A%5CUsers%5CARDUINO%5CDocuments\PlatformIO

**Comment by czecht** [comment]
Also, the PC is not using DOUBLE SLASH but a SINGLE SLASH.
Thanks!

**Comment by ivankravets** [comment]
It seems that PlatformIO can't create this folder. Maybe permission issue or your antivirus tools block it.

**Comment by czecht** [comment]
OK, lets say that you are right.
Why don't I have problems with installing other programs?
Why is it that just your program has this problem?
Thanks.
Tony

**Comment by ivankravets** [comment]
VSCode runs PlatformIO Core as subprocess which can lead to an issue with antivirus tools. Could you try to create new project and select another location? Untick "Default location".

**Comment by czecht** [comment]
OK, I'll try and let you know if I have any problems.
Thanks!

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by LeMasoud** [comment]
In my case; my system was missing Python so i installed it and voila!

**Comment by blebee** [comment]
--------------
I  Make  "New Project" then I found this Error.
"Could not initialize project
PIO Core Call Error: "[WinError 2] The system cannot find the file specified"
---------------------------------
Ryzen5 RAM 8 G  in my laptop don't have anti virus and malware
and My location Project  C:\Users\NITRO 5\Documents\PlatformIO\Projects
Help me please.

**Comment by PlatformIO-SoeN** [comment]
I use PlatformIO without problems until the update to PlatformIO IDE 2.3.2
Now I have the same problems ...[WinError 2]....
I Try to:
1. Uninstall PlatformIO from VsCode, uninstall VsCode, uninstall Python
Restart my PC, and start new installation depend on "https://platformio.org/"
again the same problems ...[WinError 2]....

2. Uninstall PlatformIO from VsCode, uninstall VsCode, uninstall Python
Restart my PC, deactivate my Kaspersky-Anti-Virus and start new installation depend on "https://platformio.org/"
again the same problems ...[WinError 2]....

3.
I tried a number of suggested solutions to this problem and also tried older versions of VsCode and PlatformIO IDE
again the same problems ...[WinError 2]....

I have no idea how I should get on there.
I do not understand that this problem is not easy to recreate by the developers of platformIO!

I've really liked the PlatformIO IDE so far

**Comment by TR7Mike** [comment]
Just installed PlatforIO and it's now showing as Core 5.2.0b1 / Home 3.3.4 and tried to add a library to my existing project.

Error shows:
Libraries: Installed - PIO Core Call Error: "[WinError 2] The system cannot find the file specified"

Can't see anything of reference in the log files at all. Library installed tab just has spinning waiting icons. 

Path to project is "E:\Documents\Arduino\Projects\MyProjectName"

**Comment by Yukaira** [comment]
Hiya, Im getting this same error even after completely disabling windows defender

ive tried reinstalling platformIO multiple times, and multiple versions

Everything related to creating a new project throws this error, and stalls

Any assistance would be appreciated, Thanks

**Comment by Juoper** [comment]
I got the same problem and i have the folder what can i do

**Comment by PlatformIO-SoeN** [comment]
Hi,
in my case the solution was double backslash in the environment variables


Am Mi., 24. Nov. 2021 um 12:19 Uhr schrieb Julian Thanner <
***@***.***>:

**Comment by paloj** [comment]
> Hiya, Im getting this same error even after completely disabling windows defender
> 
> ive tried reinstalling platformIO multiple times, and multiple versions
> 
> Everything related to creating a new project throws this error, and stalls
> 
> Any assistance would be appreciated, Thanks

Same here!

**Comment by Yukaira** [comment]
> > Hiya, Im getting this same error even after completely disabling windows defender
> > ive tried reinstalling platformIO multiple times, and multiple versions
> > Everything related to creating a new project throws this error, and stalls
> > Any assistance would be appreciated, Thanks
> 
> Same here!

My issue was special characters in my windows file name. I had to make a new windows user with only alphanumerics in the name and installed it there, worked perfectly there

**Comment by nabeelkirmani** [comment]
> > > Hiya, Im getting this same error even after completely disabling windows defender
> > > ive tried reinstalling platformIO multiple times, and multiple versions
> > > Everything related to creating a new project throws this error, and stalls
> > > Any assistance would be appreciated, Thanks
> > 
> > 
> > Same here!
> 
> My issue was special characters in my windows file name. I had to make a new windows user with only alphanumerics in the name and installed it there, worked perfectly there

I don't have any special characters in my windows file name. I still face the issue. Please assist.

**Comment by jpolo2021** [comment]
![image](https://user-images.githubusercontent.com/77569876/162574662-441b46b7-ff16-4027-9b17-f87cc2ed28ee.png)
可能是window与linux之间的路径出错了吧

**Comment by MnemonicFish** [comment]
This solution worked for me...   

1. uninstall platformio from extensions in VScode
3. open windows explorer got to  'Users/' folder 
4. on the menu 'View' then tick the checkbox 'Hidden items' 
5. delete '.platformio' folder
6. then install platformio extension in VScode 

Once re-installed, you should see message 'Platfrom(); Rebuiling IntelliSense Index' (in the bottom footer bar). 

Install development Platform (i.e., Espressif 32) and create project as normal.

**Comment by IPTRAIN** [comment]
Hi,

as to my observations it is a fundamental error in different situations ...! Unfortunately the Error notification does not name the file which is basic for the trouble.

E.g. I have tried to import an example  sketch from an Arduino istallation which is definitely not corrupted (fully works in the Arduino IDE eco system) ...!

So I think it is an internal file (of PlatformIO) is not been found.

As so many users are facing this error - what is the official statement from PlatformIO? Or  habe I missed the offical solution / healing for some reason ?

The windows defender (in my installation) is not the problem ... ! During all trouble shooting attempts I had swiitched it off - on the other hand (by experiences from the Arduino IDE), in case of security issuses windows 10 professionel would pop up a system message asking for special allowance ...!

Such a brilliant tool ... and such a frustrating error whithout any general solution ?

**Comment by Iburtum** [comment]
i have a esp8266mod mini but im stuck aat the loadfing screen

**Comment by 61pete** [comment]
For me this was caused by Win10 "ransomware protection" on, which caused everything to be made read only.
Switching to off allowed platformio to create its default project directory in my documents.

**Comment by javierlf** [comment]
¿El fin de PlatformIO? Falta de atención por Kravets
