### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by jonathanrjpereira** [platformio/platformio-core#2325]
`PIO Core Call Error: "Obsolete PIO Core v3.6.6 is used (previous was 4.0.0a1)\r\r\nPlease remove multiple PIO Cores from a system:\r\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\r\n\r\nThe next files/directories have been created in C:\\Users\\Jonathan\\Documents\\GitHub\\Incubator\\Incubator\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing atmelsam\r\nDownloading...\r\nUnpacking...\r\natmelsam @ 3.5.0 has been successfully installed!\r\nPackageManager: Installing toolchain-gccarmnoneeabi @ >=1.40803.0,<1.40805.0\r\r\nDownloading...\r\nUnpacking...\r\ntoolchain-gccarmnoneeabi @ 1.40804.0 has been successfully installed!\r\nThe platform 'atmelsam' has been successfully installed!\r\r\nThe rest of packages will be installed automatically depending on your build environment.\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 16, in new_func\r\n    return f(get_current_context(), *args, **kwargs)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\init.py\", line 95, in cli\r\n    ide is not None)\r\n  File \"c:\\users\\jonathan\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\init.py\", line 410, in fill_project_envs\r\n    with open(join(project_dir, \"platformio.ini\"), \"a\") as f:\r\nIOError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Jonathan\\\\Documents\\\\GitHub\\\\Incubator\\\\Incubator\\\\platformio.ini'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"`

**Comment by ivankravets** [comment]
Could you reproduce this issue after VSCode restart? It seems that antivirus tools block PlatformIO.
