### ISSUE TITLE
Home: Could not list directory/Users/ali/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by engali94** [platformio/platformio-core#2327]
Invalid params: {"type":"TypeError","args":["'cmp' is an invalid keyword argument for this function"],"message":"'cmp' is an invalid keyword argument for this function"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2319

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2169
