### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by frankcfx** [platformio/platformio-core#2331]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\frank\\Documents\\PlatformIO\\Projects\\Arduino Uno\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing espressif8266\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\nespressif8266 @ 2.0.4 has been successfully installed!\r\nPackageManager: Installing toolchain-xtensa @ ~1.40802.0\r\r\nDownloading\r\nDownloading\r\nWarning! Package Mirror: \r\nLooking for another mirror...\r\nDownloading...\r\nDownloading...\r\nWarning! Package Mirror: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))\r\nLooking for another mirror...\n\nError: Please read http://bit.ly/package-manager-ioerror\r\nError: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
> Connection broken: IncompleteRead(0 bytes read)

Please check your internet connection
