### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by demsergey** [platformio/platformio-core#2332]
PIO Core Call Error: "<Exception instance at 0x7f2a1bcfb680 with str error:\n Traceback (most recent call last):\n  File \"/home/usr/.platformio/packages/contrib-pysite/twisted/python/reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 58-66: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
