### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by clplaneguy** [platformio/platformio-core#2334]
PIO Core Call Error: "Library Storage: C:\\Users\\CL Plane Guy 3\\Documents\\PlatformIO\\Projects\\190314-093423-megaatmega2560\\.piolibdeps\r\nUpdating PID                             @ bb7fb20        [dd51ba7]\r\ngit version 2.21.0.windows.1\nUpdating bb7fb20..dd51ba7\n\nerror: Your local changes to the following files would be overwritten by merge:\n\tlibrary.json\nPlease commit your changes or stash them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
> Please commit your changes or stash them before you merg

It seems that you modified cloned library.
