### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by markdlehane** [platformio/platformio-core#2337]
PIO Core Call Error: "Platform /Users/mark/.platformio/platforms/titiva\n--------\nUpdating titiva                          @ 2.0.5          [2.0.6]\nUninstalling titiva @ 2.0.5: \t[OK]\nPlatformManager: Installing titiva @ 2.0.6\nDownloading...\nUnpacking...\ntitiva @ 2.0.6 has been successfully installed!\nUpdating framework-libopencm3            @ 1.1.0          [Up-to-date]\n\nError: Detected unknown package '/Users/mark/.platformio/packages/toolchain-gccarmnoneeabi@1.40804.0 @ >=1.40803.0,<1.40805.0'"

**Comment by ivankravets** [comment]
Please close/open PIO Home. It should be fixed.
