### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by mspcbs** [platformio/platformio-core#2338]
PIO Core Call Error: "Library Storage: C:\\bb\\.platformio\\lib\r\nLibraryManager: Installing id=868\n\nError: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

**Comment by ivankravets** [comment]
> You are not connected to the Internet

Please check your internet connection

**Comment by mspcbs** [comment]
Internet connect is connected correctly.
