### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by wernersmook** [platformio/platformio-core#2342]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\werne\\Documents\\PlatformIO\\Projects\\ESP32_Toets\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError:"

**Comment by ivankravets** [comment]
Could you provide more details? Can you reproduce this issue after VSCode restart?

**Comment by wernersmook** [comment]
I have tried several times to create a new ESP32 project, without success.  Each time the process seems to get stuch and there is no internet data flow.  My internet had some problems the past few day, but this can't be the entire problem.  Is is as if PIO just can't download the necessary files

**Comment by wernersmook** [comment]
I managed to create a new ESP32 project, thanks.

**Comment by ivankravets** [comment]
How did you resolve it?

**Comment by wernersmook** [comment]
Hi Ivan, I'm not sure what actually helped.  I have uninstalled my original ESP32 platform, restarted VS Code and my internet connection got better last night.
