### ISSUE TITLE
Home: Could not list directory/private/var/folders/cm/87164lm91_517vp5t0w6lvn00000gn/T/AppTranslocation/DBFAE66A-2C46-40A2-A2ED-4EADB6131CCA

### ISSUE THREAD

**Issue by aramperez** [platformio/platformio-core#2344]
Server error: {"message":"[Errno 34] Result too large: '/private/var/folders/cm/87164lm91_517vp5t0w6lvn00000gn/T/AppTranslocation/DBFAE66A-2C46-40A2-A2ED-4EADB6131CCA'","args":[34,"Result too large"],"type":"OSError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2085
