### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by gutyek** [platformio/platformio-core#2357]
PIO Core Call Error: "<Exception instance at 0x52d7548 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\Gutyek\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe1' in position 140: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
