### ISSUE TITLE
support for arduino's tools

### ISSUE THREAD

**Issue by aster94** [platformio/platformio-core#2358]
hello,

arduino ide support the installation of tools (like [EspExceptionDecoder](https://github.com/me-no-dev/EspExceptionDecoder)) it would be useful that platformio handles in same way this too

**Comment by ivankravets** [comment]
See https://github.com/platformio/platform-espressif32/issues/105

**Comment by aster94** [comment]
Ok, that was an example so don t forget that that isn t the only tool so a generalized way of handling this would be useful
