### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by mosallaei** [platformio/platformio-core#2361]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\Mostafa\\Documents\\PlatformIO\\Projects\\190421-191629-hello_bc66\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not find a version that satisfies the requirement '>=4.8.3' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
What is your dev/platform? Please forward to https://community.platformio.org/
