### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Matias-Aguirre-CUBA** [platformio/platformio-core#2404]
Server error: {"message":"[Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\\\Users\\\\Matias Aguirre\\\\Documents\\\\PlatformIO'","args":[2,"El sistema no puede encontrar el archivo especificado"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Do you have this folder `C:\\Users\\Matias Aguirre\\Documents\\PlatformIO`? It seems that antivirus tools block PlatformIO.
