### ISSUE TITLE
Home: Libraries: Search

### ISSUE THREAD

**Issue by soelgaard** [platformio/platformio-core#2409]
PIO Core Call Error: "Error: Traceback (most recent call last):\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.params)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\r\n    return callback(*args, **kwargs)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 213, in lib_search\r\n    cache_valid=\"1d\")\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 663, in get_api_result\r\n    cc.set(cache_key, result, cache_valid)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\site-packages\\platformio\\app.py\", line 192, in set\r\n    os.makedirs(self.cache_dir)\r\n  File \"c:\\users\\laso\\.platformio\\penv\\lib\\os.py\", line 157, in makedirs\r\n    mkdir(name, mode)\r\nWindowsError: [Error 5] Access is denied: 'C:\\\\Users\\\\laso\\\\.platformio\\\\.cache'\r\n\r\n============================================================\r\n\r\nAn unexpected error occurred. Further steps:\r\n\r\n* Verify that you have the latest version of PlatformIO using\r\n  `pip install -U platformio` command\r\n\r\n* Try to find answer in FAQ Troubleshooting section\r\n  https://docs.platformio.org/page/faq.html\r\n\r\n* Report this problem to the developers\r\n  https://github.com/platformio/platformio-core/issues\r\n\r\n============================================================"

**Comment by ivankravets** [comment]
Please remove this folder `C:\\Users\\laso\\.platformio\\.cache` and restart VSCode.
