### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by Schmithtrigger** [platformio/platformio-core#2420]
PIO Core Call Error: "CorePackageManager: Installing tool-pioplus @ ^2.0.0\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\n\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\packages\\\\tool-pioplus\\\\pioplus.exe' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\packages\\tool-pioplus\\pioplus.exe`\r\n[Error 5] Acesso negado: 'C:\\\\Users\\\\schmith\\\\.platformio\\\\packages\\\\tool-pioplus' \r\nPlease manually remove the file `C:\\Users\\schmith\\.platformio\\packages\\tool-pioplus`\r\nError: Could not install 'tool-pioplus' with version requirements '^2.0.0' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Duplicate of #2369
