### ISSUE TITLE
Home: Libraries: Installed

### ISSUE THREAD

**Issue by iamaooddy** [platformio/platformio-core#2427]
PIO Core Call Error: "Error: Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /home/evga/Documents/PlatformIO/Projects/ESP32 Experiment/platformio.ini\n\t[line 26]: 'Microgear ESP32 \\n'\n\t[line 29]: 'ArduinoJson@<6.0\\n''"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2260
