### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by ibaitnt** [platformio/platformio-core#2430]
PIO Core Call Error: "Library Storage: C:\\Users\\IBAI\\.platformio\\lib\r\nLibraryManager: Installing id=1747\r\nESP8266MQTTMesh @ 1.0.4 is already installed\r\nInstalling dependencies\r\nLibraryManager: Installing id=305 @ ^1.1.3\r\r\nESPAsyncTCP @ 1.2.0 is already installed\r\nLibraryManager: Installing id=346 @ ^0.8.1\r\r\nAsyncMqttClient @ 0.8.2 is already installed\r\nInstalling dependencies\r\nLibraryManager: Installing id=305 @ ^1.1.0\r\r\nESPAsyncTCP @ 1.2.0 is already installed\r\nLibraryManager: Installing id=1826 @ ^1.0.0\r\r\nAsyncTCP @ 1.0.3 is already installed\r\nLibraryManager: Installing id=1826\r\nAsyncTCP @ 1.0.3 is already installed\r\nLibraryManager: Installing id=1938\r\nTicker-esp32 @ 1.1.0 is already installed\r\nLibraryManager: Installing AsyncMqttClient\n\nError: Please install Git client from https://git-scm.com/downloads"

**Comment by ivankravets** [comment]
Please install Git client from https://git-scm.com/downloads
