### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by doriade** [platformio/platformio-core#2432]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: /Users/Kz02/Documents/PlatformIO/Projects/slot/platformio.ini\n\t[line 15]: '1''","args":["File contains parsing errors: /Users/Kz02/Documents/PlatformIO/Projects/slot/platformio.ini\n\t[line 15]: '1'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2260
