### ISSUE TITLE
Home: Error occurred while requesting content from https://raw.githubusercontent.com/platformio/platformio-libmirror/master/configs/mbed/ILI9340Library_gmoralis.json

### ISSUE THREAD

**Issue by lxz1104** [platformio/platformio-core#2433]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /platformio/platformio-libmirror/master/configs/mbed/ILI9340Library_gmoralis.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000061D1D68>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=2)'))

**Comment by ivankravets** [comment]
Please check your internet connection.
