### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ZycaR** [platformio/platformio-core#2438]
PIO Core Call Error: "The next files/directories have been created in D:\\workspaces\\bb_ESP8266\\_tank\\EspTank\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'esp32cam'\r\n [ERROR] Took 2.57 seconds"

**Comment by ivankravets** [comment]
Please update dev/platforms in PIO IDE > PIO Home > Platforms > Updates. Restart VSCode.
