### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by karlNL** [platformio/platformio-core#2439]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\debooisk\\Documents\\PlatformIO\\Projects\\blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not install 'framework-arduinoxmc' with version requirements '^1.2.0' for your system 'windows_x86'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Please forward to https://github.com/Infineon/platformio-infineonxmc/issues
