### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by redstar2k1** [platformio/platformio-core#2440]
PIO Core Call Error: "Platform /home/mihai/.platformio/platforms/espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d\n--------\nUpdating espressif32                     @ a9e10bb        [Up-to-date]\nUpdating tool-esptoolpy                  @ 1.20600.0      [Up-to-date]\nUpdating tool-espotapy                   @ 1.1.3          [Up-to-date]\nUpdating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]\nUpdating framework-arduinoespressif32    @ 7df50a9        [697d4ff]\ngit version 2.17.1\nUpdating 7df50a9..697d4ff\n\nFetching submodule libraries/AzureIoT\nFetching submodule libraries/BLE\nerror: The following untracked working tree files would be overwritten by merge:\n\tlibraries/BLE/README.md\n\tlibraries/BLE/examples/BLE_client/BLE_client.ino\n\tlibraries/BLE/examples/BLE_iBeacon/BLE_iBeacon.ino\n\tlibraries/BLE/examples/BLE_notify/BLE_notify.ino\n\tlibraries/BLE/examples/BLE_scan/BLE_scan.ino\n\tlibraries/BLE/examples/BLE_server/BLE_server.ino\n\tlibraries/BLE/examples/BLE_server_multiconnect/BLE_server_multiconnect.ino\n\tlibraries/BLE/examples/BLE_uart/BLE_uart.ino\n\tlibraries/BLE/examples/BLE_write/BLE_write.ino\n\tlibraries/BLE/library.properties\n\tlibraries/BLE/src/BLE2902.cpp\n\tlibraries/BLE/src/BLE2902.h\n\tlibraries/BLE/src/BLE2904.cpp\n\tlibraries/BLE/src/BLE2904.h\n\tlibraries/BLE/src/BLEAddress.cpp\n\tlibraries/BLE/src/BLEAddress.h\n\tlibraries/BLE/src/BLEAdvertisedDevice.cpp\n\tlibraries/BLE/src/BLEAdvertisedDevice.h\n\tlibraries/BLE/src/BLEAdvertising.cpp\n\tlibraries/BLE/src/BLEAdvertising.h\n\tlibraries/BLE/src/BLEBeacon.cpp\n\tlibraries/BLE/src/BLEBeacon.h\n\tlibraries/BLE/src/BLECharacteristic.cpp\n\tlibraries/BLE/src/BLECharacteristic.h\n\tlibraries/BLE/src/BLECharacteristicMap.cpp\n\tlibraries/BLE/src/BLEClient.cpp\n\tlibraries/BLE/src/BLEClient.h\n\tlibraries/BLE/src/BLEDescriptor.cpp\n\tlibraries/BLE/src/BLEDescriptor.h\n\tlibraries/BLE/src/BLEDescriptorMap.cpp\n\tlibraries/BLE/src/BLEDevice.cpp\n\tlibraries/BLE/src/BLEDevice.h\n\tlibraries/BLE/src/BLEEddystoneTLM.cpp\n\tlibraries/BLE/src/BLEEddystoneTLM.h\n\tlibraries/BLE/src/BLEEddystoneURL.cpp\n\tlibraries/BLE/src/BLEEddystoneURL.h\n\tlibraries/BLE/src/BLEExceptions.cpp\n\tlibraries/BLE/src/BLEExceptions.h\n\tlibraries/BLE/src/BLEHIDDevice.cpp\n\tlibraries/BLE/src/BLEHIDDevice.h\n\tlibraries/BLE/src/BLERemoteCharacteristic.cpp\n\tlibraries/BLE/src/BLERemoteCharacteristic.h\n\tlibraries/BLE/src/BLERemoteDescriptor.cpp\n\tlibraries/BLE/src/BLERemoteDescriptor.h\n\tlibraries/BLE/src/BLERemoteService.cpp\n\tlibraries/BLE/src/BLERemoteService.h\n\tlibraries/BLE/src/BLEScan.cpp\n\tlibraries/BLE/src/BLEScan.h\n\tlibraries/BLE/src/BLESecurity.cpp\n\tlibraries/BLE/src/BLESecurity.h\n\tlibraries/BLE/src/BLEServer.cpp\n\tlibraries/BLE/src/BLEServer.h\n\tlibraries/BLE/src/BLEService.cpp\n\tlibraries/BLE/src/BLEService.h\n\tlibraries/BLE/src/BLEServiceMap.cpp\n\tlibraries/BLE/src/BLEUUID.cpp\n\tlibraries/BLE/src/BLEUUID.h\n\tlibraries/BLE/src/BLEUtils.cpp\n\tlibraries/BLE/src/BLEUtils.h\n\tlibraries/BLE/src/BLEValue.cpp\n\tlibraries/BLE/src/BLEValue.h\n\tlibraries/BLE/src/FreeRTOS.cpp\n\tlibraries/BLE/src/FreeRTOS.h\n\tlibraries/BLE/src/GeneralUtils.cpp\n\tlibraries/BLE/src/GeneralUtils.h\n\tlibraries/BLE/src/HIDKeyboardTypes.h\n\tlibraries/BLE/src/HIDTypes.h\nPlease move or remove them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
> Please move or remove them before you merge

It seems that you did changes in /home/mihai/.platformio/platforms/espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d. Please uninstall VCS version of dev/platform from `PIO IDE> PIO Home > Platforms > Installed` and install the latest stable version.
