### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by jafasa** [platformio/platformio-core#2455]
PIO Core Call Error: "Error: Invalid 'C:\\Users\\SAEED\\Desktop\\RFID + Arduino\\Arduino + ethernet shield + rfid + buzzer + display + postgresql server\\Platformio_prj_RFID\\platformio_rfid\\platformio.ini' (project configuration file): 'File contains parsing errors: C:\\Users\\SAEED\\Desktop\\RFID + Arduino\\Arduino + ethernet shield + rfid + buzzer + display + postgresql server\\Platformio_prj_RFID\\platformio_rfid\\platformio.ini\r\n\t[line 16]: 'SPI\\n'\r\n\t[line 17]: 'LiquidCrystal\\n''"

**Comment by ivankravets** [comment]
Invalid 'C:\Users\SAEED\Desktop\RFID + Arduino\Arduino + ethernet shield + rfid + buzzer + display + postgresql server\Platformio_prj_RFID\platformio_rfid\platformio.in

See https://en.wikipedia.org/wiki/INI_file
