### ISSUE TITLE
Cannot install library to project storage using GUI

### ISSUE THREAD

**Issue by kobuki** [platformio/platformio-core#2458]
As the title says. Installing eg. `id=2941`  (HTU21D by ejoyneering) from the command line like `platformio lib install 2941` works properly and installs the lib under .piolibdeps, I can update the index, use the lib, etc. However, the GUI doesn't offer to install the lib locally for the project. Image of the GUI attached.

Additional info: the project was moved from the default location in my Windows profile dir to my work directory on another drive. System is Win7 x64, VSCode 1.32.1, PIO Home 2.0.0, Core 3.6.5

![libinst](https://user-images.githubusercontent.com/6766047/54074372-06e77000-4292-11e9-80db-0e8eec4ef7df.png)

**Comment by ivankravets** [comment]
You need to open your project with PIO Home > OPen Project. After this step, you will see projects listed in this dropdown menu.

**Comment by kobuki** [comment]
@ivankravets: how is your response related to my original issue?

**Comment by ivankravets** [comment]
Could you explain in details about your issue?

**Comment by kobuki** [comment]
Could you please read my first post? I've explained and illustrated it.

**Comment by ivankravets** [comment]
Answeredhere => https://github.com/platformio/platformio-core/issues/2458#issuecomment-495331541

PIO Home does not see your project because you have not opened it yet via PIO Home.

**Comment by kobuki** [comment]
OK, so opening in PIO Home is different from opening via File/Open... or restarting VSC and letting it re-open by itself? I didn't know that.

**Comment by ivankravets** [comment]
Yes, you are right.
