### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by Jason0416** [platformio/platformio-core#2459]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/platformio/commands/lib.py\", line 403, in lib_stats\n    result = get_api_result(\"/lib/stats\", cache_valid=\"1h\")\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/platformio/util.py\", line 663, in get_api_result\n    cc.set(cache_key, result, cache_valid)\n  File \"/Users/JasonAir/.platformio/penv/lib/python2.7/site-packages/platformio/app.py\", line 201, in set\n    os.makedirs(dirname(cache_path))\n  File \"/Users/JasonAir/.platformio/penv/bin/../lib/python2.7/os.py\", line 157, in makedirs\n    mkdir(name, mode)\nOSError: [Errno 13] Permission denied: '/Users/JasonAir/.platformio/.cache/77'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please remove `/Users/JasonAir/.platformio/.cache` folder and restart VSCode.
