### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by TheOnlyMrCat** [platformio/platformio-core#2460]
PIO Core Call Error: "The next files/directories have been created in ~/Documents/PlatformIO/Projects/Robotic Arm
include - Put project header files here
lib - Put here project specific (private) libraries
src - Put project source files here
platformio.ini - Project Configuration File

Error: Detected unknown package 'tool-scons'"

**Comment by ivankravets** [comment]
It seems that your antivirus tool blocks PlatformIO Package Manager. See http://docs.platformio.org/en/latest/faq.html#error-5-access-is-denied
