### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Antonio199811** [platformio/platformio-core#2464]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\DELL\\Documents\\PlatformIO\\Projects\\fotocelda\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing atmelavr\r\nDownloading\r\nDownloading\r\nUnpacking\r\nUnpacking\r\natmelavr @ 1.13.0 has been successfully installed!\r\nPackageManager: Installing toolchain-atmelavr @ ~1.50400.0\r\r\nDownloading...\r\nUnpacking\r\nUnpacking\r\ntoolchain-atmelavr @ 1.50400.0 has been successfully installed!\r\nThe platform 'atmelavr' has been successfully installed!\r\r\nThe rest of packages will be installed automatically depending on your build environment.\n\nError: Detected unknown package 'tool-scons'"

**Comment by ivankravets** [comment]
It seems that antivirus tools block PlatformIO Package manager. Please check them and restart VSCode.
