### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by halipic** [platformio/platformio-core#2467]
PIO Core Call Error: "Library Storage: C:\\Users\\AKTA\\.platformio\\lib\r\nLibraryManager: Installing id=727\r\nDownloading...\r\nUnpacking...\r\nNtpClientLib @ 3.0.1-beta has been successfully installed!\r\nInstalling dependencies\r\nLooking for Time library in registry\r\r\nFound: https://platformio.org/lib/show/44/Time\r\nLibraryManager: Installing id=44 @ ^5.10\n\nError: Could not find a version that satisfies the requirement '^5.10' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
There is no 5.10 version for https://platformio.org/lib/show/44/Time%5Cr%5CnLibraryManager
