### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by kutitata** [platformio/platformio-core#2479]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\balraj.gopala\\Documents\\PlatformIO\\Projects\\strip rgb node32s\\platformio.ini, line: 1\n'esp32thing ; PlatformIO Project Configuration File\\n''","args":["File contains no section headers.\nfile: C:\\Users\\balraj.gopala\\Documents\\PlatformIO\\Projects\\strip rgb node32s\\platformio.ini, line: 1\n'esp32thing ; PlatformIO Project Configuration File\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\nfile: C:\Users\balraj.gopala\Documents\PlatformIO\Projects\strip rgb node32s\platformio.ini
