### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Mechanikerlegion511** [platformio/platformio-core#2481]
PIO Core Call Error: "Library Storage: C:\\Users\\rtyuu\\.platformio\\lib\r\nLooking for Eeprom_at24c256 library in registry\n\nError: Library `{'requirements': None, 'name': 'Eeprom_at24c256'}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'requirements': None, 'name': 'Eeprom_at24c256'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
There is no `Eeprom_at24c256` library in public registry.
