### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by exocode** [platformio/platformio-core#2483]
When I try to update my libs of a project I get this error

PIO Core Call Error: "Library Storage: /Users/janjezek/Coding/PlatformIO/Projects/myproject/.piolibdeps\nUpdating arduino-esp32                   @ 5af0336        [aff2e42]\ngit version 2.20.1\nUpdating 5af0336..aff2e42\n\nFrom https://github.com/espressif/arduino-esp32\n   7dd537f..aff2e42  master     -> origin/master\nFetching submodule libraries/AzureIoT\nFetching submodule libraries/BLE\nerror: The following untracked working tree files would be overwritten by merge:\n\tlibraries/BLE/README.md\n\tlibraries/BLE/examples/BLE_client/BLE_client.ino\n\tlibraries/BLE/examples/BLE_iBeacon/BLE_iBeacon.ino\n\tlibraries/BLE/examples/BLE_notify/BLE_notify.ino\n\tlibraries/BLE/examples/BLE_scan/BLE_scan.ino\n\tlibraries/BLE/examples/BLE_server/BLE_server.ino\n\tlibraries/BLE/examples/BLE_server_multiconnect/BLE_server_multiconnect.ino\n\tlibraries/BLE/examples/BLE_uart/BLE_uart.ino\n\tlibraries/BLE/examples/BLE_write/BLE_write.ino\n\tlibraries/BLE/library.properties\n\tlibraries/BLE/src/BLE2902.cpp\n\tlibraries/BLE/src/BLE2902.h\n\tlibraries/BLE/src/BLE2904.cpp\n\tlibraries/BLE/src/BLE2904.h\n\tlibraries/BLE/src/BLEAddress.cpp\n\tlibraries/BLE/src/BLEAddress.h\n\tlibraries/BLE/src/BLEAdvertisedDevice.cpp\n\tlibraries/BLE/src/BLEAdvertisedDevice.h\n\tlibraries/BLE/src/BLEAdvertising.cpp\n\tlibraries/BLE/src/BLEAdvertising.h\n\tlibraries/BLE/src/BLEBeacon.cpp\n\tlibraries/BLE/src/BLEBeacon.h\n\tlibraries/BLE/src/BLECharacteristic.cpp\n\tlibraries/BLE/src/BLECharacteristic.h\n\tlibraries/BLE/src/BLECharacteristicMap.cpp\n\tlibraries/BLE/src/BLEClient.cpp\n\tlibraries/BLE/src/BLEClient.h\n\tlibraries/BLE/src/BLEDescriptor.cpp\n\tlibraries/BLE/src/BLEDescriptor.h\n\tlibraries/BLE/src/BLEDescriptorMap.cpp\n\tlibraries/BLE/src/BLEDevice.cpp\n\tlibraries/BLE/src/BLEDevice.h\n\tlibraries/BLE/src/BLEEddystoneTLM.cpp\n\tlibraries/BLE/src/BLEEddystoneTLM.h\n\tlibraries/BLE/src/BLEEddystoneURL.cpp\n\tlibraries/BLE/src/BLEEddystoneURL.h\n\tlibraries/BLE/src/BLEExceptions.cpp\n\tlibraries/BLE/src/BLEExceptions.h\n\tlibraries/BLE/src/BLEHIDDevice.cpp\n\tlibraries/BLE/src/BLEHIDDevice.h\n\tlibraries/BLE/src/BLERemoteCharacteristic.cpp\n\tlibraries/BLE/src/BLERemoteCharacteristic.h\n\tlibraries/BLE/src/BLERemoteDescriptor.cpp\n\tlibraries/BLE/src/BLERemoteDescriptor.h\n\tlibraries/BLE/src/BLERemoteService.cpp\n\tlibraries/BLE/src/BLERemoteService.h\n\tlibraries/BLE/src/BLEScan.cpp\n\tlibraries/BLE/src/BLEScan.h\n\tlibraries/BLE/src/BLESecurity.cpp\n\tlibraries/BLE/src/BLESecurity.h\n\tlibraries/BLE/src/BLEServer.cpp\n\tlibraries/BLE/src/BLEServer.h\n\tlibraries/BLE/src/BLEService.cpp\n\tlibraries/BLE/src/BLEService.h\n\tlibraries/BLE/src/BLEServiceMap.cpp\n\tlibraries/BLE/src/BLEUUID.cpp\n\tlibraries/BLE/src/BLEUUID.h\n\tlibraries/BLE/src/BLEUtils.cpp\n\tlibraries/BLE/src/BLEUtils.h\n\tlibraries/BLE/src/BLEValue.cpp\n\tlibraries/BLE/src/BLEValue.h\n\tlibraries/BLE/src/FreeRTOS.cpp\n\tlibraries/BLE/src/FreeRTOS.h\n\tlibraries/BLE/src/GeneralUtils.cpp\n\tlibraries/BLE/src/GeneralUtils.h\n\tlibraries/BLE/src/HIDKeyboardTypes.h\n\tlibraries/BLE/src/HIDTypes.h\nPlease move or remove them before you merge.\nAborting\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
> The following untracked working tree files would be overwritten by merge

It seems that you edited the cloned source code. Also, `https://github.com/espressif/arduino-esp32` this is not a library.
