### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by 1v1n** [platformio/platformio-core#2484]
Server error: {"message":"[Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\\\Users\\\\XXXX\\\\Documents\\\\PlatformIO'","args":[2,"El sistema no puede encontrar el archivo especificado"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Comment by ivankravets** [comment]
Do you see this folder `C:\\Users\\XXXX\\Documents\\PlatformIO`?
