### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by witan4702** [platformio/platformio-core#2491]
PIO Core Call Error: "Library Storage: C:\\Users\\witan\\Documents\\Arduino\\libraries\r\nUpdating AutoConnect                     @ 0.9.7          [0.9.8]\r\r\nUninstalling AutoConnect @ 0.9.7: \t[OK]\r\nLooking for AutoConnect library in registry\r\nFound: https://platformio.org/lib/show/2678/AutoConnect\n\nError: Traceback (most recent call last):\r\n  File \"c:\\users\\witan\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 120, in main\r\n    cli(None, None, None)\r\n  File \"c:\\users\\witan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"c:\\users\\witan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\r\n    rv = self.invoke(ctx)\r\n  File \"c:\\users\\witan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\witan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\r\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\r\n  File \"c:\\users\\witan\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\r\n    return ctx.invoke(self.callback, **ctx.para

**Comment by ivankravets** [comment]
What is a version of PIO Core? Please open PlatformIO IDE Terminal and type `pio --version.`

**Comment by witan4702** [comment]
PlatformIO, version 4.0.0a12

**Comment by ivankravets** [comment]
I can't reproduce this issue. Could you try to run `pio update` from PlatformIO IDE Terminal and provide full output?

**Comment by ivankravets** [comment]
Please reopen if you still need help
