### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Microinstance** [platformio/platformio-core#2492]
PIO Core Call Error: "The next files/directories have been created in /Users/Partha/Documents/PlatformIO/Projects/Quectel\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing mc60 (platform: quectel; board: mc60; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\n<<<<<<<<<<<< QUECTEL MC60 MODULE 2018 Georgi Angelov >>>>>>>>>>>>\nCONFIGURATION: https://docs.platformio.org/page/boards/quectel/mc60.html\nPLATFORM: Quectel > Quectel MC60 module\nHARDWARE: ARM, MT2503 260MHz 100KB RAM (320KB Flash)\nDEBUG: CURRENT(uart) ON-BOARD(uart)\nImportError: No module named arduino-mc60:\nFile \"/Users/Partha/.platformio/penv/lib/python2.7/site-packages/platformio/builder/main.py\", line 169:\nenv.SConscript(\"$BUILD_SCRIPT\")\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/Users/Partha/.platformio/platforms/quectel/builder/main.py\", line 37:\nelf = env.BuildProgram()\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"/Users/Partha/.platformio/penv/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 107:\nenv.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\nreturn self.method(*nargs, **kwargs)\nFile \"/Users/Partha/.platformio/penv/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 319:\nSConscript(env.GetFrameworkScript(f), exports=\"env\")\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 604:\nreturn method(*args, **kw)\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\nreturn _SConscript(self.fs, *files, **subst_kw)\nFile \"/Users/Partha/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\nexec _file_ in call_stack[-1].globals\nFile \"/Users/Partha/.platformio/platforms/quectel/builder/frameworks/arduino.py\", line 11:\nm = __import__(module)\n========================== [ERROR] Took 0.44 seconds =========================="

**Comment by ivankravets** [comment]
Please move issue to https://github.com/Wiz-IO/platform-quectel/issues
