### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by gdmuzzillo** [platformio/platformio-core#2493]
PIO Core Call Error: "Library Storage: /home/gustavo/.platformio/lib\nUpdating NtpClientLib                    @ 2.5.1          [3.0.1-beta]\nUninstalling NtpClientLib @ 2.5.1: \t[OK]\nLooking for NtpClientLib library in registry\nFound: https://platformio.org/lib/show/727/NtpClientLib\nLibraryManager: Installing id=727 @ 3.0.1-beta\nDownloading...\nUnpacking...\nNtpClientLib @ 3.0.1-beta has been successfully installed!\nInstalling dependencies\nLooking for Time library in registry\nFound: https://platformio.org/lib/show/44/Time\nLibraryManager: Installing id=44 @ ^5.10\n\nError: Could not find a version that satisfies the requirement '^5.10' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment]
Fixed in https://github.com/gmag11/NtpClient/pull/96
