### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by gonraul** [platformio/platformio-core#2495]
Server error: {"message":"[Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\\\Users\\\\grele\\\\Documents\\\\PlatformIO\\\\Projects\\\\Blink Arduino UNO'","args":[2,"El sistema no puede encontrar el archivo especificado"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
