### ISSUE TITLE
Home: Could not list directory/private/var/folders/1_/9sqg05x94sn3qvp0czv06d980000gp/T/AppTranslocation/888A3063-26AE-4977-B4FC-981473D6D159

### ISSUE THREAD

**Issue by HiroyukiInamoto** [platformio/platformio-core#2501]
Server error: {"message":"[Errno 34] Result too large: '/private/var/folders/1_/9sqg05x94sn3qvp0czv06d980000gp/T/AppTranslocation/888A3063-26AE-4977-B4FC-981473D6D159'","args":[34,"Result too large"],"type":"OSError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2083
