### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by jhon24samuel** [platformio/platformio-core#2507]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\JSFGDEVELOPER\\Documents\\PlatformIO\\Projects\\Arduino_Reader\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing atmelavr\r\nDownloading...\r\nUnpacking...\r\natmelavr @ 1.13.0 has been successfully installed!\r\nPackageManager: Installing toolchain-atmelavr @ ~1.50400.0\r\r\nDownloading...\r\nUnpacking...\r\ntoolchain-atmelavr @ 1.50400.0 has been successfully installed!\r\nThe platform 'atmelavr' has been successfully installed!\r\r\nThe rest of packages will be installed automatically depending on your build environment.\n\nError: Could not install 'framework-arduinoavr' with version requirements '~3.10623.190424' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
It seems that antivirus tools block PlatformIO package manager. Please try this solution -> http://bit.ly/faq-package-manager
