### ISSUE TITLE
[Eclipse] -U in build_flags does not undefine symbols in generated project

### ISSUE THREAD

**Issue by dogtopus** [platformio/platformio-core#2508]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Arch Linux

**PlatformIO Version** (`platformio --version`): 4.0.0a13

### Description of problem

Undefining a previously defined symbol using -U does not undefine it in the generated Eclipse project file.

#### Steps to Reproduce

1. Append `-DA_SYMBOL -UA_SYMBOL` to `build_flags`
2. Run `pio init --ide eclipse`
3. Open the generated `.cproject` file and check for `Symbols` option

### Actual Results

`A_SYMBOL` still shows up.

### Expected Results

`A_SYMBOL` should not appear in the list since it is already undefined

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -DA_SYMBOL -UA_SYMBOL
```

**Comment by ivankravets** [comment]
Please re-test with the latest PIO Core 
```
pio upgrade --dev
```

Thanks!
