### ISSUE TITLE
[Eclipse] Include path search order is inconsistent to what passed to the compiler

### ISSUE THREAD

**Issue by dogtopus** [platformio/platformio-core#2509]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Arch Linux

**PlatformIO Version** (`platformio --version`): 4.0.0a13

### Description of problem

When generating a Eclipse project, PlatformIO writes the include search path backwards. This results in Eclipse not being able to read the same header files as the compiler when there is a name collision between project header files and library header files.

#### Steps to Reproduce

1. Install a library that contains header H.
2. Create a different header in project and name it H.
3. Include H somewhere in the project.
4. Open project in Eclipse and browse through source file.

### Actual Results

Eclipse complains about undefined symbols despite that they were defined in H (project) (but not in H (library)). Using the "Jump to Declaration" feature on the include statement jumps to H (library). The project builds okay using `pio run`.

### Expected Results

Eclipse resolves the include correctly and using the "Jump to Declaration" feature on the include statement jumps to H (project).

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
```

**Source file to reproduce issue:**
lib/Library/header.h:

```cpp
#pragma once

#define IN_LIBRARY
```

include/header.h:

```cpp
#pragma once

#define IN_PROJECT
```

src/main.cpp:

```cpp
#include <Arduino.h>
#include "header.h"

#ifdef IN_LIBRARY
#warning "In library"
#endif

#ifdef IN_PROJECT
#warning "In project"
#endif

void setup() {}
void loop() {}
```

### Additional info

![warn](https://user-images.githubusercontent.com/3405234/57961442-6478e800-78e5-11e9-9bcd-2cb4385dc9f0.png)

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.
