### ISSUE TITLE
platformio build not respecting library.json in a lib/ directory

### ISSUE THREAD

**Issue by lf-** [platformio/platformio-core#2518]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 10

**PlatformIO Version** (`platformio --version`):
```
platformio --version
PlatformIO, version 3.6.7
```

### Description of problem
My library.json in lib/ETL appears to be being ignored as includeDir is not being passed to the compiler.

Its contents are:
```json
{
    "name": "etl",
    "description": "C++1x Embedded Template Library for AVR 8-bit and Espressif ESP8266 microcontrollers.",
    "keywords": "stl",
    "repository": {
        "type": "git",
        "url": "https://github.com/ambroise-leclerc/ETL"
    },
    "build": {
        "includeDir": "libstd/include/"
    }
}
```

#### Steps to Reproduce

1. Make a new platformio project
2. `cd lib`, `git clone https://github.com/ambroise-leclerc/ETL`, `cd ETL`
3. Create `library.json` in current directory with above contents
4. `#include <initializer_list>` in your main.cpp

### Actual Results
```
platformio run -vvv
<...>
avr-g++ -o .pioenvs\uno\src\main.cpp.o -c <...> -Iinclude -Isrc -Ilib\TETRIX_PRIZM *************-Ilib\ETL*********** -IC:\Users\lf\.platformio\packages\framework-arduinoavr\cores\arduino -IC:\Users\lf\.platformio\packages\framework-arduinoavr\variants\standard src\main.cpp
```

(copious asterisks my own)

### Expected Results
It should produce the correct `-I` option including the libstd/include part.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_deps = etl
```

**Source file to reproduce issue:**
```cpp
#include <initializer_list>
void setup(){}
void loop(){}
```

**Comment by ivankravets** [comment]
`includeDir` and `srcDir` were added in PlatformIO Core 4.0. Please re-test with `pio upgrade --dev`.

Thanks!
