### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by UweSeifert** [platformio/platformio-core#2521]
PIO Core Call Error: "The next files/directories have been created in /Volumes/externeSSD/20-Development/14-PlatformIO/2-Robots/robot-5001\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Could not install 'framework-esp8266-rtos-sdk' with version requirements '>=1.5.0-beta' for your system 'darwin_x86_64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Please check that you have access to this manifest https://raw.githubusercontent.com/yanbe/framework-esp8266-rtos-sdk/master/manifest.json

Try to restart VSCode and check that antivirus tools don't block PlatformIO package manager.
