### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by chivi3d** [platformio/platformio-core#2522]
PIO Core Call Error: "PlatformManager: Installing Sonoff-Tasmota\ngit version 2.21.0\nSonoff-Tasmota @ d599f21 has been successfully installed!\n\nClonando en '/home/chivi/.platformio/platforms/_tmp_installing-BVrEH4-package'...\nError: Traceback (most recent call last):\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/platform.py\", line 313, in platform_install\n    force=force):\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 71, in install\n    p = PlatformFactory.newPlatform(platform_dir)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 250, in newPlatform\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/platform.py\", line 460, in __init__\n    self._manifest = util.load_json(manifest_path)\n  File \"/home/chivi/.platformio/penv/local/lib/python2.7/site-packages/platformio/util.py\", line 185, in load_json\n    with open(file_path, \"r\") as f:\nIOError: [Errno 2] No such file or directory: '/home/chivi/.platformio/platforms/Sonoff-Tasmota/platform.json'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> '/home/chivi/.platformio/platforms/Sonoff-Tasmota/platform.json

What is it? Please uninstall it and use official ESP8266 dev/platform.
