### ISSUE TITLE
CMakeListsPrivate.txt gets hardcoded `set(CMAKE_CXX_STANDARD 11)`

### ISSUE THREAD

**Issue by SurealCereal** [platformio/platformio-core#2527]
What kind of issue is this?

- [x] **PlatformIO Core**.
------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu 19.04 x64
**PlatformIO Version** (`platformio --version`): 3.6.7

### Description of problem
The generated CMakeListsPrivate.txt seems to have a "hard-coded" value from [`platformio/ide/tpls/clion/CMakeLists.txt.tpl`](https://github.com/platformio/platformio-core/blob/master/platformio/ide/tpls/clion/CMakeListsPrivate.txt.tpl).  The line `set(CMAKE_CXX_STANDARD 11)` is added even if  `platformio.ini` contains a C++ version override, say via `build_flags=-std=c++14`

The next problem occurs if I fix the hard-coded value to `set(CMAKE_CXX_STANDARD 14)` - the fix will be reset the next time the CMakeListsPrivate.txt is generated.

I am using PlatformIO inside CLion where it works well.  File Watchers triggering CMakeList generation seems like a very elegant solution imo :^)

#### Steps to Reproduce

1. Create a project using instructions here: https://docs.platformio.org/en/latest/ide/clion.html#integration
2. Use the included platformio.ini config or similar
3.  Re-index/regenerate CMake files.
4.  Add some C++ 2014 code
4.  Build the project.

### Actual Results
CMakeListsPrivate.txt contains `set(CMAKE_CXX_STANDARD 11)`

Project fails to build

### Expected Results
CMakeListsPrivate.txt should contain `set(CMAKE_CXX_STANDARD 14)`
Project should build successfully.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:zeroUSB]
platform = atmelsam
board = zeroUSB
framework = arduino
upload_port = /dev/ttyACM0
build_unflags =
    -std=gnu++98
    -std=gnu++11
    -std=c++11
build_flags =
    -std=c++14
```

**Source file to reproduce issue:**
```cpp
// Example C++ 2014 code that fails to compile due to C++ 2011 being set.
template <typename E>
constexpr auto ordinal(E e) noexcept {
    return static_cast<std::underlying_type_t<E>>(e);
}
```

### Additional info
It seems this issue was raised here: https://github.com/platformio/platformio-core/pull/873 which resulted in the hard-coded `set(CMAKE_CXX_STANDARD 11)` being added to the template.  I can update the template on my filesystem, but then it may be overridden in a PlatformIO update, and I have projects that have different language levels; C++ 11, 14, 17.

**Comment by ivankravets** [comment]
Please re-test with `$ pio upgrade --dev`.

> The next problem occurs if I fix the hard-coded value to set(CMAKE_CXX_STANDARD 14) - the fix will be reset the next time the CMakeListsPrivate.txt is generated.

Fixed in https://github.com/platformio/platformio-core/commit/7beb332b3170141331b1c58837d3380872b1adcc
