### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by spdi** [platformio/platformio-core#2533]
PIO Core Call Error: "Library Storage: C:\\Users\\Michal\\.platformio\\lib\r\nLibraryManager: Installing id=727\r\nDownloading...\r\nUnpacking\r\nUnpacking\r\nNtpClientLib @ 3.0.1-beta has been successfully installed!\r\nInstalling dependencies\r\nLooking for Time library in registry\r\r\nFound: https://platformio.org/lib/show/44/Time\r\nLibraryManager: Installing id=44 @ ^5.10\n\nError: Could not find a version that satisfies the requirement '^5.10' for your system 'windows_amd64'"

I have not AMD. My procesor is Intel i7 :)

Second "Install" hit gives:

Libraries: Could not install library
PIO Core Call Error: "Library Storage: C:\\Users\\Michal\\.platformio\\lib\r\nLibraryManager: Installing id=727\r\nNtpClientLib @ 3.0.1-beta is already installed\r\nInstalling dependencies\r\nLooking for Time library in registry\r\r\nFound: https://platformio.org/lib/show/44/Time\r\nLibraryManager: Installing id=44 @ ^5.10\n\nError: Could not find a version that satisfies the requirement '^5.10' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Fixed in https://github.com/gmag11/NtpClient/pull/96
