### ISSUE TITLE
Use wildcards for monitor_port

### ISSUE THREAD

**Issue by robbertkl** [platformio/platformio-core#2541]
See #839, same thing but for `monitor_port`.

I use a wildcard in my `upload_port` setting, but unfortunately can't do the same for `monitor_port`, which means I still have to change or choose it manually every time.

**Comment by ivankravets** [comment]
Please re-test with the latest PIO Core 4.0:
```
pio upgrade --dev
```

**Comment by robbertkl** [comment]
Works for me. Thanks for the super fast fix!
