### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [platformio/platformio-core#2546]
PIO Core Call Error: "The next files/directories have been created in /Users/taghawi/Documents/PlatformIO/Projects/smart_toilet\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: \nProcessing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'esp32cam'\n========================== [ERROR] Took 0.69 seconds ==========================\n\n================================== [SUMMARY] ==================================\nEnvironment nodemcu-32s\t[SKIP]\nEnvironment esp32cam   \t[ERROR]\n========================== [ERROR] Took 0.69 seconds =========================="

**Comment by ivankravets** [comment]
> Error: Unknown board ID 'esp32cam

Please update your dev/platforms via PIO Home > Platforms > Updates.
