### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mksouzza** [platformio/platformio-core#2550]
PIO Core Call Error: "<Exception instance at 0x68777c8 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe3' in position 63: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
What is your Windows version and locale?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2078
