### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by DjamesSuhanko** [platformio/platformio-core#2555]
PIO Core Call Error: "Library Storage: /home/djames/.platformio/lib\nLibraryManager: Installing id=727\nDownloading...\nUnpacking\nUnpacking\nNtpClientLib @ 3.0.1-beta has been successfully installed!\nInstalling dependencies\nLooking for Time library in registry\nFound: https://platformio.org/lib/show/44/Time\nLibraryManager: Installing id=44 @ ^5.10\n\nError: Could not find a version that satisfies the requirement '^5.10' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment]
Fixed in gmag11/NtpClient#96
