### ISSUE TITLE
Package cache expires too fast

### ISSUE THREAD

**Issue by mcspr** [platformio/platformio-core#2559]
Running platformio from develop branch.

In platformio.ini
```
lib_deps =
    ArduinoJson@5.13.4
```

Watching 2 files:
```
~/.platformio/.cache/65/8154dacc963fd98df885ac5d9cc5c265
~/.platformio/.cache/7e/ba586a56b4024a92728654afd0862c7e
```

Running basic empty project with d1_mini board:
```
$ pio run
$ rm -r .pio/libdeps/<env>/ArduinoJson_ID64
$ ...wait some time...
$ pio run
```
Package archive and fname from cache are deleted and redownloaded after 1 minute.
Observed either using prints in ContentCache or `inotifywait -mr ~/.platformio/.cache` (preemptively cleaned, to minimize cache changes)

Looking at expiration time shortcuts:
https://github.com/platformio/platformio-core/blob/67f7b6cda39b607e3c093bbb254443ef93cd3a68/platformio/app.py#L199

This is 1 minute instead of intended 30d:
https://github.com/platformio/platformio-core/blob/67f7b6cda39b607e3c093bbb254443ef93cd3a68/platformio/managers/package.py#L142

Shouldn't expiration time be "never" for these, since urls are (evidently) unique per version? Still allowing manual clean-up (adding second time field, "created_at"?)
Or requests itself can cache things based on etag, or pass it along.

_Originally posted by @mcspr in https://github.com/platformio/platformio-core/issues/1696#issuecomment-495916657_
*edit: pio version, typo. and sorry no template, this was opened via "reference in a new issue"*

**Comment by ivankravets** [comment]
Thank you so much for the report! Please re-test with `pio upgrade --dev`.

**Comment by mcspr** [comment]
It works, thanks!
