### ISSUE TITLE
Home: object has no attribute 'get_projectlibdeps_dir'

### ISSUE THREAD

**Issue by phsarawut** [platformio/platformio-core#2561]
Server error: {"message":"'module' object has no attribute 'get_projectlibdeps_dir'","args":["'module' object has no attribute 'get_projectlibdeps_dir'"],"type":"AttributeError"}

**Comment by ivankravets** [comment]
What is your PIO Core version? Please open PIO IDE Terminal and type 
```
pio upgrade
```
