### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by anchevab** [platformio/platformio-core#2562]
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\Anchev\\\\Documents\\\\PlatformIO\\\\Projects\\\\STM32F103C\\\\STM32F103C_BlinkLED'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Do have this folder `C:\\Users\\Anchev\\Documents\\PlatformIO\\Projects\\STM32F103C\\STM32F103C_BlinkLED'`? Please restart VScode, it should be fixed.
