### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by shadababe04** [platformio/platformio-core#2563]
PIO Core Call Error: "The next files/directories have been created in /Users/Beyond/Documents/PlatformIO/Projects/stm blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Detected unknown package 'framework-arduinoststm32'"

**Comment by ivankravets** [comment]
> Detected unknown package 'framework-arduinoststm32'

It seems that antivirus tools of a system block PlatformIO package manager. Please restart VSCode and check internet connection.
