### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by juniorya** [platformio/platformio-core#2575]
PIO Core Call Error: "<Exception instance at 0x4aa3848 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-63: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
What is your Windows version and locale?

**Comment by juniorya** [comment]
Windows 7 x64

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart VSCode. Does it work now?
