### ISSUE TITLE
util.load_project_config() no longer working

### ISSUE THREAD

**Issue by cyberman54** [platformio/platformio-core#2583]
@ivankravets 
In `platformio.org` I'm calling a pre:build.py script which uses

```
# get platformio environment variables
project_config = util.load_project_config()
```

It seems commit #3df0140 broke this. How can i fix it?

**Comment by ivankravets** [comment]
See updated example http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#custom-options-in-platformio-ini

We recommend using native Python config parser.

**Comment by cyberman54** [comment]
@ivankravets 
But some .py modules of platformio-core still use the old method, e.g.

https://github.com/platformio/platformio-core/blob/develop/platformio/builder/main.py

**Comment by ivankravets** [comment]
> But some .py modules of platformio-core still use the old method, e.g.

Which old methods?

**Comment by cyberman54** [comment]
https://github.com/platformio/platformio-core/search?q=import+util&unscoped_q=import+util

**Comment by cyberman54** [comment]
@ivankravets 

> TypeError: 'module' object is not callable:
>   File "C:\Users\MyUser\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 178:
>     env.SConscript(item, exports="env")

**Comment by ivankravets** [comment]
We'll introduce totally new project option management API today/tomorrow. Still in testing. There will be opened API for build scripts:
```
env.GetProjectOption(option, default=None)
```

> from platformio import util

What is wrong with this import? I mean that `load_project_config` was totally removed from PlatformIO Core 4.0 because there is no single config `platformio.ini` which we had in PlatformIO Core. Now, you can pass a custom project config.

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by irwanayeah** [comment]
yes, I have same issue and solved by http://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#custom-options-in-platformio-ini
thx guys.

**Comment by cyberman54** [comment]
Same here.
