### ISSUE TITLE
 TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by cyberman54** [platformio/platformio-core#2588]
After upgrade to platformio v4.0.0a15 i cannot build any more, build is running on error

> TypeError: 'module' object is not callable:
> File "C:\Users\MyUser\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 178:
> env.SConscript(item, exports="env")

After reinstalling platformio with old core v3.6.7 it works again.

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce this issue? Thanks!

**Comment by ivankravets** [comment]
Please reopen if you still need help
