### ISSUE TITLE
Improve platform update error management through GUI

### ISSUE THREAD

**Issue by Navis-Raven** [platformio/platformio-core#2594]
The problem is that from time to time there is some trouble or errors while updating a platform through GUI here:
![image](https://user-images.githubusercontent.com/15887222/58682031-442e3c00-836f-11e9-9128-778498dd0ae0.png)

However, there is no error message nor anything we only see that it is still trying/loading for updating the platform. 
Otherwise if we do platformio updates all platform through scripts or command then we see the problem or the error message, and what we have to fix. 

So my suggestion is to improve error management through the GUI.

**Comment by ivankravets** [comment]
Could you provide more details? I've just raised some exception in the update process and it works:

# CLI

![Screen Shot 2019-08-25 at 12 21 39](https://user-images.githubusercontent.com/1760209/63648069-ea9d9980-c732-11e9-8aee-371093843e1d.png)

# PIO Home

![Screen Shot 2019-08-25 at 12 21 55](https://user-images.githubusercontent.com/1760209/63648072-fee19680-c732-11e9-8cfa-16e7f7cd63b6.png)

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by Navis-Raven** [comment]
Sorry for the delay, I was in vacations. 


I think you didn''t understand. The problem occurs when you update through the GUI. 

Look at the screenshots you have, you have also some errors !
![image](https://user-images.githubusercontent.com/15887222/64559850-817b7000-d347-11e9-85fc-b1f9ac5c91a7.png)

**Comment by ivankravets** [comment]
Hi! This is normal. If you click on "Report problem", what do you see? Could you post report here? Thanks!

**Comment by Navis-Raven** [comment]
That's ok, next time I'll see the report I'll post it here.
