### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by vasilev3103** [platformio/platformio-core#2596]
Server error: {"message":"'ascii' codec can't encode characters in position 43-49: ordinal not in range(128)","args":["ascii","File contains no section headers.\nfile: E:\\Ардуино\\JeeUIFramework-master\\platformio.ini, line: 1\n' ; PlatformIO Project Configuration File\\n'",43,50,"ordinal not in range(128)"],"type":"UnicodeEncodeError"}

**Comment by ivankravets** [comment]
> File contains no section headers

Invalid `platformio.ini` file.
