### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by jpunn** [platformio/platformio-core#2604]
PIO Core Call Error: "The next files/directories have been created in /home/jpy/Documents/PlatformIO/Projects/SoftGrow\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Processing ttgo-lora32-v1 (platform: espressif32; board: ttgo-lora32-v1; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'ttgo-lora32-v1'\n========================== [ERROR] Took 1.66 seconds =========================="

**Comment by ivankravets** [comment]
Please open PIO Home > Platforms > Updates and update all platforms. Restart VSCode.
