### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by ogursoft** [platformio/platformio-core#2609]
PIO Core Call Error: "<Exception instance at 0x777ca48 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-60: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio upgrade --dev
pio update
```

Restart VSCode. Does it work now?
