### ISSUE TITLE
Not able to see which project lib gets assigned to

### ISSUE THREAD

**Issue by exocode** [platformio/platformio-core#2614]
Feature/Issue

#### Steps to Reproduce

1. Open library browser
2. select a library
3. try to assign them to a specific project

### Actual Results

Cannot read which project is selected

### Expected Results

Broader / wider selection list.

### Additional info

![2019-06-03 16 37 17](https://user-images.githubusercontent.com/1597621/58810475-47028880-861e-11e9-939d-6487ab1668ed.gif)

**EDIT**

Here is the corresponding CSS
```
<div class="ant-select-dropdown ant-select-dropdown--single ant-select-dropdown-placement-bottomLeft" style="width: 362px;left: 710.375px;top: 222.207px;">
```

**EXPECTED RESULT**

![Bildschirmfoto 2019-06-03 um 16 45 14](https://user-images.githubusercontent.com/1597621/58810830-022b2180-861f-11e9-8dea-9b0fbed121f6.png)

**Comment by ivankravets** [comment]
Please update core packages via `pio update` command. Restart VSCode.

Thanks for the report!
