### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by Bighoneypot** [platformio/platformio-core#2624]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\IoT\\Documents\\PlatformIO\\Projects\\190604-123315-nodemcuv2\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Invalid value: Directory \"~/Documents/Arduino/libraries\" does not exist. for option `lib_extra_dirs` in section [env:nodemcuv2]"

**Comment by ivankravets** [comment]
> Directory "~/Documents/Arduino/libraries

Is it true?

**Comment by ivankravets** [comment]
Please open PIO IDE Terminal, type `pio upgrade --dev`, restart VSCOde.

Should work now. Thanks for the report!

**Comment by Bighoneypot** [comment]
> Please open PIO IDE Terminal, type pio upgrade --dev, restart VSCOde


Ok, now is possible to import a .ino file.

Thank you man.

**Comment by Bighoneypot** [comment]
> > Directory "~/Documents/Arduino/libraries
> 
> Is it true?

Yes

**Comment by Bighoneypot** [comment]
But..
when I use platformio I can't build the sketch because (.platformio applications framework-arduinoespressif8266 libraries Wire Wire.cpp: 38: 2: error: #error Wire library is not supported on this board)

instead with the arduino I can compile an the libraries Wire is compatibile.
The libraries are the same
