### ISSUE TITLE
Please open PIO IDE Terminal, type `pio upgrade --dev` and restart VSCode.

### ISSUE THREAD

**Issue by toni55** [platformio/platformio-core#2640]
Please open PIO IDE Terminal, type `pio upgrade --dev` and restart VSCode.

_Originally posted by @ivankravets in https://github.com/platformio/platformio-core/issues/2621#issuecomment-498440231_

this answer don't work for me

**Comment by ivankravets** [comment]
Could you try to kill all `pioplus` processes? And restart VSCode

**Comment by toni55** [comment]
There is no "pioplus processes" on my mac.
I have solved the problem with reinstall the platformio-plugin in vscode.
Before i install the plugin, i delete the .platformio folder on my homedir.

thanks

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!
