### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by cpassuel** [platformio/platformio-core#2653]
PIO Core Call Error: "Library Storage: C:\\Users\\Chris\\.platformio\\lib\r\r\nUpdating Adafruit-INA219                 @ 64f4d97f9a     [1.0.4]\r\r\nUninstalling Adafruit-INA219 @ 64f4d97f9a: \t[OK]\r\nLooking for Adafruit-INA219 library in registry\r\n\n\nError: Library `{'requirements': u'1.0.4', 'name': 'Adafruit-INA219'}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'requirements': u'1.0.4', 'name': 'Adafruit-INA219'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
Please run `pio lib -g uninstall Adafruit-INA219` and later `pio lib -g install Adafruit-INA219`.
