### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by lakithaomal** [platformio/platformio-core#2655]
PIO Core Call Error: "The next files/directories have been created in /home/teamlary/Documents/PlatformIO/Projects/lk\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Unknown board ID 'seeeduino_lorawan'"

**Comment by ivankravets** [comment]
Please update dev/platforms and restart VSCode. You can do that via `PIO Home > Platforms > Updates`.
