### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by abis1212** [platformio/platformio-core#2658]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\abishekk\\Documents\\PlatformIO\\Projects\\190606-131921-energia-blink\\platformio.ini, line: 10\n'[env:lpmsp430f449\\n''","args":["File contains no section headers.\nfile: C:\\Users\\abishekk\\Documents\\PlatformIO\\Projects\\190606-131921-energia-blink\\platformio.ini, line: 10\n'[env:lpmsp430f449\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
> File contains no section headers.\nfile: C:\Users\abishekk\Documents\PlatformIO\Projects\190606-131921-energia-blink\platformio.ini

Please fix PIO INI
