### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by leogomide** [platformio/platformio-core#2665]
PIO Core Call Error: "<Exception instance at 0x472df30 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\Usuario\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 50-51: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Should be fixed in the latest version. Could you re-test switching to PIO Core 4.0? See docs https://docs.platformio.org/en/latest/installation.html#development-version

Restart VSCode.
