### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by AOISAMAKK** [platformio/platformio-core#2666]
PIO Core Call Error: "The next files/directories have been created in /home/aoi/Documents/PlatformIO/Projects/190614-111421-arduino-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Could not find a version that satisfies the requirement '~0.3.9' for your system 'linux_x86_64'"

**Comment by ivankravets** [comment]
What is your board?

**Comment by AOISAMAKK** [comment]
> What is your board?

KD233

**Comment by ivankravets** [comment]
What is the name of dev/platform? Which project did you import?

**Comment by ivankravets** [comment]
Please reopen if you still need help
