### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Nolan2011** [platformio/platformio-core#2667]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\zhang\\AppData\\Roaming\\SPB_Data\\Documents\\PlatformIO\\Projects\\UNO\\platformio.ini, line: 10\n'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00''","args":["File contains no section headers.\nfile: C:\\Users\\zhang\\AppData\\Roaming\\SPB_Data\\Documents\\PlatformIO\\Projects\\UNO\\platformio.ini, line: 10\n'\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\
