### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by stick2017** [platformio/platformio-core#2668]
'utf8' codec can't decode byte 0xc6 in position 19: invalid continuation byte

**Comment by ivankravets** [comment]
It should be fixed in the latest PIO Core 4.0. Could you re-test with the latest version? http://docs.platformio.org/en/latest/installation.html#development-version

Please restart VSCode when switching to dev/version of PIO Core.

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by stick2017** [comment]
Thank you. It's settled.
