### ISSUE TITLE
Home: Platforms: Registry

### ISSUE THREAD

**Issue by grey-gray** [platformio/platformio-core#2669]
PIO Core Call Error: "Error: [API] Invalid response: <!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n   \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html>\n<head>\n<title>internet hotspot > login</title>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<meta http-equiv=\"pragma\" content=\"no-cache\" />\n<meta http-equiv=\"expires\" content=\"-1\" />\n<meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0; maximum-scale=1.0;\"/>\n<style type=\"text/css\">\nbody {color: #737373; font-size: 10px; font-family: verdana;}\n\ntextarea,input,select {\nbackground-color: #FDFBFB;\nborder: 1px solid #BBBBBB;\npadding: 2px;\nmargin: 1px;\nfont-size: 14px;\ncolor: #808080;\n}\n\na, a:link, a:visited, a:active { color: #AAAAAA; text-decoration: none; font-size: 10px; }\na:hover { border-bottom: 1px dotted #c1c1c1; color: #AAAAAA; }\nimg {border: none;}\ntd { font-size: 14px; color: #7A7A7A; }\n</style>\n\n</head>\n\n<body>\n\n\t<form name=\"sendin\" action=\"http://10.0.1.1/login\" method=\"post\">\n\t\t<input type=\"hidden\" name=\"username\" />\n\t\t<input type=\"hidden\" name=\"password\" />\n\t\t<input type=\"hidden\" name=\"dst\" value=\"http://api.platformio.org/platforms\" />\n\t\t<input type=\"hidden\" name=\"popup\" value=\"true\" />\n\t</form>\n\t\n\t<script type=\"text/javascript\" src=\"/md5.js\"></script>\n\t<script type=\"text/javascript\">\n\t\n\t</script>\n\n\n<div align=\"center\">\n<a href=\"http://10.0.1.1/login?target=lv&amp;dst=http%3A%2F%2Fapi.platformio.org%2Fplatforms\">Latviski</a>\n</div>\n\n<table width=\"100%\" style=\"margin-top: 10%;\">\n\t<tr>\n\t<td align=\"center\" valign=\"middle\">\n\t\t<div class=\"notice\" style=\"color: #c1c1c1; font-size: 9px\">Please log on to use the internet hotspot service<br />Free trial available, <a style=\"color: #FF8080\"href=\"http://10.0.1.1/login?dst=http%3A%2F%2Fapi.platformio.org%2Fplatforms&amp;username=T-40%3AF0%3A2F%3AAF%3A79%3AFB\">click here</a>.</div><br />\n\t\t<table width=\"280\" height=\"280\" style=\"border: 1px solid #cccccc; padding: 0px;\" cellpadding=\"0\" cellspacing=\"0\">\n\t\t\t<tr>\n\t\t\t\t<td align=\"center\" valign=\"bottom\" height=\"175\" colspan=\"2\">\n\t\t\t\t\t<form name=\"login\" action=\"http://10.0.1.1/login\" method=\"post\"\n\t\t\t\t\t     onSubmit=\"return doLogin()\" >\n\t\t\t\t\t\t<input type=\"hidden\" name=\"dst\" value=\"http://api.platformio.org/platforms\" />\n\t\t\t\t\t\t<input type=\"hidden\" name=\"popup\" value=\"true\" />\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t<table width=\"100\" style=\"background-color: #ffffff\">\n\t\t\t\t\t\t\t\t<tr><td align=\"right\">login</td>\n\t\t\t\t\t\t\t\t\t\t<td><input style=\"width: 80px\" name=\"username\" type=\"text\" value=\"\"/></td>\n\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t<tr><td align=\"right\">password</td>\n\t\t\t\t\t\t\t\t\t\t<td><input style=\"width: 80px\" name=\"password\" type=\"password\"/></td>\n\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t\t<tr><td>&nbsp;</td>\n\t\t\t\t\t\t\t\t\t\t<td><input type=\"submit\" value=\"OK\" /></td>\n\t\t\t\t\t\t\t\t</tr>\n\t\t\t\t\t\t\t</table>\n\t\t\t\t\t</form>\n\t\t\t\t</td>\n\t\t\t</tr>\n\t\t\t<tr><td align=\"center\"><a href=\"http://www.mikrotik.com\" target=\"_blank\" style=\"border: none;\"><img src=\"/img/logobottom.png\" alt=\"mikrotik\" /></a></td></tr>\n\t\t</table>\n\t\n\t<br /><div style=\"color: #c1c1c1; font-size: 9px\">Powered by MikroTik RouterOS</div>\n\t\n\t</td>\n\t</tr>\n</table>\n\n<script type=\"text/javascript\">\n\n</script>\n</body>\n</html>"

**Comment by ivankravets** [comment]
> internet hotspot > login

Bad internet connection.
