### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by josaved-midder** [platformio/platformio-core#2671]
PIO Core Call Error: "The next files/directories have been created in /home/midder/VS Code /Jose Saavedra\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError:"

**Comment by ivankravets** [comment]
Could you provide a full output?

**Comment by ivankravets** [comment]
Please reopen if you still need help
