### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by petrusmuc** [platformio/platformio-core#2673]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: D:\\3D Marlin\\Marlin 2.0.x 32 bit\\Marlin-bugfix-2.0.x-SKR V1.3\\platformio.ini, line: 1\n' #\\n''","args":["File contains no section headers.\nfile: D:\\3D Marlin\\Marlin 2.0.x 32 bit\\Marlin-bugfix-2.0.x-SKR V1.3\\platformio.ini, line: 1\n' #\\n'"],"type":"InvalidProjectConf"}

Any help to solve this will be much appreciated !

Peter

**Comment by ivankravets** [comment]
> File contains no section headers

it seems that you remove all build environments from platformio.ini
