### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ozanoner** [platformio/platformio-core#2678]
PIO Core Call Error: "The next files/directories have been created in /home/ozan/projects/mevoo_ha/blueway-gw-esp32/test/board_test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nProject has been successfully initialized including configuration files for `vscode` IDE.\nUpdating contrib-piohome                 @ 2.1.0          [2.2.0]\nUninstalling contrib-piohome @ 2.1.0: \t[OK]\nCorePackageManager: Installing contrib-piohome @ 2.2.0\nWarning! Package Mirror: ('Connection aborted.', error(0, 'Error'))\nLooking for another mirror...\nWarning! Package Mirror: Got an unrecognized status code '504' when downloaded http://dl.platformio.org/packages/contrib-piohome-2.2.0.tar.gz\nLooking for another mirror...\n\nError: Please read http://bit.ly/package-manager-ioerror\nError: Could not install 'contrib-piohome' with version requirements '2.2.0' for your system 'linux_x86_64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Please check your internet connection and try again. Should work now.
