### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by jgeissler** [platformio/platformio-core#2680]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\PC Portable 1\\Documents\\PlatformIO\\Projects\\190617-155514-arduino-wifiscan\\platformio.ini\n\t[line 16]: '[''","args":["File contains parsing errors: C:\\Users\\PC Portable 1\\Documents\\PlatformIO\\Projects\\190617-155514-arduino-wifiscan\\platformio.ini\n\t[line 16]: '['"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
See error above. You have empty C:\Users\PC Portable 1\Documents\PlatformIO\Projects\190617-155514-arduino-wifiscan\platformio.ini

**Comment by jgeissler** [comment]
PID_v1.h
