### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by osorescu** [platformio/platformio-core#2683]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: C:\\Users\\osorescu\\Documents\\PlatformIO\\Projects\\Arduino_blink\\platformio.ini, line: 11\n' [env:uno]\\n''","args":["File contains no section headers.\nfile: C:\\Users\\osorescu\\Documents\\PlatformIO\\Projects\\Arduino_blink\\platformio.ini, line: 11\n' [env:uno]\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
See error description. You have broken `platformio.ini`.
