### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Luke-Thomas-Wood** [platformio/platformio-core#2686]
PIO Core Call Error: "The next files/directories have been created in /mnt/olympus/Luke/Development/Arduino/Learning_Arduino\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Traceback (most recent call last):\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py\", line 16, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/init.py\", line 96, in cli\n    ide is not None)\n  File \"/home/luke/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/init.py\", line 412, in fill_project_envs\n    with open(join(project_dir, \"platformio.ini\"), \"a\") as f:\nIOError: [Errno 95] Operation not supported: '/mnt/olympus/Luke/Development/Arduino/Learning_Arduino/platformio.ini'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Do you have permissions to this file /mnt/olympus/Luke/Development/Arduino/Learning_Arduino/platformio.ini'?
