### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by Helix70** [platformio/platformio-core#2687]
PIO Core Call Error: "<Exception instance at 0x583ea88 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\lexus\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 808-809: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Fixed in PlatformIO Core 4.0. Please re-test with the latest development version http://docs.platformio.org/en/latest/installation.html#development-version
