### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by lesmalave** [platformio/platformio-core#2692]
Server error: {"message":"[Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\\\Users\\\\luisb\\\\Documents\\\\PlatformIO\\\\Projects\\\\190530-143708-nucleo_f103rb'","args":[2,"El sistema no puede encontrar el archivo especificado"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Did you remove this folder `C:\\Users\\luisb\\Documents\\PlatformIO\\Projects\\190530-143708-nucleo_f103rb` from a system while loading PIO Home? Try to reopen PIO Home tab. Should be fixed.
