### ISSUE TITLE
y

### ISSUE THREAD

**Issue by asiongtobing** [platformio/platformio-core#2695]
PIO Core Call Error: "PlatformManager: Installing timsp430\nDownloading\nDownloading\nUnpacking\nUnpacking\ntimsp430 @ 2.0.6 has been successfully installed!\nPackageManager: Installing toolchain-timsp430 @ ~1.40603.0\n\nError: Could not find a version that satisfies the requirement '~1.40603.0' for your system 'linux_aarch64'"

**Comment by ivankravets** [comment]
Duplicate
