### ISSUE TITLE
PLATFORMIO_CORE_DIR environmental variable unused

### ISSUE THREAD

**Issue by stawiski** [platformio/platformio-core#2697]
### Configuration

**Operating system**: Windows 10 64bit
**Python**: Python 2.7.16 (v2.7.16:413a49145e, Mar  4 2019, 01:37:19) [MSC v.1500 64 bit (AMD64)] on win32
**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.6.7

### Description of problem

According to documentation [https://docs.platformio.org/en/latest/projectconf/section_platformio.html#core-dir](url) PlatformIO uses environmental variable `PLATFORMIO_CORE_DIR` to determine the main directory where the platforms, packages, libraries, etc are installed.

While in fact `home_dir` is used and no reference to `PLATFORMIO_CORE_DIR` is in the code.

#### Steps to Reproduce

1. Set up environmental variable (Windows) `PLATFORMIO_CORE_DIR`
2. Try to install new platform e.g. `teensy`
3. It will be installed under `home_dir` instead of `core_dir`

### Additional info

I found the issue trying to use PlatformIO on Jenkins server, which runs under some system username.
It tries to install platforms and libraries under
`C:\Windows\system32\config\systemprofile\.platformio\`
path, as that's system username profile path, which then leads to problems like
`arm-none-eabi-g++: error: CreateProcess: No such file or directory`.

**Comment by ivankravets** [comment]
You use the documentation for PlatformIO Core 4.0 but installed PlatformIO Core 3.0. The final release of PlatformIO Core 4.0 is coming this week. See stable docs https://docs.platformio.org/en/stable/
