### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by sneharankhambe13** [platformio/platformio-core#2699]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\123\\Documents\\PlatformIO\\Projects\\home automation\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing espressif8266\r\nDownloading...\r\nUnpacking...\r\nespressif8266 @ 2.2.2 has been successfully installed!\r\nPackageManager: Installing toolchain-xtensa @ <3\r\r\nDownloading...\r\nWarning! Package Mirror: (\"Connection broken: error(10053, 'An established connection was aborted by the software in your host machine')\", error(10053, 'An established connection was aborted by the software in your host machine'))\r\nLooking for another mirror...\r\nDownloading...\r\nWarning! Package Mirror: (\"Connection broken: error(10053, 'An established connection was aborted by the software in your host machine')\", error(10053, 'An established connection was aborted by the software in your host machine'))\r\nLooking for another mirror...\n\nError: Please read http://bit.ly/package-manager-ioerror\r\nError: Please read http://bit.ly/package-manager-ioerror\r\nError: Could not install 'toolchain-xtensa' with version requirements '<3' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
> Connection broken: error(10053, 'An established connection was aborted by the software in your host machine

Please check your internet connection.
