### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by caiosignor** [platformio/platformio-core#2706]
PIO Core Call Error: "The next files/directories have been created in /home/ragnar/Documents/PlatformIO/Projects/190625-131010-esp8266-nonos-sdk-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\nError: Could not install 'toolchain-xtensa' with version requirements '~1.40802.0' for your system 'linux_x86_64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
https://bintray.com/platformio/dl-packages/toolchain-xtensa#files

Please check your antivirus tools, maybe they block PlatformIO.
