### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Erica1627** [platformio/platformio-core#2717]
PIO Core Call Error: "Library Storage: /home/nildo/Documents/PlatformIO/Projects/testandoEthernet/.piolibdeps\nLibraryManager: Installing id=1484\nDownloading\nDownloading\n\nError: Traceback (most recent call last):\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py\", line 120, in main\n    cli(None, None, None)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py\", line 26, in new_func\n    return f(get_current_context().obj, *args, **kwargs)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/lib.py\", line 103, in lib_install\n    library, silent=silent, interactive=interactive, force=force)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/lib.py\", line 352, in install\n    force=force)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 723, in install\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/lib.py\", line 213, in _install_from_piorepo\n    if app.get_setting(\"enable_ssl\") else dl_data['url'], requirements)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 508, in _install_from_url\n    dlpath = self.download(url, tmp_dir, sha1)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 185, in download\n    fd.start(with_progress=with_progress)\n  File \"/home/nildo/.platformio/penv/local/lib/python2.7/site-packages/platformio/downloader.py\", line 85, in start\n    f.write(next(itercontent))\nStopIteration\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> An unexpected error occurred

Please check your internet connection and try again.
