### ISSUE TITLE
Home: The system cannot find the file specified

### ISSUE THREAD

**Issue by herry93** [platformio/platformio-core#2718]
Server error: {"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\rnd01\\\\Documents\\\\PlatformIO'","args":[2,"The system cannot find the file specified"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
It seems that your antivirus tools remove files which PlatformIO Core create.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Comment by ivankravets** [comment]
Do you have an antivirus tool in a system?
