### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by lcary132** [platformio/platformio-core#2719]
PIO Core Call Error: "<Exception instance at 0x5ee1f08 with str error:\n Traceback (most recent call last):\n  File \"C:\\Users\\lyc\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 69-70: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
It was fixed in PlatformIO Core 4.0. Could you re-test with https://community.platformio.org/t/platformio-core-4-0-beta/8304?
