### ISSUE TITLE
monitor_port wildcard not working

### ISSUE THREAD

**Issue by BbIKTOP** [platformio/platformio-core#2721]
**Operating system**:

macOS 10.14.5
```
viktor@Black-pro-4:~/Documents/PlatformIO/Projects/Test $ uname -a
Darwin Black-pro-4.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
viktor@Black-pro-4:~/Documents/PlatformIO/Projects/Test $ ~/.platformio/penv/bin/platformio --version
PlatformIO, version 3.6.7
viktor@Black-pro-4:~/Documents/PlatformIO/Projects/Test $ cat platformio.ini
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
upload_port = /dev/cu.wchusbser*
upload_speed = 921600
monitor_speed = 115200
monitor_port = /dev/cu.wchusbser*
viktor@Black-pro-4:~/Documents/PlatformIO/Projects/Test $ ls -l /dev/cu.wchusbser*
crw-rw-rw-  1 root  wheel   19,  29 Jun 28 20:17 /dev/cu.wchusbserial14140
viktor@Black-pro-4:~/Documents/PlatformIO/Projects/Test $ ~/.platformio/penv/bin/platformio device monitor
could not open port '/dev/cu.wchusbser*': [Errno 2] could not open port /dev/cu.wchusbser*: [Errno 2] No such file or directory: '/dev/cu.wchusbser*'
viktor@Black-pro-4:~/Documents/PlatformIO/Projects/Test $
```

### Description of problem
According to the [docs] (https://docs.platformio.org/en/latest/projectconf/section_env_monitor.html) monitor_port parameter shall support wildcards. But it does not. Hardware used is Wemos D1 mini with CH341 UART-USB chip

#### Steps to Reproduce

1. Create empty arduino esp8266 project (ESP-12e)
2. Specify path with wildcard for monitor_port
3. Open monitor
4. Observe "No such file or directory" message

### Actual Results
errno=2 (ENOENT, pathname not found)

### Expected Results
Wildcard replaced with the actual port (probably the first found one)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```
[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino
upload_port = /dev/cu.wchusbser*
upload_speed = 921600
monitor_speed = 115200
monitor_port = /dev/cu.wchusbser*

```

**Source file to reproduce issue:**
```
#include <Arduino.h>

void setup()
{
  Serial.begin(115200);
  Serial.println("Started");
}
void loop()
{
  Serial.println("Running");
  delay(3000);
}
```

Code uploading works fine

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/serial-monitor-cannot-find-port/8444/6?u=ivankravets
