### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by zufrimohammad** [platformio/platformio-core#2722]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /Users/macbook/Documents/PlatformIO/Projects/ethernet/platformio.ini, line: 11\n'env:nucleo_f767zi]\\n''","args":["File contains no section headers.\nfile: /Users/macbook/Documents/PlatformIO/Projects/ethernet/platformio.ini, line: 11\n'env:nucleo_f767zi]\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\nfile: /Users/macbook/Documents/PlatformIO/Projects/ethernet/platformio.ini

Please fix INI file
