### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by vitek331** [platformio/platformio-core#2725]
PIO Core Call Error: "<Exception instance at 0x4dec208 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57-62: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Should be fixed in PlatformIO Core 4.0. Please re-test with https://community.platformio.org/t/platformio-core-4-0-beta/8304
