### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by meinci** [platformio/platformio-core#2726]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\Mehmet\\Documents\\PlatformIO\\Projects\\Neues Arduino Projekt\\platformio.ini\n\t[line 16]: '1909\\n'\n\t[line 17]: 'Nextion\\n''","args":["File contains parsing errors: C:\\Users\\Mehmet\\Documents\\PlatformIO\\Projects\\Neues Arduino Projekt\\platformio.ini\n\t[line 16]: '1909\\n'\n\t[line 17]: 'Nextion\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains parsing errors: C:\Users\Mehmet\Documents\PlatformIO\Projects\Neues Arduino Projekt\platformio.ini
