### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by SpeziMM** [platformio/platformio-core#2728]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains no section headers.\nfile: /Users/magnusmuller/Documents/PlatformIO/Projects/Test/platformio.ini, line: 11\n'common_env_data]\\n''","args":["File contains no section headers.\nfile: /Users/magnusmuller/Documents/PlatformIO/Projects/Test/platformio.ini, line: 11\n'common_env_data]\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
File contains no section headers.\nfile: /Users/magnusmuller/Documents/PlatformIO/Projects/Test/platformio.ini,
