### ISSUE TITLE
Home: Could not load platform updates

### ISSUE THREAD

**Issue by EBZ-Krisemendt** [platformio/platformio-core#2730]
PIO Core Call Error: "Error: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'returncode': 128, 'err': \"remote: Repository not found.\\nfatal: repository 'https://github.com/atanisoft/platform-espressif32/' not found\\n\", 'out': ''})"

**Comment by ivankravets** [comment]
epository not found.\nfatal: repository 'https://github.com/atanisoft/platform-espressif32/'
