### ISSUE TITLE
Generate manpages with Sphinx

### ISSUE THREAD

**Issue by Yuri-M-Dias** [platformio/platformio-core#2731]
- [X] **Feature Request**

Hello, I'd like to first thank you guys for this awesome project!

I want to add manpage generation to the CLI core. 

I was going to make a completions plugin to get completions to work on the fish shell, as that's what I used daily, but I realized that I don't need to do that if there's already a manpage for the project, as it's possible to automatically parse manpages for command completion, see [here](https://github.com/fish-shell/fish-shell/issues/4621) for the idea.

Sphinx seems to already have this prepared on the docs project folder, it'd be a question of adding it to `tox.ini` and then creating a script to bind it to the OS. [docs](https://www.sphinx-doc.org/en/master/man/index.html?highlight=man)

I'm willing to make a pull request is that's OK.

**Comment by ivankravets** [comment]
It works out of the box, please clone this repo, navigate to `/docs` and rune `make man`.
