### ISSUE TITLE
Docs: missing comma in env.Replace in custom upload example

### ISSUE THREAD

**Issue by fredvik** [platformio/platformio-core#2735]
### Description of problem
Example of custom upload tool in the doc page on advanced_scripting does not work due to a typo.

#### Steps to Reproduce
The example code snippet for custom upload on the advanced_scripting doc page does not run as written. Lines 488-491 contains the code:
```
env.Replace(
    UPLOADER="executable or path to executable"
    UPLOADCMD="$UPLOADER $UPLOADERFLAGS $SOURCE"
)
```

This produces an error as a comma is missing. The correct code would be:
```
env.Replace(
    UPLOADER="executable or path to executable",
    UPLOADCMD="$UPLOADER $UPLOADERFLAGS $SOURCE"
)
```

**Comment by ivankravets** [comment]
Thanks, fixed!
