### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by hongnhan100** [platformio/platformio-core#2738]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\nhanbms\\Documents\\PlatformIO\\Projects\\ESP32Cemera\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\r\n\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nError: Unknown board ID 'esp32cam'\r\n [ERROR] Took 0.90 seconds"

**Comment by ivankravets** [comment]
PIO Home > Platforms > Updates

Try again.
