### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by RoliAlpha** [platformio/platformio-core#2742]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\jtext\\Documents\\PlatformIO\\Projects\\MqttSNComAppDemo\\platformio.ini\n\t[line 16]: 'Ethernet\\n''","args":["File contains parsing errors: C:\\Users\\jtext\\Documents\\PlatformIO\\Projects\\MqttSNComAppDemo\\platformio.ini\n\t[line 16]: 'Ethernet\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2732
