### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by juergenschubert** [platformio/platformio-core#2745]
PIO Core Call Error: "The next files/directories have been created in /Users/juergenschubert/Documents/ESP8266/PlatformIO/Projects/ESP32 CAM/ESP32_cam\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'esp32cam'\n========================== [ERROR] Took 1.85 seconds =========================="

**Comment by ivankravets** [comment]
PIO Home > Platforms > Updates.

Try agian.
