### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by hajdurobert92** [platformio/platformio-core#2746]
PIO Core Call Error: "<Exception instance at 0x66954c8 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 60: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Should be fixed in PlatformIO Core 4.0. Please re-test with https://community.platformio.org/t/platformio-core-4-0-beta/8304/3
