### ISSUE TITLE
Home: Error occurred while requesting content from https://gitlab.com/BlackEdder/painlessMesh/raw/master/library.json

### ISSUE THREAD

**Issue by prlombaard** [platformio/platformio-core#2747]
HTTPSConnectionPool(host='gitlab.com', port=443): Max retries exceeded with url: /BlackEdder/painlessMesh/raw/master/library.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000087D4F28>, 'Connection to gitlab.com timed out. (connect timeout=2)'))

**Comment by ivankravets** [comment]
> 'Connection to gitlab.com timed out. (connect timeout=2)

Please try again after PIO Home restart
