### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by SSilverHawk** [platformio/platformio-core#2752]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\suking\\Documents\\PlatformIO\\Projects\\190707-105949-esp12e\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not find a version that satisfies the requirement '1.20401.3-puya' for your system 'windows_x86'"

**Comment by ivankravets** [comment]
`1.20401.3-puya` what is it?
