### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by actionaer** [platformio/platformio-core#2758]
Server error: {"message":"[Error 2] Das System kann die angegebene Datei nicht finden: u'C:\\\\Users\\\\akkiz\\\\Documents\\\\PlatformIO'","args":[2,"Das System kann die angegebene Datei nicht finden"],"type":"WindowsError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
