### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/1/135/OLED_featherwing.ino

### ISSUE THREAD

**Issue by Darlingtone** [platformio/platformio-core#2762]
HTTPConnectionPool(host='dl.platformio.org', port=80): Read timed out. (read timeout=2)

is there a way to increase the timeout, for some of us our internet/device
 is not that fast

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2753
