### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by juergenschubert** [platformio/platformio-core#2768]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/juergenschubert/Documents/ESP8266/PlatformIO/Projects/ESP32 CAM/CameraWebServer'","type":"OSError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
