### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by flexiti** [platformio/platformio-core#2769]
PIO Core Call Error: "Platform C:\\Users\\mariuszb\\.platformio\\platforms\\espressif32@1.2.0\n--------\nUpdating espressif32                     @ 1.2.0          [Detached]\nUpdating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]\nUpdating tool-openocd-esp32              @ 1.1000.20190313[1.1000.20190625]\r\nUninstalling tool-openocd-esp32 @ 1.1000.20190313: \t[OK]\nPackageManager: Installing tool-openocd-esp32 @ 1.1000.20190625\r\nDownloading...\nUnpacking...\nWarning! Package Mirror: [Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 'C:\\\\Users\\\\mariuszb\\\\.platformio\\\\packages\\\\_tmp_installing-bzdnvl-package\\\\tool-openocd-esp32-windows_x86-1.1000.20190625.tar.gz'\nLooking for another mirror...\nDownloading...\nUnpacking...\nWarning! Package Mirror: [Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 'C:\\\\Users\\\\mariuszb\\\\.platformio\\\\packages\\\\_tmp_installing-vv2ypl-package\\\\tool-openocd-esp32-windows_x86-1.1000.20190625.tar.gz'\nLooking for another mirror...\n\n\n[Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 'C:\\\\Users\\\\mariuszb\\\\.platformio\\\\packages\\\\_tmp_installing-bzdnvl-package\\\\tool-openocd-esp32-windows_x86-1.1000.20190625.tar.gz' \nPlease manually remove the file `C:\\Users\\mariuszb\\.platformio\\packages\\_tmp_installing-bzdnvl-package\\tool-openocd-esp32-windows_x86-1.1000.20190625.tar.gz`\n[Error 5] Odmowa dostępu: 'C:\\\\Users\\\\mariuszb\\\\.platformio\\\\packages\\\\_tmp_installing-bzdnvl-package' \nPlease manually remove the file `C:\\Users\\mariuszb\\.platformio\\packages\\_tmp_installing-bzdnvl-package`\n[Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 'C:\\\\Users\\\\mariuszb\\\\.platformio\\\\packages\\\\_tmp_installing-vv2ypl-package\\\\tool-openocd-esp32-windows_x86-1.1000.20190625.tar.gz' \nPlease manually remove the file `C:\\Users\\mariuszb\\.platformio\\packages\\_tmp_installing-vv2ypl-package\\tool-openocd-esp32-windows_x86-1.1000.20190625.tar.gz`\n[Error 5] Odmowa dostępu: 'C:\\\\Users\\\\mariuszb\\\\.platformio\\\\packages\\\\_tmp_installing-vv2ypl-package' \nPlease manually remove the file `C:\\Users\\mariuszb\\.platformio\\packages\\_tmp_installing-vv2ypl-package`\nError: Could not install 'tool-openocd-esp32' with version requirements '1.1000.20190625' for your system 'windows_amd64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
> [Error 32] Proces nie może uzyskać dostępu do pliku, ponieważ jest on używany przez inny proces: 

It seems like your antivirus tools block PlatformIO Package Manager.
