### ISSUE TITLE
Home: Could not load PIO Account information

### ISSUE THREAD

**Issue by TD-er** [platformio/platformio-core#2772]
PIO Core Call Error: "No JSON object could be decoded"

This is in my PlatformIO Home tab in VS code.
I cannot login to my PIO account via this tab.
![image](https://user-images.githubusercontent.com/3751318/60923566-7781b600-a29f-11e9-9072-6d3c7f574d67.png)

Running: 
- Home 2.2.0
- Core 4.0.0rc5

**Comment by ivankravets** [comment]
Thanks for the report! See https://github.com/platformio/platformio-core/issues/2748
