### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by kkaleta** [platformio/platformio-core#2773]
PIO Core Call Error: "The next files/directories have been created in C:\\Users\\kkaleta\\Documents\\PlatformIO\\Projects\\esp32_stepper\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\n\nError: Could not install 'framework-arduinoespressif32' with version requirements '~2.10002.190416' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Check antivirus tools, it seems they block PlaformIO Package manager
