### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by martinjger** [platformio/platformio-core#2774]
Server error: {"message":"Invalid `platformio.ini`, project configuration file: 'File contains parsing errors: C:\\Users\\jutta\\Documents\\PlatformIO\\Projects\\190708-140550-arduino-wifiscan\\platformio.ini\n\t[line 14]: 'c\\n''","args":["File contains parsing errors: C:\\Users\\jutta\\Documents\\PlatformIO\\Projects\\190708-140550-arduino-wifiscan\\platformio.ini\n\t[line 14]: 'c\\n'"],"type":"InvalidProjectConf"}

**Comment by ivankravets** [comment]
"Invalid platformio.ini, project configuration file: 'File contains parsing errors: C:\Users\jutta\Documents\PlatformIO\Projects\190708-140550-arduino-wifiscan\platformio.ini
