### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by zhangzq71** [platformio/platformio-core#2775]
PIO Core Call Error: "The current working directory /home/scutech/Documents/PlatformIO/Projects/testcm3 will be used for the project.\n\nThe next files/directories have been created in /home/scutech/Documents/PlatformIO/Projects/testcm3\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing genericSTM32F103RB (platform: ststm32; board: genericSTM32F103RB; framework: libopencm3)\n----------------------------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103RB.html\nPLATFORM: ST STM32 5.4.3 > STM32F103RB (20k RAM. 128k Flash)\nHARDWARE: STM32F103RBT6 72MHz, 20KB RAM, 128KB Flash\nDEBUG: Current (blackmagic) External (blackmagic, jlink, stlink)\nPACKAGES: framework-libopencm3 1.1.0, toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\nIOError: [Errno 2] No such file or directory: '/home/scutech/.platformio/packages/framework-libopencm3/lib/Makefile':\n  File \"/home/scutech/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/main.py\", line 126:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"/home/scutech/.platformio/platforms/ststm32/builder/main.py\", line 91:\n    target_elf = env.BuildProgram()\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/home/scutech/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 112:\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"/home/scutech/.platformio/penv/local/lib/python2.7/site-packages/platformio/builder/tools/platformio.py\", line 326:\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 604:\n    return method(*args, **kw)\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"/home/scutech/.platformio/packages/tool-scons/script/../engine/SCons/Script/SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"/home/scutech/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 181:\n    get_source_files(root_dir)\n  File \"/home/scutech/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 100:\n    mkdata = parse_makefile_data(join(src_dir, \"Makefile\"))\n  File \"/home/scutech/.platformio/platforms/ststm32/builder/frameworks/libopencm3/libopencm3.py\", line 77:\n    with open(makefile) as f:\n==================================== [ERROR] Took 0.43 seconds ===================================="

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/issues/232
