### ISSUE TITLE
Home: Could not initialize project with Rasperry Pi 3 B

### ISSUE THREAD

**Issue by Jeronimo016** [platformio/platformio-core#2782]
PIO Core Call Error: "<Exception instance at 0x5b43b48 with str error:\n Traceback (most recent call last):\n  File \"C:\\.platformio\\packages\\contrib-pysite\\twisted\\python\\reflect.py\", line 448, in safe_str\n    return str(o)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xf3' in position 60: ordinal not in range(128)\n>"

**Comment by ivankravets** [comment]
Do you use the latest PIO Core 4.0?

**Comment by Jeronimo016** [comment]
How can i see if I use the latest PIO Core 4.0?

**Comment by ivankravets** [comment]
On the PIO Home > Welcome page.

**Comment by Jeronimo016** [comment]
I just updated it but now the progarm has a new error:
PIO Core Call Error: "The current working directory C:\\Users\\Jerónimo Torres\\Documents\\PlatformIO\\Projects\\ppppppppppp will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\Jerónimo Torres\\Documents\\PlatformIO\\Projects\\ppppppppppp\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: PlatformIO temporary does not support cross-compilation for WiringPi framework. Please use PIO Core directly on Raspberry Pi"

**Comment by ivankravets** [comment]
> PlatformIO temporary does not support cross-compilation for WiringPi framework. Please use PIO Core directly on Raspberry Pi

https://github.com/platformio/platform-linux_arm/issues/2
