### ISSUE TITLE
Enhancement: Don't stop piohome if not needed

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-core#2784]
So, on Windows (and apparently linux, although I couldn't reproduce it), it seems that if there are no updates to the core, or `contrib-piohome`, that the piohome server is still stopped. i.e. choosing the 'Update all' option in the VScode extension, or even running   `pio update --core-packages` when there are no updates present will result in a `Reconnecting` message if the PIO Home tab is open, resulting in the user needed to close the tab, and reopen PIO Home. 

Is it possible to make it so that this does not occur if no dependencies are altered/affected? 

It might also be worth adding a message to the update routine to indicate that PIO Home will need to be reloaded/reopened if it was indeed running and closed, or perhaps automatically restart it if it were previously running?

https://github.com/platformio/platformio-core/blob/fee748d38400db63de403d8279ac44b05a0834da/platformio/managers/core.py#L103

Forum ref: https://community.platformio.org/t/reconnecting-message/8654

**Comment by ivankravets** [comment]
Thanks! 😊
