### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by dr-apple** [platformio/platformio-core#2787]
Server error: {"args":["/Users/drapple/.platformio/platforms/espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf/platform.json"],"message":"Could not load broken JSON: /Users/drapple/.platformio/platforms/espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf/platform.json","type":"InvalidJSONFile"}

**Comment by ivankravets** [comment]
Please remove `/Users/drapple/.platformio/platforms/espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf/` and try to build project again.
