### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by Darlingtone** [platformio/platformio-core#2791]
PIO Core Call Error: "Error: [API] Could not connect to PlatformIO API Service. Please try later."

Am getting this Error a lot, installing Library is a hit or miss. i have to retry and retry sometimes for hours before i can install a library

**Comment by ivankravets** [comment]
> "Error: [API] Could not connect to PlatformIO API Service. Please try later."

Do you have unstable internet connection?

**Comment by Darlingtone** [comment]
My internet is fairly stable, that was the first thing i checked given the nature of the error message

**Comment by ivankravets** [comment]
Could you run in PlatformIO IDE Terminal:
```
python -c "import requests; print(requests.get('https://api.platformio.org/lib/stats').json())"
```

Try to run this command multiple times. Does it work every time?

**Comment by ivankravets** [comment]
Please reopen if you still need help
