### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by bikevit2008** [platformio/platformio-core#2793]
PIO Core Call Error: "Platform /Users/vitalijsatilov/.platformio/platforms/espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d\n--------\nUpdating espressif32                     @ 839ae90        [Up-to-date]\nUpdating tool-esptoolpy                  @ 1.20600.0      [Up-to-date]\nUpdating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]\nUpdating framework-arduinoespressif32    @ 812d131        [7dbda49]\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
It seems that you did change in the master `framework-arduinoespressif32` repository. Please remove this package from `/Users/vitalijsatilov/.platformio/packages` and start build again.
