### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by salperes** [platformio/platformio-core#2794]
PIO Core Call Error: "The current working directory C:\\Users\\salpe\\OneDrive\\Documents\\PlatformIO\\Projects\\test-non-arduino-framework will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\salpe\\OneDrive\\Documents\\PlatformIO\\Projects\\test-non-arduino-framework\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing nanoatmega328new (platform: atmelavr; board: nanoatmega328new; framework: simba)\n\nPackageManager: Installing framework-simba @ >=7.0.0\nDownloading\nDownloading\nUnpacking\nUnpacking\nframework-simba @ 15.0.3 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/nanoatmega328new.html\nPLATFORM: Atmel AVR 1.14.0 > Arduino Nano ATmega328 (New Bootloader)\nHARDWARE: ATMEGA328P 16MHz, 2KB RAM, 30KB Flash\nPACKAGES: toolchain-atmelavr 1.50400.190710 (5.4.0), framework-simba 15.0.3\nValueError: BOARD nanoatmega328new is not supported by Simba.:\n  File \"C:\\Users\\salpe\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 126:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"C:\\Users\\salpe\\.platformio\\platforms\\atmelavr\\builder\\main.py\", line 154:\n    target_elf = env.BuildProgram()\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"C:\\Users\\salpe\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 112:\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"C:\\Users\\salpe\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 326:\n    SConscript(env.GetFrameworkScript(f), exports=\"env\")\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 604:\n    return method(*args, **kw)\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"C:\\Users\\salpe\\.platformio\\platforms\\atmelavr\\builder\\frameworks\\simba.py\", line 60:\n    [env.subst(join(\"$PLATFORMFW_DIR\", \"make\", \"platformio.sconscript\"))])\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 604:\n    return method(*args, **kw)\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"C:\\Users\\salpe\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"C:\\Users\\salpe\\.platformio\\packages\\framework-simba\\make\\platformio.sconscript\", line 4187:\n    raise ValueError(\"BOARD {} is not supported by Simba.\".format(board))\n [ERROR] Took 151.25 seconds"

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-atmelavr/commit/acca29b9b3864a869d8bfc7456915d2e4c421e8f
