### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by GaryMatthews** [platformio/platformio-core#2797]
PIO Core Call Error: "The current working directory /home/gary/Documents/PlatformIO/Projects/Cam will be used for the project.\n\nThe next files/directories have been created in /home/gary/Documents/PlatformIO/Projects/Cam\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp32cam (platform: espressif32; board: esp32cam; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'esp32cam'\n========================== [ERROR] Took 0.23 seconds =========================="

**Comment by ivankravets** [comment]
PIO Home > Platforms > Updates. Restart VSCode.
