### ISSUE TITLE
Servo.h not found - Arduino

### ISSUE THREAD

**Issue by anthgur** [platformio/platformio-core#28]
I can't seem to find the [Arduino Servo](http://arduino.cc/en/Reference/Servo) library in the registry. I'm not sure if this is related to #23. How should I go about including the Arduino core libraries?

Thanks

**Comment by civet** [comment]
platformio version 4.1.0 
Servo.h not found (for arduino) again.

**Comment by etulupov** [comment]
@civet You should add Servo library in platformio.ini
```
lib_deps =
     arduino-libraries/Servo @ 1.1.8
```
