### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by vicpb** [platformio/platformio-core#2809]
PIO Core Call Error: "Library Storage: /home/vicpb/.platformio/lib\nLibraryManager: Installing VarSpeedServo\n\n\nError: Traceback (most recent call last):\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/platformio/__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/platformio/commands/lib.py\", line 149, in lib_install\n    force=force)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/platformio/managers/lib.py\", line 353, in install\n    force=force)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/platformio/managers/package.py\", line 724, in install\n    track=True)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/site-packages/platformio/managers/package.py\", line 502, in _install_from_url\n    shutil.copytree(_url, tmp_dir)\n  File \"/home/vicpb/.platformio/penv/lib/python3.6/shutil.py\", line 315, in copytree\n    names = os.listdir(src)\nFileNotFoundError: [Errno 2] No such file or directory: 'home/vidpb/Documentos/VarSpeedServo/'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
It seems that you removed `home/vidpb/Documentos/VarSpeedServo/`
