### ISSUE TITLE
Support for NXP i.MXRT1050-EVK

### ISSUE THREAD

**Issue by jdavid75** [platformio/platformio-core#2813]
- [ ] **Feature Request**.
      Please add support for the NXP i.MXRT1050-EVK
( https://www.nxp.com/support/developer-resources/evaluation-and-development-boards/i.mx-evaluation-and-development-boards/i.mx-rt1050-evaluation-kit:MIMXRT1050-EVK )

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3117
