### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by Eltopinovatif** [platformio/platformio-core#2817]
PIO Core Call Error: "PlatformManager: Installing ESP8266_RTOS_SDK\n\n\nError: VCS: Could not process command ['git', 'clone', '--recursive', '--depth', '1', 'esp8266-rtos-sdk-idf,https://github.com/espressif/ESP8266_RTOS_SDK.git', 'C:\\\\Users\\\\Laptop\\\\.platformio\\\\platforms\\\\_tmp_installing-btozxo-package']"

**Comment by ivankravets** [comment]
> esp8266-rtos-sdk-idf

This is invalid dev/platform. See available https://platformio.org/platforms
