### ISSUE TITLE
Library install-to... option ignores selected library version.

### ISSUE THREAD

**Issue by tavdog** [platformio/platformio-core#2819]
Using PIO Home 2.2.0·Core 4.0.0 on OSX 10.11.6  on VSCode 1.36.1
When trying to install a specific lower version of a library into a specific workspace, PIO ignores the selected version and installs only the latest version of the library into the workspace.

It works fine when installing the library globally.

**Comment by ivankravets** [comment]
Please update core packages via `pio update` command. Restart VSCode.
