### ISSUE TITLE
主页:无法初始化项目

### ISSUE THREAD

**Issue by plnmmnlq** [platformio/platformio-core#2821]
PIO Core Call Error: "The current working directory C:\\Users\\plmlq\\Documents\\PlatformIO\\Projects\\123 will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\plmlq\\Documents\\PlatformIO\\Projects\\123\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Could not install 'toolchain-atmelavr' with version requirements '~1.50400.0' for your system 'windows_amd64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
Please check that antivirus tools do not block PlatformIO package installer.
