### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by greg-wood** [platformio/platformio-core#2826]
PIO Core Call Error: "Platform /Users/greg/.platformio/platforms/espressif32@src-9112e7894fcfd1325e3c29a50a2b0d5d\n--------\nUpdating espressif32                     @ 6a9dbef        [839ae90]\nUpdating tool-esptoolpy                  @ 1.20600.0      [Up-to-date]\nUpdating toolchain-xtensa32              @ 2.50200.80     [Up-to-date]\nUpdating framework-arduinoespressif32    @ 5af0336        [548f712]\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please remove ` /Users/greg/.platformio/platforms/espressif32` and ` /Users/greg/.platformio/packages/framework-arduinoespressif32`. It seems that did modifications in these places.
