### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by PUTTICHAMP** [platformio/platformio-core#2831]
PIO Core Call Error: "The current working directory C:\\Users\\acer\\Documents\\PlatformIO\\Projects\\test cui mag will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\acer\\Documents\\PlatformIO\\Projects\\test cui mag\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing atmelavr\n\n\nError: Detected unknown package 'atmelavr'"

**Comment by ivankravets** [comment]
> Detected unknown package 'atmelavr'

Check you internet connection and firewall

You can try to open PlatformIO IDE Terminal and run `pio platform install atmelavr`
