### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by HorizonMC** [platformio/platformio-core#2832]
PIO Core Call Error: "The current working directory C:\\Users\\User\\Documents\\PlatformIO\\Projects\\cui test mag will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\User\\Documents\\PlatformIO\\Projects\\cui test mag\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'ATmega328P'"

**Comment by ivankravets** [comment]
PlatformIO IDE > PIO Home > Platforms > Updates. Restart VSCode. Should work now.
