### ISSUE TITLE
Home: Platforms: Registry

### ISSUE THREAD

**Issue by missingxin** [platformio/platformio-core#2833]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py\", line 169, in platform_search\n    expose_packages=False))\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py\", line 126, in _get_registry_platform_data\n    for p in _get_registry_platforms():\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py\", line 54, in _get_registry_platforms\n    platforms = util.get_api_result(\"/platforms\", cache_valid=\"7d\")\n  File \"/Users/jo/.platformio/penv/lib/python2.7/site-packages/platformio/util.py\", line 383, in get_api_result\n    return json.loads(result)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/json/__init__.py\", line 339, in loads\n    return _default_decoder.decode(s)\n  File \"/Users/jo/.platformio/penv/lib/python2.7/json/decoder.py\", line 364, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/Users/jo/.platformio/penv/lib/python2.7/json/decoder.py\", line 382, in raw_decode\n    raise ValueError(\"No JSON object could be decoded\")\nValueError: No JSON object could be decoded\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
It seems like something went wrong with PIO Registry. Please open PlatformIO IDE Terminal, type `pio update`, restart VSCode. Should work.
