### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by SrGeek** [platformio/platformio-core#2836]
PIO Core Call Error: "The current working directory C:\\Users\\Daddo\\Documents\\PlatformIO\\Projects\\190725-124345-arduino-internal-libs will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Daddo\\Documents\\PlatformIO\\Projects\\190725-124345-arduino-internal-libs\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing uno (platform: atmelavr; framework: arduino; board: uno)\r\n--------------------------------------------------------------------------------\r\nCorePackageManager: Installing tool-scons @ ~3.30005.0\r\ntool-scons @ 3.30005.0 has been successfully installed!\r\nUninstalling tool-scons @ 2.20501.7: \t[OK]\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/uno.html\r\nPLATFORM: Atmel AVR 1.15.0 > Arduino Uno\r\nHARDWARE: ATMEGA328P 16MHz, 2KB RAM, 31.50KB Flash\r\nPACKAGES: toolchain-atmelavr 1.50400.190710 (5.4.0), framework-arduinoavr 4.1.1\r\nConverting ChatServer.ino\r\ncc1plus.exe: fatal error: opening output file C:\\Users\\Daddo\\Documents\\PlatformIO\\Projects\\190725-124345-arduino-internal-libs\\src\\ChatServer.ino.cpp: Permission denied\r\ncompilation terminated.\r\n*** Error 1\r\nAssertionError: :\r\n  File \"C:\\Users\\Daddo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 126:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\Daddo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 605:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\Daddo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\Daddo\\.platformio\\platforms\\atmelavr\\builder\\main.py\", line 155:\r\n    target_elf = env.BuildProgram()\r\n  File \"C:\\Users\\Daddo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\Daddo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 112:\r\n    env.BuildFrameworks(env.get(\"PIOFRAMEWORK\"))\r\n  File \"C:\\Users\\Daddo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\Daddo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 323:\r\n    env.ConvertInoToCpp()\r\n  File \"C:\\Users\\Daddo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\Daddo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piomisc.py\", line 198:\r\n    out_file = c.convert(ino_nodes)\r\n  File \"C:\\Users\\Daddo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piomisc.py\", line 57:\r\n    return self.process(contents)\r\n  File \"C:\\Users\\Daddo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piomisc.py\", line 80:\r\n    assert self._gcc_preprocess(contents, out_file)\r\n========================== [ERROR] Took 5.49 seconds ==========================\r\n\r\n================================== [SUMMARY] ==================================\r\nEnvironment uno           \t[FAILED]\r\nEnvironment megaatmega2560\t[IGNORED]\r\nEnvironment nanoatmega328 \t[IGNORED]\r\nEnvironment leonardo      \t[IGNORED]\r\nEnvironment ethernet      \t[IGNORED]\r\n==================== 1 failed, 0 succeeded in 5.50 seconds ===================="

**Comment by ivankravets** [comment]
> Permission denied

Please check your permissions
