### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by hoekbrwr** [platformio/platformio-core#2837]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: **u'D**:\\\\Leo\\\\Documents\\\\PlatformIO'","type":"WindowsError"}
I have checked the folder and the meant file exists, but the name starts with strange characters in the error report!
On a freshly installed VSC+PIO and platforms Espressif 32 & Espressif 8266 there are access problems.
On another computer with same OS w10-1903 there were not thee kind of problems
I get an error from MS Defender,but that is a thing of MSDef.

**Comment by ivankravets** [comment]
Yes, it looks like your antivirus tools block PlatformO.
