### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Eltopinovatif** [platformio/platformio-core#2838]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\Laptop\\\\.platformio\\\\platforms\\\\ESP8266_RTOS_SDK\\\\platform.json'","type":"IOError"}

**Comment by ivankravets** [comment]
Pelase remove C:\\Users\\Laptop\\.platformio\\platforms\\ESP8266_RTOS_SDK

**Comment by Eltopinovatif** [comment]
Okay Thaks, sucsess..

**Comment by Eltopinovatif** [comment]
Please upgrade the latest version of the ESP8266 SDK RTOS as the original version
