### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by ihavenonick** [platformio/platformio-core#2840]
PIO Core Call Error: "Platform C:\\Users\\Jan\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\n--------\nUpdating espressif8266                   @ 02e2007        [4db7ada]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Did you do any changes to `C:\Users\Jan\.platformio\platforms\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf`? Please remove this folder and start the build again.

**Comment by ihavenonick** [comment]
removed everythink and new installed, no problem anymore
