### ISSUE TITLE
Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by Joob1965** [platformio/platformio-core#2846]
Server error: {"args":[3,"Das System kann den angegebenen Pfad nicht finden"],"message":"[Error 3] Das System kann den angegebenen Pfad nicht finden: u'C:\\\\Users\\\\joach\\\\Documents\\\\PlatformIO\\\\Projects\\\\*.*'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Error 3] Das System kann den angegebenen Pfad nicht f
