### ISSUE TITLE
Private dependency is installed twice if specified with and without `.git`

### ISSUE THREAD

**Issue by Bascy** [platformio/platformio-core#2847]
What kind of issue is this?

- [X] **PlatformIO Core**.

------------------------------------------------------------------

### Configuration

**Operating system**: Win64

**PlatformIO Version** (`platformio --version`): 4.0.1b3

### Description of problem
When specifying a depency on a git repository in one library with `.git` in the "version" and in another dependant library without the `.git` extension, the library is installed twice in the lib_deps folder

#### Steps to Reproduce

So if project A is dependent on lib B and C, and both lib B and C are dependent on lib D, specified as follows:

B:
`    "dependencies": [
        {
            "name": "D",
            "version": "https://github.com/MyName/D.git"
        }`
C:
`    "dependencies": [
        {
            "name": "D",
            "version": "https://github.com/MyName/D"
        }`

### Actual Results
`pio lib install` will install the same version of library D twice, adding the last commithash to the last installment.

### Expected Results
As, apparently, the `.git` extension is added when missing, this should be handled as "already installed"

**Comment by ivankravets** [comment]
We use this "version" as unified ID for custom libs.
