### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mahmoudnr** [platformio/platformio-core#2850]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\Administrator\\\\Documents\\\\PlatformIO'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Do have antivirus tools in a system? They block PlatformIO.

Duplicate of #2321
