### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by YES365** [platformio/platformio-core#2853]
PIO Core Call Error: "The current working directory C:\\Users\\77293\\Documents\\PlatformIO\\Projects\\190802-110806-arduino-blink will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\77293\\Documents\\PlatformIO\\Projects\\190802-110806-arduino-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError:"

**Comment by ivankravets** [comment]
Yes, please add some build envs and source code.
