### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by YES365** [platformio/platformio-core#2854]
PIO Core Call Error: "Downloading...\ntoolchain-atmelavr @ 1.50400.190710 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~2.20501.7\ntool-scons @ 2.20501.7 has been successfully installed!\n======================== [SUCCESS] Took 837.55 seconds ========================\n\r\n================================== [SUMMARY] ==================================\nEnvironment teensy2  \t[SUCCESS]\nEnvironment teensy2pp\t[IGNORED]\nEnvironment teensy30 \t[IGNORED]\nEnvironment teensy31 \t[IGNORED]\nEnvironment teensylc \t[IGNORED]\nEnvironment teensy35 \t[IGNORED]\nEnvironment teensy36 \t[IGNORED]\n======================== 1 succeeded in 837.55 seconds ========================"

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/issues/2853
