### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Commandoser** [platformio/platformio-core#2855]
PIO Core Call Error: "The current working directory C:\\Users\\anzh\\Documents\\PlatformIO\\Projects\\qweqweqweqwew will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\anzh\\Documents\\PlatformIO\\Projects\\qweqweqweqwew\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Unknown board ID 'sodaq_sara'"

**Comment by ivankravets** [comment]
PlatformIO IDE > PIO Home > Platforms > Updates. Restart VSCode. Should work now.
