### ISSUE TITLE
Home: Could not list directory/private/var/folders/8h/cspp2z115d93bf37l4_nstw40000gn/T/AppTranslocation/C0DA81F4-08BE-4FC5-970A-A374EB8F157D

### ISSUE THREAD

**Issue by deamens** [platformio/platformio-core#2862]
Server error: {"args":[34,"Result too large"],"message":"[Errno 34] Result too large: '/private/var/folders/8h/cspp2z115d93bf37l4_nstw40000gn/T/AppTranslocation/C0DA81F4-08BE-4FC5-970A-A374EB8F157D'","type":"OSError"}

**Comment by ivankravets** [comment]
[Errno 34] Result too large: '/private/var/folders/8h/cspp2z115d93bf37l4_nstw40000gn/T/AppTranslocation/C0DA81F4-08BE-4FC5-970A-A374EB8F157D
