### ISSUE TITLE
Digi Xbee3 Board Support 

### ISSUE THREAD

**Issue by tou2** [platformio/platformio-core#2863]
Requesting to the support for Digi Xbee3 with HCS08 CPU up to 50.33 MHz.

The board is a great IoT programmable module using Micropython and it can be configured to communicate with Zigbee 3.0, 802.15.4, DigiMesh® and BLE,.

https://www.digi.com/products/embedded-systems/rf-modules/2-4-ghz-modules/xbee3-zigbee-3#specifications

I would love to help adding them to Platformio.

**Comment by SRGDamia1** [comment]
https://github.com/platformio/platformio-core/issues/728

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platformio-core/issues/728
