### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by helmo-araujo** [platformio/platformio-core#2864]
Server error: {"args":["C:\\Users\\ifc\\.platformio"],"message":"The directory `C:\\Users\\ifc\\.platformio` or its parent directory is not owned by the current user and PlatformIO can not store configuration data.\nPlease check the permissions and owner of that directory.\nOtherwise, please remove manually `C:\\Users\\ifc\\.platformio` directory and PlatformIO will create new from the current user.","type":"HomeDirPermissionsError"}

**Comment by ivankravets** [comment]
Please remove `C:\\Users\\ifc\\.platformio` folder and check permissions.
