### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by pke0515** [platformio/platformio-core#2865]
PIO Core Call Error: "The current working directory /Users/JeongHun/Documents/PlatformIO/Projects/190804-110332-megaADK will be used for the project.\n\nThe next files/directories have been created in /Users/JeongHun/Documents/PlatformIO/Projects/190804-110332-megaADK\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing megaADK (board: megaADK; platform: atmelavr; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\n  File \"/Users/JeongHun/.platformio/platforms/atmelavr/builder/main.py\", line 30\n\n    print \"Please unplug/plug device ...\"\n\n                                        ^\n\nSyntaxError: Missing parentheses in call to 'print'\n\n========================== [ERROR] Took 0.83 seconds =========================="

**Comment by ivankravets** [comment]
You use very old Atmel AVR dev/platform Please run `pio update`.
