### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Abdullah-ece** [platformio/platformio-core#2868]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\Abdullah Al-lababidy\\\\Documents\\\\PlatformIO\\\\Projects\\\\test'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Do have antivirus tools in a system? They block PlatformIO.

Duplicate of #2321
