### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by golfri** [platformio/platformio-core#2870]
Server error: {"args":[2,"Das System kann die angegebene Datei nicht finden"],"message":"[Error 2] Das System kann die angegebene Datei nicht finden: u'C:\\\\Users\\\\wolfi\\\\Downloads\\\\Sonoff-Tasmota-6.6.0\\\\Sonoff-Tasmota-6.6.0'","type":"WindowsError"}

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/issues/2321
