### ISSUE TITLE
Why is pio destroying environment by default?

### ISSUE THREAD

**Issue by nardev** [platformio/platformio-core#2873]
I just installed pio through atom/vscode (same case with both) and completely on the side i tried installing something with pip but with no success.

What happened. The pip put it self in the path and default pip is the one here /home/user/.espressif/python_env/idf4.0_py2.7_env/bin/pip

I’m wondering, who is joking here. Why, by default it can’t be isolated properly. What i’m doing wrong???

btw i'm using linux and latest pio, if that's important at all since it has been like that always.

**Comment by ivankravets** [comment]
It should be in `/home/user/.platformio/penv`. See http://docs.platformio.org/en/latest/installation.html#virtual-environment
