### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by Ducktr00per** [platformio/platformio-core#2888]
PIO Core Call Error: "Library Storage: I:\\OneDrive\\3D Projekte\\dATEIEN\\AM8\\Marlin-bugfix-2.0 - TMC2208 Stepper\\Marlin-bugfix-2.0.x\\.piolibdeps\\megaatmega2560\nUpdating TMCStepper                      @ 0.4.5          [0.4.6]\r\nUninstalling TMCStepper @ 0.4.5: \t[OK]\nLooking for TMCStepper library in registry\nFound: https://platformio.org/lib/show/5513/TMCStepper\nLibraryManager: Installing id=5513 @ 0.4.6\r\nDownloading\nDownloading\nUnpacking\nUnpacking\n\n\nError: Traceback (most recent call last):\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 16, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 252, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 831, in update\n    self.install(name, latest, after_update=True)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 353, in install\n    force=force)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 726, in install\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 214, in _install_from_piorepo\n    if app.get_setting(\"enable_ssl\") else dl_data['url'], requirements)\n  File \"c:\\users\\gabri\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 507, in _install_from_url\n    os.remove(dlpath)\nWindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'I:\\\\OneDrive\\\\3D Projekte\\\\dATEIEN\\\\AM8\\\\Marlin-bugfix-2.0 - TMC2208 Stepper\\\\Marlin-bugfix-2.0.x\\\\.piolibdeps\\\\megaatmega2560\\\\_tmp_installing-lziabj-package\\\\20727.tar.gz'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> WindowsError: [Error 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird:

Something is wrong with OneDrive?
