### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by andrejsv** [platformio/platformio-core#2893]
PIO Core Call Error: "Platform C:\\Users\\andrej\\.platformio\\platforms\\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708cf\n--------\nUpdating espressif8266                   @ 02e2007        [4db7ada]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please remove `C:\Users\andrej\.platformio\platforms\espressif8266@src-6efb4f0f29b812e7c80b1237c4c708c` folder and restrat build
