### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by Darwinian2** [platformio/platformio-core#2894]
PIO Core Call Error: "The current working directory C:\\Users\\edwar\\Documents\\PlatformIO\\Projects\\190811-172048-sipeed-maix-bit-mic will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\edwar\\Documents\\PlatformIO\\Projects\\190811-172048-sipeed-maix-bit-mic\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing sipeed-maix-bit-mic (platform: kendryte210; board: sipeed-maix-bit-mic; framework: arduino)\n-------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'sipeed-maix-bit-mic'\n========================== [ERROR] Took 2.50 seconds =========================="

**Comment by ivankravets** [comment]
PlatformIO IDE > PIO Home > Platforms > Updates. Restart VSCode. Should work now.
