### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by rhallado** [platformio/platformio-core#2899]
PIO Core Call Error: "The current working directory /Users/rhallado/Documents/PlatformIO/Projects/Projeto teste will be used for the project.\n\nThe next files/directories have been created in /Users/rhallado/Documents/PlatformIO/Projects/Projeto teste\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Traceback (most recent call last):\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/commands/init.py\", line 107, in cli\n    pg.generate()\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 102, in generate\n    tpl_vars = self._load_tplvars()\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/ide/projectgenerator.py\", line 55, in _load_tplvars\n    load_project_ide_data(self.project_dir, self.env_name) or {})\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/project/helpers.py\", line 188, in load_project_ide_data\n    from platformio.commands.run import cli as cmd_run\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/__init__.py\", line 15, in <module>\n    from platformio.commands.run.command import cli\n  File \"/Users/rhallado/.platformio/penv/lib/python3.7/site-packages/platformio/commands/run/command.py\", line 15, in <module>\n    from multiprocessing import cpu_count\nModuleNotFoundError: No module named 'multiprocessing'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
```
(py37) /V/S/P/G/p/origin (develop|✚1) $ python --version
Python 3.7.4
(py37) /V/S/P/G/p/origin (develop|✚1) $ python -c "from multiprocessing import cpu_count;print(cpu_count())"
4
```

It seems you have broken Python 3.7 installation. Please re-install with official and remove `/Users/rhallado/.platformio/penv` folder after it. Restart VSCode.
