### ISSUE TITLE
projects_dir invalid values

### ISSUE THREAD

**Issue by soulraven** [platformio/platformio-core#2903]
i get this error,
![image](https://user-images.githubusercontent.com/1303303/63022490-ba8d0580-beab-11e9-9ee3-586bd6d6180b.png)

i have try to update manually the setting but i get:
![image](https://user-images.githubusercontent.com/1303303/63022611-f922c000-beab-11e9-83cf-3de310132d72.png)

is some kind of bug?

**Comment by ivankravets** [comment]
1. Did you set http://docs.platformio.org/en/latest/envvars.html#envvar-PLATFORMIO_SETTING_PROJECTS_DIR ?
2. Does this `project_dir` exist in the system?

**Comment by ivankravets** [comment]
Please reopen if you still need help
