### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Haschmaradi** [platformio/platformio-core#2907]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/hanspeterscheffler/.platformio/platforms/arduino-esp32/platform.json'","type":"IOError"}

**Comment by ivankravets** [comment]
Please remove `/Users/hanspeterscheffler/.platformio/platforms/arduino-esp32` folder and restart IDE
