### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by aldibagas** [platformio/platformio-core#2909]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\PC\\\\Documents\\\\PlatformIO\\\\Projects\\\\190816-173230-arduino-blink'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Do have antivirus tools in a system? They block PlatformIO. 

Duplicate of https://github.com/platformio/platformio-core/issues/2321

**Comment by ivankravets** [comment]
Do have antivirus tools in a system? They block PlatformIO.

Duplicate of #2321
