### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by kotkajorn** [platformio/platformio-core#2911]
PIO Core Call Error: "PlatformManager: Installing platform-quectel\nquectel @ 207b87a has been successfully installed!\nPackageManager: Installing framework-quectel\nframework-quectel @ 3b001cc has been successfully installed!\nPackageManager: Installing toolchain-gccarmnoneeabi @ =1.70201.0\nWarning! Package Mirror: ('Connection aborted.', error(54, 'Connection reset by peer'))\nLooking for another mirror...\n\n\nError: Please read http://bit.ly/package-manager-ioerror\nError: Could not install 'toolchain-gccarmnoneeabi' with version requirements '=1.70201.0' for your system 'darwin_x86_64'.\n\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
> ackage Mirror: ('Connection aborted.', error(54, 'Connection reset by peer')

Please check your internet connection
