### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by kotkajorn** [platformio/platformio-core#2913]
PIO Core Call Error: "PlatformManager: Installing platformio-pkg-framework-arduinosam\nplatformio-pkg-framework-arduinosam @ 5fb4cbe is already installed\n\n\nError: Traceback (most recent call last):\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 700, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 680, in main\n    rv = self.invoke(ctx)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1027, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 873, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 508, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py\", line 302, in platform_install\n    force=force):\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 83, in install\n    p = PlatformFactory.newPlatform(platform_dir)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 260, in newPlatform\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 497, in __init__\n    self._manifest = fs.load_json(manifest_path)\n  File \"/Users/kot/.platformio/penv/lib/python2.7/site-packages/platformio/fs.py\", line 54, in load_json\n    with open(file_path, \"r\") as f:\nIOError: [Errno 2] No such file or directory: '/Users/kot/.platformio/platforms/platformio-pkg-framework-arduinosam/platform.json'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> IOError: [Errno 2] No such file or directory: '/Users/kot/.platformio/platforms/platformio-pkg-framework-arduinosam/platform.json

What is it? Please remove `/Users/kot/.platformio/platforms/platformio-pkg-framework-arduinosam` folder and restart VSCode.
