### ISSUE TITLE
Home: Could not load platform updates

### ISSUE THREAD

**Issue by Qitas** [platformio/platformio-core#2918]
PIO Core Call Error: "Error: VCS: Could not receive an output from `['git', 'branch']` command ({'returncode': 128, 'err': u'fatal: \\xe4\\xb8\\x8d\\xe6\\x98\\xaf\\xe4\\xb8\\x80\\xe4\\xb8\\xaa git \\xe4\\xbb\\x93\\xe5\\xba\\x93\\xef\\xbc\\x88\\xe6\\x88\\x96\\xe8\\x80\\x85\\xe7\\x9b\\xb4\\xe8\\x87\\xb3\\xe6\\x8c\\x82\\xe8\\xbd\\xbd\\xe7\\x82\\xb9 / \\xe7\\x9a\\x84\\xe4\\xbb\\xbb\\xe4\\xbd\\x95\\xe7\\x88\\xb6\\xe7\\x9b\\xae\\xe5\\xbd\\x95\\xef\\xbc\\x89\\n\\xe5\\x81\\x9c\\xe6\\xad\\xa2\\xe5\\x9c\\xa8\\xe6\\x96\\x87\\xe4\\xbb\\xb6\\xe7\\xb3\\xbb\\xe7\\xbb\\x9f\\xe8\\xbe\\xb9\\xe7\\x95\\x8c\\xef\\xbc\\x88\\xe6\\x9c\\xaa\\xe8\\xae\\xbe\\xe7\\xbd\\xae GIT_DISCOVERY_ACROSS_FILESYSTEM\\xef\\xbc\\x89\\xe3\\x80\\x82', 'out': u''})"

**Comment by ivankravets** [comment]
Could you open PlatformIO IDE Terminal and provide output from 
```
pio platform list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
