### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by JuanCentenoPadilla** [platformio/platformio-core#2919]
Server error: {"args":[2,"El sistema no puede encontrar el archivo especificado"],"message":"[Error 2] El sistema no puede encontrar el archivo especificado: u'C:\\\\Users\\\\almacen81\\\\Documents\\\\PlatformIO'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
