### ISSUE TITLE
Home: Could not load boards list

### ISSUE THREAD

**Issue by xyz626813738** [platformio/platformio-core#2922]
PIO Core Call Error: "Error: Traceback (most recent call last):\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 88, in main\n    cli(None, None, None)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 30, in cli\n    return _print_boards_json(query, installed)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 80, in _print_boards_json\n    for board in _get_boards(installed):\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\boards.py\", line 75, in _get_boards\n    return pm.get_installed_boards() if installed else pm.get_all_boards()\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 194, in get_all_boards\n    for board in self.get_registered_boards():\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\platform.py\", line 188, in get_registered_boards\n    return util.get_api_result(\"/boards\", cache_valid=\"7d\")\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 381, in get_api_result\n    result = cc.get(cache_key)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\site-packages\\platformio\\app.py\", line 226, in get\n    return fp.read()\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\codecs.py\", line 686, in read\n    return self.reader.read(size)\n  File \"c:\\users\\86186\\.platformio\\penv\\lib\\codecs.py\", line 492, in read\n    newchars, decodedbytes = self.decode(data, self.errors)\nUnicodeDecodeError: 'utf8' codec can't decode byte 0xeb in position 20: invalid continuation byte\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Could you open PlatformIO IDE Terminal  (PIO Core CLI) and type this command:
```
pio boards
```

Do you see any errors?

**Comment by ivankravets** [comment]
Please reopen if you still need help
