### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by TechnoElectro** [platformio/platformio-core#2923]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[Error 2] The system cannot find the file specified: u'C:\\\\Users\\\\BDB1\\\\Documents\\\\PlatformIO'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321

Could you try to turn off Antivirus tools for PlatformIO? Does it work now?
