### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by cqwuxiaolong** [platformio/platformio-core#2931]
PIO Core Call Error: "The current working directory C:\\Users\\cqwuxiaolong\\Documents\\PlatformIO\\Projects\\190819-233427-esp8266-rtos-sdk-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\cqwuxiaolong\\Documents\\PlatformIO\\Projects\\190819-233427-esp8266-rtos-sdk-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError:"

**Comment by ivankravets** [comment]
Could you provide more details?

**Comment by ivankravets** [comment]
Please reopen if you still need help
