### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by Nollirom** [platformio/platformio-core#2933]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\WSLee\\\\.platformio\\\\platforms\\\\Arduino\\\\platform.json'","type":"IOError"}

**Comment by ivankravets** [comment]
Please remove `C:\\Users\\WSLee\\.platformio\\platforms\\Arduino` folder and restart IDE.

**Comment by Nollirom** [comment]
Thank you for help!! It works :)
