### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by weiwei2** [platformio/platformio-core#2949]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\Leow Cheah Wei\\\\Documents\\\\PlatformIO\\\\Projects\\\\190827-010617-arduino-blink'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
It looks like antivirus tool block PlatformIO.
