### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by DjamTechnologies** [platformio/platformio-core#2950]
PIO Core Call Error: "Library Storage: C:\\Users\\landr\\.platformio\\lib\r\nLooking for SD library in registry\r\nSD\r\n==\r\n#ID: 161\r\nThis library aims to expose a subset of SD card functionality in the form of a higher level 'wrapper' object\r\n\r\nKeywords: sd, card, file, system\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR\r\nAuthors: Adafruit Industries\r\n\r\nSD\r\n==\r\n#ID: 868\r\nEnables reading and writing on SD cards.\r\n\r\nKeywords: data, storage\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, Teensy, TI MSP430\r\nAuthors: Arduino, SparkFun\r\n\r\nSD\r\n==\r\n#ID: 79\r\nThis library aims to expose a subset of SD card functionality in the form of a higher level 'wrapper' object (adaptation for LaunchPad LM4F120 / TM4C123)\r\n\r\nKeywords: sd, card, file, system\r\nCompatible frameworks: Energia\r\nCompatible platforms: TI MSP430, TI Tiva\r\nAuthors: Rei Vilo, William Greiman, SparkFun Electronics\r\n\r\nSD\r\n==\r\n#ID: 5210\r\nSD\r\n\r\nKeywords: sd\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Jackson Lv\r\n\r\nFound: https://platformio.org/lib/show/161/SD\r\nLibraryManager: Installing id=161 @ ^041f788250\r\n\n\nConflict: More than one library has been found by request {\"name\": \"SD\", \"requirements\": \"^041f788250\"}:\r\nAutomatically chose the first available library (use `--interactive` option to make a choice)\r\nError: Could not find a version that satisfies the requirement '^041f788250' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type
```
pio update
```

Restart VScode. Thanks for the report!
