### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by enderjrios** [platformio/platformio-core#2954]
PIO Core Call Error: "Library Storage: C:\\Users\\ender\\.platformio\\lib\r\nLooking for RotaryEncoder library in registry\r\nRotaryEncoder\r\n=============\r\n#ID: 151\r\nRotary Encoder\r\n\r\nKeywords: input, encoder, signal\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR\r\nAuthors: Watterott electronic\r\n\r\nRotaryEncoder\r\n=============\r\n#ID: 1569\r\nUse a rotary encoder with quadrature pulses as an input device.\r\n\r\nKeywords: signal, input, output\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Infineon XMC, Intel ARC32, Kendryte K210, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, ST STM8, Teensy, TI MSP430\r\nAuthors: Matthias Hertel\r\n\r\nRotaryEncoder\r\n=============\r\n#ID: 5568\r\nRotary Encoder with interrupts\r\n\r\nKeywords: rotary, encoder, quadrature, ky-040, timerone, interrupt, sensor\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, Teensy, TI MSP430\r\nAuthors: ejoyneering\r\n\r\nRotaryEncoder\r\n=============\r\n#ID: 2655\r\nRotary encoder library.\r\n\r\nKeywords: encoder, rotary\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Shinichiro Nakamura\r\n\r\nRotaryEncoder\r\n=============\r\n#ID: 5199\r\nRotary encoder handler.\r\n\r\nKeywords: rotaryencoder\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: PB\r\n\r\nRotaryEncoder\r\n=============\r\n#ID: 4552\r\nロータリーエンコーダー (機械接点式インクリメンタル型) の信号をデコードするクラスです。 Rotary Encoder (incremental, mechanical switch type) signal decoder class.\r\n\r\nKeywords: encoder, incremental, mechanical, rotary, switch\r\nCompatible frameworks: mbed\r\nCompatible platforms: Atmel SAM, Freescale Kinetis, Maxim Integrated MAX32, Nordic nRF51, Nordic nRF52, NXP LPC, Silicon Labs EFM32, ST STM32, Teensy, WIZNet W7500\r\nAuthors: Tetsuya Hoshino\r\n\r\nFound: https://platformio.org/lib/show/151/RotaryEncoder\r\nLibraryManager: Installing id=151 @ ^1.4.0\r\n\n\nConflict: More than one library has been found by request {\"name\": \"RotaryEncoder\", \"requirements\": \"^1.4.0\"}:\r\nAutomatically chose the first available library (use `--interactive` option to make a choice)\r\nError: Could not find a version that satisfies the requirement '^1.4.0' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Try this `id=5568`.

**Comment by adamzxtan** [comment]
@ivankravets what do you mean by that? I'm getting the same message when I try to install the library too

**Comment by ivankravets** [comment]
Fixed in PIO Home 2.3.3. Please open PlatformIO IDE Terminal and type:
```
pio update
```

Restart IDE. Start installing again using PIO Home.
