### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by mrzombit** [platformio/platformio-core#2955]
PIO Core Call Error: "The current working directory C:\\Users\\MrZOMBIT\\Documents\\PlatformIO\\Projects\\ITC1 will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\MrZOMBIT\\Documents\\PlatformIO\\Projects\\ITC1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing atmelavr\n\n\nError: You are not connected to the Internet.\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

**Comment by ivankravets** [comment]
You are not connected to the Internet.\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains
