### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by spdi** [platformio/platformio-core#2957]
PIO Core Call Error: "Library Storage: C:\\Users\\Michal\\.platformio\\lib\nLooking for SerialCommand library in registry\nFound: https://platformio.org/lib/show/173/SerialCommand\nLibraryManager: Installing id=173 @ ^76ebd2d60e\n\n\nError: Could not find a version that satisfies the requirement '^76ebd2d60e' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
It was fixed in the latest PIo Home. Please open PlatformIO IDE Terminal and type `pio update`. Restart VSCode
