### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by mspcbs** [platformio/platformio-core#2959]
PIO Core Call Error: "PlatformManager: Installing atmelavr\nDownloading...\nUnpacking...\natmelavr @ 1.15.0 has been successfully installed!\nPackageManager: Installing toolchain-atmelavr @ ~1.50400.0\r\nWarning! Package Mirror: ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'))\nLooking for another mirror...\nDownloading...\n\n\nError: Please read http://bit.ly/package-manager-ioerror"

**Comment by ivankravets** [comment]
> ('Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host'

Please check internet connection
