### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by finite-state-maid** [platformio/platformio-core#2967]
PIO Core Call Error: "The current working directory C:\\Users\\lenovo\\Desktop\\1111 will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\lenovo\\Desktop\\1111\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Detected unknown package 'toolchain-gccarmnoneeabi'"

**Comment by ivankravets** [comment]
Which board did you select? What is your OS?

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by finite-state-maid** [comment]
I have solved this problem. Thanks for your help.




------------------ 原始邮件 ------------------
发件人: "Ivan Kravets"<notifications@github.com>;
发送时间: 2019年9月2日(星期一) 晚上6:39
收件人: "platformio/platformio-core"<platformio-core@noreply.github.com>;
抄送: "朱世健"<1291255759@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [platformio/platformio-core] Home: Could not initialize project(#2967)




Please reopen if you still need help
