### ISSUE TITLE
Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by live-user0001** [platformio/platformio-core#2968]
Server error: {"args":[3,"Systém nemůže nalézt uvedenou cestu"],"message":"[Error 3] Systém nemůže nalézt uvedenou cestu: u'C:\\\\Users\\\\pc\\\\Documents\\\\PlatformIO\\\\Projects\\\\*.*'","type":"WindowsError"}

**Comment by live-user0001** [comment]
000011

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2321
