### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by calox63** [platformio/platformio-core#2978]
PIO Core Call Error: "Error: Invalid 'C:\\Users\\Carlos\\Documents\\PlatformIO\\Projects\\ioticos\\platformio.ini' (project configuration file): 'File contains no section headers.\nfile: C:\\Users\\Carlos\\Documents\\PlatformIO\\Projects\\ioticos\\platformio.ini, line: 6\n'//**************************************\\n''"

**Comment by ivankravets** [comment]
> File contains no section headers

Please fix `platformio.ini` file
