### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by redphoenix741** [platformio/platformio-core#2980]
PIO Core Call Error: "Platform C:\\Users\\Joem Diente\\.platformio\\platforms\\espressif8266\n--------\nUpdating espressif8266                   @ fe8c185        [3500fb2]\r\nUpdating tool-mkspiffs                   @ 1.200.0        [Up-to-date]\nUpdating tool-esptool                    @ 1.413.0        [Up-to-date]\nUpdating framework-arduinoespressif8266  @ 21926a6        [77c4f5e]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please remove `C:\Users\Joem Diente\.platformio\packages\framework-arduinoespressif8266 ` and start build again. It seems you modified original sources

**Comment by redphoenix741** [comment]
Thank you.
