### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by paulnguyen2833** [platformio/platformio-core#2981]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\Dell\\\\Documents\\\\PlatformIO'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2718
