### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by mmvirus** [platformio/platformio-core#2988]
PIO Core Call Error: "toolchain-atmelavr @ 1.50400.190710 has been successfully installed!\nPackageManager: Installing framework-arduinoavr @ ~4.1.1\r\nframework-arduinoavr @ 4.1.2 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~2.20501.7\ntool-scons @ 2.20501.190826 has been successfully installed!\n======================== [SUCCESS] Took 112.77 seconds ========================"

**Comment by ivankravets** [comment]
Try to restart VSCode. Should work.
