### ISSUE TITLE
Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by live-user0001** [platformio/platformio-core#2994]
Server error: {"args":[123,"Název souboru či adresáře nebo jmenovka svazku je nesprávn"],"message":"[Error 123] Název souboru či adresáře nebo jmenovka svazku je nesprávn: u'C:\\\\Users\\\\pc\\\\---1\\\\\"TRUE\"\\\\*.*'","type":"WindowsError"}

**Comment by ivankravets** [comment]
> [Error 123]

No permissions or antivirus tools.
