### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by bouba830** [platformio/platformio-core#2997]
PIO Core Call Error: "Library Storage: D:\\MARLIN\\Marlin-bltouch\\.pio\\libdeps\\alfawise_U30\nUpdating TMCStepper                      @ 0.4.6          [0.5.0]\r\nUninstalling TMCStepper @ 0.4.6: \t[OK]\nLooking for TMCStepper library in registry\nFound: https://platformio.org/lib/show/5513/TMCStepper\nLibraryManager: Installing id=5513 @ 0.5.0\r\n\n\nError: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by ivankravets** [comment]
Sorry for the issue, should work now. Please try again.
