### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by PascalMonnier** [platformio/platformio-core#2998]
PIO Core Call Error: "Library Storage: C:\\Users\\pasca\\.platformio\\lib\nLibraryManager: Installing id=13 @ ^1.5.7\n\n\nError: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by teoman002** [comment]
related to issue #2999

**Comment by ivankravets** [comment]
Sorry for the issue, should work now. Please try again.
