### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by bouba830** [platformio/platformio-core#2999]
PIO Core Call Error: "Library Storage: D:\\MARLIN\\Marlin_2.0.X_Beta_Alfawise_Ux0-master\\.pio\\libdeps\\alfawise_U30\nUpdating LiquidCrystal                   @ 1.3.4          [1.5.0]\r\nUninstalling LiquidCrystal @ 1.3.4: \t[OK]\nLooking for LiquidCrystal library in registry\nLiquidCrystal\r\n=============\n#ID: 136\nLiquidCrystal Library is faster and extensable, compatible with the original LiquidCrystal library\r\n\r\nKeywords: lcd, hd44780\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Espressif 32, Espressif 8266\r\nAuthors: F Malpartida\r\n\r\nLiquidCrystal\r\n=============\n#ID: 887\nAllows communication with alphanumerical liquid crystal displays (LCDs).\r\n\r\nKeywords: display\r\nCompatible frameworks: Arduino\r\nCompatible platforms: Atmel AVR, Atmel SAM, Espressif 32, Espressif 8266, Intel ARC32, Microchip PIC32, Nordic nRF51, Nordic nRF52, ST STM32, Teensy, TI MSP430\r\nAuthors: Arduino, Adafruit\r\n\r\nFound: https://platformio.org/lib/show/136/LiquidCrystal\nLibraryManager: Installing id=136 @ 1.5.0\r\n\n\nConflict: More than one library has been found by request {\"requirements\": \"1.5.0\", \"name\": \"LiquidCrystal\"}:\nAutomatically chose the first available library (use `--interactive` option to make a choice)\nError: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by ivankravets** [comment]
Sorry for the issue, should work now. Please try again.
