### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by tonchi76** [platformio/platformio-core#3001]
PIO Core Call Error: "Library Storage: /Users/fer/.platformio/lib\nUpdating ArduinoJson                     @ 6.11.3         [6.12.0]\nUninstalling ArduinoJson @ 6.11.3: \t[OK]\nLooking for ArduinoJson library in registry\nFound: https://platformio.org/lib/show/64/ArduinoJson\nLibraryManager: Installing id=64 @ 6.12.0\n\n\nError: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by teoman002** [comment]
related to issue #2999

**Comment by ivankravets** [comment]
Sorry for the issue, should work now. Please try again.
