### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by NAPCAL** [platformio/platformio-core#3006]
PIO Core Call Error: "Library Storage: H:\\3D printing\\BIGTREETECH-SKR-PRO-V1.1-master\\firmware\\Marlin-SKR-Pro\\.piolibdeps\\BIGTREE_SKR_PRO\nUpdating TMCStepper                      @ 7fda12f        [7d0f0f7]\r\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
Please remove ` H:\3D printing\BIGTREETECH-SKR-PRO-V1.1-master\firmware\Marlin-SKR-Pro\.piolibdeps\BIGTREE_SKR_PRO` and start building again.
