### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by Ikes72000** [platformio/platformio-core#3010]
Hi,

I'm trying to install library with a fresh install of PIO, under VSCode and Debian 9.
I have tried with diffferents libraries, same error.

`PIO Core Call Error: "Library Storage: /home/xxxx/.platformio/lib\nLibraryManager: Installing id=64 @ ^6.12.0\n\n\nError: [API] Invalid response: Internal Server Error"`

Thanks for help.

Ikes

**Comment by ivankravets** [comment]
Sorry for the issue, should work now. Please try again.
