### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by mars000** [platformio/platformio-core#3011]
PIO Core Call Error: "Library Storage: /Users/mars/.platformio/lib\nLibraryManager: Installing id=64 @ ^6.12.0\n\n\nError: [API] Invalid response: <html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>"

**Comment by ivankravets** [comment]
Sorry for the issue, should work now. Please try again.
