### ISSUE TITLE
Home: Libraries: Updates

### ISSUE THREAD

**Issue by red913** [platformio/platformio-core#3017]
PIO Core Call Error: "Error: VCS: Could not receive an output from `['git', 'ls-remote']` command ({'returncode': 128, 'err': u\"fatal: unable to access 'https://github.com/mikeshub/SailfishLCD.git/': Failed to connect to github.com port 443: Timed out\", 'out': u''})"

**Comment by ivankravets** [comment]
fatal: unable to access 'https://github.com/mikeshub/SailfishLCD.git/': Failed to connect to github.com port 443
