### ISSUE TITLE
Home: Could not initialize project - Unknown development platform '.\\.platformio\\platforms\\espressif32'"

### ISSUE THREAD

**Issue by StewLG** [platformio/platformio-core#3019]
I've been trying to install PlatformIO in Visual Studio Code for Windows for about 5 hours.

I'm stuck on the following error which comes when I attempt to create a new vanilla Arduino project:

PIO Core Call Error: "********************************************************************************\r\nIf you like PlatformIO, please:\r\n- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org\r\n- star it on GitHub > https://github.com/platformio/platformio\r\n- support us with PlatformIO Plus > https://pioplus.com\r\n********************************************************************************\r\n\r\n\n\nError: Unknown development platform '.\\.platformio\\platforms\\espressif32'"

**Comment by ivankravets** [comment]
Just set in `platformio.ini` 
```
[env:xxxx]
platform = espressif32
```
