### ISSUE TITLE
Home: OS_COPY_FILE

### ISSUE THREAD

**Issue by coincashbank** [platformio/platformio-core#3027]
Server error: {"args":[3,"Sistem belirtilen yolu bulamıyor"],"message":"[Error 3] Sistem belirtilen yolu bulamıyor: u'C:\\\\Users\\\\fato\\u015f\\\\Documents\\\\PlatformIO\\\\Projects\\\\*.*'","type":"WindowsError"}

**Comment by ivankravets** [comment]
> [Error 3] Sistem belirtilen yolu bulamıyor

Antivirus? permissions?
