### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by igrowing** [platformio/platformio-core#3028]
PIO Core Call Error: "Library Storage: C:\\Users\\yanyui\\.platformio\\lib\nUpdating SparkFun MAX3010x Pulse and Proximity Sensor Library @ 1.0.8          [1.1.1]\r\nUninstalling SparkFun MAX3010x Pulse and Proximity Sensor Library @ 1.0.8: \t[OK]\nLooking for SparkFun MAX3010x Pulse and Proximity Sensor Library library in registry\n\n\nError: Library `{'requirements': u'1.1.1', 'name': 'SparkFun MAX3010x Pulse and Proximity Sensor Library'}` has not been found in PlatformIO Registry.\nYou can ignore this message, if `{'requirements': u'1.1.1', 'name': 'SparkFun MAX3010x Pulse and Proximity Sensor Library'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

Not sure it it unique case, maybe opened. PlatformIO suggested to submit issue.It's annoying so I agreed  :)

**Comment by ivankravets** [comment]
We don't have this library in registry https://platformio.org/lib/search?query=name:%22SparkFun%20MAX3010x%20Pulse%20and%20Proximity%20Sensor%20Library%22
