### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by NeevMahajan** [platformio/platformio-core#3029]
PIO Core Call Error: "The current working directory C:\\Users\\Fountlab\\Documents\\PlatformIO\\Projects\\190918-162306-arduino-blink will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\Fountlab\\Documents\\PlatformIO\\Projects\\190918-162306-arduino-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing esp wrover kit (platform: espressif32; framework: arduino; board: esp-wrover-kit)\n\nUnpacking\nUnpacking\ntoolchain-xtensa @ 2.40802.190218 has been successfully installed!\nPackageManager: Installing tool-esptool @ <2\nDownloading\nDownloading\nUnpacking\nUnpacking\ntool-esptool @ 1.413.0 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\ntool-esptoolpy @ 1.20600.0 is already installed\nThe platform 'espressif8266' has been successfully installed!\nThe rest of packages will be installed automatically depending on your build environment."

**Comment by ivankravets** [comment]
Please open `C:\Users\Fountlab\Documents\PlatformIO\Projects\190918-162306-arduino-blink` project and try to build it. Do you see any errors? If yes, please reopen.
