### ISSUE TITLE
VCS: Could not process command ['git', 'pull', '--recurse-submodules']

### ISSUE THREAD

**Issue by MacWyznawca** [platformio/platformio-core#3033]
PIO Core Call Error: "Platform /Users/jkk/.platformio/platforms/espressif32_stage\n--------\nUpdating espressif32                     @ 839ae90        [cff56ff]\n\n\nError: VCS: Could not process command ['git', 'pull', '--recurse-submodules']"

**Comment by ivankravets** [comment]
How to reproduce it? Did you modify files in a cloned repo?

@valeros please help.

**Comment by ivankravets** [comment]
Did you resolve it?

**Comment by ivankravets** [comment]
Please reopen if you still need help
