### ISSUE TITLE
Configuration file parameters partly ignored when using --project-conf

### ISSUE THREAD

**Issue by daniel-starke** [platformio/platformio-core#3034]
**PlatformIO Core**
------------------------------------------------------------------

### Configuration

**Operating system**: Windows 7

**PlatformIO Version** (`platformio --version`): 4.0.3

### Description of problem
platformio section is not evaluated if a non-default configuration file is provided with `-c`.

#### Steps to Reproduce

1. `platformio run -c test.ini`

### Actual Results

.pio is used as default.

### Expected Results

The path defined in workspace_dir is used.

### Problems with PlatformIO Build System:

**The content of `test.ini`:**
```ini
[platformio]
workspace_dir = bin

[env:wavrec]
platform = espressif32
framework = arduino
board = wemosbat
monitor_speed = 115200
```

**Source file to reproduce issue:**
```cpp
setup(void) {}
loop(void) {}
```

### Additional info

Defining the environment variable PLATFORMIO_WORKSPACE_DIR works regardlessly.

**Comment by ivankravets** [comment]
Oh, this issue took a lot of efforts, but it worth it. See https://github.com/platformio/platformio-core/commit/d2abac9b18ff47cd2ab32312995ba52e78cfd62a

Could you re-test with `pio upgrade --dev`?

**Comment by daniel-starke** [comment]
Thank you. Works for me as expected.

**Comment by ivankravets** [comment]
Thanks for the report!

Happy coding with PlatformIO!

**Comment by daniel-starke** [comment]
Hm... would had been nice to have a way to "upgrade" back to stable...

**Comment by ivankravets** [comment]
`pip uninstall platformio`
`pip install platformio`
