### ISSUE TITLE
Home: Error occurred while requesting content from http://dl.platformio.org/libraries/examples/5/567/AutoConnect.ino

### ISSUE THREAD

**Issue by NicolasMoine** [platformio/platformio-core#3036]
401 Client Error: Unauthorized for url: http://fw/auth?u=aHR0cDovL2RsLnBsYXRmb3JtaW8ub3JnL2xpYnJhcmllcy9leGFtcGxlcy81LzU2Ny9BdXRvQ29ubmVjdC5pbm8=

**Comment by ivankravets** [comment]
Please check your proxy configuration
