### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by szczawioslaw** [platformio/platformio-core#3037]
PIO Core Call Error: "Library Storage: C:\\Users\\Szymon\\.platformio\\lib\nUpdating VirtuinoESP                     @ 1.7.2          [1.8.0]\r\nUninstalling VirtuinoESP @ 1.7.2: \t[OK]\nLooking for VirtuinoESP library in registry\n\n\nError: Library `{'requirements': u'1.8.0', 'name': 'VirtuinoESP'}` has not been found in PlatformIO Registry.\nYou can ignore this message, if `{'requirements': u'1.8.0', 'name': 'VirtuinoESP'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
We don't have this library in registry https://platformio.org/lib/search?query=name%253A%2522VirtuinoESP%2522&page=1
