### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by flyucc** [platformio/platformio-core#3042]
PIO Core Call Error: "PlatformManager: Installing gd32v\ngd32v @ 1.0.0 has been successfully installed!\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/sipeed/platform-gd32v/issues/6
