### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by yifanff** [platformio/platformio-core#3048]
PIO Core Call Error: "The current working directory C:\\Users\\liyifan\\Documents\\PlatformIO\\Projects\\190925-160755-IMU will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\liyifan\\Documents\\PlatformIO\\Projects\\190925-160755-IMU\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing OpenIMU300ZI (platform: aceinna_imu; board: OpenIMU300)\n\nVerbose mode can be enabled via `-v, --verbose` option\nCONFIGURATION: https://docs.platformio.org/page/boards/aceinna_imu/OpenIMU300.html\nPLATFORM: Aceinna IMU 1.2.0 > Aceinna OpenIMU 300ZA\nHARDWARE: STM32F405RG 120MHz, 128KB RAM, 1MB Flash\nDEBUG: Current (stlink) External (blackmagic, jlink, stlink)\nPACKAGES: toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\nLDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf\nLDF Modes: Finder ~ chain, Compatibility ~ soft\nLooking for OpenIMU300-base-library library in registry\nAPIRequestError: [API] Invalid response: Unable to round-trip http request to upstream: EOF:\n  File \"C:\\Users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 126:\n    env.SConscript(\"$BUILD_SCRIPT\")\n  File \"C:\\Users\\liyifan\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 541:\n    return _SConscript(self.fs, *files, **subst_kw)\n  File \"C:\\Users\\liyifan\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 250:\n    exec _file_ in call_stack[-1].globals\n  File \"C:\\Users\\liyifan\\.platformio\\platforms\\aceinna_imu\\builder\\main.py\", line 125:\n    target_elf = env.BuildProgram()\n  File \"C:\\Users\\liyifan\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"C:\\Users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 122:\n    _build_project_deps(env)\n  File \"C:\\Users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 47:\n    project_lib_builder = env.ConfigureProjectLibBuilder()\n  File \"C:\\Users\\liyifan\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\n    return self.method(*nargs, **kwargs)\n  File \"C:\\Users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 1043:\n    project.install_dependencies()\n  File \"C:\\Users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 878:\n    lm.install(uri)\n  File \"c:\\users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 352:\n    interactive=interactive)\n  File \"c:\\users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 253:\n    cache_valid=\"1h\")\n  File \"c:\\users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 361:\n    result = _get_api_result(url, params, data)\n  File \"c:\\users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 85:\n    return func(*args, **kwargs)\n  File \"c:\\users\\liyifan\\.platformio\\penv\\lib\\site-packages\\platformio\\util.py\", line 337:\n    r.text.encode(\"utf-8\"))\n [FAILED] Took 6.49 seconds"

**Comment by ivankravets** [comment]
> : [API] Invalid response: Unable to round-trip http request to upstream: EOF

Please check your Internet/Proxy settings, restart VSCode. It should work.
