### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by dmitryyurch** [platformio/platformio-core#3057]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/dc-forte/.platformio/platforms/Arduino_Core_STM8/platform.json'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
1. Remove /Users/dc-forte/.platformio/platforms/Arduino_Core_STM8
2. Restart VSCode.
