### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by psinetron** [platformio/platformio-core#3058]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: 'C:\\\\Users\\\\Dell\\\\.platformio\\\\platforms\\\\Arduino\\\\platform.json'","type":"IOError"}

**Comment by ivankravets** [comment]
REmove C:\\Users\\Dell\\.platformio\\platforms\\Arduino
Restart
