### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by AdamPudil** [platformio/platformio-core#3059]
PIO Core Call Error: "Library Storage: /home/adam/.platformio/lib\n\n\nError: Could not load broken JSON: /home/adam/.platformio/lib/TFT_Touch_ID5461/.library.json"

**Comment by ivankravets** [comment]
Please remove this file `/home/adam/.platformio/lib/TFT_Touch_ID5461/.library.json`
