### ISSUE TITLE
Using Specific Commit/tag of arduino core may not be working as expected for submodules

### ISSUE THREAD

**Issue by arihantdaga** [platformio/platformio-core#3060]
What kind of issue is this?
- [ X ] **PlatformIO Core**.
      

### Configuration

**Operating system**: Mac Os 

**PlatformIO Version** 4.1.0b1

### Description of problem
I am using platformio for my esp8266 project with arduino framework. 
I found that we can use git urls for installing custom/staging version of the core. 
I have a url like this - where i want to use the core upto a specific commit. 
`https://github.com/arihantdaga/Arduino.git#961b558a91caf9589cdf0daa76a2aafd4a6ec568`
We are using package manager's  _install_from_url method and then calling vcsclient.export(). 
However in this export method we first call 
```
git clone --recursive {repo url} 
and then call 
git reset --hard {tag}
```
https://github.com/platformio/platformio-core/blob/3dcf1784fb1db0a0dee20ec50b63df73e41b5f01/platformio/vcsclient.py#L157-L168

Problem is while cloning recursively we cloned submodules and checkout specific tags of thos submodules as they were in latest `https://github.com/arihantdaga/Arduino.git` and then calling reset --hard will only reset the parent module, but the submodules are still at the same version (latest from git) and are not checked out to the version they are at the tag of framework. 
I was thinking maybe we should add another stage and call `git submodule update --init --recursive`. 
I am sorry if i am not thinking in right direction. I am not sure, i haven't looked the complete code of this and how different parts are working.

**Comment by ivankravets** [comment]
Thanks for the report! Please re-test with `pio upgrade --dev`
