### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by harrinp** [platformio/platformio-core#3069]
PIO Core Call Error: "The current working directory /Users/paulharrington/Documents/PlatformIO/Projects/PleaseWork will be used for the project.\n\nThe next files/directories have been created in /Users/paulharrington/Documents/PlatformIO/Projects/PleaseWork\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing nanoatmega328 (platform: atmelavr; board: nanoatmega328; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\n  File \"/Users/paulharrington/.platformio/platforms/atmelavr/builder/main.py\", line 30\n\n    print \"Please unplug/plug device ...\"\n\n                                        ^\n\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"Please unplug/plug device ...\")?\n\n========================== [FAILED] Took 0.61 seconds =========================="

**Comment by ivankravets** [comment]
Please open PlatformIO IDE Terminal and type `pio update`. Restart VSCode.
