### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by arsalanj** [platformio/platformio-core#3075]
PIO Core Call Error: "PlatformManager: Installing espressif8266\nespressif8266 @ 2.2.3 is already installed\nPackageManager: Installing toolchain-xtensa @ <3\ntoolchain-xtensa @ 2.40802.190218 is already installed\nPackageManager: Installing tool-esptool @ <2\ntool-esptool @ 1.413.0 is already installed\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\ntool-esptoolpy @ 1.20600.0 is already installed\n\n\nError: Traceback (most recent call last):\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 90, in main\n    cli(None, None, None)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/commands/platform.py\", line 302, in platform_install\n    force=force):\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 95, in install\n    return self.cleanup_packages(list(p.packages))\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 155, in cleanup_packages\n    p = PlatformFactory.newPlatform(manifest['__pkg_dir'])\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 260, in newPlatform\n    _instance = platform_cls(join(platform_dir, \"platform.json\"))\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/managers/platform.py\", line 497, in __init__\n    self._manifest = fs.load_json(manifest_path)\n  File \"/Users/mehdi/.platformio/penv/lib/python2.7/site-packages/platformio/fs.py\", line 54, in load_json\n    with open(file_path, \"r\") as f:\nIOError: [Errno 2] No such file or directory: '/Users/mehdi/.platformio/platforms/Arduino/platform.json'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> /Users/mehdi/.platformio/platforms/Arduino

Please remove this folder and restart VScode.
