### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by hamed-ta** [platformio/platformio-core#3077]
PIO Core Call Error: "framework-arduinoespressif32 @ 2.10003.190916 has been successfully installed!\nPackageManager: Installing tool-esptoolpy @ ~1.20600.0\r\ntool-esptoolpy @ 1.20600.0 has been successfully installed!\nCorePackageManager: Installing tool-scons @ ~2.20501.7\ntool-scons @ 2.20501.190826 has been successfully installed!\n======================== [SUCCESS] Took 235.37 seconds ========================\n\r\nEnvironment     Status    Duration\r\n--------------  --------  ------------\r\nesp32dev        SUCCESS   00:03:55.374\r\nesp wrover kit  IGNORED\r\nespea32         IGNORED\r\nesp320          IGNORED\r\n========================= 1 succeeded in 00:03:55.374 ========================="

**Comment by ivankravets** [comment]
Try to restart VSCode, open PIO Home and install dev/platform manually. later import its project example.
