### ISSUE TITLE
Force Upload and Monitor not working on 4.1.0b2

### ISSUE THREAD

**Issue by meltdown03** [platformio/platformio-core#3081]
Using the latest platformio-core 4.1.0b2 (master branch - 10/3/2019) with VSCode or from the terminal:
Running `pio run -t upload -t monitor` just uploads the sketch and will not automatically open the serial monitor. I can open it manually without issue. Seems to have just broke in the last few days.

ESP32 or ESP8266, both do it, using the "feature/stage"  versions for these platforms.

**Comment by ivankravets** [comment]
Thanks for the report! The issue has been fixed. Please re-run `pio upgrade --dev`.
