### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by CheJiangbo** [platformio/platformio-core#3084]
PIO Core Call Error: "Error: [API] Invalid response: b'<html>\\n<head>\\n <title>500 Internal Privoxy Error</title>\\n <link rel=\"shortcut icon\" href=\"http://config.privoxy.org/error-favicon.ico\" type=\"image/x-icon\"></head>\\n<body>\\n<h1>500 Internal Privoxy Error</h1>\\n<p>Privoxy encountered an error while processing your request:</p>\\n<p><b>Could not load template file <code>no-server-data</code> or one of its included components.</b></p>\\n<p>Please contact your proxy administrator.</p>\\n<p>If you are the proxy administrator, please put the required file(s)in the <code><i>(confdir)</i>/templates</code> directory.  The location of the <code><i>(confdir)</i></code> directory is specified in the main Privoxy <code>config</code> file.  (It\\'s typically the Privoxy install directory).</p>\\n</body>\\n</html>\\n'"

**Comment by ivankravets** [comment]
Check proxy settings
