### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by peter3920fm** [platformio/platformio-core#3086]
PIO Core Call Error: "The current working directory C:\\Users\\Peter\\Documents\\PlatformIO\\Projects\\191007-091506-esp8266-rtos-sdk-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Peter\\Documents\\PlatformIO\\Projects\\191007-091506-esp8266-rtos-sdk-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing nodemcuv2 (platform: espressif8266; framework: esp8266-rtos-sdk; board: nodemcuv2)\r\n--------------------------------------------------------------------------------\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xa5 in position 0: invalid start byte:\r\n  File \"C:\\SPB_Data\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 91:\r\n    env = DefaultEnvironment(**DEFAULT_ENV_OPTIONS)\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Defaults.py\", line 88:\r\n    _default_env = SCons.Environment.Environment(*args, **kw)\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 992:\r\n    apply_tools(self, tools, toolpath)\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 107:\r\n    env.Tool(tool)\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 1799:\r\n    tool(self)\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\__init__.py\", line 303:\r\n    self.generate(env, *args, **kw)\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\gcc.py\", line 59:\r\n    version = detect_version(env, env['CC'])\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\gcc.py\", line 94:\r\n    while SCons.Util.to_str(pipe.stdout.readline()):\r\n  File \"C:\\SPB_Data\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Util.py\", line 1593:\r\n    return str (s, 'utf-8')\r\n========================== [FAILED] Took 4.77 seconds ==========================\r\n\r\nEnvironment    Status    Duration\r\n-------------  --------  ------------\r\nnodemcuv2      FAILED    00:00:04.767\r\nesp_wroom_02   IGNORED\r\n==================== 1 failed, 0 succeeded in 00:00:04.767 ===================="

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```
