### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by Zy19930907** [platformio/platformio-core#3094]
PIO Core Call Error: "The current working directory /Users/shuuyou/Documents/PlatformIO/Projects/test1 will be used for the project.\n\nThe next files/directories have been created in /Users/shuuyou/Documents/PlatformIO/Projects/test1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Traceback (most recent call last):\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/platformio/__main__.py\", line 90, in main\n    cli(None, None, None)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/platformio/commands/init.py\", line 106, in cli\n    pg.generate()\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py\", line 131, in generate\n    tpl_vars = self._load_tplvars()\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/platformio/ide/projectgenerator.py\", line 86, in _load_tplvars\n    load_project_ide_data(self.project_dir, self.env_name) or {})\n  File \"/Users/shuuyou/.platformio/penv/lib/python2.7/site-packages/platformio/project/helpers.py\", line 208, in load_project_ide_data\n    raise result.exception\nOSError: [Errno 2] No such file or directory: '/Users/shuuyou/Documents/PlatformIO/Projects/test1'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please restart VSCode. It should work now.
