### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by kumarisurbhi** [platformio/platformio-core#3098]
Server error: {"args":[2,"No such file or directory"],"message":"[Errno 2] No such file or directory: '/Users/surbhikumari/.platformio/platforms/Arduino_Core_STM32/platform.json'","type":"IOError"}

**Comment by ivankravets** [comment]
Please remove `/Users/surbhikumari/.platformio/platforms/Arduino_Core_STM3` folder and restart VSCode.
