### ISSUE TITLE
No eligible build target.

### ISSUE THREAD

**Issue by JeronimoProgramer** [platformio/platformio-core#3100]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:Windows 10

**PlatformIO Version** (`platformio --version`): 2.3.3 --4.0.3

### Description of problem
The platform io send me an error when I want build.
Yesterday the platformIO build the code but now it didint.

The error was this:
No eligible build target.
No configuration to build this project exists.
No eligible build target.: No configuration to build this project exists.
    at file:///C:/Users/*USER*/.atom/packages/build/lib/build.js:113:15

#### Steps to Reproduce

1.Open de Code
2.Edit the Code
3.Try to compile the code

### Actual Results
The program didnt compile

### Expected Results
The expected result was that the program could compile

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
#include <LiquidCrystal_I2C.h>
#include <Wire.h>
#include <dht.h> //borrar************************
#include <Adafruit_Sensor.h> //borrar*************

#define lcdAdrres 0x27 //0x3F
LiquidCrystal_I2C lcd(lcdAdrres, 16, 2); //objeto lcd
DHT dht(36, DHT11); //borrar

void initLCD() {
  lcd.init();
  lcd.clear();
  lcd.backlight();
  lcd.print("Inicio Exitoso");
  delay(1000);
  lcd.clear();
  lcd.noBacklight();
}



void setup() {
  Wire.begin(); //aca se usan los pines default de la placa.
  initLCD();

}

void loop() {

}

void  deleteThis() {

}
```

### Additional info
I think that the same core deleted the mother file to compile. Since I have never accessed the folder where it indicates the error.

**Comment by ivankravets** [comment]
Please switch to PlatformIO IDE for VSCode -> https://platformio.org/platformio-ide
