### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by hassanmj** [platformio/platformio-core#3102]
PIO Core Call Error: "Library Storage: C:\\Users\\Hassan.Jajai\\.platformio\\lib\r\nLibraryManager: Installing id=431 @ ^0.3.9.2\r\n\n\nError: Could not find a version that satisfies the requirement '^0.3.9.2' for your system 'windows_x86'"

**Comment by ivankravets** [comment]
Please install direct version
```
pio lib -g install 431@0.3.9.2
```
`0.3.9.2` is not valid SemVer version.
