### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by rwagnervm** [platformio/platformio-core#3104]
PIO Core Call Error: "Library Storage: /home/87333953300/.platformio/lib\nLibraryManager: Installing id=408 @ ^1.2.0\nUsing cache: /home/87333953300/.platformio/.cache/cc/338ee11d777d75e24f4008826cd592cc\n\n\nError: Traceback (most recent call last):\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/__main__.py\", line 90, in main\n    cli(None, None, None)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/click/decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/commands/lib.py\", line 150, in lib_install\n    force=force)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/lib.py\", line 359, in install\n    force=force)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 703, in install\n    pkg_dir = self._install_from_piorepo(name, requirements)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/lib.py\", line 220, in _install_from_piorepo\n    if app.get_setting(\"strict_ssl\") else dl_data['url'], requirements)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 483, in _install_from_url\n    self.unpack(dlpath, tmp_dir)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/managers/package.py\", line 212, in unpack\n    with FileUnpacker(source_path) as fu:\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/unpacker.py\", line 102, in __enter__\n    self._unpacker = TARArchive(self.archpath)\n  File \"/home/87333953300/.platformio/penv/local/lib/python2.7/site-packages/platformio/unpacker.py\", line 51, in __init__\n    super(TARArchive, self).__init__(tarfile_open(archpath))\n  File \"/usr/lib/python2.7/tarfile.py\", line 1680, in open\n    raise ReadError(\"file could not be opened successfully\")\nReadError: file could not be opened successfully\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
> ReadError: file could not be opened successfully

Please try installing library again. It seems like broken archive
