### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by samfenix** [platformio/platformio-core#3107]
PIO Core Call Error: "Library Storage: C:\\Users\\Samuel\\.platformio\\lib\nLibraryManager: Installing id=7 @ ^1.19.1\nDownloading...\n\n\nError: Please read http://bit.ly/package-manager-ioerror\nError: Traceback (most recent call last):\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 90, in main\n    cli(None, None, None)\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\users\\samuel\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.par

**Comment by ivankravets** [comment]
It seems like antivirus tools block PlatformIO:
1. Plese close VScode
2.  Open system task manager and kill all Pythons
3. Start VScode.
