### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by VictorVital100** [platformio/platformio-core#3108]
PIO Core Call Error: "The current working directory C:\\Users\\maxst\\Documents\\PlatformIO\\Projects\\RelayTest will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\maxst\\Documents\\PlatformIO\\Projects\\RelayTest\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing uno (platform: atmelavr; board: uno; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nImportError: cannot import name 'Serial' from 'serial' (c:\\users\\maxst\\.platformio\\penv\\lib\\site-packages\\serial\\__init__.py):\r\n  File \"C:\\Users\\maxst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 91:\r\n    env = DefaultEnvironment(**DEFAULT_ENV_OPTIONS)\r\n  File \"C:\\Users\\maxst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Defaults.py\", line 88:\r\n    _default_env = SCons.Environment.Environment(*args, **kw)\r\n  File \"C:\\Users\\maxst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 992:\r\n    apply_tools(self, tools, toolpath)\r\n  File \"C:\\Users\\maxst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 107:\r\n    env.Tool(tool)\r\n  File \"C:\\Users\\maxst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 1798:\r\n    tool = SCons.Tool.Tool(tool, toolpath, **kw)\r\n  File \"C:\\Users\\maxst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\__init__.py\", line 122:\r\n    module = self._tool_module()\r\n  File \"C:\\Users\\maxst\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\__init__.py\", line 239:\r\n    module = spec.loader.load_module(spec.name)\r\n  File \"<frozen importlib._bootstrap_external>\", line 407:\r\n    \r\n  File \"<frozen importlib._bootstrap_external>\", line 907:\r\n    \r\n  File \"<frozen importlib._bootstrap_external>\", line 732:\r\n    \r\n  File \"<frozen importlib._bootstrap>\", line 265:\r\n    \r\n  File \"<frozen importlib._bootstrap>\", line 696:\r\n    \r\n  File \"<frozen importlib._bootstrap>\", line 677:\r\n    \r\n  File \"<frozen importlib._bootstrap_external>\", line 728:\r\n    \r\n  File \"<frozen importlib._bootstrap>\", line 219:\r\n    \r\n  File \"C:\\Users\\maxst\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\pioupload.py\", line 26:\r\n    from serial import Serial, SerialException\r\n========================== [FAILED] Took 3.57 seconds =========================="

**Comment by ivankravets** [comment]
> ImportError: cannot import name 'Serial' from 'serial'

Please remove `c:\users\maxst\.platformio\penv` folder and restart VSCode.
