### ISSUE TITLE
Request: Metapackages System

### ISSUE THREAD

**Issue by ptiza-v-nebe** [platformio/platformio-core#3109]
Dear Platformio!

I have a project where I want to group multiple packages to one cluster, because such way the project organisation is much more cleaner. In ROS it is called [metapackages](http://wiki.ros.org/Metapackages), it handles multiple packages as one package. Modularity of the project is much higher as having just flat list of packages.

Platformio has only indirect support for nested hierarchy. I have a hard time to create such construct, because the "lib" folder is just advanced g++ lib/include build enviroment and not real modular, flexible packaging system.

My dream is to have following project folder structure:
├── include
├── lib
│   ├── comm_manager
│   │   ├── comm_dispatcher
│   │   ├── comm_driver
│   │   ├── comm_messenger
│   │   └── comm_msgs
│   ├── decision_manager
│   │   ├── decision_behavior_tree
│   │   └── decision_main_control
│   ├── driver_manager
│   │   ├── driver_controller
│   │   ├── driver_encoder
│   │   ├── driver_fsm
│   │   └── driver_motor
│   ├── general_tools
│   │   ├── geometry_math
│   │   └── task_scheduler
│   └── obstacle_manager
│       ├── obstacle_enemy_detection
│       └── obstacle_map
├── platformio.ini
└── src
    └── main.cpp

As you see, the size of the project is already a little larger and it will even more grow. I want to have nice clean folder namings like above, so people who are at beginning of the coding journey don't lost by the chaos which is always caused by typical flat src/include folder structure.  Another advantage is the modularity. I just give someone comm_manager folder, he places it in his lib folder and has all what he need to participating in the communication network. It is only one piece of something that works solid out of box, independently of computer and os, but there is still this good organisation feeling because of clear groupings and namings that could be possible.

It is ok if we have to create some additional file like "metapackage.json" or whatever in the root of comm_manager and other overall folders. The content of this file would be just the list of all folders or however (example of comm_manager)
```
{
    "package_type": "metapackage"
    "list_of_packages": 
    [
        "comm_driver",
        "comm_messenger",
        "comm_dispatcher",
        "comm_msgs"
    ]
}
```

It will very improve the experience of platformio as simple coding tool!

Thank you!

**Comment by ivankravets** [comment]
So, and why it does not work now?

**Comment by ivankravets** [comment]
Please reopen if you still need help
