### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by Qitas** [platformio/platformio-core#3112]
when I want to install some platform then: 

PIO Core Call Error: "PlatformManager: Installing H6\r\n\n\nError: Could not load broken JSON: C:\\Users\\admin\\.platformio\\platforms\\_tmp_installing-i123vp7j-package\\platform.json"

**Comment by ivankravets** [comment]
>  Installing H6

What is it? See valid platforms https://platformio.org/platforms
