### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte

### ISSUE THREAD

**Issue by densorr** [platformio/platformio-core#3115]
PIO Core Call Error: "The current working directory C:\\Users\\densor\\Documents\\PlatformIO\\Projects\\dmx_2560_test will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\densor\\Documents\\PlatformIO\\Projects\\dmx_2560_test\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)\r\n--------------------------------------------------------------------------------\r\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 0: invalid continuation byte:\r\n  File \"C:\\Users\\densor\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 91:\r\n    env = DefaultEnvironment(**DEFAULT_ENV_OPTIONS)\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Defaults.py\", line 88:\r\n    _default_env = SCons.Environment.Environment(*args, **kw)\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 992:\r\n    apply_tools(self, tools, toolpath)\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 107:\r\n    env.Tool(tool)\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 1799:\r\n    tool(self)\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\__init__.py\", line 303:\r\n    self.generate(env, *args, **kw)\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\gcc.py\", line 59:\r\n    version = detect_version(env, env['CC'])\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Tool\\gcc.py\", line 94:\r\n    while SCons.Util.to_str(pipe.stdout.readline()):\r\n  File \"C:\\Users\\densor\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Util.py\", line 1593:\r\n    return str (s, 'utf-8')\r\n========================== [FAILED] Took 0.93 seconds =========================="

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
