### ISSUE TITLE
Run miniterm with --filter=direct argument

### ISSUE THREAD

**Issue by minecraft2048** [platformio/platformio-core#3121]
What kind of issue is this?

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

ESP32 uses ANSI color codes for their serial print output, for example this example ESP32 project: https://github.com/platformio/platform-espressif32/tree/master/examples/espidf-http-request?utm_source=platformio&utm_medium=docs ,but miniterm.py by default filters out terminal control codes that control colors, which means that in default serial monitor it looks like this:
![image](https://user-images.githubusercontent.com/2445636/66791697-01958680-ef41-11e9-9081-2f090b964d59.png)
while it should look like this:
![image](https://user-images.githubusercontent.com/2445636/66791727-1b36ce00-ef41-11e9-9ee7-f29d4adc2dd1.png)
Running miniterm with `--filter=direct` argument makes the colors work again

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/projectconf/section_env_monitor.html#monitor-flags
