### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by erkuo521** [platformio/platformio-core#3122]
PIO Core Call Error: "The current working directory C:\\Users\\chenerkuo\\Documents\\PlatformIO\\Projects\\191015-132530-IMU will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\chenerkuo\\Documents\\PlatformIO\\Projects\\191015-132530-IMU\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing OpenIMU300RI (platform: aceinna_imu; board: OpenIMU300)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/aceinna_imu/OpenIMU300.html\r\nPLATFORM: Aceinna IMU 1.2.0 > Aceinna OpenIMU 300ZA\r\nHARDWARE: STM32F405RG 120MHz, 128KB RAM, 1MB Flash\r\nDEBUG: Current (stlink) External (blackmagic, jlink, stlink)\r\nPACKAGES: toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)\r\nLDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf\r\nLDF Modes: Finder ~ chain, Compatibility ~ soft\r\nLooking for OpenIMU300-base-library library in registry\r\nFound: https://platformio.org/lib/show/6538/OpenIMU300-base-library\r\nLibraryManager: Installing id=6538 @ 1.0.8\r\nDownloading...\r\nError: Please read http://bit.ly/package-manager-ioerror\r\nChunkedEncodingError: (\"Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)\", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)):\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 126:\r\n    env.SConscript(\"$BUILD_SCRIPT\")\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 605:\r\n    return _SConscript(self.fs, *files, **subst_kw)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Script\\SConscript.py\", line 286:\r\n    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\platforms\\aceinna_imu\\builder\\main.py\", line 125:\r\n    target_elf = env.BuildProgram()\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 122:\r\n    _build_project_deps(env)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\platformio.py\", line 47:\r\n    project_lib_builder = env.ConfigureProjectLibBuilder()\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\packages\\tool-scons\\script\\..\\engine\\SCons\\Environment.py\", line 224:\r\n    return self.method(*nargs, **kwargs)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 1043:\r\n    project.install_dependencies()\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\tools\\piolib.py\", line 878:\r\n    lm.install(uri)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 359:\r\n    force=force)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 703:\r\n    pkg_dir = self._install_from_piorepo(name, requirements)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\lib.py\", line 220:\r\n    if app.get_setting(\"strict_ssl\") else dl_data['url'], requirements)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 481:\r\n    dlpath = self.download(url, tmp_dir, sha1)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 193:\r\n    raise e\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 179:\r\n    fd.start(with_progress=with_progress)\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\platformio\\downloader.py\", line 83:\r\n    f.write(next(itercontent))\r\n  File \"C:\\Users\\chenerkuo\\.platformio\\penv\\lib\\site-packages\\requests\\models.py\", line 753:\r\n    raise ChunkedEncodingError(e)\r\n========================= [FAILED] Took 28.86 seconds ========================="

**Comment by ivankravets** [comment]
> ConnectionResetError

Do you use Proxy? Please check inernet connection.
