### ISSUE TITLE
Unable to run "remote test" when using latest dev PlatformIO

### ISSUE THREAD

**Issue by drorgl** [platformio/platformio-core#3127]
### Configuration

Windows 10/Linux

PlatformIO, version 4.1.0b4

When attempting to execute tests on latest dev PlatformIO:
```
pio remote test
```

There is an error:
Error: Please upgrade to PlatformIO Core 4.0 or above.

#### Steps to Reproduce

1. update platformio to latest dev ```pio upgrade --dev```
2. have a working agent, e.g.  ```pio remote agent start```
3. attempt to run tests on remote: ```pio remote test```

### Actual Results
Error: Please upgrade to PlatformIO Core 4.0 or above.

### Expected Results
Running the tests

**Comment by ivankravets** [comment]
Thanks for the report! Please re-run `pio update`.
