### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by adi3399** [platformio/platformio-core#3129]
PIO Core Call Error: "Library Storage: C:\\Users\\adi\\.platformio\\lib\nLibraryManager: Installing id=6519 @ ^2.0.0.6\n\n\nError: Could not find a version that satisfies the requirement '^2.0.0.6' for your system 'windows_amd64'"

**Comment by sivar2311** [comment]
There seems to be a problem @ platformio with 4 digit version numbers like "2.0.0.6".
We changed our library to version "2.0.1"
Installation should work now.

**Comment by ivankravets** [comment]
Yes, 2.0.0.6 is not a valid Semantic version. See https://semver.org/
