### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by JugensVan** [platformio/platformio-core#3130]
Server error: {"args":[3,"The system cannot find the path specified"],"message":"[Error 3] The system cannot find the path specified: 'c:\\\\users\\\\jurgens\\\\.platformio\\\\penv\\\\lib\\\\site-packages\\\\platformio\\\\ide\\\\tpls/*.*'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Remove `c:\\users\\jurgens\\.platformio\\penv` fodler
Restart VSCode,

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/issues/3130
