### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by patricphinehas** [platformio/platformio-core#3133]
PIO Core Call Error: "The current working directory /Users/patricphinehasraj/Documents/PlatformIO/Projects/test will be used for the project.\n\nThe next files/directories have been created in /Users/patricphinehasraj/Documents/PlatformIO/Projects/test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing ttgo-t1 (platform: espressif32; board: ttgo-t1; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'ttgo-t1'\n========================== [FAILED] Took 0.70 seconds =========================="

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core/issues/3090
