### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by majay123** [platformio/platformio-core#3135]
PIO Core Call Error: "The current working directory /Users/majay/Documents/PlatformIO/Projects/GD-ESP8266 will be used for the project.\n\nThe next files/directories have been created in /Users/majay/Documents/PlatformIO/Projects/GD-ESP8266\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing gd32v\ngd32v @ 1.1.0 has been successfully installed!\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/sipeed/platform-gd32v/issues/6
