### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by FailSafinho** [platformio/platformio-core#3136]
Operative System: Windows 10
Issue: Cannot initialize a project. It is using an ICE40HX1K-STICK-EVN board and as soon as I try to start a new project I have that error also. I also noticed that the Framework field is empty.

PIO Core Call Error: "The current working directory \\\\xxxxx\\PlatformIO\\Projects\\Led1 will be used for the project.\r\n\r\nThe next files/directories have been created in \\\\xxxxx\\PlatformIO\\Projects\\Led1\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing icestick (platform: lattice_ice40; board: icestick)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\n\r\n*** Import of non-existent variable ''projenv''\r\nFile \"C:\\Users\\xxxxxxx\AppData\\Roaming\\SPB_16.6\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 163, in <module>\r\n========================== [FAILED] Took 2.23 seconds =========================="

**Comment by ivankravets** [comment]
It seems you have multiple PIo Cores in system http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
