### ISSUE TITLE
Detected unknown package 'tool-scons'

### ISSUE THREAD

**Issue by KorishPal** [platformio/platformio-core#3138]
PIO Core Call Error: "The current working directory C:\\Users\\igorwin\\Documents\\PlatformIO\\Projects\\191017-182354-uno will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\igorwin\\Documents\\PlatformIO\\Projects\\191017-182354-uno\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\nPlatformManager: Installing atmelavr\r\natmelavr @ 1.15.0 has been successfully installed!\r\nPackageManager: Installing toolchain-atmelavr @ ~1.50400.0\r\ntoolchain-atmelavr @ 1.50400.190710 has been successfully installed!\r\nThe platform 'atmelavr' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Detected unknown package 'tool-scons'"

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
