### ISSUE TITLE
Home: PIO Core Call Error: "cannot import name threadpool"

### ISSUE THREAD

**Issue by kasapisthan** [platformio/platformio-core#3141]
PIO Core Call Error: "cannot import name 'threadpool'"

**Comment by ivankravets** [comment]
What is your OS?

**Comment by kasapisthan** [comment]
Windows 10.the problem solved after  restarting my PC.
Best regards


Στις Κυρ, 20 Οκτ 2019, 2:50 μ.μ. ο χρήστης Ivan Kravets <
notifications@github.com> έγραψε:

**Comment by ivankravets** [comment]
Could you try this solution https://github.com/platformio/platformio-vscode-ide/issues/1259#issuecomment-545377055 ?
