### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by DaQue** [platformio/platformio-core#3155]
PIO Core Call Error: "framework-arduinosam @ 4.4.191002 has been successfully installed!\r\n========================= [SUCCESS] Took 63.53 seconds =========================\r\n\r\nEnvironment                    Status    Duration\r\n-----------------------------  --------  ------------\r\nadafruit_circuitplayground_m0  SUCCESS   00:01:03.531\r\nadafruit_feather_m0            IGNORED\r\nadafruit_itsybitsy_m0          IGNORED\r\nadafruit_metro_m4              IGNORED\r\ndue                            IGNORED\r\ndueUSB                         IGNORED\r\ndigix                          IGNORED\r\nmkr1000USB                     IGNORED\r\nmkrzero                        IGNORED\r\nmzeropro                       IGNORED\r\nmzeroUSB                       IGNORED\r\nsodaq_autonomo                 IGNORED\r\nsparkfun_samd21_mini_usb       IGNORED\r\ntian                           IGNORED\r\nzero                           IGNORED\r\nzeroUSB                        IGNORED\r\n========================= 1 succeeded in 00:01:03.531 ========================="

**Comment by ivankravets** [comment]
Could you reproduce this issue after VSCode restart?

**Comment by ivankravets** [comment]
Please reopen if you still need help
