### ISSUE TITLE
Home: Could not list directory/Users/luyuan/Documents/PlatformIO/Projects

### ISSUE THREAD

**Issue by Echanging** [platformio/platformio-core#3166]
Server error: {"args":[1,"Operation not permitted"],"message":"[Errno 1] Operation not permitted: '/Users/luyuan/Documents/PlatformIO/Projects'","type":"PermissionError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3167
