### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by atyanands** [platformio/platformio-core#3169]
Server error: {"args":[2,"The system cannot find the file specified"],"message":"[WinError 2] The system cannot find the file specified: 'C:\\\\Users\\\\Anand\\\\Documents\\\\PlatformIO\\\\Projects'","type":"FileNotFoundError"}

**Comment by ivankravets** [comment]
This is a known issue when antivirus tools block PlatformIO. Please disable them for a while
