### ISSUE TITLE
Home: Libraries: Could not update library

### ISSUE THREAD

**Issue by knopserl** [platformio/platformio-core#3171]
PIO Core Call Error: "Library Storage: C:\\Users\\internet\\.platformio\\lib\r\nUpdating littlevgl_sdl_drivers           @ 1.1            [1.1.8]\r\nUninstalling littlevgl_sdl_drivers @ 1.1: \t[OK]\r\nLooking for littlevgl_sdl_drivers library in registry\r\n\n\nError: Library `{'name': 'littlevgl_sdl_drivers', 'requirements': '1.1.8'}` has not been found in PlatformIO Registry.\r\nYou can ignore this message, if `{'name': 'littlevgl_sdl_drivers', 'requirements': '1.1.8'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc."

**Comment by ivankravets** [comment]
There is no `littlevgl_sdl_drivers` library in our registry.
