### ISSUE TITLE
Home: Could not import project

### ISSUE THREAD

**Issue by 237833645** [platformio/platformio-core#3173]
PIO Core Call Error: "The current working directory C:\\Users\\WANGFENG\\Documents\\PlatformIO\\Projects\\191021-174313-espidf-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\WANGFENG\\Documents\\PlatformIO\\Projects\\191021-174313-espidf-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp-wrover-kit (platform: espressif32; framework: espidf; board: esp-wrover-kit)\r\n--------------------------------------------------------------------------------\r\nframework-espidf @ 3.30300.190916 has been successfully installed!\r\nCorePackageManager: Installing tool-scons @ ~3.30101.0\r\ntool-scons @ 3.30101.0 has been successfully installed!\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp-wrover-kit.html\r\nPLATFORM: Espressif 32 1.11.0 > Espressif ESP-WROVER-KIT\r\nHARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (ftdi) On-board (ftdi) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: toolchain-xtensa32 2.50200.80 (5.2.0), framework-espidf 3.30300.190916 (3.3.0), tool-esptoolpy 1.20600.0 (2.6.0)\r\nCONFIGURATION: https:

**Comment by ivankravets** [comment]
Download this project manually and import in VSCode https://github.com/platformio/platform-espressif32/tree/develop/examples/espidf-blink
