### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by ndtcenter** [platformio/platformio-core#3175]
Server error: {"args":[2,"系统找不到指定的文件。"],"message":"[WinError 2] 系统找不到指定的文件。: 'C:\\\\Users\\\\yujin\\\\Documents\\\\PlatformIO\\\\Projects\\\\pio053ardudemo1'","type":"FileNotFoundError"}

failed on creating an arduino project .

platformio ver 1.9.2
win10 home

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/issues/3174
