### ISSUE TITLE
cannot import name 'threadpool' from 'twisted.python

### ISSUE THREAD

**Issue by marcus266** [platformio/platformio-core#3176]
PIO Core Call Error: "cannot import name 'threadpool' from 'twisted.python' (unknown location)"

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3189
