### ISSUE TITLE
'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by vlapa1973** [platformio/platformio-core#3179]
'ascii' codec can't decode byte 0xd1 in position 54: ordinal not in range(128)

**Comment by ivankravets** [comment]
What is your OS?

**Comment by vlapa1973** [comment]
MacOS Catalina 10.15

**Comment by ivankravets** [comment]
Please provide an output from `~/.platformio/penv/bin/python —version`?

**Comment by vlapa1973** [comment]
Python 2.7.16 (v2.7.16:413a49145e, Mar  2 2019, 14:32:10) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by ivankravets** [comment]
Could you install Python 3 from https://www.python.org/downloads/?
After installing please remove `~/.platformio/penv` folder and test again
```
~/.platformio/penv/bin/python --version
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
