### ISSUE TITLE
Invalid encoding for project files for Visual Studio 

### ISSUE THREAD

**Issue by antipin00** [platformio/platformio-core#3183]
What kind of issue is this?

-  **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 x64

**PlatformIO Version** (`platformio --version`): 4.0.3

### Description of problem
When generating project files for Visual Studio, PIO adds 6 bytes `C3 AF C2 BB C2 BF` at the beginning of `platformio.vcxproj` and `platformio.vcxproj.filters` files. These 6 bytes, if decoded as UTF-8, become characters `ï»¿`, which look exactly like UTF-8 Byte Order Mark [decoded using CP1252](https://en.wikipedia.org/wiki/Byte_order_mark#Byte_order_marks_by_encoding).
Trying to open the project file in Visual Studio 2019 as is gives the following error:
![image](https://user-images.githubusercontent.com/17460779/67426971-d3b8dd80-f5e3-11e9-9e9a-733725804f4e.png)
Removing these 6 bytes or replacing them with `EF BB BF`, a correct value for UTF-8 BOM, fixes it.

#### Steps to Reproduce

1. `mkdir test`
2. `cd test`
3. `platformio init --ide visualstudio -b uno`

### Actual Results
platformio.vcxproj (as UTF-8)
```
ï»¿<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
   ...
```

### Expected Results
platformio.vcxproj (as UTF-8)
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="12.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
   ...
```

### Additional info
Python 3.7.3
Visual Studio Community 16.3.6

**Comment by ivankravets** [comment]
@valeros could you reproduce it?

**Comment by valeros** [comment]
Many thanks for reporting! Fixed in the development branch.
