### ISSUE TITLE
cannot import name threadpool

### ISSUE THREAD

**Issue by issacpena** [platformio/platformio-core#3184]
PIO Core Call Error: "cannot import name threadpool"

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by issacpena** [comment]
It looks like a temp issue with my laptop, it is working properly now, sorry for the noise.


Issac Peña

 

    El jueves, 24 de octubre de 2019 10:23:58 GMT-6, Ivan Kravets <notifications@github.com> escribió:  
 
 
Please provide an output from system Terminal cmd
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list

**Comment by ivankravets** [comment]
How did you resolve it?

**Comment by issacpena** [comment]
Yes, I close VS and open again, I wait a few minutes in order to allow PIO to load all the dependencies, after that, it worked properly.
I think my PC had an unusual work load.
Thank you


Issac Peña

 

    El jueves, 24 de octubre de 2019 10:44:32 GMT-6, Ivan Kravets <notifications@github.com> escribió:  
 
 
How did you resolve it?
