### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by MengYang37** [platformio/platformio-core#3191]
PIO Core Call Error: "The current working directory C:\\Users\\MengYang\\Documents\\PlatformIO\\Projects\\191026-161037-arduino-blink will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\MengYang\\Documents\\PlatformIO\\Projects\\191026-161037-arduino-blink\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Could not install 'toolchain-xtensa' with version requirements '<3' for your system 'windows_amd64'.\r\n\r\nPlease try this solution -> http://bit.ly/faq-package-manager"

**Comment by ivankravets** [comment]
1. Please check your Internet connection
2. Please check that firewall or antivirus tools do not block PlatformIO
