### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by andrecouceiro6** [platformio/platformio-core#3194]
PIO Core Call Error: "********************************************************************************\nObsolete PIO Core v4.0.3 is used (previous was 4.1.0b4)\nPlease remove multiple PIO Cores from a system:\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\n********************************************************************************\n\nThe current working directory /Users/andrecouceiro/Documents/PlatformIO/Projects/test1 will be used for the project.\n\nThe next files/directories have been created in /Users/andrecouceiro/Documents/PlatformIO/Projects/test1\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing uno (platform: atmelavr; board: uno; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\n  File \"/Users/andrecouceiro/.platformio/platforms/atmelavr/builder/main.py\", line 30\n\n    print \"Please unplug/plug device ...\"\n\n                                        ^\n\nSyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"Please unplug/plug device ...\")?\n\n========================== [FAILED] Took 3.68 seconds =========================="

**Comment by ivankravets** [comment]
PIO Home > Platforms > Updates
