### ISSUE TITLE
Home: Could not import Arduino project

### ISSUE THREAD

**Issue by smagghe** [platformio/platformio-core#3199]
Server error: {"args":[2,"Le fichier spécifié est introuvable"],"message":"[Error 2] Le fichier spécifié est introuvable: u'C:\\\\Users\\\\gabri\\\\Documents\\\\PlatformIO\\\\Projects\\\\191027-225354-d1_mini'","type":"WindowsError"}

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3174
