### ISSUE TITLE
Home: Libraries: Could not install library

### ISSUE THREAD

**Issue by GarMingLi** [platformio/platformio-core#3203]
PIO Core Call Error: "Library Storage: C:\\Users\\shaoy\\.platformio\\lib\nLibraryManager: Installing id=431 @ ^0.3.9.2\n\n\nError: Could not find a version that satisfies the requirement '^0.3.9.2' for your system 'windows_amd64'"

**Comment by ivankravets** [comment]
Fixed in PIO Home 3.0. The final release is coming soon.
