### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by victorromeo** [platformio/platformio-core#3206]
PIO Core Call Error: "The current working directory /home/ian/Documents/Arduino/Wemos/WemosElements will be used for the project.\n\nThe next files/directories have been created in /home/ian/Documents/Arduino/Wemos/WemosElements\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing wemos_d1_mini32 (platform: espressif32; board: wemos_d1_mini32; framework: arduino)\n--------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\nError: Unknown board ID 'wemos_d1_mini32'\n========================== [FAILED] Took 0.31 seconds =========================="

**Comment by ivankravets** [comment]
PIO Home > Platforms > Updates. Update all dev/platforms.
