### ISSUE TITLE
change Sequence of linker parameters and object files 

### ISSUE THREAD

**Issue by haarer** [platformio/platformio-core#3208]
**PlatformIO Core**

------------------------------------------------------------------

### Configuration
**Operating system**:
```
uname -a
Linux gore 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
```
**PlatformIO Version** 
```
platformio --version
PlatformIO, version 4.1.0rc2
```
### Description of problem
Currently the object files  are inserted after the linker flags. This is a problem when using linker scripts that define symbols. The symbols are not found.
#### Steps to Reproduce
**Test**
------------------------------------------------------------------
 Set Linker Flags as follows
```
env.Append(
  LINKFLAGS=[
      "-Wl,--script=bcc.ld,-Map=m68k-test.map,--allow-multiple-definition"
  ]
)
```
Build (pio uses the following command line for linking)

```
m68k-elf-gcc -o .pio/build/ttt/firmware.elf -m68332 -g -Wl,--script=bcc.ld,-Map=m68k-test.map,--allow-multiple-definition --verbose .pio/build/ttt/src/main.o -L.pio/build/ttt
```
The result is, that the symbols sbrk (and others) are not found.
```
/home/mac/.platformio/packages/toolchain-m68k-elf-current/bin/../lib/gcc/m68k-elf/9.2.0/../../../../m68k-elf/bin/ld: /home/mac/.platformio/packages/toolchain-m68k-elf-current/bin/../lib/gcc/m68k-elf/9.2.0/../../../../m68k-elf/lib/mcpu32/libc.a(lib_a-sbrkr.o): in function `_sbrk_r':
/home/mac/projects/toolchain68k/cross-toolchain/newlib-3.1.0/cross-chain-m68k-elf-obj/m68k-elf/mcpu32/newlib/libc/reent/../../../../../../newlib/libc/reent/sbrkr.c:51: undefined reference to `sbrk'
```
Manually changing the sequence fixes the problem
```
m68k-elf-gcc  .pio/build/ttt/src/main.o   -m68332 -g  -Wl,--script=bcc.ld,-Map=m68k-test.map,--allow-multiple-definition -L. -o m68k-test.elf
```

### Actual Results
Cant link with linker scripts passed by LINKFLAGS

### Expected Results
Can link with linker scripts passed by LINKFLAGS

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:ttt]
platform = https://github.com/haarer/platform-m68k.git
board = GenericM68332
```

**Source file to reproduce issue:**
```cpp
#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("Hello world\n");
  for(;;);
  //return 0;
}

```

**Comment by valeros** [comment]
Hi @haarer ! Thanks for reporting. Linker flags after sources is default behavior for SCons build system. If you want to change it you can try something like this in your build script:
```
env.Replace(
    LINKCOM=("$LINK -o $TARGET $__RPATH ${_long_sources_hook(__env__, SOURCES)}"
             " $LINKFLAGS $_LIBDIRFLAGS $_LIBFLAGS")
)
```
