### ISSUE TITLE
Home: Libraries: Stats

### ISSUE THREAD

**Issue by jhonatas336** [platformio/platformio-core#3211]
PIO Core Call Error: "Error: [API] Invalid response: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\"><html><head><meta http-equiv=\"Expires\" content=\"-1\"><meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Cache-Control\" content=\"no-cache\"><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta name='id' content='siteBlocked'><title>Web Site Blocked</title><meta name='ip' content='172.16.32.254'></head><body bgcolor=\"#005d84\"><center><div style=\"background:#fff;border-radius:8px;padding:48px;width:275px;margin:72px auto;font:14px sans-serif;text-align:left\"><center></center><img style=\"float:left;margin:7px 7px 0 -3px\" src=\"data:image/gif;base64,R0lGODlhGAAYAJEAAP///9sbIeVUWfOsriH5BAAAAAAALAAAAAAYABgAAAJchG8jErGDYmStWiHRsJxDuXVi8x3hOJYAuqAH1X0nh61p4s4ensIxL2rdALoLKiA7HpOso3D0VEKLFcFAgYJkgR2Dz8Ls1Gzi67eikf7SalKGKlJJzpfMW/iwFwAAOw==\"><div style=\"font-weight:bold;word-wrap:break-word;margin-top:7px;padding-left:28px;\"><div id=\"alert_text\">This site has been blocked by the network administrator.</div></div><div style=\"word-wrap:break-word;margin-top:8px;padding-left:28px;font-size:13px\"><div style=\"margin-bottom:8px\">Block reason: Gateway GEO-IP Filter Alert</div><div style=\"margin-bottom:8px\">IP address: 31.28.1.238</div><div>Connection initiated towards country: Russian Federation</div></div></div></ce

**Comment by ivankravets** [comment]
> Block reason: Gateway GEO-IP Filter Alert. Connection initiated towards country: Russian Federation

Sorry for this issue. Our server is located in Ukraine, not in Russia. Please remove this IP from the black list.
