### ISSUE TITLE
platformio.ini lost semicolon separated comments support

### ISSUE THREAD

**Issue by dontsovcmc** [platformio/platformio-core#3213]
Visual studio code platformio extension lost semicolon separeted comments support.

### Configuration
Home 2.3.3 Core 4.0.3
PACKAGES: toolchain-xtensa32 2.50200.80 (5.2.0), framework-arduinoespressif32 2.10004.191002 (1.0.4), tool-esptoolpy 1.20600.0 (2.6.0)
**Operating system**: MacOS

### Description of problem

Bad content of `platformio.ini`:**
```[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev

upload_port = /dev/cu.wchusbserial1420 
upload_speed = 115200  ; раньше это компилировалось
```

Good:**
```[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev

upload_port = /dev/cu.wchusbserial1420 
; теперь комментарии должны быть на отдельной строке
upload_speed = 115200  
```

I think the reason is tool-scons:
tool-scons ~2.20501.7 is support semicolons

tool-scons 3.30101.0 NOT:
`Error: Invalid value: 115200  ; раньше это компилировалось is not a valid integer for option `upload_speed` in section [env:esp32dev]`

**Comment by ivankravets** [comment]
Thanks! Interesting bug. Python 3 has different behavior for RAW config parsing and does not handle inline comments. We will work on a fix for this.

**Comment by ivankravets** [comment]
You can re-test with `pio upgrade --dev`.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/1d5d09feab2640d372e42744e12356605d84e697
