### ISSUE TITLE
Home: Error occurred while requesting content from https://raw.githubusercontent.com/olikraus/U8g2_Arduino/master/library.properties

### ISSUE THREAD

**Issue by chenliyang** [platformio/platformio-core#3215]
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /olikraus/U8g2_Arduino/master/library.properties (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005835518>: Failed to establish a new connection: [Errno 10061] ',))

**Comment by ivankravets** [comment]
or('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005835518>: Failed to establish a new connection: [Errno 10061] ',))


Please check Internet connection
