### ISSUE TITLE
FR - Warning if `lib_compat_mode` excludes a library

### ISSUE THREAD

**Issue by pfeerick** [platformio/platformio-core#3217]
What kind of issue is this?

- [x] **Feature Request**

---

It seems that both the `soft` (default) and `strict` `lib_compat_mode` modes will automatically prevent incompatible libraries specified via `lib_deps` from being used... without any information statements to indicate this. This became apparent when a user was trying to work on a project without using a framework, and since the default `soft` mode checks for a compatible framework, it omitted libraries specified via `lib_deps` with no warning. 

This FR makes two requests:
- show a message saying that a explicitly included library has been excluded because of the compatibility check 
- `lib_compat_mode` should act as if it were `off` if there’s no framework specified - i.e. don't do the framework compatibility check if there's no framework!

Forum ref: https://community.platformio.org/t/lib-deps-not-included-should-warn-about-compatibility/10270

**Comment by ivankravets** [comment]
Resolved in https://community.platformio.org/t/lib-deps-not-included-should-warn-about-compatibility/10270/5?u=ivankravets
