### ISSUE TITLE
Linter error in Spackfun boards

### ISSUE THREAD

**Issue by MarioJose** [platformio/platformio-core#3218]
Linter get error when using "sparkfun_promicro8" board:

```
avr-g++: error: Pro: No such file or directory avr-g++: error: Micro": No such file or directory
```

Because that, all the code line isn't checked for error.

I changed line 25 in ".platformio/platforms/atmelavr/boards/sparkfun_promicro8.json"

from:
```
    "usb_product": "SparkFun Pro Micro",
```

to:
```
    "usb_product": "SparkFunProMicro",
```

and problem is [solved](https://community.platformio.org/t/linter-error-when-using-spakfun-boards/10260).

Maybe this problem is related with [this](https://github.com/hebaishi/linter-gcc/issues/23) issue.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.
