### ISSUE TITLE
PIO Remote Device List returns error

### ISSUE THREAD

**Issue by samisabik** [platformio/platformio-core#3220]
**Mac OS Version 10.14.6**:

**PlatformIO, version 4.0.3** 

### Description of problem

When sending a `platformio remote device list` pio returns :
`sequence item 2: expected str instance, bytes found`

However, I have been running on the remote agent,`platformio remote device list`
and successfully listed the available devices :

> /dev/cu.Bluetooth-Incoming-Port
> Hardware ID: n/a
> Description: n/a
> 
> /dev/cu.D32-L-SerialPort
> Hardware ID: n/a
> Description: n/a

**Comment by ivankravets** [comment]
You must use the same major Python version on both sides. For example, Python 2 for server+ client, or Python 3 for server and client.
