### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by hblslt** [platformio/platformio-core#3221]
PIO Core Call Error: "********************************************************************************\r\nObsolete PIO Core v4.0.3 is used (previous was 4.1.0rc1)\r\nPlease remove multiple PIO Cores from a system:\r\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\r\n********************************************************************************\r\n\r\nThe current working directory D:\\Users\\Documents\\PlatformIO\\Projects\\tts will be used for the project.\r\n\r\nThe next files/directories have been created in D:\\Users\\Documents\\PlatformIO\\Projects\\tts\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Detected unknown package 'framework-stm32cube'"

**Comment by ivankravets** [comment]
> Detected unknown package 'framework-stm32cube'

It seems like an issue with Internet connection. try to restart VSCode.
