### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by oscarmh** [platformio/platformio-core#3224]
PIO Core Call Error: "Platform /Users/oscarmh/.platformio/platforms/espressif32@src-954eb7597124cde84510c6cdfe58b713\n--------\nUpdating espressif32                     @ 671234e        [685e78f]\n\n\nError: Please install Git client from https://git-scm.com/downloads"

**Comment by ivankravets** [comment]
Error: Please install Git client from https://git-scm.com/downloads
