### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by WarlockD** [platformio/platformio-core#3225]
PIO Core Call Error: "The current working directory C:\\Users\\warlo\\Documents\\PlatformIO\\Projects\\UpDuo test will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\warlo\\Documents\\PlatformIO\\Projects\\UpDuo test\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\nPlatformManager: Installing lattice_ice40\nlattice_ice40 @ 1.2.2 has been successfully installed!\nPackageManager: Installing toolchain-icestorm @ ~1.10.0\r\ntoolchain-icestorm @ 1.10.1 has been successfully installed!\nPackageManager: Installing toolchain-iverilog @ ~1.1.0\r\ntoolchain-iverilog @ 1.1.0 has been successfully installed!\nThe platform 'lattice_ice40' has been successfully installed!\r\nThe rest of packages will be installed automatically depending on your build environment.\r\n\n\nError: Processing icestick (platform: lattice_ice40; board: icestick)\n-------------------------------------------------------------------------------\nVerbose mode can be enabled via `-v, --verbose` option\n---> WARNING: no .pcf file found\n\n*** Import of non-existent variable ''projenv''\nFile \"C:\\Users\\warlo\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 163, in <module>\n========================= [FAILED] Took 4.39 seconds ========================="

**Comment by ivankravets** [comment]
Please upgrade PIO Core to the latest version
