### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by rmaltais** [platformio/platformio-core#3231]
PIO Core Call Error: "Library Storage: D:\\Users\\Réjean Maltais\\Documents\\Ender_3_mat\\Marlin-bugfix-2.0.x\\.pio\\libdeps\\megaatmega2560\n\n\nError: Traceback (most recent call last):\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 90, in main\n    cli(None, None, None)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\__init__.py\", line 37, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\click\\decorators.py\", line 17, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\platformio\\commands\\lib.py\", line 253, in lib_update\n    lm.update(library, only_check=only_check)\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 773, in update\n    pkg_dir = self.get_package_dir(*self.parse_pkg_uri(package))\n  File \"c:\\.platformio\\penv\\lib\\site-packages\\platformio\\managers\\package.py\", line 237, in parse_pkg_uri\n    text = str(text)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xe9' in position 10: ordinal not in range(128)\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
echo %PYTHONPATH%
python --version
pip --version
pip list
```

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by gorrioncillo** [comment]
Sorry for opening this threat
I have the same problem when I search for `pio lib search arduinojson`
`UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 75: character maps to <undefined>`

I use platformio installed from recommend script and on `~/.platformio` as and venv on windows 10 SO.
python --version
`python 3.7.2`
pip --version
`pip 20.3.1`

**Comment by ivankravets** [comment]
Could you provide any links to this library?

**Comment by gorrioncillo** [comment]
> Could you provide any links to this library?

Of course
https://libraries.io/platformio/ArduinoJson

**Comment by ivankravets** [comment]
Sorry, I can't reproduce it in the Windows virtual machine. It seems you have multiple Pythons in the system and Python 2 is used. I  recommend to UNINSTALL all Pythons, remove `~/.platformio/penv` folder and restart VSCode.

![Screen Shot 2020-12-23 at 14 01 53](https://user-images.githubusercontent.com/1760209/102994293-7a21ab00-4527-11eb-8b41-da81a213ebc2.png)

![Screen Shot 2020-12-23 at 14 02 11](https://user-images.githubusercontent.com/1760209/102994305-7e4dc880-4527-11eb-9110-9a6466b71ab2.png)

**Comment by gorrioncillo** [comment]
I use only python 3.7 in windows 10 with platformio core on a terminal (the terminal taht comes with git for windows, mintty i thing)
Do not use vsCode
Using ``pio home`` do not show any error, as you show on that pictures
