### ISSUE TITLE
Home: Could not install platform

### ISSUE THREAD

**Issue by marchold** [platformio/platformio-core#3232]
I was trying to connect to a Longan nano and got this error installing. I was on a Mac OS 10.13.16

PIO Core Call Error: "PlatformManager: Installing gd32v\ngd32v @ 1.1.0 is already installed\nPackageManager: Installing toolchain-gd32v @ ~9.2.0\n\n\nError: Could not find a version that satisfies the requirement '~9.2.0' for your system 'darwin_x86_64'"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/sipeed/platform-gd32v/issues/6
