### ISSUE TITLE
Can not find active PlatformIO project.

### ISSUE THREAD

**Issue by Jeronimo016** [platformio/platformio-core#3236]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Window 10 Pro

**PlatformIO Version** (`platformio --version`): 2.3.3 --4.0.3

### Description of problem
When I try to build or compile the next message apear:
Make sure that an opened project you are trying to rebuid is a PlatformIO project (e.g., contains `platformio.ini`).

#### Steps to Reproduce

1.Create a Project
2.Write some Code
3.Try to Compile

### Actual Results
Error. And cant compile

### Expected Results
Compile

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
;PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp12e]
platform = espressif8266
board = esp12e
framework = arduino

```

**Source file to reproduce issue:**
```cpp
#define BLYNK_PRINT Serial
#include <Arduino.h>
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

const char id[3][33] = {"wSVzLCg4iXwFISc9UCQ3yj5qqZFtzY_N", "Fibertel WiFi381 5.8GHz", "0042071630"};
WiFiClient client;


BLYNK_WRITE(V2){
  int status = param.asInt();
  if (status == 1) {
    Serial.print(status);
  }else Serial.print(status);
}

void setup() {
  Serial.begin(9600);
  Blynk.begin(id[0], id[1], id[2]);
  delay(10);
}

void loop() {
Blynk.run();
}
```

### Additional info
![Screenshot (29)](https://user-images.githubusercontent.com/45039865/68091873-096f8900-fe64-11e9-8b4b-095b24042e43.png)

**Comment by ivankravets** [comment]
PlatformIO project should be in the ROOT of file explorer. Currently, it's placed in the CasaAutonam.

P.S: Please switch to VSCode. It will not allow you to do this mistake.
