### ISSUE TITLE
Home: Libraries: Search, cannot search for libraries

### ISSUE THREAD

**Issue by Mimile-Ali** [platformio/platformio-core#3244]
PIO Core Call Error: "Error: You are not connected to the Internet.\r\nIf you build a project first time, we need Internet connection to install all dependencies and toolchains."

Using PlatformIO on VS and I cannot search for any libraries.

**Comment by Mimile-Ali** [comment]
Also, I am connected...

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/1348
