### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by jonkiszp** [platformio/platformio-core#3247]
PIO Core Call Error: "Platform /home/pawel/.platformio/platforms/espressif32@src-5f117260f75b328038ec9d3fd0e14a68\n--------\nUpdating espressif32                     @ 685e78f        [f2f3285]\n\n\nError: Please install Git client from https://git-scm.com/downloads"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2811
