### ISSUE TITLE
Home: Could not load platform data

### ISSUE THREAD

**Issue by llino** [platformio/platformio-core#3248]
PIO Core Call Error: "Platform /Users/lenny/.platformio/platforms/espressif32@src-954eb7597124cde84510c6cdfe58b713\n--------\nUpdating espressif32                     @ 685e78f        [f2f3285]\n\n\nError: Please install Git client from https://git-scm.com/downloads"

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/2811
