### ISSUE TITLE
pio init --ide clion ... Error: 'set' object does not support indexing

### ISSUE THREAD

**Issue by teoman002** [platformio/platformio-core#3251]
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Linux Mint 19.2 / Ubuntu

**PlatformIO Version** (`platformio --version`): 4.0.3

### Description of problem

I want to port a platformIO project from VScode IDE to Clion IDE.
However, I encounter an error by typing 'pio init --ide clion'

#### Steps to Reproduce

1. Download this project https://github.com/littlevgl/lv_platformio
2. Go into project folder and do a pio init --ide clion

### Actual Results

```
File "/home/username/.local/bin/bottle.py", line 3400, in execute
    eval(self.co, env)
  File "<string>", line 64, in <module>
  File "/home/username/.local/lib/python2.7/site-packages/platformio/project/helpers.py", line 220, in load_project_ide_data
    if len(envs) == 1 and envs[0] in data:
TypeError: 'set' object does not support indexing
```

### Expected Results

`Initialization successful`

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[platformio]
default_envs = native

[env:native]
platform = native
build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  ; -I src Required to find lv_conf.h
  -I src
  -I drivers/sdl2
  -lSDL2
  ; SDL drivers options
  -D LV_LVGL_H_INCLUDE_SIMPLE
  -D LV_DRV_NO_CONF
  -D USE_MONITOR
  -D MONITOR_ZOOM=2
  -D USE_MOUSE
  -D USE_MOUSEWHEEL
  -D USE_KEYBOARD
lib_deps =
  ;lvgl=https://github.com/littlevgl/lvgl/archive/master.zip
  lvgl@^6.0.2
  ;lv_drivers=https://github.com/littlevgl/lv_drivers/archive/master.zip
  lv_drivers@^6.0.2
src_filter = +<*> +<../drivers/sdl2>

[env:stm32f429_disco]
platform = ststm32
board = disco_f429zi
framework = stm32cube
build_flags =
  -D LV_CONF_INCLUDE_SIMPLE
  -D HSE_VALUE=12000000
  -I src
  -I drivers/stm32f429_disco
lib_deps =
  lvgl@^6.0.2
src_filter = +<*> +<../drivers/stm32f429_disco>

```

**Source file to reproduce issue:**

`No source file necessary`

**Comment by ivankravets** [comment]
It's fixed in the dev version which is planned for release today. You can re-test with `pio upgrade --dev`.
