### ISSUE TITLE
PROJECTPACKAGES_DIR empty

### ISSUE THREAD

**Issue by MarkJeronimus** [platformio/platformio-core#3267]
The platformio.ini variable `PROJECTPACKAGES_DIR` doesn't resolve anymore in VSCode IDE since last night's update (code 4.1.0, plugin v1.9.3).

Off-topic: I also had to uninstall and re-install PlatformIO in VSCode to fix some serious sqlite problems.

According to the [manual](https://docs.platformio.org/en/latest/projectconf/section_platformio.html#projectconf-pio-packages-dir), `PROJECTPACKAGES_DIR` should resolve to “core_dir/packages”. In my experience this is "~/.platformio/packages". Previously it resolved to this, but now it resolves to "".

The aforementioned problems only exist on my Ubuntu machine. On my W10 machine there are no problems.

This bug prevents me from using custom avrdude parameters.

Excerpt from my platformio.ini:

```prefs
upload_flags =
    -C$PROJECTPACKAGES_DIR/tool-avrdude/avrdude.conf
    -P$UPLOAD_PORT
    -c$UPLOAD_PROTOCOL
    -b$UPLOAD_SPEED
    -patmega328p
    -V
upload_command = avrdude $UPLOAD_FLAGS -U flash:w:$SOURCE:i
```

Error I'm getting:

> avrdude: can't open config file "/tool-avrdude/avrdude.conf": No such file or directory
> avrdude: error reading system wide configuration file "/tool-avrdude/avrdude.conf"

**Comment by ivankravets** [comment]
It should be `PROJECT_PACKAGES_DIR`. See https://github.com/platformio/platformio-core/blob/develop/platformio/builder/main.py#L104

**Comment by MarkJeronimus** [comment]
Thanks, it works.

Changes like these should be put in the release notes and the manual updated in tandem with the update rollout.

**Comment by ivankravets** [comment]
It was changed in PIO Core 4.0. We totally refactored project configuration. We don't plan to change these variables in future. Sorry for the issue.

**Comment by MarkJeronimus** [comment]
If the update is that big, it should be able to migrate project configuration to the new format (after user confirmation)

**Comment by ivankravets** [comment]
We have it, maybe, not so much clear http://docs.platformio.org/en/latest/migration.html

**Comment by MarkJeronimus** [comment]
- I can't find PROJECTPACKAGES_DIR or even "PROJECT_PACKAGES_DIR" on that page
- When I click on the platformio.ini item it takes me to the old ('latest') manual with PROJECTPACKAGES_DIR
- When I go to the release notes, I already read that and it doesn't seem to contain anything relevant to this

**Comment by MarkJeronimus** [comment]
Sorry if I sound angry, I'm not. It's just that with great projects (and this is one heck of a great project) comes great responsibility.

**Comment by ivankravets** [comment]
I've just fixed docs https://github.com/platformio/platformio-docs/commit/a6c6b4a80591388e3b76c04bec7920aed13ed851

> Sorry if I sound angry

Everything is OK, this open-source project. We would be thankful if you help us to improve current documentation https://github.com/platformio/platformio-docs
