### ISSUE TITLE
Home: Could not initialize project

### ISSUE THREAD

**Issue by moranfarky** [platformio/platformio-core#3269]
PIO Core Call Error: "********************************************************************************\r\nObsolete PIO Core v4.0.3 is used (previous was 4.1.0b4)\r\nPlease remove multiple PIO Cores from a system:\r\nhttps://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system\r\n********************************************************************************\r\n\r\nThe current working directory C:\\Users\\moran\\Documents\\PlatformIO\\Projects\\ESP_IDF_SDCARD will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\moran\\Documents\\PlatformIO\\Projects\\ESP_IDF_SDCARD\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Traceback (most recent call last):\r\n  File \"C:\\Users\\moran\\.platformio\\penv\\lib\\site-packages\\platformio\\__main__.py\", line 90, in main\r\n    click.echo = lambda *args, **kwargs: _safe_echo(0, *args, **kwargs)\r\n  File \"C:\\Users\\moran\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 764, in __call__\r\n    return self.main(*args, **kwargs)\r\n  File \"C:\\Users\\moran\\.platformio\\penv\\lib\\site-packages\\click\\core.py\", line 717, in main\r\n    rv = self.invoke(ctx)\r\n  File \"C:\\Users\\moran\\.platformio\\penv\\lib\\site-packages\\p

**Comment by ivankravets** [comment]
Please update PIO Core to 4.1
```
pio update
```
