### ISSUE TITLE
PIO Remote macOS bug

### ISSUE THREAD

**Issue by tanishqaggarwal** [platformio/platformio-core#3272]
What kind of issue is this?

- [x ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**: macOS Catalina (10.15.1) and Windows 10

**PlatformIO Version** (`platformio --version`): 4.1.0

```
~ pio update
Updating contrib-piohome                 @ 3.0.1          [Up-to-date]
Updating contrib-pysite                  @ 2.36.191017    [Up-to-date]
Updating tool-pioplus                    @ 2.6.0          [Up-to-date]
Updating tool-unity                      @ 1.20403.0      [Up-to-date]
Updating tool-scons                      @ 3.30101.0      [Up-to-date]

Platform Manager
================
Platform Native
--------
Updating native                          @ 1.1.1          [Up-to-date]

Platform Teensy
--------
Updating teensy                          @ 4.6.0          [Up-to-date]
Updating toolchain-gccarmnoneeabi        @ 1.50401.190816 [Up-to-date]
Updating framework-arduinoteensy         @ 1.148.0        [Up-to-date]
Updating tool-teensy                     @ 1.148.0        [Up-to-date]
```

### Description of problem
When getting the remote agent list, the following output is observed on macOS and Windows. I do not see this issue on Ubuntu.

```
~ pio remote agent list
PIO Plus (https://pioplus.com) v2.6.0
sequence item 1: expected str instance, bytes found
```

### Expected Results
The list of objects (there definitely is one remote agent.)

**Comment by ivankravets** [comment]
Do you use the same Python 3 or Python 2 for your agents? You can't mix with Python2/3

**Comment by ivankravets** [comment]
Please reopen if you still need help
