### ISSUE TITLE
problems when i try to publish my library

### ISSUE THREAD

**Issue by epsilon11101** [platformio/platformio-core#3277]
Hi, I can not upload my library, I followed the steps on the page but nevertheless I have the following error, I hope someone can help me

```
platformio lib register https://github.com/epsilon11101/Cerebro/blob/master/ARDUINO_LIBRARY/cerebro/library.js
on
```

`Error: Could not parse manifest -> No JSON object could be decoded`

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/librarymanager/creating.html
