### ISSUE TITLE
BTT e3 mini blank screen

### ISSUE THREAD

**Issue by thebest07111** [platformio/platformio-core#3287]
Whenever I compile a firmware using platformio core 4.1.0 It gives me a blank screen on my ender 3 mini.

People say with the new marlin it is fixed that we can use 4.1.0 but for me it is not fixed. Any idea how to fix this?

**Comment by ivankravets** [comment]
Do you use the LATEST firmware for ender 3 mini? Where did you get source code?

**Comment by ivankravets** [comment]
Please reopen if you still need help
