### ISSUE TITLE
Allow easy overriding of all properties

### ISSUE THREAD

**Issue by StefanBruens** [platformio/platformio-core#3294]
- [x] **Feature Request**.
      
------------------------------------------------------------------

### Configuration

**Operating system**: Any

**PlatformIO Version** (`platformio --version`): 4.1

### Description of problem

Currently it is only possible to override very specific parts of the config, e.g. using `PLATFORMIO_UPLOAD_PORT` and the like.

Editing the platformio.ini is often not a good idea:
- it may come from an upstream project, any changes will likely result in a merge conflict later
- depending on the structure, the same option may be set for multiple envs (the `extends` only allows a tree structure, but often a board is a mix-and-match of several components).
- even for local platformio.ini's, the same file may be used on different computers.

I would like to override toolchains, debugging tools, debug/optimization settings, ...

Currently, I have to:
- copy the platformio.ini
- in each relevant env, set a different platform (to use a different compiler)
- in each relevant env, set the relevant debug/optimization flags (typically I want "fully optimized - release", "optimized, but with extra debug output", "unoptimized".

Even for a single board, I end up with 3 (compilers) * 3 (debug settings) = 9 envs, more when multiple boards are affected.

Preferably, I could:
- create a file platformio_local.ini
- include the upstream platformio.ini (using an "include" directive")
- override e.g. "[env:foo_board]/platform_packages ~= s/toolchain-gccarmnoneeabi/toolchain-mygcc"
- add non-env specific debug settings 
- run something like (foo_board_1, foo_board_2 `extends` foo_board):
  - `pio run -f platformio_local.ini -e foo_board_1+debug`
  - `pio run -f platformio_local.ini -e foo_board_2+fulldebug`
  - `pio run -f platformio_local.ini -e foo_board_1+release`

**Comment by ivankravets** [comment]
We can't cover 70+ options with environment variables. What I recommend for your case:

1. Create `mycustom.ini`
2. Use http://docs.platformio.org/en/latest/projectconf/section_platformio.html#extra-configs and load original `platformio.ini`
3. Then a new item in `extra_configs` which overrides original values.
