### ISSUE TITLE
Request for monitor_speed preprocessor macro definition

### ISSUE THREAD

**Issue by HeathPetersen** [platformio/platformio-core#3297]
It would be nice if we could easily set the serial port baud rate in our application to the monitor_speed parameter in platformio.ini.  Could you add a preprocessor macro passing this to the compiler?  Maybe __PLATFORMIO_MONITOR_SPEED?

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags
