### ISSUE TITLE
Support for board STM32H747I-DISCO (Error: Unknown board ID 'disco_h743xi')

### ISSUE THREAD

**Issue by cychai1995** [platformio/platformio-core#3307]
The board STM32H747I-DISCO is supported in the [documentation](https://docs.platformio.org/en/latest/boards/ststm32/disco_h743xi.html#board-ststm32-disco-h743xi). However, when initializing the project with command for some IDE (e.g., Clion)
`platformio init --ide clion -b disco_h743xi`
the result is 
**Error: Unknown board ID 'disco_h743xi'.**. Same for vscode or any other IDEs.

Tested using the development branch (PlatformIO, version 4.1.1b5) on MacOS 10.15.2.

**Comment by ivankravets** [comment]
It seems you use development version of docs. In this case, please switch to upstream dev.platform https://docs.platformio.org/en/latest/platforms/ststm32.html#upstream
