### ISSUE TITLE
Using {env.src_filter} does not work for extending filter in an environment

### ISSUE THREAD

**Issue by Bascy** [platformio/platformio-core#3308]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows
**PlatformIO Version** (`platformio --version`): 4.1.1b5

### Description of problem
Using ${env.src_filter} in an evniroment definition, does not work

#### Steps to Reproduce

1. Add `src_filter = ${env.src_filter} -<exclfile.*> to an environment in platofmio.ini
2. run `pio run -t envdump
3.

### Actual Results
'SRC_FILTER': '+<*> -<.git/> -<.svn/>',

### Expected Results
'SRC_FILTER': ['+<*> -<.git/> -<.svn/> -<exclfile.*>'],

When `src_filter = +<*> -<.git/> -<.svn/> -<exclfile.*>` is used then the result is correct

**Comment by ivankravets** [comment]
Could you provide a simple `platformio.ini` to reproduce this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
