### ISSUE TITLE
Import of non-existent variable ''projenv''

### ISSUE THREAD

**Issue by ceuti** [platformio/platformio-core#3315]
PIO Core Call Error: "The current working directory C:\\Users\\Pedro\\Documents\\PlatformIO\\Projects\\191117-053108-counter will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\Pedro\\Documents\\PlatformIO\\Projects\\191117-053108-counter\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Processing icestick (platform: lattice_ice40; board: icestick)\n-------------------------------------------------------------------------------\nCorePackageManager: Installing tool-scons @ ~2.20501.7\ntool-scons @ 2.20501.190826 has been successfully installed!\nVerbose mode can be enabled via `-v, --verbose` option\n\n*** Import of non-existent variable ''projenv''\nFile \"C:\\Users\\Pedro\\.platformio\\penv\\lib\\site-packages\\platformio\\builder\\main.py\", line 191, in <module>\n========================= [FAILED] Took 4.07 seconds ========================="

**Comment by ivankravets** [comment]
Thanks! Please re-test with `pio upgrade --dev`
