### ISSUE TITLE
Add "pio project config" command

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#3335]
Allow dumping of runtime configuration to JSON
```
pio project config --json-output
```

> python -c "from platformio.project.config import ProjectConfig; print(ProjectConfig().to_json())"

**Comment by luchiago** [comment]
Hi, this issue needs help?

**Comment by ivankravets** [comment]
Sorry, what do you mean?

**Comment by luchiago** [comment]
If I can help with this issue
