### ISSUE TITLE
Generate project main

### ISSUE THREAD

**Issue by KevinOI** [platformio/platformio-core#3337]
It would be nice to redefine the main.cpp file.

In **platformio-core\platformio\commands\home\rpc\handlers\project.py** there is a method (**_generate_project_main()**) to generate de default main.cpp.

I have a custom framework and I would like to create a default main.cpp.

Is it possible ?

**Comment by ivankravets** [comment]
What will be inside `main.cpp`?

**Comment by KevinOI** [comment]
Something like that:

#include "OpenIndus.h"

int main(void)
{

   while(1)
   {
   }
}

I wish I could customize the main.cpp file when I create the project.





Le ven. 10 janv. 2020 à 13:53, Ivan Kravets <notifications@github.com> a
écrit :

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/446
