### ISSUE TITLE
Override label on library.json for framework and platform

### ISSUE THREAD

**Issue by ivan1993br** [platformio/platformio-core#3352]
What kind of issue is this?

- [ ] **Question**.

- [ ] **PlatformIO IDE**.

- [ ] **Development Platform or Board**.

- [X] **Feature Request**.
     Is it coherent to have a feature that adds a new field on the library.json that overrides some build properties? like:

```yml
"framework_mbed_override" : { "build": {
        "flags": [
            "...",
            "..."
        ],
        "srcFilter": [
          "...",
          "..."
       ]
}
}
```
```yml
"platform_native_override" : { "build": {
        "flags": [
            "...",
            "..."
        ],
        "srcFilter": [
          "...",
          "..."
       ]
}
}
```

- [ ] **PlatformIO Core**.

# Addition info

My question is raised because lets suppose that I have a package that will have some part with specific framework or platform related files, so if I create an application that is dependent  of this library I can have tests for platform A and B(that may be native), with their specific enviroment which will compile different files.

What do you think @ivankravets ?

**Comment by ivankravets** [comment]
Thanks for the issue! We try to keep configuration process very simple. If you need advanced configuration, please use https://docs.platformio.org/en/latest/librarymanager/config.html#extrascript
