### ISSUE TITLE
Error: You are not connected to the Internet.

### ISSUE THREAD

**Issue by alexmww** [platformio/platformio-core#3359]
- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

```
PS ************> platformio init --ide clion --board nano
Error: You are not connected to the Internet.
If you build a project first time, we need Internet connection to install all dependencies and toolchains.
```

Same error at Windows and Paspbian, same error at different APs.

**Comment by alexmww** [comment]
Some of your IPs got blocked in Russia, I suppose.
I have managed to get things working using VPN.

**Comment by alexmww** [comment]
It seems for me that you need to execute first any command using VPN, then everything should work fine.
Checked at different machines and WSL, at different AP. Same behavior.

**Comment by ivankravets** [comment]
Thanks! Please re-test with `pio ugprade --dev`.
