### ISSUE TITLE
Access to latest Unity including its extra features, in unit tests.

### ISSUE THREAD

**Issue by joustava** [platformio/platformio-core#3362]
- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

### Configuration

**Operating system**:
Mac
```
⟩ sw_vers -productVersion
10.15.2
```
**PlatformIO Version** (`platformio --version`):
```
⟩ pio --version
PlatformIO, version 4.1.0
```

### Description of problem

Would like to be able to use the latest Unity including its extra features  as described [here](https://github.com/ThrowTheSwitch/Unity/tree/master/extras/fixture) if possible.

**Comment by pfeerick** [comment]
Latest version of Unity is currently 2.5.0, from Oct 31, 2019. There has been a bunch of commits since then, the most recent only five days ago, so there *could* be another release, although it may only be a minor release, on the way soon. https://github.com/ThrowTheSwitch/Unity/releases/tag/v2.5.0
