### ISSUE TITLE
Following Contribution Guidelines ends up in 'toolchain-gd32v' issue.

### ISSUE THREAD

**Issue by joustava** [platformio/platformio-core#3363]
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration
Mac
⟩ sw_vers -productVersion
10.15.2

⟩ pio --version
PlatformIO, version 4.1.0

### Description of problem

While following the contribution guidelines I also ended up with an installation error caused by:  
https://github.com/sipeed/platform-gd32v/issues/6
Now, I know this is sort of a duplicate but I'm not really sure what the preferred workaround is. 
Maybe the contribution guidelines could clarify if this error would be a blocker when developing for other platforms/boards (? maybe mixing up jargon here, sorry) that require the *toolchain-gd32v* package? Is it maybe somehow possible to ignore this platform temporarily with a local setting before repeating the steps in the contribution guidelines, so one could successfully set up the (albeit restricted to certain platforms only) dev environment?

Also, one ends up with this after setting up this repo for contributing:
```
Obsolete PIO Core v4.1.0 is used (previous was 4.1.1b9)
Please remove multiple PIO Cores from a system:
https://docs.platformio.org/page/faq.html#multiple-pio-cores-in-a-system
...
```
Should a contributor also only just have one instance even if they use need platformio in both contributing and normal usage?

#### Steps to Reproduce

Just follow  the current Contribution Guidelines at the bottom of the [README.md](CONTRIBUTING.md) and in step 5. run the activation for Fish: source .tox/py27/bin/activate.fish.

**Comment by ivankravets** [comment]
Just remove `~/.platformio/appstate.json` file and "Obsolete PIO" message will be gone.
