### ISSUE TITLE
PIO IDE in VSCode: Please don’t overwrite `extensions.json`

### ISSUE THREAD

**Issue by neilbalch** [platformio/platformio-core#3374]
**Issue type:** PlatformIO Core/IDE feature request.

On a regular basis, I use the VSCode-generated `.vscode/extensions.json` to maintain a list of VSCode extensions relevant to the project. Every time PlatformIO updates (_I think this is the trigger, I could be wrong_), it overwrites the entire file with one that just recommends itself for installation. Every time I see this, I need to revert the changes in git before I make commits.

I wish this weren’t the case. I’d be perfectly happy (_pleased even_) if the PlatformIO IDE extension _appended_ itself to the end of the file rather than _overwriting_ it. Could we make this change a reality/get an explanation for why it is the way it currently is?

See [PlatformIO Community post](https://community.platformio.org/t/pio-ide-in-vscode-please-dont-overwrite-extensions-json/11905) for discussion.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`. Restart VSCode.
