### ISSUE TITLE
Include wrong library

### ISSUE THREAD

**Issue by meditant** [platformio/platformio-core#3375]
Hello,
Since the last update to Home 3.1.0 RC4 and Core 4.2.0RC2 i have a compilation error on one project is load the good library but an other wrong library (lib319).

Compiling .pio/build/debug/lib60f/AsyncTCP_ID1826/AsyncTCP.cpp.o
Compiling .pio/build/debug/lib319/ESPAsyncTCP_ID305/AsyncPrinter.cpp.o

My PIO ini :

platform = espressif32
board = lolin32
lib_deps =
  AsyncTCP
  AsyncMqttClient
  ESP Async WebServer
  ArduinoJson
framework = arduino

Mac OS 10.15.3

Best

**Comment by meditant** [comment]
I deleted the library in libdeps in .pio and now it's work but i nevers add this 8266 library...

Strange !

**Comment by ivankravets** [comment]
Which library is incompatible?

**Comment by ivankravets** [comment]
Please reopen if you still need help
