### ISSUE TITLE
Feature Request - ESP32 boards TTGO T4 and TTGO T7 Mini32

### ISSUE THREAD

**Issue by HaroldEmmers** [platformio/platformio-core#3392]
**Feature Request**:

I would like suppport for the following two boards:
- LilyGO TTGO T4 V1.3 ESP32
- LilyGO TTGO T7 Mini32 V1.4 ESP32-WROVER

**Comment by happy1234567** [comment]
and this board please LILYGO TTGO T-Internet-POE ESP32-WROOM LAN8720A Chip
