### ISSUE TITLE
PIO Home: Call Error: "the JSON object must be str, not 'bytes'"

### ISSUE THREAD

**Issue by CH-WangMing** [platformio/platformio-core#3396]
PIO Core Call Error: "the JSON object must be str, not 'bytes'"

**Comment by ivankravets** [comment]
Thanks for the report! Please re-test with the latest PIO Core via running `$ pio upgrade --dev` in PlatformIO IDE Terminal. You may also need to kill existing `python` processes. Restart VSCode.
