### ISSUE TITLE
PIO Home server security model

### ISSUE THREAD

**Issue by FedericoCeratto** [platformio/platformio-core#3397]
- [x] **PlatformIO Core**

### Configuration

**Operating system**: any

**PlatformIO Version**: any

### Description of problem

Initially described in: https://community.platformio.org/t/pio-home-security-issue/12196

When `platformio home` is run by a user, PIO has unlimited access to the user's home directory.

PIO home on `http://127.0.0.1:8008` exposes the home contents:
- to any other local user
- to any (potentially malicious) website that can connect to localhost (e.g. using javascript and websockets)
- to any (potentially malicious) PIO library

#### Suggested mitigations

On Linux the process can be sandboxed by either:
- Ship a firejail profile and start platformio under firejail
- Run platformio as a system process using systemd sandboxing capabilities
- Implement native sandboxing

The sandboxing is meant to limit which paths the process (and its children) can read and write from.

EDIT: I'm happy to contribute the systemd sandboxing if needed.

**Comment by ivankravets** [comment]
What is a multiplatform solution for this issue? Could you provide a PR? Thanks in advance!

**Comment by ivankravets** [comment]
Thanks for the report. We will generate a secure token on a server side and use it for clients.

**Comment by FedericoCeratto** [comment]
@ivankravets the token provides a basic form of authentication/authorization but cannot not provide any protection to the user's home directory from a platformio instance that is running untrusted code or has been otherwise compromised.
Can you please reopen the bug report? Thanks.

**Comment by ivankravets** [comment]
> but cannot not provide any protection to the user's home directory from a platformio instance

Have you tried the latest development version? The upcoming PlatformIO IDE 2.1 will use a unique session ID for each session. So, you will not be able to connect to the existing session.

**Comment by FedericoCeratto** [comment]
Yes, hence my answer. The unique session ID provides only authentication/authorization and is besides the point of sandboxing. PlatformIO downloads and executes a lot of code and tools and communicates with many devices, leading to  large attack surface.

**Comment by ivankravets** [comment]
So, this is a different story. In this case, you can use Docker or similar virtualization platforms and connect your hardware to them. 

We agree, we had a security issue with PIO Home but it is now resolved.
