### ISSUE TITLE
Serial monitor does not conform to --quiet flag

### ISSUE THREAD

**Issue by sjoerdsein** [platformio/platformio-core#3404]
When I open the serial monitor on the cli with the `--quiet` flag I expect it to print only whatever came in from the serial port and error messages as per the documentation. Not a recommendation for a different serial monitor.
```
$ pio device monitor --port /dev/ttyACM0 --quiet
Looking for advanced Serial Monitor with UI? Check http://bit.ly/pio-advanced-monitor
...
``` 
I am running PlatformIO 4.2.1 on Linux.
The offending code:
https://github.com/platformio/platformio-core/blob/7716fe1d1c26e0c2a15b7d6871febe88ca32aa21/platformio/commands/device.py#L176-L180
[Documentation](https://github.com/platformio/platformio-docs/blob/d2977210978165793d4e98c7a94b4ef045f89eae/userguide/cmd_device.rst#id6) (including the superfluous hyphen):
```
    ---quiet
Diagnostics: suppress non-error messages, default Off
```

**Comment by ivankravets** [comment]
Thanks for the report! Resolved in https://github.com/platformio/platformio-core/commit/108b892e30e599bd22a547384c544363ed75fae5
