### ISSUE TITLE
Build fail with Error

### ISSUE THREAD

**Issue by Hedgehog61** [platformio/platformio-core#3405]
Build fail witg the following errors:

PIO Core Call Error: "Can not remove temporary directory `D:\\OneDrive\\Software\\SmartHome\\PlatformIO-Projekte\\Stromzaehler\\.pioenvs`. Please remove it manually to avoid build issues\r\n\n\nError: Invalid 'D:\\OneDrive\\Software\\SmartHome\\PlatformIO-Projekte\\Stromzaehler\\platformio.ini' (project configuration file): 'No option 'platform_packages' in section: 'common''"

Environment:
VSC
Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Paltformio: 
Core 4.2.1
Home 3.1.1

The working Projekt is https://github.com/gemu2015/Sonoff-Tasmota

During the Build the directory ".pioenvs" is  deleted, but the the related error ist posted.

The second Error is correct, but new. The platformio.ini File doesn't contain any option "platform_packages"

The problem with these issues are, that i started  a buildung serveral times before but with a older version of platformio.

This problem is well discussed here: https://forum.iobroker.net/topic/27999/stromz%C3%A4hler-per-sonoff-esp8266-auslesen/94

The same problem happens under Linux and Windows.

**Comment by ivankravets** [comment]
> No option 'platform_packages' in section: 'common''"

This bug was fixed in original repository https://github.com/arendst/Tasmota

Please ask @gemu2015 to update his fork.
