### ISSUE TITLE
Library error

### ISSUE THREAD

**Issue by sysdl132** [platformio/platformio-core#3407]
Configuration

**Operating system**:windows 10

**PlatformIO Version** (`platformio --version`):4.2.1

### Description of problem

When I installing "TFT_eSPI"library it always reports the following error:
![image](https://user-images.githubusercontent.com/54708046/76136965-7002ee80-6072-11ea-9260-f8022665f3aa.png)
But I install other libraries it works fine:
![image](https://user-images.githubusercontent.com/54708046/76136975-9fb1f680-6072-11ea-8642-da7eb2c35c21.png)
When I download a library I want ,it always show an error.
But when I download a library I don't want,it always success.

### Actual Results

Lib call error

### Additional info

I can use powershell to update.But can't install libraries.

**Comment by ivankravets** [comment]
Do you use proxy? I see in the error above an error with ConnectionReset...

**Comment by ivankravets** [comment]
Please reopen if you still need help
