### ISSUE TITLE
how to change the ram size in platform?

### ISSUE THREAD

**Issue by KiraVerSace** [platformio/platformio-core#3430]
i know the platform support the  board  [nucleo_l476rg],
but in my project, i used  STM32L476RET6  that ram is less to 80KB , or i used STM32L476VG that pins are up to LQFP100.
which files i should to modified to adapt to the two chips?
thank you

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/c/development-platforms/17

**Comment by KiraVerSace** [comment]
I see nothing ?


| |
X.X.Yao
|
|
kiraversace@yeah.net
|
签名由网易邮箱大师定制


On 03/20/2020 19:57，Ivan Kravets<notifications@github.com> wrote：

Please forward to https://community.platformio.org/c/development-platforms/17

**Comment by ivankravets** [comment]
https://community.platformio.org/

**Comment by KiraVerSace** [comment]
> https://community.platformio.org/

thank you for your replay , but I can not find any topic about the question, and i just register in the community, so i cannot post a topic?

**Comment by ivankravets** [comment]
Please try again to crate a post.
