### ISSUE TITLE
executing menuconfig make target results in error

### ISSUE THREAD

**Issue by eliabieri** [platformio/platformio-core#3434]
### Configuration

**Operating system**:
MacOs

**PlatformIO Version** (`platformio --version`):
4.3.1

### Description of problem
When running `platformio run -t menuconfig`, the following error appears:
```
scons: *** Do not know how to make File target `menuconfig' (/private/tmp/test/menuconfig).
```

#### Steps to Reproduce

1. Run platformio run -t menuconfig
2. The error appears

### Actual Results
```
scons: *** Do not know how to make File target `menuconfig' (/private/tmp/test/menuconfig).
```

### Expected Results
The menuconfig UI is started

**The content of `platformio.ini`:**
```ini
[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = espidf
```

**Comment by ivankravets** [comment]
ESP32 dev-platform with support for menuconfig has not been released yet. Pelase use upstream version https://docs.platformio.org/en/latest/platforms/espressif32.html#upstream

**Comment by 2dom** [comment]
Still present with upstream version:


```
[env:esp32thing]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32thing
monitor_baud = 115200
framework = arduino
lib_extra_dirs = C:\Users\dbuch\Dropbox\coding\Arduino\libraries
```

**Comment by valeros** [comment]
Hi @2dom ! The `menuconfig` target is only available for `ESP-IDF` framework and Arduino uses prebuilt `ESP-IDF` so it's not configurable.

**Comment by 2dom** [comment]
I see ... thanks for the heads up

**Comment by vindolin** [comment]
> 
> 
> Hi @2dom ! The `menuconfig` target is only available for `ESP-IDF` framework and Arduino uses prebuilt `ESP-IDF` so it's not configurable.

Are there any workarounds if I wanted to use arduino?
E.g. to enable CONFIG_PM_ENABLE on a ESP32s2 module.

**Comment by pcontezini** [comment]
Did anyone made the menuconfig work with PlataformIO?

I'm using the develop framework as pointed out and it doesn't know the menuconfig target with pio run -t menuconfig.

Thanks

**Comment by zekageri** [comment]
same problem here
