### ISSUE TITLE
Package manager could not install cmake

### ISSUE THREAD

**Issue by adrianpanicek** [platformio/platformio-core#3438]
### Configuration

**Operating system**: Windows 10 x64

**PlatformIO Version**: 4.3.2a1

### Description of problem

When I try to build a project for espressif platform, PackageManager says

`Error: Could not find a version that satisfies the requirement '~3.16.0' for your system 'windows_x86'`

Platformio worked for me before. I tried removing `.platformio` from Users folder and even reinstalling it in VScode but it didn't help.

Full log:
```
> Executing task: C:\Users\Ado\.platformio\penv\Scripts\platformio.exe run <

Processing esp32dev (platform: espressif32; board: esp32dev; framework: espidf)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

PackageManager: Installing tool-cmake @ ~3.16.0
Error: Could not find a version that satisfies the requirement '~3.16.0' for your system 'windows_x86'
```

#### Steps to Reproduce

1. Rebuild project
2. Observe error

### Actual Results

Platformio crashes out before building.

### Expected Results

Platformio builds a project

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
build_flags = -std=c++17
build_unflags = -std=gnu++11
monitor_speed = 115200
lib_ldf_mode = chain
monitor_flags=
        --raw
upload_protocol = esptool
```

**Comment by valeros** [comment]
Hi @adrianpanicek ! Looks like you have 32-bit version of Python installed. We've added the missing package for this architecture, could you please try again?

**Comment by adrianpanicek** [comment]
@valeros This worked, thank you very much.
