### ISSUE TITLE
lib_ldf_mode setting does work in [common_env_data] section

### ISSUE THREAD

**Issue by fjulian79** [platformio/platformio-core#3444]
### Configuration

**Operating system**: Mac OS X Catalina

**PlatformIO Version**: 4.3.1

### Description of problem

When placing the lib_ldf_mode setting in the common_env_data section it seems as it is ineffective. When moving it to a specific env section it woks fine.

**In `platformio.ini` this does not work:**
```ini
[common_env_data]
lib_ldf_mode = deep+
lib_deps = ...

[env:nucleo_f103rb]
platform = ststm32
board = nucleo_f103rb
framework = stm32cube
lib_deps =
    ${common_env_data.lib_deps}
    ...
```

**In `platformio.ini` this does work:**
```ini
[common_env_data]
lib_deps = ...

[env:nucleo_f103rb]
platform = ststm32
board = nucleo_f103rb
framework = stm32cube
lib_ldf_mode = deep+
lib_deps =
    ${common_env_data.lib_deps}
    ...
```

**Comment by ivankravets** [comment]
You need https://docs.platformio.org/en/latest/projectconf/section_env.html#common-env
