### ISSUE TITLE
Support for SPL framework on STM32L1

### ISSUE THREAD

**Issue by laurentS** [platformio/platformio-core#348]
I'm testing code on ST Nucleo L152RE, which is based on STM32L152 mcu. I found code examples that use SPL framework for this MCU, but cannot get them to compile with platformio.
When I try to add SPL to frameworks (along with mbed), I get a "SPL not supported for this platform" error.
Why is this? I understand that SPL is linked to the MCU, not the board. So I'm expecting I should be able to use it for that MCU. Any suggestions?

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-ststm32/issues/24
