### ISSUE TITLE
please add CubeCell platform from Heltec

### ISSUE THREAD

**Issue by fredolaredo** [platformio/platformio-core#3489]
- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

------------------------------------------------------------------
sorry if I'm not posting at the right place .... did not find any suitable one. 

### Platform

https://github.com/HelTecAutomation/ASR650x-Arduino

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3078
