### ISSUE TITLE
debugging support for Arduino Uno

### ISSUE THREAD

**Issue by justin-romano** [platformio/platformio-core#3499]
this has probably been requested before but would be good. im pretty sure i read something about the ATmega having a debug wire protocol

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-atmelavr/issues/95

You can try a simulator for AVR https://community.platformio.org/t/avr-simulator-as-aid-tool-for-debugging-code/13444/10?u=ivankravets
