### ISSUE TITLE
problem in compiling  on platformio with ThinyWireM

### ISSUE THREAD

**Issue by JKWork3** [platformio/platformio-core#3504]
What kind of issue is this?

- [x] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

i have the same problem: Il processo del terminale è stato terminato. Codice di uscita: 1

Terminale verrà riutilizzato dalle attività, premere un tasto qualsiasi per chiuderlo.

> Executing task: platformio run <

Processing megaatmega2560 (platform: atmelavr; board: megaatmega2560; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/megaatmega2560.html
PLATFORM: Atmel AVR 2.0.0 > Arduino Mega or Mega 2560 ATmega2560 (Mega 2560)
HARDWARE: ATMEGA2560 16MHz, 8KB RAM, 248KB Flash
PACKAGES: 
 - framework-arduino-avr 5.0.0 
 - toolchain-atmelavr 1.50400.190710 (5.4.0)
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 14 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Wire> 1.0
|-- <LiquidCrystal_I2C>
|   |-- <Wire> 1.0
|-- <RTClib> 1.6.0
|   |-- <TinyWireM> 1.0.1
|   |-- <Wire> 1.0
|-- <EEPROM> 2.0
|-- <LiquidCrystal> 1.5.0
|   |-- <TinyWireM> 1.0.1
|   |-- <Wire> 1.0
|-- <Adafruit Unified Sensor> 1.1.2
|   |-- <Adafruit ADXL343> 1.3.0
|   |   |-- <Adafruit BusIO> 1.2.3
|   |   |   |-- <Wire> 1.0
|   |   |   |-- <SPI> 1.0
|   |   |-- <Wire> 1.0
|-- <Adafruit BME280 Library> 2.0.2
|   |-- <Adafruit Unified Sensor> 1.1.2
|   |   |-- <Adafruit ADXL343> 1.3.0
|   |   |   |-- <Adafruit BusIO> 1.2.3
|   |   |   |   |-- <Wire> 1.0
|   |   |   |   |-- <SPI> 1.0
|   |   |   |-- <Wire> 1.0
|   |-- <Wire> 1.0
|   |-- <SPI> 1.0
Building in release mode
Compiling .pio/build/megaatmega2560/src/main.cpp.o
Compiling .pio/build/megaatmega2560/lib525/Wire/Wire.cpp.o
Compiling .pio/build/megaatmega2560/lib525/Wire/utility/twi.c.o
Compiling .pio/build/megaatmega2560/lib9ab/LiquidCrystal_I2C_ID576/LiquidCrystal_I2C.cpp.o
src/main.cpp:19:32: warning: invalid conversion from 'int' to 't_backlightPol' [-fpermissive]
 LiquidCrystal_I2C lcd(0x27,16,2); // 0x27 is the I2C bus address for an unmodified backpack 
                                ^
In file included from src/main.cpp:7:0:
/Users/giacomofidanza/.platformio/lib/LiquidCrystal_ID136/LiquidCrystal_I2C.h:65:4: note:   initializing argument 3 of 'LiquidCrystal_I2C::LiquidCrystal_I2C(uint8_t, uint8_t, t_backlightPol)'
    LiquidCrystal_I2C (uint8_t lcd_Addr, uint8_t backlighPin, t_backlightPol pol);
    ^
src/main.cpp: In function 'int temperatureHumidityControl()':
src/main.cpp:1245:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        if (((currentMillis - previousMillisT) >= timeOff) && !digitalRead(tout)) {
                                               ^
src/main.cpp:1252:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (((currentMillis - previousMillisT) >= timeOn) && digitalRead(tout)) {
                                                ^
src/main.cpp:1284:5: warning: no return statement in function returning non-void [-Wreturn-type]
     }
     ^
src/main.cpp: In function 'int THAllarm()':
src/main.cpp:1480:2: warning: no return statement in function returning non-void [-Wreturn-type]
  }
  ^
src/main.cpp: In function 'void loop()':
src/main.cpp:1762:45: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (currentMillis - previousMillisPlate >= intervalPlate) {
                                             ^
Compiling .pio/build/megaatmega2560/lib124/TinyWireM-master/TinyWireM.cpp.o
Archiving .pio/build/megaatmega2560/lib525/libWire.a
Indexing .pio/build/megaatmega2560/lib525/libWire.a
Archiving .pio/build/megaatmega2560/lib9ab/libLiquidCrystal_I2C_ID576.a
Compiling .pio/build/megaatmega2560/lib124/TinyWireM-master/USI_TWI_Master.cpp.o
Indexing .pio/build/megaatmega2560/lib9ab/libLiquidCrystal_I2C_ID576.a
Compiling .pio/build/megaatmega2560/lib925/RTClib_ID83/RTClib.cpp.o
lib/TinyWireM-master/USI_TWI_Master.cpp: In function 'void USI_TWI_Master_Initialise()':
lib/TinyWireM-master/USI_TWI_Master.cpp:48:3: error: 'PORT_USI' was not declared in this scope
   PORT_USI |= (1<<PIN_USI_SDA);           // Enable pullup on SDA, to set high as released state.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:48:19: error: 'PIN_USI_SDA' was not declared in this scope
   PORT_USI |= (1<<PIN_USI_SDA);           // Enable pullup on SDA, to set high as released state.
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:49:19: error: 'PIN_USI_SCL' was not declared in this scope
   PORT_USI |= (1<<PIN_USI_SCL);           // Enable pullup on SCL, to set high as released state.
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:51:3: error: 'DDR_USI' was not declared in this scope
   DDR_USI  |= (1<<PIN_USI_SCL);           // Enable SCL as output.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:54:3: error: 'USIDR' was not declared in this scope
   USIDR    =  0xFF;                       // Preload dataregister with "released level" data.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:55:3: error: 'USICR' was not declared in this scope
   USICR    =  (0<<USISIE)|(0<<USIOIE)|                            // Disable Interrupts.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:55:19: error: 'USISIE' was not declared in this scope
   USICR    =  (0<<USISIE)|(0<<USIOIE)|                            // Disable Interrupts.
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:55:31: error: 'USIOIE' was not declared in this scope
   USICR    =  (0<<USISIE)|(0<<USIOIE)|                            // Disable Interrupts.
                               ^
lib/TinyWireM-master/USI_TWI_Master.cpp:56:19: error: 'USIWM1' was not declared in this scope
               (1<<USIWM1)|(0<<USIWM0)|                            // Set USI in Two-wire mode.
Archiving .pio/build/megaatmega2560/lib0b7/libEEPROM.a
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:56:31: error: 'USIWM0' was not declared in this scope
               (1<<USIWM1)|(0<<USIWM0)|                            // Set USI in Two-wire mode.
                               ^
lib/TinyWireM-master/USI_TWI_Master.cpp:57:19: error: 'USICS1' was not declared in this scope
               (1<<USICS1)|(0<<USICS0)|(1<<USICLK)|                // Software stobe as counter clock source
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:57:31: error: 'USICS0' was not declared in this scope
               (1<<USICS1)|(0<<USICS0)|(1<<USICLK)|                // Software stobe as counter clock source
                               ^
lib/TinyWireM-master/USI_TWI_Master.cpp:57:43: error: 'USICLK' was not declared in this scope
Indexing .pio/build/megaatmega2560/lib0b7/libEEPROM.a
               (1<<USICS1)|(0<<USICS0)|(1<<USICLK)|                // Software stobe as counter clock source
                                           ^
lib/TinyWireM-master/USI_TWI_Master.cpp:58:19: error: 'USITC' was not declared in this scope
               (0<<USITC);
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:59:3: error: 'USISR' was not declared in this scope
   USISR   =   (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Clear flags,
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:59:19: error: 'USISIF' was not declared in this scope
   USISR   =   (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Clear flags,
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:59:31: error: 'USIOIF' was not declared in this scope
   USISR   =   (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Clear flags,
                               ^
lib/TinyWireM-master/USI_TWI_Master.cpp:59:43: error: 'USIPF' was not declared in this scope
   USISR   =   (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Clear flags,
                                           ^
lib/TinyWireM-master/USI_TWI_Master.cpp:59:54: error: 'USIDC' was not declared in this scope
   USISR   =   (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Clear flags,
                                                      ^
lib/TinyWireM-master/USI_TWI_Master.cpp:60:21: error: 'USICNT0' was not declared in this scope
               (0x0<<USICNT0);                                     // and reset counter.
                     ^
lib/TinyWireM-master/USI_TWI_Master.cpp: In function 'unsigned char USI_TWI_Start_Transceiver_With_Data(unsigned char*, unsigned char)':
lib/TinyWireM-master/USI_TWI_Master.cpp:130:44: error: 'USISIF' was not declared in this scope
   unsigned char const tempUSISR_8bit = (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Prepare register value to: Clear flags, and
                                            ^
lib/TinyWireM-master/USI_TWI_Master.cpp:130:56: error: 'USIOIF' was not declared in this scope
   unsigned char const tempUSISR_8bit = (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Prepare register value to: Clear flags, and
                                                        ^
lib/TinyWireM-master/USI_TWI_Master.cpp:130:68: error: 'USIPF' was not declared in this scope
   unsigned char const tempUSISR_8bit = (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Prepare register value to: Clear flags, and
                                                                    ^
lib/TinyWireM-master/USI_TWI_Master.cpp:130:79: error: 'USIDC' was not declared in this scope
   unsigned char const tempUSISR_8bit = (1<<USISIF)|(1<<USIOIF)|(1<<USIPF)|(1<<USIDC)|      // Prepare register value to: Clear flags, and
                                                                               ^
lib/TinyWireM-master/USI_TWI_Master.cpp:131:40: error: 'USICNT0' was not declared in this scope
                                  (0x0<<USICNT0);                                     // set USI to shift 8 bits i.e. count 16 clock edges.
                                        ^
lib/TinyWireM-master/USI_TWI_Master.cpp:196:7: error: 'PORT_USI' was not declared in this scope
       PORT_USI &= ~(1<<PIN_USI_SCL);                // Pull SCL LOW.
       ^
lib/TinyWireM-master/USI_TWI_Master.cpp:196:24: error: 'PIN_USI_SCL' was not declared in this scope
       PORT_USI &= ~(1<<PIN_USI_SCL);                // Pull SCL LOW.
                        ^
lib/TinyWireM-master/USI_TWI_Master.cpp:197:7: error: 'USIDR' was not declared in this scope
       USIDR     = *(msg++);                        // Setup data.
       ^
lib/TinyWireM-master/USI_TWI_Master.cpp:201:7: error: 'DDR_USI' was not declared in this scope
       DDR_USI  &= ~(1<<PIN_USI_SDA);                // Enable SDA as input.
       ^
lib/TinyWireM-master/USI_TWI_Master.cpp:201:24: error: 'PIN_USI_SDA' was not declared in this scope
       DDR_USI  &= ~(1<<PIN_USI_SDA);                // Enable SDA as input.
                        ^
lib/TinyWireM-master/USI_TWI_Master.cpp:234:7: error: 'DDR_USI' was not declared in this scope
       DDR_USI   &= ~(1<<PIN_USI_SDA);               // Enable SDA as input.
       ^
lib/TinyWireM-master/USI_TWI_Master.cpp:234:25: error: 'PIN_USI_SDA' was not declared in this scope
       DDR_USI   &= ~(1<<PIN_USI_SDA);               // Enable SDA as input.
                         ^
lib/TinyWireM-master/USI_TWI_Master.cpp:240:9: error: 'USIDR' was not declared in this scope
         USIDR = 0xFF;                              // Load NACK to confirm End Of Transmission.
         ^
lib/TinyWireM-master/USI_TWI_Master.cpp:244:9: error: 'USIDR' was not declared in this scope
         USIDR = 0x00;                              // Load ACK. Set data register bit 7 (output for SDA) low.
         ^
lib/TinyWireM-master/USI_TWI_Master.cpp: In function 'unsigned char USI_TWI_Master_Transfer(unsigned char)':
lib/TinyWireM-master/USI_TWI_Master.cpp:263:3: error: 'USISR' was not declared in this scope
   USISR = temp;                                     // Set USISR according to temp.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:265:16: error: 'USISIE' was not declared in this scope
   temp  =  (0<<USISIE)|(0<<USIOIE)|                 // Interrupts disabled
                ^
lib/TinyWireM-master/USI_TWI_Master.cpp:265:28: error: 'USIOIE' was not declared in this scope
   temp  =  (0<<USISIE)|(0<<USIOIE)|                 // Interrupts disabled
                            ^
lib/TinyWireM-master/USI_TWI_Master.cpp:266:16: error: 'USIWM1' was not declared in this scope
            (1<<USIWM1)|(0<<USIWM0)|                 // Set USI in Two-wire mode.
                ^
lib/TinyWireM-master/USI_TWI_Master.cpp:266:28: error: 'USIWM0' was not declared in this scope
            (1<<USIWM1)|(0<<USIWM0)|                 // Set USI in Two-wire mode.
                            ^
lib/TinyWireM-master/USI_TWI_Master.cpp:267:16: error: 'USICS1' was not declared in this scope
            (1<<USICS1)|(0<<USICS0)|(1<<USICLK)|     // Software clock strobe as source.
                ^
lib/TinyWireM-master/USI_TWI_Master.cpp:267:28: error: 'USICS0' was not declared in this scope
            (1<<USICS1)|(0<<USICS0)|(1<<USICLK)|     // Software clock strobe as source.
                            ^
lib/TinyWireM-master/USI_TWI_Master.cpp:267:40: error: 'USICLK' was not declared in this scope
            (1<<USICS1)|(0<<USICS0)|(1<<USICLK)|     // Software clock strobe as source.
                                        ^
lib/TinyWireM-master/USI_TWI_Master.cpp:268:16: error: 'USITC' was not declared in this scope
            (1<<USITC);                              // Toggle Clock Port.
                ^
lib/TinyWireM-master/USI_TWI_Master.cpp:272:5: error: 'USICR' was not declared in this scope
     USICR = temp;                          // Generate positve SCL edge.
     ^
lib/TinyWireM-master/USI_TWI_Master.cpp:273:14: error: 'PIN_USI' was not declared in this scope
     while( !(PIN_USI & (1<<PIN_USI_SCL)) );// Wait for SCL to go high.
              ^
lib/TinyWireM-master/USI_TWI_Master.cpp:273:28: error: 'PIN_USI_SCL' was not declared in this scope
     while( !(PIN_USI & (1<<PIN_USI_SCL)) );// Wait for SCL to go high.
                            ^
lib/TinyWireM-master/USI_TWI_Master.cpp:276:25: error: 'USIOIF' was not declared in this scope
   }while( !(USISR & (1<<USIOIF)) );        // Check for transfer complete.
                         ^
lib/TinyWireM-master/USI_TWI_Master.cpp:279:11: error: 'USIDR' was not declared in this scope
   temp  = USIDR;                           // Read out data.
           ^
lib/TinyWireM-master/USI_TWI_Master.cpp:281:3: error: 'DDR_USI' was not declared in this scope
   DDR_USI |= (1<<PIN_USI_SDA);             // Enable SDA as output.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:281:18: error: 'PIN_USI_SDA' was not declared in this scope
   DDR_USI |= (1<<PIN_USI_SDA);             // Enable SDA as output.
                  ^
lib/TinyWireM-master/USI_TWI_Master.cpp: In function 'unsigned char USI_TWI_Master_Start()':
lib/TinyWireM-master/USI_TWI_Master.cpp:291:3: error: 'PORT_USI' was not declared in this scope
   PORT_USI |= (1<<PIN_USI_SCL);                     // Release SCL.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:291:19: error: 'PIN_USI_SCL' was not declared in this scope
   PORT_USI |= (1<<PIN_USI_SCL);                     // Release SCL.
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:296:20: error: 'PIN_USI_SDA' was not declared in this scope
   PORT_USI &= ~(1<<PIN_USI_SDA);                    // Force SDA LOW.
                    ^
lib/TinyWireM-master/USI_TWI_Master.cpp:302:9: error: 'USISR' was not declared in this scope
   if( !(USISR & (1<<USISIF)) )
         ^
lib/TinyWireM-master/USI_TWI_Master.cpp:302:21: error: 'USISIF' was not declared in this scope
   if( !(USISR & (1<<USISIF)) )
                     ^
lib/TinyWireM-master/USI_TWI_Master.cpp: In function 'unsigned char USI_TWI_Master_Stop()':
lib/TinyWireM-master/USI_TWI_Master.cpp:316:3: error: 'PORT_USI' was not declared in this scope
   PORT_USI &= ~(1<<PIN_USI_SDA);           // Pull SDA low.
   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:316:20: error: 'PIN_USI_SDA' was not declared in this scope
   PORT_USI &= ~(1<<PIN_USI_SDA);           // Pull SDA low.
                    ^
lib/TinyWireM-master/USI_TWI_Master.cpp:317:19: error: 'PIN_USI_SCL' was not declared in this scope
   PORT_USI |= (1<<PIN_USI_SCL);            // Release SCL.
                   ^
lib/TinyWireM-master/USI_TWI_Master.cpp:318:12: error: 'PIN_USI' was not declared in this scope
   while( !(PIN_USI & (1<<PIN_USI_SCL)) );  // Wait for SCL to go high.  
            ^
lib/TinyWireM-master/USI_TWI_Master.cpp:324:9: error: 'USISR' was not declared in this scope
   if( !(USISR & (1<<USIPF)) )
         ^
lib/TinyWireM-master/USI_TWI_Master.cpp:324:21: error: 'USIPF' was not declared in this scope
   if( !(USISR & (1<<USIPF)) )
                     ^
*** [.pio/build/megaatmega2560/lib124/TinyWireM-master/USI_TWI_Master.cpp.o] Error 1
================================================================ [FAILED] Took 3.19 seconds =

**Comment by JKWork3** [comment]
i work on mac whit VSC, the same program is compiled fine from Arduino IDE, i try the guide in this link but dont work: https://github.com/platformio/platformio-core/issues/1783

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/ and provide a simple project to reproduce this issue.

**Comment by JKWork3** [comment]
i try other way but dont have the same problem, i create this post:
https://community.platformio.org/t/compiling-problem-on-platformio-on-arduino-compiling-done-adafruit-tinywirem/13763?u=jackekrawattwork

Il giorno ven 15 mag 2020 alle ore 15:23 Ivan Kravets <
notifications@github.com> ha scritto:
