### ISSUE TITLE
Dynamic variables in Inherited common env not handled

### ISSUE THREAD

**Issue by drawlerr** [platformio/platformio-core#3508]
### Configuration

**Operating system**: MacOS Catalina 10.15.4

**PlatformIO Version** (`platformio --version`): 4.3.3

### Description of problem
My project has dynamic build flags in the common env section, debug and release envs both use the common build flags.  I would expect dynamic build flags to be expanded even when inherited from common env, but they are not.

#### Steps to Reproduce

1. Create minimal platform.io file like so:
```
[env]
build_flags = !cat .creds
[env:debug]
build_flags = ${env.build_flags} -D DEBUG
```
Run:
`pio run -e debug -t envdump`

### Actual Results
  'BUILD_FLAGS': ['!cat .creds', '-D DEBUG'],

### Expected Results
 'BUILD_FLAGS': [<contents of .creds>, '-D DEBUG']

### Additional info
Works fine if I copy the command into each environment manually, but I would like to be able to share common dynamic build flags

**Comment by ivankravets** [comment]
You can't have 2 options with the same name. (build_flags)
