### ISSUE TITLE
check: ignore library files

### ISSUE THREAD

**Issue by peterus** [platformio/platformio-core#3524]
- [X] **PlatformIO Core**.

### Additional info

I am using cppcheck for static code analysis. If I run `platformio check` also the used libraries are checked. Some of this libraries are not perfectly implemented and I don't want to have them in my overview.
It would be nice to have a flag to turn of cppchek on the library-files in `.pio/libdeps`

**Comment by ivankravets** [comment]
https://docs.platformio.org/en/latest/projectconf/section_env_check.html#check-patterns

**Comment by lalten** [comment]
Can you please give an example how to suppress `cppcheck` checking of `.pio/libdeps`? I tried to configure `check_flags = --suppress=*.pio`, but it still prints a long list of defects in third party code (in this case, [ETL](https://www.etlcpp.com/), on platform [native](https://docs.platformio.org/en/latest/platforms/native.html))

**Comment by peterus** [comment]
i am using this setting kn platformio.ini:


`check_flags = cppcheck: --suppress=*:*.pio\* --inline-suppr`

**Comment by lalten** [comment]
Nice, the trick is to have both the wildcard before .pio and the escaped one after. Thanks!
