### ISSUE TITLE
List dev-platform targets with a new `--list-targets` option

### ISSUE THREAD

**Issue by weberw** [platformio/platformio-core#3544]
### Configuration

**Operating system**: all

**PlatformIO Version** (`platformio --version`): 4.3.4

### Description of problem
According to https://docs.platformio.org/en/stable/projectconf/section_env_build.html#targets running `platformio run --target` should produce a list of targets, however an error is generated instead

#### Steps to Reproduce

1. `platformio run --target`

### Actual Results
```
Error: --target option requires an argument
```
### Expected Results
A list of build targets

### If problems with PlatformI

**Comment by jnr2820** [comment]
I'm seeing this too.

```
pio run --target
Error: --target option requires an argument

pio --version
PlatformIO, version 4.3.4
```

**Comment by ivankravets** [comment]
Thanks! Indeed, this feature has not been implemented yet. I renamed this issue.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev` version of PIO core. See https://docs.platformio.org/en/latest/core/userguide/cmd_run.html#cmdoption-platformio-run-list-targets

**Comment by jnr2820** [comment]
It's working for me. (Also, it is very neat. Thank you)
`
┌─[jnr2820@nano-cube-black] - [~/blink_machine] - [Fri Jun 26, 03:49]
└─[$]> platformio run --list-targets
Environment       Group     Name        Title                    Description
----------------  --------  ----------  -----------------------  -----------------------------------------------------
nanoatmega328new  Advanced  compiledb   Compilation Database     Generate compilation database 'compile_commands.json'
nanoatmega328new  Generic   clean       Clean
nanoatmega328new  Platform  bootloader  Burn Bootloader
nanoatmega328new  Platform  fuses       Set Fuses
nanoatmega328new  Platform  program     Upload using Programmer
nanoatmega328new  Platform  size        Program Size             Calculate program size
nanoatmega328new  Platform  upload      Upload
nanoatmega328new  Platform  uploadeep   Upload EEPROM
`
