### ISSUE TITLE
Where is RTOS in mbed os(v 5.14)?

### ISSUE THREAD

**Issue by zayats1** [platformio/platformio-core#3553]
https://imgur.com/uFb2Ot4

**Comment by valeros** [comment]
Hi @zayats1 ! It's hard to answer, is the RTOS enabled in `platformio.ini`
https://docs.platformio.org/en/latest/frameworks/mbed.html#mbed-lib-and-mbed-os-5

**Comment by zayats1** [comment]
Thank you!
