### ISSUE TITLE
Wrong interspercing of error message with verbose output in the terminal

### ISSUE THREAD

**Issue by tm-playground** [platformio/platformio-core#3557]
### Configuration

**Operating system**: Linux Mint 19.3 Cinnamon (but the same was observed also on Windows 7)

**PlatformIO Version** (`platformio --version`): version 4.3.4

### Description of problem

When there is an error during build and the verbose mode is active (by running "pio run -v"), the resulting error messages are interlaced with the other output (processed commands and their parameters). Sometimes, even incorrect parts of the output are colorized.

See the attached screenshot of terminal window with highlighted command parameters split (and thus hard to read) by the error message.
![Screenshot from 2020-06-11 16-55-32](https://user-images.githubusercontent.com/66616666/84421811-644c3880-ac1c-11ea-963a-42e97dcd694a.png)

**Comment by ivankravets** [comment]
PlatformIO runs a build process in multiple processes. You can run with 1 job using `pio run -j 1`.

**Comment by tm-playground** [comment]
Ok, I see. But still, since it is an output targeted for a human, I would expect it will be human-readable as much as possible (despite the technical difficulties that the multi-process build introduces).
