### ISSUE TITLE
pio device list take long time when bluetooth COM ports are installed

### ISSUE THREAD

**Issue by ajaybhargav** [platformio/platformio-core#3558]
### Configuration

**Operating system**: Windows

**PlatformIO Version** (`platformio --version`): 4.3.4

### Description of problem
This is more related to pyserial than platformio itself, However pyserial is stuck with no developments going on and since pio is heavily using pyserial for most of the serial related stuff, I guess it is has to be reported.

In short `pio device list` takes huge amount of time on widows pc when bluetooth COM ports are installed. This is because link validation is done in pyserial.

### Additional info

I have reported this issue on community here: https://community.platformio.org/t/autodetectuploadport-hit-miss-case/14143

and also made a post here:
https://community.platformio.org/t/platformio-ide-for-vscode-2-0-beta-help-us-with-testing/14097/6?u=ajaybhargav

**Comment by ivankravets** [comment]
Please report issue to https://github.com/pyserial/pyserial/issues
