### ISSUE TITLE
cppcheck for armv6

### ISSUE THREAD

**Issue by peterus** [platformio/platformio-core#3559]
What kind of issue is this?

- [x] **Question**
------------------------------------------------------------------

### Configuration

**Operating system**:
latest Raspian on Raspberry 3B

**PlatformIO Version** (`platformio --version`):
latest

### Description of problem
CorePackageManager: Installing tool-cppcheck @ ~1.190.0
Error: Could not find a version that satisfies the requirement '~1.190.0' for your system 'linux_armv7l'

#### Steps to Reproduce

platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high

### Actual Results
cppcheck can not be installed because it is not existing to download for armv7l.

### Expected Results
running cppcheck
### Additional info
Would it be possible to add cppcheck for armv7l to use it on a Raspberry 3B?

**Comment by valeros** [comment]
Hi @peterus ! We've added the Cppcheck package for ARM architecture, please upgrade your PlatformIO Core to the development version via `pio upgrade --dev` and try run the `check` command. Feel free to reopen if you have any problems.
