### ISSUE TITLE
Error: [API] Method Not Allowed

### ISSUE THREAD

**Issue by blinkinglight** [platformio/platformio-core#3582]
What kind of issue is this?

- [ ] **PlatformIO Core**.
     when trying to register lib "platformio lib register https://raw.githubusercontent.com/9glt/arduino-button/master/library.json" get this "Error: [API] Method Not Allowed"

------------------------------------------------------------------

### Configuration

**Operating system**: osx

**PlatformIO Version** (`platformio --version`): PlatformIO, version 4.3.4

### Description of problem
Error: [API] Method Not Allowed

#### Steps to Reproduce

1. platformio lib register https://raw.githubusercontent.com/9glt/arduino-button/master/library.json

### Actual Results
Error: [API] Method Not Allowed

**Comment by dimircea** [comment]
I have the same problem when trying to register this library: https://raw.githubusercontent.com/dimircea/REncoder/master/library.json

It appears to be a more general problem...

Regards,
Mircea

**Comment by ivankravets** [comment]
Fixed. Please use 
```
pio upgrade --dev
pio package publish --help
```
