### ISSUE TITLE
lib_deps  = AliyunMqttArduino,ArduinoJson,NTPClient   and  lib_deps  = AliyunMqttArduino

### ISSUE THREAD

**Issue by hzhh110** [platformio/platformio-core#3604]
lib_deps  = AliyunMqttArduino,ArduinoJson,NTPClient

[API] ConnectionError: HTTPSConnectionPool(host='api.registry.platformio.org', port=443): Max retries exceeded with url: /v2/lib/search?query=name%3A%22AliyunMqttArduino%22+name%3A%22ArduinoJson%22+name%3A%22NTPClient%22 (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) (incremented retry: max=5, total=1)

lib_deps  = AliyunMqttArduino  OK

**Comment by ivankravets** [comment]
Each dependency in a new line. Or, split with COMMA + SPACE

```
lib_deps = 
  AliyunMqttArduino
  ArduinoJson
  NTPClient
```
