### ISSUE TITLE
"pio lib register" is deprecated but "pio package publish" is unknown

### ISSUE THREAD

**Issue by OrsoEric** [platformio/platformio-core#3614]
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Win 10

**PlatformIO Version** (`platformio --version`): PlatformIO, version 4.3.4

### Description of problem
I wish to upload a library for the GD32VF103
"pio lib register" is deprecated but "pio package publish" is unknown
"pio update" returns up to date and latest version

#### Steps to Reproduce

PS F:\Project\Project Programming\Project Risc-V\Examples Working\Longan Nano GD32VF103 Screen Class Demo>platformio package
Usage: platformio [OPTIONS] COMMAND [ARGS]...
Try "platformio -h" for help.

Error: No such command "package"

### Expected Results
https://docs.platformio.org/en/latest/core/userguide/lib/cmd_register.html
https://docs.platformio.org/en/latest/core/userguide/package/cmd_publish.html#cmd-package-publish

### Additional info
![2020-08-01 PIO package](https://user-images.githubusercontent.com/30684972/89097729-c8e87000-d3e1-11ea-945b-bf5965924271.PNG)

**Comment by ivankravets** [comment]
Please run `pio upgrade --dev`. PIO Core 4.4 has not been released yet.
