### ISSUE TITLE
Please remove my ArduinoOTA library from PlatformIO Registry

### ISSUE THREAD

**Issue by jandrassy** [platformio/platformio-core#3617]
My ArduinoOTA library is not compatible with PlatformIO. Can you remove it from the PlatformIO Registry? I guess you import it from the Arduino library index.

Usage of the library relays on Arduino IDE ecosystem: arduinoOTA upload tool, network port detection and configuring platform.local.txt. This are not present in platformio as I learned from issues for my library filled by platformio users.
Also in platformio a conflict with the esp8266/esp32 core ArduinoOTA library doesn't discourage the esp users from using my library instead of the library bundled with the esp8266/esp32 core.

I get issue reports from confused platformio users.

**Comment by ivankravets** [comment]
Thanks for the report! The library has been removed from the PlatformIO Registry.
