### ISSUE TITLE
Libraries: Could not install library

### ISSUE THREAD

**Issue by jyberg** [platformio/platformio-core#3618]
Hi,
I uploaded new version of library and then removed the old one as it had dependencys problems. Now in web I can see verion 1.2.3 that is available:
https://platformio.org/lib/show/10941/Enhanced-Nextion-Library/installation

But PlatforIO only founds the original 1.2.0 version that that already removed from registry, and installation fails also Pio command with exact version number not work either.

PIO Core Call Error: "Library Storage: C:\Users\jyke\.platformio\lib\r\nLibraryManager: Installing id=10941 @ ^1.2.0\r\n\n\nError: [API] Unknown library with ID '10941'"

Can you check what is wrong...

**Comment by ivankravets** [comment]
I can't reproduce this issue. It looks like an issue with a caching on your local machine. This is a bug of PIO Core 4.3 and we fixed it in PIO Core 4.4 which is coming soon.

Next time just run `pio update` and API cache will be removed automatically.
