### ISSUE TITLE
Already installed libraries are missed in dependency search when versions aren't tagged

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#3619]
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**:  Windows 10

**PlatformIO Version** (`platformio --version`): pio 4.3.4 under vscode 

### Description of problem
Installing a 2nd library with a dependency of an already installed library causes the 1st library to be reinstalled when the first library is installed at a set version but the second does not give a specific version for the dependency.
This makes it impossible to use controlled versions of dependencies when other libraries do not specify the exact versions to use.

#### Steps to Reproduce

1.  Install OneWire, at version 2.3.4
    ```pio lib install 1@2.3.4```
2.  Install Dallas Temperature at version 3.8.0
    ```pio lib install DallasTemperature@3.8.0```

### Actual Results
1.  Library manager installs OneWire at version 2.3.4
2.  Library manager installs Dallas Temperature at version 3.8.0
3.  Dependency finder sees "OneWire" (without version specified) as a dependency in DallasTemperature's library.json.
It ignores the already installed 2.3.4 and installs 2.3.5.
4. Two versions of OneWire are installed

### Expected Results
1.  Library manager installs OneWire at version 2.3.4
2.  Library manager installs Dallas Temperature at version 3.8.0
3.  Dependency finder finds OneWire already installed and stops.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:mayfly]
platform = atmelavr
board = mayfly
framework = arduino
lib_ldf_mode = off
lib_deps =
    1@2.3.4
    DallasTemperature@3.8.0
```

**Comment by ivankravets** [comment]
Should be fixed in the latest dev version. Please re-run `pio upgrade --dev`.

Does it work now?
