### ISSUE TITLE
Project libraries (lib folder) are not detected if srcDir doesn't directly contain source files

### ISSUE THREAD

**Issue by eudes** [platformio/platformio-core#3626]
What kind of issue is this?
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**:
```
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;2;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```
**PlatformIO Version** (`platformio --version`):
```
PlatformIO, version 4.4.0a7
```

### Description of problem
I'm using a library in my platformio project that has a weird file structure. This library is included as a git submodule in my `lib` folder.

I don't want to change the file structure, because my changes are intended to be pushed upstream eventually, and I don't own the library. Instead, I'm trying to add a `library.json` file that declares where the source files are located. These files are distributed into various different folders, that all reside under a common base folder (`Custom_Panel_RevC/Arduino/` in the structure below).

The logical approach to this would be to declare a `library.json` where `srcDir` is the common folder, and you filter elements in `srcFilter`, like this:
```
{
    "name": "nts-1-customizations",
    "version": "1.0.0",
    "description": "nts-1-customizations",
    "keywords": "nts",
    "build": {
        "srcDir": "Custom_Panel_RevC/Arduino",
        "srcFilter": [
            "+<libraries/NTS-1/src/*>",
            "+<variants/**/*>"
        ]
    }
}
```
However, this approach doesn't work at all. When running `platformio run`, the log says that "No dependencies were found".

After a few hours of trying different things, I could only get it to work by doing the following:
```
{
    "name": "nts-1-customizations",
    "version": "1.0.0",
    "description": "nts-1-customizations",
    "keywords": "nts",
        "build": {
        "srcDir": "Custom_Panel_RevC/Arduino/libraries/NTS-1/src",
        "srcFilter": [
            "+<*>",
            "+<../../../variants/NTS1_REF_CP_REVC/*>"
        ]
    }
}
```
I assume this is because the `srcDir` doesn't have any source files per se, so it gets ignored.

```
.
├── Arduino
│   └── package_nts1_custom_panels_index.json
├── Custom_Panel_RevC
│   ├── Arduino
│   │   ├── libraries
│   │   │   └── NTS-1
│   │   │       ├── examples
│   │   │       │   ├── Blank_Template
│   │   │       │   │   ├── Blank_Template.ino
│   │   │       │   │   └── README.md
│   │   │       │   └── Sequencer_Template
│   │   │       │       ├── README.md
│   │   │       │       └── Sequencer_Template.ino
│   │   │       ├── keywords.txt
│   │   │       ├── library.properties
│   │   │       ├── README.md
│   │   │       └── src
│   │   │           ├── nts-1.cpp
│   │   │           └── nts-1.h
│   │   └── variants
│   │       └── NTS1_REF_CP_REVC
│   │           ├── esp32
│   │           │   └── nts1_iface.c
│   │           ├── nts1_iface.c
│   │           ├── nts1_iface.h
│   │           └── stm32
│   │               └── nts1_iface.c
│   ├── Gerber
│   ├── gerber_reference.pdf
│   ├── KiCAD
│   │   └── ...
│   └── ...
├── library.json
├── LICENSE
└── README.md
```

#### Steps to Reproduce

1. `git clone --branch platformio-library-issue --recurse-submodules git@github.com:eudes/korg-nts1-esp32.git && cd korg-nts1-esp32`
2. `platformio run`

**Note:** the code won't compile anyway, but the issue is with the dependencies, not with the code itself.

### Actual Results
```
Processing stm32 (platform: ststm32; board: nucleo_f030r8; framework: arduino)
...
Scanning dependencies...
No dependencies
....
```

### Expected Results
```
Processing stm32 (platform: ststm32; board: nucleo_f030r8; framework: arduino)
...
Scanning dependencies...
Dependency Graph
|-- <nts-1-customizations> 1.0.0
....
```
This is the result of changing `library.json` to the second version mentioned above. It's uploaded to the master branch if you want to try it out: https://github.com/eudes/nts-1-customizations

### If problems with PlatformIO Build System:
See the repo mentioned above.

**Comment by ivankravets** [comment]
1) The root of the library ALWAYS will point to the directory where the manifest was picked. You need to keep it in mind when operating with `build.flags`. 
2) `srcDir` - ONLY override the root for the SOURCE FILES
3) you MUST add as a minimum one static location where any header files are located, to help LDF pick your library for analyzing, later you will tune build process using `build_flags` keeping in ming that all flags are related to the root of dir.

See updated manifest

```json
{
    "name": "nts-1-customizations",
    "version": "1.0.0",
    "description": "nts-1-customizations",
    "keywords": "nts",
    "build": {
        "includeDir": "Custom_Panel_RevC/Arduino/variants/NTS1_REF_CP_REVC",
        "srcDir": "Custom_Panel_RevC/Arduino",
        "srcFilter": [
            "-<*>",
            "+<libraries/NTS-1/src/*>",
            "+<variants/**/*>"
        ],
        "flags": [
            "-ICustom_Panel_RevC/Arduino/variants/NTS1_REF_CP_REVC/stm32",
            "-ICustom_Panel_RevC/Arduino/libraries/NTS-1/src"
        ]
    }
}
```
