### ISSUE TITLE
"New Project" wizard not load boards

### ISSUE THREAD

**Issue by skvarovski** [platformio/platformio-core#3632]
Hi Devs
I use ISP and MobileISP
on 
Ubuntu 20.04 / Windows 10
via PlatformIO latest verison 1.10 (fresh install)
When i open New project ... i see load boards infinity

**Comment by nicraMarcin** [comment]
Hi, I have the same issue but in VSCode on ubuntu 20.04 and newest Mint. I also tried with fresh install both vsc and platformio. 
On Windows 10 works.

**Comment by skvarovski** [comment]
today its work.
additional servers avaible for content.
