### ISSUE TITLE
Could not import project

### ISSUE THREAD

**Issue by mcaycho** [platformio/platformio-core#3638]
PIO Core Call Error: "The current working directory C:\\Users\\Marco\\Documents\\PlatformIO\\Projects\\200823-153820-arduino-blink will be used for the project.\n\r\nThe next files/directories have been created in C:\\Users\\Marco\\Documents\\PlatformIO\\Projects\\200823-153820-arduino-blink\ninclude - Put project header files here\nlib - Put here project specific (private) libraries\nsrc - Put project source files here\nplatformio.ini - Project Configuration File\n\n\nError: Development platform 'atmelavr' is not compatible with PlatformIO Core v4.4.0-b.1 and depends on PlatformIO Core ^3.0.0."

**Comment by ivankravets** [comment]
Please open PIO Cli and type `pio upgrade --dev`. It should work now.
