### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 255: invalid start byte

### ISSUE THREAD

**Issue by happyme531** [platformio/platformio-core#3648]
### Configuration

**Operating system**: Ububtu 20.04

**PlatformIO Version** (`platformio --version`): 5.0.0

### Description of problem

When I compile my project, this error appeared:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/platformio/proc.py", line 46, in run
    self.do_reading()
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/platformio/proc.py", line 69, in do_reading
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
  File "/home/user/.platformio/penv/lib/python3.8/site-packages/platformio/proc.py", line 69, in <lambda>
    for byte in iter(lambda: self._pipe_reader.read(1), ""):
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 255: invalid start byte
```

This error won't break compilation process, but compiler's messages become that error message (compiler's messages not get output). 

#### Steps to Reproduce

1.Clone my M5StickC_ClassTimer project and copy project files into a blank platformio esp32-arduino project.
2.Open the project, click the build button.

### Actual Results

That error occured but build succeed.

### Expected Results

All compiler's messages show properly

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions=min_spiffs.csv
upload_speed = 1500000
monitor_speed = 115200
build_flags = -DCORE_DEBUG_LEVEL=3

```
### Additional info
The error is not caused by non-ascii characters in the project path or user name.

**Comment by ivankravets** [comment]
It seems like a known issue with Python 3.8. Please use PlatformIO IDE 2.0 for VSCode, it uses built-in portable Python 3.7 or downgrade your version.
