### ISSUE TITLE
Dependencies from private lib disappear after upgrading to Core 5.0.0

### ISSUE THREAD

**Issue by Bascy** [platformio/platformio-core#3649]
**PlatformIO Core**.

### Configuration
OS: **Windows 10**:
Version: **PlatformIO 5.0.0** 

### Description of problem
Dependencies on private library (not published on PlatformIO) are not included when building a project that using this private library

#### Steps to Reproduce
See https://community.platformio.org/t/dependencies-from-private-lib-disappear-after-upgrading-to-core-5-0-0/15720/3
with details about platform.io and library.json files

**Comment by wefleenor** [comment]
Similar dependency issues, but my programs worked fine before the upgrade and now throw multiple dependency issues.  Is there a way to turn back to the previous version of pio?

**Comment by ivankravets** [comment]
Should be fixed in https://github.com/platformio/platformio-core/commit/4f47ca57429f80006b111538769526d35eedc8d2

Please re-run `pio upgrade --dev`. Does it work now?

**Comment by GaryMatthews** [comment]
this hasn't been fixed yet? 
 ~/.platformio/penv/bin/pio upgrade --dev
PlatformIO has been successfully upgraded to 5.3.0a3
In file included from .pio/libdeps/esp12e/Adafruit GFX Library/Adafruit_GrayOLED.cpp:20:
.pio/libdeps/esp12e/Adafruit GFX Library/Adafruit_GrayOLED.h:30:10: fatal error: Adafruit_I2CDevice.h: No such file or directory

**Comment by ivankravets** [comment]
What is your `platformio.ini`?
