### ISSUE TITLE
process_extra_options always run even platform is incompatible when parse libraries

### ISSUE THREAD

**Issue by GeneKong** [platformio/platformio-core#3654]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`):  PlatformIO, version 4.3.4

### Description of problem
If we mixed different paltform libraries in same lib directory, some incompatible library extra_scripts will execute and add into flags.

If possible add some judgement before process_extra_options in piolib.py?
```python
    def process_extra_options(self):
        # Only process extra scripts in compatible platform
        if self.is_platforms_compatible(self.env.PioPlatform().name):
            with fs.cd(self.path):
                self.env.ProcessFlags(self.build_flags)
                if self.extra_script:
                    self.env.SConscriptChdir(1)
                    self.env.SConscript(
                        realpath(self.extra_script),
                        exports={"env": self.env, "pio_lib_builder": self},
                    )
                self.env.ProcessUnFlags(self.build_unflags)
```

**Comment by ivankravets** [comment]
Set https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-compat-mode to `strict`
