### ISSUE TITLE
Add support for manually installing packages (frameworks, tools, etc.) via CLI

### ISSUE THREAD

**Issue by nanosonde** [platformio/platformio-core#3656]
### Configuration

**PlatformIO Version** (`platformio --version`): 5.0.0

### Description of problem
Currently it is possible to add a new platform via `pio platform install <file>`.
I use this for example to install my custom platform during CI testing from my GitHub repo.

However, the platform is not the only archive that is required for making the custom platform to build projects.
Another archive which contains the framework (e.g. arduino core) is also required to be installed.

If the framework (or a newer version) of the framework which has **not been uploaded to the package registry** yet is to be installed during CI test run of the platform, the automatic download of the dependency (=the framework) does not work as it is not in the registry.

I would be nice to have a command like `pio package install <url>`with all supported URL types (local files, HTTP, git, etc.).

### Additional info
My current workaround is this:
```
  - pip install -U https://github.com/platformio/platformio-core/archive/master.zip
  - platformio --version
  - platformio platform install file://.
  - wget https://github.com/nanosonde/platformio-packages/raw/master/cc13xx-core-5.20.0.tar.gz
  - mkdir -p ~/.platformio/packages/framework-energiaticc13x0
  - tar xfzv cc13xx-core-5.20.0.tar.gz -C ~/.platformio/packages/framework-energiaticc13x0
```
I manually download the package and unpack it locally after creating the directories.

**Comment by ivankravets** [comment]
Implemented in https://github.com/platformio/platformio-core/commit/9e40eb992e44d3ddb7e3e8e4477d8af68766567a

Please re-test with `pio upgrade --dev` and check `pio pkg install` command. https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html
