### ISSUE TITLE
PlatformIO 5.0.1 rewriting platformio.ini when "pio lib install" is used

### ISSUE THREAD

**Issue by nomis** [platformio/platformio-core#3673]
### Configuration

**Operating system**: Ubuntu 18.04

**PlatformIO Version** (`platformio --version`): 5.0.1

### Description of problem

PlatformIO is now rewriting `platformio.ini` when `pio lib install` is used.

#### Steps to Reproduce

1. git clone https://github.com/nomis/mcu-uuid-telnet
2. cd test/build/example-DigitalIO
3. pio lib install uuid-common uuid-log
4. git diff

### Actual Results

PlatformIO has modified `build/example-DigitalIO/platformio.ini`

### Expected Results

PlatformIO does not modify `build/example-DigitalIO/platformio.ini`

### Additional info

I can't find anything in the release notes to indicate that this should be happening.

There is a `--save` option for `pio lib install` but that implies that this is not the default.

If this is now the default then there should be a `--no-save` option to stop doing this.

(I'm using `pio lib install` as a workaround for #2573.)

**Comment by ivankravets** [comment]
Sorry, we forgot to document it. See https://github.com/platformio/platformio-docs/commit/aeecb4b365c2af98162b0e8c1505616cbae9bf68
