### ISSUE TITLE
Clarify the usage of `upload_command` in docs

### ISSUE THREAD

**Issue by sprig** [platformio/platformio-core#3682]
From reading the documentation page at https://docs.platformio.org/en/latest/projectconf/section_env_upload.html?highlight=upload, it is not at all obvious that in order for `upload_command` to work, one needs to specify `upload_protocol = custom`. After a lot of trial and error, I finally found out about this at #2599. In fact, all of the examples with `upload_command` won't work due to this, as far as I understand.

I respectfully suggest updating the docs to reflect this fact.

**Comment by ivankravets** [comment]
Thanks for the PR! https://github.com/platformio/platformio-docs/pull/151
