### ISSUE TITLE
Home: Could not load recent projects

### ISSUE THREAD

**Issue by rafael1969** [platformio/platformio-core#3694]
Invalid params: {"args":["get_projects() takes 0 positional arguments but 1 was given"],"message":"get_projects() takes 0 positional arguments but 1 was given","type":"TypeError"}

**Comment by ivankravets** [comment]
Please uninstall multiple PIO Cores in a system https://docs.platformio.org/en/latest/faq.html#multiple-platformio-cores-in-a-system
