### ISSUE TITLE
Python 3.9 is not supported

### ISSUE THREAD

**Issue by dariomas** [platformio/platformio-core#3700]
# Temorary solution

Please use the latest Python 3.8 (not 3.9). See https://docs.platformio.org/en/latest/faq.html#install-python-interpreter

--------

### Configuration

**Operating system**: Linux Fedora 33

**PlatformIO Version** (`platformio --version`): PlatformIO, version 5.0.1

### Description of problem

The Platformio installer on a Linux system wit Python 3.9 (Fedora 33) hung while installing because it does not find the
'platformio/contrib-pysite @ ~2.39.0'

### Actual Results

VSCode: 1.50.0
PIO IDE: v2.1.0
System: Linux, 5.8.13-300.fc33.x86_64, x64

%23 Exception

 `Error: Error: Could not find the package with 'platformio/contrib-pysite @ ~2.39.0' requirements for your system 'linux_x86_64'`

### Additional info

A temporary resolution:

- setting in VSCode path https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-ide-custompath
`"platformio-ide.customPATH": "/home/xxxx/.platformio/penv/bin/"`

- disabling in VSCode builtin core https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-ide-usebuiltinpiocore

- installing python3.8 in Fedora 33
`dnf install python3.8`

- run the Platformio installation script with python 3.8 (creating virtualenv with python3.8)
`python3.8 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/develop/scripts/get-platformio.py)"`

- check into the `penv/bin/` that python links to 3.8

%23 Configuration

VSCode: 1.50.0
PIO IDE: v2.1.0
System: Linux, 5.8.13-300.fc33.x86_64, x64

**Comment by bronsen** [comment]
Another approach is to create a python virtualenv with the desired python version. Then start vscode from the actived virtualenv: platformio then picks ups the compatible version.

[Here are some more details](https://infuanfu.de/howto/2020/10/19/platformio-vscode-python.html), for fish shell, using pyenv and virtualfish.

**Comment by ivankravets** [comment]
Packages for Python 3.9 are published in the registry.
