### ISSUE TITLE
ino => cpp includes invalid prototypes

### ISSUE THREAD

**Issue by martgras** [platformio/platformio-core#3706]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): PlatformIO, version 5.0.1

### Description of problem
ino converter sometimes ignores conditional compilation for prototypes 
if the ino files is renamed to cpp the build succeeds 

#### Steps to Reproduce

1. Clone https://github.com/martgras/pio-ino-repro.git
2. run build 

### Actual Results

C:/code/pio-ino-repro/src/QuickStart_P.ino:28:26: error: 'WiFiEventStationModeGotIP' does not name a type

### Expected Results
compile without errors 

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
https://github.com/martgras/pio-ino-repro/blob/main/platformio.ini

**Source file to reproduce issue:**
https://github.com/martgras/pio-ino-repro/blob/main/src/QuickStart_P.ino

### Additional info

The generated cpp file contains prototypes for functions that should be ignored because  ARDUINO_ARCH_ESP8266 is not defined 

```cpp
# 1 "C:\\Users\\martin\\AppData\\Local\\Temp\\tmpwwhv48y7"
#include <Arduino.h>
# 1 "C:/code/pangolin/src/QuickStart_P.ino"
#include <arduino.h>
#ifdef ARDUINO_ARCH_ESP8266
#include <ESP8266WiFi.h>
#else
#include <WiFi.h>
#endif
...
PangolinMQTT mqttClient;
Ticker mqttReconnectTimer;
Ticker wifiReconnectTimer;
void connectToWifi();
void connectToMqtt();
void WiFiEvent(WiFiEvent_t event);

// these 2 prototypes are causing build to fail because WiFiEventStationModeGotIP is not definied if the platform is esp32 
==> void onWifiConnect(const WiFiEventStationModeGotIP& event);
==> void onWifiDisconnect(const WiFiEventStationModeDisconnected& event);

void onMqttConnect(bool sessionPresent);
void onMqttDisconnect(int8_t reason);
void onMqttMessage(const char* topic, uint8_t* payload, struct PANGO_PROPS props, size_t len, size_t index, size_t total);
void setup();
void loop();
#line 26 "C:/code/pangolin/src/QuickStart_P.ino"
void connectToWifi() {
  Serial.println("Connecting to Wi-Fi...");
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
}

...

#ifdef ARDUINO_ARCH_ESP8266
void onWifiConnect(const WiFiEventStationModeGotIP& event) {
  Serial.println("Connected to Wi-Fi.");
  connectToMqtt();
}

void onWifiDisconnect(const WiFiEventStationModeDisconnected& event) {
  Serial.println("Disconnected from Wi-Fi.");
  mqttReconnectTimer.detach();
  wifiReconnectTimer.once(RECONNECT_DELAY_W, connectToWifi);
}
#endif
...

```

**Comment by ivankravets** [comment]
Sorry for the issue. We use our Python-based INO to CPP converter and do not plan to improve it. I know, it sounds bad but it's better to say the truth instead of saying "we will fix it soon".

INO is a fake file format which breaks embedded developers who start from Arduino. INO is not valid C++ file. Please forget about it. See https://docs.platformio.org/en/latest/faq.html#convert-arduino-file-to-c-manually
