### ISSUE TITLE
Problem with Twi.h and Wire.h on Platformio

### ISSUE THREAD

**Issue by Bighoneypot** [platformio/platformio-core#3718]
Hi, I have a problem with Platformio and Wire libraries

I have a main.cpp and into a Arduino IDE works fine, but I have a problem with platformio

my Platformio.ini
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 3000000
monitor_speed = 115200
lib_deps = adafruit/DHT sensor library@^1.4.0
adafruit/Adafruit Unified Sensor@^1.1.4
adafruit/Adafruit SHT31 Library@^2.0.0

This is a result from terminal:

C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:37:2: error: #error Wire library is not supported on this board
#error Wire library is not supported on this board
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:55:30: error: 'SDA' was not declared in this scope
static int default_sda_pin = SDA;
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:56:30: error: 'SCL' was not declared in this scope
static int default_scl_pin = SCL;
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'void TwoWire::begin(int, int)':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:67:20: error: too many arguments to function 'void twi_init()'
twi_init(sda, scl);
^
In file included from C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:30:0:
C:\Users\gabri\OneDrive\Documents\Arduino\libraries\Twi/twi.h:41:8: note: declared here
void twi_init(void);
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'uint8_t TwoWire::status()':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:89:20: error: 'twi_status' was not declared in this scope
return twi_status();
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'void TwoWire::setClock(uint32_t)':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:97:25: error: 'twi_setClock' was not declared in this scope
twi_setClock(frequency);
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'void TwoWire::setClockStretchLimit(uint32_t)':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:101:33: error: 'twi_setClockStretchLimit' was not declared in this scope
twi_setClockStretchLimit(limit);
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'uint8_t TwoWire::endTransmission(uint8_t)':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:142:73: error: too few arguments to function 'uint8_t twi_writeTo(uint8_t, uint8_t*, uint8_t, uint8_t, uint8_t)'
int8_t ret = twi_writeTo(txAddress, txBuffer, txBufferLength, sendStop);
^
In file included from C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:30:0:
C:\Users\gabri\OneDrive\Documents\Arduino\libraries\Twi/twi.h:44:11: note: declared here
uint8_t twi_writeTo(uint8_t, uint8_t*, uint8_t, uint8_t, uint8_t);
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'virtual int TwoWire::available()':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:185:26: error: 'optimistic_yield' was not declared in this scope
optimistic_yield(1000);
^
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp: In member function 'uint8_t TwoWire::status()':
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\libraries\Wire\Wire.cpp:90:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
*** [.pio\build\nodemcuv2\libe34\Wire\Wire.cpp.o] Error 1
In file included from src\main.cpp:34:0:
C:\Users\gabri\OneDrive\Documents\Arduino\libraries\Twi/twi.h:41:21: error: declaration of C function 'void twi_init()' conflicts with
void twi_init(void);
^
In file included from C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:39:0,
from src\main.cpp:11:
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/twi.h:40:6: error: previous declaration 'void twi_init(unsigned char, unsigned char)' here
void twi_init(unsigned char sda, unsigned char scl);
^
In file included from src\main.cpp:34:0:
C:\Users\gabri\OneDrive\Documents\Arduino\libraries\Twi/twi.h:43:59: error: declaration of C function 'uint8_t twi_readFrom(uint8_t, uint8_t*, uint8_t, uint8_t)' conflicts with
uint8_t twi_readFrom(uint8_t, uint8_t*, uint8_t, uint8_t);
^
In file included from C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:39:0,
from src\main.cpp:11:
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/twi.h:46:9: error: previous declaration 'uint8_t twi_readFrom(unsigned char, unsigned char*, unsigned int, unsigned char)' here
uint8_t twi_readFrom(unsigned char address, unsigned char * buf, unsigned int len, unsigned char sendStop);
^
In file included from src\main.cpp:34:0:
C:\Users\gabri\OneDrive\Documents\Arduino\libraries\Twi/twi.h:44:67: error: declaration of C function 'uint8_t twi_writeTo(uint8_t, uint8_t*, uint8_t, uint8_t, uint8_t)' conflicts with
uint8_t twi_writeTo(uint8_t, uint8_t*, uint8_t, uint8_t, uint8_t);
^
In file included from C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:39:0,
from src\main.cpp:11:
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/twi.h:45:9: error: previous declaration 'uint8_t twi_writeTo(unsigned char, unsigned char*, unsigned int, unsigned char)' here
uint8_t twi_writeTo(unsigned char address, unsigned char * buf, unsigned int len, unsigned char sendStop);
^
In file included from src\main.cpp:34:0:
C:\Users\gabri\OneDrive\Documents\Arduino\libraries\Twi/twi.h:46:56: error: declaration of C function 'void twi_attachSlaveRxEvent(void ()(uint8_t, int))' conflicts with
void twi_attachSlaveRxEvent( void ()(uint8_t, int) );
^
In file included from C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/Arduino.h:39:0,
from src\main.cpp:11:
C:\Users\gabri.platformio\packages\framework-arduinoespressif8266\cores\esp8266/twi.h:51:6: error: previous declaration 'void twi_attachSlaveRxEvent(void ()(uint8_t, size_t))' here
void twi_attachSlaveRxEvent(void ()(uint8_t, size_t));
^
*** [.pio\build\nodemcuv2\src\main.cpp.o] Error 1
================================================================================================== [FAILED] Took 8.90 seconds ==================================================================================================
The terminal process "C:\Users\gabri.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by ivankravets** [comment]
Please report to https://community.platformio.org/
