### ISSUE TITLE
Additional libraries included in .clang_complete

### ISSUE THREAD

**Issue by vakker** [platformio/platformio-core#3728]
### Configuration

**Operating system**: Ubuntu 20.10

**PlatformIO Version** (`platformio --version`): 5.0.2

### Description of problem
I'm using Emacs with the generated .clang_complete. I installed the Adafruit NeoPixel library, but my lsp doesn't find the required header `Adafruit_NeoPixel.h`. However, I can compile and upload from Emacs.

#### Steps to Reproduce

1. create project
2. run `pio lib install "adafruit/Adafruit NeoPixel"`
3. add `#include <Adafruit_NeoPixel.h>` to the code

### Actual Results
`Adafruit_NeoPixel.h file not found` warning.

### Expected Results
No warning.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_deps = adafruit/Adafruit NeoPixel@^1.6.0
```

**Source file to reproduce issue:**
```cpp
#include "Arduino.h"
#include <Adafruit_NeoPixel.h>

...
```

**Comment by ivankravets** [comment]
You need to re-init the project when adding new dependencies. Navigate to the project and run `pio project init --ide emacs`
