### ISSUE TITLE
Building fails in Windows when "&" is in path

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platformio-core#3746]
- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows

**PlatformIO Version** (`platformio --version`): ?

### Description of problem

A user reports (https://community.platformio.org/t/cant-build-my-project/17312) that when a building a project, the build output only says `avr-g++: fatal error: no input files` or `The system cannot find the path specified.`. When executing `pio run` in the PlatformIO CLI, the error is 

```
> avr-g++ -o .pio\build\nanoatmega328\lib109\EtherCard\dns.cpp.o -c -fno-exceptions -fno-threadsafe-statics -fpermissive -std=gnu++11 -Os -Wall -ffunction-sections -fdata-sections -flto -mmcu=atmega328p -DPLATFORMIO=50003 -DARDUINO_AVR_NANO -DF_CPU=16000000L -DARDUINO_ARCH_AVR -DARDUINO=10808 -Ilib\EtherCard -IC:\Users\Oleg&Vika\.platformio\packages\framework-arduino-avr\cores\arduino -IC:\Users\Oleg&Vika\.platformio\packages\framework-arduino-avr\variants\eightanaloginputs lib\EtherCard\dns.cpp
At line:1 char:324
+ ... INO_ARCH_AVR -DARDUINO=10808 -Ilib\EtherCard -IC:\Users\Oleg&Vika\.pl ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation     
marks ("&") to pass it as part of a string.
At line:1 char:402
+ ... packages\framework-arduino-avr\cores\arduino -IC:\Users\Oleg&Vika\.pl ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation     
marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
``` 

So it seems to me that because of this username `Olega&Vika`, passing file names via the shell is somehow screwed up and `&` is a special shell character in that regard.

I don't know if it's an issue in SCons or PlatformIO, so I first open the issue here and if it doesn't fit we can open one at SCons.

#### Steps to Reproduce

1. Set Windows username to contain an ampersand
2. Create a project
3. Build it

### Actual Results

Build failure as described above

### Expected Results

Paths and shell characters are escaped correctly.

**Comment by ivankravets** [comment]
It seems like a system issue and we will not be able to fix it. Nevertheless, there is a very good workaround https://docs.platformio.org/en/latest/envvars.html#envvar-PLATFORMIO_CORE_DIR

So, could you ask the user to set it for example to `C:\.platformio`? (system environment variable)

Thanks!
