### ISSUE TITLE
Request support for Heltec CubeCell-GPS (HTCC-AB02S)

### ISSUE THREAD

**Issue by artbotterell** [platformio/platformio-core#3748]
As recommended in my terminal.  Thanks!

**Comment by valeros** [comment]
Already available in the [ASR Microelectronics ASR605x](https://docs.platformio.org/en/latest/platforms/asrmicro650x.html#boards) platform.

**Comment by artbotterell** [comment]
Sorry, wasn’t precise.  The request was meant to be for debugging support on the AB02S.

**Comment by valeros** [comment]
Anyway, this repository is not the right place. Please open an issue here https://github.com/HelTecAutomation/platform-asrmicro650x
