### ISSUE TITLE
Implement --environment argument for pio ci

### ISSUE THREAD

**Issue by mairas** [platformio/platformio-core#3754]
What kind of issue is this?

- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------

### Description of problem

We're building a subset of SensESP examples as CI smoke tests on GitHub Actions. Our default platformio.ini defines d1_mini and esp32dev as the default environments. They get built sequentially for each example. This is pretty much as expected, and fine. However, it would be nice if you could limit (or redefine) the environments in `pio ci` like you can in `pio run`.

It would be nice if the `--environment` command line argument was supported also for `pio ci`.

This would allow e.g. building some example only in some environments, or increasing parallelisation by defining the examples and environments as separate matrix dimensions.

TIA!

**Comment by ivankravets** [comment]
Why you can't use directly `pio run -e`?

**Comment by ivankravets** [comment]
Please reopen if you still need help
