### ISSUE TITLE
SCons ignoring updated configuration in PlatformFactory when building programmatically

### ISSUE THREAD

**Issue by andyshinn** [platformio/platformio-core#3766]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: macOS 10.15.7

**PlatformIO Version** (`platformio --version`): PlatformIO, version 5.0.3

### Description of problem

First, I understand this may be out of scope and unsupported. If that is the case and it is not an issue worth pursuing then I understand if you want to close the issue.

I am trying to use `platformio` as a library to build programmatically in Python. I am building a `PlatformConfig` and `PlatformFactory`. I then update the default `PlatformFactory.config` with my built config (no file). But when SCons comes time to build the project it ends up ignoring this config because it appears to initialize a new one at https://github.com/platformio/platformio-core/blob/3e7e9e2b3d1b75cd76fc623b6adf9927f35f4225/platformio/builder/tools/pioproject.py#L20-L21

It feels like it should be reusing the configuration from the `PlatformFactory`. But maybe I am doing something wrong?
#### Steps to Reproduce

Example code:

```
import os
import sys
import configparser

from platformio.platform.factory import PlatformFactory
from platformio.project.config import ProjectConfig

platform = "espressif8266@2.6.2"
dir = "/Users/andy/Documents/GitHub/andyshinn/wled"

os.chdir(dir)

s = '''[env:quinled_dig_test]
extends = env:d1_mini
build_flags = ${common.build_flags_esp8266}
  -D USERMOD_DALLASTEMPERATURE
  -D USERMOD_DALLASTEMPERATURE_CELSIUS
lib_deps = ${env.lib_deps}
  milesburton/DallasTemperature@^3.9.0
  OneWire@~2.3.5'''

cc = configparser.ConfigParser()
cc.read_string(s)
pf = PlatformFactory.new("espressif8266@2.6.2")
pf.config.update([(cc.sections()[0], list(cc[cc.sections()[0]].config.items()))])
variables = variables = {"pioenv": "quinled_dig_test", "project_config": pf.config.path}
pr.run()
```

This works with WLED config from project config folder to extend:

```
[env:d1_mini]
board = d1_mini
platform = ${common.platform_wled_default}
platform_packages = ${common.platform_packages}
upload_speed = 921600
board_build.ldscript = ${common.ldscript_4m1m}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags_esp8266}
monitor_filters = esp8266_exception_decoder
```

### Actual Results
The resulting build will fail because `env.get("BOARD")` is empty (the `env:quinled_dig_test` is gone at this point).

### Expected Results
The `config` object loaded by `ProjectFactory` should be preserved even when updated to add configuration on the fly and passed to SCons instead of initializing a new one.

### Additional info

Related to https://community.platformio.org/t/building-programmatically-in-another-python-project/17568 (original question).

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/building-programmatically-in-another-python-project/17568/6?u=ivankravets
