### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by geoph9** [platformio/platformio-core#3780]
### Description

I just started using `esphome` and while I was trying to `run` a test project I got the following error (which is related to platformio):

```python
  File "/path-to-virtual-env/lib64/python3.7/site-packages/platformio/package/manifest/parser.py", line 174, in normalize_repository
    url = (data.get("repository") or {}).get("url")
AttributeError: 'str' object has no attribute 'get'
```

I have used the PlatformIO vscode extension before and I have had no problem, so I am not entirely sure why this happens here. 

### Configuration

**Operating system**:

- Fedora 33
- Python 3.7 (virtual environment - python 3.9 had other issues)

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 4.3.4

#### Steps to Reproduce

1. Create python 3.7 virtual environment: `python3.7 -m venv env` (and activate it)
2. Create esphome project: `esphome test.yaml wizard`
3. Run project  `esphome test.yaml rum`

### Solution

The problem was that in line 174 `data.get("repository")` was returning an `str` object at some occassions and so I simply added an extra check (if the output is string and convert to dict with a key `url`). Below is the `normalize_repository` function which currently works for me.

```python
    @staticmethod
    def normalize_repository(data):
        if isinstance(data.get("repository"), str):
            # In some cases the 'repository' attribute contains only a string
            # and the .get method will not work.
            data['repository'] = {'url': data['repository']}
        url = (data.get("repository") or {}).get('url')
        if not url or "://" not in url:
            return data
        url_attrs = urlparse(url)
        if url_attrs.netloc not in ("github.com", "bitbucket.org", "gitlab.com"):
            return data
        url = "https://%s%s" % (url_attrs.netloc, url_attrs.path)
        if url.endswith("/"):
            url = url[:-1]
        if not url.endswith(".git"):
            url += ".git"
        data["repository"]["url"] = url
        return data
```

Everything is running fine now so that seems to do the job. Hope this is helpful!

**Comment by ivankravets** [comment]
> PlatformIO, version 4.3.4

What is it? https://docs.platformio.org/en/latest/core/migration.html
