### ISSUE TITLE
c_cpp_properties.json.tpl Incorrect

### ISSUE THREAD

**Issue by atestani** [platformio/platformio-core#3785]
The template  is generating comment lines with "//" comments which are not allowed in json files.  These lines (87-90):
//
// !!! WARNING !!! AUTO-GENERATED FILE!
// PLEASE DO NOT MODIFY IT AND USE "platformio.ini":
// https://docs.platformio.org/page/projectconf/section_env_build.html#build-flags
//

should be removed and some other way to include the warning be added.

**Comment by maxgerhardt** [comment]
Reference to thread: https://community.platformio.org/t/failed-to-parse-c-cpp-properties-json/17861

**Comment by ivankravets** [comment]
VSCode uses its own JSON parser that allows comments. It seems like you use some extension that tries to parse VSCode JSON file and as a bare JSON.

**Comment by atestani** [comment]
I fixed it by finding I had *TWO* C/C++ extensions where one was an
extension pack by Microsoft v1.0.0 and the other C/C++ v 1.13 also by
Microsoft.  I was unable to uninstall either of the C/C++ extensions
because PIO "required them".  I uninstalled PIO and both extensions and
reinstalled PIO and the v1.13 C/C++ extension and the issue is resolved.

Thanks for the lead.

**Comment by ivankravets** [comment]
Great that you resolved it!

Happy coding with PlatformIO!
