### ISSUE TITLE
support for engduino

### ISSUE THREAD

**Issue by pelikhan** [platformio/platformio-core#38]
Hi Ivan,

How do you usually proceed to add a library in platformio? We would like to be able to target Engduino.

```
https://code.google.com/p/engduino/wiki/InstallingEngduinoV3
```

**Comment by pelikhan** [comment]
Engduino requires the TwoWire library (http://arduino.cc/en/Reference/Wire) but I could not find it in the library repo.

**Comment by ivankravets** [comment]
We are working on it with Engduino team. Just include in your source file this line:
```c
#include <Wire.h>
```

The `Wire.h` library is bundled with Arduino Framework by default.
