### ISSUE TITLE
ccls support is broken

### ISSUE THREAD

**Issue by ettom** [platformio/platformio-core#3808]
### Configuration

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 5.0.4
### Description of problem
Starting with 5.0.4, ccls support is broken for `--ide vim` (possibly others), no language server related features seem to be working. It seems that the problem is the first line of the generated `.ccls` file. It's now the full path to the used compiler, however according to [ccls documentation](https://github.com/MaskRay/ccls/wiki/Project-Setup#compiler-driver), it should contain the name of a compiler driver - either `clang` or `clang++`. This was changed in 32181d1bd298c368993bd1264d7e595163fb70a4.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`. Does it work now?

**Comment by ettom** [comment]
Yes, it works now. Thank you!

**Comment by ivankravets** [comment]
Thanks that reported!

Happy coding with PlatformIO!
