### ISSUE TITLE
Libraries: Could not uninstall library

### ISSUE THREAD

**Issue by tolgaberk** [platformio/platformio-core#3816]
PIO Core Call Error: "Library Storage: /Users/tolga/Documents/PlatformIO/Projects/smava/.pio/libdeps/nodemcuv2\nLibrary Manager: Removing AsyncHTTPRequest_Generic @ 1.1.1\nLibrary Manager: Removing dependencies...\nLibrary Manager: Removing AsyncTCP @ 1.1.1\nLibrary Manager: AsyncTCP @ 1.1.1 has been removed!\nLibrary Manager: Removing ESPAsync_WiFiManager @ 1.4.2\nLibrary Manager: Removing dependencies...\nLibrary Manager: Removing ESP Async WebServer @ 1.2.3\nLibrary Manager: Removing dependencies...\nLibrary Manager: Removing ESPAsyncTCP @ 1.2.2\nLibrary Manager: ESPAsyncTCP @ 1.2.2 has been removed!\nLibrary Manager: ESP Async WebServer @ 1.2.3 has been removed!\nLibrary Manager: Removing ESP_DoubleResetDetector @ 1.1.1\nLibrary Manager: Removing dependencies...\nLibrary Manager: Removing LittleFS_esp32 @ 1.0.5\nLibrary Manager: LittleFS_esp32 @ 1.0.5 has been removed!\nLibrary Manager: ESP_DoubleResetDetector @ 1.1.1 has been removed!\nLibrary Manager: ESPAsync_WiFiManager @ 1.4.2 has been removed!\nLibrary Manager: Removing STM32duino LwIP @ 2.1.2\nLibrary Manager: STM32duino LwIP @ 2.1.2 has been removed!\nLibrary Manager: Removing STM32Ethernet @ 1.2.0\nLibrary Manager: STM32Ethernet @ 1.2.0 has been removed!\n\n\nError: Traceback (most recent call last):\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/__main__.py\", line 109, in main\n    cli()  # pylint: disable=no-value-for-parameter\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 829, in __call__\n    return self.main(*args, **kwargs)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 782, in main\n    rv = self.invoke(ctx)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/commands/__init__.py\", line 44, in invoke\n    return super(PlatformioCLI, self).invoke(ctx)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1259, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 1066, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/core.py\", line 610, in invoke\n    return callback(*args, **kwargs)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/click/decorators.py\", line 21, in new_func\n    return f(get_current_context(), *args, **kwargs)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/commands/lib/command.py\", line 215, in lib_uninstall\n    uninstalled_pkgs = {\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/commands/lib/command.py\", line 216, in <dictcomp>\n    library: lm.uninstall(library, silent=silent) for library in libraries\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_uninstall.py\", line 29, in uninstall\n    return self._uninstall(spec, silent, skip_dependencies)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/_uninstall.py\", line 46, in _uninstall\n    self.uninstall_dependencies(pkg, silent)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/package/manager/library.py\", line 147, in uninstall_dependencies\n    PackageSpec(\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/package/meta.py\", line 117, in __init__\n    self.requirements = requirements\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/platformio/package/meta.py\", line 162, in requirements\n    else semantic_version.SimpleSpec(str(value))\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/semantic_version/base.py\", line 618, in __init__\n    self.clause = self._parse_to_clause(expression)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/semantic_version/base.py\", line 1014, in _parse_to_clause\n    return cls.Parser.parse(expression)\n  File \"/Users/tolga/.platformio/penv/lib/python3.8/site-packages/semantic_version/base.py\", line 1034, in parse\n    raise ValueError(\"Invalid simple block %r\" % block)\nValueError: Invalid simple block 'https://github.com/philbowles/STM32AsyncTCP'\n\n============================================================\n\nAn unexpected error occurred. Further steps:\n\n* Verify that you have the latest version of PlatformIO using\n  `pip install -U platformio` command\n\n* Try to find answer in FAQ Troubleshooting section\n  https://docs.platformio.org/page/faq.html\n\n* Report this problem to the developers\n  https://github.com/platformio/platformio-core/issues\n\n============================================================"

**Comment by Utopists** [comment]
Processing esp32dev (platform: espressif32; board: esp32dev; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------
Removing unused dependencies...
SemanticVersionError: Invalid simple block ''

This suddenly appeared when trying to compile a C++ program with Platformio on VS.  Can't find any decipherable clues as to what is wrong and how to fix it?
