### ISSUE TITLE
Why is pio so slow to create a project every time?

### ISSUE THREAD

**Issue by china-zhangdj** [platformio/platformio-core#3821]

**Comment by ivankravets** [comment]
If you create a new project first time, PlatformIO downloads dependent packages. You can use [PlatformIO Core CLI](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-core-cli) and [pio project init](https://docs.platformio.org/en/latest/core/userguide/project/cmd_init.html) command. You will see all progress.

**Comment by china-zhangdj** [comment]
Thank you.
