### ISSUE TITLE
Please add support for BIGTREETECH SKR PRO V1.2

### ISSUE THREAD

**Issue by MetallianFR68** [platformio/platformio-core#3838]
Please add native support for this card.

Name: BIGTREETECH BTT SKR PRO V1.2
Documentations : https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/SKR-PRO-V1.2/manual
Schematics : https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/SKR-PRO-V1.2/Schematic
Where this hardware can be purchased : https://www.bigtree-tech.com/

This board definition seems to be compatible with V1.1 and V1.2 of the board
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/blob/master/firmware/SKR%20ProV1.1-Marlin_v2.0-Demo/buildroot/share/PlatformIO/boards/BigTree_SKR_Pro.json

They have a variant definition here :
https://github.com/bigtreetech/BIGTREETECH-SKR-PRO-V1.1/tree/master/firmware/SKR%20ProV1.1-Marlin_v2.0-Demo/buildroot/share/PlatformIO/variants/BIGTREE_SKR_PRO_1v1

Thanks in advance !
Best regards

**Comment by ivankravets** [comment]
Please forward to https://github.com/MarlinFirmware/Marlin/issues
