### ISSUE TITLE
Mks PIO tool failed

### ISSUE THREAD

**Issue by ChrisYOLO** [platformio/platformio-core#3843]
==> Installing Python Package Manager ...

Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

[FAILURE]
The installation process has been FAILED!
Please report about this problem here
< https://github.com/platformio/platformio-core/issues > 
This is the error output i got from MKS-Marlin2.0 Compile tool

**Comment by Jason2866** [comment]
Did you try to compile this https://github.com/makerbase-mks/Mks-Robin-Nano-Marlin2.0-Firmware ?
Just tried does work and the firmware is compiled successful

**Comment by ivankravets** [comment]
Please reopen if you still need help
