### ISSUE TITLE
ZoneStar

### ISSUE THREAD

**Issue by LeonardCross** [platformio/platformio-core#3844]
What kind of issue is this?

- [x ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

I have a ZoneStar z9m4 in which I am having a very difficult time is finding information. Like what kind of board it has so I can update the firmware.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
> I am having a very difficult time is finding information

Sorry, no info.
