### ISSUE TITLE
"Bad JSON" error in Inspect tab with multiple code check tools

### ISSUE THREAD

**Issue by GovorovViva64** [platformio/platformio-core#3847]
As described [in this topic](https://community.platformio.org/t/pvs-studio-will-return-bad-json-error-when-run/19203), when multiple tools are specified in the `check_tool` parameter (platformio.ini), the Project Inspection produces a "Bad JSON" error.
That happens even if some incorrect tools are specified i.e.
`check_tool = pvs-studio, foo`

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3790
