### ISSUE TITLE
Support for Rpi Pico board?

### ISSUE THREAD

**Issue by lo-gain** [platformio/platformio-core#3861]
What kind of issue is this?

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform
Do you have any plans to add support for the Rpi Pico? Apologies if this is in the wrong place or has been asked a thousand times already. Regards, Colin.

**Comment by valeros** [comment]
Duplicate https://github.com/platformio/platformio-core/issues/3805
