### ISSUE TITLE
Can't Login to all PIO's services

### ISSUE THREAD

**Issue by Kamilake** [platformio/platformio-core#3866]
What kind of issue is this?

- [x] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 10 20H2 with WSL Ubuntu 20.10 (Groovy Gorilla)

VScode 1.53.2
**PlatformIO Version** (`platformio --version`):

PlatformIO Core, version 5.1.0

#### Steps to Reproduce

1. Install Platformio.
2. Log In with PlatformIO Account or Log In with OAuth
![image](https://user-images.githubusercontent.com/15166740/109587129-e03f3580-7b49-11eb-9e77-7784e8825405.png)

### Actual Results
Error output at the top "code not valid"

When I use GitHub login, I get a message like this:
![image](https://user-images.githubusercontent.com/15166740/109587424-68253f80-7b4a-11eb-8d96-7a155f54f2bc.png)

### Expected Results
Retrieve my information with successful login.

### Additional info

I am a new user of pio. And I tried to create a new account and it failed.
I don't have permission to write on pio forums, and I can't write on Reddit.

Because they all require login.

I will provide any additional information needed.
I apologize for the lack of information.

**Comment by ivankravets** [comment]
Could you try again?

**Comment by Kamilake** [comment]
> Could you try again?

Thank you for replying.
It still doesn't work and when I click the login button it prints 'Not Found' at address 127.0.0.1.
![image](https://user-images.githubusercontent.com/15166740/109741169-e0a20400-7c0f-11eb-9536-56140a8049a1.png)
![image](https://user-images.githubusercontent.com/15166740/109741187-e861a880-7c0f-11eb-9d79-fb5da7e69794.png)

**Comment by ivankravets** [comment]
Could you try to remove all cookies or open that URL in the private window in Google chrome?

**Comment by Kamilake** [comment]
> Could you try to remove all cookies or open that URL in the private window in Google chrome?
Thanks for the reply.
![image](https://user-images.githubusercontent.com/15166740/109889067-fffc6800-7cc7-11eb-8a4e-d402a26fc7f6.png)

![image](https://user-images.githubusercontent.com/15166740/109889083-0ab6fd00-7cc8-11eb-9559-2ac39953aa64.png)

Deleting cookies didn't work for me.
But the New Incognito tab worked successfully.
Although the problem has not been completely resolved, it has made the official forum accessible. Thanks! I'm going to write there.

**Comment by Kamilake** [comment]
![image](https://user-images.githubusercontent.com/15166740/109890055-e825e380-7cc9-11eb-92b7-1462272dd6b0.png)
![image](https://user-images.githubusercontent.com/15166740/109890193-363ae700-7cca-11eb-9f1a-802aa4ff163f.png)

But still I can't log in from VScode-WSL.
When you click the login button, the following window is displayed.
I used the Chrome built-in cookie, clear cache feature, and I used the EditThisCookie extension. This problem could not be solved using Incognito.

Please do not hesitate to let me know if you have any additional information you need.

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by Kamilake** [comment]
> Have you resolved this issue?

No, it got worse.
![image](https://user-images.githubusercontent.com/15166740/110739535-b934e200-8274-11eb-989e-6badda68d0b9.png)
Now the browser is not showing up..

This problem only occurs in WSL.
so I have given up on WSL for now.

**Comment by ivankravets** [comment]
WSL is not currently supported.
