### ISSUE TITLE
Using $PROJECT_DIR on WIN10 results in a strange path string

### ISSUE THREAD

**Issue by captFuture** [platformio/platformio-core#3869]
What kind of issue is this?

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

---------------------------------------------

### Configuration

**Win10 Pro**:

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 5.1.0

### Description of problem
As stated in this community post (https://community.platformio.org/t/using-project-dir-on-win10-results-in-a-strange-path-string/15882) the outcome of a pathstring for including a config file via build flags results in a strange behaviour on windows 10.

#### Steps to Reproduce

1. Use build flag in platformio.ini 
build_flags =
‘-include $PROJECT_DIR\configs\variables_${extra.unitid}.h’ or

build_flags =
‘-include C:\sketchdir\configs\variables_${extra.unitid}.h

2. Try to compile sketch and watch output

### Actual Results
cc1plus.exe: fatal error: **./** C:\sketchdir\configs\variables_815.h: Invalid argument

### Expected Results
C:\sketchdir\configs\variables_815.h gets included with no error

**Comment by valeros** [comment]
Hi @captFuture ! Is there a reason that you wrapped both flags using `'`? The following variant should work just fine:
```ini
build_flags =
    -include "$PROJECT_DIR/configs/variables_${extra.unitid}.h"
```

**Comment by ivankravets** [comment]
Please reopen if you still need help
