### ISSUE TITLE
Please add support for debugging NodeMCU 1.0 (ESP-12E Module)

### ISSUE THREAD

**Issue by peternlewis** [platformio/platformio-core#3873]
Feature Request

As requested I am requesting support for debugging NodeMCU 1.0.

If this is not the right place, then I am reporting a bug that the text in the error:

>Error: Currently, PlatformIO does not support debugging for `NodeMCU 1.0 (ESP-12E Module)`.
>Please request support at https://github.com/platformio/platformio-core/issues 
>or visit -> https://docs.platformio.org/page/plus/debugging.html

Should be updated.

### Configuration

Mac OS X Big Sur

**PlatformIO Version** (`platformio --version`):

It's not clear to me how or where to run that. Pretty current given I only just installed it a few days ago.

**Comment by ivankravets** [comment]
ESP8266 does not support hardware debugging. Please use ESP32 or other MCU
