### ISSUE TITLE
Upload fails with "serial.serialutil.SerialException: could not open port 'COM5': FileNotFoundError..."

### ISSUE THREAD

**Issue by WhiteLionATX** [platformio/platformio-core#3875]
All my projects (espressif32/espressif8266) drop this error when I try to upload.
platformio.ini: "upload_port = COM8" <- thats the right one. Autodetect in terminal works fine. Only upload fails and shows COM5 instead of COM8.
I guess this issue was caused by an update.

`Traceback (most recent call last):
  File "C:\Users\Admin\.platformio\packages\tool-esptoolpy\esptool.py", line 3969, in <module>  _main()
  File "C:\Users\Admin\.platformio\packages\tool-esptoolpy\esptool.py", line 3962, in _main main()
  File "C:\Users\Admin\.platformio\packages\tool-esptoolpy\esptool.py", line 3551, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "C:\Users\Admin\.platformio\packages\tool-esptoolpy\esptool.py", line 271, in __init__ self._port = serial.serial_for_url(port)
  File "c:\users\Admin\.platformio\penv\lib\site-packages\serial\__init__.py", line 90, in serial_for_url instance.open()
  File "c:\users\Admin\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM5': FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden.', None, 2)`

**Comment by ivankravets** [comment]
It looks like other process uses this COM port. Try to reboot machine and try again.

**Comment by WhiteLionATX** [comment]
> It looks like other process uses this COM port. Try to reboot machine and try again.

The are no devices connected to other COM ports than COM8. I restarted multiple times. Debug works like charm while upload doesn´t. Nothing helped. Any other ideas that could help me to find the problem ? - Thx!

**Comment by WhiteLionATX** [comment]
> It looks like other process uses this COM port. Try to reboot machine and try again.

I MADE DOWN GRADE TO V2.21 AND THAT FIXED IT ! SO MARK THIS AS BUG PLEASE!!!

**Comment by ivankravets** [comment]
what is 2.21?

**Comment by WhiteLionATX** [comment]
PlatformIO V2.2.1

**Comment by ivankravets** [comment]
This issue is not related to PlatformIO IDE for VSCode. You could potentially have opened serial monitor sessions in the VSCode terminal

**Comment by SpacewormSera** [comment]
I have the same error even after restarting windows and I know for sure that no one else uses this port

**Comment by SpacewormSera** [comment]
I found out what was my problem: in platformio.ini i wrote "upload_port = 9"  but after I changed it to "port = 9"  all worked!
