### ISSUE TITLE
Remove framework coupling from platforms

### ISSUE THREAD

**Issue by dzarda** [platformio/platformio-core#3888]
- [x] **Feature Request**

------------------------------------------------------------------
Disclosure: I'm working on porting ChibiOS as a framework.

### Description of problem
Frameworks seem to be tightly coupled to platforms. When a new framework is added, it must be mentioned in the related platform(s). This constrains framework creation. 

### Rationale
1. Simplify creation of new frameworks.
2. Make frameworks more easily movable between platforms. Ideally, make it possible to create a multi-platform framework.

### Possible solution
Code in https://github.com/platformio/platform-ststm32/tree/develop/builder/frameworks tells me that largely this coupling is just forward logic (invoking `platformio-build.py`). Maybe this could be done automatically?

In the same sense that frameworks don't have to list all the libraries they support, this would make the hierarchy cleaner.

**Comment by ivankravets** [comment]
See example how do we use the same framework for the multiple dev-platforms https://github.com/platformio/platform-nordicnrf52/blob/develop/builder/frameworks/zephyr.py
