### ISSUE TITLE
Nested Base Environments in platformio.ini

### ISSUE THREAD

**Issue by fazerlicourice7** [platformio/platformio-core#3891]
- [ X] **Feature Request**.
      Add the ability to have nested base environments in `platformio.ini`.
     For example:
```
[env]
platform = teensy
board = teensy41
framework = arduino

[env:cryo]
lib_deps = 
    adafruit/Adafruit MCP9600 Library@^1.1.1

[env:cryo:E1_coldflow]
src_filter = -<*> +<E1_coldflow/>
build_flags = -DHAL=teensy

[env:cryo:E1_coldflow_v2]
src_filter = -<*> +<E1_coldflow_v2/>
build_flags = -DHAL=teensy
```

------------------------------------------------------------------

### Additional info

Currently, the single default env is pretty restrictive, I'd like the ability to dynamically change dependencies w/out having to change the dependencies on every single image. Additionally this is very useful for doing embedded vs native (w/ a HAL) development.

**Comment by ivankravets** [comment]
You need https://docs.platformio.org/en/latest/projectconf/section_env_advanced.html#extends
