### ISSUE TITLE
Dynamic build flags and reading from stdin creates error when building

### ISSUE THREAD

**Issue by baender** [platformio/platformio-core#3897]
# Temporary solution

Please use extra script as described at https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html

--------
- [x] **PlatformIO IDE**.
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 Home, 20H2, 64 bit

**PlatformIO Version**: PlatformIO Core, version 5.1.1

**Python**: 3.9.2, 64 bit

**VSCode**: 1.54.3

**NodeJS**: 12.18.3

### Description of problem
 
When using Dynamic Build Flags with Python's `input()` for reading from stdin and building, the following error occurs
```
Traceback (most recent call last):
  File "getName.py", line 2, in <module>
    stationName = input("***Enter station name***\n")
EOFError: EOF when reading a line
OSError: 'python getName.py' exited 1:
```

#### Steps to Reproduce

1. Add the following line to your environment in `platformio.ini`
`build_flags = !python getName.py`

2. Create file `getName.py` with the following content
```py
stationName = "dummy"
# stationName = input("***Enter station name***\n")

print("-DSTATION_NAME='\"%s\"'" % stationName)
```

3. Build with `stationName = "dummy"`
4. Switch to `stationName = input("***Enter station name***\n")` and build

### Actual Results

When using `dummy`: everything works as expected.
When using `input()`: Throws the error stated above and does not ask for any input via stdin.

### Expected Results

It should behave the same in both cases.

**The content of `platformio.ini`:**
```ini
[env:mkrnb1500]
platform = atmelsam
board = mkrnb1500
framework = arduino
build_flags = 
  !python getName.py
```

**Source file to reproduce issue:** (does not matter)
```cpp
#include <Arduino.h>

void setup() {
    Serial.begin(9600);
    while(!Serial);
}

void loop() {
    Serial.print("This station is called: ");
    Serial.println(STATION_NAME);
    delay(5000);
}

```

**Comment by ivankravets** [comment]
It seems like the issue is related to [SCons project](https://scons.org/).

A temporary solution is to use https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html

**Comment by ivankravets** [comment]
Please reopen if you still need help
