### ISSUE TITLE
Nixos: Detected unknown package

### ISSUE THREAD

**Issue by phodina** [platformio/platformio-core#3920]
I'm attempting to run PlatformIO on Nixos 20.09. But I get error regarding python package:

```
$> nix-shell -p platformio gcc-arm-embedded python38 python38Packages.pyopenssl

[nix-shell:~/Marlin]$ pio home
CorePackageManager: Installing contrib-pysite @ ~2.38.0
Error: Detected unknown package 'contrib-pysite'

[nix-shell:~/Marlin]$ pio --version
PlatformIO, version 4.3.4
```

When I attempt to build Marlin FW I also get issue regarding ARM GCC:
```
[nix-shell:~/Marlin]$ pio run
Processing LPC1768 (platform: https://github.com/p3p/pio-nxplpc-arduino-lpc176x/archive/0.1.3.zip; board: nxp_lpc1768; framework: arduino)
---------------------------------------------------------------------------------------------------------------------
PackageManager: Installing toolchain-gccarmnoneeabi @ >=1.90000
Error: Detected unknown package 'toolchain-gccarmnoneeabi'
```

Any hints what to patch or fix?

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/custom-platform-packagerepositories-alternative-4-3-x-continued-support/20264/3?u=ivankravets

There are 2 options here:

1. Use official installation script of PlatformIO Core https://docs.platformio.org/en/latest/core/index.html
2. Ask Nixos maintainers to update PlatformIO Core package to the latest 5.0 branch.
