### ISSUE TITLE
PlatformIO update command has a git issue on Portduino platform

### ISSUE THREAD

**Issue by hpsaturn** [platformio/platformio-core#3929]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [x] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Debian GNU/Linux 10 (buster)

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 5.1.1

### Description of problem

After run `pio update` I have the next error:

```bash
Platform portduino
--------
Updating git+https://github.com/geeksville/platform-portduino.git 1.1.2+sha.4e2251a                  [Updating to 1.1.2+sha.0edd298]
git version 2.20.1
fatal: refusing to merge unrelated histories
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']
```

#### Steps to Reproduce

1. `pio update`
2.
3.

### Actual Results

```bash
Platform portduino
--------
Updating git+https://github.com/geeksville/platform-portduino.git 1.1.2+sha.4e2251a                  [Updating to 1.1.2+sha.0edd298]
git version 2.20.1
fatal: refusing to merge unrelated histories
Error: VCS: Could not process command ['git', 'pull', '--recurse-submodules']
```

**Comment by ivankravets** [comment]
Something went wrong with your local cloned version. Please `pio platform uninstall portduino` and install again.
