### ISSUE TITLE
PlatformIO Installation Issue Windows 10

### ISSUE THREAD

**Issue by rohanprakash12** [platformio/platformio-core#3931]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [X ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

Object.<anonymous> - C:\Users\rohan\AppData\Local\atom\app-1.56.0\resources\app.asar\exports\shell.js:4:6
Object.<anonymous> - C:\Users\rohan\AppData\Local\atom\app-1.56.0\resources\app.asar\exports\shell.js:9:3
Module._compile - <embedded>:11:149837
Object..js - <embedded>:11:153385
Module.load - internal/modules/cjs/loader.js:815:32
Module._load - internal/modules/cjs/loader.js:727:14

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 10
**PlatformIO Version** (`platformio --version`):

### Description of problem
2.7.2

#### Steps to Reproduce

1.Install platformio
2.click platformio tab
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

### Additional info
I am unable to install platform IO for atom on my windows 10 with python 3.5.

**Comment by ivankravets** [comment]
> python 3.5.

Python 3.5 is not supported. Please uninstall it and install the latest using this guide https://docs.platformio.org/en/latest/faq.html#install-python-interpreter
