### ISSUE TITLE
Add Raspberry Pi Pico support

### ISSUE THREAD

**Issue by Can-too** [platformio/platformio-core#3937]
-  **Feature Request**.
      I would like  to use PlatformIO with my Raspberry PI PICO to code in MicroPython

------------------------------------------------------------------

### Additional info
Raspberry Pi Pico powered by RP2040 dual-core Cortex-M0+ microcontroller designed in-house by the Raspberry Pi Foundation

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/728
