### ISSUE TITLE
Can not create new project

### ISSUE THREAD

**Issue by nimaltd** [platformio/platformio-core#3938]
![image](https://user-images.githubusercontent.com/4112219/115952420-086c6480-a4fb-11eb-8b51-e4c8884ea796.png)

I can not create new project for esp32 arduino platform

core 5.1.1 
python 3.9.4
win10

**Comment by ivankravets** [comment]
Seems like an issue with the Internet conenction. PlatformIO needs the Internet first time to download dependent packages.

In any case, please forward this issue to https://community.platformio.org/
