### ISSUE TITLE
Feature-request: allowing the use of "src_dir" also in the env section

### ISSUE THREAD

**Issue by nielsnl68** [platformio/platformio-core#3945]
- [X ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

Lately i'm starting to use platformio for more and more projects. 
One project is becoming so big that i needed to break it appart. 

That is with the following folder structure:
> ├── src
> │   ├── bridge
> │   │   └── main.cpp
> │   └── commBadge
> │       └── main.cpp

I tried to add the src_dir option in the env sections but that failed because it is now only allowed in the top level section (under platformio). My suggestion is to allow the use of src_dir also under the env section. To me that makes more sense then using the work-a-round like:

  src_filter= -<*> +<your_sub_project>

**Comment by Jason2866** [comment]
Why not using lib to place additional env specific code?

**Comment by ivankravets** [comment]
Please reopen if you still need help
