### ISSUE TITLE
STM32RTC library is wrongly tagged in the library manager

### ISSUE THREAD

**Issue by wilmardo** [platformio/platformio-core#3966]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**PlatformIO Version** (`platformio --version`): 5.1.1

### Description of problem
The STM32RTC library has a wrong 1.1.0 tag of May 2020. The 1.1.0 tag has just been released and this currently breaks building with this library with the `ststm32` platform.
See here for some more information: https://github.com/stm32duino/STM32RTC/issues/49

The maintainer of the library suggest that the issue lays on the PIO side :)

**Comment by ivankravets** [comment]
It should be fixed automatically. https://platformio.org/lib/show/5502/STM32duino%20RTC
