### ISSUE TITLE
Feature Request: Add support for STM32H755 (Nucelo-H755ZI-Q) board

### ISSUE THREAD

**Issue by anirudh-upadhya** [platformio/platformio-core#3979]
Feature Request - Could you please add STM32H755 (Nucelo-H755ZI-Q)

**Comment by maxgerhardt** [comment]
Board requests shuold go to https://github.com/platformio/platform-ststm32/issues.

**Comment by anirudh-upadhya** [comment]
Issue closed as a new replica is created in https://github.com/platformio/platform-ststm32/issues. 
New issue - https://github.com/platformio/platform-ststm32/issues/538.
