### ISSUE TITLE
Add support for Picoprobe

### ISSUE THREAD

**Issue by lorenzgeisser** [platformio/platformio-core#3993]
Could you include the [Picoprobe](https://github.com/raspberrypi/picoprobe) as a debugging option in PlatformIO? It would be very useful if we could debug and program the [Raspberry Pi Pico](https://www.raspberrypi.org/products/raspberry-pi-pico/) (with the [RP2040](https://datasheets.raspberrypi.org/rp2040/rp2040-datasheet.pdf) MCU) projects with an under $5 device.

**Comment by maxgerhardt** [comment]
I aggree, but this issue should opened in https://github.com/platformio/platform-raspberrypi/issues though.

**Comment by lorenzgeisser** [comment]
moved to https://github.com/platformio/platform-raspberrypi/issues
