### ISSUE TITLE
Include clashing in PIO, works in Arduino IDE

### ISSUE THREAD

**Issue by microtronics** [platformio/platformio-core#4003]
### Configuration

**Operating system**: Windows 10 64bit

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 5.1.1

### Description of problem

When a library contains a Header identically named as one of a core they get mixed up. This does not happen in Arduino IDE.
https://community.platformio.org/t/pio-issue-clashing-includes-working-in-arduino-ide/22428
In this case, the ststm32 core has a "timer.h" and the RF24Ethernet library has another "timer.h" with different contents and meaning.

#### Steps to Reproduce

Use the platformio.ini below on an empty project and try to build it

### Actual Results

Building fails due to missing typedefs that are part of the other "timer.h"

### Expected Results

Building should work fine, as in Arduino IDE

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:nucleo_l053r8]
platform = ststm32
board = nucleo_l053r8
framework = arduino

lib_deps = nrf24/RF24Ethernet@1.6.8
```

**Source file to reproduce issue:**
None needed. (default Arduino template is sufficient)

### Additional info

Some might argue that header names should be unique and so on, but in a growing project with different libraries I doubt this is realistic. The obvious workaround is to rename one of the occurences. However, I think this should be fixed as it works on the Arduino IDE

**Comment by valeros** [comment]
Hi @microtronics! PlatformIO gives library includes a higher priority than the Arduino IDE and hence you see that error. You can take a look at the discussion here https://github.com/platformio/platformio-core/issues/1914, especially this comment https://github.com/platformio/platformio-core/issues/1914#issuecomment-439939637. 

So I believe renaming of conflicted is the best workaround at the moment.
