### ISSUE TITLE
udev rule for Portenta

### ISSUE THREAD

**Issue by liningpan** [platformio/platformio-core#4014]
What kind of issue is this?

- [ ] **PlatformIO Core**.

Arduino Protenta has a VID:PID of 2341:035B, which is not captured by the current udev rule for other arduino boards. 

Current udev rule:
```
ATTRS{idVendor}=="2341", ATTRS{idProduct}=="[08][02]*", MODE:="0666", ENV{ID_MM_DEVICE_IGNORE}="1", ENV{ID_MM_PORT_IGNORE}="1"
```
Possible modification:
```
ATTRS{idVendor}=="2341", ATTRS{idProduct}=="[08][023]*", MODE:="0666", ENV{ID_MM_DEVICE_IGNORE}="1", ENV{ID_MM_PORT_IGNORE}="1"
```
Without this modification, dfu cannot upload to Portenta H7 properly.

**Comment by valeros** [comment]
Thanks updated, please don't hesitate to submit a PR next time!
