### ISSUE TITLE
Support multi-licensed packages

### ISSUE THREAD

**Issue by 2bndy5** [platformio/platformio-core#4037]
I noticed the [license field of the library.json](https://docs.platformio.org/en/latest/librarymanager/config.html#license) only takes a string with 1 SPDX identifier. I have a lib that distributes with 3 different licenses (all have a SPDX identifier). I was wondering how to go about specifying this in the JSON (if possible). I would have guessed that the license field could optionally take a list of strings (all SPDX identifiers) in this scenario.

In the Meantime I have resorted to only specifying 1 of the 3 licenses in the JSON (its not published to PIO registry yet).

**Comment by ivankravets** [comment]
See updated docs for https://docs.platformio.org/en/latest/librarymanager/config.html#license

You need to use [SPDX Expression](https://spdx.github.io/spdx-spec/SPDX-license-expressions/).
