### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by Luxtech** [platformio/platformio-core#4045]
What kind of issue is this?
Problem while compiling firmware for SKR-e3 3d printer board
------------------------------------------------------------------

### Configuration

**Operating system**:
Fedora 32
**PlatformIO Version** (`platformio --version`):
5.1.1. (installed with pip3)
### Description of problem
I tried to compile 3d printer firmware for my SKR-E3 3d printer board and got the following error:
`AttributeError: module 'enum' has no attribute 'IntFlag'`

#### Steps to Reproduce

1. clone the firmware that uses platformio from the repository:
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/tree/master/Firmware 
2. run the following command: `platformio run`  in the following folder:  `BIGTREETECH-SKR-E3-DIP-V1.0/Firmware/Marlin-2.0.7.2-SKR-E3-DIP/ `
(where the platformio.ini file is located)

### Actual Results
the following error:
`
Traceback (most recent call last):
  File "/home/lux/.platformio/packages/tool-scons/scons.py", line 87, in <module>
    import SCons.Script
  File "/home/lux/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Script/__init__.py", line 71, in <module>
    import SCons.Action
  File "/home/lux/.platformio/packages/tool-scons/scons-local-4.1.0/SCons/Action.py", line 104, in <module>
    import pickle
  File "/usr/lib64/python3.8/pickle.py", line 34, in <module>
    import re
  File "/usr/lib64/python3.8/re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
`

### Expected Results
A compiled binary file

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/blob/master/Firmware/Marlin-2.0.7.2-SKR-E3-DIP/platformio.ini
```

**Source file to reproduce issue:**
```
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-DIP-V1.0/tree/master/Firmware 
```

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
