### ISSUE TITLE
Cannot create any File

### ISSUE THREAD

**Issue by Unshown** [platformio/platformio-core#4052]
`PIO Core Call Error: "[WinError 2] Das System kann die angegebene Datei nicht finden"`

This error occurs when trying to create anything via the local website which is run through IntelliJ CLion

Antivirus is completely off and i just installed PlatformIO Freshly.

I have this problem on all of my PCs and i am sick of finding the problem now all i read is Disable Antivirus but i dont even have an antivirus installed and my Windows Defender is turned off...

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
