### ISSUE TITLE
Add support for BigTreeTech Octopus Version 1.1 board

### ISSUE THREAD

**Issue by 1979mgb** [platformio/platformio-core#4066]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [x ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [x ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

I'm a major Newbie.

Windows 10 Home Version 21H1
Visual Studio Code Version 1.60.2

PlatformIO Core 5.2.0  Home 3.3.4 

Can't find BigTreeTech Octopus Version 1.1 board in PlatformIO/QuickAccess/PIO Home/Boards.
When I try to open new project, I'm stuck at "Select a Board".

**Comment by ivankravets** [comment]
Please forward to https://github.com/MarlinFirmware/Marlin
