### ISSUE TITLE
nrf5340-DK hardware support

### ISSUE THREAD

**Issue by JonasForssell** [platformio/platformio-core#4079]
**Feature Request**.

I would like to request support for the new nrf5340 - DK board from Nordic Semiconductor

https://www.nordicsemi.com/Products/Development-hardware/nRF5340-DK

Official supported with Zephyr but can also be programmed using the nrfx libraries which is a more traditional low-level approach.

https://github.com/NordicSemiconductor/nrfx

**Comment by domhardt** [comment]
Why was this issue closed? It seems that the [nRF5340](https://www.nordicsemi.com/Products/nRF5340) ist still unsupported.

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/3978
