### ISSUE TITLE
Intellisense don't pick nested configs up in macos

### ISSUE THREAD

**Issue by ptiza-v-nebe** [platformio/platformio-core#4081]
Hello,
as maxgerhardt suggested in [here](https://community.platformio.org/t/intellisense-broken-with-wildcard-config/23960), I would like to post following issue. This is VSCode related, sorry if this is wrong place for that.

------------------------------------------------------------------

### Configuration

**Operating systems**:
macOS 10.15.7
macOS 10.13.6

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 5.2.1
PlatformIO IDE v2.3.3
VSCode 1.61.1

### Description of problem

Nested ini configurations not properly processed by Intellisense of VSCode. Includes missing in .vscode/c_cpp_properties.json file. Actual code is compiling only Intellisense is not working.

**Project structure:**
proj/platformio.ini
proj/src/brain_node/inc
proj/src/brain_node/src
proj/src/brain_node/node.ini
proj/src/exec_node/inc
proj/src/exec_node/src
proj/src/exec_node/node.ini

#### Steps to Reproduce

1. clone https://github.com/maxgerhardt/pio-lib-access-project-includes
2. cd into pio-lib-access-project-includes
3. execute pio init --ide=vscode
4. observe c_cpp_properties.json in .vscode of the project
 
### Actual Results in c_cpp_properties.json

```json
{
“configurations”: [
{
“name”: “PlatformIO”,
“includePath”: [
“proj/include”,
“proj/src”,
“proj/src/exec_node/inc”,
…
}
```

### Expected Results in c_cpp_properties.json
```json
{
“configurations”: [
{
“name”: “PlatformIO”,
“includePath”: [
“proj/include”,
“proj/src”,
“proj/src/exec_node/inc”,
“proj/src/brain_node/inc”,
…
}
```

**The content of `proj/platformio.ini`:**
```ini
[platformio]
extra_configs = src/*/node.ini

[base_env]
base_extra_scripts = 
    pre:scripts/add_inc_src.py
```

**The content of `proj/src/exec_node/node.ini`:**
```ini
[env:exec_node]
platform = ststm32
board = nucleo_h743zi
framework = arduino
extra_scripts = 
    ${base_env.base_extra_scripts}
```

**The content of `proj/src/brain_node/node.ini`:**
```ini
[env:brain_node]
platform = ststm32
board = nucleo_h743zi
framework = arduino
extra_scripts =
    ${base_env.base_extra_scripts}
build_flags = -I include23
```

**The content of `add_inc_src.py`:**
```python
Import("env")
from os import path

PIOENV = env.subst("$PIOENV")
PROJECT_SRC_DIR = env.subst("$PROJECT_SRC_DIR")

#add include path
env.Append(
    CPPPATH=[path.join(PROJECT_SRC_DIR, PIOENV, "inc")]
)

#add src path
env.Append(
    SRC_FILTER=["+<"+ PIOENV +">"]
)
```

Adding or removing inc/ folders don't make difference, Intellisense still don't pick them up.

With regards,
Ivan

**Comment by joined** [comment]
>  PlatformIO allows you to work with only ONE dev environment for code completion.

@ivankravets I just hid a roadblock because of this, I'm wondering if there are any plans to support multiple dev environments for code completion? I could try contributing to this feature.
