### ISSUE TITLE
Why PIO not Support Pic Microcontroller with 8 Bit or 16 Bit or 32 Bit

### ISSUE THREAD

**Issue by MaxBayne** [platformio/platformio-core#4101]
i try to use PIO for programming PIC MCU
like 8 Bit Called PIC16F877A
but i cant to do it , any help for that and need answer why PIO Not Support PIC MCU LIke AVR MCU
Thanks

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-core/issues/704

**Comment by s-celles** [comment]
@MaxBayne It's a bit late but you may be interested by https://github.com/platformio/platformio-core/issues/704#issuecomment-3075061143 (still very experimental)
