### ISSUE TITLE
INA3221::GetRawShuntVoltage is signed, but bit shifted.

### ISSUE THREAD

**Issue by LaughtonAndrew** [platformio/platformio-core#4103]
INA3221.cpp   INA3221::GetRawShuntVoltage Line 139

This raw shunt voltage can be negative, however when it is bit shifted the negative bit becomes the most significant bit, and the value is now positive, and much higher than it should be.

Either the value needs to be divided by 8, or the constant INA3221_SHUNT_VOLTAGE_LSB needs to be divided by 8 to maintain the signed bit as the signed bit.

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
