### ISSUE TITLE
The next files/directories have been created when I installing ESP32-IDF with vscode ide

### ISSUE THREAD

**Issue by Yecgaa1** [platformio/platformio-core#4109]
When I installing ESP32-IDF with vscode ide, I have a problem. By the way, this is my first time using ESP32-IDF in this computer

`
PIO Core Call Error: "The current working directory C:\\Users\\Vikki\\Documents\\PlatformIO\\Projects\\Esp32 will be used for the project.\r\n\r\nThe next files/directories have been created in C:\\Users\\Vikki\\Documents\\PlatformIO\\Projects\\Esp32\r\ninclude - Put project header files here\r\nlib - Put here project specific (private) libraries\r\nsrc - Put project source files here\r\nplatformio.ini - Project Configuration File\r\n\n\nError: Processing esp32-c3-devkitm-1 (platform: espressif32; board: esp32-c3-devkitm-1; framework: espidf)\r\n--------------------------------------------------------------------------------\r\nVerbose mode can be enabled via `-v, --verbose` option\r\nCONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-c3-devkitm-1.html\r\nPLATFORM: Espressif 32 (3.4.0) > Espressif ESP32-C3-DevKitM-1\r\nHARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash\r\nDEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)\r\nPACKAGES: \r\n - framework-espidf 3.40301.0 (4.3.1) \r\n - tool-cmake 3.16.4 \r\n - tool-esptoolpy 1.30100.210531 (3.1.0) \r\n - tool-idf 1.0.1 \r\n - tool-mconf 1.4060000.20190628 (406.0.0) \r\n - tool-ninja 1.9.0 \r\n - toolchain-riscv32-esp 8.4.0+2021r1 \r\n - toolchain-xtensa-esp32s2 8.4.0+2021r1\r\nReading CMake configuration...\r\n-- Found Git: E:/Git/cmd/git.exe (found version \"2.32.0.windows.2\") \r\n-- The C compiler identification is GNU 8.4.0\r\n-- The CXX compiler identification is GNU 8.4.0\r\n-- The ASM compiler identification is GNU\r\n-- Found assembler: C:/Users/Vikki/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc.exe\r\n-- Check for working C compiler: C:/Users/Vikki/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc.exe\r\n-- Check for working C compiler: C:/Users/Vikki/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-gcc.exe -- works\r\n-- Detecting C compiler ABI info\r\n-- Detecting C compiler ABI info - done\r\n-- Detecting C compile features\r\n-- Detecting C compile features - done\r\n-- Check for working CXX compiler: C:/Users/Vikki/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++.exe\r\n-- Check for working CXX compiler: C:/Users/Vikki/.platformio/packages/toolchain-riscv32-esp/bin/riscv32-esp-elf-g++.exe -- works\r\n-- Detecting CXX compiler ABI info\r\n-- Detecting CXX compiler ABI info - done\r\n-- Detecting CXX compile features\r\n-- Detecting CXX compile features - done\r\n-- Project is not inside a git repository, or git repository has no commits; will not use 'git describe' to determine PROJECT_VER.\r\n-- Building ESP-IDF components for target esp32c3\r\n-- Project sdkconfig file C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/sdkconfig.esp32-c3-devkitm-1\r\n-- Found PythonInterp: C:/Users/Vikki/.platformio/penv/Scripts/python.exe (found version \"3.9.8\") \r\n-- Could NOT find Perl (missing: PERL_EXECUTABLE) \r\n-- App \"Esp32\" version: 1\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom/esp32c3/ld/esp32c3.rom.ld\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom/esp32c3/ld/esp32c3.rom.api.ld\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom/esp32c3/ld/esp32c3.rom.libgcc.ld\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom/esp32c3/ld/esp32c3.rom.newlib.ld\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom/esp32c3/ld/esp32c3.rom.version.ld\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom/esp32c3/ld/esp32c3.rom.eco3.ld\r\n-- Adding linker script C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/.pio/build/esp32-c3-devkitm-1/esp-idf/esp32c3/esp32c3_out.ld\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp32c3/ld/esp32c3.project.ld.in\r\n-- Adding linker script C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp32c3/ld/esp32c3.peripherals.ld\r\n-- Components: __pio_env app_trace app_update asio bootloader bootloader_support bt cbor cmock coap console cxx driver efuse esp-tls esp32c3 esp_adc_cal esp_common esp_eth esp_event esp_gdbstub esp_hid esp_http_client esp_http_server esp_https_ota esp_https_server esp_hw_support esp_ipc esp_local_ctrl esp_netif esp_pm esp_ringbuf esp_rom esp_serial_slave_link esp_system esp_timer esp_websocket_client esp_wifi espcoredump esptool_py expat fatfs freemodbus freertos hal heap idf_test jsmn json libsodium log lwip mbedtls mdns mqtt newlib nghttp nvs_flash openssl partition_table protobuf-c protocomm pthread riscv sdmmc soc spi_flash spiffs src tcp_transport tcpip_adapter tinyusb unity vfs wear_levelling wifi_provisioning wpa_supplicant\r\n-- Component paths: C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/.pio/build/esp32-c3-devkitm-1/__pio_env C:/Users/Vikki/.platformio/packages/framework-espidf/components/app_trace C:/Users/Vikki/.platformio/packages/framework-espidf/components/app_update C:/Users/Vikki/.platformio/packages/framework-espidf/components/asio C:/Users/Vikki/.platformio/packages/framework-espidf/components/bootloader C:/Users/Vikki/.platformio/packages/framework-espidf/components/bootloader_support C:/Users/Vikki/.platformio/packages/framework-espidf/components/bt C:/Users/Vikki/.platformio/packages/framework-espidf/components/cbor C:/Users/Vikki/.platformio/packages/framework-espidf/components/cmock C:/Users/Vikki/.platformio/packages/framework-espidf/components/coap C:/Users/Vikki/.platformio/packages/framework-espidf/components/console C:/Users/Vikki/.platformio/packages/framework-espidf/components/cxx C:/Users/Vikki/.platformio/packages/framework-espidf/components/driver C:/Users/Vikki/.platformio/packages/framework-espidf/components/efuse C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp-tls C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp32c3 C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_adc_cal C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_common C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_eth C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_event C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_gdbstub C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_hid C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_http_client C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_http_server C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_https_ota C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_https_server C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_hw_support C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_ipc C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_local_ctrl C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_netif C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_pm C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_ringbuf C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_rom C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_serial_slave_link C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_system C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_timer C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_websocket_client C:/Users/Vikki/.platformio/packages/framework-espidf/components/esp_wifi C:/Users/Vikki/.platformio/packages/framework-espidf/components/espcoredump C:/Users/Vikki/.platformio/packages/framework-espidf/components/esptool_py C:/Users/Vikki/.platformio/packages/framework-espidf/components/expat C:/Users/Vikki/.platformio/packages/framework-espidf/components/fatfs C:/Users/Vikki/.platformio/packages/framework-espidf/components/freemodbus C:/Users/Vikki/.platformio/packages/framework-espidf/components/freertos C:/Users/Vikki/.platformio/packages/framework-espidf/components/hal C:/Users/Vikki/.platformio/packages/framework-espidf/components/heap C:/Users/Vikki/.platformio/packages/framework-espidf/components/idf_test C:/Users/Vikki/.platformio/packages/framework-espidf/components/jsmn C:/Users/Vikki/.platformio/packages/framework-espidf/components/json C:/Users/Vikki/.platformio/packages/framework-espidf/components/libsodium C:/Users/Vikki/.platformio/packages/framework-espidf/components/log C:/Users/Vikki/.platformio/packages/framework-espidf/components/lwip C:/Users/Vikki/.platformio/packages/framework-espidf/components/mbedtls C:/Users/Vikki/.platformio/packages/framework-espidf/components/mdns C:/Users/Vikki/.platformio/packages/framework-espidf/components/mqtt C:/Users/Vikki/.platformio/packages/framework-espidf/components/newlib C:/Users/Vikki/.platformio/packages/framework-espidf/components/nghttp C:/Users/Vikki/.platformio/packages/framework-espidf/components/nvs_flash C:/Users/Vikki/.platformio/packages/framework-espidf/components/openssl C:/Users/Vikki/.platformio/packages/framework-espidf/components/partition_table C:/Users/Vikki/.platformio/packages/framework-espidf/components/protobuf-c C:/Users/Vikki/.platformio/packages/framework-espidf/components/protocomm C:/Users/Vikki/.platformio/packages/framework-espidf/components/pthread C:/Users/Vikki/.platformio/packages/framework-espidf/components/riscv C:/Users/Vikki/.platformio/packages/framework-espidf/components/sdmmc C:/Users/Vikki/.platformio/packages/framework-espidf/components/soc C:/Users/Vikki/.platformio/packages/framework-espidf/components/spi_flash C:/Users/Vikki/.platformio/packages/framework-espidf/components/spiffs C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/src C:/Users/Vikki/.platformio/packages/framework-espidf/components/tcp_transport C:/Users/Vikki/.platformio/packages/framework-espidf/components/tcpip_adapter C:/Users/Vikki/.platformio/packages/framework-espidf/components/tinyusb C:/Users/Vikki/.platformio/packages/framework-espidf/components/unity C:/Users/Vikki/.platformio/packages/framework-espidf/components/vfs C:/Users/Vikki/.platformio/packages/framework-espidf/components/wear_levelling C:/Users/Vikki/.platformio/packages/framework-espidf/components/wifi_provisioning C:/Users/Vikki/.platformio/packages/framework-espidf/components/wpa_supplicant\r\n-- Configuring incomplete, errors occurred!\r\nSee also \"C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/.pio/build/esp32-c3-devkitm-1/CMakeFiles/CMakeOutput.log\".\r\nSee also \"C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/.pio/build/esp32-c3-devkitm-1/CMakeFiles/CMakeError.log\".\r\n\r\nCMake Error at .pio/build/esp32-c3-devkitm-1/CMakeFiles/git-data/grabRef.cmake:48 (file):\r\n file failed to open for reading (No such file or directory):\r\n\r\n C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/.pio/build/esp32-c3-devkitm-1/CMakeFiles/git-data/head-ref\r\nCall Stack (most recent call first):\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/third_party/GetGitRevisionDescription.cmake:80 (include)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/third_party/GetGitRevisionDescription.cmake:90 (get_git_head_revision)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/build.cmake:67 (git_describe)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/build.cmake:165 (__build_get_idf_git_revision)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/idf.cmake:50 (__build_init)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/project.cmake:7 (include)\r\n CMakeLists.txt:2 (include)\r\n\r\n\r\nCMake Error at .pio/build/esp32-c3-devkitm-1/CMakeFiles/git-data/grabRef.cmake:48 (file):\r\n file failed to open for reading (No such file or directory):\r\n\r\n C:/Users/Vikki/Documents/PlatformIO/Projects/Esp32/.pio/build/esp32-c3-devkitm-1/CMakeFiles/git-data/head-ref\r\nCall Stack (most recent call first):\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/third_party/GetGitRevisionDescription.cmake:80 (include)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/third_party/GetGitRevisionDescription.cmake:90 (get_git_head_revision)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/project.cmake:52 (git_describe)\r\n C:/Users/Vikki/.platformio/packages/framework-espidf/tools/cmake/project.cmake:395 (__project_get_revision)\r\n CMakeLists.txt:3 (project)\r\n\r\n\r\n\r\n========================= [FAILED] Took 12.20 seconds
`

Win10 system
vscode 
ESP32-C3 board 
ESP-IDF Framework

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
