### ISSUE TITLE
Feature request:  Add ability to skip dependencies in library install/uninstall

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#4119]
What kind of issue is this?

- [x] **Feature Request**

------------------------------------------------------------------

### Additional info

It would be nice to have to option of uninstalling or installing a library while ignoring dependencies.  I very much appreciate (<3!) the automatic dependency retrieval and clean-up afterwards, but sometimes it would be nice to just ignore the dependencies.

**Comment by ivankravets** [comment]
Implemented in https://github.com/platformio/platformio-core/commit/9e40eb992e44d3ddb7e3e8e4477d8af68766567a

Please re-test with `pio upgrade --dev` and check `pio pkg install --skip-dependencies` command. https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html
