### ISSUE TITLE
Accelerometer_And_Gyroscope_LSM6DS3 library is not the lated version

### ISSUE THREAD

**Issue by FarFlyer** [platformio/platformio-core#4128]
### Configuration

**Operating system**: Windows 10 Version	10.0.19042 Build 19042

**PlatformIO Version** Core 5.2.3·Home 3.4.0

### Description of problem

The library Accelerometer And Gyroscope LSM6DS3 by Seeed Studio is shown in version 2.0.0, released on 2019-11-28T07:49:17Z

This version is not the latest and has issues.

The latest version can be found on GitHub at [here](https://github.com/Seeed-Studio/Accelerometer_And_Gyroscope_LSM6DS3).

The versioning can be misleading, the latest on GitHub of this library is marked as 1.0.1, but it's indeed newer that the 2.0.0 in platform IO.

Is it possible to update platform IO to point the correct lib?

**Comment by ivankravets** [comment]
Please forward the issue to https://github.com/Seeed-Studio/Accelerometer_And_Gyroscope_LSM6DS3/issues

See https://raw.githubusercontent.com/Seeed-Studio/Accelerometer_And_Gyroscope_LSM6DS3/master/library.properties

Ask them to make a tag for 2.0.0
