### ISSUE TITLE
Add support for Cypress EZ-USB FX3

### ISSUE THREAD

**Issue by nschurando** [platformio/platformio-core#4136]
What kind of issue is this?
- Development Platform or Board.
- Feature Request.
------------------------------------------------------------------
I am interested in adding support for the Cypress EZ-USB FX3 microcontroller. I would be happy to help, but I'm not sure where to start.

Here are the [product page](https://www.cypress.com/products/ez-usb-fx3-superspeed-usb-30-peripheral-controller) and the [datasheet](https://www.cypress.com/file/140296/download).

It is an ARM926 with 512 kB SRAM with multiple peripherals in particular a 5 Gbps USB 3 controller with built-in PHY. Which makes it frequently used in video over usb products.

There is an [official CYUSB3KIT-003 development board](https://www.cypress.com/documentation/development-kitsboards/cyusb3kit-003-ez-usb-fx3-superspeed-explorer-kit) with an integrated debugger.

![CYUSB3KIT-003 development board](https://user-images.githubusercontent.com/1104104/145407163-cf5b64c4-76af-4965-8481-a18ebf7e8e6e.png)

**Comment by Dantali0n** [comment]
I'd like to add that the same toolchain is used to program the FX2 that supports 480mbps USB 2.

**Comment by ivankravets** [comment]
Please vote 👍  for this issue https://github.com/platformio/platformio-core/issues/2052
