### ISSUE TITLE
Debian Docker Image with prebuilt pio cli

### ISSUE THREAD

**Issue by theionSami** [platformio/platformio-core#4148]
I opened this issue as Enhancement for CI/CD for embedded developpers:

I created a docker image for automation testing. you can found it here 

https://hub.docker.com/r/theionbatteries/platformio_docker_linux_amd64

This image can be used as a base image for further Integration:

example: github self hosted runner-> container created by runner on workflow 

https://hub.docker.com/r/theionbatteries/platformio_docker_linux_amd64-github-runner

**Comment by ivankravets** [comment]
@theionSami thanks for your contribution to the PlatformIO ecosystem.

Could we ask you to share this amazing project with our community? So, more people will see it. Please move it to https://community.platformio.org/c/projects-made-with-platformio/14
