### ISSUE TITLE
Built-in variable $PIOPLATFORM expands with = (equals-sign) in-front

### ISSUE THREAD

**Issue by synco** [platformio/platformio-core#4171]
- [x] **PlatformIO Core**.
      If you’ve found a bug

Built-in variable $PIOPLATFORM expands with = (equals-sign) in-front of the platform name. Suspect this is not meant to be? -as it could cause confusion and problems in macro expansions etc.

------------------------------------------------------------------

### Configuration

**Operating system**: ALL

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 5.2.2

### Description of problem

**The content of `platformio.ini`:**
Example: 
```ini
[env:linux_x86_64]
platform = linux_x86_64
build_flags = 
	${env.build_flags} 
	-D=${PIOPLATFORM}
	-v
```

#### Steps to Reproduce
1. Add -D=${PIOPLATFORM} to the build flags (and -v to for verbose)
2. Build project and look at output

### Actual Results
Looking at the compiler flags, we can see $PIOPLATFORM expands to: **'-D' '=linux_x86_64'**
``` 
COLLECT_GCC_OPTIONS='-o' '.pio/build/linux_x86_64/src/Script.o' '-c' '-v' '-D' 'PLATFORMIO=50204' '-D' '=linux_x86_64' '-I' 'include' '-I' 'src' '-I' 'lib/protocol' '-I' 'lib/modules' '-I' 'lib/utils' '-mtune=generic' '-march=x86-64'
 as -v -I include -I src -I lib/protocol -I lib/modules -I lib/utils --64 -o .pio/build/linux_x86_64/src/Script.o /tmp/ccROOl90.s
```

### Expected Results
In this case I'd expect no equals-sign so: '-D' 'linux_x86_64'

**Comment by ivankravets** [comment]
> -D=${PIOPLATFORM}

Just remove `=`.
