### ISSUE TITLE
Is it really necessary to pin zero_conf so hard?

### ISSUE THREAD

**Issue by hmaarrfk** [platformio/platformio-core#4177]
https://github.com/platformio/platformio-core/blob/c9b3dedbb05b242666db23548487c199e1d6d0b2/setup.py#L43

The zero_conf pinnign makes it kinda hard to repackage this in the larger python ecosystem. Could we use `>=` instead?

**Comment by ivankravets** [comment]
Thanks, fixed! This dependency is not very important for PlatformIO.

**Comment by hmaarrfk** [comment]
Thank you for the quick response
