### ISSUE TITLE
'pio platform install' hangs

### ISSUE THREAD

**Issue by Spongman** [platformio/platformio-core#4197]
- [x] **PlatformIO Core**.

**Operating system**: MacOS 11.3

**PlatformIO Version** PlatformIO Core, version 5.2.5

### Description of problem
```
% pio platform install raspberrypi
Platform Manager: Installing raspberrypi
Unpacking  [####################################]  100%
Platform Manager: raspberrypi @ 1.5.0 has been installed!
```

that's it. it doesn't complete.

**Comment by ivankravets** [comment]
It seems PIO checks global updates for platforms and libraries. This functionality was removed in the upcoming PlatformIO Core 5.3. Please upgrade via `pio upgrade --dev`.
