### ISSUE TITLE
Failed to Create hex file,please help me

### ISSUE THREAD

**Issue by TonyCWong** [platformio/platformio-core#4203]
Processing stc8h1k24 (platform: intel_mcs51; board: stc8h1k24)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/intel_mcs51/stc8h1k24.html
PLATFORM: Intel MCS-51 (8051) (1.2.3) > Generic STC8H1K24
HARDWARE: STC8H1K24 22MHz, 1.25KB RAM, 24KB Flash
PACKAGES:
 - tool-stcgal 1.104.0 (1.4)
 - toolchain-sdcc 1.30804.10766 (3.8.4)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
*** [.pio\build\stc8h1k24\firmware.hex] Implicit dependency `C:\Users\wwb_w\.platformio\platforms\intel_mcs51\builder\=' not found, needed by target `.pio\build\stc8h1k24\firmware.hex'.
====================================================================================== [FAILED] Took 0.73 seconds ======================================================================================

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
