### ISSUE TITLE
Escaping linker arguments with quotes impossible to do correctly

### ISSUE THREAD

**Issue by maxgerhardt** [platformio/platformio-core#4205]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Win10 x64

**PlatformIO Version** (`platformio --version`): 5.2.5

### Description of problem

See https://github.com/espressif/arduino-esp32/issues/6463 and [forum](https://community.platformio.org/t/working-with-esp-arduino-2-0-2/26540/6?u=maxgerhardt).

The Arduino-ESP32 PlatformIO builder script tries to generate a `.map` file via the [code](https://github.com/espressif/arduino-esp32/blob/0b10c8b79ef3edb88709f5da9e751578abdf2877/tools/platformio-build-esp32.py#L115) (simplified)

```py
env.Append(
   LINKFLAGS = [
    #... 
   '-Wl,-Map="%s"' % join("$BUILD_DIR", basename(env.subst("${PROJECT_DIR}.map")))
   ]
)
```

However, PlatformIO or SCons seem to not be able to evaluate this correcty. If the project is e.g. in the path `C:\Users\Max\temp\Test Project With Spaces`, the generated commandline is 

```
-Wl,-Map="C:\Users\Max\temp\Test Project With "Spaces\.pio\build\esp32dev\Test Project With Spaces.map""
```

which as an extremely weird `"` at the last space in the project path (`$BUILD_DIR` presumably). As a result, the linker command is messed up and errors out, leaving users with a space in their username or project path unable to build Arduino-ESP32 2.0.2 firmwares.

How can the builder script be written so that the argument of the form `-Wl,-Map="%s"` is not further messed with by SCons or PlatformIO? The path escaping is already done here after all.

P.S.: Using `-Wl,-Map` followed by just the path does not seem to work, GCC seems to need it as one flag.

#### Steps to Reproduce

1. Create a new folder with a space in it
2. Execute `pio init -b esp32dev` in it
3. Overwrite the `platformio.ini` with the one shown below
4. Use the minimal C++ code shown below
5. Attempt compilation

### Actual Results

Linking failure due to weird double quoting.

```
Linking .pio\build\esp32dev\firmware.elf
xtensa-esp32-elf-g++: error: Project: No such file or directory
xtensa-esp32-elf-g++: error: With: No such file or directory
xtensa-esp32-elf-g++: error: Spaces.map: No such file or directory
*** [.pio\build\esp32dev\firmware.elf] Error 1
================[FAILED] Took 102.29 seconds ================
```

### Expected Results

Succcessful compilation since the builder script correctly escapes paths with a potential space in it with quotes.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:arduino-esp32]
platform = https://github.com/Jason2866/platform-espressif32.git
board = esp32dev
framework = arduino
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32#master
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
void setup() {}
void loop(){}
```

**Comment by ivankravets** [comment]
> '-Wl,-Map="%s"' % join("$BUILD_DIR", basename(env.subst("${PROJECT_DIR}.map")))

Could you remove `basename()`?

**Comment by maxgerhardt** [comment]
Then the project path would be there twice due to `BUILD_DIR` with `PROJECT_DIR` I think

**Comment by ivankravets** [comment]
Sorry, that disturb you. Could you try 
```
import os


'-Wl,-Map="%s"' % join("$BUILD_DIR", os.path.abspath(env.subst("${PROJECT_DIR}.map")))
```

**Comment by maxgerhardt** [comment]
Sadly no luck, this produces

```
-u __cxa_guard_dummy "-Wl,-Map="/home/max/temp/Test Project With Space.map"" 
```

Aka the entire command is quoted, which GCC still doesn't like

```
xtensa-esp32-elf-g++: error: Project: No such file or directory
xtensa-esp32-elf-g++: error: With: No such file or directory
xtensa-esp32-elf-g++: error: Space.map: No such file or directory
*** [.pio/build/arduino-esp32/firmware.elf] Error 1
```

**Comment by ivankravets** [comment]
The last attempt...

```
'-Wl,-Map=\"%s\"' % join("$BUILD_DIR", os.path.abspath(env.subst("${PROJECT_DIR}.map")))
```

**Comment by maxgerhardt** [comment]
Produces the same 

```
-u __cxa_guard_dummy "-Wl,-Map="/home/max/temp/Test Project With Space.map""
```

with the same error.

I think some auto-escape logic in SCons is messing with it here.

**Comment by ivankravets** [comment]
Yes, I'll dig into the SCons. I hoped we can find a quick workaround. Currently, I'm busy with https://github.com/platformio/platformio-core/issues/3373
Finally, found a time for this. The war changed plans. I'll ask later our community to test it. The goal is to deprecate `pio lib` and `pio platform` commands. See https://docs.platformio.org/en/latest/core/history.html

**Comment by ivankravets** [comment]
> I think some auto-escape logic in SCons is messing with it here.

It was my typo, need to double escape `\`. 

```
'-Wl,-Map=\\"%s\\"' % join("$BUILD_DIR", os.path.abspath(env.subst("${PROJECT_DIR}.map")))
```

**Comment by maxgerhardt** [comment]
Hm it's just missing the `.pio/build/<environment name>/` there, the rest actually looks good..

**Comment by maxgerhardt** [comment]
I have tried with
```py
        '-Wl,-Map=\\"%s\\"' % join("$BUILD_DIR", basename(env.subst("$PROJECT_DIR") + ".map"))

```
and that produces the weird
```
Wl,-Map=\"/home/max/temp/Test Project With "Space/.pio/build/arduino-esp32/Test Project With Space.map\""
```
space in the middle pf the path again. If it weren't for that the path would be correct..

**Comment by ivankravets** [comment]
Does it make sense to escape spaces directly?
```

'-Wl,-Map=%s' % join("$BUILD_DIR", os.path.abspath(env.subst("${PROJECT_DIR}.map")).replace(" ", "\\ "))
```

**Comment by maxgerhardt** [comment]
The Arduino people want it in `<project folder>/.pio/build/<environment name>/<project folder name>.map`, I'll quickly adapt.

**Comment by maxgerhardt** [comment]
No, the moment I try to get the project folder's bare name with `basename(env.subst("${PROJECT_DIR}.map"))` to generate the correct name for the `.map` file, the mysterious `"`" gets inserter again :(.

**Comment by ivankravets** [comment]
Ahh, I see where the problem is, we do not operate with a full path. Where did you get this example?
```
'-Wl,-Map="%s"' % join("$BUILD_DIR", basename(env.subst("${PROJECT_DIR}.map")))
```

So, we should pass the resolved full path to the SCons before it starts parsing.

```python
'-Wl,-Map="%s"' % os.path.abspath(env.subst(join("$BUILD_DIR", "${PROJECT_DIR}.map"))))
```

Sorry, I didn't test this code, maybe there is a missing `)`. The goal is to receive resolved path and pass it directly to the scons. SCons processes strings only when sees `$` pattern.

**Comment by ivankravets** [comment]
Maybe, we even don't need `os.path.abspath(`, just to resolve path with `env.subst` before SCons.

**Comment by maxgerhardt** [comment]
>'-Wl,-Map="%s"' % join("$BUILD_DIR", basename(env.subst("${PROJECT_DIR}.map")))

That results in ` -Wl,-Map="/home/max/temp/Test Project With "Space/.pio/build/arduino-esp32/Test Project With Space.map""` which fails

>'-Wl,-Map="%s"' % os.path.abspath(env.subst(join("$BUILD_DIR", "${PROJECT_DIR}.map"))))

That results in 
```
"-Wl,-Map="/home/max/temp/Test Project With Space/.pio/build/arduino-esp32/home/max/temp/Test Project With Space.map""
```
which fails and has the project path twice in it 

>Maybe, we even don't need os.path.abspath

With `'-Wl,-Map="%s"' % env.subst(join("$BUILD_DIR", "${PROJECT_DIR}.map"))` we get 

```
"-Wl,-Map="/home/max/temp/Test Project With Space/.pio/build/arduino-esp32//home/max/temp/Test Project With Space.map""
```
which has the project path twice in it

**Comment by ivankravets** [comment]
Let's back quickly to the root of the problem https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build-esp32.py#L115

Why do we need `-Wl,-Map` here? This is debugging information and is not required for the generic build process. Another solution is to replace that line with 
```
'-Wl,-Map="%s"' % join("$BUILD_DIR", "output.map"))
```

**Comment by maxgerhardt** [comment]
Try, with the last `)` removed this works too

```
-Wl,-Map="/home/max/temp/Test Project With Space/.pio/build/arduino-esp32/output.map"
```
And funnility this time there's no quoting the entire argument.

The fix I wanted to produce for the Arduino-ESP32 people would be that their wanted file is generated at the same originally intended place as before. If `output.map` is fine for them too, okay. But it's still weird that it won't work the way originally intended with the project name as the filepath and `basename`.

**Comment by ivankravets** [comment]
Is this a blocker issue? Should we fix this line https://github.com/espressif/arduino-esp32/blob/master/tools/platformio-build-esp32.py#L115 ASAP?

**Comment by maxgerhardt** [comment]
Only people wanting to use Arduino-ESP32 2.0.x with Tasmota's version of platform-espressif32 that uses this new of a Arduino-ESP32 at all are affected. (`platform = https://github.com/Jason2866/platform-espressif32.git`, `platform_packages = framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git`), people using the regular `platform = espressif32` are unaffacted since it's using the older 1.0.6 core anways. (which apparently there wasn't a problem? ..) 

However, on the forum and in https://github.com/platformio/platform-espressif32/issues/619 I see more and more demand for Arduino-ESP32 2.0.2 version, so people running into this bug will increase I think. Better fix this cleanly now than later. For the meantime, the hotfix I posted in https://community.platformio.org/t/working-with-esp-arduino-2-0-2/26540/11?u=maxgerhardt should suffice.

**Comment by ivankravets** [comment]
Thanks for the clarification! I propose to comment on that line or replace it with `output.map`.

P.S: We have progress in negotiations with the Espressif company. There will be official support for Arduino-ESP32 2.0 and new ESP MCUs.

**Comment by mcspr** [comment]
Re. the original issue... This should work?
https://github.com/xoseperez/espurna/blob/791576458f8c039b6ef4a583f7887f1c2f52a8ae/code/scripts/pio_main.py#L31-L32
```python
env.ProcessFlags('-Wl,-Map -Wl,\\"${BUILD_DIR}/${PROGNAME}.map\\"')
```
(or just the env.ParseFlags(). with the goal of allowing SCons to expand things when they are needed)

**Comment by maxgerhardt** [comment]
Closing as https://github.com/espressif/arduino-esp32/pull/6464 was merged. Weird quotes if `basename()` is used still seems unsolved, but not needed anymore.
