### ISSUE TITLE
Add support for SMC (.sm-files) to PlatformIO

### ISSUE THREAD

**Issue by jkoeter** [platformio/platformio-core#4209]
For using statemachines inside (embedded) software I have been creating statemachines defined in a .sm files. These files are processed by a java tool to generate .h and .cpp files [SMC](http://smc.sourceforge.net/).

I would love to see support for the generation of the .h and .cpp files from .sm files in PlatformIO. I am used to writing makefiles which have contents like:
```
SM_FILES = $(shell find $(SRC_DIR) -name "*.sm")
SM_TRANSPILED_FILES = $(SM_FILES:.sm=_sm.cpp) $(SM_FILES:.sm=_sm.h)

compile: statemachines
	make

statemachines: $(SM_TRANSPILED_FILES)

statemachines-clean:
	rm -rf $(SM_TRANSPILED_FILES)

%_sm.h %_sm.cpp : %.sm
	smc -c++  -nostreams -nocatch -noex -stack 100 -cast static_cast $<
```
Is there any place in PlatformIO where I can create/add such a thing? I am willing to help but then will need some pointers.

**Comment by ivankravets** [comment]
Please check [PlatformIO Advanced Scripting](https://docs.platformio.org/en/latest/scripting/index.html), especially Pre/Post Actions => https://docs.platformio.org/en/latest/scripting/actions.html

If you have any questions, please forward them to https://community.platformio.org/ , our awesome community will be glad to help you.
