### ISSUE TITLE
platform_packages not installing when using git reference

### ISSUE THREAD

**Issue by sinedied** [platformio/platformio-core#4215]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: MacOS

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 5.2.5

### Description of problem

When trying to install platform package from git, nothing happens and it get stuck indefinitely. If I comment the package trying to be fetched from git, it works just fine.

This is the problematic part:
```
platform_packages =
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#cbcba53
```

#### Steps to Reproduce

1. Create new PIO project
2. Replace platformio.ini with this
```
[env:s2]
platform = espressif32
platform_packages =
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#cbcba53
	platformio/tool-esptoolpy @ ~1.30100
	toolchain-xtensa32s2
framework = arduino
board = esp32dev
```
3. Run `pio run`

### Actual Results
It get stuck processing:
```
CyanideBook:s2test noda$ pio run
Processing s2 (platform: espressif32; framework: arduino; board: esp32dev)
------------------------------------------------------------------------------------------------

```
(nothing more happens)

### Expected Results

platform_package gets fetched and my project builds.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:s2]
platform = espressif32
platform_packages =
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#cbcba53
	platformio/tool-esptoolpy @ ~1.30100
	toolchain-xtensa32s2
framework = arduino
board = esp32dev
```

**Source file to reproduce issue:**
```cpp
void setup(){
  // Open serial communications and wait for port to open:
  Serial.begin(9600);
  while (!Serial);
  Serial.println("Hello Arduino!");
}

void loop {
}
```

### Additional info
Thanks for you help.

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
