### ISSUE TITLE
how to solve it in China?

### ISSUE THREAD

**Issue by zsm666** [platformio/platformio-core#4216]
![image](https://user-images.githubusercontent.com/44770623/162165859-ac8b47dc-e5ac-49aa-8e70-b37a090b4d75.png)

long ago,the get-plantformio.py was wrong,but i get PIO by anyway.
now,the plantformio_init is wrong now.i can't solve it.so sad...please help

**Comment by ivankravets** [comment]
Thanks for contacting us! Do you mean that https://api.registry.platformio.org is blocked in China?

**Comment by zsm666** [comment]
> 

yes,i think maybe.

**Comment by zsm666** [comment]
> Thanks for contacting us! Do you mean that https://api.registry.platformio.org is blocked in China?
yes,i think maybe.

**Comment by zsm666** [comment]
> Thanks for contacting us! Do you mean that https://api.registry.platformio.org is blocked in China?

yes,i think maybe.

**Comment by zsm666** [comment]
do you know how to manual download?

**Comment by zsm666** [comment]
or do you have any mirror in China?

**Comment by zsm666** [comment]
if my word rude,please forgive me.

**Comment by zsm666** [comment]
i'm f**king solved it.I use my mobile phone to open the VPN and hotspot, and then use the computer to connect my phone.

**Comment by ivankravets** [comment]
Could you try to download this file - what is your speed?

https://dl.registry.platformio.org/download/platformio/tool/toolchain-xtensa32/2.50200.97/toolchain-xtensa32-windows-2.50200.97.tar.gz

**Comment by zsm666** [comment]
> Could you try to download this file - what is your speed?
> 
> https://dl.registry.platformio.org/download/platformio/tool/toolchain-xtensa32/2.50200.97/toolchain-xtensa32-windows-2.50200.97.tar.gz

![image](https://user-images.githubusercontent.com/44770623/162189084-af56c3f6-2110-42ab-b896-29468824aa5d.png)
without VPN

and
![image](https://user-images.githubusercontent.com/44770623/162189246-1eb0cdd2-df6c-420e-b12b-7c5c4614fc94.png)
with VPN

emmm..what about this?

**Comment by ivankravets** [comment]
@Gianthard-cyh is PlatformIO blocked in China? Do you have access to our registry?

**Comment by zsm666** [comment]
![image](https://user-images.githubusercontent.com/44770623/162190016-bf767599-ac1f-4539-8df3-cbef4cb17da0.png)
it's ok now.i using chinese to tell other people in China how to solve it.

用手机开VPN和热点,然后拿电脑连接手机热点即可.

**Comment by ivankravets** [comment]
Thanks for the solution. Please do not hesitate to contact us if still have problems with our registry.

Happy coding with PlatformIO!

**Comment by zsm666** [comment]
> Thanks for the solution. Please do not hesitate to contact us if still have problems with our registry.
> 
> Happy coding with PlatformIO!

Thanks for your previous help!! :)

**Comment by dennisdebel** [comment]
What VPN can be forwarded through a phone's Hot Spot?
