### ISSUE TITLE
Path for extra script inside a library

### ISSUE THREAD

**Issue by FernandoGarcia** [platformio/platformio-core#4220]
Hi!

I was asking on [forum](https://community.platformio.org/t/path-for-extra-script-inside-a-library) about the right path to execute a script inside a library.

At first time I was using:

```
extra_scripts = 
 pre:.pio\libdeps\esp32dev\esp8266-react\scripts\build_interface.py
```

But changing the `ENV` brakes the path. So Max suggested me to use `$PROJECT_LIBDEPS_DIR\$PIOENV\esp8266-react\scripts\build_interface.py` but while PIO is showing the right path on terminal it gives an error of wrong path.

![89faa98a0192d1e2d40c38a62b5cceb95625121d](https://user-images.githubusercontent.com/2778501/162592676-998661a1-6d86-49d3-864f-0c698d2d8c1a.png)

Then Max [asked](https://community.platformio.org/t/path-for-extra-script-inside-a-library/26964/10?u=fernando) me to open this issue.

 Best regards.

**Comment by ivankravets** [comment]
Could you provide a simple project to reproduce this issue?

**Comment by FernandoGarcia** [comment]
Hi!

Try this:

```cpp
#include <Arduino.h>
void setup(){}
void loop(){}
```

```ini
[env:esp32dev]
platform = espressif32
framework = arduino
board = esp32dev
monitor_speed = 115200
lib_deps = 
	maakbaas/ESP8266 IoT Framework
extra_scripts = 
	pre:$PROJECT_LIBDEPS_DIR\$PIOENV/ESP8266 IoT Framework/scripts/preBuild.py
```

Best regards.

**Comment by ivankravets** [comment]
Thanks for the report! Fixed in the latest dev-version. Please re-test with `pio upgrade --dev`.

**Comment by FernandoGarcia** [comment]
Yes, it's working now.
Thank you!
