### ISSUE TITLE
Using Arduino framework with esp32 platform problem with FILE typedef

### ISSUE THREAD

**Issue by Daven005** [platformio/platformio-core#4223]
I have imported an arduino project into PlatformIO that successfully compiled under Arduino. I cannot successfully compile it under PlatformIO because there are two incompatible typedefs for FILE; 
1) typedef __FILE FILE;  (In C:/Users/User/.platformio/packages/framework-arduinoespressif32/tools/sdk/include/newlib/wchar.h:52:16)

2) typedef struct __file FILE; (In C:/Users/User/Documents/Arduino/libraries/stdio/src/stdio.h:275:23)

How can I disentangle the relevant libraries.

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
