### ISSUE TITLE
ImportError for PY2 in PlatformIO (and VSCode) when using serial monitor

### ISSUE THREAD

**Issue by jasongaunt** [platformio/platformio-core#4226]
Hi folks,

I'm raising this issue primarily for myself, but as I understand it, others are having the same issue [over here](https://community.platformio.org/t/platformio-serial-monitor-not-working/20143/5) on the PlatformIO forums.

### Problem

Something recently updated within PlatformIO / VSCode and now we are getting the following error when trying to use the serial monitor...

```python
ImportError: cannot import name 'PY2' from 'platformio.compat'
```

This error is coming from `filter_exception_decoder.py` (irrespective of whether the `esp32_exception_decoder` monitor filter is active) and is affecting myself (using VSCode on Windows 10) and at least one other Windows user and Mac OS user.

### Temporary workaround

This is a dirty workaround to get the monitor working again. I stress that **this should not be the solution** and it is _temporary_;

1. Open up `filter_exception_decoder.py` in your favourite text editor
2. Around line 20 change the following line and comment out `, PY2` at the end of the line:
```python
from platformio.compat import path_to_unicode, WINDOWS, PY2
```

3. Around lines 114-115 comment out the following lines:
```python
        if PY2:
            args = [a.encode(enc) for a in args]
```

4. Around lines 118-119 comment out the following lines:
```python
                if PY2:
                    addr = addr.encode(enc)
```

5. Save the file

This file is _typically_ located in your HOME folder under the following locations;

- `~/.platformio/platforms/espressif32/monitor/filter_exception_decoder.py` on Linux / Mac OS
- `%HOMEPATH%\.platformio\platforms\espressif32\monitor\filter_exception_decoder.py` on Windows

**Comment by ivankravets** [comment]
Sorry for the issue. Please re-run `pio upgrade --dev`. Does it work now?
