### ISSUE TITLE
Platformio crashes with circular transitive dependencies

### ISSUE THREAD

**Issue by lmgeorge** [platformio/platformio-core#4228]
What kind of issue is this?
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu 20.04.4 LTS and Windows 11

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 6.0.0a1

### Description of problem
Any attempt to install a direct dependency that has circular dependencies causes a `RecursionError: maximum recursion depth exceeded`.

This is particularly acute when using `pio run` because there is no way to circumvent the installation of transitive dependencies using the `--skip-dependencies` flag that is present on the `install` command.  The `run` command attempts to process the project environment and install all project dependencies prior to running a target, but doesn't pass along any of the options provided by the project configuration or command line arguments to the function `platformio.package.commands.install.install_project_env_dependencies`.

`platformio/commands/run/processor.py:68`
```py
class EnvironmentProcessor(object):
 # ...
    def process(self):
    # ...
            install_project_env_dependencies(
                self.name,
                {"project_targets": build_targets},
            )

```

There is no way to circumvent this behavior using a pre-build script either, as the environment processing step happens prior to its execution.

#### Steps to Reproduce

1. Create a simple project
2. Declare a dependency that has circular dependencies in `lib_deps`
3. Execute `pio run` 

OR 

1. Use `pio pkg install --library <library_name>` to replicate 

### Actual Results
 LibraryPackageManager attempts to keep walking the dependency graph and installing dependencies until a `RecursionError` is thrown.

### Expected Results
*PackageManager stops walking the dependency graph if the spec has already been seen.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:release]
platform = ststm32
board = portenta_h7_m7
framework = arduino
lib_deps = khoih-prog/NTPClient_Generic@^3.7.2
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

void setup() {
    Serial.println("setup called");
}
void loop()
{
}
```

### Additional info

Attempted workarounds:
1. Using a pre script to prune the dependency list
2. Setting `lib_ldf_mode`  to `off` and `deep+`
3. Putting all transitive dependencies in the `lib_ignore` setting

Only thing that worked for me (without rewriting a bunch of logic in platformio.package.manager._install.py) was adding `skip_dependencies = yes` to my platformio.ini and patching platformio directly as so:
`platformio/commands/run/processor.py:68`
```py
class EnvironmentProcessor(object):
 # ...
    def process(self):
    # ...
            install_project_env_dependencies(
                self.name,
                dict(**self.options, project_targets=build_targets)
            )

```

**Comment by ivankravets** [comment]
Thanks for the report!

Please re-test with the next

```
pio upgrade --dev
pio system prune --cache
```
