### ISSUE TITLE
Platformio.org domain is not accessible from Moldova

### ISSUE THREAD

**Issue by vladkozlov69** [platformio/platformio-core#4232]
Hi guys,

today platformio.org domain became inaccessible from Moldova (e.g. IP 89.149.84.67 of Orange ISP provider). Via VPN through Romania it works fine. Could you please check whether this ISP's IP range was accidentally banned?

**Comment by maxgerhardt** [comment]
Could the reverse be true? Your ISP blocking PlatformIO because it e.g. thinks its russian? We had a similiar situation [here](https://community.platformio.org/t/platformio-is-a-ukrainian-project-please-help-us-stop-the-war/26330/47?u=maxgerhardt).

**Comment by ivankravets** [comment]
We don't have any tracks to Russia. The load balancer is located in the German data center. @vladkozlov69 which IP do you see when 

```
ping platformio.org
```?

Could you try `1.1.1.1` DNS?

**Comment by vladkozlov69** [comment]
Thanks a lot @ivankravets ! I just changed my DNS to 1.1.1.1 and it works now. Resolves 88.198.170.159 and VS Code plugin works fine. Then I'm going to close this issue and will ask my ISP support about wrong blocking.

**Comment by ivankravets** [comment]
We would be thankful if you provide us with the reason why they blocked PlatformIO :(

Happy coding with PlatformIO!
