### ISSUE TITLE
Allow to inject or modify SCons command line

### ISSUE THREAD

**Issue by mcspr** [platformio/platformio-core#4236]
What kind of issue is this?

- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------

While debugging extra scripts, it may be fairly difficult to trace the dependency tree or the custom targets just by re-running the script over and over to test some theories. Or, to know the exact internal decision making happening in SCons, related to built and not built targets. To help with that, there are a couple of command line flags that could be used
- [`--tree=...`](https://scons.org/doc/production/HTML/scons-man.html#opt-tree) to see the file dependency tree. for example, `all` will show everything, including implicit and ignored dependencies.
- [`--debug=explain`](https://scons.org/doc/production/HTML/scons-man.html#opt-debug) will notify about changed, alwaysbuild() targets, or not built ones 

Right now, the only way to add them is to manually change this module's code
https://github.com/platformio/platformio-core/blob/ee43b86742b253217fef794c575d17f5544d9012/platformio/platform/_run.py#L82-L91

Perhaps there should be a way to add or modify scons flags via .ini or environment variable?
Or, at least these two?

**Comment by ivankravets** [comment]
You need `SCONSFLAGS` environment variable, see https://scons.org/doc/production/HTML/scons-user/ch10.html#sect-command-line-options
