### ISSUE TITLE
Add support for doctest

### ISSUE THREAD

**Issue by jcw** [platformio/platformio-core#4240]
- [x] **Feature Request**.

The "doctest" unit test framework is a variant of "Catch2", but much simpler (and faster). I've been using this on native builds for some time now. For an example, tied into PIO for native, but still using Unity for embedded tests, see https://git.jeelabs.org/monty/tree/test?h=v1.6

See also https://github.com/doctest/doctest/issues/506 which tries to run Doctest on embedded.

The key benefit, as with Catch2, is the amount of info you can see when tests fail, i.e. a test such as  `CHECK(abc == 42);` then the _actual_ value of abc will also be reported. Better still, you can capture other expressions tp print out, only on failure. This is such a game-changer that I've been going out of my way to test as much as possible on native (always a good strategy, of course).

If nothing else, I would be nice to support mixed doctest/unity testing, but supporting doctest on embedded would be even more powerful.

(This feature request was previously mentioned at https://github.com/platformio/platformio-core/issues/2185#issuecomment-1106593399)

**Comment by Di3mex** [comment]
@ivankravets Is it possible to use the VS Code GUI to run the tests? For example via the TestMate extension?

**Comment by ivankravets** [comment]
Which features from that extension are the most important for you? You can use that extension for "native executables" but not for the embedded.

**Comment by Di3mex** [comment]
![image](https://user-images.githubusercontent.com/966375/167486473-3c7578a9-72be-4ebc-9147-2e2f9b794882.png)
Right now I cannot use the Test Explorer from Vs Code. I would like to be able to use the GUI. It doesn't have to be via the TestMate extension. It just seemed like it would/should work through the Extension. 

I also really would like to be able to simply press the debug unit tests feature from withing the GUI.

From previous experience with integrated unit testing framework in IntelliJ / AndroidStudio I really miss the integrated GUI overview tables that would show you the list of the tests, allow you to run individual (failing) tests, debug a specific test. 

Overall the unit testing experience is quite slow and cumbersome on PIO in VsCode, so I am really excited to see some advancements in a more modern unit testing direction! Thanks for the support and work on that!
