### ISSUE TITLE
Option to run specific Unity test function

### ISSUE THREAD

**Issue by nbolton** [platformio/platformio-core#4248]
Related: https://github.com/ThrowTheSwitch/Unity/issues/611

Within my project, I have many test functions. When one fails, finding out which one is tedious. Unity has command line support (when `UNITY_USE_COMMAND_LINE_ARGS` is defined) through it's `-n` or `-f` arg, but I couldn't see how to pass args to Unity via pio. The `test_filter` option in the `.ini` isn't useful in this situation, because it filters on test library, not test function.

Idea: Provide a way of filtering by Unity test function, or maybe have a way of passing args to Unity.

**Comment by ivankravets** [comment]
Will https://github.com/platformio/platformio-core/issues/3132 help you to solve this issue?

**Comment by nbolton** [comment]
Yes thanks, I'll close and add to that issue.
