### ISSUE TITLE
PIO test filters not working

### ISSUE THREAD

**Issue by ali80** [platformio/platformio-core#4274]
**Operating system**:
macos 12.1

**PlatformIO Version**:
tested on both `6.0.1` & `6.0.2a1`

### Description of problem
first mentioned here [PIO test filters not working?](https://community.platformio.org/t/pio-test-filters-not-working/27792/2)
Hi, I’ve used filters for unit testing on version 5x without problem,
now I’m testing same project on version 6.0.1 but seems filters are broken?
also created new project and got the same results.
sample command:
`pio test -e native -f aaa`
should only run aaa file but it seems that the filter is ignored all together.
the output is like this;
```bash
ali@Air ~/d/n/esp32> pio test -e native --filter aaa                                             master-!?
Verbose mode can be enabled via `-v, --verbose` option
Collected 1 tests

Processing * in native environment
.
.
.
```

**The content of `platformio.ini`:**
```ini
[env:native]
platform = native
build_type = debug
build_flags = -std=gnu++11
lib_compat_mode = off
lib_archive = no
```

**Comment by ivankravets** [comment]
> Processing * in native environment

There is no "aaa" test. Please read updated docs https://docs.platformio.org/en/latest/advanced/unit-testing/structure.html

A test folder must start with `test_` prefix. Otherwise, PlatformIO treats this folder and a group of tests.
