### ISSUE TITLE
Jumper T Pro TX Build Error

### ISSUE THREAD

**Issue by GutoFleury** [platformio/platformio-core#4280]
I tried to build firmware for Jumper T Pro with internal ERLS using configurator V1.4.1 and was not successful.
The error message generated by the configurator was:

Build error
An error has occured, see the above log for the exact error message. If you have not already done so, visit [Expresslrs.org](https://www.expresslrs.org/2.0/) and read the [Flashing Guide](https://www.expresslrs.org/2.0/quick-start/getting-started/) for your particular device as well as the [Troubleshooting Guide](https://www.expresslrs.org/2.0/quick-start/troubleshooting/#flashingupdating). If you are still having issues after reviewing the documentation, please copy the build logs above to an online paste site and post in the #help-and-support channel on the [ExpressLRS Discord](https://discord.gg/dS6ReFY) with a link to the logs and other relevant information like your device, which flashing method you were using, and what steps you have already taken to resolve the issue.

The message below appeared along with the messages generated in the Build process:

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gutof\\.platformio\\.cache\\http\\db.data'

What could have happened?

Thanks

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
