### ISSUE TITLE
Compiling error Express LRS Configurator

### ISSUE THREAD

**Issue by GutoFleury** [platformio/platformio-core#4281]
I had the following error when compiling an update for my Jumper T Pro radio:

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\gutof\\.platformio\\.cache\\http\\db.data'

Can someone help me?

**Comment by ivankravets** [comment]
Please remove `C:\Users\gutof\.platformio\.cache` folder and restart VSCode.
