### ISSUE TITLE
Add board :- ESP-12F 

### ISSUE THREAD

**Issue by ben700** [platformio/platformio-core#4283]
My board is actually a ESP-12F but I select ESP-12E as ESP-12F isn't listed as a known board in platformio 

Many Thanks

Ben

**Comment by maxgerhardt** [comment]
Issues that refer to this: https://github.com/platformio/platform-espressif8266/issues/195, https://github.com/platformio/platform-espressif8266/issues/274

**Comment by ivankravets** [comment]
Thanks, @maxgerhardt, for the solution.

**Comment by ben700** [comment]
How is this request the same as those issues?

**Comment by ben700** [comment]
> Thanks, @maxgerhardt, for the solution.

Is that because the codebase isn't being maintained or because ESP-12F is so similar to esp12e?  

Ben

**Comment by needfulthing** [comment]
The only difference between 12E and 12F seems to be an improved antenna design. See https://components101.com/article/major-differences-between-esp12e-and-esp12f
