### ISSUE TITLE
Add support for Nuvoton NUC130LC1CN

### ISSUE THREAD

**Issue by gspmkjh** [platformio/platformio-core#4306]
What kind of issue is this?

Development Platform or Board.
Feature Request.

I am interested in adding support for the NUC130LC1CN microcontroller. I would be happy to help, but I'm not sure where to start.

Here are the [product page](https://www.nuvoton.com/products/microcontrollers/arm-cortex-m0-mcus/nuc130-230-automotive-series/nuc130lc1cn/) and the [datasheet](https://www.nuvoton.com/export/resource-files/DA00-NUC130EN1.pdf).

**Comment by maxgerhardt** [comment]
* With what framework code do you want to use that board?
* How do you upload to the board? (OpenOCD with special config files? What SWD/JTAG/etc. adapter?)

**Comment by ivankravets** [comment]
Please vote 👍  for this feature request https://github.com/platformio/platformio-core/issues/2453
