### ISSUE TITLE
Telemetry can not be disabled via "pio settings set enable_telemetry No"

### ISSUE THREAD

**Issue by CodeBreakerOO7** [platformio/platformio-core#4324]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

MacOS 10.15.7 (19H1715) (Catalina)
**PlatformIO Version** (`platformio --version`):
Core 6.0.2 - Home 3.4.2 Visual Studio Code Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 19.6.0
### Description of problem
Entering in terminal the command
xxx% pio settings set enable_telemetry No
The new value for the setting has been set!
Name              Current value [Default]    Description
----------------  -------------------------  ---------------------------------------------------------
enable_telemetry  No [Yes]                   Telemetry service <https://bit.ly/pio-telemetry> (Yes/No)

results in an still(?) enabled telemetry (at least as feedback on the screen

#### Steps to Reproduce
see above

### Actual Results
see above

### Expected Results
Name              Current value [Default]    Description
----------------  -------------------------  ---------------------------------------------------------
enable_telemetry  [No] Yes                   Telemetry service <https://bit.ly/pio-telemetry> (Yes/No)

### Additional info
Thanks for looking into this issue, a setting in PIO Home would be nice

**Comment by ivankravets** [comment]
> Current value [Default]

See description. You disabled telemetry. The `[Yes]` means default value.
