### ISSUE TITLE
it is possible to specify upload-port from the CLI, but not monitor-port (feature request)

### ISSUE THREAD

**Issue by hamishcunningham** [platformio/platformio-core#4337]
If working with multiple boards connected at one time (e.g. when developing a test rig), there are multiple upload ports and multiple corresponding monitor ports. At present it seems impossible to specify the latter.

For example
`pio run -e unphone7 --upload-port /dev/ttyUSB1 -t upload -t monitor`
will correctly upload to ttyUSB1, but will then monitor on e.g. ttyUSB0

Adding a monitor_port to the .ini file can solve this, but then doesn't cope with subsequent changes.

Addition of a --monitor-port option would solve this, as would defaulting monitor-port to upload-port instead of trying to guess it when the latter is present. An alternative would be to allow overriding of .ini settings from the command line.

Thanks!

**Comment by ivankravets** [comment]
Do you type this command manually?

**Comment by hamishcunningham** [comment]
Brilliant, works perfectly :)
Thanks!

**Comment by ivankravets** [comment]
Happy coding with PlatformIO! 🚀
