### ISSUE TITLE
"ValueError: Invalid simple block" on Clean All

### ISSUE THREAD

**Issue by banoz** [platformio/platformio-core#4344]
Getting the following error `ValueError: Invalid simple block '#24db08e'` while trying to do Clean All after accidental entering `lib_deps = lvgl/lvgl@#24db08e` in platformio.ini. 
The only way to get out of that was manual cleaning of `\.pio\libdeps\bluepill_f103c8\integrity.dat` file.

**Comment by ivankravets** [comment]
Thanks for the report! Please re-test with `pio upgrade --dev`.
