### ISSUE TITLE
Allow specifying environments to process using the ci (continuous integration) command

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#4347]
What kind of issue is this?
- [x] **Feature Request**.

------------------------------------------------------------------

### Configuration

**Operating system**:
 - Ubuntu latest
**PlatformIO Version** (`platformio --version`):
-6.1

When using the ci command to run continuous integration tests, it would be very nice if I could specify which environments to use in the test, exactly how it is possible with the  `run` command.

ie: `pio ci --project-conf my-config.ini --e uno -e zero my_source`

Currently, the ci command always processes all environments in the project configuration file.

**Comment by ivankravets** [comment]
Thanks for the feature request. Please re-test with `pio upgrade --dev`.
