### ISSUE TITLE
Minimum version of Python is 3.6 but `pio package publish` requires 3.7

### ISSUE THREAD

**Issue by nomis** [platformio/platformio-core#4352]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu 18.04 LTS

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.0.2

### Description of problem

The `HISTORY.rst` file claims that PlatformIO's minimum Python version is 3.6 but `pio package publish` requires 3.7 because it uses `str.isascii()`.

(Ideally the Python code should be automatically checked to determine if it can be run on older versions of Python.)

#### Steps to Reproduce

1. Run `pio package publish` with python 3.6

### Actual Results

```
...
  File "/home/simon/.local/lib/python3.6/site-packages/platformio/package/commands/publish.py", line 116, in package_publish_cmd
    check_archive_file_names(archive_path)
  File "/home/simon/.local/lib/python3.6/site-packages/platformio/package/commands/publish.py", line 152, in check_archive_file_names
    if not name.isascii():
AttributeError: 'str' object has no attribute 'isascii'
```

### Expected Results

Package is published

**Comment by ivankravets** [comment]
Thanks for the report! Please re-test with `pio upgrade --dev`.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/commit/4278574450f6e9b93a130590439b27fc96b54ea8
