### ISSUE TITLE
PlatformIO detect wrong system type on Windows

### ISSUE THREAD

**Issue by KawaiiZapic** [platformio/platformio-core#4353]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 Pro x64

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.1

### Description of problem
PlatformIO detect my system as `windows` instead of `windows_amd64`, and could not install package from repo.

#### Steps to Reproduce

1. Create a project with STC8H8K64U
2. platformio run --target upload

### Actual Results
```
Processing STC8H8K64U (platform: intel_mcs51; board: STC8H8K64U)
------------------------------------------------------------------------------------------------------------------------
Tool Manager: Installing platformio/toolchain-sdcc @ >=1.40100.0,<1.40201.0
Error: Could not find the package with 'platformio/toolchain-sdcc @ >=1.40100.0,<1.40201.0' requirements for your system 'windows'
```

### Expected Results
should detect my system as `windows_amd64` and install package successfully.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:STC8H8K64U]
platform = intel_mcs51
board = STC8H8K64U
```

**Source file to reproduce issue:**
No.

**Comment by ivankravets** [comment]
How is it possible? Please provide an output of `pio system info` command.

**Comment by KawaiiZapic** [comment]
> How is it possible? Please provide an output of `pio system info` command.

```
(penv) PS C:\Users\57735> pio system info
--------------------------  ------------------------------------------------------
PlatformIO Core             6.1.1
Python                      3.9.10-final.0
System Type                 windows
Platform                    Windows-10
File System Encoding        utf-8
Locale Encoding             cp936
PlatformIO Core Directory   C:\Users\*****\.platformio
PlatformIO Core Executable  C:\Users\*****\.platformio\penv\Scripts\platformio.exe
Python Executable           C:\Users\*****\.platformio\penv\Scripts\python.exe
Global Libraries            0
Development Platforms       2
Tools & Toolchains          8
--------------------------  ------------------------------------------------------
```

**Comment by KawaiiZapic** [comment]
```py
def get_systype():
    type_ = platform.system().lower()
    arch = platform.machine().lower()
    if type_ == "windows" and "x86" in arch:
        arch = "amd64" if "64" in arch else "x86"
    return "%s_%s" % (type_, arch) if arch else type_
```
[    return "%s_%s" % (type_, arch) if arch else type_](https://github.com/platformio/platformio-core/blob/4278574450f6e9b93a130590439b27fc96b54ea8/platformio/util.py#L146)
seem cannot get arch in here, maybe a python internal bug?

**Comment by KawaiiZapic** [comment]
> Is this a virtual machine? What is your CPU?

It's my notebook, Ryzen 5 5700U

**Comment by ivankravets** [comment]
Please type `python` and run the next:
```python
import platform
platform.architecture()
platform.machine()
```

Please provide output.

**Comment by KawaiiZapic** [comment]
```
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
''
>>> platform.system()
'Windows'
>>>
```

**Comment by ivankravets** [comment]
Yes, looks like a Python bug. Let me quickly make a fix on our side. Thanks for the report.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.

Does it work now?

**Comment by KawaiiZapic** [comment]
I noticed that we use `64` as keyword to determine the system is 64 bit or not.  
Now Arm device is being more and more popular, Windows also has officially support for arm64(or "aarch64") devices, I think is better to make a more strict check on system type.   
  
I do have a Windows arm device but I can't access to it now, so I can't give a help on this.  
Maybe we can mark this down and fix it up later.

**Comment by KawaiiZapic** [comment]
> Please re-test with `pio upgrade --dev`.
> 
> Does it work now?

```
(penv) PS C:\Users\57735> pio system info
--------------------------  ------------------------------------------------------
PlatformIO Core             6.1.2a2
Python                      3.9.10-final.0
System Type                 windows_amd64
Platform                    Windows-10
File System Encoding        utf-8
Locale Encoding             cp936
PlatformIO Core Directory   C:\Users\57735\.platformio
PlatformIO Core Executable  C:\Users\57735\.platformio\penv\Scripts\platformio.exe
Python Executable           C:\Users\57735\.platformio\penv\Scripts\python.exe
Global Libraries            0
Development Platforms       2
Tools & Toolchains          8
--------------------------  ------------------------------------------------------
```
work fine now

**Comment by sghillie** [comment]
WE are having the same issue, but in reverse. it is detecting as a windows_amd64, but I am running on intel

**Comment by KawaiiZapic** [comment]
> WE are having the same issue, but in reverse. it is detecting as a windows_amd64, but I am running on intel

It's actually correct. Most 64bit Intel processor should be determined as `amd64`.  
https://en.m.wikipedia.org/wiki/X86-64
