### ISSUE TITLE
COM ports inaccessible after building FW in release 6.1.1

### ISSUE THREAD

**Issue by singletone** [platformio/platformio-core#4357]
I work with Platform IO integrated into VS Code in Windows 11.
The release Core 6.1.1 (2022-07-11) contains the following item: "Fixed an issue when a serial port was not automatically detected if the board has predefined HWIDs"
As a result, the device containing the firmware built in this release and connected to a PC makes COM ports inaccessible. They cannot be opened and detected by the Device Manager. The same code built in previous versions (Cores) causes no problem.
I tried to downgrade to the previous Core of Platform IO, with no success. 
The command: 
pip install -U "platformio<6"
- didn't help.

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by singletone** [comment]
Thanks for your quick response. The board is Raytac MDBT50Q.
