### ISSUE TITLE
build_flags not working with space

### ISSUE THREAD

**Issue by KawaiiZapic** [platformio/platformio-core#4360]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 Pro x64

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.2a3

### Description of problem
`build_flags` not working with space.

#### Steps to Reproduce

1. add code in platformio.ini: 
```
build_flags=
	'-DMYSTRING="Text is \\"Quoted\\"'
```
2. Save.

### Actual Results
PlatformIO will not update the `c_cpp_properties.json`

### Expected Results
in `c_cpp_properties.json`:
```
"defines": [
                "MYSTRING=\"Text is \"Quoted\"",
 ]
```

**Comment by ivankravets** [comment]
Thanks for the report! Fixed! Please re-test with `pio upgrade --dev`.
