### ISSUE TITLE
LDF ignores dependencies from library.json unless owner field is present

### ISSUE THREAD

**Issue by jackjansen** [platformio/platformio-core#4376]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [*] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

macOS 12.4

PlatformIO Core, version 6.1.3

### Description of problem

LDF will ignore some library dependencies that are in the `dependencies` list, specifically entries that have no `owner` and no `version`. It may be this only happens if `lib_compat_mode=strict`, because I am only seeing this problem the last few days, since I enabled that option.

#### Steps to Reproduce

1. Create a library that depends on some other library, and corresponding example code. Specify the dependency only by name in `library.json`.
2. `PLATFORMIO_CI_SRC=examples/example pio ci -v --lib="." --project-option="lib_ldf_mode=deep+" --project-option="lib_compat_mode=strict" --board=nodemcuv2`

### Actual Results

Dependencies without `owner` are ignored, with a warning (if `-v` specified) like:

```
Warning: Ignored `Adafruit NeoPixel` dependency for `iotsa` library
```

### Expected Results

The expected results are that the library is included. This can be gotten by adding `"owner" : "adafruit"` to the dependency.

### If problems with PlatformIO Build System:

As the bug is also clear with `pio ci` I don't think a platformio.ini is needed.

**Comment by ivankravets** [comment]
Please provide a simple PlatformIO project to reproduce this issue

**Comment by ivankravets** [comment]
Please reopen if you still need help
