### ISSUE TITLE
About pio core override extensions.json enhancement

### ISSUE THREAD

**Issue by seishinkouki** [platformio/platformio-core#4383]
- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

Currently, pio will keep user custom [recommendations] section when overriding extensions.json, I think it will be helpful keep both custom [recommendations] and [unwanted Recommendations] sections.

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.

**Comment by seishinkouki** [comment]
> Please re-test with `pio upgrade --dev`.

it work as expected, thanks
