### ISSUE TITLE
BuildSources() not work from post : script.py

### ISSUE THREAD

**Issue by Wiz-IO** [platformio/platformio-core#4385]
I want to add and compile code from not compiled framework folder
but **BuildSources() not work from POST:SCRIPT.PY**

as example:
https://github.com/Wiz-IO/TEST/blob/main/PICO-LWIP-APP/extra_script.py

pre:scrypt.py
BuildSources() work
BuildLibrary() work

**post:scrypt.py**
BuildLibrary() work
**BuildSources() not work … Is it a BUG?** or I make any wrong...

**Comment by ivankravets** [comment]
Hi Georgi,

This is a feature, not a bug. The inline source files are handled at the [BuildProgram](https://github.com/platformio/platformio-core/blob/develop/platformio/builder/tools/piobuild.py#L59) step which you call in your platformio/main.py 

So, any calling of `BuildSources`later does not have any effect. We will inform the user about this issue.

**Comment by Wiz-IO** [comment]
Hi Ivan, thanks for the answer

my thought was: add_module( src folder ) from ini file ... CMAKE uses similar practices
some code is not compiled by main builder, but exist in framework
example: 
lwip is compiled as basic, without apps ... http, tftp etc
and I wanted to add them from INI with POST script
for now I found a way with PRE script - I had uninitialized variables

```
...
Building in release mode
-- EXECUTE POST-SCRIPT.PY --
-- FROM PRE-SCRIPT - BuildSources() -- Compiling WORK
-- FROM MAIN BUILDER --
Compiling .pio\build\...any code...
Compiling .pio\build\any-framework\main.o
-- FROM POST-SCRIPT - BuildSources() -- Would be great feature <<<----------
-- FROM POST-SCRIPT - BuildLibrary() -- Compiling WORK
Linking .pio\build\raspberry-pi-pico\APPLICATION.elf
...
```

you can close issue if not important

**Comment by ivankravets** [comment]
I've just added a warning message. Please use BuildLibrary in this case.

**Comment by Wiz-IO** [comment]
BTW in doc
https://docs.platformio.org/en/latest/scripting/actions.html

need more info about action target( trigers )
env.AddPreAction(TRIGER", before)
env.AddPostAction(AFTER, after)

maybe exist: before_main_build, after_main_build

**Comment by ivankravets** [comment]
Pre/Post action accepts a taget (or list of targets) as a first argument. Target can be a physical path, a SCons node, or virtual alias.

**Comment by Wiz-IO** [comment]
I understood

**Comment by Wiz-IO** [comment]
as idea / info

I make experiment with add "modules" ( not compiled codes, existing in framework ) - **makefile style**

as example:
https://github.com/Wiz-IO/framework-wizio-pico/tree/main/SDK/lib/at_tok

**at_tok** is not compiled from my builder by default and I add this module with project ini
board_build.modules = $FRAMEWORK_DIR/SDK/lib/at_tok

the "module" can be existing code in framework or
can be internal or external library ... lib_deps etc
can be compiled "on request"

my add modules function ... 
https://github.com/Wiz-IO/wizio-pico/blob/e2ca0e87724e0fd8cd90b09563aa3aea5e6af232/builder/frameworks/common.py#L348-L364
