### ISSUE TITLE
Confusing behaviour for Clean All

### ISSUE THREAD

**Issue by DigiH** [platformio/platformio-core#4386]
With recent updates of Visual Studio Code (1.17.0) and Platformio (Core 6.1.3/Home 3.4.3/IDEv2.5.1) on macOS 10.15.7 I'm experiencing strange behaviours when trying to select the **Clean All** project task in an environment.

**Clean** works fine as usual, cleaning the build directory of the environment.

**Clean All** however, which previously nicely also cleaned the libdeps of the project environment, now only brings up the task menu, with the shown three options when clicking on the entered Clean All command

<img width="313" alt="Screenshot 2022-08-09 at 20 19 38" src="https://user-images.githubusercontent.com/17110652/183740705-86342bba-200f-4f20-8313-2d75604c9fc6.png">

<img width="628" alt="Screenshot 2022-08-09 at 20 20 08" src="https://user-images.githubusercontent.com/17110652/183740725-4e204726-3590-4347-a684-560cf39268d2.png">

Also when using the cli command for cleanall, e.g.

`platformio run --target cleanall --environment esp32dev-ble`

it cleans ALL libdeps for all previously built environments, but only the build directory for the specified environment.

I'm pretty confident that when the actual **Clean All** project task was still working for me previously it only ever cleared/deleted both the build directory and the libdeps only for the environment it was selected in.

Thought I had might have something messed up on my system, but just confirmed with a colleague confirming the same behaviour on his macOS 12.5 and all the latest relevant versions as myself.

**Comment by DigiH** [comment]
Hi @ivankravets , thanks a lot for the very quick fix, which seemed to have solved the cli command issue mentioned above

`platformio run --target cleanall --environment esp32dev-ble`

in the --dev upgrade. 👍 

The sidebar task **Clean All** still is broken though. 

Searching for **Clean** tasks in the Platformio tasks brings up 

<img width="622" alt="Screenshot 2022-08-10 at 16 26 21" src="https://user-images.githubusercontent.com/17110652/183926964-afa2f27a-ac21-4a27-a886-5db257c74e7c.png">

with the `PlatformIO: Clean a build environment and installed library dependencies` being the `cleanall` task, but not named/linked to the **Clean All** sidebar project task any longer.

Or would this be addressable in [platformio-vscode-ide](https://github.com/platformio/platformio-vscode-ide) ?

Thanks

**Comment by ivankravets** [comment]
It looks like an issue in VSCode, see https://github.com/microsoft/vscode/issues/157814

Could you file a new issue in https://github.com/platformio/platformio-vscode-ide/issues ? We will make a hotfix to it and release a new version of extension. Thanks!
