### ISSUE TITLE
WiFI issues  cant FIND ESP32 SSID

### ISSUE THREAD

**Issue by ains98** [platformio/platformio-core#4388]
With PlatformIO core V5.1.0 ESP32-s2-solana dev board also not  working with WiFiManager lib.
Also tested with esp32-s3 the same issue.
ESP32-S3 not working SPIFS and NVS

Cant find SSID AutoConnectAP 
I used 4 different mobile phones and 2 different laptop PC to find esp32 in WiFi list

platform.ini:
[env:esp32-s2-saola-1]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/tzapu/WiFiManager.git

Terminal output:
SPIFFS mounted
*wm:[1] AutoConnect
*wm:[2] ESP32 event handler enabled 
*wm:[2] Connecting as wifi client...
*wm:[2] setSTAConfig static ip not set, skipping
*wm:[1] Connecting to SAVED AP: espressif
*wm:[1] connectTimeout not set, ESP waitForConnectResult... 
*wm:[2] [EVENT] WIFI_REASON:  201
*wm:[2] [EVENT] WIFI_REASON: NO_AP_FOUND
*wm:[2] Connection result: WL_NO_SSID_AVAIL
*wm:[1] AutoConnect: FAILED
*wm:[2] Starting Config Portal
*wm:[2] Disabling STA
*wm:[2] Enabling AP
*wm:[1] StartAP with SSID:  AutoConnectAP
*wm:[2] AP has anonymous access!
*wm:[1] AP IP address: 192.168.4.1
*wm:[1] Starting Web Portal
*wm:[2] HTTP server started
*wm:[2] Config Portal Running, blocking, waiting for clients...
*wm:[2] NUM CLIENTS:  0

Code i`m using for this test:

```c++
#include <Arduino.h>
#include <SPIFFS.h>
#include <FS.h>
#include <WiFiManager.h> 



void setup() {
  Serial.begin(115200);
  if (!SPIFFS.begin(true))
  {
    Serial.println("SPIFFS failure");
  }
    Serial.println("SPIFFS mounted");

    WiFiManager wifiManager;
   
    wifiManager.autoConnect("AutoConnectAP");
    
    Serial.println("connected...yeey :)");
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
