### ISSUE TITLE
PIO Home not showing up

### ISSUE THREAD

**Issue by TheMakerJojo** [platformio/platformio-core#4390]
Hello.
I have a problem using PlatformIO in codeserver. 
I installed the extension using the VSIX-File from the VS code marketplace.
Codeserver is running on an Raspberry Pi 4b with 2GB of RAM which is connected to my iPad Pro M1 via usb-c cable.
The connection is set up like in this tutorial: https://www.hardill.me.uk/wordpress/2019/11/02/pi4-usb-c-gadget/

The PIO Home won’t show up in codeserver. See in the picture below:
![image](https://user-images.githubusercontent.com/60624394/184013382-f8e296ad-25b5-4b20-92cc-7e64a3e816b8.jpeg)

If i do „pio home --host 10.55.0.1“ to display PIO Home in my Webbrowser it works perfectly fine.
![image](https://user-images.githubusercontent.com/60624394/184013586-219ac0f6-92ab-498d-83e4-f963f17caed5.jpeg)
![image](https://user-images.githubusercontent.com/60624394/184013665-c08c5f25-adf9-44d0-b47d-977892d376db.jpeg)

Please help me!

**Comment by ivankravets** [comment]
Please take a look at the [platformio-ide.pioHomeServerHttpHost](https://docs.platformio.org/en/latest/integration/ide/vscode.html#platformio-ide-piohomeserverhttphost) setting.

**Comment by TheMakerJojo** [comment]
Thanks for the answer.

I tried 0.0.0.0, 127.0.0.1 and 10.55.0.1 (IP-Address of the Raspberry Pi), but it didn't work.

Does the Raspberry Pi (vs codeserver) need an internet connection?
