### ISSUE TITLE
I can't install platforms

### ISSUE THREAD

**Issue by dunielm02** [platformio/platformio-core#4392]
Hello I'm using the latest PlatformIO version for VSCode windows11 amd64 based

First I try to create a new project, I wait for hours but nothing happens, after that I try to install de platform via terminal with this command:
`pio pkg install -p espressif32`

thats give me this:

![image](https://user-images.githubusercontent.com/98489250/184467277-69bce8f8-712e-479c-b136-426590044d16.png)

and nothing happens, the terminal stills loading, when I try again to init project, that never over.

I haven't idea what is happening

**Comment by ivankravets** [comment]
It looks like IDE is resolving project dependencies. Do you see a spinner icon on the bottom status bar?

**Comment by ivankravets** [comment]
Please reopen if you still need help
