### ISSUE TITLE
Update clang-tidy support to v15.0.0 (or later)

### ISSUE THREAD

**Issue by zeroisnan** [platformio/platformio-core#4420]
**Feature Request**.
As per subject, update PlatformIO to use the recently released clang-tidy v15.0.0 or whatever will be the latest available version when this ticket will be looked into

Thank you very much,
nico

------------------------------------------------------------------

### Configuration

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.4

### Description of problem

PlatformIO is currently using clang-tidy v12.0.1

### Additional info

Links to clang-tidy release notes between 12.0.1 (currently supported version in PIO) and 15.0.0 (latest release at the time of writing):
* https://releases.llvm.org/12.0.1/tools/clang/tools/extra/docs/ReleaseNotes.html#improvements-to-clang-tidy
* https://releases.llvm.org/13.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#improvements-to-clang-tidy
* https://releases.llvm.org/13.0.1/tools/clang/tools/extra/docs/ReleaseNotes.html#improvements-to-clang-tidy
* https://releases.llvm.org/14.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#improvements-to-clang-tidy
* https://releases.llvm.org/15.0.0/tools/clang/tools/extra/docs/ReleaseNotes.html#improvements-to-clang-tidy

**Comment by grisharav** [comment]
Any updates on this?
