### ISSUE TITLE
 *  The terminal process "...\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 

### ISSUE THREAD

**Issue by jonogunn** [platformio/platformio-core#4426]
I have a fresh install of VS Code and Platformio IDE. Everything up to date. Whenever I try to Build I keep getting the below error:

Warning! Ignore unkn
own configuration op
tion `monitor_flags`
 in section [env]   
Warning! `src_filter
` configuration opti
on in section [env:i
nclude_tree] is depr
ecated and will be r
emoved in the next r
elease! Please use `
build_src_filter` in
stead
Warning! `src_filter
` configuration opti
on in section [env:D
UE] is deprecated an
d will be removed in
 the next release! P
lease use `build_src
_filter` instead    
Warning! `src_filter
` configuration opti
on in section [env:e
sp32] is deprecated 
and will be removed 
in the next release!
 Please use `build_s
rc_filter` instead  
Warning! `src_build_
flags` configuration
 option in section [
env:linux_native] is
 deprecated and will
 be removed in the n
ext release! Please 
use `build_src_flags
` instead
Warning! `src_filter
` configuration opti
on in section [env:l
inux_native] is depr
ecated and will be r
emoved in the next r
elease! Please use `
build_src_filter` in
stead
Warning! `src_filter
` configuration opti
on in section [env:S
AMD51_grandcentral_m
4] is deprecated and
 will be removed in 
the next release! Pl
ease use `build_src_
filter` instead     
Warning! `src_filter
` configuration opti
on in section [env:m
alyan_M300] is depre
cated and will be re
moved in the next re
lease! Please use `b
uild_src_filter` ins
tead
Warning! `src_filter
` configuration opti
on in section [env:t
eensy31] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy35] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy36] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy41] is deprecat
CONFIGURATION: https
://docs.platformio.o
rg/page/boards/ststm
32/marlin_CHITU_F103
.html
PLATFORM: ST STM32 (
12.1.1) > CHITU STM3
2F103Z (64k RAM. 512
k Flash)F103; framew
HARDWARE: STM32F103Z
ET6 72MHz, 59.12KB R
AM, 469.03KB Flash  
DEBUG: Current (blac
kmagic) External (bl
AssertionError: :
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
main.py", line 188: 
    env.SConscript("
$BUILD_SCRIPT")     
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Script\SConscript.
py", line 597:      
    return _SConscri
pt(self.fs, *files, 
**subst_kw)
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Script\SConscript.
py", line 285:      
    exec(compile(scr
iptdata, scriptname,
 'exec'), call_stack
[-1].globals)       
  File "C:\Users\Jon
athan\.platformio\pl
atforms\ststm32\buil
der\main.py", line 1
20:
    target_elf = env
.BuildProgram()     
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 60:
    env.ProcessProgr
amDeps()
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 120:
    env.BuildFramewo
rks(env.get("PIOFRAM
EWORK"))
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 328:
    env.ConvertInoTo
Cpp()
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 238:
    out_file = c.con
vert(ino_nodes)     
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 86:
    return self.proc
ess(contents)       
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 107:
    assert self._gcc
_preprocess(contents
, out_file)
 [FAILED] Took 2.06 
seconds

Environment    Statu
s    Duration       
-------------  -----
Warning! Ignore unkn
own configuration op
tion `monitor_flags`
 in section [env]   
Warning! `src_filter
` configuration opti
on in section [env:icess "C:\Users\Jonathan\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
nclude_tree] is depr reused by tasks, press any key to close it. 
ecated and will be r
emoved in the next rC:\Users\Jonathan\.platformio\penv\Scripts\platformio.exe run 
elease! Please use `
build_src_filter` in
stead
Warning! `src_filter
` configuration opti
on in section [env:D
UE] is deprecated an
d will be removed in
 the next release! P
lease use `build_src
_filter` instead    
Warning! `src_build_
flags` configuration
 option in section [
env:linux_native] is
 deprecated and will
 be removed in the n
ext release! Please 
use `build_src_flags
` instead
Warning! `src_filter
` configuration opti
on in section [env:l
inux_native] is depr
ecated and will be r
emoved in the next r
elease! Please use `
build_src_filter` in
stead
Warning! `src_filter
` configuration opti
on in section [env:S
AMD51_grandcentral_m
4] is deprecated and
 will be removed in 
the next release! Pl
ease use `build_src_
filter` instead     
Warning! `src_filter
` configuration opti
on in section [env:m
alyan_M300] is depre
cated and will be re
moved in the next re
lease! Please use `b
uild_src_filter` ins
tead
Warning! `src_filter
` configuration opti
on in section [env:t
eensy31] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy35] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy36] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy41] is deprecat
CONFIGURATION: https
://docs.platformio.o
rg/page/boards/ststm
32/marlin_CHITU_F103
.html
PLATFORM: ST STM32 (
12.1.1) > CHITU STM3
2F103Z (64k RAM. 512
k Flash)F103; framew
HARDWARE: STM32F103Z
ET6 72MHz, 59.12KB R
AM, 469.03KB Flash  
DEBUG: Current (blac
kmagic) External (bl
AssertionError: :
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
main.py", line 188: 
    env.SConscript("
$BUILD_SCRIPT")     
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Script\SConscript.
py", line 597:      
    return _SConscri
pt(self.fs, *files, 
**subst_kw)
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Script\SConscript.
py", line 285:      
    exec(compile(scr
iptdata, scriptname,
 'exec'), call_stack
[-1].globals)       
  File "C:\Users\Jon
athan\.platformio\pl
atforms\ststm32\buil
der\main.py", line 1
20:
    target_elf = env
.BuildProgram()     
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 60:
    env.ProcessProgr
amDeps()
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 120:
    env.BuildFramewo
rks(env.get("PIOFRAM
EWORK"))
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 328:
    env.ConvertInoTo
Cpp()
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 238:
    out_file = c.con
vert(ino_nodes)     
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 86:
    return self.proc
ess(contents)       
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 107:
    assert self._gcc
_preprocess(contents
, out_file)
 [FAILED] Took 1.79 
seconds

Environment    Statu
s    Duration       
Warning! Ignore unkn
own configuration op
tion `monitor_flags`
 in section [env]   
Warning! `src_filter
` configuration opti
on in section [env:i
nclude_tree] is deprcess "C:\Users\Jonathan\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
ecated and will be r reused by tasks, press any key to close it. 
emoved in the next r
elease! Please use `
build_src_filter` in
stead
Warning! `src_filter
` configuration opti
on in section [env:D
UE] is deprecated an
d will be removed in
 the next release! P
lease use `build_src
_filter` instead    
Warning! `src_build_
flags` configuration
 option in section [
env:linux_native] is
 deprecated and will
 be removed in the n
ext release! Please 
use `build_src_flags
` instead
Warning! `src_filter
` configuration opti
on in section [env:l
inux_native] is depr
ecated and will be r
emoved in the next r
elease! Please use `
build_src_filter` in
stead
Warning! `src_filter
` configuration opti
on in section [env:S
AMD51_grandcentral_m
4] is deprecated and
 will be removed in 
the next release! Pl
ease use `build_src_
filter` instead     
Warning! `src_filter
` configuration opti
on in section [env:m
alyan_M300] is depre
cated and will be re
moved in the next re
lease! Please use `b
uild_src_filter` ins
tead
Warning! `src_filter
` configuration opti
on in section [env:t
eensy31] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy35] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy36] is deprecat
ed and will be remov
ed in the next relea
se! Please use `buil
d_src_filter` instea
d
Warning! `src_filter
` configuration opti
on in section [env:t
eensy41] is deprecat
CONFIGURATION: https
://docs.platformio.o
rg/page/boards/ststm
32/marlin_CHITU_F103
.html
PLATFORM: ST STM32 (
12.1.1) > CHITU STM3
2F103Z (64k RAM. 512
k Flash)F103; framew
HARDWARE: STM32F103Z
ET6 72MHz, 59.12KB R
AM, 469.03KB Flash  
DEBUG: Current (blac
kmagic) External (bl
AssertionError: :
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
main.py", line 188: 
    env.SConscript("
$BUILD_SCRIPT")     
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Script\SConscript.
py", line 597:      
    return _SConscri
pt(self.fs, *files, 
**subst_kw)
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Script\SConscript.
py", line 285:      
    exec(compile(scr
iptdata, scriptname,
 'exec'), call_stack
[-1].globals)       
  File "C:\Users\Jon
athan\.platformio\pl
atforms\ststm32\buil
der\main.py", line 1
20:
    target_elf = env
.BuildProgram()     
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 60:
    env.ProcessProgr
amDeps()
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 120:
    env.BuildFramewo
rks(env.get("PIOFRAM
EWORK"))
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\piobuild.py", 
line 328:
    env.ConvertInoTo
Cpp()
  File "C:\Users\Jon
athan\.platformio\pa
ckages\tool-scons\sc
ons-local-4.4.0\SCon
s\Util.py", line 737
:
    return self.meth
od(*nargs, **kwargs)
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 238:
    out_file = c.con
vert(ino_nodes)     
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 86:
    return self.proc
ess(contents)       
  File "C:\Users\Jon
athan\.platformio\pe
nv\lib\site-packages
\platformio\builder\
tools\pioino.py", li
ne 107:
    assert self._gcc
_preprocess(contents
, out_file)
 [FAILED] Took 1.81 
seconds

Environment    Statu
s    Duration       
-------------  -----
---  ------------   
chitu_f103     FAILE
D    00:00:01.810   
 1 failed, 0 succeed
ed in 00:00:01.810  

 *  The terminal process "C:\Users\Jonathan\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by ivankravets** [comment]
Do you use any espionage software ("antivirus" tools, such as Kaspersky, etc)? Try to disable them. Another idea is to remove `C:\Users\Jonathan\.platformio\` folder, restart VSCode, and try to build again.
