### ISSUE TITLE
Error while trying to install m5stack/M5-ADS1115 @ ^0.0.2

### ISSUE THREAD

**Issue by Tinyu-Zhao** [platformio/platformio-core#4430]
When trying to install M5-ADS1115 with the command `pio pkg install -l "m5stack/M5-ADS1115 @ ^0.0.2"`, an error occurs and the error message is empty.

<img width="779" alt="image" src="https://user-images.githubusercontent.com/44396641/193396440-e214fa32-4ca9-4878-af21-379fdb40b183.png">

And in the warehouse search, there are two identical libraries.

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/44396641/193396539-70390306-ca0d-4673-a069-7bb7e0a39b15.png">

**Comment by ivankravets** [comment]
Thanks for the report! Fixed. Please run `pio system prune -f` and try again.
