### ISSUE TITLE
Feature request for Inkplate 6

### ISSUE THREAD

**Issue by LovroG05** [platformio/platformio-core#4435]
What kind of issue is this?

- [ *] **Feature Request**.
      I hereby request that the Inkplate 6 board be added to Platformio

------------------------------------------------------------------

### Additional info

https://inkplate.readthedocs.io/en/latest/features.html#inkplate-6

**Comment by maxgerhardt** [comment]
This issue is suitable for https://github.com/platformio/platform-espressif32/issues since this is an ESP32 based board using a [fork of Arduino-ESP32](https://github.com/e-radionicacom/Dasduino-Board-Definitions-for-Arduino-IDE).

**Comment by LovroG05** [comment]
solved using https://github.com/martinberlin/inkplate-platformio
