### ISSUE TITLE
Warning! Ignore unknown configuration option `monitor_flags` in section [env]

### ISSUE THREAD

**Issue by XeroZar** [platformio/platformio-core#4441]
Has anyone found a solution for this warning... I've looked at the documentation 

https://docs.platformio.org/en/latest/projectconf/section_env_monitor.html#monitor-flags

and it doesn't help...

I am trying to fix this, if anyone know how, I can't figure it out if my life depended on it.

==Code Below==

monitor_flags =
  --quiet
  --echo
  --eol
    LF
  --filter
    colorize
  --filter
    time

==End Code==

**Comment by maxgerhardt** [comment]
```ini
monitor_echo = yes
monitor_eol = LF
monitor_filters =
   colorize
   time
```

**Comment by ivankravets** [comment]
Thanks, @maxgerhardt, for the solution.

**Comment by XeroZar** [comment]
> ```ini
> monitor_echo = yes
> monitor_eol = LF
> monitor_filters =
>    colorize
>    time
> ```

Your awesome thank you.

**Comment by N0YHR** [comment]
I know this is closed, but I've searched numerous files within the project hoping to find "monitor_echo", but do not see where these edits go to eliminate the error.

**Comment by N0YHR** [comment]
I just found them in platformio.ini

Thanks...

**Comment by sancio1234** [comment]
dove e cosa hai fato

**Comment by sancio1234** [comment]
> Li ho appena trovati in platformio.ini
> 
> Grazie...

come lo ai compilato che non riesco

**Comment by sancio1234** [comment]
> > ```ini
> > monitor_echo = yes
> > monitor_eol = LF
> > monitor_filters =
> >    colorize
> >    time
> > ```
> 
> Il tuo fantastico grazie.

dove lo devo copiare in piu mi dice no section headers
