### ISSUE TITLE
Not receiving account registration emails

### ISSUE THREAD

**Issue by echiu64** [platformio/platformio-core#4443]
Not receiving account registration emails or password reset emails from platformio. Can someone help me look into this? Registered a few accounts (echiu64, echiu65, echiu642) with different emails, no luck. Checked spam folder, nothing. It's been over 5-10 minutes, assuming there's an issue on the sender side (emails I'm using are @gmail.com or a gsuite domain)

**Comment by ivankravets** [comment]
Sorry for the issue, we are working on it.

**Comment by ivankravets** [comment]
Should be fixed now. Please check your email. The duplicated accounts were deleted. Please use `echiu64`
