### ISSUE TITLE
PIO is not building files that should be build because defines in a header file included by compiler flag -include changed

### ISSUE THREAD

**Issue by Ing-Dom** [platformio/platformio-core#4449]
### Configuration

**Operating system**: Win10

**PlatformIO Version** (`platformio --version`): 

### Description of problem

If a preprocessor define within a file that is included by -include in the plattformio.ini is changed this change does not lead to a recompile of codefiles that use that define

#### Steps to Reproduce

I prepared a sample project: [(https://github.com/Ing-Dom/TestProject_include)](https://github.com/Ing-Dom/TestProject_include)

1. Build with build_RP2040 => firmware.bin is created, all files are compiled
2. Build again build_RP2040 => no file is recompiled
3. Change e.g. the delay in main.cpp, Build again build_RP2040 => main.cpp file is recompiled
4. Change -D OUTPIN1=? in plattformio.ini, Build again build_RP2040 => all files are recompiled
5. change OUTPIN2 in hardware.h => Build again build_RP2040 => no file is recompiled (but should !!)

### Actual Results

the binary of a partial build differs from a clean build

### Expected Results

a change in a included (by build_flag -include) header file should at least lead to a recompile of every file actually using that define

**Comment by ivankravets** [comment]
Part of this issue https://github.com/platformio/platformio-core/issues/3113
