### ISSUE TITLE
using extra_scripts is not working as expected (global scope)

### ISSUE THREAD

**Issue by slaesh** [platformio/platformio-core#4453]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

# repo to reproduce

https://github.com/slaesh/platformio_extra_scripts_issue

# using `env` is not working, BUT `projenv` is

```py
# this does not work as expected!
env.Append(CPPDEFINES=[
    ("CPPDEF_GLOBAL", env.StringifyMacro('injected1..')),
])

# this does work
projenv.Append(CPPDEFINES=[
  ("CPPDEF_PROJECT", env.StringifyMacro('injected2..'))
])
```

# the actual output from the ESP

```
git : 6b80bc8776e90cde928e9e9e301eaede1be1808b
glob: CPPDEF_GLOBAL
proj: injected2..
```

# the expected output

```
git : 6b80bc8776e90cde928e9e9e301eaede1be1808b
glob: injected1..
proj: injected2..
```

**Comment by ivankravets** [comment]
This is the feature of the PlatformIO Build System. If you want to pass global flags to ALL components (frameworks, project, libraries), please use [PRE script](https://docs.platformio.org/en/latest/scripting/launch_types.html). The POST-type script operates with "cloned" and isolated envs.
