### ISSUE TITLE
Installs `scripts/` directory to the global namespace

### ISSUE THREAD

**Issue by mcepl** [platformio/platformio-core#4458]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Linux, openSUSE/Tumbleweed

**PlatformIO Version** (`platformio --version`): 6.1.5

### Description of problem

When packaging platformIO-core for openSUSE, I have discovered that the package’s install script creates and populates purelib/scripts directory. That sounds wrong to me, shouldn’t it put these scripts as a subdirectory of the platformio package?

#### Steps to Reproduce

1. `python3 setup.py install`
2.
3.

### Actual Results
The script installs two subdirectories in `purelib`: `platformio/` and `scripts/`.

### Expected Results
It should install just one subdirectory, not using another name in the global namespace and especially not with so generic symbol.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
none

Complete [build log](https://github.com/platformio/platformio-core/files/9995117/_log.txt) for details of packages used and steps taken to reproduce.

**Comment by ivankravets** [comment]
Thanks for the PR! Please re-test with `pio upgrade --dev`.
