### ISSUE TITLE
Add support for the Cypress FM0+ S6E1A Series

### ISSUE THREAD

**Issue by Jozo132** [platformio/platformio-core#4465]
**Feature Request**
Requesting support for Cypress FM0+ S6E1A Series, 32-bit Arm® Cortex®-M0+
There are a lot of industrial and commercial electronic products that use this family of microcontrollers.
I've been trying to find resources for the Cypress S6E1A11C0A and the only way to program it right now is using the Keil MDK IDE.
It only mentions UART/Serial for flash upload even though it supports SWD for debugging.

**Comment by ivankravets** [comment]
Please vote 👍  for this issue https://github.com/platformio/platformio-core/issues/2052
