### ISSUE TITLE
Disabled COM ports appear in Devices

### ISSUE THREAD

**Issue by arc12** [platformio/platformio-core#4486]
### Configuration
Windows 11
Platformio core 6.1.5

### Description of problem
A COM port appears as disabled in "Device Manager" but is listed in Platformio Devices/Serial and is auto-selected by platformio for program upload (to ESP8266 board).

**Comment by ivankravets** [comment]
We use the PySerial Python package to work with serial devices. Could I ask you to forward this issue to https://github.com/pyserial/pyserial/issues?
