### ISSUE TITLE
Compilation ignores preprocessor definitions leading to import errors

### ISSUE THREAD

**Issue by Dantali0n** [platformio/platformio-core#4489]
When including headers that are part of the framework any pre processor statement to prevent inclusion is ignored and the underlying code is incorrectly compiled leading to compilation errors.

------------------------------------------------------------------

### Configuration

**Operating system**: Arch Linux

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.5

### Description of problem

The use of preproccesor definitions should allow to prevent inclusion of unwanted headers but they are still included if part of the framework. 

#### Steps to Reproduce

1. Define a platform in the ini, say using the following

```
[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
framework = arduino
```

3. In the main.cpp create an `#ifdef` that is clearly false and inside the statement include `WiFi.h`
4. Watch the code highlighting in your IDE of choice shows this will not be included.

### Actual Results

Now when you compile the compilation fails because WiFi.h is still included...

### Expected Results

The compilation should succeed and WifFi.h should not be included.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:nanorp2040connect]
platform = raspberrypi
board = nanorp2040connect
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

#if 0 == 1
  #include <WiFi.h>
#endif

void setup() {
}

void loop() {
}
```
### Additional Info

The header WiFi.h and the platform are carefully chosen such that the WiFI.h actually exists as part of the includes provided by the framework while also causing the compilation to fail. Choosing headers files that are not part of the framework will not trigger this bug.

Some excerpts of the moment it makes the error to include WiFi.h:

```
In file included from /home/xxx/.platformio/packages/framework-arduino-mbed/libraries/WiFi/src/WiFiServer.h:20,
                 from /home/xxx/.platformio/packages/framework-arduino-mbed/libraries/WiFi/src/WiFiServer.cpp:1:
/home/xxx/.platformio/packages/framework-arduino-mbed/libraries/WiFi/src/WiFi.h:203:3: error: 'WiFiAccessPoint' does not name a type
  203 |   WiFiAccessPoint* ap_list = nullptr;
  ```
  
  Yes, if you remove the statement to include WiFi.h it compiles without issue.

**Comment by ivankravets** [comment]
Please check https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-ldf-mode
