### ISSUE TITLE
GIT "Local" Repositories with "#TAG" missing in lib_deps documentation

### ISSUE THREAD

**Issue by fixus971** [platformio/platformio-core#4492]
Feature Doc issue

I have been sent here by the community:
[community quest](https://community.platformio.org/t/include-local-git-repositories-with-tag-from-platformio-ini-lib-deps/30862)

* Doc Feature Request:
Information about using GIT "Local" Repositories.
 I intend to call back through platformio.ini lib_deps
  a certain version of the local GIT using a #TAG:

* Solution:
  The content of `platformio.ini`:
```
lib_deps =
  git+…/…/library#TAG
  ^^^___________^no final /, no.git here
```
  In my case the relative path comes in handy

  PlatformIO for VSCode  Core 6.1.5
  Arduino: Esp32 / nRF52
  Win10

* Description of problem:
Missing information in the lib_deps FAQ
I intend to call back through platformio.ini lib_deps a certain version of the local GIT using a #TAG.
I had to try so many combinations!! (mindmeld)
The only one that works and is not mentioned in the examples.
I know that in the faq it is written to use this protocol key:
[Version control](https://docs.platformio.org/en/latest/core/userguide/lib/cmd_install.html#id6)[¶](https://docs.platformio.org/en/latest/core/userguide/lib/cmd_install.html#version-control)
```
PlatformIO supports installing from Git, Mercurial and Subversion, and detects the type of VCS using url prefixes: “git+”, “hg+”, or “svn+”.
```
but then different examples are given which look like completion and are misleading in my case.
https://docs.platformio.org/en/latest/core/userguide/lib/cmd_install.html
```
git+git://git.server.org/my-library#master
git+https://git.server.org/my-library#v1.0
git+ssh://git.server.org/my-library#7846d8ad5
```

Now I solved it while writing here after days of testing…
Please add such type of code into yours examples.

Related problem I've encountered:
"git+file" protocol takes #TAG as part of the name

* Final note:
I don’t see the library Auto-Update in this application project when I commit the library in it’s original directory.

I tried to force the update but it gives me an error:
```
*  Executing task: C:\Users\user\.platformio\penv\Scripts\platformio.exe pkg update 
Resolving LCD dependencies...
Error: VCS: Could not receive an output from `['git', 'ls-remote', '../../ard-lib1', 'refs/heads/main']` command ({'out': '', 'err': "fatal: '../../ard-lib1' does not appear to be a git repository\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", 'returncode': 128})       
```
Instead it works and updates by doing it all over again:
```
CleanAll + Compile
```

Thanks -Fixus971

**Comment by ivankravets** [comment]
That command and docs for it are deprecated. There is a warning block on the top of that page.

The new command and docs https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#repository-git-hg-svn
