### ISSUE TITLE
pio dependency installation on linux compiles all packages from source, ignoring wheels in pypi and piwheels

### ISSUE THREAD

**Issue by yschroeder** [platformio/platformio-core#4493]
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**:
Debian GNU/Linux 11 (bullseye) on a Raspberry Pi 3B

**PlatformIO Version** (`platformio --version`):
6.1.5

### Description of problem
When running `pio remote agent start`, dependencies are installed via `pip`. Due to

https://github.com/platformio/platformio-core/blob/6395a032e5dfb7ad444718ec0da08e0f9370f3c0/platformio/package/manager/core.py#L150-L151

all packages are ALWAYS compiled from source which is extremely slow and annoying especially on slow hardware. It ignores all wheels in both, the pypi and piwheels index.

#### Steps to Reproduce

1. Run `pio remote agent start`
2. Wait an eternity for all packages to compile
3. Have everything recompiled when pio decided to update something

### Actual Results
`pip` compiles all packages from source.

### Expected Results
`pip` uses wheels when available.

### Workaround
Comment out both lines mentioned above. `pip` uses wheels for everything and installation is very fast.

**Comment by yschroeder** [comment]
Digging deeper, this change was introduced to fix https://github.com/platformio/platformio-core/issues/3652.

However, I managed to use the remote agent on a Raspberry Pi with the wheel of `cryptography`, so maybe the issue is fixed?

**Comment by yschroeder** [comment]
@ivankravets you marked this as known issue. Do you have a link to the other issue?

Is there anything I can do to help here? The issue still exists in version 6.1.6.

**Comment by ivankravets** [comment]
Now dependencies will be built on the target side. Please re-test with `pio upgrade --dev`. Does it work now?
