### ISSUE TITLE
library.json Schema - incorrect type of "examples"

### ISSUE THREAD

**Issue by nkaaf** [platformio/platformio-core#4502]
What kind of issue is this?

- [X] **PlatformIO Core**.
      If you’ve found an inconsistency between documentation and code, please provide an information below.

------------------------------------------------------------------

### Description of problem

The library.json schema that came in PR #4476 says that "examples" is of type "Object". However, the documentation (https://docs.platformio.org/en/latest/manifests/library-json/fields/examples.html) says that "examples" is of type "Array".

**Comment by ivankravets** [comment]
Thanks for the report!
