### ISSUE TITLE
Arduino "main.cpp" - user templates

### ISSUE THREAD

**Issue by Wiz-IO** [platformio/platformio-core#4504]
- [x] **PlatformIO Core**.

Hi there,

Could you modify slightly **_generate_project_main**() ( project.py )

```py
    def _generate_project_main(project_dir, board, framework):
        main_content = None
        if 'user_template' in board: ### some flag logic from board-xyz.json
            main_content = None ### skip next templates 
        elif framework == "arduino":
            ...
```

Then **project/src is empty** and gives us the opportunity to create another main.cpp template and add other project settings
example: 
https://github.com/Wiz-IO/XC16/blob/main/builder/frameworks/build-arduino.py#L11

Regards and Happy New Year
Georgi

**Comment by ivankravets** [comment]
Hi @Wiz-IO, 
There is a similar issue https://github.com/platformio/platformio-core/issues/446
Hope we will back soon to it.
