### ISSUE TITLE
Board gets additionally listed in the wrong platform in `pio board`

### ISSUE THREAD

**Issue by FFY00** [platformio/platformio-core#4511]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to appropriate repository:
      [PlatformIO IDE for Atom](https://github.com/platformio/platformio-atom-ide/issues) or
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues)

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Arch Linux

**PlatformIO Version** (`platformio --version`):

```bash
$ pio --version
PlatformIO Core, version 6.1.5
```

### Description of problem

In https://github.com/platformio/platform-ststm32/pull/670 I added a board definition, but when I went to use it I noticed that `pio boards` is outputting incorrect information. The board in question is an ST Nucleo H7A3ZI-Q, which should be only listed under the `ststm32` platform, instead it is *also* listed under `atmelavr`.

#### Steps to Reproduce

1. Copy `nucleo_h7a3zi_q.json` from https://github.com/platformio/platform-ststm32/pull/670 to a project
2. Run `pio boards h7a3`

### Actual Results

```bash
$ pio boards h7a3

Platform: atmelavr
=================================================================================
ID               MCU             Frequency    Flash    RAM     Name
---------------  --------------  -----------  -------  ------  ------------------
nucleo_h7a3zi_q  STM32H7A3ZIT6Q  280MHz       2MB      1.34MB  ST Nucleo H7A3ZI-Q

Platform: ststm32
=================================================================================
ID               MCU             Frequency    Flash    RAM     Name
---------------  --------------  -----------  -------  ------  ------------------
nucleo_h7a3zi_q  STM32H7A3ZIT6Q  280MHz       2MB      1.34MB  ST Nucleo H7A3ZI-Q
```

### Expected Results

```bash
$ pio boards h7a3

Platform: ststm32
=================================================================================
ID               MCU             Frequency    Flash    RAM     Name
---------------  --------------  -----------  -------  ------  ------------------
nucleo_h7a3zi_q  STM32H7A3ZIT6Q  280MHz       2MB      1.34MB  ST Nucleo H7A3ZI-Q
```

**Comment by ivankravets** [comment]
If you add custom boards, you can specify the `platforms` list of compatible platforms.
