### ISSUE TITLE
Add the ability to disable the output of the library tree in the terminal when compiling the project

### ISSUE THREAD

**Issue by kotyara12** [platformio/platformio-core#4517]
Add the ability to disable the output of the library tree in the terminal when compiling the project. 
It has grown VERY large for me recently, and simple output to the terminal takes a lot of time. Not to mention the fact that the information displayed in the terminal before is lost

**Comment by ivankravets** [comment]
Please re-test with `pio upgrade --dev`.

**Comment by kotyara12** [comment]
Great! Thank you very much!
