### ISSUE TITLE
Programming Arduino Yun over wifi?

### ISSUE THREAD

**Issue by grzegorzshub** [platformio/platformio-core#452]
Is it possible to program Yun over wifi please?

**Comment by ivankravets** [comment]
I hope yes. Please explain me how does it look from CLI.

**Comment by grzegorzshub** [comment]
I don’t know I'm afraid. I use Atom with Platformio and program Yun over USB only.
I have found: https://www.twilio.com/blog/2015/02/arduino-wifi-getting-started-arduino-yun.html
In the second half of the page there is description how to set Arduino IDE with Port over IP and program it over the air.
Just wondering it there is a way to do it with platformio.
Thank you

**Comment by ivankravets** [comment]
Please enable verbose mode for building and uploading in Arduino IDE settings. Then run uploading via OTA and share here link with output http://pastebin.com

**Comment by grzegorzshub** [comment]
done
http://pastebin.com/1kGkPVK9

**Comment by ivankravets** [comment]
TODO: Make uploading via SSH https://github.com/arduino/openwrt-packages-yun/blob/master/arduino/yun-scripts/files/usr/bin/run-avrdude

**Comment by AKBON** [comment]
Hi,

what is the status of this feature? Am using deviot which offers me to manually add an IP under "Serial Port(s)", but if I trigger the upload, it only says "None serial port selected".

My System is: Windows 7, Sublime + Deviot, Arduino Yun connected via LAN

**Comment by ivankravets** [comment]
Hi,

Sorry for delay. We will add full support for Arduino Yun as soon as possible.

> On Apr 12, 2016, at 11:31, AKBON <notifications@github.com> wrote:
> 
> Hi,
> 
> what is the status of this feature? Am using deviot which offers me to manually add an IP under "Serial Port(s)", but if I trigger the upload, it only says "None serial port selected".
> 
> My System is: Windows 7, Sublime + Deviot, Arduino Yun connected via LAN
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> 
> https://github.com/platformio/platformio/issues/452#issuecomment-208781683
> 

Regards, Ivan Kravets
   - Founder and CTO at PlatformIO.Org
   - Ph.D, Researcher and Software Architect
   - Creativity comes from talent and never from knowledge (c)
________________________
http://www.ikravets.com

**Comment by yveshanoulle** [comment]
last reaction to have it soon was april . We are now October. Is there any progress?

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-atmelavr/issues/23
