### ISSUE TITLE
[Feature Request] - Board Support for Seeed Studio XIAO nRF52840

### ISSUE THREAD

**Issue by imvrba** [platformio/platformio-core#4529]
Hello, I was wondering if it is possible to add support in PlatformIO for the "Seeed Studio XIAO nRF52840" and the "Seeed Studio XIAO nRF52840 (Sense)" models. 

This is the board manager URL that is given in the documentation: 
https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

For any further information, it can be found on their wiki:
https://wiki.seeedstudio.com/XIAO_BLE/

Please let me know if there is anything else that I need to provide or mention, Thanks.

**Comment by maxgerhardt** [comment]
Already implemented in https://github.com/platformio/platform-nordicnrf52/pull/151, PR review is pending.
