### ISSUE TITLE
error

### ISSUE THREAD

**Issue by heliang1795** [platformio/platformio-core#4541]
PlatformIO IDE v3.0.0

platformio.ini

build_flags =
    -I /${platformio.packages_dir}

c_cpp_properties.json
 "C:/Users123.platformiopackages/

should be  "C:/Users/123/.platformiopackages/

**Comment by ivankravets** [comment]
This is the feature of SCons/Python? See https://github.com/SCons/scons/blob/c80cbb0846c5d9265f356e86c4e79f1d13e3e8a8/SCons/Environment.py#L917

SCons parses flags expecting that you declare them in POSIX/Shell format. See also https://docs.python.org/3/library/shlex.html

So, we updated our docs and added more examples on how to use Windows paths for build flags. Shortly, you need to quote them.

https://github.com/platformio/platformio-docs/compare/437b1175bdb310e143f1fe6312433ba4f34ef715...890d8e20fed40f653ac84ff366ac16d805b4bf01#diff-1e28bcc53ccefd895de2837f99653dcc2288250029038ccc8476a4b589b0e907
