### ISSUE TITLE
Add the STM32 arduino core repo

### ISSUE THREAD

**Issue by NitrofMtl** [platformio/platformio-core#4545]
Hi.

Is it possible to add the stm32 arduino core ?

[STM32core](https://github.com/stm32duino/Arduino_Core_STM32)

Thanks

**Comment by ivankravets** [comment]
Added https://registry.platformio.org/tools/platformio/framework-arduinoststm32

**Comment by NitrofMtl** [comment]
Thanks, I install it.

One other question, on the Arduino repo, I have the stm32g070 generic supporterd but not in PIO ?? Any reason ?

**Comment by ivankravets** [comment]
Please file a new feature request at https://github.com/platformio/platform-ststm32/issues
