### ISSUE TITLE
Custom program name causes error when running native tests

### ISSUE THREAD

**Issue by j4m3s** [platformio/platformio-core#4546]
Having followed the instructions [here](https://docs.platformio.org/en/latest/scripting/examples/custom_program_name.html) I now have a version number appended to my firmware binaries.  However, I now also get 
```
Building...
Testing...
[Errno 2] No such file or directory: '.pio/build/native/program'
```
when I try to run my native tests.  

Commenting the extra_script out in platformio.ini allows the tests to run fine again in the `native` .  The tests work ok in the embedded environment - the extra_script only causes the problem running native tests.

**Comment by ivankravets** [comment]
Yes, the problem is here https://github.com/platformio/platformio-core/blob/develop/platformio/test/runners/readers/program.py#L78

We will think about how to fix it.

**Comment by j4m3s** [comment]
That's really interesting - why would appending something to PROGNAME cause an issue there?  The updated PROGNAME doesn't seem to be referenced in that function, and the error message doesn't contain anything pointing to the appended PROGNAME either.  

(I should say... my python knowledge is minimal, so don't spend time replying if it's going to be obvious to others)

**Comment by ivankravets** [comment]
Thanks for the report. Please re-test with `pio upgrade --dev`.

Does it work now?

**Comment by j4m3s** [comment]
Yes!  Brilliant, thank you :)

How do I get off the dev branch and back onto stable when the next version of platformio is released?

**Comment by ivankravets** [comment]
See https://docs.platformio.org/en/latest/core/installation/development-version.html
