### ISSUE TITLE
Debugger does not display value in native unit testing project

### ISSUE THREAD

**Issue by dtila** [platformio/platformio-core#4553]
Given a small PlatformIO project referencing ArduinoMock, the debugger does not display the value given by the mock.

![image](https://user-images.githubusercontent.com/5718468/218706747-7e10d812-12e2-4e0f-86d6-357332a91e48.png)

The bug can be reproduced using this project: https://github.com/dtila/platfornio_unittesting

------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 10

**PlatformIO Version** (`platformio --version`):
PlatformIO Core, version 6.1.6

#### Steps to Reproduce

1. Checkout the project was given the link above
2. Hit a breakpoint in the unit test

You should see debugger displayed value is not the one returned by the mock.

However the mock works correctly, since running the tests, they pass successfully:
`Building...
Testing...
test\test_native_sut\SUTTests.cpp:54: TestMock  [PASSED]`

**Comment by ivankravets** [comment]
@valeros , could you reproduce this issue? I can't make my `gdb` work on the latest macOS due to the system error `warning: unhandled dyld version (17)`.

**Comment by valeros** [comment]
Strange, but I cannot reproduce:

![image](https://user-images.githubusercontent.com/886732/232291397-4ffee6ce-6281-4c22-8396-800dbce696f5.png)

**Comment by ivankravets** [comment]
Thanks, @valeros!
