### ISSUE TITLE
How can you use 'check_patterns' to EXCLUDE a folder or file?

### ISSUE THREAD

**Issue by codegrue** [platformio/platformio-core#4566]
The example only shows how to include additional folders

https://docs.platformio.org/en/latest/projectconf/sections/env/options/check/check_patterns.html

**Comment by ivankravets** [comment]
Hints for the implementation:

- Rename `check_patterns` to the `check_src_filters` 
- Leverage [fs.match_src_file](https://github.com/platformio/platformio-core/blob/develop/platformio/fs.py#L156)
- Copy docs from [build_src_filter](https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_src_filter.html)
- Keep support for legacy `check_pattern` adding it to the [option.oldnames](https://github.com/platformio/platformio-core/blob/develop/platformio/project/options.py#L50)
