### ISSUE TITLE
Tests fail when "test_dir = ." is set

### ISSUE THREAD

**Issue by ghost** [platformio/platformio-core#4569]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**: macOS

**PlatformIO Version** (`platformio --version`): 6.1.6

### Description of problem
I'm trying to simplify my test setups, to reduce the number of nested directories.
This is useful when creating lots of tests for lots of different boards and configurations.

#### Steps to Reproduce
Run tests (one of various STM32 boards using CMSIS in my case), with these settings:

```
[platformio]
test_dir = .

[env:...]
...
```

### Actual Results
Several build errors, while PIO finds sources inside `.pio/libdeps/.../Unity/examples/` and tries to compile them.

### Expected Results
A single test build, using just the files in the current directory.

### Additional info
One solution could be to skip hidden files and subdirectories when traversing the project tree (at least for tests).

**Update** - another solution (hack?) is to add `workspace_dir = ../.pio/` to avoid creating a hidden subdir.

**Comment by ivankravets** [comment]
It works for me. Please read https://docs.platformio.org/en/latest/advanced/unit-testing/structure/hierarchy.html

You need to crate `test_***` folders in the project root.
