### ISSUE TITLE
Commented inlcudes still compiled

### ISSUE THREAD

**Issue by Xraydylan** [platformio/platformio-core#4584]
I have an issue with Clion and Platformio and not sure what the exact root cause is.

In short:

A commented `#include` is still used compiled and not excluded.
The same is true for an `#include` which is skipped with an precompile flag.

In the following instances the `#include` is still compiled:
```C++
/*
#include "Nicla_System.h"
*/
```

as well as
```C++
#if false

#include "Nicla_System.h"

#endif
```

As mentioned, I am not sure where the root cause of the issue is, and if it is even directly related to platformio or if this issue would be better suited for the CLion support or the youtrack.jetbrains forum.
I'd appreciate the help.

As for the Hard/Software:
- I am running on a Linux Ubuntu operating system,
- I am using CLion 2023.1 with the platformio plugin
- Specifically I am compiling for the Arduino Nano 33 BLE

Thank you in advance.

**Comment by ivankravets** [comment]
Please set [Dependency Finder Mode](https://docs.platformio.org/en/latest/librarymanager/ldf.html#id5) to the `chain+`.
