### ISSUE TITLE
Debug Console uses different environment than Terminal

### ISSUE THREAD

**Issue by dzid26** [platformio/platformio-core#4597]
### Configuration

**Operating system**:
Windows 11
**PlatformIO Version** (`platformio --version`):
6.1.6
### Description of the problem
Debug console uses an environment from default_envs rather than one containing build_type = debug and the whole thing builds twice 

#### Steps to Reproduce

1. Clone https://github.com/dzid26/StepperServoCAN/tree/StepperServoCAN/firmware
2. Replace `platformio.ini` with the one provided here https://github.com/platformio/platformio-core/issues/4098#issuecomment-1503082282 
3. Environment switcher is set to Default (Auto). 
4. Run debug (F5)

### Actual Results
Terminal builds `ServoCAN_debug` env. 
Debug console clears build folder and build `ServoCAN` env

### Expected Results
Both terminal and debug console should build `ServoCAN_debug` env when debugging is run because ServoCAN_debug  contains `build_type = debug` directive.

### Additional info
If I change the default env on the toolbar or modify "projectEnvName": to "ServoCAN_debug" manually then both terminal and debug_console build the same thing.

I used Python debugger to figure out what was going on. 
So far I noticed that the terminal uses the following to determine the environment name,
https://github.com/platformio/platformio-core/blob/58a1d5d96e6a1259dcb5d12b7b103eff4bbdd1fd/platformio/debug/helpers.py#L68-L74 
while Debug console uses https://github.com/platformio/platformio-core/blob/58a1d5d96e6a1259dcb5d12b7b103eff4bbdd1fd/platformio/run/cli.py#L137-L138 logic for some reason.

I think both should use the same determination logic.

**Comment by ivankravets** [comment]
Thanks for the report. Please re-test with `pio upgrade --dev`.
