### ISSUE TITLE
Building twice - Project checksum inconsistent between terminal and debug console - (Windows VSCode).

### ISSUE THREAD

**Issue by dzid26** [platformio/platformio-core#4600]
### Configuration

**Operating system**:
Windows
**PlatformIO Version** (`platformio --version`):
6.1.7a4
### Description of problem
The code is build cleaned and build twice due to the project checksum calculation.

#### Steps to Reproduce

1. Clone https://github.com/dzid26/StepperServoCAN.git
2. Open /firmware as a workspace in VScode
3. Debug (F5)

### Actual Results
The compilation is performed in the terminal, output files are cleaned, second compilation is performed in debug console, and finally enters debugging.

### Expected Results
Compilation performed in the terminal, in debug console enters debugging immediately.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[platformio]
src_dir      = src
include_dir  = src/BSP
default_envs = ServoCAN

[env]
platform = ststm32

board = genericSTM32F103C8
upload_protocol = stlink
....
```
### Additional info
The problem is on Windows. JSON file contains an absolute path that starts with the drive letter [checksum](https://github.com/platformio/platformio-core/blob/66fe55668e8bab03e12377dd55613f6f8b11b9e5/platformio/project/helpers.py#L97) 
The drive letter is upper-case when running in the terminal and lower-case in debug console. 

For example:
Terminal:
1. Checksum after [version data](https://github.com/platformio/platformio-core/blob/66fe55668e8bab03e12377dd55613f6f8b11b9e5/platformio/project/helpers.py#L94): **0f436509ab5bd52c0ae2b582dad27602dc8c71e1**
2. [JSON data](https://github.com/platformio/platformio-core/blob/66fe55668e8bab03e12377dd55613f6f8b11b9e5/platformio/project/helpers.py#L97): ```b'[["platformio", [["src_dir", "C:\\\\Users\\\\dzidm\\\\Repos\\\\MKS-SERVO42B\\\\firmware\\\\src"], ["include_dir", "C:\\\\Users\\\\dzidm\\\\Repos\\\\MKS-SERVO42B\\\\firmware\\\\src\\\\BSP"], .....```
3. Checksum after JSON data: **fae33213302e58f06acecf4878b0852887f2e409** 

Debug Console:
1. Checksum after version data: **0f436509ab5bd52c0ae2b582dad27602dc8c71e1** 
2. JSON data: ```b'[["platformio", [["src_dir", "c:\\\\Users\\\\dzidm\\\\Repos\\\\MKS-SERVO42B\\\\firmware\\\\src"], ["include_dir", "c:\\\\Users\\\\dzidm\\\\Repos\\\\MKS-SERVO42B\\\\firmware\\\\src\\\\BSP"], .....```  **_LOWER-CASE DRIVE LETTERS_**
3. Checksum after JSON data: **a3265617b703ab7b8618f1cb1eb4b1309fef17d0**  - **_DIFFERENT_**

------
Locally I created a dirty fix to normalize the drive letters which fixes the double re-build:
```
import re
def consistent_drive_letter_case(json_data: str) -> str:
    return re.sub(r'([A-Za-z]):(\\)', lambda match: match.group(1).lower() + ':' + match.group(2), json_data)
```
Replace this [line ](https://github.com/platformio/platformio-core/blob/66fe55668e8bab03e12377dd55613f6f8b11b9e5/platformio/project/helpers.py#L97)with:
`checksum.update(hashlib_encode_data(consistent_drive_letter_case((config.to_json()))))`

**Comment by ivankravets** [comment]
See https://github.com/platformio/platformio-core/blob/0d9ee75b05909c4b1d7947828f345e501867c142/platformio/project/helpers.py#L117:L118

Do you use the same working environment and build it in "debug" mode?

**Comment by dzid26** [comment]
Oh, I overlooked the Windows check. This is not where the problem is, but basically same could be done [here](https://github.com/platformio/platformio-core/blob/66fe55668e8bab03e12377dd55613f6f8b11b9e5/platformio/project/helpers.py#L97).  like this:
```
if IS_WINDOWS:  # case insensitive OS:
   checksum.update(hashlib_encode_data(((config.to_json().lower()))))
```
Or better, it would be to normalize the path in a routine that parses `src_dir` and `include_dir` are read... 


Yes, I am using a single environment and just press debug. But I also used it with dedicated env, and the problem was still there. Because it is just the source path in the JSON config that has the issue which is a common setting for both environments.

**Comment by dzid26** [comment]
How about adding:
```
    if IS_WINDOWS:
        drive_letter, rest_of_path = os.path.splitdrive(path)
        return drive_letter.lower() + rest_of_path
```
at the beginning of this code:
https://github.com/platformio/platformio-core/blob/97a7cdd2a21d76cf648266d59ba448dadef89b8e/platformio/fs.py#L199-L215

**Comment by ivankravets** [comment]
I can't reproduce this issue. Could you add to your `env` in the `platformio.ini` the following line:

```
[env:myenv]

build_type = debug

```

Does it work now?

**Comment by dzid26** [comment]
No, `build_type = debug` doesn't make a difference. 

Something causes `os.getcwd()` to behave differently depending on where the Python script is executed.

I tested by attaching `debugpy`. Commands output  when running in the terminal 
```
os.getcwd()
'C:\\Users\\dzidm\\Downloads\\MKS-SERVO42B.worktrees\\voltage-control\\firmware'
import sys
print("Path to the Python interpreter:", sys.executable)
Path to the Python interpreter: C:\Program Files\Python39\python.exe
print(sys.version)
3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
```

Commands output when running in the terminal.  `os.getcwd()` produces lower case drive letter this time.
```
os.getcwd()
'c:\\Users\\dzidm\\Downloads\\MKS-SERVO42B.worktrees\\voltage-control\\firmware'
import sys
sys.version
'3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]'
sys.executable
'C:\\Program Files\\Python39\\python.exe'
```

**Comment by ivankravets** [comment]
> 1.  tested by attaching debugpy. Commands output when running in the terminal
> 2. Commands output when running in the terminal. 

Which terminals do you use?

**Comment by dzid26** [comment]
> > 1. tested by attaching debugpy. Commands output when running in the terminal
> > 2. Commands output when running in the terminal.
> 
> Which terminals do you use?

Sorry, I meant to say 2. Commands output when script running in Debug console

**Comment by ivankravets** [comment]
What is debug console? Please provide screenshots.

**Comment by dzid26** [comment]
Basically I am running Platformio in debug mode (F5) for my stm32 project.
First pio executes in the terminal:
<img width="746" alt="image" src="https://user-images.githubusercontent.com/841061/233619316-a6c0c3f4-924c-4552-96be-f52bb60835e4.png">
Then it executes in Debug Console:
<img width="803" alt="image" src="https://user-images.githubusercontent.com/841061/233619540-598f45e9-5989-4d8d-b140-6469aebcec32.png">
As you can see it compiles the code again, which is the main reason creating this issue:

Additionally, I am debugging platformio itself in the other vscode window:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/841061/233620134-bbc3cc14-7b3a-4e6f-ba8d-76301890672f.png">

**Comment by dzid26** [comment]
Lots of issues with drive letters in vscode (python -> `os.getcwd()`):

- https://github.com/microsoft/vscode/issues?q=is%3Aissue+cwd+drive+letter+windows+
- ["Drive letters can be any casing and when implementing uri we have picked the lower-case variant"](https://github.com/microsoft/vscode/issues/146245#issuecomment-1081889928)
- https://github.com/iterative/dvc/issues/7909


Can we just normalize drive letters in the `json` for the purpose of [checksum](https://github.com/platformio/platformio-core/blob/a0c959be2877d36ba188ef5eb05329446061bbdb/platformio/project/helpers.py#L97) calculation with the following?:
```
if IS_WINDOWS:
    checksum.update(hashlib_encode_data(upper_drive_letter_case((config.to_json()))))
```


And add:

```
import re
def upper_drive_letter_case(json_data: str) -> str:
    return re.sub(r'([A-Za-z]):(\\)', lambda match: match.group(1).upper() + ':' + match.group(2), json_data)
```

**Comment by ivankravets** [comment]
I could not reproduce this issue on my Windows in a virtual machine (I'm a macOS user). Nevertheless, I added the patch which you proposed. Please re-test with `pio upgrade --dev`.
