### ISSUE TITLE
Seeed Studio XIAO nRF52840 Sense

### ISSUE THREAD

**Issue by ericphilbaz** [platformio/platformio-core#4602]
please  add the seeed board "Seeed Studio XIAO nRF52840 Sense", the board repo is : 
 https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json

**Comment by maxgerhardt** [comment]
Duplicate of https://github.com/platformio/platform-nordicnrf52/issues/142 and will be fixed by https://github.com/platformio/platform-nordicnrf52/pull/151
