### ISSUE TITLE
Issue with multiple targets

### ISSUE THREAD

**Issue by fabianoriccardi** [platformio/platformio-core#4604]
### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.6

### Description of problem

In platformio.ini I have created an env with the following target in order to flash an ESP8266:

    [env:my_env]
    targets = clean, upload, uploadfs, monitor

(other options are omitted for brevity)

I would expect they run sequentially, instead they run in parallel. Running in parallel, they lead to an obvious error since the last 3 targets try to acquire the serial port all together (the fastest target is `monitor`, so in the end `upload` and `uploadfs` fail).

### Actual Results

The targets run in parallel.

### Expected Results

The targets run sequentially.

### Additional info

Issue already posted and confirmed on PIO forum [here](https://community.platformio.org/t/issue-with-multiple-targets/33372).

**Comment by ivankravets** [comment]
Thanks for the report. Please run `pio upgrade --dev` command and re-test. It should work now.

**Comment by fabianoriccardi** [comment]
Now it **partially** works!

If I run 

    pio run -t clean -t upload -t uploadfs -t monitor

it uploads 2 times the fs, but no firmware! Clean and monitor are executed properly.

If I run 

    pio run -t clean -t upload -t monitor

it uploads the firmware as expected.

pio --version gives `6.1.7b2`

**Comment by ivankravets** [comment]
@fabianoriccardi now, this is the issue of epsressif32 dev-platform. Could you report it to https://github.com/platformio/platform-espressif32/issues ?

Thanks in advance!

**Comment by ivankravets** [comment]
@vshymanskyy , could you re-test the latest development PIO Core (`pio upgrade --dev`) for your workflow with multiple targets?

**Comment by fabianoriccardi** [comment]
I'm working on ESP8266, so I have opened the issue there.
