### ISSUE TITLE
Does Platform IO have plans for multilingual adaptation?

### ISSUE THREAD

**Issue by gxdung** [platformio/platformio-core#4640]
Platform IO IDE is not very friendly to non-English speakers. Is there any official plan to adapt to multiple languages? If so, can developers join the program to help with translations?

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platformio-vscode-ide/issues/452 

Please vote (👍 ) for this request https://github.com/platformio/platformio-vscode-ide/issues/452
