### ISSUE TITLE
Changing ini file rebuild all, but ?

### ISSUE THREAD

**Issue by mmar22** [platformio/platformio-core#4662]
For example change upload or monitor speed, add monitor filter ... rebuild all project.
Is this realy required?
If not why your build engine dont ignore rebuild ?

**Comment by ivankravets** [comment]
You can disable the default autocleaning operation with [--disable-auto-clean](https://docs.platformio.org/en/latest/core/userguide/cmd_run.html#cmdoption-pio-run-disable-auto-clean) option.
