### ISSUE TITLE
setup and teardown are not called before and after every Test

### ISSUE THREAD

**Issue by Speidey** [platformio/platformio-core#4687]
- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**: WIn10

**PlatformIO Version** (`platformio --version`): 6.1.9

### Description of problem
When following the Unit testing tutorial here: https://piolabs.com/blog/insights/unit-testing-part-1.html
I ran into the problem, that setUp and tearDown are not called when not calling them in the main function. My understanding from the tutorial was, that this should not be the case but these functions should be called automatically before and after each RUN_TEST.

I asked in the community forum and was send here by ivankravets of the PlatformIO Team.

#### Steps to Reproduce

1. Follow https://piolabs.com/blog/insights/unit-testing-part-1.html
2. get to the part where cbuffer_init(&buff); is extracted into setUp

### Actual Results
failed test

### Expected Results
succesfull testing

**Comment by valeros** [comment]
Hi @Speidey ! How did you test that the `setUp` and `tearDown` functions are not called? I just tried a basic example with `printf` and it seems to work just fine:
![image](https://github.com/platformio/platformio-core/assets/886732/3ae87c08-1937-4a82-9198-27082c40b7a1)

**Comment by ivankravets** [comment]
Please reopen if you still need help
