### ISSUE TITLE
Add support for Infineon XMC1000/XMC1100 (XMC 2GO) and XMC4000/XMC4500 (XMC 4500 Relax) Familiy

### ISSUE THREAD

**Issue by nmaas87** [platformio/platformio-core#471]
http://www.infineon.com/cms/en/product/microcontroller/32-bit-industrial-microcontroller-based-on-arm-registered-cortex-registered-m/xmc-development-tools-kits-and-boards/channel.html?channel=db3a30433580b3710135a07902883872

http://www.infineon.com/cms/en/product/evaluation-boards/KIT_XMC_2GO_XMC1100_V1/productType.html?productType=db3a304443537c4e01436ccecb5d154f#ispnTab1

http://www.infineon.com/cms/en/product/evaluation-boards/KIT_XMC45_RELAX_V1/productType.html?productType=db3a304437849205013813b23ac17763

**Comment by rezasurmar** [comment]
Any progres? Is it possible to import from Arduino IDE?

**Comment by ivankravets** [comment]
@rezasurmar could you provide links to Arduino IDE and Infineon XMC?

**Comment by rezasurmar** [comment]
https://github.com/Infineon/XMC-for-Arduino/wiki/Implementation-in-Arduino-IDE

**Comment by PabloPL** [comment]
Any update on this? It would be nice to have this supported in PlatformIO (so we don't have to use Arduino IDE).

**Comment by sherylll** [comment]
https://github.com/Infineon/platformio-infineonxmc

**Comment by ivankravets** [comment]
- https://platformio.org/platforms/infineonxmc

Please open PlatformIO IDE > PIO Home > Platforms
