### ISSUE TITLE
${platformio.name} gives "None"

### ISSUE THREAD

**Issue by swortain** [platformio/platformio-core#4717]
What kind of issue is this?

- [x] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to the
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues) repository

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------
Hi, my setting in platformio.ini shown below, In my opinion, it should set build_dir with current folder name, but it gives "None".
If there is something wrong with my setting?
<img width="1279" alt="648a4648a84deaae8db37d48993af9a" src="https://github.com/platformio/platformio-core/assets/6780386/560b836c-ab33-45af-ab26-aebe8ef773b3">

**Comment by ivankravets** [comment]
Thanks for the report. Please re-test with `pio upgrade --dev`.
