### ISSUE TITLE
Different heap consumption

### ISSUE THREAD

**Issue by Blueforcer** [platformio/platformio-core#4727]
If i compile my ESP32 firmware with VS-Code/platformIO on windows 11, the ESP reports a free heap of 135kb.
As soon my github action compiles the same code, the ESP reports only 95kb left.
Why i have 30kb less, with the same code?

```yaml
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pio run --environment ulanzi
  ```

------------------------------------------------------------------

### Configuration

platformIO core on both: 6.1.10

**Operating system**:

Windows 11 (VSCode), ubuntu-latest (GithubAction)

#### Steps to Reproduce

1. compile a firmware in VSCode under windows 11
2. compile a firmware via github action
3. compare the ESP.getFreeHeap(); output

### Expected Results
Both should be the same

**Comment by Blueforcer** [comment]
Both are the same platformIO core (6.1.10)

I see the package verisons are a bit differnet

Github:
 - framework-arduinoespressif32 @ 3.20011.230801 (2.0.11) 
 - tool-esptoolpy @ 1.40501.0 (4.5.1) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
 
 Vscode:
 - framework-arduinoespressif32 @ 3.20007.0 (2.0.7) 
 - tool-esptoolpy @ 1.40500.0 (4.5.0) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
 
 Maybe i should force platfromIO in the ini to use arduinoespressif32 2.0.7?

**Comment by ivankravets** [comment]
@maxgerhardt , thanks for the hint! 

@Blueforcer , see https://github.com/platformio/platform-espressif32/releases

You can use the fixed version in `platformio.ini`. See https://docs.platformio.org/en/latest/projectconf/sections/env/options/platform/platform.html
