### ISSUE TITLE
toolchain-gccarmnoneeabi  version 1.120201.221222  triggers Blocked insecure item errors

### ISSUE THREAD

**Issue by ellensp** [platformio/platformio-core#4741]
### Configuration

Seen on Ubuntu and Mac

PlatformIO Core, version 6.1.11

### Description of problem

Latest https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi  version 1.120201.221222 will not fully install
correctly

Installing this package triggers "Blocked insecure item" errors from

https://github.com/platformio/platformio-core/blob/develop/platformio/package/unpack.py#L84-L98

The archive seems to be damaged in some way.

### Actual Results

<img src="https://cdn.discordapp.com/attachments/491165528295997450/1149348743875928154/Capture_decran_2023-09-07_a_16.17.38.png">

### Expected Results

No Blocked insecure item errors.

### Additional info

This was noticed by Marlin firmware user, code and platformio ini files are huge, and not really relevant to this issue.

**Comment by maxgerhardt** [comment]
FYI this was added in https://github.com/platformio/platformio-core/commit/2388b2a62be5c220736dbf205bb33d413fa04cea almost 4 years ago. I think the toolchains come from the GNU ARM download directly.

**Comment by ivankravets** [comment]
We have just removed the broken `1.120201.221222` version. Please try the recently published [1.120301.0](https://registry.platformio.org/tools/platformio/toolchain-gccarmnoneeabi)

**Comment by ellensp** [comment]
Issue is still present with 1.120301.0

**Comment by maxgerhardt** [comment]
No, it does work with the new package on my machine.
```
$ pio pkg install -g -t "toolchain-gccarmnoneeabi@1.120301.0"
Tool Manager: Installing toolchain-gccarmnoneeabi @ 1.120301.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-gccarmnoneeabi@1.120301.0 has been installed!
```

```
$ pio system info
--------------------------  --------------------------------------------
PlatformIO Core             6.1.11
Python                      3.11.4-final.0
System Type                 linux_x86_64
Platform                    Linux-6.2.0-32-generic-x86_64-with-glibc2.37
```

**Comment by ellensp** [comment]
secondary linking warnings that I thought stemmed from this issue are still present.  These threw me

This issue is resolved.

**Comment by maxgerhardt** [comment]
Linking warnings? In Arduino-Pico we also noticed we need `build_flags = -Wl,--no-warn-rwx-segments` to supress a supurious warning.

**Comment by ellensp** [comment]
well getting off topic here but...

Getting these linker warnings 

warning: _close is not implemented and will always fail
warning: _fstat is not implemented and will always fail
warning: _getpid is not implemented and will always fail
warning: _isatty is not implemented and will always fail
warning: _kill is not implemented and will always fail
warning: _lseek is not implemented and will always fail
warning: _read is not implemented and will always fail
warning: _write is not implemented and will always fail

If I revert toolchain-gccarmnoneeabi to the older release
pio pkg uninstall -g -t "toolchain-gccarmnoneeabi@1.120301.0"
pio pkg install -g -t "toolchain-gccarmnoneeabi@1.100301.220327"

The warnings are not present

**Comment by ivankravets** [comment]
@ellensp , what is your development `platform`?
