### ISSUE TITLE
udev rules missing for Espressif USB JTAG/serial debug unit

### ISSUE THREAD

**Issue by jake-is-ESD-protected** [platformio/platformio-core#4758]
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.
------------------------------------------------------------------

### Configuration

**Zorin OS 16**:

**PlatformIO Version** (`platformio --version`): 6.1.8a4
**Editor**: VSCodium 1.83.1

### Description of problem
**Espressif USB JTAG/serial debug unit** is not in udev rules. This very handy "2-line JTAG" which is on chips like the **ESP32-C3-MINI-1** failed to launch when configuring a project for debugging via the debug-tool `esp-builtin`.

#### Steps to Reproduce

1. Create new project with for example the **esp32-c3-devkitm-1**
2. Launch debugging session
3. Fails with .pioinit 11

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_protocol = esp-builtin
debug_tool = esp-builtin
debug_init_break = tbreak setup
```

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio-core/pull/4759
