### ISSUE TITLE
Support wanted 4 the Lilygo T-FPGA

### ISSUE THREAD

**Issue by ikaruz567** [platformio/platformio-core#4805]
What kind of issue is this?
- [ x] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

------------------------------------------------------------------

### Additional info
there is a github page:
https://github.com/Xinyuan-LilyGO/T-FPGA

**Comment by ivankravets** [comment]
See https://github.com/Xinyuan-LilyGO/T-FPGA#platformio
