### ISSUE TITLE
pio system prune | UnknownPlatform: Unknown development platform 'atmelavr'

### ISSUE THREAD

**Issue by classicrocker883** [platformio/platformio-core#4806]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to the
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues) repository

- [x] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 11
**PlatformIO Version** (`platformio --version`):
`PlatformIO Core, version 6.1.11`
#### Steps to Reproduce
Received a warning to purge cache.
Followed instructions of the following:   
1. in terminal, type `pio system prune`
2. say "y" (yes) to prompts
3.

### Actual Results
Error:
```r
Prune unnecessary development platform packages:
Calculating...
UnknownPlatform: Unknown development platform 'atmelavr'
```
then it exits to a new line in terminal.
### Expected Results
Expected to follow through with the "system prune"

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**

**Source file to reproduce issue:**

[MarlinFirmware/Marlin](https://github.com/MarlinFirmware/Marlin.git)

### Additional info

I was able to remove the "atmelavr" directory from `C:\<User>\.platformio\platforms` and this worked correctly.

**Comment by ivankravets** [comment]
Have you manually modified `atmelavr` dev-platform?

**Comment by ivankravets** [comment]
Please reopen if you still need help
