### ISSUE TITLE
Add a programatic way to commit and push changes in libdeps repositories (propietary dependencies) 

### ISSUE THREAD

**Issue by OrnellaBenzi** [platformio/platformio-core#4807]
What kind of issue is this?
- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------
### Description of problem
Currently we are working in a complex project that involves the use of several (~40) libraries produced by us that we have in individual remote repositories (1 repo per lib), and during the process of developing it is common to make changes in them, and it is quite uncomfortable not being able to programatically commit and push the changes made in them. We are aware that we can make scripts to do that, but we thought it could be really helpful for the users of the platform.

**Comment by ivankravets** [comment]
It seems like this feature is not a part of PlatformIO Core (CLI). You need to use UI tools to manage your repositories such as https://www.sourcetreeapp.com/

You can clone your in-house libraries to the `project/lib` folder and PlatformIO Core will find them automatically.

**Comment by OrnellaBenzi** [comment]
I understand, we are currently using Tortoise Git and we manage our repositories manually.
 But we don't want to clone manually the libraries in lib folder, because the goal of using platformio was to manage the download of the dependencies  automatically when opening the project in the IDE (they are 40+ in-house libraries). That works just find, the only problem we found is that we have to commit each modified dependency individually  when developing.

**Comment by ivankravets** [comment]
Do you use [Git URL](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_install.html#repository-git-hg-svn) for [lib_deps](https://docs.platformio.org/en/latest/projectconf/sections/env/options/library/lib_deps.html)? If yes, the source files will be cloned to https://docs.platformio.org/en/latest/projectconf/sections/platformio/options/directory/libdeps_dir.html  You can edit files here and commit changes.

Another solution is to leverage https://docs.platformio.org/en/latest/scripting/index.html

1. Use PRE script
2. Declare a list of 40 libs
3. Ensure they are cloned to `lib` folder
4. If they are already cloned, pull changes with `subprocess.run(["git",  "pull")`

This is just a hint... You can extend this approach.

**Comment by ivankravets** [comment]
We would be thankful if you share here your script/solution. So, we could close the issue and other people will benefit from the idea.
