### ISSUE TITLE
CLION PIO FOR NEW VERSION WITHOUT CMAKELIST.TXT

### ISSUE THREAD

**Issue by DrRaphael** [platformio/platformio-core#4816]
I am using PlatformIO in Clion, but after upgrading to the latest version, I cancelled the CmakeList.txt file. How can I add an include path or header file path in this situation

**Comment by ivankravets** [comment]
Do you use the latest version of the PlatfomIO plugin for CLion? It should automatically pull all metadata for code completion and navigation.

**Comment by ivankravets** [comment]
Please reopen if you still need help
