### ISSUE TITLE
custom boards_dir not recognized with core version >6.1.11

### ISSUE THREAD

**Issue by Tretgo** [platformio/platformio-core#4837]
------------------------------------------------------------------

### Configuration

**Operating system**: Win 10

**PlatformIO Version** (`platformio --version`): Tested with Core 6.1.12 and 6.1.13 --> NOK, works with 6.1.11

When using a custom board and specifying a boards_dir in the platformio ini, this setting is ignored.

```ini
[platformio]
boards_dir = $PROJECT_DIR/../Shared_Files
```

#### Steps to Reproduce

1. Update Core
2. Try rebuilding

### Actual Results
Processing Bewaesserung_F030C8 (platform: ststm32; board: genericSTM32F030C8; framework: arduino)
UnknownBoard: Unknown board ID 'genericSTM32F030C8'

### Expected Results
Board builds, like it did with 6.1.11

**Comment by ivankravets** [comment]
See valid syntax https://docs.platformio.org/projectconf/interpolation.html

or just use ../


All paths are related to the project directory.
