### ISSUE TITLE
Feature request to support python extra_scripts with dependency manager

### ISSUE THREAD

**Issue by elon-code** [platformio/platformio-core#4839]
What kind of issue is this?

- [x] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

------------------------------------------------------------------

**PlatformIO Version** (`platformio --version`): 6.1.13

### Description of request
As of now, I believe you can include extra_scripts repository link in the lib_deps flags, however, it would be nice if extra scripts were more fully supported in the dependency manager. I think these features would be great to add:
- Have a separate section for extra_scripts dependencies, possibly with the ability to just paste repo links into the extra_scripts section as is.
- Download extra_scripts into a separate folder from normal libdeps
- Ability to call these scripts in an easy way. Just using the relative path would be fine, but it might be useful to have it so I can call these scripts automatically when included in dependency manager.

Thanks for your help and for the work you do! I may be able to contribute to helping develop this feature if it is desired, let me know if there is anything I can do.

**Comment by ivankravets** [comment]
Do you mean https://docs.platformio.org/en/latest/manifests/library-json/fields/build/extrascript.html ?

**Comment by elon-code** [comment]
Yes, this works! I do kind of think it might be best to have a differentiation between scripts and libraries in the dependency manager and registry... but it works good enough as is.

As it works well enough for my use case, feel free to close at your discretion. Thank you for your help and for your support of PlatformIO!

**Comment by ivankravets** [comment]
Happy coding with PlatformIO! 🚀
