### ISSUE TITLE
Support for "scripts" in package manifest

### ISSUE THREAD

**Issue by mogorman** [platformio/platformio-core#485]
It would be nice to have the toolchains have the option to be built locally.  This would make platformio more portable and sustainable in the future.

**Comment by ivankravets** [comment]
Allow assigning different scripts per events from PlatformIO Package Manager via "scripts" property. Example, https://docs.npmjs.com/misc/scripts

Having "postinstall" action will allow calling a build script where we can build a toolchain/tools from the source code.

**Comment by ivankravets** [comment]
Sorry that it took so many years :(
