### ISSUE TITLE
Addition of new boards of Texas Instruments especially TMDXRM57LHDK , RM57L843 and C6000 family

### ISSUE THREAD

**Issue by Ahmed-Bilal-01** [platformio/platformio-core#4866]
Please add new these boards in this system of Texas Instruments especially TMDXRM57LHDK, RM57L843 and C6000 family

**Comment by ivankravets** [comment]
https://github.com/platformio/platformio-core/issues/3732

**Comment by Ahmed-Bilal-01** [comment]
These boards are not added why you marked it as done?
