### ISSUE TITLE
Cppcheck does not work on Windows...

### ISSUE THREAD

**Issue by FredM67** [platformio/platformio-core#4867]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to the
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues) repository

- [X] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Windows 11

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.14b1

### Description of problem
Whatever options/flags I'm trying for cppcheck, I get always :
```
Error: Checking basic_debug > cppcheck (platform: atmelavr; framework: arduino; board: uno)
--------------------------------------------------------------------------------
Error: Nothing to check.

Error: cppcheck failed to perform check! Please examine tool output in verbose mode.
```

#### Steps to Reproduce

1. Perform a check with the UI or command line (verbose does not help at all)

### Actual Results
```
Error: Checking basic_debug > cppcheck (platform: atmelavr; framework: arduino; board: uno)
--------------------------------------------------------------------------------
Error: Nothing to check.

Error: cppcheck failed to perform check! Please examine tool output in verbose mode.
```

### Expected Results
Should run without critical error !

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[platformio]
description = Router program
default_envs = basic
src_dir = ./

[env]
platform = atmelavr
framework = arduino
board = uno
build_flags =
    -std=c++17
    -std=gnu++17
build_unflags =
    -std=c++11
    -std=gnu++11
extra_scripts = pre:inject_sketch_name.py
check_tool = cppcheck, clangtidy
check_flags =
    cppcheck: --enable=all
    clangtidy: --fix --checks=*,-llvmlibc-callee-namespace,-llvmlibc-implementation-in-namespace,-clang-diagnostic-c++17-extensions
check_skip_packages = yes
monitor_filters =
    default   ; Remove typical terminal control codes from input
    time      ; Add timestamp with milliseconds for each new line
    log2file  ; Log data to a file “platformio-device-monitor-*.log” located in the current working directory
```

**Source file to reproduce issue:**
Project available at https://github.com/FredM67/PVRouter-3-phase/tree/main/Mk2_3phase_RFdatalog_temp

**Comment by valeros** [comment]
Hi @FredM67, since you've changed the source directory, I'd recommend specifying a proper source file filter relative to the root of your project, for example:
```ini
[env]
platform = atmelavr
framework = arduino
board = uno
<...>
check_tool = cppcheck, clangtidy
check_src_filters = +<*>
; or if subfolders should be omitted
; check_src_filters = +<*.c*>
<...>
```
