### ISSUE TITLE
Creating projects taking very long or not creating at all

### ISSUE THREAD

**Issue by RaysoftTechnologiesInc** [platformio/platformio-core#4873]
I am trying to create projects on PlatformIO but nothing is happening when trying to create any of the following projects. 

1. Mbed project using the nucleof412zg
2. Nrf project unsing the Zephyr RTOS
3. ESP32 projects using the esp32-idf

I can only create an Arduino platform project.

What maybe the issue here? when creating the projects, I am just getting stuck on this screen...
![image](https://github.com/platformio/platformio-core/assets/45296244/8cdba68f-cceb-411d-82e3-2833905223f0)

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
