### ISSUE TITLE
we would suggest using the short name here (`mon swd`) as this might change through releases. Also, on a new enough BMP (v1.8 firmware or newer), `mon auto` allows what we've named "auto scan" which tries first JTAG and then SWD which opens this up to more targets.

### ISSUE THREAD

**Issue by RawRaw111** [platformio/platformio-core#4889]
we would suggest using the short name here (`mon swd`) as this might change through releases. Also, on a new enough BMP (v1.8 firmware or newer), `mon auto` allows what we've named "auto scan" which tries first JTAG and then SWD which opens this up to more targets.

_Originally posted by @dragonmux in https://github.com/platformio/platformio-core/pull/4521#discussion_r1071579962_

**Comment by ivankravets** [comment]
Yes, https://github.com/platformio/platformio-core/pull/4521#discussion_r1071579962
