### ISSUE TITLE
Help with Migrating ESP-IDF Project to PlatformIO"

### ISSUE THREAD

**Issue by nasihnazer** [platformio/platformio-core#4899]
I have been using the simple_cmux_client_main example from the [esp_modem repository](https://github.com/espressif/esp-protocols/tree/master/components/esp_modem/examples/simple_cmux_client) within ESP-IDF in Visual Studio Code. Now, I'm attempting to migrate this project to PlatformIO for better project management and IDE support.
platformIO version: 6.1.14
ESP-IDF version: 4.4.3

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
