### ISSUE TITLE
Package CDN speed, Russia

### ISSUE THREAD

**Issue by katsu-chan** [platformio/platformio-core#4909]
What kind of issue is this?

- [ ] **Question**.
      This issue tracker is not the place for questions. If you want to ask how to do something,
      or to understand why something isn't working the way you expect it to, 
      use [Community Forums](https://community.platformio.org) or [Premium Support](https://platformio.org/support)

- [ ] **PlatformIO IDE**.
      All issues related to PlatformIO IDE should be reported to the
      [PlatformIO IDE for VSCode](https://github.com/platformio/platformio-vscode-ide/issues) repository

- [ ] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

- [ ] **Feature Request**.
      Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [X] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: NixOS 23.11.6359.53a2c32bc66f (Tapir) x86_64

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.6

**Internet speed** (yandex.com/internet):

<a href="https://yandex.com/internet/"><img src="https://yandex.com/internet/informer/black/en/11482539.33-10558876.95.png"/></a>

#### ISP

asn: AS34168
name: PJSC Rostelecom
city: Vladimir
country: Russia

### Description of problem

Package download speed is too slow: 47 minutes for esp32s3 toolchain.

CDN choosing on client side would solve this problem btw

#### Steps to Reproduce

1. pio init --ide eclipse -b esp32-s3-devkitc-1

### Actual Results

Download speed is very slow

### Expected Results

Download speed is high, package downloads in under 5 minutes

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
```

**Comment by ivankravets** [comment]
Do you still experience this issue?

**Comment by ivankravets** [comment]
Please reopen if you still need help
