### ISSUE TITLE
Parse error in Azure from junit output

### ISSUE THREAD

**Issue by merijnrats** [platformio/platformio-core#4918]
What kind of issue is this?
- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

### Configuration

**Operating system**:
Windows
**PlatformIO Version**:
6.1.15
### Description of problem
there seems to be a bug with the formatting of the junit-output, there aren't any new lines or spacings and because of that Azure can't parse the xml.

#### Steps to Reproduce
1. pio test  --junit-output-path .

### Actual Results
![wrong](https://github.com/platformio/platformio-core/assets/36266304/4cd0fe92-ad65-493a-98e1-2e6150565267)

### Expected Results
![correct](https://github.com/platformio/platformio-core/assets/36266304/07cf11d9-29e0-4e15-95c0-53e156510feb)

### Additional info
I have a fix and I will try to create merge request as suggestion for devs

**Comment by ivankravets** [comment]
Spaces should not be a cause of the issue. Could you debug in depth this issue and find the problem?

**Comment by merijnrats** [comment]
![pipeline](https://github.com/platformio/platformio-core/assets/36266304/02bb436b-04f3-4a63-80fb-8f71108f33f7)
![pipelinefail](https://github.com/platformio/platformio-core/assets/36266304/9e1026c5-809f-46fb-bcac-5a4ec9d8001e)
I want to run the unittest with junit output to insert the test results into the pipeline results.  But I get a utf-8 parse error and since the current results are in 1 line I figured that would lead to the parse error which in my tested fixed it after adding newlines and whitespaces.

But i've got a workaround where I output it to json and run a custom script to parse it to junit which i can insert into Azure so it's fine,

**Comment by ivankravets** [comment]
> utf-8 parse error

UTF-8 is de-facto standard encoding. If the system does not support it, you need to tune your system. You can also add extra step and convert from UTF-8 to "encoding supported by OS".
