### ISSUE TITLE
Very very slow download (stuck at 0%)

### ISSUE THREAD

**Issue by paulrouget** [platformio/platformio-core#4924]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

macos

**PlatformIO Version** (`platformio --version`):

PlatformIO Core, version 6.1.15

### Description of problem

Stuck on this:

```
Tool Manager: Installing espressif/toolchain-xtensa-esp32s3
Downloading  [------------------------------------]    0%
```

It seems to actually download, but at 1kb/s.

### Additional info

I've read about CDN issues. But I tried to connect via a VPN, still stuck at 0%.

**Comment by ivankravets** [comment]
Hello. Currently, we don’t experience any issues. See https://community.platformio.org/t/platformio-packages-download-is-slow/40037/10

What is your country?

**Comment by paulrouget** [comment]
> What is your country?

Taiwan.

**Comment by paulrouget** [comment]
I tried download this: https://dl.registry.platformio.org/download/platformio/tool/toolchain-xtensa/2.100300.220621/toolchain-xtensa-windows_amd64-2.100300.220621.tar.gz with wget, and I get 3k/s.

**Comment by paulrouget** [comment]
Using a VPN from Korea solved the issue.

**Comment by ivankravets** [comment]
Could you try again [this link](https://dl.registry.platformio.org/download/platformio/tool/toolchain-xtensa/2.100300.220621/toolchain-xtensa-windows_amd64-2.100300.220621.tar.gz)?

**Comment by paulrouget** [comment]
Yes it's fast. thanks

**Comment by ivankravets** [comment]
Great! Sorry again for the issue and thanks for the report. If you experience this issue next time, please inform us. The situation with wars/conflicts is difficult, and it is normal to expect network issues.
