### ISSUE TITLE
ModuleNotFoundError: No module named 'serial' in ~/.platformio

### ISSUE THREAD

**Issue by torbeneims** [platformio/platformio-core#4931]
What kind of issue is this?

- [x] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**: NixOS 24.11.20240531.57610d2 (Vicuña) x86_64

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.6

### Description of problem
Project build fails with `ModuleNotFoundError: No module named 'serial'`.

#### Steps to Reproduce

1. `git clone https://gitlab.com/torben-iot/pio-ftm; git checkout 9d44c34` (Don't worry about the actual usefulness of the code)
2. (Make sure you actually want to do this) Delete `~/.platformio` 
3. `nix develop .  --experimental-features 'nix-command flakes'` (Creates a reproducible build environment with pio, esptool, etc. installed; requires NixOS or a nix-enabled system, you might be able to reproduce without this step)
4. `pio run -t upload`

### Actual Results
![image](https://github.com/platformio/platformio-core/assets/63680413/cc924dbf-7ebf-4ff5-9a45-774872d0cbb3)

### Expected Results
![image](https://github.com/platformio/platformio-core/assets/63680413/d2eab58b-2149-4340-b6fd-146345d90118)
or
![image](https://github.com/platformio/platformio-core/assets/63680413/8e3c5e55-8ebb-4611-aca3-2ff682636455)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = espidf

monitor_speed = 9600

lib_deps =
        serial


build_flags = 
        -D ARDUINO_USB_MODE=1         # \ Required for serial monitor
        -D ARDUINO_USB_CDC_ON_BOOT=1  # /
        -std=c++98
        -D CLIENT_ENABLED
```

**Source file to reproduce issue:**
```cpp
#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "nvs_flash.h"
#include "esp_netif.h"

static const char *TAG = "example";

static void event_handler(void* arg, esp_event_base_t event_base,
                          int32_t event_id, void* event_data) {
    if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t* event = (ip_event_got_ip_t*) event_data;
        char ip[16];
        esp_ip4addr_ntoa(&event->ip_info.ip, ip, sizeof(ip));
        ESP_LOGI(TAG, "got ip:%s", ip);
    } else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {
        ESP_LOGI(TAG, "disconnected");
        esp_wifi_connect();
    }
}

void wifi_init_sta() {
    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());
    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    esp_event_handler_instance_t instance_any_id;
    esp_event_handler_instance_t instance_got_ip;
    ESP_ERROR_CHECK(esp_event_handler_instance_register(WIFI_EVENT,
                                                        ESP_EVENT_ANY_ID,
                                                        &event_handler,
                                                        NULL,
                                                        &instance_any_id));
    ESP_ERROR_CHECK(esp_event_handler_instance_register(IP_EVENT,
                                                        IP_EVENT_STA_GOT_IP,
                                                        &event_handler,
                                                        NULL,
                                                        &instance_got_ip));

    wifi_config_t wifi_config = {
        .sta = {
            .ssid = "myssid",
            .password = "mypassword",
            .threshold = {
                .rssi = -127,
                .authmode = WIFI_AUTH_WPA2_PSK,
            },
        },
    };
    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());
    ESP_ERROR_CHECK(esp_wifi_connect());
}

void ftm_initiate() {
    wifi_ftm_initiator_cfg_t ftm_cfg = {
        .frm_count = 10,
        .burst_period = 100,
    };
    ESP_ERROR_CHECK(esp_wifi_ftm_initiate_session(&ftm_cfg));
}

extern "C" void app_main() {
    ESP_ERROR_CHECK(nvs_flash_init());
    wifi_init_sta();
}
```

### Additional info
* A similar issue was already mentioned as [platformio/platformio-vscode-ide#695](https://github.com/platformio/platformio-vscode-ide/issues/695)
* A workaround was presented in the forum [Trying to get core working on NixOS](https://community.platformio.org/t/trying-to-get-core-working-on-nixos/36388) but this feels hacky as the packages are normally self-managed. Still, it works, so thanks a lot
* Note that pyserial is installed in the shell context:
```bash
torben@torbens-xps ~/i/pio-ftm ((9d44c341))> pip list
Package    Version
---------- ------------
pip        23.2.1
pyserial   3.5
setuptools 68.2.2.post0
```

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/
