### ISSUE TITLE
Heltec Wireless Tracker

### ISSUE THREAD

**Issue by saxa66** [platformio/platformio-core#4938]
- [X] **Development Platform or Board**.
      All issues (building, uploading, adding new boards, etc.) related to PlatformIO development platforms
      should be reported to appropriate repository related to your hardware
      https://github.com/topics/platformio-platform

Please add the Heltec Wireless Tracker board to the library.

**Comment by ivankravets** [comment]
Please forward your issue to https://github.com/HelTecAutomation/platform-heltec-cubecell/issues
