### ISSUE TITLE
Australian download mirror incredibly slow; Breaks and tries new mirror that is faster

### ISSUE THREAD

**Issue by Raspberry-Jam** [platformio/platformio-core#4939]
- [ ] **PlatformIO Core**.
      If you’ve found a bug, please provide an information below.

------------------------------------------------------------------

### Configuration

**Operating system**:
Linux x86_64 - Fedora 40

**PlatformIO Version** (`platformio --version`):
6.1.15

### Description of problem
Downloading the package `platformio/toolchain-atmelavr @ ~1.70300.0` for the `nanoatmega328` board is incredibly slow. Checking I/O through system monitor indicates intermittent bursts of ~5KiB/s speeds. After sitting for well over 2 hours, it finally errors and switches to a new mirror, which downloads at a steady ~230KiB/s. After completing download of `toolchain-atmelavr`, it moves onto `framework-arduino-avr` presumably using the original mirror, at intermittent bursts of ~5KiB/s speeds. Have been unable to find any documentation regarding any methods to manually switch to a different mirror, or otherwise any fixes related to this issue.

#### Steps to Reproduce

1. Be in Australia
2. Run `pio init --board nanoatmega328`
3. Suffer

### Actual Results
Several hours of waiting to initialise the project, stuck staring at this:
``` 
Resolving nanoatmega328 dependencies...
Tool Manager: Installing platformio/toolchain-atmelavr @ ~1.70300.0
Downloading  [#####-------------------------------]   14%  03:07:01
Downloading...
Tool Manager: Error: Please read https://bit.ly/package-manager-ioerror
Tool Manager: Warning! Package Mirror: ('Connection broken: IncompleteRead(7662149 bytes read, 45302898 more expected)', IncompleteRead(7662149 bytes read, 45302898 more expected))
Tool Manager: Looking for another mirror...
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%
Tool Manager: toolchain-atmelavr@1.70300.191015 has been installed!
Tool Manager: Installing platformio/framework-arduino-avr @ ~5.2.0
Downloading  [#-----------------------------------]    3%  00:14:40
```

### Expected Results
Project init finished in a few minutes tops, ready for me to do work.

### Additional info
I've seen multiple problems reported about CDN issues, all with very similar symptoms. It seems as though it's widespread and there is very little that developers can do on their side to work around it. The service outage caused by this, along with no documented permanent fixes, makes PlatformIO very difficult to work with.

**Comment by ivankravets** [comment]
See https://www.capacitymedia.com/article/2d5m1eo5yohwx2zl557uo/news/indonesian-policy-delays-sea-me-we-5s-repair

They still have not fixed the issue permanently. Nevertheless, we have made some improvements in our CDN configuration. It should work fast now. Please confirm.
