### ISSUE TITLE
In file included from .pio\libdeps\development\PicoDVI - Adafruit Fork\src\libdvi\tmds_encode.S:3: .pio\libdeps\development\PicoDVI - Adafruit Fork\src\libdvi\dvi_config_defs.h:12:10: fatal error: pico/config.h: No such file or directory 12 | #include "pico/config.h" 

### ISSUE THREAD

**Issue by Carlos-TGW** [platformio/platformio-core#4946]
Anybody know how to fix this?

This is an error for the PicoDVI library downloaded from platfrom.
Here is the full build output:

Library Manager: Could not parse manifest -> Extra data: line 1 column 7 (char 6)
Verbose mode can be enabled via option
CONFIGURATION: https://docs.platformio.org/page/boards/raspberrypi/adafruit_feather_dvi.html
PLATFORM: Raspberry Pi RP2040 (1.12.0+sha.503933d) > Feather RP2040 DVI
HARDWARE: RP2040 133MHz, 264KB RAM, 8MB Flash
DEBUG: Current (blackmagic) External (blackmagic, cmsis-dap, jlink, pico-debug, picoprobe, raspberrypi-swd)
PACKAGES:-v, --verbose

framework-arduinopico @ 1.30800.0+sha.d53d003
tool-mklittlefs-rp2040-earlephilhower @ 5.100300.230216 (10.3.0)
tool-openocd-rp2040-earlephilhower @ 5.120300.240125 (12.3.0)
tool-rp2040tools @ 1.0.2
toolchain-rp2040-earlephilhower @ 5.120300.240125 (12.3.0)
Flash size: 8.00MB
Sketch size: 8.00MB
Filesystem size: 0.00MB
Maximium Sketch size: 8384512 EEPROM start: 0x107ff000 Filesystem start: 0x107ff000 Filesystem end: 0x107ff000
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Warning! Ignoring broken library manifest in C:\Users\Carlos\Desktop\Pico4.3_homeassistant\Pico4.3_homeassistant\lib\FT6X36
Library Manager: Could not parse manifest -> Extra data: line 1 column 7 (char 6)
Library Manager: Could not parse manifest -> Extra data: line 1 column 7 (char 6)
Found 73 compatible libraries
Scanning dependencies...
Library Manager: Could not parse manifest -> Extra data: line 1 column 7 (char 6)
Library Manager: Could not parse manifest -> Extra data: line 1 column 7 (char 6)
Dependency Graph
|-- lvgl @ 8.3.6
|-- PicoDVI - Adafruit Fork @ 1.1.0
|-- Crowbits_DHT20
|-- Grove - Digital Light Sensor @ 1.0.0
|-- Adafruit GFX Library @ 1.11.9
|-- SPI @ 1.0
|-- WiFi @ 1.0.0
|-- Wire @ 1.0
|-- FT6X36
|-- gt911-arduino-main
|-- XPT2046_Touchscreen
Building in release mode
Compiling .pio\build\development\FrameworkArduinoBootloader\boot2_w25q080_2_padded_checksum.S.o
Compiling .pio\build\development\src\light.c.o
Compiling .pio\build\development\src\main.cpp.o
Compiling .pio\build\development\src\no_light.c.o
Compiling .pio\build\development\src\ui.c.o
Compiling .pio\build\development\src\ui_helpers.c.o
Compiling .pio\build\development\src\ui_img_small_hum_png.c.o
Compiling .pio\build\development\src\ui_img_small_logo_png.c.o
Compiling .pio\build\development\src\ui_img_small_off_png.c.o
Compiling .pio\build\development\src\ui_img_small_temp_png.c.o
Generating linkerscript C:\Users\Carlos\Desktop\Pico4.3_homeassistant\Pico4.3_homeassistant.pio\build\development/memmap_default.ld
Compiling .pio\build\development\libf08\FreeRTOS\croutine.c.o
Compiling .pio\build\development\libf08\FreeRTOS\event_groups.c.o
Compiling .pio\build\development\libf08\FreeRTOS\heap_3.c.o
Compiling .pio\build\development\libf08\FreeRTOS\idle_task_static_memory.c.o
Compiling .pio\build\development\libf08\FreeRTOS\list.c.o
Compiling .pio\build\development\libf08\FreeRTOS\port.c.o
Compiling .pio\build\development\libf08\FreeRTOS\queue.c.o
Compiling .pio\build\development\libf08\FreeRTOS\stream_buffer.c.o
Compiling .pio\build\development\libf08\FreeRTOS\tasks.c.o
Compiling .pio\build\development\libf08\FreeRTOS\timers.c.o
Compiling .pio\build\development\libf08\FreeRTOS\variantHooks.cpp.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_disp.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_event.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_group.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_indev.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_indev_scroll.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_class.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_draw.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_pos.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_scroll.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_style.c.o
Archiving .pio\build\development\libf08\libFreeRTOS.a
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_style_gen.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_obj_tree.c.o
Indexing .pio\build\development\libf08\libFreeRTOS.a
Compiling .pio\build\development\lib3ef\lvgl\core\lv_refr.c.o
Compiling .pio\build\development\lib3ef\lvgl\core\lv_theme.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\arm2d\lv_gpu_arm2d.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_arc.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_img.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_label.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_layer.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_line.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_mask.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_rect.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_transform.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_draw_triangle.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_img_buf.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_img_cache.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\lv_img_decoder.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\pxp\lv_draw_pxp.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\pxp\lv_draw_pxp_blend.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\pxp\lv_gpu_nxp_pxp.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\pxp\lv_gpu_nxp_pxp_osa.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_draw_vglite.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_draw_vglite_arc.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_draw_vglite_blend.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_draw_vglite_line.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_draw_vglite_rect.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_vglite_buf.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\nxp\vglite\lv_vglite_utils.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_arc.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_bg.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_composite.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_img.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_label.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_layer.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_line.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_mask.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_polygon.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_rect.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_stack_blur.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_texture_cache.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sdl\lv_draw_sdl_utils.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\stm32_dma2d\lv_gpu_stm32_dma2d.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_arc.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_blend.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_dither.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_gradient.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_img.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_layer.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_letter.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_line.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_polygon.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_rect.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\sw\lv_draw_sw_transform.c.o
Compiling .pio\build\development\lib3ef\lvgl\draw\swm341_dma2d\lv_gpu_swm341_dma2d.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\layouts\flex\lv_flex.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\layouts\grid\lv_grid.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\bmp\lv_bmp.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\ffmpeg\lv_ffmpeg.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\freetype\lv_freetype.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\fsdrv\lv_fs_fatfs.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\fsdrv\lv_fs_posix.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\fsdrv\lv_fs_stdio.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\fsdrv\lv_fs_win32.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\gif\gifdec.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\gif\lv_gif.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\png\lodepng.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\png\lv_png.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\qrcode\lv_qrcode.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\qrcode\qrcodegen.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\rlottie\lv_rlottie.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\sjpg\lv_sjpg.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\libs\sjpg\tjpgd.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\lv_extra.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\fragment\lv_fragment.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\fragment\lv_fragment_manager.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\gridnav\lv_gridnav.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\ime\lv_ime_pinyin.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\imgfont\lv_imgfont.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\monkey\lv_monkey.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\msg\lv_msg.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\others\snapshot\lv_snapshot.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\themes\basic\lv_theme_basic.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\themes\default\lv_theme_default.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\themes\mono\lv_theme_mono.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\animimg\lv_animimg.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\calendar\lv_calendar.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\calendar\lv_calendar_header_arrow.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\calendar\lv_calendar_header_dropdown.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\chart\lv_chart.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\colorwheel\lv_colorwheel.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\imgbtn\lv_imgbtn.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\keyboard\lv_keyboard.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\led\lv_led.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\list\lv_list.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\menu\lv_menu.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\meter\lv_meter.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\msgbox\lv_msgbox.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\span\lv_span.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\spinbox\lv_spinbox.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\spinner\lv_spinner.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\tabview\lv_tabview.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\tileview\lv_tileview.c.o
Compiling .pio\build\development\lib3ef\lvgl\extra\widgets\win\lv_win.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_dejavu_16_persian_hebrew.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_fmt_txt.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_loader.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_10.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_12.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_12_subpx.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_14.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_16.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_18.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_20.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_22.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_24.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_26.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_28.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_28_compressed.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_30.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_32.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_34.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_36.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_38.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_40.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_42.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_44.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_46.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_48.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_montserrat_8.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_simsun_16_cjk.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_unscii_16.c.o
Compiling .pio\build\development\lib3ef\lvgl\font\lv_font_unscii_8.c.o
Compiling .pio\build\development\lib3ef\lvgl\hal\lv_hal_disp.c.o
Compiling .pio\build\development\lib3ef\lvgl\hal\lv_hal_indev.c.o
Compiling .pio\build\development\lib3ef\lvgl\hal\lv_hal_tick.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_anim.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_anim_timeline.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_area.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_async.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_bidi.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_color.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_fs.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_gc.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_ll.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_log.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_lru.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_math.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_mem.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_printf.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_style.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_style_gen.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_templ.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_timer.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_tlsf.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_txt.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_txt_ap.c.o
Compiling .pio\build\development\lib3ef\lvgl\misc\lv_utils.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_arc.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_bar.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_btn.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_btnmatrix.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_canvas.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_checkbox.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_dropdown.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_img.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_label.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_line.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_objx_templ.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_roller.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_slider.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_switch.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_table.c.o
Compiling .pio\build\development\lib3ef\lvgl\widgets\lv_textarea.c.o
Compiling .pio\build\development\lib7ac\Wire\Wire.cpp.o
Compiling .pio\build\development\libe36\SPI\SPI.cpp.o
Compiling .pio\build\development\lib2a9\Adafruit BusIO\Adafruit_BusIO_Register.cpp.o
Compiling .pio\build\development\lib2a9\Adafruit BusIO\Adafruit_I2CDevice.cpp.o
Compiling .pio\build\development\lib2a9\Adafruit BusIO\Adafruit_SPIDevice.cpp.o
Archiving .pio\build\development\lib3ef\liblvgl.a
Indexing .pio\build\development\lib3ef\liblvgl.a
Archiving .pio\build\development\lib7ac\libWire.a
Compiling .pio\build\development\lib2f9\Adafruit GFX Library\Adafruit_GFX.cpp.o
Compiling .pio\build\development\lib2f9\Adafruit GFX Library\Adafruit_GrayOLED.cpp.o
Indexing .pio\build\development\lib7ac\libWire.a
Compiling .pio\build\development\lib2f9\Adafruit GFX Library\Adafruit_SPITFT.cpp.o
Compiling .pio\build\development\lib2f9\Adafruit GFX Library\glcdfont.c.o
Archiving .pio\build\development\libe36\libSPI.a
Compiling .pio\build\development\liba13\PicoDVI - Adafruit Fork\PicoDVI.cpp.o
Indexing .pio\build\development\libe36\libSPI.a
Archiving .pio\build\development\lib2a9\libAdafruit BusIO.a
Indexing .pio\build\development\lib2a9\libAdafruit BusIO.a
Compiling .pio\build\development\liba13\PicoDVI - Adafruit Fork\libdvi\dvi.c.o
Compiling .pio\build\development\liba13\PicoDVI - Adafruit Fork\libdvi\dvi_serialiser.c.o
Compiling .pio\build\development\liba13\PicoDVI - Adafruit Fork\libdvi\dvi_timing.c.o
Compiling .pio\build\development\liba13\PicoDVI - Adafruit Fork\libdvi\tmds_encode.S.o
Compiling .pio\build\development\liba13\PicoDVI - Adafruit Fork\libdvi\tmds_encode.c.o
In file included from .pio\libdeps\development\PicoDVI - Adafruit Fork\src\libdvi\tmds_encode.S:3:
.pio\libdeps\development\PicoDVI - Adafruit Fork\src\libdvi\dvi_config_defs.h:12:10: fatal error: pico/config.h: No such file or directory
12 | #include "pico/config.h"
| ^~~~~~~~~~~~~~~
compilation terminated.
*** [.pio\build\development\liba13\PicoDVI - Adafruit Fork\libdvi\tmds_encode.S.o] Error 1

**Comment by ivankravets** [comment]
Please forward to https://community.platformio.org/c/development-platforms/17
