### ISSUE TITLE
Telemetry should be off by default

### ISSUE THREAD

**Issue by g1smo** [platformio/platformio-core#4951]
As a number of european DPAs (Data Protection Authorities) have pointed out, the use of google analytics goes against the european law of privacy protection. You can read more about that [here](https://plausible.io/blog/google-analytics-illegal) if you want.

Telemetry of any kind should be off by default. Even more so if you're sending data to giant corporate data silos. 

It's not hard to make a first run notice of the possibility to turn telemetry on and how to do that.

**EDIT**: I don't remember where I saw google analytics may have been used to collect telemetry data. I could not find information where data gets stored, whether it is shared with any third parties, who those might be etc. Is there any privacy policy regarding telemetry specifically? I can see from the source code that the data is posted to [https://collector.platformio.org/collect](https://collector.platformio.org/collect) but no further information.

**Comment by ivankravets** [comment]
We moved from GA to our own analytics infrastructure 1 year ago. See https://github.com/platformio/platformio-core/commit/cb65bdf22f2013cee5352a6d8f5ecc982fd9a1e4#diff-0c53d0b5772ef2e51a6e610d7d4402004f6dc0c4a1889f18805c04d7a6bdb192 )
