### ISSUE TITLE
please declare pip dependencies statically

### ISSUE THREAD

**Issue by branchvincent** [platformio/platformio-core#4955]
- [x] **Feature Request**.

------------------------------------------------------------------

### Configuration

**Operating system**: macOS

**PlatformIO Version** (`platformio --version`): PlatformIO Core, version 6.1.15

### Description of problem

Currently, dependencies are declared dynamically based on the caller's environment (python, os, etc):

https://github.com/platformio/platformio-core/blob/9eb6e5166d4a7c366e5cacbd39fc467c16644667/platformio/dependencies.py#L48

https://github.com/platformio/platformio-core/blob/9eb6e5166d4a7c366e5cacbd39fc467c16644667/platformio/dependencies.py#L55-L56

This makes it impossible to resolve requirements for an environment different than the current one (i.e. create a cross-platform lockfile via [`poetry`](https://github.com/python-poetry/poetry) or [`uv`](https://github.com/astral-sh/uv)). Instead, the standard way to declare these are using [PEP 508](https://peps.python.org/pep-0508/) specifiers:

```python
uvicorn==0.16.0; python_version < "3.7"
uvicorn>=0.16, <0.31; python_version >= "3.7"
chardet>=3.0.2,<6; platform_system == "Darwin" and "arm" in platform_machine
```

#### Steps to Reproduce

1. Resolve requirements on a linux machine
2. Install requirements on an M1 mac
3. See that the environment is invalid 

```console
$ docker run --rm -i --entrypoint=sh python:3.12-alpine <<EOF >requirements.txt
pip install -qqq uv
echo platformio | uv pip compile --universal -
EOF 
$ uname -sm
Darwin arm64
$ python3 -m venv .venv
$ .venv/bin/pip install --no-deps -r requirements.txt
```

### Actual Results

```console
$ .venv/bin/pip check
platformio 6.1.15 requires chardet, which is not installed.
```

### Expected Results

```console
$ .venv/bin/pip check
No broken requirements found.
```

### Additional info

I noticed this as a Homebrew maintainer, where our CI resolves python requirements on Linux for use on both Linux and macOS machines. However, this leads to a missing `chardet` for our macOS users.

**Comment by ivankravets** [comment]
Thanks for the report!
