### ISSUE TITLE
add an esprissif board ESP32-S2-DevKitC-1 v1.0

### ISSUE THREAD

**Issue by Hassanphiri** [platformio/platformio-core#4984]
I am trying to upload code into the new board I have ESP32-S2-SOLO-2

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-espressif32/issues

**Comment by Hassanphiri** [comment]
I checked that one out and it turns out that S3 doesnt support S2 . So please can you consider adding this one also, thankyou.
