### ISSUE TITLE
Python error caused by empty args

### ISSUE THREAD

**Issue by PRugg-Cap** [platformio/platformio-core#5047]
I have a custom platform and I "start debugging" from the VSCode PlatformIO extension. I get a Python error caused by the following line:

https://github.com/platformio/platformio-core/blob/c1afb364e9039fac2838bd000227b0a1871a07a6/platformio/package/commands/exec.py#L57

It seems `args` is an empty list. This is fixed by changing the condition to `if args and args[0].endswith(...)`

I note in the rest of this function, there are checks that `args` is non-empty, e.g. https://github.com/platformio/platformio-core/blob/c1afb364e9039fac2838bd000227b0a1871a07a6/platformio/package/commands/exec.py#L41

**Comment by ivankravets** [comment]
Thanks for the report! Please re-test with `pio upgrade --dev`.

**Comment by PRugg-Cap** [comment]
Thanks! All fixed
