### ISSUE TITLE
Use hooks from CVS to update library

### ISSUE THREAD

**Issue by marvinroger** [platformio/platformio-core#557]
What is the frequency of the crawler? It seems to be about an hour but my library was updated more than 2 hours ago and is still not updated on the library manager.

Here is the library: http://platformio.org/#!/lib/show/555/Homie

**Comment by ivankravets** [comment]
Please provide link to your library in our Registry.

**Comment by marvinroger** [comment]
@ivankravets sorry, of course I provided the link, but it seems like the content of the issue disappeared. I updated the first post. ;)

**Comment by ivankravets** [comment]
Crawlers syncronizes lib 1 time per 24 hours. I see a few problems with your lib:

1. You registered lib with version 1.0.0
2. Then downgraded to 0.1.0
3. Today, you again release as 1.0.0

I fixed this issue in DB. Please be careful with versioning.

**Comment by ivankravets** [comment]
See updated Registry http://platformio.org/#!/lib/show/555/Homie

**Comment by marvinroger** [comment]
Yes, I messed up. Thanks for the correction.
What about an hook (GitHub hook in our case) instead of pooling repos every 24h? This would allow for faster updates on registry and would probably reduce bandwidth server side. This could land in pio 3?

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platformio-api/issues/23
