### ISSUE TITLE
How to compile Wiring Pi to use for cross compilation on a mac

### ISSUE THREAD

**Issue by kanedo** [platformio/platformio-core#729]
I want to compile my raspberry pi projects on my mac. Whenever I try to setup a project for this using 

```
pio init -b raspberrypi_2b --ide clion
```

and then 

```
pio run
```

it tells me 

```
Error: PlatformIO does not support temporary cross-compilation for WiringPi framework. Please run PlatformIO directly on Raspberry Pi
```

but I cant find any information on how to actually to this and where to place the compiled library on my mac. What is the way to do this?
thanks

**Comment by ivankravets** [comment]
> but I cant find any information on how to actually to this and where to place the compiled library on my mac

Do you have cross toolchain for RPi with peripheral support? We have basic toolchain for ARM arch but it doesn't support perepherial :(

**Comment by ivankravets** [comment]
Temporary solution is to use http://docs.platformio.org/en/latest/plus/pio-remote.html

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-linux_arm/issues/2
