### ISSUE TITLE
extra_script preand post action doesn't work with buildprog

### ISSUE THREAD

**Issue by dehav** [platformio/platformio-core#812]
Tried to use pre/post action for 'buildprog' in an extra_script per example in doc. While it worked for 'size', it didn't work for 'buildprog'. FYI, the line

print "Current build targets", map(str, BUILD_TARGETS)

printed 

Current build targets ["buildprog", "size"]

**Comment by ivankravets** [comment]
All development platforms have been updated too. See
https://github.com/ivankravets?tab=overview&from=2016-10-27

For example, https://github.com/platformio/platform-atmelavr/commit/5b438b9b5428dcfce39b60d558bfc2447db4cc82

New development platforms will be released with PlatformIO 3.2.

**Comment by Disane87** [comment]
Issue persists. Any solutions for that?

**Comment by Disane87** [comment]
I just discovered, that this isn‘t an issue of your framework. It was a failure by me. I didn‘t changed anything in the main.cpp so the compiler doesn‘t trigger the buildprog. The size is called without an problem. 

I guess it would be great, to implement a hint like: „nothing changed, buildprog is not called“

**Comment by ivankravets** [comment]
That is normal behavior. If you need to call something "always", please use [AlwaysBuild](http://scons.org/doc/production/HTML/scons-user.html#idm139933296955680).

**Comment by Disane87** [comment]
Yep, sorry for bothing you! :)

**Comment by Piroro-hs** [comment]
Issue persists for me. I checked that I changed the content in the main.cpp...

**Comment by ivankravets** [comment]
@Piroro-hs could you share your `platformio.ini` and extra script to reproduce this issue?

**Comment by dehav** [comment]
If your asking me, no I can't. I've been removed from this for too long now. Sorry.
  ----- Original Message -----

**Comment by Piroro-hs** [comment]
Sorry, it works. I've just misunderstood that the pre callback are excuted before compiling starts.
