### ISSUE TITLE
Environments as arguments

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio-core#824]
Would be good to simplify commands that have `-e, --environments` options and allow to pass arguments as envs. For example,

* `pio run -e uno` is equal to `pio run uno`
* `pio run -e uno -e teeensy` is equal to `pio run uno teensy`
* `pio run -e release -t upload` => `pio run release -t upload`
* `pio test -e embedded` => `pio test embedded`
* `pio device monitor uno`, depends on @blackketter #787
*  etc...

**Comment by jrobeson** [comment]
in that case, maybe it'd be nice to have a separate upload command also?
`pio upload env1 env2`, but error out if there's no upload target.

**Comment by ivankravets** [comment]
@jrobeson I'm not sure that this issue will be implemented. It's just an idea.  According to `pio upload`,  we can't have this command because we have different type of upload commands: upload, program, uploadfs, etc.

**Comment by ivankravets** [comment]
There is no support from the community for this feature and documentation already is well established using `-e, --environment`.
