### ISSUE TITLE
Show vendor version of a package

### ISSUE THREAD

**Issue by Testato** [platformio/platformio-core#838]
# TODO

* https://github.com/platformio/platformio/issues/838#issuecomment-263030613
----

st-link is updated to a new 1.2.0 release, it include a year of changes and improvements
https://github.com/texane/stlink/releases/tag/1.2.0

**Comment by ivankravets** [comment]
We updated our packages a few months ago. Please check `pio platform show ststm32`

**Comment by Testato** [comment]
nope, it's the old 1.10 version

```
Package tool-stlink
-------------------
Type: uploader
Requirements: ~1.10200.0
Installed: Yes
Description: ST-Link
Url: https://github.com/texane/stlink
Version: 1.10200.1

```

**Comment by ivankravets** [comment]
PlatformIO Package Version = X.Y.Z, where X & Z is our internal data and Y is real package version in format %2d%2d%%2d.

**Comment by Testato** [comment]
Ok, thanks
I suggest to add a new row whit the original version format, example:
Package Version: 1.2.0
Platformio Version: 1.10200.1
