### ISSUE TITLE
CLI: platformio platform install espressif32 fail

### ISSUE THREAD

**Issue by rolandoo** [platformio/platformio-core#841]
Hi, how to fix this issue, thanks.

![2016-11-28 10_06_48-datalogger cpp d__onedrive_magnus_kitchendefender-palatis_mcs51_mcu_esp8266_da](https://cloud.githubusercontent.com/assets/12479703/20654334/2d8eaf8a-b553-11e6-836d-addf4466852e.png)

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/can-not-install-framework-spl/983
