### ISSUE TITLE
Produce less noisy output when -s/silent arguments are used

### ISSUE THREAD

**Issue by thomasf** [platformio/platformio-core#850]
* Don't print anything that isn't a warning or error when -s is used
* The `init` command doesnt have a `--silent` argument.

I started something here https://github.com/platformio/platformio-core/pull/849 but aborted because I'm too tired.. 

It would probably be a good thing to utilize some simple leveled logging system for all status output functions..  Either implement a small one directly in pio-core or make use of pythons build in `logging` module as long as there are no integration problems with `click`

**Comment by thomasf** [comment]
The "please wait.." line is also useless for a silent output.

**Comment by ivankravets** [comment]
> The "please wait.." line is also useless for a silent output.

Where do you see that?

**Comment by thomasf** [comment]
Sorry, I accidentally reset to the master branch instead of develop. All good now!
