### ISSUE TITLE
STM32F103 (Blue Pill) customize upload options

### ISSUE THREAD

**Issue by Split7fire** [platformio/platformio-core#855]
Programming in Atom and using Arduino framework. While I press upload, I see that program compiles fine and started to upload, but it chooses wrong configuration (thus failing to upload)
- in dfu mode it need "Alternate Setting 2" to be set
- in stlink mode it need to set address to 0x08000000

May be there are options to include to platformio.ini?

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-ststm32
