### ISSUE TITLE
Bug: TEST_FAIL() does not get picked up by pio test

### ISSUE THREAD

**Issue by eric-wieser** [platformio/platformio-core#859]
### Configuration

**Operating system**: Windows 10 x64

**PlatformIO Version** (`platformio --version`): 3.2.1

### Description of problem

Unit tests that call `TEST_FAIL()` do not acquire the red `[FAILED]` text, and the overall test is therefore marked as passing!

Seems there is a regex looking for `:FAIL: `, that should also be looking for `:FAIL\n`

**Comment by ivankravets** [comment]
Thanks, fixed in PIO Plus v0.6.8! Please run `pio update` command.
