### ISSUE TITLE
Support for Flutter Boards

### ISSUE THREAD

**Issue by kevinfoote** [platformio/platformio-core#871]
Please add support for Flutter Wireless  <http://flutterwireless.com> boards.
These are ARM based and arduino compatible devices.

<http://flutterwireless.com/index.php?route=product/product&path=59&product_id=42>

Software Compatibility	Arduino & GCC
Memory
Storage	64KB
RAM	16KB
Processor
Clockspeed	64mhz
Physical Pins	10 Digital + 5 Analog / Digital

**Comment by ivankravets** [comment]
Useful links:

* Integration with Arduino IDE: http://community.flutterwireless.com/t/getting-started-with-the-flutter-basic-and-flutter-pro/216

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-atmelsam/issues
