### ISSUE TITLE
Updated PlatformIo problem with WiFi.status() when using custom design board

### ISSUE THREAD

**Issue by williamesp2015** [platformio/platformio-core#877]
IDE 1.7.1 | Core 3.2.1  ESP8266 Custom design Board with 26 Mhz crystal and 4 Megabyte Flash
I had no problem connecting to wifi previousely with NodeMcu ESp12E board or my custom design board but now I can not connect may be because of PlatformIo version or setting in PlatformIo.ini because there is no custom  design board to select as target. Please help to solve it out.
Thank you

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-espressif8266/issues and provide `platformio.ini` contents.
