### ISSUE TITLE
espressif8266_stage fails to install on PlatformIO 3.3.0a3

### ISSUE THREAD

**Issue by rwalli** [platformio/platformio-core#878]
### Configuration

**Operating system**: OS X 10.11.6

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.3.0a3

### Description of problem

espressif8266_stage fails to install on PlatformIO 3.3.0a3

#### Steps to Reproduce

1. platformio platform install https://github.com/platformio/platform-espressif8266.git#feature/stage

### Actual Results
git version 2.11.0
Cloning into '/Users/xxx/.platformio/platforms/installing-a7czZ2-package'...
remote: Counting objects: 92, done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 92 (delta 46), reused 54 (delta 24), pack-reused 0
Unpacking objects: 100% (92/92), done.
platform-espressif8266 @ 4e64659 has been successfully installed!
Error: Unknown platform '/Users/xxx/.platformio/platforms/platform-espressif8266/.git/.piopkgmanager.json'

### Expected Results

No error.

**Comment by ivankravets** [comment]
Thank you for a report!
