### ISSUE TITLE
Add support for Sparkfun nRF52832 breakout

### ISSUE THREAD

**Issue by colinblake** [platformio/platformio-core#881]
Info and board support libraries are linked here:

https://learn.sparkfun.com/tutorials/nrf52832-breakout-board-hookup-guide?_ga=1.157336826.1789378654.1479477791

**Comment by jrobeson** [comment]
I wonder if it'd be better if the breakout board support was merged into https://github.com/sandeepmistry/arduino-nRF5/   (minus the bit about the custom bootloader), then the nrf51/nr52 codebase would be shared.

It'd require a yay or nay on https://github.com/platformio/platformio-core/issues/868#issuecomment-274421965 though

**Comment by colinblake** [comment]
That would make sense to me

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-nordicnrf52/issues/2
