### ISSUE TITLE
Debug and simulation with toolchain-atmelavr on Win8 x64

### ISSUE THREAD

**Issue by igorsoft** [platformio/platformio-core#886]
### Configuration

Win8 x64
IDE 1.7.1 | Core 3.3.0a2

### Description of problem
avr-gdb.exe NOT EXECUTABLE because of missing dlls from MinGW like 
libgcc_s_dw2-1.dll, liblzma-5.dll etc.
simulavr.exe not exists at all.

#### Steps to Reproduce

1. platformio platform install atmelavr
2. change to ..\.platformio\packages\toolchain-atmelavr\bin\ 
3. execute avr-gdb.exe or search for simulavr.exe

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr/issues
