### ISSUE TITLE
Add CI support for custom boards

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#888]
It would be very nice to have the ability to use the continuous integration tools with custom boards!

**Comment by ivankravets** [comment]
and why you can't do that?

**Comment by SRGDamia1** [comment]
I'm sorry.  Maybe it's just that I can't figure out how.  Every time I run TravisCI over the code on GitHub, it tells me that it can't find the board, even though I have the board spec in a "boards" directory there.  When I run the ci command locally (where I have the board installed in the global directory), it does work without trouble.

**Comment by SRGDamia1** [comment]
I also added an issue in the atmelavr repo to add support for our board:  https://github.com/platformio/platform-atmelavr/issues/28

**Comment by ivankravets** [comment]
> have the board installed in the global directory), it does work without trouble.

You need to do the same on CI side.

P.S: I'll add your board to our official Atmel AVR development platform and you will use it without any hooks.

**Comment by SRGDamia1** [comment]
How do you install the board on the CI side?

Thank you so much!

**Comment by ivankravets** [comment]
The board has been added to our off repo. Just use it as generic Uno or etc.

P.S: Would be thankful for any support https://pioplus.com/pricing.html
