### ISSUE TITLE
CLion code insights doesn't work inside ./lib folder

### ISSUE THREAD

**Issue by diejmon** [platformio/platformio-core#897]
### Configuration

**Operating system**: macOS 10.12.3

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.3.0a10

### Description of problem
CLion 2016.3.2 code insights doesn't work in `./lib` folder unless all files inside this folder are added to `CMakeLists.txt`. For example: `add_executable(${PROJECT_NAME} ${SRC_LIST} lib/DHT/DHT.h lib/DHT/DHT.cpp)`. But `CMakeLists.txt` is regenerated during `PLATFORMIO_REBUILD_PROJECT_INDEX` build step.  

#### Steps to Reproduce

1. `platformio init --ide clion --board uno`
2. Import project into CLion
3. Create a folder inside `./lib` folder
4. Create files inside the folder

### Actual Results
All files inside `./lib` folder appears in light grey inside CLion project navigator and code insights doesn't work.

### Expected Results
CLion recognize all files inside `./lib` folder similar to how it recognize them inside `./src` folder.

**Comment by diejmon** [comment]
I've found a workaround which is acceptable for me: Right click on `./lib` folder inside CLion and choose `Mark Directory as -> Library Files`. After this code insights are working inside `./lib`.

**Comment by ivankravets** [comment]
Please re-test with the latest PIO Core and re-init project:
```
pio upgrade --dev
pio init
```
