### ISSUE TITLE
Always recieve ISO C99 warning at build

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#898]
### Configuration

**Operating system**:  Windows 7 or TravisCI

**PlatformIO Version** (`platformio --version`): 3.2.1

### Description of problem
At every build, I receive this error:
 <command-line>:0:17: warning: ISO C99 requires whitespace after the macro name

The GCC linter in the IDE also displays this warning for every project.

The build continues successfully, but the warning is always there.

I also see the error in builds run by TravisCI.  For example:  https://travis-ci.org/EnviroDIY/EnviroDIY_Mayfly_Logger/jobs/198466734

**Comment by ivankravets** [comment]
Please move issue to related repository. Thanks!

* https://github.com/platformio/platform-atmelavr/issues

**Comment by SRGDamia1** [comment]
Is it an AtmelAVR specific problem?  It seems like a compiler problem to me because even TravisCI sees the issue and it's not writing to any hardware.

**Comment by ivankravets** [comment]
Yep, see `platform = atmelavr`. This repository is intended for PlatformIO Core issues.

**Comment by SRGDamia1** [comment]
Moved to https://github.com/platformio/platform-atmelavr/issues/29
