### ISSUE TITLE
Can support c51 series mcu?

### ISSUE THREAD

**Issue by guoqingaa** [platformio/platformio-core#907]
platformio-atom-ide Can support c51 series mcu?Hope to perfect support Keil uVision5 c51 mcu project development.

**Comment by zerog2k** [comment]
looks like there is some experimental support for sdcc and one particular board:
https://community.platformio.org/t/experimental-platform-mcs51/811/12

Not sure how functional this is yet, nor how much trouble will be to port to other boards.

**Comment by ivankravets** [comment]
Done in https://platformio.org/platforms/intel_mcs51
