### ISSUE TITLE
How to hide search panel?

### ISSUE THREAD

**Issue by katzz0** [platformio/platformio-core#910]
I don't see any way to close a search panel. Is it possible at all?

**Comment by ivankravets** [comment]
Escape?

**Comment by profra** [comment]
ESC key is working...

**Comment by katzz0** [comment]
Yes, it's true, but it isn't clear. Could you add a close button? It's better to have straightforward interface.

**Comment by ivankravets** [comment]
1. You posted the issue in the wrong repository. This repository is related to PIO Core.2
2. You mean PlatformIO IDE that is built on top of Atom text editor.
3. Please file an issue here https://github.com/atom/find-and-replace/issues
