### ISSUE TITLE
Importing a project unrecoverably wiped it!

### ISSUE THREAD

**Issue by przem312** [platformio/platformio-core#914]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [X] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.
- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:
Windows 7 64bit
**PlatformIO Version** (`platformio --version`):
IDE 1.7.3 | Core 3.2.1
### Description of problem
During importing of existing ESP8266 project something went wrong. As a result I got ENOENT: error, and everything dissappeared. There are no leftovers after my files on disk.

#### Steps to Reproduce

1. Work on sketch for couple of weeks
2. Install PlatformIO for first time.
3. Import existing project.
4. Point to directory where your project exist(ed).
5. Say goodbye to your work.

### Actual Results
Files wiped.

### Expected Results
Files not wiped.

### Additional info
Arduino 1.8.1
.ini settings to identify platforms:
[env:nodemcuv2]
platform=espressif8266
board=nodemcuv2
framework=arduino

[env:d1_mini]
platform=espressif8266
board=d1_mini
framework=arduino

[platformio]
src_dir=HelloWorld
lib_dir=~\Documents\Arduino\libraries

**Comment by ivankravets** [comment]
See above:

>  PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
https://github.com/platformio/platformio-atom-ide/issues
