### ISSUE TITLE
Cannot get list of targets as suggested by documentation

### ISSUE THREAD

**Issue by me21** [platformio/platformio-core#920]
### Configuration

**Operating system**: Windows 7 x64

**PlatformIO Version** (`platformio --version`): 3.2.1

### Description of problem

The command to get list of available targets does not work. The error message says it requires an argument.

#### Steps to Reproduce

1. Initialize a project (I used espressif8266 platform, arduino framework).
2. Open terminal.
3. PS C:\Temp\Platformio Projects\project> platformio run --target

### Actual Results

Error: --target option requires an argument

### Expected Results

List of supported targets.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
upload_resetmethod = ck
lib_deps = I2Cdevlib-MPU6050, ESPAsyncWebServer
lib_ldf_mode = deep
```

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/userguide/cmd_run.html#cmdoption-platformio-run-t
