### ISSUE TITLE
Using directory junctions has no effect for rebuilding autocomplete index

### ISSUE THREAD

**Issue by me21** [platformio/platformio-core#922]
### Configuration

**Operating system**: Windows 7 x64

**PlatformIO Version** (`platformio --version`): 3.2.1

### Description of problem

I use PlatformIO on my laptop with Windows 7. My user name contains non-latin characters. I've created a subdirectory in my home dir for PlatformIO projects. To work around the bugs triggered by non-latin paths, I've created a symlink (i.e. directory junction) to that subdirectory (C:\Temp\PlatformIO Projects).

I've created the project in C:\Temp\PlatformIO Projects\myproject. But when I rebuild C/C++ project index, I get a notification that index for project "C:\Users\Пользователь\Documents\PlatformIO Projects\myproject" will be rebuilt. Somehow PlatformIO uses real project path, even though I've opened it through symlink. Rebuild fails.

#### Steps to Reproduce

1. Create a project in a directory (I created a project for Generic ESP-01 module with 1M flash, so it might be an issue with esp8266 platform, not Platformio core, but I'm not sure).
2. Create symlink to that directory.
3. Remove project folder from Atom.
4. Open a project through symlink and trigger the rebuild of index for that project.

### Actual Results

A notification appears stating that autocomplete index for project will be rebuilt shortly, citing the path to the project. The path is real project path, regardless of created symlink.

### Expected Results

The path should contain the symlink since we've opened project through symlink.

**Comment by ivankravets** [comment]
Could you try the latest PIO Core 3.4b1 ? It should be fixed in https://github.com/platformio/platformio-core/commit/d37c6fcdce7c08c380c1ad567b9efac965a29ee6

Please reopen if you still need a help.
