### ISSUE TITLE
Implement manual package removal

### ISSUE THREAD

**Issue by me21** [platformio/platformio-core#923]
I have uninstalled atmelsam platform. However, toolchain-gccarmnoneeabi failed to uninstall automatically. After installing atmelsam platform one more time (throwing errors in process), then uninstalling it again, the package toolchain-gccarmnoneeabi was uninstalled too.

However, it might be beneficial to implement manual package installation/removal. Please consider.

**Comment by ivankravets** [comment]
See updated docs https://docs.platformio.org/en/latest/core/userguide/system/cmd_prune.html
