### ISSUE TITLE
Send text to Serial Port

### ISSUE THREAD

**Issue by formulahendry** [platformio/platformio-core#926]
# Temporary solution

- CoolTerm http://freeware.the-meiers.org/
----------

Arduino IDE and Deviot could send text to Serial Port. It seems like platformio-core cli does not support that. I plan to add this function into the [PlatformIO VSCode extension](https://marketplace.visualstudio.com/items?itemName=formulahendry.platformio). Not sure whether this function will be added in platformio-core cli in the near future, otherwise I may want to use other library to implement that. 😄

**Comment by ivankravets** [comment]
Please sorry, what do you mean? Have you seen `pio device monitor`?

**Comment by formulahendry** [comment]
Oh, really sorry. I have tried `pio device monitor` before but did not find it support to send text when it is running. Thanks for pointing out!

**Comment by cybergogo** [comment]
Hi, i'm looking for the same basic option that Arduino IDE offers. Have tried to find that in the pio device monitor section but nothing seems to look like what we need, which is to pass commands to our devices (arduino or ESPs):

`$ platformio device monitor

--- Available ports:
--- /dev/cu.Bluetooth-Incoming-Port n/a
--- /dev/cu.Bluetooth-Modem n/a
--- /dev/cu.SLAB_USBtoUART CP2102 USB to UART Bridge Controller
--- /dev/cu.obd2ecu-SPPDev n/a
Enter port name:/dev/cu.SLAB_USBtoUART
--- Miniterm on /dev/cu.SLAB_USBtoUART: 9600,8,N,1 ---
--- Quit: Ctrl+C  |  Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
Hello PlatformIO!
---
--- Ctrl+]   Exit program
--- Ctrl+T   Menu escape key, followed by:
--- Menu keys:
---    Ctrl+T  Send the menu character itself to remote
---    Ctrl+]  Send the exit character itself to remote
---    Ctrl+I  Show info
---    Ctrl+U  Upload file (prompt will be shown)
--- Toggles:
---    Ctrl+R  RTS          Ctrl+E  local echo
---    Ctrl+D  DTR          Ctrl+B  BREAK
---    Ctrl+L  line feed    Ctrl+A  Cycle repr mode
---
--- Port settings (Ctrl+T followed by the following):
---    p          change port
---    7 8        set data bits
---    n e o s m  change parity (None, Even, Odd, Space, Mark)
---    1 2 3      set stop bits (1, 2, 1.5)
---    b          change baud rate
---    x X        disable/enable software flow control
---    r R        disable/enable hardware flow control
--- exit ---`

Maybe i'm missing something, help would be greatly appreciated.

**Comment by ivankravets** [comment]
@cybergogo please note that @pyserial currently does not support sending bulk of data. See my issue/feature request https://github.com/pyserial/pyserial/issues/388

We plan to add "Serial Monitor" and other instruemnts to PIO Home soon. A temporary solution is to use free  tool Coolterm http://freeware.the-meiers.org/

**Comment by cybergogo** [comment]
> @cybergogo please note that @pyserial currently does not support sending bulk of data. See my issue/feature request [pyserial/pyserial#388](https://github.com/pyserial/pyserial/issues/388)
> 
> We plan to add "Serial Monitor" and other instruemnts to PIO Home soon. A temporary solution is to use free tool Coolterm http://freeware.the-meiers.org/

Thanks for the reply. I With hope it gets integrated asap, it would help us a loooooot :-)

**Comment by glrs** [comment]
@cybergogo I come a bit late to that, but I just faced this issue. Eventually, I was able to send data to my arduino through the pio serial monitor. I did so, by pressing ctrl+t (opening the menu), followed by another ctrl+t. Then I just typed what I wanted to send and hit enter. It worked. However, I could not see the command I was typing. This is still a bad design and error prone.

@ivankravets how is things with this issue?

**Comment by ivankravets** [comment]
Depends on https://github.com/pyserial/pyserial/issues/388

**Comment by ivankravets** [comment]
Please upgrade to the latest version via `pio upgrade --dev` and re-test with `send_on_enter` filter. See docs https://docs.platformio.org/en/latest/core/userguide/device/cmd_monitor.html

Does it work?

**Comment by brianfaires** [comment]
Working for me.  Would love to see the text as it's typed, but send_on_enter working in VScode pio plugin.

**Comment by ivankravets** [comment]
Does it work if you use `--echo` flag in a combination with filters?

**Comment by brianfaires** [comment]
Yes, echo flag works!  This is my first week with PIO, I can't believe how long I was using the Arduino IDE...  Thanks for the quick responses and contributions!
