### ISSUE TITLE
lib_deps multiline format not recognized in 3.4.0a3

### ISSUE THREAD

**Issue by zgoda** [platformio/platformio-core#931]
[According to docs](http://docs.platformio.org/en/latest/projectconf.html#lib-deps), `lib_deps` can be either comma separated list on single line or multiline with one lib name/ID per line. The latter does not work for me, I keep getting message like the one below (note line break):

```
Warning! Library `LiquidCrystal
Keypad` has not been found in PlatformIO Registry.
You can ignore this message, if `LiquidCrystal
Keypad` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.
```

Everything is fine if I put lib names in comma separated list on single line (iow `LiquidCrystal, Keypad`).

This is in core 3.4.0a3 that's installed with IDE 2.0.0-beta2.3. With core 3.3.0 everything works fine

**Comment by ivankravets** [comment]
Thanks, fixed! Please `pio upgrade`.
