### ISSUE TITLE
Navigator does not reset icon

### ISSUE THREAD

**Issue by tapvanvn** [platformio/platformio-core#932]
What kind of issue is this?

- [ # ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): 2.0.0-bega.2.3

### Description of problem
Project Navigator does not reset icon.

#### Steps to Reproduce

1. Create folder with name "A.hpp"
2. Remove "A.hpp" folder and choice "move to trash"
3. Create new file and name it "A.hpp"

### Actual Results
A.hpp file display with a folder icon.

### Expected Results
A.hpp file display with a C++ file Icon

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platformio-atom-ide/issues
