### ISSUE TITLE
Library Encoder.h ID_129 not compiled by platformio

### ISSUE THREAD

**Issue by Incalculable83** [platformio/platformio-core#938]
------------------------------------------------------------------

### Configuration

**Operating system**: Windows 10 64

**PlatformIO Version** (`platformio --version`): Core 3.4.0a4

### Description of problem
The Encoder.h library ID129 does not work when compiled for an adafruit Feather M0 Wifi in platformio, but the library works without issues in the Arduino IDE 1.8.2. First time this happened to me. I already checked with some past issues regarding the same problem with other libraries, but i can`t get the library to work with platformio.

#### Steps to Reproduce

1. Download Encoder Library by Paul Stoffregen ID_129
2. Compile example for Adafruit Feather M0; Should compile without errors
3. Sketch does not work
4. Try in Arduino IDE. Sketch works.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```
[env:adafruit_feather_m0_usb]
platform = atmelsam
board = adafruit_feather_m0_usb
framework = arduino
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
Can't reproduce this issue. Please provide detailed build log. See my:

- https://pastebin.com/gv0qRSMU
