### ISSUE TITLE
Upload keyboard shortcut is not upload

### ISSUE THREAD

**Issue by Thijxx** [platformio/platformio-core#941]
- [ ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**: Arch Linux
**PlatformIO Version** (`platformio --version`):

### Description of problem
CTRL-ALT-U is the keyboard shortcut for UPLOAD but it does something else, I do not know what

#### Steps to Reproduce
1. Press CTRL-ALT-U

### Actual Results
No upload

### Expected Results
Upload

### If problems with PlatformIO Build System:
IDE 2.0.0-beta.2
core 3.4.0a6

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platformio-atom-ide/issues
