### ISSUE TITLE
lib dependencies not calculated correctly if src_dir is changed

### ISSUE THREAD

**Issue by Spongman** [platformio/platformio-core#942]
### Configuration

**Operating system**:
win10

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 3.3.0

### Description of problem
platformio doesn't find references to built-in libraries if the src_dir is changed.

#### Steps to Reproduce

1. set src_dir = .
2. in ./Foo.ino: #include <SPI.h>
3. build

### Actual Results
````
..../Foo.ino:2:17: fatal error: SPI.h: No such file or directory
````

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[platformio]
src_dir = .
```

**Source file to reproduce issue:**
```cpp
// Foo.ino
#include <SPI.h>
```

**Comment by ivankravets** [comment]
Thanks a lot for the report!
