### ISSUE TITLE
IDE can't deal with multiples ino files yet

### ISSUE THREAD

**Issue by FernandoGarcia** [platformio/platformio-core#946]
I have a code working with Arduino IDE but it doesn't work with platformIO.

The issue with multiples ino files was pointed as solved [here](https://github.com/platformio/platformio-core/issues/130) but it doesn't work to me.

See the print screen with errors:

![platformio](https://cloud.githubusercontent.com/assets/2778501/25343572/db47534c-28e5-11e7-9985-6b55b9c88a85.PNG)

Here the full code: https://github.com/FernandoGarcia/Ferduino_with_webcontrol_beta/tree/master/Ferduino_with_webcontrol_beta

Another thing, the IDE is adding `#include <Arduino.h>` to each file on code. It's really needed?

Best regards.

**Comment by ivankravets** [comment]
Please check that you don't have "space" in a new line before prototype.
For example, 
```
void correct();
 void incorrect();
```

I remember that someone reported this bug before.

**Comment by ivankravets** [comment]
Also, we highly recommend switching from INO files to CPP. We are working on a debugger feature for PIO IDE 2.0 and it will not work with multiple INOs.

More info http://docs.platformio.org/en/latest/ide/atom.html#convert-arduino-file-to-c-manually

**Comment by ivankravets** [comment]
@valeros could you check that?

**Comment by valeros** [comment]
Hi @FernandoGarcia !
There is no an easy way to convert such a complicated project to PlatformIO. So if you are going to use PlatformIO I suggest you reorganize your project according to C/C++ guidelines (with source/header files).

**Comment by FernandoGarcia** [comment]
Ok, thanks!
