### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by DJManas** [platformio/platformio-core#950]
What kind of issue is this?

- [X] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [ ] Development Platform or Board. All issues related to Development Platforms or Embedded Boards
      should be reported to appropriate repository. 
      See full list with repositories and search for "platform-xxx" repository related to your hardware
      https://github.com/platformio?query=platform-

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**MacOS**:

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.4.0a6

I just want to ask if this is pio problem or I should contact someone else. When I create program and use e.g. A1 as analog pin number I get errors in project that A1 was not declared in this scope, but when I compile it everything is OK. I would like to know if this is pio problem or I should contact anyone else to repair it, because it is anoying.
![2017-04-27_22-57-41](https://cloud.githubusercontent.com/assets/2048276/25504301/ae59cfbc-2b9d-11e7-9079-e1cf62079f5a.png)

#### Steps to Reproduce

1.
2.
3.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by ivankravets** [comment]
Have you tried Menu: PlatformIO > Rebuild C/C++ Index ?

**Comment by DJManas** [comment]
Nope :-( since I see it is happening automatically at some point. But I have tried it now, did make clean of the project, now I see only A1 is not declared, the SHT1x.h has been found and it skipped out of the scope. 

I am just wondering couldn’t it be, because the analog pins are „declared“ when at compile using #if defined(processor type) ?

**Comment by ivankravets** [comment]
Could you provide `platformio.ini`?

**Comment by DJManas** [comment]
Sure
[platformio.ini.zip](https://github.com/platformio/platformio-core/files/964270/platformio.ini.zip)

**Comment by ivankravets** [comment]
This is a bug, PIO does not handle `env_default` from config. I'll fix it. Thanks.

**Comment by DJManas** [comment]
Thank you
