### ISSUE TITLE
"pio test" does not pick up libs used in test

### ISSUE THREAD

**Issue by tehnorm** [platformio/platformio-core#953]
### Configuration

**Operating system**: macOS Sierrra - v 10.2.4

**PlatformIO Version** (`PlatformIO, version 3.4.0a8`):

### Description of problem

It seems that the `pio test` command does not correctly include `libs`.

#### Steps to Reproduce

1. Create a test file
2. Create a lib in the `/libs` folder, say `mylib.h` `mylib.cpp`
3. Include the lib in `some_test.cpp`

### Actual Results

`test/some_test/some_test.cpp:4:16: fatal error: mylib.h: No such file or directory`

### Expected Results

The build to run and create the test build.

**Comment by ivankravets** [comment]
A temporary solution is one of:

* Add library to [dependency list](http://docs.platformio.org/page/projectconf/section_env_library.html#lib-deps) 
* Include the main header from a library in one of project files from `src` folder
