### ISSUE TITLE
BUG: Debugging fails with a space in path to project

### ISSUE THREAD

**Issue by tvr3000** [platformio/platformio-core#954]
**OS X 10.12.1**:

**PlatformIO, version 3.4.0b1** 

#### Steps to Reproduce

1. Make a project folder with a space in it
2. Try to debug
3.

### Actual Results
Eror with non descriptive message, debugigng failes

### Expected Results
Debugger

**Comment by ivankravets** [comment]
Please run `pio update` and re-test. Thanks!
