### ISSUE TITLE
Keyboard/HID library not working with PlatformIO.

### ISSUE THREAD

**Issue by simonj0** [platformio/platformio-core#955]
### Configuration

**Operating system**: Windows 10

**PlatformIO Version** (`platformio --version`): `PlatformIO, version 3.4.0b1`

### Description of problem
The Keyboard/HID library does not work after compiling & uploading with platformio, although the same sketch file works with the standard Arduino IDE.

#### Steps to Reproduce

1. Compile & run the code below both in the standard Arduino IDE and from PlatformIO.

### Actual Results
The windows key is pressed after running from the Arduino IDE, but not when run from PlatformIO.

### Expected Results
The windows key should be pressed after both compilations, since it's the same code.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:micro]
platform = atmelavr
board = micro
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
#include <Keyboard.h>

void setup() {
  Keyboard.begin();
}

void loop() {
  delay(500);

  Keyboard.press(KEY_LEFT_GUI);
  delay(100);
  Keyboard.releaseAll();

  for(;;);
}
```

**Comment by simonj0** [comment]
Alright, the issue seems to be on my side. I tried the same with another Arduino of the same model, and that one seems to work. I suppose it was just faulty hardware, not an issue with PIO; Solved.

**Comment by Blockguy24** [comment]
I don't think this is faulty hardware, I have the same problem on PlatformIO version 4.0.3
First, I upload this code to the Arduino using the Arduino IDE:
```c++
#include <Arduino.h>
#include <Keyboard.h>

void setup() {
  pinMode(6, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  if (!digitalRead(6))
  {
    Keyboard.print("a");
  }
}
```
Then I run this command to read the flash back from the Arduino:
`"C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude" -C"C:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf" -v -patmega32u4 -cavr109 -PCOM17 -b57600 -D -U flash:r:arduino-ide.hex:i`

I repeated this for the PlatformIO IDE and saw that the .hex files produced were completely different.

[Hex files.zip](https://github.com/platformio/platformio-core/files/3701969/Hex.files.zip)

Also, looking in Devices and Printers, the device is recognized differently:
Arduino IDE:
![image](https://user-images.githubusercontent.com/21016331/66389245-a846c800-ea13-11e9-84b9-c48eb1d0fecb.png)
![image](https://user-images.githubusercontent.com/21016331/66389434-15f2f400-ea14-11e9-8bce-ff7ad90a077d.png)

PlatformIO IDE:
![image](https://user-images.githubusercontent.com/21016331/66389301-cf9d9500-ea13-11e9-8bd2-03c0a87e6c2f.png)
![image](https://user-images.githubusercontent.com/21016331/66389340-e17f3800-ea13-11e9-82fd-6f19eeab4b9c.png)

When it is recognized as a bootloader device, it is still able to run the sketch, except HID functionality does not work.

**Comment by Blockguy24** [comment]
Sorry about the previous post, I'll make a new issue as this may not be exactly the same issue.
