### ISSUE TITLE
[Feature Request] Add support for Microsoft Azure - MXChip IoT Developer Kit

### ISSUE THREAD

**Issue by formulahendry** [platformio/platformio-core#963]
Here is the the page about Microsoft Azure - MXChip IoT Developer Kit: https://microsoft.github.io/azure-iot-developer-kit/  and the board info: https://raw.githubusercontent.com/VSChina/azureiotdevkit_tools/master/package_azureboard_index.json

Two requests here:

1. Could we add the board support in http://platformio.org/boards? So that user could just use command like `platformio init --board azure-iot-devkit` to initialize the environment
2. Before it is officially supported in http://platformio.org/boards, is there a way for users to do some manual work to make user could build, upload DevKit in PlatformIO? Just like Arduino IDE, it could add an Additional Boards Manager URLs:
![image](https://cloud.githubusercontent.com/assets/1050213/26088698/31a1e332-3a2b-11e7-8725-571d9dc3da7c.png)

Thanks in advance! 😃 Let me know whether I need to add more info.

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platform-ststm32/blob/develop/boards/mxchip_az3166.json
