### ISSUE TITLE
Generating build flags does not work when inheriting from environments

### ISSUE THREAD

**Issue by eric-wieser** [platformio/platformio-core#964]
The following `platformio.ini`

```ini
[git]
build_flags = !python get_git_defines.py

[env:mega_pic32]
platform = microchippic32
board = mega_pic32
framework = arduino
build_flags = ${git.build_flags} -Wall -Werror -Wpedantic
```

Results in calling `python get_git_defines.py -Wall -Werror -Wpedantic`. What it should do is invoke the script to produce `git,build_flags`, and then substitute

**Comment by ivankravets** [comment]
Fixed in PlatformIO Core 3.4.1
