### ISSUE TITLE
PIO doesn't wait long enough for port open/close (SAMD21G)

### ISSUE THREAD

**Issue by SRGDamia1** [platformio/platformio-core#965]
What kind of issue is this?

- [*] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:  Windows 7 SP1

**PlatformIO Version** (`platformio --version`):  v3.4.0b2 (within Atom: 2.0.0b.3)

### Description of problem
When attempting to upload to an SAMD21 board (Adafruit Feather M0), the upload force closes the port, but does not wait long enough for Windows to actually close and re-open the serial port and so the upload fails.  Sometimes Windows is speedy enough with the ports, but other times it misses.

#### Steps to Reproduce

1.  Create sketch for Adafruit Feather M0
2.  Upload using standard upload button in Atom (pio run --target upload)

### Actual Results
Sometimes works without error
Other times, the port is forced closed, but before Windows has close the port, the uploader detects the old port as if it was the new port and attempts to upload to just as it is closing, causing a failure

### Expected Results
Successful upload

### Additional info
The Arduino IDE does not seem to have trouble with the port open/close and the speed of the port open/close on my system seems to depend some on what code the M0 had been running.

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelsam/issues

**Comment by SRGDamia1** [comment]
Sorry!  Done.
