### ISSUE TITLE
internet_on isn't a great test for connectivity

### ISSUE THREAD

**Issue by seaduck13** [platformio/platformio-core#968]
- [X] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

**Operating system**:

**PlatformIO Version** (`platformio --version`):

### Description of problem

When behind a firewall, like most professional institutions, it is difficult to get an internet connection for the platformio upgrade/updates.  Checking 8.8.8.8 isn't a great way to see if there is a connection, especially when certain ports are closed for security reasons. 

This is found in util.py

**Comment by ivankravets** [comment]
Your proposition?

**Comment by seaduck13** [comment]
Why not check for connections to the site/s that are queried for the package updates?  This seems like it'd be more direct and check to make sure that the updates could actually occur, especially since your internet could be on and some other resource could be down.

Alternatively, you could check for a local DNS response for the repo/hosting sites.  That'd be similar to the port 53 connection to 8.8.8.8, correct?

**Comment by ivankravets** [comment]
Thanks!
