### ISSUE TITLE
Errors in header files.

### ISSUE THREAD

**Issue by portew** [platformio/platformio-core#970]
I have error in linter when i using in function located into .h/.hpp file variables from main.cpp or another files. In compilation is all ok but in liner i have errors. For example:
main.cpp :

```
int abc = 1;
#include test.hpp
void setup()
{
.....
test();
}
```
test.hpp
```
void test()
{
abc + 10; //now I have error is abc is not declared. 
}
```

**Comment by ivankravets** [comment]
Could you reproduce this issue with PlatformIO IDE for VSCode? http://platformio.org/platformio-ide

**Comment by ivankravets** [comment]
Please reopen if you still need help
