### ISSUE TITLE
Linter counting library pragma messages as errors

### ISSUE THREAD

**Issue by jfro** [platformio/platformio-core#971]
### Configuration

**Operating system**: macOS Sierra 10.12.5

**PlatformIO Version** (`platformio --version`): 3.4.0b9

### Description of problem
I'm using FastLED library 3.1.4 building against ESP8266 (Adafruit Feather Huzzah) which produces 2 pragmas in FastLED, one is just the version (#pragma message "FastLED Version 3.001.003") and another due to no hardware SPI pins defined (#pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output")

Problem is these are showing as errors in the bottom status bar. Clicking on it also won't show anything in the list. Only way I found out what they were was using the "Linter Ui Default: Next" action.

#### Steps to Reproduce

1. Create new project, preferably against an ESP boards or other without SPI pins defined
2. Add FastLED library globally (not sure if locally is the same)
3. Wait for linter to run

### Actual Results
2 errors in linter status, clicking produces no linter list. Expanding linter UI also lists nothing.

### Expected Results
1. Linter should maybe count these as "infos" not errors
2. Linter should list them in the actual list
3. Or possibly not show any linter issues in libraries (or option not to show library linting)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:huzzah]
platform = espressif8266
board = huzzah
framework = arduino
```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>
#include "FastLED.h"
void setup() {
}
void loop() {
}
```

**Comment by ivankravets** [comment]
Could you reproduce this issue with PlatformIO IDE for VSCode?

**Comment by ivankravets** [comment]
Please reopen if you still need help

Also, check PlatformIO IDE for VSCode https://platformio.org/get-started/ide?install=vscode
