### ISSUE TITLE
ATxmega128A1U support

### ISSUE THREAD

**Issue by Xav83** [platformio/platformio-core#972]
Hi,

I've looked on the forum without success so I come here to ask you if there is a chance that you'll support the board ATxmega128A1U. Indeed I use this board with an Atmel project using C and C++11 and I would really like to use your PlatformIO on this project.

Thanks in advance for your time,
Xav.

------------------------------------------------------------------

### Configuration

**Operating system**:

Windows 10 64 bits, Atmel Studio 7, avr-gcc and avr-g++

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr/issues
