### ISSUE TITLE
Error while uploading to target (STM32F407, STM32F103)

### ISSUE THREAD

**Issue by Split7fire** [platformio/platformio-core#977]
While trying to upload using stlink in atom (all updates), following error comes out: 

> st-flash: error while loading shared libraries: libstlink-shared.so.1: cannot open shared object file: No such file or directory
> *** [upload] Error 127

------------------------------------------------------------------

### Configuration

**Operating system**: Ubuntu x86_64 17.04

**PlatformIO Version** (`platformio --version`): latest

**Comment by ivankravets** [comment]
Please move this issue to https://github.com/platformio/platform-ststm32/issues

**Comment by 1am** [comment]
@ivankravets Where was this issue moved? I can't find it in the repo you mentioned and the issue is still there as I'm experiencing it now.

**Comment by ivankravets** [comment]
Please open new here https://github.com/platformio/platform-ststm32/issues

**Comment by 1am** [comment]
You marked is as moved, thus I'm asking where. Don't want to report issues which are already there.

**Comment by ivankravets** [comment]
There is no problem with PlatformIO Core

**Comment by ivankravets** [comment]
Duplicate of https://github.com/platformio/platform-ststm32/issues/58
