### ISSUE TITLE
Source files with extension *.cc do not compile on Linux

### ISSUE THREAD

**Issue by Mindavi** [platformio/platformio-core#983]
### Configuration

**Operating System**: Linux Ubuntu Trusty

**PlatformIO Version** (`platformio --version`): 3.3.1

### Description of problem
When I have files that have the extension *.cc, they will not be built by platformio.

#### Steps to Reproduce
1. Initialize platformio project
2. Put main.cc file in src folder
3. Run `platformio run`

### Actual Results
There is an error which says I have to put source files in the /src folder

### Expected Results
The project compiles and there are no problems

### Additional info
On Windows with the IDE there is no problem with *.cc files, but on Linux there is.
To see the problem happening, see [this ](https://github.com/Mindavi/CactusJump/commit/f6eb579463759bce4a84676024fd84739e6b722b) commit. This one builds, the one before it does not.

**Comment by ivankravets** [comment]
PIO IDE uses built-in the latest PIO Core 3.4 which has not been released yet. See http://docs.platformio.org/en/latest/installation.html#development-version
