### ISSUE TITLE
CLI keeps upgrading itself every time it is executed

### ISSUE THREAD

**Issue by streamliner18** [platformio/platformio-core#990]
Each time I'm using the `platformio` cli, either from a shell or PlatformIO IDE, it attempts to upgrade itself and ALL its platforms / libraries just as it would by typing `pio upgrade; pio update`. It has been disruptive to my workflow, as it takes a long time to upgrade and it prevents me from doing anything with the CLI until the upgrade is complete.

My settings for the relevant parts are shown below:

Name | Value
--- | ---
auto_update_libraries | No
auto_update_platforms | No
check_libraries_interval | 30 [7]
check_platformio_interval | 30 [3]
check_platforms_interval | 30 [7]
enable_cache | Yes

**Comment by ivankravets** [comment]
http://docs.platformio.org/en/latest/faq.html#multiple-pio-cores-in-a-system
