### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by daecepi** [platformio/platformio-core#994]
### Configuration

**Operating system**:
Windows 8.1

**PlatformIO Version** (`platformio --version`): 2.0 beta (and in the version before i had the same issue)

### Description of problem
Problems when trying to compile the code in platformio

#### Steps to Reproduce
1.After getting every part of the code wrtten, i press the compile buttton

### Actual Results
Image of my results:
![image](https://user-images.githubusercontent.com/19631029/27940427-2ab78a30-6290-11e7-833b-8422599675fd.png)

### Expected Results
Compiling succesfull or something like that

### If problems with PlatformIO Build System:
[env:atmelavr_arduino_uno_board]
platform = atmelavr
framework = arduino
board = uno
upload_speed = 115200
targets = upload

**Source file to reproduce issue:**
#include <Arduino.h>

int led = 13;

void setup(/* arguments */) {
  //Serial.begin(9600);
  pinMode(led, OUTPUT);
}

void loop() {
  delay(1000);
  digitalWrite(led, HIGH);
  delay(1000);
  digitalWrite(led, LOW);
}

**Comment by ivankravets** [comment]
Could you reproduce this issue when open PlatfomIO IDE Terminal and type `pio run`?

**Comment by daecepi** [comment]
Yes
![image](https://user-images.githubusercontent.com/19631029/27982107-f3b1cd4a-635f-11e7-9497-af61a1198a02.png)
This occurs when running from the command's tool

And when i try to change the board, the problem seems to change
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_speed = 115200

![image](https://user-images.githubusercontent.com/19631029/27982273-dd3c49e2-6363-11e7-8afc-e15166beeb74.png)

**Comment by ivankravets** [comment]
Could you try to remove `.platformio` folder from HOME directory and start build again?

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by daecepi** [comment]
There is no .platformio folder in the project's folder, and these are the captures from the commands you requested:
![image](https://user-images.githubusercontent.com/19631029/27999513-a8b59166-64e3-11e7-83d3-aba3e50651af.png)
![image](https://user-images.githubusercontent.com/19631029/27999523-baab42f8-64e3-11e7-8bbb-a6ac5920ef2c.png)
![image](https://user-images.githubusercontent.com/19631029/27999535-e349ba8c-64e3-11e7-94e7-b2d522df8b78.png)
As you see the command "pip" was not recongnized from a normal opened terminal (by the way i tried the command pio as well, and neither does it)

Thank's again

**Comment by daecepi** [comment]
1 correction when i run the command "platformio --version" this is the output: PlatformIO, version 3.4.1a5

**Comment by ivankravets** [comment]
Could you try to create project in "Documents/Test" folder  (without spaces) and try again. Just for test

**Comment by daecepi** [comment]
I tried it as you mentioned and the problem remains, i have a question is necesary to have the board connected for compilation purposes?

![image](https://user-images.githubusercontent.com/19631029/28049117-cdf0b546-65ba-11e7-828c-ed59663215e4.png)

**Comment by daecepi** [comment]
And when running from the command line:

![image](https://user-images.githubusercontent.com/19631029/28049139-f2fb2722-65ba-11e7-84fd-177d8913b8a2.png)

**Comment by ivankravets** [comment]
Do you have antivirus in a system? Maybe, McAfee?

**Comment by daecepi** [comment]
Problem solved, i installed LLVM software with the version recommended for platformio installing tutorials.

Somehow the version of the software was newer, eventhough i had it installed with the right version.

Everything works fine now, except for the serial monitor which shows an empty list in the ports selection and when trying to upload  shows me the message:
![image](https://user-images.githubusercontent.com/19631029/28511084-2f246a96-7011-11e7-9c9a-76f1c7799dbf.png)

Any suggestions?
Thanks in advance

**Comment by ivankravets** [comment]
Do you see ports in OS Device Manager (COM section)?

**Comment by daecepi** [comment]
I forgot to mention i changed the OS recently, now is a windows 10 home single language (because of some problems i had on the last one, aside from that problem all software worked properly by the way)

Now the ports appear to be identified like this:
![image](https://user-images.githubusercontent.com/19631029/28525727-c3d1a9b8-704a-11e7-9275-cb8df98254f5.png)

always varying last number of the port section:
Port_#0003.Hub_#0006
Port_#0004.Hub_#0006
.
.
.

**Comment by ivankravets** [comment]
Could I close this issue?

**Comment by ivankravets** [comment]
Please provide an output from system Terminal `cmd`
```
echo %PATH%
python --version
pip --version
pip list
```

**Comment by daecepi** [comment]
Yes, sure
