### ISSUE TITLE
mbed-filesystem compile error

### ISSUE THREAD

**Issue by fidomax** [platformio/platformio-core#998]
------------------------------------------------------------------

### Configuration

**Operating system**:Ubuntu 17.04 x64

**PlatformIO Version** (`platformio --version`): PlatformIO, version 3.4.1a5

### Description of problem

Failed to compile mbed-filesystem

#### Steps to Reproduce

1. Create any mbed project from example
2. Add #include "FATFileSystem.h" at main.cpp
3. Try to compile

### Actual Results

[Mon Jul 10 12:47:23 2017] Processing nucleo_f411re (upload_protocol: stlink; platform: ststm32; board: nucl
eo_f411re; framework: mbed)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
Collected 8 compatible libraries
Looking for dependencies...
￼
Library Dependency Graph
|-- <mbed-filesystem>
|-- <mbed-rtos>
Compiling .pioenvs/nucleo_f411re/src/main.o
Compiling .pioenvs/nucleo_f411re/lib/filesystem/Dir.o
Compiling .pioenvs/nucleo_f411re/lib/filesystem/File.o
In file included from /home/maximus/.platformio/packages/framework-mbed/features/filesystem/Dir.cpp:17:0:
/home/maximus/.platformio/packages/framework-mbed/features/filesystem/Dir.h:20:35: fatal error: filesystem/F
ileSystem.h: No such file or directory
#include "filesystem/FileSystem.h"
^
compilation terminated.
Linter
Severity 	Provider 	Description	Line 
Git
GitHub (preview)
PIO Buildsrc/main.cpp0208:1(1, 26)
LFUTF-8C++0 files

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
Insert here...
```

**Source file to reproduce issue:**
```cpp
Insert here...
```

**Comment by valeros** [comment]
Please move issue to https://github.com/platformio/platform-ststm32
