### ISSUE TITLE
Error finding serial-ports on Win8 (since last upgrade)

### ISSUE THREAD

**Issue by IoTAdri** [platformio/platformio-core#999]
- [X] PlatformIO Core. If you’ve found a bug, please provide an information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Configuration

Win8.1

**PlatformIO Version** (`platformio --version`):

### Description of problem
Cant find list of Serial-ports (see picture)

#### Steps to Reproduce

1. Open Serial-terminal

### Additional info
![platformioerror](https://user-images.githubusercontent.com/16754039/28286522-bdc18c4e-6b38-11e7-9a13-8261d646ae27.png)

**Comment by IoTAdri** [comment]
could it be that core 3.4.**1a6** is installed (see picture) and the errormessage states that "3.4.**1a5** distribution is required by the application".. how to correct this? please advise

**Comment by ivankravets** [comment]
1. Please opem system Terminal `cmd` (not in IDE), and check that you don't have global PIO Core. Run `pip uninstall platformio`. If you see error that `pip` not found or etc, that is OK.
2. Remove `C:users\adri\.platformio\penv` folder and restart Atom
